### ISSUE TITLE
Deadlock occurred while executing queries concurrently

### ISSUE THREAD

**Issue by winter7** [ClickHouse/ClickHouse#10452]
**Describe the unexpected behaviour**
I executed the query at 40 concurrency and clickhouse-server hung up.

**How to reproduce**
* version 19.14.7.15
* query pattern:
```
SELECT 
    a, 
    b, 
    c,  
    sum(d) AS d_sum, 
    sum(e) AS e_sum, 
    round(sum(f), 2) AS f_sum
FROM table AS t
WHERE (a = 1) AND (b = 2) AND (c = 3) AND (g = 4) AND (event_date >= '2019-07-02 04:00:00') AND (event_date <= '2019-07-30 14:00:00')
GROUP BY a,b,c
```
I can reproduce the deadlock executing concurrent queries.
* Non-default settings
```
config.xml
mark_cache_size=5368709120

users.xml
optimize_skip_unused_shards=1
max_memory_usage=10000000000
use_uncompressed_cache=0
```
**Error message and/or stacktrace**
I used gdb to see threads, found lots of  `__lll_lock_wait()`.
Mainly these two kinds of threads deadlocked:
```
(gdb) thread 2
[Switching to thread 2 (Thread 0x7fe5b4641700 (LWP 12912))]
#0  0x00007fea7e7ec50d in __lll_lock_wait () from /lib64/libpthread.so.0
(gdb) bt
#0  0x00007fea7e7ec50d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007fea7e7e7e5b in _L_lock_883 () from /lib64/libpthread.so.0
#2  0x00007fea7e7e7d28 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x000055a92ac973c3 in DB::ProcessList::insert(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::IAST const*, DB::Context&) ()
#4  0x000055a92ad083a5 in ?? ()
#5  0x000055a92ad087ac in DB::executeQuery(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) ()
#6  0x000055a9279b3410 in DB::TCPHandler::runImpl() ()
#7  0x000055a9279b3dab in DB::TCPHandler::run() ()
#8  0x000055a92b790b40 in Poco::Net::TCPServerConnection::start() ()
#9  0x000055a92b79125d in Poco::Net::TCPServerDispatcher::run() ()
#10 0x000055a92ce74571 in Poco::PooledThread::run() ()
#11 0x000055a92ce7231c in Poco::ThreadImpl::runnableEntry(void*) ()
#12 0x000055a92d5e7b60 in ?? ()
#13 0x00007fea7e7e5e65 in start_thread () from /lib64/libpthread.so.0
#14 0x00007fea7e10288d in clone () from /lib64/libc.so.6
```
and
```
(gdb) frame 3
#3  0x000055a92d61b393 in unw_step ()
(gdb) bt
#0  0x00007fea7e7ec50d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007fea7e7e9172 in pthread_rwlock_rdlock () from /lib64/libpthread.so.0
#2  0x000055a92d62287f in ?? ()
#3  0x000055a92d61b393 in unw_step ()
#4  0x000055a92d61b4b0 in unw_backtrace ()
#5  0x000055a92793e1e0 in StackTrace::StackTrace() ()
#6  0x000055a92b4b8d50 in Coordination::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int) ()
#7  0x000055a92b4b9643 in Coordination::Exception::Exception(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#8  0x000055a92b4c1696 in zkutil::ZooKeeper::create(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) ()
#9  0x000055a92ae2fba4 in DB::StorageReplicatedMergeTree::createLogEntryToMergeParts(std::shared_ptr<zkutil::ZooKeeper>&, std::vector<std::shared_ptr<DB::MergeTreeDataPart const>, std::allocator<std::shared_ptr<DB::MergeTreeDataPart const> > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, DB::ReplicatedMergeTreeLogEntryData*) ()
#10 0x000055a92ae52280 in DB::StorageReplicatedMergeTree::mergeSelectingTask() ()
#11 0x000055a92b1312d9 in DB::BackgroundSchedulePoolTaskInfo::execute() ()
#12 0x000055a92b131c1a in DB::BackgroundSchedulePool::threadFunction() ()
#13 0x000055a92b131c9a in ?? ()
#14 0x000055a92797938c in ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>) ()
#15 0x000055a92d5e7b60 in ?? ()
#16 0x00007fea7e7e5e65 in start_thread () from /lib64/libpthread.so.0
#17 0x00007fea7e10288d in clone () from /lib64/libc.so.6
```

**Additional context**

**Comment by alexey-milovidov** [comment]
First recommendation is to update to 19.14.9.
