### ISSUE TITLE
CentOS7.8 arm cpu, try catch invalid

### ISSUE THREAD

**Issue by jch0629** [ClickHouse/ClickHouse#12483]
branch：v20.5.2.7-stable 

below is the exception call stack，#12 TCPHandler::runImpl() have try catch,but not effective:

```
#0  0x0000ffffbe2f5238 in raise () from /lib64/libc.so.6
#1  0x0000ffffbe2f68b0 in abort () from /lib64/libc.so.6
#2  0x000000000b063b8c in terminate_handler() () at /home/jch/ck/ClickHouse/base/daemon/BaseDaemon.cpp:356
#3  0x000000000c8a68c0 in std::__terminate(void (*)()) (func=0x0) at /home/jch/ck/ClickHouse/contrib/libcxxabi/src/cxa_handlers.cpp:59
#4  0x000000000c8a60e0 in __cxa_rethrow () at /home/jch/ck/ClickHouse/contrib/libcxxabi/src/cxa_exception.cpp:616
#5  0x000000000812770c in DB::getCurrentExceptionMessage(bool, bool, bool) (with_stacktrace=true, check_embedded_stacktrace=false, with_extra_info=true)
    at /home/jch/ck/ClickHouse/src/Common/Exception.cpp:237
#6  0x000000000b063a70 in terminate_handler() () at /home/jch/ck/ClickHouse/base/daemon/BaseDaemon.cpp:341
#7  0x000000000c8a68c0 in std::__terminate(void (*)()) (func=0x0) at /home/jch/ck/ClickHouse/contrib/libcxxabi/src/cxa_handlers.cpp:59
#8  0x000000000c8a5dec in __cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*) (exception_header=0xffff20406880)
    at /home/jch/ck/ClickHouse/contrib/libcxxabi/src/cxa_exception.cpp:152
#9  0x000000000c8a5d68 in __cxa_throw (thrown_object=<optimized out>, tinfo=0x48789a0 <typeinfo for DB::Exception>, dest=<optimized out>)
    at /home/jch/ck/ClickHouse/contrib/libcxxabi/src/cxa_exception.cpp:283
#10 0x000000000b2e9998 in DB::Context::setUser(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Net::SocketAddress const&) (this=<optimized out>, name=..., 
    password=..., address=...) at /home/jch/ck/ClickHouse/src/Interpreters/Context.cpp:683
#11 0x000000000bae4780 in DB::TCPHandler::receiveHello() (this=0xffff20d40000) at /home/jch/ck/ClickHouse/src/Server/TCPHandler.cpp:740
#12 0x000000000bae1900 in DB::TCPHandler::runImpl() (this=0xffff20d40000) at /home/jch/ck/ClickHouse/src/Server/TCPHandler.cpp:86
#13 0x000000000baea670 in DB::TCPHandler::run() (this=0xffff20d40000) at /home/jch/ck/ClickHouse/src/Server/TCPHandler.cpp:1195
#14 0x000000000bdf5800 in Poco::Net::TCPServerConnection::start() (this=0x0) at /home/jch/ck/ClickHouse/contrib/poco/Net/src/TCPServerConnection.cpp:43
#15 0x000000000bdf5cd4 in Poco::Net::TCPServerDispatcher::run() (this=0xfffcc06a0040)
    at /home/jch/ck/ClickHouse/contrib/poco/Net/src/TCPServerDispatcher.cpp:114
#16 0x000000000c074d38 in Poco::PooledThread::run() (this=0xffff20014600) at /home/jch/ck/ClickHouse/contrib/poco/Foundation/src/ThreadPool.cpp:199
#17 0x000000000c072cfc in Poco::ThreadImpl::runnableEntry(void*) (pThread=<optimized out>)
    at /home/jch/ck/ClickHouse/contrib/poco/Foundation/src/Thread_POSIX.cpp:345
#18 0x0000ffffbe757d38 in start_thread () from /lib64/libpthread.so.0
#19 0x0000ffffbe39f5f0 in thread_start () from /lib64/libc.so.6
```

**Comment by miaojianxin** [comment]
I got the same error with you， the clickhouse is 20.8.6.6 lts  on aarch64，    have you resolved it？

**Comment by zeekling** [comment]
20.8.7.15 has the same error

**Comment by alexey-milovidov** [comment]
I confirm - ARM versions are not production ready.

**Comment by zeekling** [comment]
> I confirm - ARM versions are not production ready.

When will the ARM version be available?

**Comment by alexey-milovidov** [comment]
No one is currently assigned to this task, but we keep it in mind.

**Comment by zeekling** [comment]
Thanks .
