### ISSUE TITLE
<Error> MySQLHandler: DB::Exception: Cannot read all data. Bytes read: 0. Bytes expected: 3

### ISSUE THREAD

**Issue by xiedeyantu** [ClickHouse/ClickHouse#12701]
clickhouse cluster error log keeps printing the log：

2020.07.23 14:44:17.557671 [ 38 ] {} <Error> MySQLHandler: DB::Exception: Cannot read all data. Bytes read: 0. Bytes expected: 3.
2020.07.23 14:44:17.557760 [ 41 ] {} <Warning> TCPHandler: Client has not sent any data.
2020.07.23 14:44:18.389191 [ 37 ] {} <Warning> TCPHandler: Client has not sent any data.
2020.07.23 14:44:18.390093 [ 39 ] {} <Error> MySQLHandler: DB::Exception: Cannot read all data. Bytes read: 0. Bytes expected: 3.
2020.07.23 14:44:19.382463 [ 38 ] {} <Error> MySQLHandler: DB::Exception: Cannot read all data. Bytes read: 0. Bytes expected: 3.
2020.07.23 14:44:19.382595 [ 41 ] {} <Warning> TCPHandler: Client has not sent any data.
2020.07.23 14:44:21.718317 [ 39 ] {} <Error> MySQLHandler: DB::Exception: Cannot read all data. Bytes read: 0. Bytes expected: 3.
2020.07.23 14:44:21.718570 [ 37 ] {} <Warning> TCPHandler: Client has not sent any data.
2020.07.23 14:44:22.562992 [ 38 ] {} <Error> MySQLHandler: DB::Exception: Cannot read all data. Bytes read: 0. Bytes expected: 3.
2020.07.23 14:44:22.564134 [ 41 ] {} <Warning> TCPHandler: Client has not sent any data.
2020.07.23 14:44:23.391310 [ 39 ] {} <Error> MySQLHandler: DB::Exception: Cannot read all data. Bytes read: 0. Bytes expected: 3.
2020.07.23 14:44:23.391367 [ 37 ] {} <Warning> TCPHandler: Client has not sent any data.
2020.07.23 14:44:24.386518 [ 41 ] {} <Warning> TCPHandler: Client has not sent any data.
2020.07.23 14:44:24.386533 [ 38 ] {} <Error> MySQLHandler: DB::Exception: Cannot read all data. Bytes read: 0. Bytes expected: 3.

**Comment by qoega** [comment]
It will be easier to check this if you provide scenario to reproduce this case

**Comment by i4late** [comment]
you have mysql engine tables ?

**Comment by yishanchuan** [comment]
Hi, guys. I have a similar exception, but I use MergeTree! Following is the detail stack:

`ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 33, host: 10.58.92.49, port: 8123; Code: 33, e.displayText() = DB::Exception: Cannot read all data. Bytes read: 1. Bytes expected: 5. (version 20.8.2.3 (official build))

	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:58)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:28)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.checkForErrorAndThrow(ClickHouseStatementImpl.java:875)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.sendStream(ClickHouseStatementImpl.java:851)
	at ru.yandex.clickhouse.Writer.send(Writer.java:106)
	at ru.yandex.clickhouse.Writer.send(Writer.java:141)
	at com.ctrip.hotel.settlement.exchange.common.clickhouse.CkHelper.bulkInsertRowBinary(CkHelper.java:326)
	at com.ctrip.hotel.settlement.exchange.business.DBCleaner.ClickhouseSyncTask.sendData(ClickhouseSyncTask.java:112)
	at com.ctrip.hotel.settlement.exchange.business.DBCleaner.AbstractSync.loopSendData(AbstractSync.java:545)
	at com.ctrip.hotel.settlement.exchange.business.DBCleaner.AbstractSync.loadData(AbstractSync.java:454)
	at com.ctrip.hotel.settlement.exchange.business.DBCleaner.AbstractSync.loadDataSplit(AbstractSync.java:355)
	at com.ctrip.hotel.settlement.exchange.business.DBCleaner.AbstractSync.loopSend(AbstractSync.java:305)
	at com.ctrip.hotel.settlement.exchange.business.DBCleaner.AbstractSync.syncDataTask(AbstractSync.java:149)
	at com.ctrip.hotel.settlement.exchange.business.DBCleaner.ClickhouseSyncTask.lambda$execute$0(ClickhouseSyncTask.java:48)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Throwable: Code: 33, e.displayText() = DB::Exception: Cannot read all data. Bytes read: 1. Bytes expected: 5. (version 20.8.2.3 (official build))

	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:53)
	... 18 more`

**Comment by alexey-milovidov** [comment]
No info.

**Comment by bishrtabbaa** [comment]
I can reproduce this error details below... 

SW = Clickhouse local v 24.2.1.505
CFG = 1 singleton node
HW = Amazon EC2
Scenario = vanilla CH protocol works both locally and remotely; MySQL wire protocol adapter for CH **_also_** works both locally and remotely, however when I attempt to run an Amazon Athena JDBC Connector for MySQL and connect it to CH, the error message occurs as below... although, the network path is [initially] good, the log confirms user auth is good, and the log confirms that user permissions are good [`SELECT(dummy) ON system.one`].

LOG
```
2024.02.13 03:14:17.339002  <Trace> MySQLHandler: Capabilities: 19431944, max_packet_size: 16777215, character_set: 255, user: myuser, auth_response length: 20, database: default, auth_plugin_name: mysql_native_password
2024.02.13 03:14:17.339025 <Debug> MYSQL-Session: a4b9e2b6-8715-4439-b23a-bb2565596bec Authenticating user 'myuser' from [::ffff:172.31.24.184]:24955
2024.02.13 03:14:17.339043 <Debug> MYSQL-Session: a4b9e2b6-8715-4439-b23a-bb2565596bec Authenticated with global context as user 77448387-2437-aee6-85cc-a11ee972db13
2024.02.13 03:14:17.339057 <Debug> MySQLHandler: Authentication for user myuser succeeded.
2024.02.13 03:14:17.339065 <Debug> MYSQL-Session: a4b9e2b6-8715-4439-b23a-bb2565596bec Creating session context with user_id: 77448387-2437-aee6-85cc-a11ee972db13
2024.02.13 03:14:17.339930 <Debug> MySQLHandler: Received command: 3. Connection id: 34.
2024.02.13 03:14:17.339977 <Trace> MYSQL-Session: a4b9e2b6-8715-4439-b23a-bb2565596bec Creating query context from session context, user_id: 77448387-2437-aee6-85cc-a11ee972db13, parent context user: myuser
2024.02.13 03:14:17.340227 {mysql:34:3899c363-a11d-4e19-86f0-321ffe5398d6} <Debug> executeQuery: (from [::ffff:172.31.24.184]:24955, user: myuser) /* mysql-connector-j-8.2.0 (Revision: 06a1f724497fd81c6a659131fda822c9e5085b6c) */SELECT @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_write_timeout AS net_write_timeout, @@performance_schema AS performance_schema, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@transaction_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout (stage: Complete)
2024.02.13 03:14:17.341021 mysql:34:3899c363-a11d-4e19-86f0-321ffe5398d6} <Trace> ContextAccess (myuser): Access granted: SELECT(dummy) ON system.one
2024.02.13 03:14:17.341083 {mysql:34:3899c363-a11d-4e19-86f0-321ffe5398d6} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2024.02.13 03:14:17.341676 {mysql:34:3899c363-a11d-4e19-86f0-321ffe5398d6} <Debug> executeQuery: Read 1 rows, 1.00 B in 0.001595 sec., 626.9592476489028 rows/sec., 626.96 B/sec.
2024.02.13 03:14:17.342972 <Error> MySQLHandler: DB::Exception: Cannot read all data. Bytes read: 0. Bytes expected: 3.

```
