### ISSUE TITLE
Connection reset by peer, while reading from socket (127.0.0.1:9000)

### ISSUE THREAD

**Issue by Fanduzi** [ClickHouse/ClickHouse#16336]
we have a 6 node clickhouse cluster, I found that a node is abnormal, and it often fails to access through tcp port 9000
Only this node frequently has this problem, other nodes are normal
```
:) select version();

SELECT version()

┌─version()─┐
│ 20.3.5.21 │
└───────────┘
```
sometimes can connect but get `Cannot load data for command line suggestions` error
```
#clickhouse-client --user default --password super       --database system --multiline
ClickHouse client version 20.3.5.21 (official build).
Connecting to database system at localhost:9000 as user default.
Connected to ClickHouse server version 20.3.5 revision 54433.

bj2-clickhouse-all-prod-05 default@localhost:9000 [system]
:) Cannot load data for command line suggestions: Code: 210, e.displayText() = DB::NetException: Connection reset by peer, while reading from socket (127.0.0.1:9000) (version 20.3.5.21 (official build))
   
bj2-clickhouse-all-prod-05 default@localhost:9000 [system]
:) SELECT DISTINCT arrayJoin(extractAll(name, '[\\\\w_]{2,}')) AS res
:-] FROM 
:-] (
:-]     SELECT name
:-]     FROM system.functions
:-]     UNION ALL
:-]     SELECT name
:-]     FROM system.table_engines
:-]     UNION ALL
:-]     SELECT name
:-]     FROM system.formats
:-]     UNION ALL
:-]     SELECT name
:-]     FROM system.table_functions
:-]     UNION ALL
:-]     SELECT name
:-]     FROM system.data_type_families
:-]     UNION ALL
:-]     SELECT name
:-]     FROM system.merge_tree_settings
:-]     UNION ALL
:-]     SELECT name
:-]     FROM system.settings
:-]     UNION ALL
:-]     SELECT cluster
:-]     FROM system.clusters
:-]     UNION ALL
:-]     SELECT concat(func.name, comb.name)
:-]     FROM system.functions AS func
:-]     CROSS JOIN system.aggregate_function_combinators AS comb
:-]     WHERE is_aggregate
:-] )
:-] WHERE notEmpty(res);

SELECT DISTINCT arrayJoin(extractAll(name, '[\\\\w_]{2,}')) AS res
FROM 
(
    SELECT name
    FROM system.functions
    UNION ALL
    SELECT name
    FROM system.table_engines
    UNION ALL
    SELECT name
    FROM system.formats
    UNION ALL
    SELECT name
    FROM system.table_functions
    UNION ALL
    SELECT name
    FROM system.data_type_families
    UNION ALL
    SELECT name
    FROM system.merge_tree_settings
    UNION ALL
    SELECT name
    FROM system.settings
    UNION ALL
    SELECT cluster
    FROM system.clusters
    UNION ALL
    SELECT concat(func.name, comb.name)
    FROM system.functions AS func
    CROSS JOIN system.aggregate_function_combinators AS comb
    WHERE is_aggregate
)
WHERE notEmpty(res)

┌─res─┐
│ _w  │
│ w_  │
└─────┘
┌─res─┐
│ __  │
└─────┘
```

sometimes cannot connect 
```
#clickhouse-client --user default --password super       --database system
ClickHouse client version 20.3.5.21 (official build).
Connecting to database system at localhost:9000 as user default.
Code: 210. DB::NetException: Connection reset by peer, while reading from socket (127.0.0.1:9000)
```
use python clickhouse_driver 
```
>>> connect(f'clickhouse://{USER}:{PASSWORD}@{host}:{PORT}').cursor().execute(f'SHOW DATABASES')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/clickhouse_driver/dbapi/cursor.py", line 102, in execute
    **execute_kwargs
  File "/usr/local/lib/python3.6/site-packages/clickhouse_driver/client.py", line 199, in execute
    self.connection.force_connect()
  File "/usr/local/lib/python3.6/site-packages/clickhouse_driver/connection.py", line 180, in force_connect
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/clickhouse_driver/connection.py", line 256, in connect
    return self._init_connection(host, port)
  File "/usr/local/lib/python3.6/site-packages/clickhouse_driver/connection.py", line 238, in _init_connection
    self.receive_hello()
  File "/usr/local/lib/python3.6/site-packages/clickhouse_driver/connection.py", line 331, in receive_hello
    packet_type = read_varint(self.fin)
  File "clickhouse_driver/varint.pyx", line 38, in clickhouse_driver.varint.read_varint
  File "clickhouse_driver/bufferedreader.pyx", line 66, in clickhouse_driver.bufferedreader.BufferedReader.read_one
  File "clickhouse_driver/bufferedreader.pyx", line 196, in clickhouse_driver.bufferedreader.BufferedSocketReader.read_into_buffer
EOFError: Unexpected EOF while reading bytes
```

But when it cannot be accessed through the tcp 9000 port, it is possible to access through the http 8123 port
```
[root@bj2-clickhouse-all-prod-05 18:07:36 /data/clickhouse/ch_9000/logs]
#clickhouse-client --user default --password super       --database system --multiline --query="show databases"
Code: 210. DB::NetException: Connection reset by peer, while reading from socket (127.0.0.1:9000)


[root@bj2-clickhouse-all-prod-05 18:07:37 /data/clickhouse/ch_9000/logs]
#clickhouse-client --user default --password super       --database system --multiline --query="show databases"
Code: 210. DB::NetException: Connection reset by peer, while reading from socket (127.0.0.1:9000)


[root@bj2-clickhouse-all-prod-05 18:07:38 /data/clickhouse/ch_9000/logs]
#clickhouse-client --user default --password super       --database system --multiline --query="show databases"
Code: 210. DB::NetException: Connection reset by peer, while reading from socket (127.0.0.1:9000)


[root@bj2-clickhouse-all-prod-05 18:07:39 /data/clickhouse/ch_9000/logs]
#echo 'show databases' | curl 'http://172.16.24.133:8123/?user=default&password=super' -d @-
bp_bst_gio
bp_topping_gio
broker
broker_distribute
datacenter_dwh
datasets
default
fanboshi
infra_ycover
inno_lovestar
inno_lovestar_user_stat
inno_topping_article
inno_topping_payment
inno_topping_room
inno_topping_stat
inno_topping_user
mysql_monitor
rd_auditlog
system
testdb
```
I don't know how to troubleshoot this problem, there is no valuable information in the clickhouse log

```
#cat /etc/systemd/system/clickhouse-server.service 
[Unit]
Description=ClickHouse Server (analytic DBMS for big data)
Requires=network-online.target
After=network-online.target

[Service]
#Type=simple
Type=forking
User=clickhouse
Group=clickhouse
Restart=always
RestartSec=30
RuntimeDirectory=clickhouse-server
#ExecStart=/usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml --pid-file=/run/clickhouse-server/clickhouse-server.pid
ExecStart=/usr/bin/clickhouse-server --daemon --config=/data/clickhouse/ch_9000/config.xml --pid-file=/data/clickhouse/ch_9000/clickhouse-server.pid
#PIDFile=/data/clickhouse/ch_9000/clickhouse-server.pid
LimitCORE=infinity
LimitNOFILE=500000
CapabilityBoundingSet=CAP_NET_ADMIN CAP_IPC_LOCK CAP_SYS_NICE

[Install]
WantedBy=multi-user.target




#ps -ef| grep clickhouse
root      3758  2058  0 18:11 pts/0    00:00:00 grep --color=auto clickhouse
clickho+ 28005     1  6 Apr26 ?        12-08:23:29 /usr/bin/clickhouse-server --daemon --config=/data/clickhouse/ch_9000/config.xml --pid-file=/data/clickhouse/ch_9000/clickhouse-server.pid

[root@bj2-clickhouse-all-prod-05 18:11:47 /data/clickhouse/ch_9000/logs]
#lsof -p 28005|wc -l
193


#cat /proc/28005/limits
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        1073741824           unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             100000               100000               processes 
Max open files            500000               500000               files     
Max locked memory         65536                65536                bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       256974               256974               signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us        

```

**Comment by den-crane** [comment]
You use obsolete version 20.3.5.21. It's better to upgrade CH to 20.3.20.6.

>clickhouse-client --user default --password super       --database system --multiline --query="show databases"
>Code: 210. DB::NetException: Connection reset by peer, while reading from socket (127.0.0.1:9000)
>curl 'http://172.16.24.133:8123

You have used two different IPs. 127.0.0.1 and 172.16.24.133. Try use the same IP.

What is in CH logs at the same time? Can you provide CH logs?

**Comment by Fanduzi** [comment]
> You use obsolete version 20.3.5.21. It's better to upgrade CH to 20.3.20.6.
> 
> > clickhouse-client --user default --password super       --database system --multiline --query="show databases"
> > Code: 210. DB::NetException: Connection reset by peer, while reading from socket (127.0.0.1:9000)
> > curl 'http://172.16.24.133:8123
> 
> You have used two different IPs. 127.0.0.1 and 172.16.24.133. Try use the same IP.
> 
> What is in CH logs at the same time? Can you provide CH logs?

172.16.24.133 is the node which have the problem,  and all command is run  on that host

```
[root@bj2-clickhouse-all-prod-05 17:22:06 ~]
#clickhouse-client --user default --password super       --database system --multiline --query="show databases"; echo 'show databases' | curl 'http://127.0.0.1:8123/?user=default&password=super' -d @-  
Code: 210. DB::NetException: Connection reset by peer, while reading from socket (127.0.0.1:9000)

bp_bst_gio
bp_topping_gio
broker
broker_distribute
datacenter_dwh
datasets
default
fanboshi
infra_ycover
inno_lovestar
inno_lovestar_user_stat
inno_topping_article
inno_topping_payment
inno_topping_room
inno_topping_stat
inno_topping_user
mysql_monitor
rd_auditlog
system
testdb
```
it seems that there is nothing useful in the log
```
[root@bj2-clickhouse-all-prod-05 17:24:19 /data/clickhouse/ch_9000/logs]
#cat clickhouse.log| grep -v "<Warning> TCPHandler: Client has not sent any data."|tail -10
 (version 20.3.5.21 (official build))
2020.10.25 09:40:41.241369 [ 7864 ] {cecbb9ed-9de9-4a51-b040-f229adeac1b6} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 32, e.displayText() = DB::Exception: Attempt to read after eof (version 20.3.5.21 (official build))
2020.10.25 12:00:04.158830 [ 8835 ] {76ee972a-e24d-4a6f-81f7-42227227e746} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 32, e.displayText() = DB::Exception: Attempt to read after eof (version 20.3.5.21 (official build))
2020.10.25 12:00:28.726078 [ 7890 ] {53571e50-019c-4984-9de7-09c4993fc63d} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 32, e.displayText() = DB::Exception: Attempt to read after eof (version 20.3.5.21 (official build))
2020.10.25 12:55:48.139297 [ 11002 ] {39b8cdc8-eff9-422b-8b02-fb9ede636949} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 32, e.displayText() = DB::Exception: Attempt to read after eof (version 20.3.5.21 (official build))
2020.10.25 13:42:35.390801 [ 18743 ] {51aadd7d-dbbe-4f63-907d-40898efc4bf6} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 32, e.displayText() = DB::Exception: Attempt to read after eof (version 20.3.5.21 (official build))
2020.10.25 14:24:18.185658 [ 21510 ] {b6688e10-5277-4da7-bf30-ef215616e36c} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 32, e.displayText() = DB::Exception: Attempt to read after eof (version 20.3.5.21 (official build))
2020.10.25 15:58:35.549908 [ 10050 ] {72ef002d-4a4b-432f-be92-4cf396b37812} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 32, e.displayText() = DB::Exception: Attempt to read after eof (version 20.3.5.21 (official build))
2020.10.25 16:43:54.295334 [ 9483 ] {46ee8159-6d55-40ee-b5d9-8671544bb2ef} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 32, e.displayText() = DB::Exception: Attempt to read after eof (version 20.3.5.21 (official build))
2020.10.25 17:00:16.789277 [ 8757 ] {ac31cfdf-a813-49eb-b319-0d67f1cc01ec} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 32, e.displayText() = DB::Exception: Attempt to read after eof (version 20.3.5.21 (official build))

[root@bj2-clickhouse-all-prod-05 17:24:27 /data/clickhouse/ch_9000/logs]
#cat error.log | grep -v "<Warning> TCPHandler: Client has not sent any data."|tail -10              
 (version 20.3.5.21 (official build))
2020.10.25 09:40:41.241369 [ 7864 ] {cecbb9ed-9de9-4a51-b040-f229adeac1b6} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 32, e.displayText() = DB::Exception: Attempt to read after eof (version 20.3.5.21 (official build))
2020.10.25 12:00:04.158830 [ 8835 ] {76ee972a-e24d-4a6f-81f7-42227227e746} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 32, e.displayText() = DB::Exception: Attempt to read after eof (version 20.3.5.21 (official build))
2020.10.25 12:00:28.726078 [ 7890 ] {53571e50-019c-4984-9de7-09c4993fc63d} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 32, e.displayText() = DB::Exception: Attempt to read after eof (version 20.3.5.21 (official build))
2020.10.25 12:55:48.139297 [ 11002 ] {39b8cdc8-eff9-422b-8b02-fb9ede636949} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 32, e.displayText() = DB::Exception: Attempt to read after eof (version 20.3.5.21 (official build))
2020.10.25 13:42:35.390801 [ 18743 ] {51aadd7d-dbbe-4f63-907d-40898efc4bf6} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 32, e.displayText() = DB::Exception: Attempt to read after eof (version 20.3.5.21 (official build))
2020.10.25 14:24:18.185658 [ 21510 ] {b6688e10-5277-4da7-bf30-ef215616e36c} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 32, e.displayText() = DB::Exception: Attempt to read after eof (version 20.3.5.21 (official build))
2020.10.25 15:58:35.549908 [ 10050 ] {72ef002d-4a4b-432f-be92-4cf396b37812} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 32, e.displayText() = DB::Exception: Attempt to read after eof (version 20.3.5.21 (official build))
2020.10.25 16:43:54.295334 [ 9483 ] {46ee8159-6d55-40ee-b5d9-8671544bb2ef} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 32, e.displayText() = DB::Exception: Attempt to read after eof (version 20.3.5.21 (official build))
2020.10.25 17:00:16.789277 [ 8757 ] {ac31cfdf-a813-49eb-b319-0d67f1cc01ec} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 32, e.displayText() = DB::Exception: Attempt to read after eof (version 20.3.5.21 (official build))

```
by the way the log level is `warning`
```
    <logger>
        <level>warning</level>
        <log>/data/clickhouse/ch_9000/logs/clickhouse.log</log>
        <errorlog>/data/clickhouse/ch_9000/logs/error.log</errorlog>
        <size>500M</size>
        <count>5</count>
    </logger>
```
By the way, does the logger level parameter take effect after restarting?


By the way, is there any documentation on the upgrade operation in the official documentation? How to upgrade clickhouse in the production environment? Because we encountered a problem in https://github.com/ClickHouse/ClickHouse/issues/13848 , we were worried that it would not start after the upgrade

**Comment by Fanduzi** [comment]
i found some log maybe useful, but these logs are in other node's clickhouse.log
```
2020.10.28 01:01:28.936373 [ 31047 ] {} <Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 104, e.displayText() = Connection reset by peer, Stack trace (when copying this message, always include the lines below):

0. Poco::IOException::IOException(int) @ 0x1051822f in /usr/bin/clickhouse
1. Poco::Net::ConnectionResetException::ConnectionResetException(int) @ 0xe369bad in /usr/bin/clickhouse
2. ? @ 0xe37f30a in /usr/bin/clickhouse
3. Poco::Net::SocketImpl::receiveBytes(void*, int, int) @ 0xe37d7e3 in /usr/bin/clickhouse
4. Poco::Net::HTTPSession::receive(char*, int) @ 0xe3596d8 in /usr/bin/clickhouse
5. Poco::Net::HTTPSession::get() @ 0xe359743 in /usr/bin/clickhouse
6. Poco::Net::HTTPHeaderStreamBuf::readFromDevice(char*, long) @ 0xe34e93a in /usr/bin/clickhouse
7. Poco::BasicBufferedStreamBuf<char, std::__1::char_traits<char>, Poco::Net::HTTPBufferAllocator>::underflow() @ 0xe34b1a8 in /usr/bin/clickhouse
8. std::__1::basic_streambuf<char, std::__1::char_traits<char> >::uflow() @ 0x1102afbe in ?
9. std::__1::basic_istream<char, std::__1::char_traits<char> >::get() @ 0x110325b6 in ?
10. Poco::Net::HTTPRequest::read(std::__1::basic_istream<char, std::__1::char_traits<char> >&) @ 0xe351d07 in /usr/bin/clickhouse
11. Poco::Net::HTTPServerRequestImpl::HTTPServerRequestImpl(Poco::Net::HTTPServerResponseImpl&, Poco::Net::HTTPServerSession&, Poco::Net::HTTPServerParams*) @ 0xe3577e5 in /usr/bin/clickhouse
12. Poco::Net::HTTPServerConnection::run() @ 0xe3568e9 in /usr/bin/clickhouse
13. Poco::Net::TCPServerConnection::start() @ 0xe3867bb in /usr/bin/clickhouse
14. Poco::Net::TCPServerDispatcher::run() @ 0xe386c3d in /usr/bin/clickhouse
15. Poco::PooledThread::run() @ 0x1059d237 in /usr/bin/clickhouse
16. Poco::ThreadImpl::runnableEntry(void*) @ 0x1059903c in /usr/bin/clickhouse
17. ? @ 0x1059a9dd in /usr/bin/clickhouse
18. start_thread @ 0x7e65 in /usr/lib64/libpthread-2.17.so
19. clone @ 0xfe88d in /usr/lib64/libc-2.17.so
 (version 20.3.5.21 (official build))
2020.10.28 01:45:32.933364 [ 30126 ] {f9789412-b597-4ea6-8336-1f286edf79e4} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 210, e.displayText() = DB::NetException: Connection reset by peer, while reading from socket (172.16.24.13:9000) (version 20.3.5.21 (official build))
2020.10.28 05:40:55.055839 [ 20173 ] {ed4ed341-de00-4563-bb8b-c34584e0dbfb} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 32, e.displayText() = DB::Exception: Attempt to read after eof (version 20.3.5.21 (official build))
2020.10.28 05:53:44.230015 [ 20136 ] {04694c4b-a3fd-4d4a-b6d1-53cc08c4cbfe} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 32, e.displayText() = DB::Exception: Attempt to read after eof (version 20.3.5.21 (official build))
2020.10.28 05:53:44.230047 [ 22013 ] {04694c4b-a3fd-4d4a-b6d1-53cc08c4cbfe} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 32, e.displayText() = DB::Exception: Attempt to read after eof (version 20.3.5.21 (official build))
2020.10.28 07:18:18.450781 [ 3285 ] {19423a8c-79ac-403a-aad5-ad59b5f6ffb6} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 32, e.displayText() = DB::Exception: Attempt to read after eof (version 20.3.5.21 (official build))
2020.10.28 09:15:44.992434 [ 5603 ] {09106947-9d17-4198-b254-53c92b46596e} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 32, e.displayText() = DB::Exception: Attempt to read after eof (version 20.3.5.21 (official build))
2020.10.28 09:46:20.210471 [ 20138 ] {} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 210, e.displayText() = DB::NetException: Connection reset by peer, while reading from socket (172.16.24.153:9000) (version 20.3.5.21 (official build))
2020.10.28 09:48:49.544233 [ 30130 ] {6f55ef44-47de-4697-8c51-827956c476d4} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 210, e.displayText() = DB::NetException: Connection reset by peer, while reading from socket (172.16.24.153:9000) (version 20.3.5.21 (official build))
2020.10.28 09:50:49.640268 [ 27545 ] {26ba2518-7cf2-45db-a000-60287319ffd2} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 32, e.displayText() = DB::Exception: Attempt to read after eof (version 20.3.5.21 (official build))
2020.10.28 09:52:32.213480 [ 27543 ] {1df7e914-3041-4948-9a4b-40002f409c14} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 210, e.displayText() = DB::NetException: Connection reset by peer, while reading from socket (172.16.24.153:9000) (version 20.3.5.21 (official build))
(END)
```

**Comment by JackyWoo** [comment]
I hive the same issue with version 20.6.6.7.

**Comment by Fanduzi** [comment]
> I hive the same issue with version 20.6.6.7.
> @Fanduzi does it work with higher ch version?

I haven't upgraded yet.
