### ISSUE TITLE
Broken pipe (Write failed)

### ISSUE THREAD

**Issue by RonanMorgan** [ClickHouse/ClickHouse#17446]
Hello :)

Sometimes, I have a "Broken pipe" exception when I try to save data in ClickHouse server version 20.6.3.28 (official build).

```
2020-11-26 14:33:13,120 [pool-2-thread-76] INFO  com.mypackage.clickhouse-commons.exceptions - (ClickhouseUtils)  Error in executeBatchSaving, for database net_mydatabase, retry number :10, size of the list : 96, Number of columns : 178 : ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: myserver..net, port: 8123; Broken pipe (Write failed)
2020-11-26 14:33:13,121 [pool-2-thread-76] INFO  com.mypackage.clickhouse-commons.exceptions - (ClickhouseUtils)  Error in executeBatchSavingWithRetry, for database net_mydatabase, retry number :10, stacktrace ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: myserver.net, port: 8123; Broken pipe (Write failed)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.getException(ClickHouseExceptionSpecifier.java:91)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:55)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:24)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.sendStream(ClickHouseStatementImpl.java:855)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.sendStream(ClickHouseStatementImpl.java:824)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.sendStream(ClickHouseStatementImpl.java:817)
	at ru.yandex.clickhouse.ClickHousePreparedStatementImpl.executeBatch(ClickHousePreparedStatementImpl.java:335)
	at ru.yandex.clickhouse.ClickHousePreparedStatementImpl.executeBatch(ClickHousePreparedStatementImpl.java:320)
	at com.mypackage.clickhousecommons.ClickhouseUtils.executeBatchSaving(ClickhouseUtils.java:163)
	at com.mypackage.clickhousecommons.ClickhouseUtils.executeBatchSavingWithRetry(ClickhouseUtils.java:134)
	at com.mypackage.clickhousecommons.ClickhouseUtils.executeBatchSavingWithRetry(ClickhouseUtils.java:140)
	at com.mypackage.clickhousecommons.ClickhouseUtils.executeBatchSavingWithRetry(ClickhouseUtils.java:140)
	at com.mypackage.clickhousecommons.ClickhouseUtils.executeBatchSavingWithRetry(ClickhouseUtils.java:140)
	at com.mypackage.clickhousecommons.ClickhouseUtils.executeBatchSavingWithRetry(ClickhouseUtils.java:140)
	at com.mypackage.clickhousecommons.ClickhouseUtils.executeBatchSavingWithRetry(ClickhouseUtils.java:140)
	at com.mypackage.clickhousecommons.ClickhouseUtils.executeBatchSavingWithRetry(ClickhouseUtils.java:140)
	at com.mypackage.clickhousecommons.ClickhouseUtils.executeBatchSavingWithRetry(ClickhouseUtils.java:140)
	at com.mypackage.clickhousecommons.ClickhouseUtils.executeBatchSavingWithRetry(ClickhouseUtils.java:140)
	at com.mypackage.clickhousecommons.ClickhouseUtils.executeBatchSavingWithRetry(ClickhouseUtils.java:140)
	at com.mypackage.clickhousecommons.ClickhouseUtils.executeBatchSavingWithRetry(ClickhouseUtils.java:140)
	at com.mypackage.clickhousecommons.ClickhouseUtils.lambda$executeAsyncBatchSavingForSiteCodes$0(ClickhouseUtils.java:226)
	at com.mypackage.lang.ThreadUtils.lambda$createRunnableWithThrowableLog$1(ThreadUtils.java:25)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at org.apache.http.impl.io.SessionOutputBufferImpl.streamWrite(SessionOutputBufferImpl.java:124)
	at org.apache.http.impl.io.SessionOutputBufferImpl.flushBuffer(SessionOutputBufferImpl.java:136)
	at org.apache.http.impl.io.SessionOutputBufferImpl.write(SessionOutputBufferImpl.java:167)
	at org.apache.http.impl.io.ChunkedOutputStream.flushCacheWithAppend(ChunkedOutputStream.java:122)
	at org.apache.http.impl.io.ChunkedOutputStream.write(ChunkedOutputStream.java:179)
	at org.apache.http.impl.io.ChunkedOutputStream.write(ChunkedOutputStream.java:166)
	at ru.yandex.clickhouse.ClickHousePreparedStatementImpl$BatchHttpEntity.writeTo(ClickHousePreparedStatementImpl.java:367)
	at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:156)
	at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:162)
	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:238)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.sendStream(ClickHouseStatementImpl.java:849)
	... 25 more
```

=> there are lots of queries in //, I would say one hundred per sec
=> it happens for queries with very few row (~one hundred)
=> it happens rarely, maybe 40 times a day, only for the biggest databases (> 300 columns)
=> there are no exceptions logs server-side corresponding to this request (I have activated "trace" log)

It seems to me that clickhouse is closing the connection too early 
=> i have incread the keep_alive_timeout to 9 server side
=> client side (I am using the official java jdbc driver, v0.2.4) I have increased SOCKET_TIMEOUT, CONNECTION_TIMEOUT & DATA_TRANSFER_TIMEOUT to 1000000

But it still happens, which is surprising since there is not many rows (but lots of columns !
Do you have any idea of the reason of such behavior ?

**Comment by den-crane** [comment]
It's jdbc driver issue https://github.com/ClickHouse/clickhouse-jdbc/issues/290

It' seems it fixed here https://github.com/ClickHouse/clickhouse-jdbc/pull/515

**Comment by RonanMorgan** [comment]
thanks !

**Comment by RonanMorgan** [comment]
Hello,

I made a mistake in my description, it seems that there are errors server side for those "Broken Pipe" requests but it's written 
"The Transfer-Encoding is not chunked and there is no Content-Length header for POST"

I didn't make the link with my previous [issue](https://github.com/ClickHouse/ClickHouse/issues/17073) :/   

@den-crane do you still think that it could be linked to ClickHouse/clickhouse-jdbc#515 ? It looks more like an invalid HTTP request than a timeout errors to me

**Comment by RonanMorgan** [comment]
Hello,

After more investigation I just noticed that
1) even after retries, these requests are failing again and again so it has to be reproducible 

2) indeed cickhouse is receiving a  "Transfer Encoding: identity" without "Length" parameters
```
2020.12.02 16:13:15.557926 [ 2440479 ] {8851d60d-95d7-4464-8131-169cb5565010} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B.
2020.12.02 16:13:15.559572 [ 2440479 ] {} <Trace> HTTPHandler-factory: HTTP Request for HTTPHandler-factory. Method: POST, Address: [::ffff:95.217.43.208]:37170, User-Agent: none, Content Type: , Transfer Encoding: identity
2020.12.02 16:13:15.559974 [ 2440479 ] {} <Error> DynamicQueryHandler: Code: 381, e.displayText() = DB::Exception: The Transfer-Encoding is not chunked and there is no Content-Length header for POST request, Stack trace (when copying this message, always include the lines below):
2020.12.02 16:13:15.560064 [ 2440479 ] {} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B.
2020.12.02 16:13:15.560141 [ 2440479 ] {} <Trace> HTTPHandler-factory: HTTP Request for HTTPHandler-factory. Method: Transfer-Encoding:, Address: [::ffff:95.217.43.208]:37170, User-Agent: Apache-HttpClient/4.5.2 (Java/1.8.0_252), Content Type: , Transfer Encoding: identity
```
so maybe there is a specific case, where 
> client.execute(httpPost); (used in the client)
is wrongly filling the headers (according to the HTTP specification it should not be possible...)

3) these errors are not saved in the system.query_log table

**Comment by den-crane** [comment]
>User-Agent: none, Content Type: , Transfer Encoding: identity

none ? It's something bad happen in jdbc or apach-httpclient

**Comment by RonanMorgan** [comment]
ok, thanks, I will try tomorrow.

I just finished some tests with tshark, it really seems to me that all the failing requests have the following headers ...
```Transfer-Encoding: chunked
Host: myserver.kameleoon.net:8123
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.2 (Java/1.8.0_272)
```

**Comment by RonanMorgan** [comment]
I dig further wit thsark today :

`log.log:Dec  3, 2020 16:10:35.700820027 CET	/?query=INSERT+INTO+mytable.visits+%28VISITORCODE%2C+VISITNUMBER%2C+TIMESTARTED%2C+NUMBERPAGES%2C+OS%2C+BROWSER%2C+DEVICETYPE%2C+ADBLOCK%2C+LANGUAGE%2C+LANDINGPAGEURL%2C+VISITDURATION%2C+FIRSTREFERRERURL%2C+TRAFFICTYPE%2C+TIMESINCEPREVIOUSVISIT%2C+MAXNUMBERTABS%2C+URL%2C+URLTITLE%2C+FIRSTREFERRERS%2C+KEYPAGE%2C+GEOLOCATION_COUNTRY%2C+GEOLOCATION_REGION%2C+GEOLOCATION_CITY%2C+CUSTOMDATA_0%2C+CUSTOMDATA_1%2C+CUSTOMDATA_2%2C+CUSTOMDATA_3%2C+CUSTOMDATA_4%2C+CUSTOMDATA_5%2C+CUSTOMDATA_6%2C+CUSTOMDATA_7%2C+CUSTOMDATA_8%2C+CUSTOMDATA_9%2C+CUSTOMDATA_10%2C+CUSTOMDATA_11%2C+CUSTOMDATA_12%2C+CUSTOMDATA_13%2C+CUSTOMDATA_14%2C+CUSTOMDATA_15%2C+CUSTOMDATA_16%2C+CUSTOMDATA_17%2C+CUSTOMDATA_18%2C+CUSTOMDATA_19%2C+CUSTOMDATA_20%2C+CUSTOMDATA_21%2C+CUSTOMDATA_22%2C+CUSTOMDATA_23%2C+CUSTOMDATA_24%2C+EXPERIMENT_89219%2C+EXPERIMENT_118277%2C+EXPERIMENT_100101%2C+EXPERIMENT_89353%2C+EXPERIMENT_118539%2C+EXPERIMENT_100362%2C+EXPERIMENT_105101%2C+EXPERIMENT_110477%2C+EXPERIMENT_89359%2C+EXPERIMENT_95758%2C+EXPERIMENT_95635%2C+EXPERIMENT_110740%2C+EXPERIMENT_89367%2C+EXPERIMENT_89754%2C+EXPERIMENT_89242%2C+EXPERIMENT_96797%2C+EXPERIMENT_109340%2C+EXPERIMENT_113052%2C+EXPERIMENT_96286%2C+EXPERIMENT_98846%2C+EXPERIMENT_94627%2C+EXPERIMENT_91555%2C+EXPERIMENT_98084%2C+EXPERIMENT_102055%2C+EXPERIMENT_99753%2C+EXPERIMENT_105512%2C+EXPERIMENT_107051%2C+EXPERIMENT_89770%2C+EXPERIMENT_113066%2C+EXPERIMENT_88618%2C+EXPERIMENT_89517%2C+EXPERIMENT_89773%2C+EXPERIMENT_100783%2C+EXPERIMENT_89265%2C+EXPERIMENT_92976%2C+EXPERIMENT_117047%2C+EXPERIMENT_91190%2C+EXPERIMENT_89273%2C+EXPERIMENT_89277%2C+EXPERIMENT_108479%2C+EXPERIMENT_89279%2C+EXPERIMENT_95681%2C+EXPERIMENT_89281%2C+EXPERIMENT_117441%2C+EXPERIMENT_116674%2C+EXPERIMENT_90568%2C+EXPERIMENT_87502%2C+EXPERIMENT_105553%2C+EXPERIMENT_89299%2C+EXPERIMENT_118873%2C+EXPERIMENT_106207%2C+EXPERIMENT_101343%2C+EXPERIMENT_89315%2C+EXPERIMENT_89827%2C+EXPERIMENT_89826%2C+EXPERIMENT_89830%2C+EXPERIMENT_116591%2C+EXPERIMENT_106097%2C+EXPERIMENT_97787%2C+EXPERIMENT_95226%2C+EXPERIMENT_114942%2C+TARGETINGSEGMENT_115841%2C+TARGETINGSEGMENT_115201%2C+TARGETINGSEGMENT_128130%2C+TARGETINGSEGMENT_115844%2C+TARGETINGSEGMENT_125060%2C+TARGETINGSEGMENT_140676%2C+TARGETINGSEGMENT_132868%2C+TARGETINGSEGMENT_130057%2C+TARGETINGSEGMENT_114312%2C+TARGETINGSEGMENT_121864%2C+TARGETINGSEGMENT_115851%2C+TARGETINGSEGMENT_118926%2C+TARGETINGSEGMENT_116241%2C+TARGETINGSEGMENT_116240%2C+TARGETINGSEGMENT_122643%2C+TARGETINGSEGMENT_116243%2C+TARGETINGSEGMENT_120477%2C+TARGETINGSEGMENT_116253%2C+TARGETINGSEGMENT_138654%2C+TARGETINGSEGMENT_129567%2C+TARGETINGSEGMENT_130463%2C+TARGETINGSEGMENT_117025%2C+TARGETINGSEGMENT_120227%2C+TARGETINGSEGMENT_44710%2C+TARGETINGSEGMENT_44711%2C+TARGETINGSEGMENT_125737%2C+TARGETINGSEGMENT_44712%2C+TARGETINGSEGMENT_129320%2C+TARGETINGSEGMENT_121005%2C+TARGETINGSEGMENT_136623%2C+TARGETINGSEGMENT_125358%2C+TARGETINGSEGMENT_128561%2C+TARGETINGSEGMENT_124208%2C+TARGETINGSEGMENT_115763%2C+TARGETINGSEGMENT_115511%2C+TARGETINGSEGMENT_115767%2C+TARGETINGSEGMENT_115769%2C+TARGETINGSEGMENT_120248%2C+TARGETINGSEGMENT_115770%2C+TARGETINGSEGMENT_115773%2C+TARGETINGSEGMENT_117309%2C+TARGETINGSEGMENT_132417%2C+TARGETINGSEGMENT_116297%2C+TARGETINGSEGMENT_123720%2C+TARGETINGSEGMENT_115796%2C+TARGETINGSEGMENT_120278%2C+TARGETINGSEGMENT_128474%2C+TARGETINGSEGMENT_127713%2C+TARGETINGSEGMENT_127712%2C+TARGETINGSEGMENT_127714%2C+TARGETINGSEGMENT_116197%2C+TARGETINGSEGMENT_115813%2C+TARGETINGSEGMENT_122085%2C+TARGETINGSEGMENT_116205%2C+TARGETINGSEGMENT_122092%2C+TARGETINGSEGMENT_119535%2C+TARGETINGSEGMENT_116207%2C+TARGETINGSEGMENT_134125%2C+TARGETINGSEGMENT_139117%2C+TARGETINGSEGMENT_140528%2C+TARGETINGSEGMENT_127986%2C+TARGETINGSEGMENT_139505%2C+TARGETINGSEGMENT_123509%2C+TARGETINGSEGMENT_117879%2C+TARGETINGSEGMENT_127609%2C+TARGETINGSEGMENT_115839%2C+TARGETINGSEGMENT_139517%2C+TARGETINGSEGMENT_120318%2C+CONVERSION_168003%2C+REVENUECONVERSION_168003%2C+CONVERSION_210418%2C+REVENUECONVERSION_210418%2C+CONVERSION_168004%2C+REVENUECONVERSION_168004%2C+CONVERSION_148747%2C+REVENUECONVERSION_148747%2C+CONVERSION_204333%2C+REVENUECONVERSION_204333%29++FORMAT+TabSeparated&database=default&compress=1				Apache-HttpClient/4.5.2 (Java/1.8.0_272)	chunked		2087,10494,2190,2084,10272,2314,2272,8406,2082,3214,5128,3150,4409,2072,3284,6650,8414,2152,3041,6992,3522,8303,2181,2116,4259,4772,5879,4593,9819,23241,3105,10920,3842,3998,4243,3605,2971,8339,4187,2178,2195,2985,5526,2221,2245,4188,20626,2298,3379,23785,3854,9208,2275,9487,3336,2148,2338,9391,10173,2157,3059,17062,3223,12224,4729,2245,2864,2511,5738,3746,2561,5708,7053,3013,2261,2100,5056,4190,2079,5029,4142,0`

It's chunked but : 

```
log.log:Dec  3, 2020 16:10:41.421209797 CET		200	OK	OK		chunked		0
log.log:Dec  3, 2020 16:10:41.435653281 CET		200	OK	OK		chunked		0
log.log:Dec  3, 2020 16:10:41.467231172 CET		200	OK	OK		chunked		0
log.log:Dec  3, 2020 16:10:41.472295243 CET		200	OK	OK		chunked		0
log.log:Dec  3, 2020 16:10:41.473148709 CET		200	OK	OK		chunked		0
log.log:Dec  3, 2020 16:10:41.481199256 CET		200	OK	OK		chunked		0
log.log:Dec  3, 2020 16:10:41.507150849 CET		200	OK	OK		chunked		0
log.log:Dec  3, 2020 16:10:41.514659799 CET		200	OK	OK		chunked		0
log.log:Dec  3, 2020 16:10:41.517446401 CET		200	OK	OK		chunked		0
log.log:Dec  3, 2020 16:10:41.519751205 CET		200	OK	OK		chunked		0
log.log:Dec  3, 2020 16:10:41.530001320 CET		200	OK	OK		chunked		0
log.log:Dec  3, 2020 16:10:41.617001571 CET		200	OK	OK		chunked		0
log.log:Dec  3, 2020 16:10:41.655027446 CET	/?query_id=ee0ddf27-3329-4768-bb59-032e9487341c&extremes=0&compress=1&database=default		Apache-HttpClient/4.5.2 (Java/1.8.0_252)			
log.log:Dec  3, 2020 16:10:41.656810794 CET		200	OK	OK		chunked		59,0
log.log:Dec  3, 2020 16:10:41.672446706 CET		411,501	Length Required,Not Implemented	Length Required,Not Implemented		chunked173,0
log.log:Dec  3, 2020 16:10:41.674373995 CET		411	Length Required	Length Required		chunked		173,0
log.log:Dec  3, 2020 16:10:41.674388459 CET		501	Not Implemented	Not Implemented				
log.log:Dec  3, 2020 16:10:41.677149755 CET		411	Length Required	Length Required		chunked		173,0
log.log:Dec  3, 2020 16:10:41.677186071 CET		501	Not Implemented	Not Implemented				
log.log:Dec  3, 2020 16:10:41.679424112 CET		411	Length Required	Length Required		chunked		173,0
log.log:Dec  3, 2020 16:10:41.679454821 CET		501	Not Implemented	Not Implemented	
```

6sec have passed between the error and this call but I can see in my client logs that the error at 16:10:41 is linked to this table (and there was no other call between 16:10:35 and 16:10:41 for this table according to tshark

=> I might use tshark wrongly and miss some calls
here is my command :

`tshark -n -T fields -e frame.time -e http.request.uri -e http.response.code -e http.response.code.desc -e http.response.phrase -e http.user_agent -e http.transfer_encoding -e http.response_in -e http.chunk_size -f 'port 8123' -Y " http.request.uri or http.response.phrase"`

But I tried with two different tshark commands and I never saw an INSERT request without User-Content or  without "chunked" Transfer-Encoding

**Comment by RonanMorgan** [comment]
Hello,

I have implemented a retry logic  which is dividing the size of the batch by two at each retry, it works well, I don't have data loss anymore

For me it's clearly due to my data model ; I am using arrays which can contain lot's of elements . The error happens clearly when my row are too heavy.

Thanks for your help, I hope It's gonna be production-ready soon :)
