### ISSUE TITLE
start clickhouse on aarch64 get coredump

### ISSUE THREAD

**Issue by miaojianxin** [ClickHouse/ClickHouse#18121]
I build clickhouse 20.8.6 code on aarch64,
the gcc :9.3.0
clang+llvm:10.0
the build is ok:
cd ClickHouse
export CC=clang; export CXX=clang++; rm -rf build; mkdir -p build && cd build;cmake .. -DENABLE_TCMALLOC=OFF -DENABLE_JEMALLOC=OFF -DCMAKE_INSTALL_PREFIX=/opt/clickhouse
ninja clickhouse

when run clickhouse, use  ./clickhouse server --config etc/config.xml
it cored.  the core dump is as below:

#0  0x0000ffff9f3d1568 in raise () from /lib/aarch64-linux-gnu/libc.so.6
#1  0x0000ffff9f3d2a20 in abort () from /lib/aarch64-linux-gnu/libc.so.6
#2  0x00000000129ea890 in terminate_handler () at ../base/daemon/BaseDaemon.cpp:404
#3  0x000000001476e58c in std::__terminate (func=0x0) at ../contrib/libcxxabi/src/cxa_handlers.cpp:59
#4  0x000000001476ddc0 in __cxa_rethrow () at ../contrib/libcxxabi/src/cxa_exception.cpp:616
#5  0x000000000d7622c4 in DB::getCurrentExceptionMessage (with_stacktrace=true, check_embedded_stacktrace=false, 
    with_extra_info=true) at ../src/Common/Exception.cpp:249
#6  0x00000000129ea774 in terminate_handler () at ../base/daemon/BaseDaemon.cpp:389
#7  0x000000001476e58c in std::__terminate (func=0x0) at ../contrib/libcxxabi/src/cxa_handlers.cpp:59
#8  0x000000001476daa8 in __cxxabiv1::failed_throw (exception_header=0x2ca95560)
    at ../contrib/libcxxabi/src/cxa_exception.cpp:152
#9  0x000000001476da24 in __cxa_throw (thrown_object=<optimized out>, 
    tinfo=0xc195130 <typeinfo for Poco::Net::SSLContextException>, dest=<optimized out>)
    at ../contrib/libcxxabi/src/cxa_exception.cpp:283
#10 0x00000000139fb864 in Poco::Net::Context::init (this=0x2ca917d0, params=...)
    at ../contrib/poco/NetSSL_OpenSSL/src/Context.cpp:153
#11 0x00000000139fb38c in Poco::Net::Context::Context (this=0x2ca917d0, usage=Poco::Net::Context::SERVER_USE, 
---Type <return> to continue, or q <return> to quit---
    params=...) at ../contrib/poco/NetSSL_OpenSSL/src/Context.cpp:48
#12 0x0000000013a04efc in Poco::Net::SSLManager::initDefaultContext (this=0x2ca929f0, server=true)
    at ../contrib/poco/NetSSL_OpenSSL/src/SSLManager.cpp:297
#13 0x0000000013a04830 in Poco::Net::SSLManager::defaultServerContext (this=0x2ca929f0)
    at ../contrib/poco/NetSSL_OpenSSL/src/SSLManager.cpp:130
#14 0x0000000013569260 in DB::MySQLHandlerFactory::MySQLHandlerFactory (this=0x2ca919d0, server_=...)
    at ../src/Server/MySQLHandlerFactory.cpp:30
#15 0x000000000d7a9e94 in DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)::$_8::operator()(unsigned short) const (this=<optimized out>, port=9504)
    at ../programs/server/Server.cpp:973
#16 DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)::$_1::operator()<DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)::$_8> (this=<optimized out>, port_name=<optimized out>, func=<optimized out>)
    at ../programs/server/Server.cpp:844
---Type <return> to continue, or q <return> to quit---
#17 DB::Server::main (this=0xfffffd978850) at ../programs/server/Server.cpp:966
#18 0x0000000013a54848 in Poco::Util::Application::run (this=0xfffffd978850)
    at ../contrib/poco/Util/src/Application.cpp:334
#19 0x000000000d7a1610 in DB::Server::run (this=0xfffffd978850) at ../programs/server/Server.cpp:187
#20 0x000000000d7b4094 in mainEntryClickHouseServer (argc=22309, argv=0x6) at ../programs/server/Server.cpp:1143
#21 0x000000000d7545e8 in main (argc_=<optimized out>, argv_=<optimized out>) at ../programs/main.cpp:338
(gdb)

**Comment by miaojianxin** [comment]
the same platform， the same way build method， clickhouse20.3.19.4-lts   run ok， but 20.8.6 run  got core dump
