### ISSUE TITLE
Partial or Full support of extended queries for postgresql wire protocol to allow npgsql.NET to connect

### ISSUE THREAD

**Issue by siradjev** [ClickHouse/ClickHouse#18611]
**Use case**
Npgsql is the most popular .NET driver for postgresql wire protocol. (https://www.npgsql.org)

**Describe the solution you'd like**
Currently it's not possible to use .NET driver for postgres to connect to clickhouse because it uses extended queries on opening connection. 
```
0A000: ClickHouse doesn't support extended query mechanism
```
Example snippet to check. 
```
            using (NpgsqlConnection conn = new NpgsqlConnection("Server=server; Port=5432; User Id=ptest; Password=ptest; Database=ptest"))
            {
                conn.Open(); // throws exception
            }

```

**Describe alternatives you've considered**
No other real alternative is available. 

**Additional context**

**Comment by zhicwu** [comment]
Using JDBC driver has similar issue, but a workaround is to put `preferQueryMode=simple` in your connection string.

However, I ended up with below issues in multi-threaded environment after creating and closing connections for one or two minutes. No error spotted if I change to single thread mode.
* server (21.6.5.37)
  ```
  ...
  2021.06.24 02:10:44.437266 [ 53 ] {} <Debug> PostgreSQLHandler: Client closed the connection
  2021.06.24 02:10:44.461443 [ 125 ] {} <Error> PostgreSQLHandler: Command is not supported. Command code 0
  2021.06.24 02:10:44.461499 [ 142 ] {} <Error> PostgreSQLHandler: Command is not supported. Command code 0
  2021.06.24 02:10:44.461443 [ 54 ] {} <Error> PostgreSQLHandler: Command is not supported. Command code 0
  2021.06.24 02:10:44.461791 [ 125 ] {} <Error> PostgreSQLHandler: DB::Exception: Cannot read all data. Bytes read: 0. Bytes expected: 4.
  2021.06.24 02:10:44.461803 [ 54 ] {} <Error> PostgreSQLHandler: DB::Exception: Cannot read all data. Bytes read: 0. Bytes expected: 4.
  2021.06.24 02:10:44.461810 [ 142 ] {} <Error> PostgreSQLHandler: DB::Exception: Cannot read all data. Bytes read: 0. Bytes expected: 4.
  2021.06.24 02:10:44.461448 [ 128 ] {} <Error> PostgreSQLHandler: Command is not supported. Command code 0
  2021.06.24 02:10:44.462113 [ 128 ] {} <Error> PostgreSQLHandler: DB::Exception: Cannot read all data. Bytes read: 0. Bytes expected: 4.
  ...
  ```
* client (driver version: [42.2.22](https://mvnrepository.com/artifact/org.postgresql/postgresql/42.2.22), connection string: `jdbc:postgresql://ch-server:9005/system?user=default&password=&ssl=false&sslmode=disable&preferQueryMode=simple`)
  ```
  org.postgresql.util.PSQLException: Connection to ch-server:9005 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:303)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)
        at org.postgresql.Driver.makeConnection(Driver.java:465)
        at org.postgresql.Driver.connect(Driver.java:264)
        at tech.clickhouse.benchmark.ClientState.newConnection(ClientState.java:29)
        at tech.clickhouse.benchmark.JdbcBenchmark.createAndCloseConnection(JdbcBenchmark.java:93)
        at tech.clickhouse.benchmark.Connection.connect(Connection.java:8)
        at tech.clickhouse.benchmark.jmh_generated.Connection_connect_jmhTest.connect_thrpt_jmhStub(Connection_connect_jmhTest.java:152)
        at tech.clickhouse.benchmark.jmh_generated.Connection_connect_jmhTest.connect_Throughput(Connection_connect_jmhTest.java:87)
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:470)
        at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:453)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
  Caused by: java.net.ConnectException: Cannot assign requested address (connect failed)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:607)
        at org.postgresql.core.PGStream.createSocket(PGStream.java:231)
        at org.postgresql.core.PGStream.<init>(PGStream.java:95)
        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:98)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:213)
        ... 20 more
  ```

**Comment by siradjev** [comment]
> Using JDBC driver has similar issue, but a workaround is to put preferQueryMode=simple in your connection string.

Unfortunately npgsql for .net does not have such setting...

**Comment by greaka** [comment]
Rust's sqlx library requires this too.

**Comment by YaroShkvorets** [comment]
Same with https://github.com/diesel-rs/diesel
