### ISSUE TITLE
MemorySanitizer: use-of-uninitialized-value contrib/grpc/src/core/lib/gpr/cpu_linux.cc:40:7 in init_num_cpus()

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#19312]
**How to reproduce**
Master, integration test MSAN test_grpc_protocol
https://clickhouse-test-reports.s3.yandex.net/0/ea0052aba56bf7c279fbe0bf755bff79e4624dad/integration_tests_(memory).html

**Error message and/or stacktrace**
```
node_1  | ==8==WARNING: MemorySanitizer: use-of-uninitialized-value
node_1  |     #0 0x3e1d800f in init_num_cpus() obj-x86_64-linux-gnu/../contrib/grpc/src/core/lib/gpr/cpu_linux.cc:40:7
node_1  |     #1 0x3e1e14df in decltype(std::declval<void (*&)()>()()) absl::lts_2020_02_25::base_internal::Callable::Invoke<void (*&)()>(void (*&)()) obj-x86_64-linux-gnu/../contrib/abseil-cpp/absl/base/internal/invoke.h:153:12
node_1  |     #2 0x3e1e14df in decltype(Invoker<void (*&)()>::type::Invoke(std::declval<void (*&)()>())) absl::lts_2020_02_25::base_internal::Invoke<void (*&)()>(void (*&)()) obj-x86_64-linux-gnu/../contrib/abseil-cpp/absl/base/internal/invoke.h:180:10
node_1  |     #3 0x3e1e14df in void absl::lts_2020_02_25::base_internal::CallOnceImpl<void (*&)()>(std::__1::atomic<unsigned int>*, absl::lts_2020_02_25::base_internal::SchedulingMode, void (*&)()) obj-x86_64-linux-gnu/../contrib/abseil-cpp/absl/base/call_once.h:178:5
node_1  |     #4 0x3e1e1341 in void absl::lts_2020_02_25::call_once<void (*&)()>(absl::lts_2020_02_25::once_flag&, void (*&)()) obj-x86_64-linux-gnu/../contrib/abseil-cpp/absl/base/call_once.h:217:5
node_1  |     #5 0x3e1e1341 in gpr_once_init obj-x86_64-linux-gnu/../contrib/grpc/src/core/lib/gpr/sync_abseil.cc:113:3
node_1  |     #6 0x3e1d7da0 in gpr_cpu_num_cores obj-x86_64-linux-gnu/../contrib/grpc/src/core/lib/gpr/cpu_linux.cc:57:3
node_1  |     #7 0x3dc34a01 in grpc_stats_init() obj-x86_64-linux-gnu/../contrib/grpc/src/core/lib/debug/stats.cc:41:17
node_1  |     #8 0x3dc331ef in grpc_init obj-x86_64-linux-gnu/../contrib/grpc/src/core/lib/surface/init.cc:140:5
node_1  |     #9 0x3d828e48 in grpc::internal::GrpcLibrary::init() obj-x86_64-linux-gnu/../contrib/grpc/include/grpcpp/impl/grpc_library.h:34:26
node_1  |     #10 0x3d7c0345 in grpc::GrpcLibraryCodegen::GrpcLibraryCodegen(bool) obj-x86_64-linux-gnu/../contrib/grpc/include/grpcpp/impl/codegen/grpc_library.h:45:15
node_1  |     #11 0x3d7c0345 in grpc::CompletionQueue::CompletionQueue(grpc_completion_queue_attributes const&) obj-x86_64-linux-gnu/../contrib/grpc/include/grpcpp/impl/codegen/completion_queue.h:240:3
node_1  |     #12 0x3d83cd36 in grpc::ServerCompletionQueue::ServerCompletionQueue(grpc_cq_completion_type, grpc_cq_polling_type, grpc_experimental_completion_queue_functor*) obj-x86_64-linux-gnu/../contrib/grpc/include/grpcpp/impl/codegen/completion_queue.h:436:9
node_1  |     #13 0x3d83cd36 in grpc::ServerBuilder::AddCompletionQueue(bool) obj-x86_64-linux-gnu/../contrib/grpc/src/cpp/server/server_builder.cc:73:41
node_1  |     #14 0x2fc95eac in DB::GRPCServer::start() obj-x86_64-linux-gnu/../src/Server/GRPCServer.cpp:1645:21
node_1  |     #15 0x2fe960bc in DB::ProtocolServerAdapter::GRPCServerAdapterImpl::start() obj-x86_64-linux-gnu/../src/Server/ProtocolServerAdapter.cpp:38:42
node_1  |     #16 0x8d445ee in DB::ProtocolServerAdapter::start() obj-x86_64-linux-gnu/../src/Server/ProtocolServerAdapter.h:31:26
node_1  |     #17 0x8d445ee in DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) obj-x86_64-linux-gnu/../programs/server/Server.cpp:1228:20
node_1  |     #18 0x3a4c71a6 in Poco::Util::Application::run() obj-x86_64-linux-gnu/../contrib/poco/Util/src/Application.cpp:334:8
node_1  |     #19 0x8d1a982 in DB::Server::run() obj-x86_64-linux-gnu/../programs/server/Server.cpp:325:25
node_1  |     #20 0x3a525397 in Poco::Util::ServerApplication::run(int, char**) obj-x86_64-linux-gnu/../contrib/poco/Util/src/ServerApplication.cpp:611:9
node_1  |     #21 0x8d1668a in mainEntryClickHouseServer(int, char**) obj-x86_64-linux-gnu/../programs/server/Server.cpp:117:20
node_1  |     #22 0x8d11073 in main obj-x86_64-linux-gnu/../programs/main.cpp:368:12
node_1  |     #23 0x7f67ffb620b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
node_1  |     #24 0x8c92b6d in _start (/usr/bin/clickhouse+0x8c92b6d)
node_1  |
node_1  |   Uninitialized value was created by an allocation of 'cpu' in the stack frame of function 'sched_getcpu'
node_1  |     #0 0x41ce75a0 in sched_getcpu obj-x86_64-linux-gnu/../base/glibc-compatibility/musl/sched_getcpu.c:32
node_1  |
node_1  | SUMMARY: MemorySanitizer: use-of-uninitialized-value obj-x86_64-linux-gnu/../contrib/grpc/src/core/lib/gpr/cpu_linux.cc:40:7 in init_num_cpus()
```

```
2021.01.20 00:52:15.697413 [ 9 ] {} <Trace> BaseDaemon: Received signal -3
2021.01.20 00:52:15.697856 [ 46 ] {} <Fatal> BaseDaemon: ########################################
2021.01.20 00:52:15.698032 [ 46 ] {} <Fatal> BaseDaemon: (version 21.1.1.5732 (official build), build id: 52D059501556638673485A0977E5A88B8C455CF1) (from thread 8) (no query) Received signal Unknown signal (-3)
2021.01.20 00:52:15.698145 [ 46 ] {} <Fatal> BaseDaemon: Sanitizer trap.
2021.01.20 00:52:15.698341 [ 46 ] {} <Fatal> BaseDaemon: Stack trace: 0x8e0f5d9 0x9429aec 0x8cfd116 0x8c93963 0x3e1d8010 0x3e1e14e0 0x3e1e1342 0x3e1d7da1 0x3dc34a02 0x3dc331f0 0x3d828e49 0x3d7c0346 0x3d83cd37 0x2fc95ead 0x2fe960bd 0x8d445ef 0x3a4c71a7 0x8d1a983 0x3a525398 0x8d1668b 0x8d11074 0x7f67ffb620b3 0x8c92b6e
2021.01.20 00:52:15.698837 [ 46 ] {} <Fatal> BaseDaemon: 0. ./obj-x86_64-linux-gnu/../src/Common/StackTrace.cpp:293: StackTrace::StackTrace() @ 0x8e0f5d9 in /usr/bin/clickhouse
2021.01.20 00:52:15.699880 [ 46 ] {} <Fatal> BaseDaemon: 1. ./obj-x86_64-linux-gnu/../src/Common/CurrentThread.h:81: sanitizerDeathCallback() @ 0x9429aec in /usr/bin/clickhouse
2021.01.20 00:52:15.705134 [ 46 ] {} <Fatal> BaseDaemon: 2. __sanitizer::Die() @ 0x8cfd116 in /usr/bin/clickhouse
2021.01.20 00:52:15.709845 [ 46 ] {} <Fatal> BaseDaemon: 3. ? @ 0x8c93963 in /usr/bin/clickhouse
2021.01.20 00:52:15.714090 [ 46 ] {} <Fatal> BaseDaemon: 4. ./obj-x86_64-linux-gnu/../contrib/grpc/src/core/lib/gpr/cpu_linux.cc:41: init_num_cpus() @ 0x3e1d8010 in /usr/bin/clickhouse
2021.01.20 00:52:15.718461 [ 46 ] {} <Fatal> BaseDaemon: 5. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/atomic:1006: void absl::lts_2020_02_25::base_internal::CallOnceImpl<void (*&)()>(std::__1::atomic<unsigned int>*, absl::lts_2020_02_25::base_internal::SchedulingMode, void (*&)()) @ 0x3e1e14e0 in /usr/bin/clickhouse
2021.01.20 00:52:15.722701 [ 46 ] {} <Fatal> BaseDaemon: 6. ./obj-x86_64-linux-gnu/../contrib/abseil-cpp/absl/base/call_once.h:0: gpr_once_init @ 0x3e1e1342 in /usr/bin/clickhouse
2021.01.20 00:52:15.726975 [ 46 ] {} <Fatal> BaseDaemon: 7. ./obj-x86_64-linux-gnu/../contrib/grpc/src/core/lib/gpr/cpu_linux.cc:58: gpr_cpu_num_cores @ 0x3e1d7da1 in /usr/bin/clickhouse
2021.01.20 00:52:15.731154 [ 46 ] {} <Fatal> BaseDaemon: 8. ./obj-x86_64-linux-gnu/../contrib/grpc/src/core/lib/debug/stats.cc:41: grpc_stats_init() @ 0x3dc34a02 in /usr/bin/clickhouse
2021.01.20 00:52:15.735322 [ 46 ] {} <Fatal> BaseDaemon: 9. ./obj-x86_64-linux-gnu/../contrib/grpc/src/core/lib/surface/init.cc:141: grpc_init @ 0x3dc331f0 in /usr/bin/clickhouse
2021.01.20 00:52:15.739498 [ 46 ] {} <Fatal> BaseDaemon: 10. ./obj-x86_64-linux-gnu/../contrib/grpc/include/grpcpp/impl/grpc_library.h:34: grpc::internal::GrpcLibrary::init() @ 0x3d828e49 in /usr/bin/clickhouse
2021.01.20 00:52:15.744097 [ 46 ] {} <Fatal> BaseDaemon: 11. ./obj-x86_64-linux-gnu/../contrib/grpc/include/grpcpp/impl/codegen/grpc_library.h:46: grpc::CompletionQueue::CompletionQueue(grpc_completion_queue_attributes const&) @ 0x3d7c0346 in /usr/bin/clickhouse
2021.01.20 00:52:15.748314 [ 46 ] {} <Fatal> BaseDaemon: 12. ./obj-x86_64-linux-gnu/../contrib/grpc/include/grpcpp/impl/codegen/completion_queue.h:439: grpc::ServerBuilder::AddCompletionQueue(bool) @ 0x3d83cd37 in /usr/bin/clickhouse
2021.01.20 00:52:15.751907 [ 46 ] {} <Fatal> BaseDaemon: 13. ./obj-x86_64-linux-gnu/../src/Server/GRPCServer.cpp:1645: DB::GRPCServer::start() @ 0x2fc95ead in /usr/bin/clickhouse
2021.01.20 00:52:15.755363 [ 46 ] {} <Fatal> BaseDaemon: 14. ./obj-x86_64-linux-gnu/../src/Server/ProtocolServerAdapter.cpp:38: DB::ProtocolServerAdapter::GRPCServerAdapterImpl::start() @ 0x2fe960bd in /usr/bin/clickhouse
2021.01.20 00:52:15.757106 [ 46 ] {} <Fatal> BaseDaemon: 15. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/iterator:1496: DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x8d445ef in /usr/bin/clickhouse
2021.01.20 00:52:15.761818 [ 46 ] {} <Fatal> BaseDaemon: 16. ./obj-x86_64-linux-gnu/../contrib/poco/Util/src/Application.cpp:0: Poco::Util::Application::run() @ 0x3a4c71a7 in /usr/bin/clickhouse
2021.01.20 00:52:15.762090 [ 46 ] {} <Fatal> BaseDaemon: 17. ./obj-x86_64-linux-gnu/../programs/server/Server.cpp:325: DB::Server::run() @ 0x8d1a983 in /usr/bin/clickhouse
2021.01.20 00:52:15.766070 [ 46 ] {} <Fatal> BaseDaemon: 18. ./obj-x86_64-linux-gnu/../contrib/poco/Util/src/ServerApplication.cpp:611: Poco::Util::ServerApplication::run(int, char**) @ 0x3a525398 in /usr/bin/clickhouse
2021.01.20 00:52:15.766205 [ 46 ] {} <Fatal> BaseDaemon: 19. ./obj-x86_64-linux-gnu/../programs/server/Server.cpp:0: mainEntryClickHouseServer(int, char**) @ 0x8d1668b in /usr/bin/clickhouse
2021.01.20 00:52:15.766366 [ 46 ] {} <Fatal> BaseDaemon: 20. ./obj-x86_64-linux-gnu/../programs/main.cpp:0: main @ 0x8d11074 in /usr/bin/clickhouse
2021.01.20 00:52:15.766451 [ 46 ] {} <Fatal> BaseDaemon: 21. __libc_start_main @ 0x270b3 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.01.20 00:52:15.771140 [ 46 ] {} <Fatal> BaseDaemon: 22. _start @ 0x8c92b6e in /usr/bin/clickhouse
2021.01.20 00:52:20.011608 [ 46 ] {} <Fatal> BaseDaemon: Checksum of the binary: B8EBD3AF637E09709D7BC1360CB0FD82, integrity check passed.
```

**Comment by alexey-milovidov** [comment]
#19234

**Comment by qoega** [comment]
> @qoega If the behaviour of ClickHouse release version is not affected - never place a "bug" label.
> We have "fuzz" and "testing" labels for the purpose to highlight these issues.

Lets add separate issue template for Sanitizer reports. It is not an abort() found by fuzzing/stress tests.

**Comment by qoega** [comment]
#19318
