### ISSUE TITLE
Nullptr dereference in FULL OUTER JOIN

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#20017]
**Describe the bug**
https://clickhouse-test-reports.s3.yandex.net/19971/ac510f9770da9e59cc51cabcca8302ee9ec0f95d/fuzzer_msan/server.log

**Comment by hexiaoting** [comment]
Is this query leading to nullptr dereference?
```
SELECT intDiv(t2.y, 3), t2.* FROM t1 FULL OUTER JOIN t2 ON and(toUInt32(intDiv(intDiv(t1.y, 3), 1048576)) = t2.x) ORDER BY (t2.y AND (NULL AND (t2.y AND (t1.x = t2.x)) AND (t1.x = t2.x)) AND (t1.x = t2.x)) AND (intDiv(t1.y, NULL) AND t2.y AND (t1.x = t2.x)) AND (t1.x = t2.x) DESC NULLS LAST
```

I try it on my own env, it's ok.

How can I reproduce this bug?

**Comment by alexey-milovidov** [comment]
Yes, this query triggered nullptr dereference.
The issue does not reproduce easily - I also checked it.

It was found by fuzzer (that runs enormous amounts of randomized queries) and in this case - the server was run under Memory Sanitizer. The error may depend on the settings that were changed (fuzzer also changes almost all the settings to achieve complete madness), it may depend on modified data (fuzzer do crazy stuff with inserted data as well) and if we unfortunate - it may depend on queries history.

Most likely this task is duplicate: #20046

**Comment by akuzm** [comment]
https://clickhouse-test-reports.s3.yandex.net/20068/b0fba3decef216e32c8813c0fe321210915159c6/fuzzer_ubsan/report.html#fail1

Found a new similar report under UBSan, but can't reproduce:
```
CREATE TABLE tracking_events_tmp (`APIKey` UInt32, `EventDate` Date) ENGINE = MergeTree PARTITION BY toYYYYMM(EventDate) ORDER BY (APIKey, EventDate);
CREATE TABLE open_events_tmp (`APIKey` UInt32, `EventDate` Date) ENGINE = MergeTree PARTITION BY toMonday(EventDate) ORDER BY (APIKey, EventDate);

insert into open_events_tmp select 2, '2020-07-10' from numbers(32);
insert into open_events_tmp select 2, '2020-07-11' from numbers(31);

insert into tracking_events_tmp select 2, '2020-07-10' from numbers(1881);
insert into tracking_events_tmp select 2, '2020-07-11' from numbers(1623);

SELECT EventDate FROM (SELECT EventDate FROM tracking_events_tmp AS t1 WHERE (EventDate >= toDate('2020-07-10')) AND (EventDate <= toDate('2020-07-11')) AND (APIKey = 2) GROUP BY EventDate) FULL OUTER JOIN (SELECT EventDate FROM remote('127.0.0.{1,3}', currentDatabase(), open_events_tmp) AS t2 WHERE (EventDate >= toDate('2020-07-10')) AND (EventDate <= toDate('2020-07-11')) AND (APIKey = 2) GROUP BY EventDate WITH TOTALS) USING (EventDate) ORDER BY EventDate ASC SETTINGS totals_mode = 'after_having_auto', group_by_overflow_mode = 'any', max_rows_to_group_by = 10000000, joined_subquery_requires_alias = 0

../src/Common/assert_cast.h:50:12: runtime error: downcast of address 0x7f44852bc3e0 which does not point to an object of type 'const DB::ColumnNullable'
0x7f44852bc3e0: note: object is of type 'DB::ColumnVector<unsigned short>'
 00 00 00 00  90 e2 3a 06 00 00 00 00  03 00 00 00 44 7f 00 00  90 4d 60 a0 44 7f 00 00  92 4d 60 a0
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'DB::ColumnVector<unsigned short>'
2021.02.04 23:33:53.405571 [ 95 ] {} <Trace> SystemLog (system.query_thread_log): Flushing system log, 3411 entries to flush
2021.02.04 23:33:53.435095 [ 95 ] {} <Debug> DiskLocal: Reserving 3.35 MiB on disk `default`, having unreserved 38.50 GiB.
2021.02.04 23:33:53.445009 [ 95 ] {} <Trace> system.query_thread_log (d9a28f87-1dbc-421f-9923-a9c78af49ca6): Renaming temporary part tmp_insert_202102_307_307_0 to 202102_307_307_0.
2021.02.04 23:33:53.445351 [ 95 ] {} <Trace> SystemLog (system.query_thread_log): Flushed system log
2021.02.04 23:33:54.225390 [ 119 ] {} <Debug> DNSResolver: Updating DNS cache
2021.02.04 23:33:54.244596 [ 119 ] {} <Information> DNSResolver: Cached hosts not found: 27.0.0.1, 27.0.0.2, 127.0..1, 127.0.0.1127.0.0.1127.0.0.2127.0.0.2, 127.0.0.1127.0.0.1, 127..0.2, 127.0.0.1127.0.0.2, 127.0.0.1127.0.0.2127.0.0.2127.0.0.1, 127.0.0.2127.0.0.2127.0.0.2127.0.0.1, 127.0.0.2127.0.0.2, 127.0.0.2127.0.0.1, 127..0.1, 127.0.0., 127.0.0.1, 127.0..2, 127.0.0.1127.0.0.1127.0.0.1127.0.0.2, 127.0.0.2127.0.0.1127.0.0.1127.0.0.1, 127.0.0.2127.0.0.1127.0.0.2127.0.0.2, 127.0.0.1127.0.0.2127.0.0.1127.0.0.1, 127.0.0.2127.0.0.1127.0.0.2127.0.0.1, 127.0.0.2127.0.0.1127.0.0.1127.0.0.2, 127.0.0.1127.0.0.1127.0.0.2127.0.0.1, 127.0.0.2127.0.0.2127.0.0.2127.0.0.2, 127.0.0.1127.0.0.2127.0.0.1127.0.0.2, 2}, 127.0.0.2127.0.0.2127.0.0.1127.0.0.2, 127.0.0.2127.0.0.2127.0.0.1127.0.0.1, 127.0.0.{12}, 127.0.0.1127.0.0.1127.0.0.1127.0.0.1, 127.0.0.1127.0.0.2127.0.0.2127.0.0.2
2021.02.04 23:33:54.244632 [ 119 ] {} <Debug> DNSResolver: Updated DNS cache
    #0 0x195ad918 in DB::ColumnNullable const& assert_cast<DB::ColumnNullable const&, DB::IColumn const&>(DB::IColumn const&) obj-x86_64-linux-gnu/../src/Common/assert_cast.h:50:12
    #1 0x195ad918 in DB::DataTypeNullable::serializeBinaryBulkWithMultipleStreamsImpl(DB::IColumn const&, unsigned long, unsigned long, DB::IDataType::SerializeBinaryBulkSettings&, std::__1::shared_ptr<DB::IDataType::SerializeBinaryBulkState>&) const obj-x86_64-linux-gnu/../src/DataTypes/DataTypeNullable.cpp:92:34
    #2 0x19e60ca3 in DB::NativeBlockOutputStream::writeData(DB::IDataType const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&, DB::WriteBuffer&, unsigned long, unsigned long) obj-x86_64-linux-gnu/../src/DataStreams/NativeBlockOutputStream.cpp:58:10
    #3 0x19e6179f in DB::NativeBlockOutputStream::write(DB::Block const&) obj-x86_64-linux-gnu/../src/DataStreams/NativeBlockOutputStream.cpp:124:13
    #4 0x1aaec2e4 in DB::TCPHandler::sendTotals(DB::Block const&) obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:713:26
    #5 0x1aae70ae in DB::TCPHandler::processOrdinaryQueryWithProcessors() obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:642:13
    #6 0x1aadac37 in DB::TCPHandler::runImpl() obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:277:17
    #7 0x1aaf30cc in DB::TCPHandler::run() obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:1417:9
    #8 0x1b8f66cb in Poco::Net::TCPServerConnection::start() obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerConnection.cpp:43:3
    #9 0x1b8f6b22 in Poco::Net::TCPServerDispatcher::run() obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerDispatcher.cpp:112:19
    #10 0x1b9d4d79 in Poco::PooledThread::run() obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/ThreadPool.cpp:199:14
    #11 0x1b9d2b7b in Poco::ThreadImpl::runnableEntry(void*) obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345:27
    #12 0x7f45f2a90608 in start_thread /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477:8
    #13 0x7f45f29b7292 in clone /build/glibc-eX1tMB/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../src/Common/assert_cast.h:50:12 in 
2021.02.04 23:33:54.346727 [ 87 ] {} <Trace> BaseDaemon: Received signal -3
2021.02.04 23:33:54.347132 [ 174 ] {} <Fatal> BaseDaemon: ########################################
2021.02.04 23:33:54.347242 [ 174 ] {} <Fatal> BaseDaemon: (version 21.3.1.5913, build id: 5193BBDECBADFA12F7C389A5CD3D04235D0695B3) (from thread 89) (query_id: 4e243b64-981e-496b-998a-b75e22422e5a) Received signal Unknown signal (-3)
2021.02.04 23:33:54.347286 [ 174 ] {} <Fatal> BaseDaemon: Sanitizer trap.
2021.02.04 23:33:54.347395 [ 174 ] {} <Fatal> BaseDaemon: Stack trace: 0xe2503b5 0xe47b726 0xe214356 0xe224e39 0x195ad919 0x19e60ca4 0x19e617a0 0x1aaec2e5 0x1aae70af 0x1aadac38 0x1aaf30cd 0x1b8f66cc 0x1b8f6b23 0x1b9d4d7a 0x1b9d2b7c 0x7f45f2a90609 0x7f45f29b7293
2021.02.04 23:33:54.347536 [ 174 ] {} <Fatal> BaseDaemon: 0. ./obj-x86_64-linux-gnu/../src/Common/StackTrace.cpp:296: StackTrace::StackTrace() @ 0xe2503b5 in /workspace/clickhouse
2021.02.04 23:33:54.347878 [ 174 ] {} <Fatal> BaseDaemon: 1. ./obj-x86_64-linux-gnu/../base/daemon/BaseDaemon.cpp:380: sanitizerDeathCallback() @ 0xe47b726 in /workspace/clickhouse
2021.02.04 23:33:54.351599 [ 174 ] {} <Fatal> BaseDaemon: 2. __sanitizer::Die() @ 0xe214356 in /workspace/clickhouse
2021.02.04 23:33:54.355110 [ 174 ] {} <Fatal> BaseDaemon: 3. ? @ 0xe224e39 in /workspace/clickhouse
2021.02.04 23:33:54.356894 [ 174 ] {} <Fatal> BaseDaemon: 4. ./obj-x86_64-linux-gnu/../src/Common/assert_cast.h:0: DB::DataTypeNullable::serializeBinaryBulkWithMultipleStreamsImpl(DB::IColumn const&, unsigned long, unsigned long, DB::IDataType::SerializeBinaryBulkSettings&, std::__1::shared_ptr<DB::IDataType::SerializeBinaryBulkState>&) const @ 0x195ad919 in /workspace/clickhouse
2021.02.04 23:33:54.358816 [ 174 ] {} <Fatal> BaseDaemon: 5. ./obj-x86_64-linux-gnu/../src/DataStreams/NativeBlockOutputStream.cpp:59: DB::NativeBlockOutputStream::writeData(DB::IDataType const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&, DB::WriteBuffer&, unsigned long, unsigned long) @ 0x19e60ca4 in /workspace/clickhouse
2021.02.04 23:33:54.360778 [ 174 ] {} <Fatal> BaseDaemon: 6. ./obj-x86_64-linux-gnu/../src/DataStreams/NativeBlockOutputStream.cpp:126: DB::NativeBlockOutputStream::write(DB::Block const&) @ 0x19e617a0 in /workspace/clickhouse
2021.02.04 23:33:54.363604 [ 174 ] {} <Fatal> BaseDaemon: 7. ./obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:714: DB::TCPHandler::sendTotals(DB::Block const&) @ 0x1aaec2e5 in /workspace/clickhouse
2021.02.04 23:33:54.366456 [ 174 ] {} <Fatal> BaseDaemon: 8. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/unordered_map:1044: DB::TCPHandler::processOrdinaryQueryWithProcessors() @ 0x1aae70af in /workspace/clickhouse
2021.02.04 23:33:54.369187 [ 174 ] {} <Fatal> BaseDaemon: 9. ./obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:277: DB::TCPHandler::runImpl() @ 0x1aadac38 in /workspace/clickhouse
2021.02.04 23:33:54.372210 [ 174 ] {} <Fatal> BaseDaemon: 10. ./obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:1419: DB::TCPHandler::run() @ 0x1aaf30cd in /workspace/clickhouse
2021.02.04 23:33:54.375365 [ 174 ] {} <Fatal> BaseDaemon: 11. ./obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x1b8f66cc in /workspace/clickhouse
2021.02.04 23:33:54.378577 [ 174 ] {} <Fatal> BaseDaemon: 12. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/atomic:1072: Poco::Net::TCPServerDispatcher::run() @ 0x1b8f6b23 in /workspace/clickhouse
2021.02.04 23:33:54.381772 [ 174 ] {} <Fatal> BaseDaemon: 13. ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/include/Poco/ScopedLock.h:36: Poco::PooledThread::run() @ 0x1b9d4d7a in /workspace/clickhouse
2021.02.04 23:33:54.384903 [ 174 ] {} <Fatal> BaseDaemon: 14. ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/include/Poco/SharedPtr.h:156: Poco::ThreadImpl::runnableEntry(void*) @ 0x1b9d2b7c in /workspace/clickhouse
2021.02.04 23:33:54.384973 [ 174 ] {} <Fatal> BaseDaemon: 15. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
2021.02.04 23:33:54.385037 [ 174 ] {} <Fatal> BaseDaemon: 16. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
```

**Comment by abyss7** [comment]
Another query: `SELECT item_id FROM (SELECT item_id FROM t GROUP BY item_id WITH TOTALS) AS l FULL OUTER JOIN (SELECT item_id FROM t GROUP BY ((NULL, '0.0000065537', '0', tuple(tuple(tuple(NULL))), -9223372036854775808, NULL), (NULL, '0.0001048577', (('100', NULL), tuple((256, NULL))), NULL), NULL), item_id WITH TOTALS) AS r USING (item_id)`

With another stacktrace:
```2021.02.10 20:09:15.169724 [ 87 ] {} <Trace> BaseDaemon: Received signal 11
2021.02.10 20:09:15.169945 [ 191 ] {} <Fatal> BaseDaemon: ########################################
2021.02.10 20:09:15.170041 [ 191 ] {} <Fatal> BaseDaemon: (version 21.3.1.5973, build id: 9A6D0CB1BF0B52BBFD0D3E1C977102652333A236) (from thread 190) (query_id: b18a38a8-cb3f-4570-870f-d44284afe269) Received signal Segmentation fault (11)
2021.02.10 20:09:15.170119 [ 191 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2021.02.10 20:09:15.170205 [ 191 ] {} <Fatal> BaseDaemon: Stack trace: 0x1e6fc9f7 0x1d012fdb 0x1dfc6081 0x1dfc743d 0x1f747406 0x1f73fb1b 0x1f72df8c 0x1f751d4d 0x2573f58f 0x257400ac 0x25a01d85 0x259fc2d7 0x7f90e11c0609 0x7f90e10e7293
2021.02.10 20:09:15.238882 [ 191 ] {} <Fatal> BaseDaemon: 3. ./obj-x86_64-linux-gnu/../src/Columns/ColumnNullable.cpp:653: DB::ColumnNullable::checkConsistency() const @ 0x1e6fc9f7 in /workspace/clickhouse
2021.02.10 20:09:15.298251 [ 191 ] {} <Fatal> BaseDaemon: 4. ./obj-x86_64-linux-gnu/../src/DataTypes/DataTypeNullable.cpp:96: DB::DataTypeNullable::serializeBinaryBulkWithMultipleStreamsImpl(DB::IColumn const&, unsigned long, unsigned long, DB::IDataType::SerializeBinaryBulkSettings&, std::__1::shared_ptr<DB::IDataType::SerializeBinaryBulkState>&) const @ 0x1d012fdb in /workspace/clickhouse
2021.02.10 20:09:15.321918 [ 191 ] {} <Fatal> BaseDaemon: 5. ./obj-x86_64-linux-gnu/../src/DataStreams/NativeBlockOutputStream.cpp:59: DB::NativeBlockOutputStream::writeData(DB::IDataType const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&, DB::WriteBuffer&, unsigned long, unsigned long) @ 0x1dfc6081 in /workspace/clickhouse
2021.02.10 20:09:15.352364 [ 191 ] {} <Fatal> BaseDaemon: 6. ./obj-x86_64-linux-gnu/../src/DataStreams/NativeBlockOutputStream.cpp:0: DB::NativeBlockOutputStream::write(DB::Block const&) @ 0x1dfc743d in /workspace/clickhouse
2021.02.10 20:09:15.626991 [ 191 ] {} <Fatal> BaseDaemon: 7.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2844: std::__1::shared_ptr<DB::WriteBuffer>::operator->() const
2021.02.10 20:09:15.627129 [ 191 ] {} <Fatal> BaseDaemon: 7. ../src/Server/TCPHandler.cpp:742: DB::TCPHandler::sendTotals(DB::Block const&) @ 0x1f747406 in /workspace/clickhouse
2021.02.10 20:09:15.883037 [ 191 ] {} <Fatal> BaseDaemon: 8. ./obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:0: DB::TCPHandler::processOrdinaryQueryWithProcessors() @ 0x1f73fb1b in /workspace/clickhouse
2021.02.10 20:09:16.126512 [ 191 ] {} <Fatal> BaseDaemon: 9. ./obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:284: DB::TCPHandler::runImpl() @ 0x1f72df8c in /workspace/clickhouse
2021.02.10 20:09:16.423290 [ 191 ] {} <Fatal> BaseDaemon: 10. ./obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:1461: DB::TCPHandler::run() @ 0x1f751d4d in /workspace/clickhouse
2021.02.10 20:09:16.426048 [ 191 ] {} <Fatal> BaseDaemon: 11. ./obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x2573f58f in /workspace/clickhouse
2021.02.10 20:09:16.443828 [ 191 ] {} <Fatal> BaseDaemon: 12. ./obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerDispatcher.cpp:0: Poco::Net::TCPServerDispatcher::run() @ 0x257400ac in /workspace/clickhouse
2021.02.10 20:09:16.458740 [ 191 ] {} <Fatal> BaseDaemon: 13. ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/ThreadPool.cpp:0: Poco::PooledThread::run() @ 0x25a01d85 in /workspace/clickhouse
2021.02.10 20:09:16.471923 [ 191 ] {} <Fatal> BaseDaemon: 14. ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread_POSIX.cpp:0: Poco::ThreadImpl::runnableEntry(void*) @ 0x259fc2d7 in /workspace/clickhouse
2021.02.10 20:09:16.472026 [ 191 ] {} <Fatal> BaseDaemon: 15. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
2021.02.10 20:09:16.472105 [ 191 ] {} <Fatal> BaseDaemon: 16. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so```

**Comment by alexey-milovidov** [comment]
Duplicate #20046.
