### ISSUE TITLE
Unknown database engine

### ISSUE THREAD

**Issue by newman-xu** [ClickHouse/ClickHouse#20021]
When I tried to create a MySQL Engine Database, I got the Unknown database engine Error.
CREATE DATABASE mysql_db ENGINE = MySQL('localhost:3306', 'test', 'my_user', 'user_password')
It is fine to create table based on MySQL table Engine.

org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [336]: ClickHouse exception, code: 336, host: localhost, port: 8123; Code: 336, e.displayText() = DB::Exception: Unknown database engine: 
ENGINE = MySQL('localhost:3306', 'test', 'my_user', 'user_password'), e.what() = DB::Exception

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)

	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:509)

	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:440)

	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)

	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:427)

	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:812)

	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3181)

	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:121)

	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)

	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:119)

	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4514)

	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)

	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

Caused by: ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 336, host: localhost, port: 8123; Code: 336, e.displayText() = DB::Exception: Unknown database engine: 
ENGINE = MySQL('localhost:3306', 'test', 'my_user', 'user_password'), e.what() = DB::Exception

	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:58)

	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:28)

	at ru.yandex.clickhouse.ClickHouseStatementImpl.checkForErrorAndThrow(ClickHouseStatementImpl.java:875)

	at ru.yandex.clickhouse.ClickHouseStatementImpl.getInputStream(ClickHouseStatementImpl.java:616)

	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:117)

	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:100)

	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:95)

	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:90)

	at ru.yandex.clickhouse.ClickHouseStatementImpl.execute(ClickHouseStatementImpl.java:226)

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:327)

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:130)

	... 12 more

Caused by: java.lang.Throwable: Code: 336, e.displayText() = DB::Exception: Unknown database engine: 
ENGINE = MySQL('localhost:3306', 'test', 'my_user', 'user_password'), e.what() = DB::Exception

	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:53)

	... 22 more

**Comment by alexey-milovidov** [comment]
Possible reason 1: maybe you are using custom ClickHouse build without enabled support for MySQL?
Possible reason 2: you are running ClickHouse on AArch64 server and AArch64 build does not have MySQL support?

**Comment by newman-xu** [comment]
Thanks a lot for your information, I just installed it on WSL 2(Ubuntu)  thru the following step.
sudo apt-get update

sudo apt-get install -y clickhouse-server clickhouse-client

sudo service clickhouse-server start

**Comment by alexey-milovidov** [comment]
If you did not add official ClickHouse repositories: 

```
sudo apt-get install apt-transport-https ca-certificates dirmngr
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv E0C56BD4

echo "deb https://repo.clickhouse.tech/deb/stable/ main/" | sudo tee /etc/apt/sources.list.d/clickhouse.list
```

It will install two years old demo version of ClickHouse from Ubuntu repos - not what you need.

**Comment by newman-xu** [comment]
Thanks a lot! It worked

**Comment by gpmcadam** [comment]
I'm having this issue running clickhouse-server on ubuntu in Docker on arm64 (Apple M1 Silicon)

> Possible reason 2: you are running ClickHouse on AArch64 server and AArch64 build does not have MySQL support?

@alexey-milovidov are you saying that the MySQL database engine type is _not_ supported on aarch64 build? If not, why? Is there some limitation of this architecture preventing it from being available?

Thanks
