### ISSUE TITLE
MemorySanitizer: use-of-uninitialized-value mysql-connector-odbc-8.0.21-src/driver/dll.cc:74:13 in myodbc_init

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#20278]
test_odbc_interaction MSan
```
Uninitialized bytes in read_sigaction at offset 0 inside [0x7f6a62e0b8a8, 4)
==81==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7f6a5fbfa3e5 in myodbc_init /export/home/pb2/build/sb_0-39732616-1592478141.19/mysql-connector-odbc-8.0.21-src/driver/dll.cc:74:13
    #1 0x7f6a5fbfdcb1 in my_SQLAllocEnv /export/home/pb2/build/sb_0-39732616-1592478141.19/mysql-connector-odbc-8.0.21-src/driver/handle.cc:73:14
    #2 0x7f6a5fbff0ee in SQLAllocHandle /export/home/pb2/build/sb_0-39732616-1592478141.19/mysql-connector-odbc-8.0.21-src/driver/handle.cc:854:34
    #3 0x17598a63 in __connect_part_one obj-x86_64-linux-gnu/../contrib/unixodbc/DriverManager/SQLConnect.c:1364:19
    #4 0x175df27f in SQLDriverConnect obj-x86_64-linux-gnu/../contrib/unixodbc/DriverManager/SQLDriverConnect.c:1328:11
    #5 0x175dbd72 in SQLDriverConnectA obj-x86_64-linux-gnu/../contrib/unixodbc/DriverManager/SQLDriverConnect.c:667:12
    #6 0xa1c8680 in Poco::Data::ODBC::SQLDriverConnect(void*, void*, unsigned char*, short, unsigned char*, short, short*, unsigned short) obj-x86_64-linux-gnu/../contrib/poco/Data/ODBC/include/Poco/Data/ODBC/Unicode.h:788:9
    #7 0xa1c8680 in Poco::Data::ODBC::SessionImpl::open(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) obj-x86_64-linux-gnu/../contrib/poco/Data/ODBC/src/SessionImpl.cpp:121:23
    #8 0xa1c5ebd in Poco::Data::ODBC::SessionImpl::SessionImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, unsigned long, bool, bool) obj-x86_64-linux-gnu/../contrib/poco/Data/ODBC/src/SessionImpl.cpp:45:2
    #9 0x338eef8 in DB::ODBCColumnsInfoHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&) obj-x86_64-linux-gnu/../programs/odbc-bridge/ColumnInfoHandler.cpp:102:42
    #10 0x165b79d5 in Poco::Net::HTTPServerConnection::run() obj-x86_64-linux-gnu/../contrib/poco/Net/src/HTTPServerConnection.cpp:89:17
    #11 0x1666ca7a in Poco::Net::TCPServerConnection::start() obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerConnection.cpp:43:3
    #12 0x1666e064 in Poco::Net::TCPServerDispatcher::run() obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerDispatcher.cpp:113:19
    #13 0x17422d25 in Poco::PooledThread::run() obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/ThreadPool.cpp:199:14
    #14 0x1741dd38 in Poco::(anonymous namespace)::RunnableHolder::run() obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread.cpp:55:11
    #15 0x17419d3b in Poco::ThreadImpl::runnableEntry(void*) obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345:27
    #16 0x7f6ad2a52608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x9608)
    #17 0x7f6ad2973292 in clone (/lib/x86_64-linux-gnu/libc.so.6+0x122292)

  Uninitialized value was created by an allocation of 'szFileName' in the stack frame of function 'SQLGetPrivateProfileString'
    #0 0x17688c80 in SQLGetPrivateProfileString obj-x86_64-linux-gnu/../contrib/unixodbc/odbcinst/SQLGetPrivateProfileString.c:374

SUMMARY: MemorySanitizer: use-of-uninitialized-value /export/home/pb2/build/sb_0-39732616-1592478141.19/mysql-connector-odbc-8.0.21-src/driver/dll.cc:74:13 in myodbc_init
```

**Comment by alexey-milovidov** [comment]
Sanitizers cannot instrument pre-built shared libraries, including ODBC drivers.
Your report shows the context from inside the ODBC driver.

Our test suite has the tests with ODBC in skip list for sanitizers.
