### ISSUE TITLE
Failed: Timeout >300.0s in integration test on Centos7

### ISSUE THREAD

**Issue by hssrs** [ClickHouse/ClickHouse#21362]
**Operating system**
CentOS Linux release 7.6.1810 (Core)
**Cmake version**
3.15.5
**Ninja version**
1.9.0
**Compiler name and version**
GCC-10.2.0
**Full cmake and/or ninja output**
_**Yes, the Clickhouse has been compiled successfully.**_
```
cmake .. \
    -DCMAKE_BUILD_TYPE=Debug \
    -DENABLE_CLICKHOUSE_ALL=OFF \
    -DENABLE_CLICKHOUSE_SERVER=ON \
    -DENABLE_CLICKHOUSE_CLIENT=ON \
    -DUSE_STATIC_LIBRARIES=ON \
    -DUSE_UNWIND=ON \
    -DSPLIT_SHARED_LIBRARIES=0 \
    -DENABLE_UTILS=OFF \
    -DENABLE_MYSQL=ON
```
**_Sorry, I didn't see any tag about the `test`, so I used the `build` tag._**

I read the official documentation on testing from [this link](https://github.com/ClickHouse/ClickHouse/tree/master/tests/integration#clickhouse-integration-tests) and deployed the testing environment.  However, I get the timeout error `E           Failed: Timeout >300.0s` .

```
[hssrs[11:39:13]integration]$ pytest -v test_odbc_interaction
======================================================================================================== test session starts =========================================================================================================platform linux -- Python 3.7.9, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- /home/hssrs/softwares/pyenv-master/versions/3.7.9/bin/python3.7
cachedir: .pytest_cache
rootdir: /home/hssrs/ClickHouse/tests/integration, configfile: pytest.ini
plugins: timeout-1.4.2
timeout: 300.0s
timeout method: signal
timeout func_only: False
collected 11 items

test_odbc_interaction/test.py::test_mysql_simple_select_works ERROR [  9%] 

test_odbc_interaction/test.py::test_mysql_insert ERROR [ 18%] 

test_odbc_interaction/test.py::test_sqlite_simple_select_function_works ERROR [ 27%] 

test_odbc_interaction/test.py::test_sqlite_simple_select_storage_works ERROR [ 36%] 

test_odbc_interaction/test.py::test_sqlite_odbc_hashed_dictionary ERROR [ 45%] 

test_odbc_interaction/test.py::test_sqlite_odbc_cached_dictionary ERROR [ 54%] 

test_odbc_interaction/test.py::test_postgres_odbc_hashed_dictionary_with_schema ERROR [ 63%] 

test_odbc_interaction/test.py::test_postgres_odbc_hashed_dictionary_no_tty_pipe_overflow ERROR [ 72%] 

test_odbc_interaction/test.py::test_postgres_insert ERROR [ 81%]

test_odbc_interaction/test.py::test_bridge_dies_with_parent ERROR [ 90%] 

test_odbc_interaction/test.py::test_odbc_postgres_date_data_type ERROR [100%]

=============================================================================================================== ERRORS ===============================================================================================================__________________________________________________________________________________________ ERROR at setup of test_mysql_simple_select_works __________________________________________________________________________________________

    @pytest.fixture(scope="module")
    def started_cluster():
        try:
>           cluster.start()

test_odbc_interaction/test.py:61:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ helpers/cluster.py:650: in start
    subprocess_check_call(self.base_mysql_cmd + common_opts)
helpers/cluster.py:60: in subprocess_check_call
    run_and_check(args)
helpers/cluster.py:49: in run_and_check
    res = subprocess.run(args, stdout=stdout, stderr=stderr, env=env, shell=shell)
../../../softwares/pyenv-master/versions/3.7.9/lib/python3.7/subprocess.py:490: in run
    stdout, stderr = process.communicate(input, timeout=timeout)
../../../softwares/pyenv-master/versions/3.7.9/lib/python3.7/subprocess.py:964: in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
../../../softwares/pyenv-master/versions/3.7.9/lib/python3.7/subprocess.py:1715: in _communicate
    ready = selector.select(timeout)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <selectors.PollSelector object at 0x7f517ddfed50>, timeout = None

    def select(self, timeout=None):
        # This is shared between poll() and epoll().
        # epoll() has a different signature and handling of timeout parameter.
        if timeout is None:
            timeout = None
        elif timeout <= 0:
            timeout = 0
        else:
            # poll() has a resolution of 1 millisecond, round away from
            # zero to wait *at least* timeout seconds.
            timeout = math.ceil(timeout * 1e3)
        ready = []
        try:
>           fd_event_list = self._selector.poll(timeout)
E           Failed: Timeout >300.0s

../../../softwares/pyenv-master/versions/3.7.9/lib/python3.7/selectors.py:415: Failed
------------------------------------------------------------------------------------------------------- Captured stdout setup --------------------------------------------------------------------------------------------------------Cluster start called. is_up=False, destroy_dirs=True
Trying to kill unstopped containers...
Unstopped containers killed
Setup directory for instance: node1 destroy_dirs: True
Copy common default production configuration from /home/hssrs/ClickHouse/build_21_3_1/programs/server
Create directory for configuration generated in this helper
Create directory for common tests configuration
Copy common configuration from helpers
Generate and write macros file
Copy custom test config files ['/home/hssrs/ClickHouse/tests/integration/test_odbc_interaction/configs/openssl.xml', '/home/hssrs/ClickHouse/tests/integration/test_odbc_interaction/configs/odbc_logging.xml', '/home/hssrs/ClickHouse/tests/integration/test_odbc_interaction/configs/enable_dictionaries.xml', '/home/hssrs/ClickHouse/tests/integration/test_odbc_interaction/configs/dictionaries/sqlite3_odbc_hashed_dictionary.xml', '/home/hssrs/ClickHouse/tests/integration/test_odbc_interaction/configs/dictionaries/sqlite3_odbc_cached_dictionary.xml', '/home/hssrs/ClickHouse/tests/integration/test_odbc_interaction/configs/dictionaries/postgres_odbc_hashed_dictionary.xml'] to /home/hssrs/ClickHouse/tests/integration/test_odbc_interaction/_instances/node1/configs/config.d
Setup database dir /home/hssrs/ClickHouse/tests/integration/test_odbc_interaction/_instances/node1/database
Setup logs dir /home/hssrs/ClickHouse/tests/integration/test_odbc_interaction/_instances/node1/logs
Env {'LLVM_PROFILE_FILE': '/var/lib/clickhouse/server_%h_%p_%m.profraw'} stored in /home/hssrs/ClickHouse/tests/integration/test_odbc_interaction/_instances/node1/env_file
Entrypoint cmd: bash -c "clickhouse server --config-file=/etc/clickhouse-server/config.xml --log-file=/var/log/clickhouse-server/clickhouse-server.log --errorlog-file=/var/log/clickhouse-server/clickhouse-server.err.log --daemon; tail -f /dev/null"
Setup MySQL
Failed to start cluster:
Timeout >300.0s
None
------------------------------------------------------------------------------------------------------- Captured stderr setup --------------------------------------------------------------------------------------------------------Removing network clickhouse_default
Network clickhouse_default not found.
Traceback (most recent call last):
  File "/home/hssrs/ClickHouse/tests/integration/helpers/cluster.py", line 650, in start
    subprocess_check_call(self.base_mysql_cmd + common_opts)
  File "/home/hssrs/ClickHouse/tests/integration/helpers/cluster.py", line 60, in subprocess_check_call
    run_and_check(args)
  File "/home/hssrs/ClickHouse/tests/integration/helpers/cluster.py", line 49, in run_and_check
    res = subprocess.run(args, stdout=stdout, stderr=stderr, env=env, shell=shell)
  File "/home/hssrs/softwares/pyenv-master/versions/3.7.9/lib/python3.7/subprocess.py", line 490, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/home/hssrs/softwares/pyenv-master/versions/3.7.9/lib/python3.7/subprocess.py", line 964, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/home/hssrs/softwares/pyenv-master/versions/3.7.9/lib/python3.7/subprocess.py", line 1715, in _communicate
    ready = selector.select(timeout)
  File "/home/hssrs/softwares/pyenv-master/versions/3.7.9/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home/hssrs/softwares/pyenv-master/versions/3.7.9/lib/python3.7/site-packages/pytest_timeout.py", line 200, in handler
    timeout_sigalrm(item, params.timeout)
  File "/home/hssrs/softwares/pyenv-master/versions/3.7.9/lib/python3.7/site-packages/pytest_timeout.py", line 375, in timeout_sigalrm
    pytest.fail("Timeout >%ss" % timeout)
  File "/home/hssrs/softwares/pyenv-master/versions/3.7.9/lib/python3.7/site-packages/_pytest/outcomes.py", line 153, in fail
    raise Failed(msg=msg, pytrace=pytrace)
Failed: Timeout >300.0s
......
```
Is there something I misunderstood or  something wrong with my environment configuration? I will be appreciate if there's any suggestion.

**Comment by nikitamikhaylov** [comment]
You can run integration test in docker with `runner` script in `tests/integration` directory.

**Comment by hssrs** [comment]
> You can run integration test in docker with `runner` script in `tests/integration` directory.

@nikitamikhaylov Hi, I tried using the Docker earlier based on the instructions in [README.md](https://github.com/ClickHouse/ClickHouse/tree/master/tests/integration#running-with-runner-script) , but  the tests themselves run docker-compose, which fails to work in my develop environment. So, is there a more detailed documentation on how to handle integration testing?

**Comment by nikitamikhaylov** [comment]
No :( Try to run another test, for example 'test_logs_level' (i don't exactly remember its name), because it is very lightweight, it starts only on ClickHouse instance.

**Comment by hssrs** [comment]
> No :( Try to run another test, for example 'test_logs_level' (i don't exactly remember its name), because it is very lightweight, it starts only on ClickHouse instance.

Yes, it contains only one item, but same error occurs againe. I have no idea how to check the environment is deployed successful or not.

**Comment by hssrs** [comment]
I solved the problem and came back here to share my solution.  @nikitamikhaylov, Thank you for your help :)
The problem is caused by network. If you have a proxy configured for Docker as I do, It may help to change the proxy or simply pull the images manually (You can find the required image from `$ClickHouse/docker/test/integration/runner/compose/xxx.yml`).
