### ISSUE TITLE
Memory limit sometimes doesn't work with TSan

### ISSUE THREAD

**Issue by CurtizJ** [ClickHouse/ClickHouse#22008]
(you don't have to strictly follow this form)

**Describe the bug**
The following query leads to OOM if server was built with thread sanitizer.

```sql
SELECT range(65535) FROM system.one ARRAY JOIN range(65536) AS number

**Comment by alexey-milovidov** [comment]
Because `new`/`delete` hooks are disabled with sanitizers.

**Comment by alexey-milovidov** [comment]
But we have to find a way to enable them.

**Comment by nikitamikhaylov** [comment]
@alexey-milovidov 
ThreadSanitizer redefines global new and delete [here](https://github.com/llvm/llvm-project/blob/3d039f65015f0e7878b77c542a89493dcdd755d0/compiler-rt/lib/tsan/rtl/tsan_new_delete.cpp#L118). InternalFree is declared [here](https://github.com/llvm/llvm-project/blob/3d039f65015f0e7878b77c542a89493dcdd755d0/compiler-rt/lib/sanitizer_common/sanitizer_allocator.cpp#L205)
And it uses Deallocate method from SanitizerAllocatorCombined declared [here](https://github.com/llvm/llvm-project/blob/3d039f65015f0e7878b77c542a89493dcdd755d0/compiler-rt/lib/sanitizer_common/sanitizer_allocator_combined.h#L89)
Which will use some SizeClassAllocator and its methods. The idea of this allocator is to divide all allocation by its size to some buckets.

The main methods are [GetSizeClass](https://github.com/llvm/llvm-project/blob/62ec4ac90738a5f2d209ed28c822223e58aaaeb7/compiler-rt/lib/sanitizer_common/sanitizer_allocator_primary64.h#L180) and [ClassIdToSize](https://github.com/llvm/llvm-project/blob/62ec4ac90738a5f2d209ed28c822223e58aaaeb7/compiler-rt/lib/sanitizer_common/sanitizer_allocator_primary64.h#L314) 

There method are fully defined by constants and [here](https://github.com/llvm/llvm-project/blob/62ec4ac90738a5f2d209ed28c822223e58aaaeb7/compiler-rt/lib/sanitizer_common/sanitizer_allocator_size_class_map.h#L145) is the main method to get size of allocation.

P.S. I am very confused about mixture of overloading and specializations for 32 and 64bit systems, but I think this is because of broken GoToDefinition in VSCode for this project. 

So, how I think we can simply implement some function in our codebase based on these constants and use it in out MemoryTracker.

**Comment by alexey-milovidov** [comment]
Let's try to do it. Caveats:

- we can throw from `new` but cannot throw exception from C function malloc;
- it is needed for TSan, ASan and MSan (I hope there will be no many differencies).

**Comment by nikitamikhaylov** [comment]
@alexey-milovidov 

> Because `new`/`delete` hooks are disabled with sanitizers.

BTW, It is only disabled for gcc compiler https://github.com/ClickHouse/ClickHouse/blob/6fb444f732b6c6315e5d511690949175ca21d6c8/src/CMakeLists.txt#L143-L144

And do you mean these operator overloading under the word 'hook'? https://github.com/ClickHouse/ClickHouse/blob/b9a7d59f3bf09d898191a18aa23be2ee6af0ecef/src/Common/new_delete.cpp#L98-L122

The main problem is that sanitizer's `new`/`delete` overloadings behave like LD_PRELOAD. So we don't have any access to them. For example, we can write `assert(false)` in operator new overloading in our codebase, but the server will start and work...

**Comment by alexey-milovidov** [comment]
> And do you mean these operator overloading under the word 'hook'? 

Yes.

> BTW, It is only disabled for gcc compiler 

I see, there is a case when jemalloc is disabled:
```
malloc_usable_size(ptr)
```
It's more complicated...

**Comment by alexey-milovidov** [comment]
BTW, the case from @CurtizJ may be not related to new/delete.

**Comment by alexey-milovidov** [comment]
@nikitamikhaylov This is the issue with parallel formatting.

**Comment by alexey-milovidov** [comment]
```
curl 'http://localhost:8123/' -d "SELECT range(65535) FROM system.one ARRAY JOIN range(65536) AS number" | pv > /dev/null
```

```
gdb
br MemoryTracker::logMemoryUsage
```

```
Thread 142 "Formatter" hit Breakpoint 1, MemoryTracker::logMemoryUsage (this=this@entry=0x121aa020 <total_memory_tracker>, current=current@entry=41950399192) at ../src/Common/MemoryTracker.cpp:123
123         const auto * description = description_ptr.load(std::memory_order_relaxed);
(gdb) bt
#0  MemoryTracker::logMemoryUsage (this=this@entry=0x121aa020 <total_memory_tracker>, current=current@entry=41950399192) at ../src/Common/MemoryTracker.cpp:123
#1  0x00000000089e79b4 in MemoryTracker::updatePeak (this=0x121aa020 <total_memory_tracker>, will_be=41950399192) at ../src/Common/MemoryTracker.cpp:242
#2  MemoryTracker::alloc (this=0x121aa020 <total_memory_tracker>, size=<optimized out>) at ../src/Common/MemoryTracker.cpp:226
#3  0x00000000089e79c7 in MemoryTracker::alloc (this=0x7fff0efd9570, size=41950399192) at ../src/Common/MemoryTracker.cpp:229
#4  0x0000000008a11c78 in Allocator<false, false>::realloc (this=0x7fff42efd098, buf=0x7fece3167000, old_size=34359771150, new_size=50082873360, alignment=0) at ../src/Common/Allocator.h:138
#5  0x000000000f0552b9 in DB::Memory<Allocator<false, false> >::resize (this=0x7fff42efd098, new_size=<optimized out>) at ../src/IO/BufferWithOwnMemory.h:88
#6  DB::BufferWithOutsideMemory<DB::WriteBuffer>::nextImpl (this=0x7fff0efd93f8) at ../src/IO/BufferWithOwnMemory.h:178
#7  0x000000000eff50ac in DB::WriteBuffer::next (this=0x7fff0efd93f8) at ../src/IO/WriteBuffer.h:47
#8  DB::IOutputFormat::flush (this=<optimized out>) at ../src/Processors/Formats/IOutputFormat.cpp:108
#9  0x000000000f054853 in DB::ParallelFormattingOutputFormat::formatterThreadFunction (this=0x7fff42eadc18, current_unit_number=<optimized out>)
    at ../src/Processors/Formats/Impl/ParallelFormattingOutputFormat.cpp:188
#10 0x0000000008a099db in std::__1::__function::__policy_func<void ()>::operator()() const (this=0x7fff0efd9480) at ../contrib/libcxx/include/functional:2221
#11 std::__1::function<void ()>::operator()() const (this=0x7fff0efd9480) at ../contrib/libcxx/include/functional:2560
#12 ThreadPoolImpl<ThreadFromGlobalPool>::worker (this=this@entry=0x7fff42eadd78, thread_it=thread_it@entry=...) at ../src/Common/ThreadPool.cpp:247
#13 0x0000000008a0b39f in ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::{lambda()#3}::operator()() const (this=<optimized out>)
    at ../src/Common/ThreadPool.cpp:124
#14 std::__1::__invoke_constexpr<ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::{lambda()#3}&> (__f=...)
    at ../contrib/libcxx/include/type_traits:3682
#15 std::__1::__apply_tuple_impl<ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::{lambda()#3}&, std::__1::tuple<>&>(ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::{lambda()#3}&, std::__1::tuple<>&, std::__1::__tuple_indices<>) (__f=..., __t=...)
    at ../contrib/libcxx/include/tuple:1415
#16 std::__1::apply<ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::{lambda()#3}&, std::__1::tuple<>&>(ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::{lambda()#3}&, std::__1::tuple<>&) (__f=..., __t=...) at ../contrib/libcxx/include/tuple:1424
#17 ThreadFromGlobalPool::ThreadFromGlobalPool<ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::{lambda()#3}>(ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::{lambda()#3}&&)::{lambda()#1}::operator()() (this=<optimized out>) at ../src/Common/ThreadPool.h:178
#18 0x0000000008a0835b in std::__1::__function::__policy_func<void ()>::operator()() const (this=0x7fff0efd9780) at ../contrib/libcxx/include/functional:2221
#19 std::__1::function<void ()>::operator()() const (this=0x7fff0efd9780) at ../contrib/libcxx/include/functional:2560
#20 ThreadPoolImpl<std::__1::thread>::worker (this=0x7ffff70d7a00, thread_it=...) at ../src/Common/ThreadPool.cpp:247
#21 0x0000000008a0a653 in ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::{lambda()#3}::operator()() const (this=0x28)
    at ../src/Common/ThreadPool.cpp:124
#22 std::__1::__invoke<ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::{lambda()#3}> (__f=...)
    at ../contrib/libcxx/include/type_traits:3676
#23 std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::{lambda()#3}>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::{lambda()#3}>&, std::__1::__tuple_indices<>) (__t=...) at ../contrib/libcxx/include/thread:280
#24 std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::{lambda()#3}> >(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::{lambda()#3}>) (__vp=<optimized out>) at ../contrib/libcxx/include/thread:291
#25 0x00007ffff7f77609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#26 0x00007ffff7e9e293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by alexey-milovidov** [comment]
Looks like there are two issues:
- query context is not attached to the parallel formatting threads;
- parallel formatting may want to allocate excessive amounts of memory.
