### ISSUE TITLE
./docker/test/fuzzer/run-fuzzer.sh [base][common][DateLUTImpl] addMonthsIndex cannot be represented in type 'long'

### ISSUE THREAD

**Issue by songenjie** [ClickHouse/ClickHouse#22023]
```log
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../base/common/../common/DateLUTImpl.h:1076:56 in 
../base/common/../common/DateLUTImpl.h:1076: runtime error: signed integer overflow: 3 + 9223372036854775807 cannot be represented in type 'long'
    #0 0x164bd9cb in StrongTypedef<unsigned int, DateLUTImpl::LUTIndexTag> DateLUTImpl::addMonthsIndex<long>(long, long) const (/workspace/clickhouse+0x164bd9cb)
    #1 0x164bd744 in DateLUTImpl::addMonths(long, long) const (/workspace/clickhouse+0x164bd744)
2021.03.23 12:15:15.879970 [ 42 ] {} <Trace> BaseDaemon: Received signal -3
    #2 0x164bd598 in void DB::Adder<DB::AddMonthsImpl>::vectorConstant<DB::PODArray<unsigned int, 4096ul, Allocator<false, false>, 15ul, 16ul>, DB::PODArray<unsigned int, 4096ul, Allocator<false, false>, 15ul, 16ul> >(DB::PODArray<unsigned int, 4096ul, Allocator<false, false>, 15ul, 16ul> const&, DB::PODArray<unsigned int, 4096ul, Allocator<false, false>, 15ul, 16ul>&, long, DateLUTImpl const&) const (/workspace/clickhouse+0x164bd598)
    #3 0x164baa78 in DB::DateTimeAddIntervalImpl<DB::DataTypeDateTime, DB::DataTypeDateTime, DB::AddMonthsImpl>::execute(DB::AddMonthsImpl, std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&) (/workspace/clickhouse+0x164baa78)
    #4 0x164b9174 in DB::FunctionDateOrDateTimeAddInterval<DB::AddMonthsImpl>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/workspace/clickhouse+0x164b9174)
    #5 0x12553f76 in DB::DefaultExecutable::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/workspace/clickhouse+0x12553f76)
    #6 0x12ffa5eb in DB::ExecutableFunctionAdaptor::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const (/workspace/clickhouse+0x12ffa5eb)
    #7 0x12ffb50d in DB::ExecutableFunctionAdaptor::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const (/workspace/clickhouse+0x12ffb50d)
    #8 0x12df4424 in DB::IFunctionBase::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const (/workspace/clickhouse+0x12df4424)
    #9 0x13287ba5 in DB::FunctionBinaryArithmetic<DB::PlusImpl, DB::NamePlus, true, true>::executeDateTimeIntervalPlusMinus(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, std::__1::shared_ptr<DB::IFunctionOverloadResolver> const&) const (/workspace/clickhouse+0x13287ba5)
    #10 0x132869d3 in DB::FunctionBinaryArithmetic<DB::PlusImpl, DB::NamePlus, true, true>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/workspace/clickhouse+0x132869d3)
    #11 0x13285eeb in DB::FunctionBinaryArithmeticWithConstants<DB::PlusImpl, DB::NamePlus, true, true>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/workspace/clickhouse+0x13285eeb)
    #12 0x12553f76 in DB::DefaultExecutable::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/workspace/clickhouse+0x12553f76)
    #13 0x12ffa5eb in DB::ExecutableFunctionAdaptor::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const (/workspace/clickhouse+0x12ffa5eb)
    #14 0x12ffb50d in DB::ExecutableFunctionAdaptor::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const (/workspace/clickhouse+0x12ffb50d)
    #15 0x1a20f623 in DB::executeAction(DB::ExpressionActions::Action const&, DB::(anonymous namespace)::ExecutionContext&, bool) obj-x86_64-linux-gnu/../src/Interpreters/ExpressionActions.cpp:334:56
    #16 0x1a20eb5f in DB::ExpressionActions::execute(DB::Block&, unsigned long&, bool) const obj-x86_64-linux-gnu/../src/Interpreters/ExpressionActions.cpp:450:13
    #17 0x1b1ef7f8 in DB::ITTLAlgorithm::executeExpressionAndGetColumn(std::__1::shared_ptr<DB::ExpressionActions> const&, DB::Block const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) obj-x86_64-linux-gnu/../src/DataStreams/ITTLAlgorithm.cpp:43:17
    #18 0x1b1eed36 in DB::TTLUpdateInfoAlgorithm::execute(DB::Block&) obj-x86_64-linux-gnu/../src/DataStreams/TTLUpdateInfoAlgorithm.cpp:17:23
2021.03.23 12:15:15.880471 [ 165 ] {} <Fatal> BaseDaemon: ########################################
2021.03.23 12:15:15.880503 [ 165 ] {} <Fatal> BaseDaemon: (version 21.4.1.6317, build id: 4DFA14D70F816EAC94EDD0375374AC3F17A592C8) (from thread 156) (no query) Received signal Unknown signal (-3)    #19 0x1b1ea656 in DB::TTLBlockInputStream::readImpl() obj-x86_64-linux-gnu/../src/DataStreams/TTLBlockInputStream.cpp:107:20
```

**Comment by alexey-milovidov** [comment]
#22006
