### ISSUE TITLE
Can't connect to ZooKeeper Connection time-out when run integration test

### ISSUE THREAD

**Issue by marising** [ClickHouse/ClickHouse#22422]
1.  I tried to run integration test with reference https://github.com/ClickHouse/ClickHouse/blob/master/tests/integration/README.md,  but get the exception : Can't Connect to Zookeeper Connection time-out.

2.  docker version
```
docker version
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:05:38 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	false
``` 
3. run test
```
./runner --command=bash
// In Docker
pytest test_ddl_alter_query -ss
```

4.  Can't connect to ZooKeeper Connection time-out
```
root@A03-R05-I24-118-035PFKE:/ClickHouse/tests/integration# pytest test_ddl_alter_query -ss
============================================================================================================================ test session starts =============================================================================================================================
platform linux -- Python 3.6.9, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /ClickHouse/tests/integration, configfile: pytest.ini
plugins: timeout-1.4.2
timeout: 300.0s
timeout method: signal
timeout func_only: False
collecting ... ENV                                LS_COLORS rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
ENV                                LESSCLOSE /usr/bin/lesspipe %s %s
ENV                              PYTEST_OPTS
ENV                                       TZ Europe/Moscow
ENV                                 HOSTNAME A03-R05-I24-118-035PFKE.JD.LOCAL
ENV                                   OLDPWD /ClickHouse/tests
ENV         CLICKHOUSE_TESTS_SERVER_BIN_PATH /clickhouse
ENV           DOCKER_MYSQL_GOLANG_CLIENT_TAG latest
ENV                                JAVA_HOME /usr/lib/jvm/java-1.8-openjdk
ENV         CLICKHOUSE_TESTS_BASE_CONFIG_DIR /clickhouse-config
ENV                                CLASSPATH .:/usr/lib/jvm/java-1.8-openjdk/lib:/usr/lib/jvm/java-1.8-openjdk/jre/lib:
ENV             DOCKER_MYSQL_JAVA_CLIENT_TAG latest
ENV                                      PWD /ClickHouse/tests/integration
ENV                                     HOME /root
ENV                  DOCKER_KERBEROS_KDC_TAG latest
ENV       CLICKHOUSE_ODBC_BRIDGE_BINARY_PATH /clickhouse-odbc-bridge
ENV                           DOCKER_VERSION 5:19.03.13~3-0~ubuntu-bionic
ENV                           DOCKER_CHANNEL stable
ENV               DOCKER_MYSQL_JS_CLIENT_TAG latest
ENV                                     TERM xterm
ENV                                    SHLVL 1
ENV         CLICKHOUSE_TESTS_CLIENT_BIN_PATH /clickhouse
ENV                                 JRE_HOME /usr/lib/jvm/java-1.8-openjdk/jre
ENV                                     PATH /usr/lib/jvm/java-1.8-openjdk/bin:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV              DOCKER_MYSQL_PHP_CLIENT_TAG latest
ENV        DOCKER_POSTGRESQL_JAVA_CLIENT_TAG latest
ENV                                 LESSOPEN | /usr/bin/lesspipe %s
ENV                                        _ /usr/local/bin/pytest
CLUSTER INIT base_config_dir:/clickhouse-config
collected 1 item

test_ddl_alter_query/test.py Cluster start called. is_up=False, destroy_dirs=True
Trying to kill unstopped containers...
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

Unstopped containers killed
Setup directory for instance: node1 destroy_dirs: True
Copy common default production configuration from /clickhouse-config
Create directory for configuration generated in this helper
Create directory for common tests configuration
Copy common configuration from helpers
Generate and write macros file
Copy custom test config files ['/ClickHouse/tests/integration/test_ddl_alter_query/configs/remote_servers.xml'] to /ClickHouse/tests/integration/test_ddl_alter_query/_instances/node1/configs/config.d
Setup database dir /ClickHouse/tests/integration/test_ddl_alter_query/_instances/node1/database
Setup logs dir /ClickHouse/tests/integration/test_ddl_alter_query/_instances/node1/logs
Env {} stored in /ClickHouse/tests/integration/test_ddl_alter_query/_instances/node1/env_file
Entrypoint cmd: clickhouse server --config-file=/etc/clickhouse-server/config.xml --log-file=/var/log/clickhouse-server/clickhouse-server.log --errorlog-file=/var/log/clickhouse-server/clickhouse-server.err.log
Setup directory for instance: node2 destroy_dirs: True
Copy common default production configuration from /clickhouse-config
Create directory for configuration generated in this helper
Create directory for common tests configuration
Copy common configuration from helpers
Generate and write macros file
Copy custom test config files ['/ClickHouse/tests/integration/test_ddl_alter_query/configs/remote_servers.xml'] to /ClickHouse/tests/integration/test_ddl_alter_query/_instances/node2/configs/config.d
Setup database dir /ClickHouse/tests/integration/test_ddl_alter_query/_instances/node2/database
Setup logs dir /ClickHouse/tests/integration/test_ddl_alter_query/_instances/node2/logs
Env {} stored in /ClickHouse/tests/integration/test_ddl_alter_query/_instances/node2/env_file
Entrypoint cmd: clickhouse server --config-file=/etc/clickhouse-server/config.xml --log-file=/var/log/clickhouse-server/clickhouse-server.log --errorlog-file=/var/log/clickhouse-server/clickhouse-server.err.log
Setup directory for instance: node3 destroy_dirs: True
Copy common default production configuration from /clickhouse-config
Create directory for configuration generated in this helper
Create directory for common tests configuration
Copy common configuration from helpers
Generate and write macros file
Copy custom test config files ['/ClickHouse/tests/integration/test_ddl_alter_query/configs/remote_servers.xml'] to /ClickHouse/tests/integration/test_ddl_alter_query/_instances/node3/configs/config.d
Setup database dir /ClickHouse/tests/integration/test_ddl_alter_query/_instances/node3/database
Setup logs dir /ClickHouse/tests/integration/test_ddl_alter_query/_instances/node3/logs
Env {} stored in /ClickHouse/tests/integration/test_ddl_alter_query/_instances/node3/env_file
Entrypoint cmd: clickhouse server --config-file=/etc/clickhouse-server/config.xml --log-file=/var/log/clickhouse-server/clickhouse-server.log --errorlog-file=/var/log/clickhouse-server/clickhouse-server.err.log
Setup directory for instance: node4 destroy_dirs: True
Copy common default production configuration from /clickhouse-config
Create directory for configuration generated in this helper
Create directory for common tests configuration
Copy common configuration from helpers
Generate and write macros file
Copy custom test config files ['/ClickHouse/tests/integration/test_ddl_alter_query/configs/remote_servers.xml'] to /ClickHouse/tests/integration/test_ddl_alter_query/_instances/node4/configs/config.d
Setup database dir /ClickHouse/tests/integration/test_ddl_alter_query/_instances/node4/database
Setup logs dir /ClickHouse/tests/integration/test_ddl_alter_query/_instances/node4/logs
Env {} stored in /ClickHouse/tests/integration/test_ddl_alter_query/_instances/node4/env_file
Entrypoint cmd: clickhouse server --config-file=/etc/clickhouse-server/config.xml --log-file=/var/log/clickhouse-server/clickhouse-server.log --errorlog-file=/var/log/clickhouse-server/clickhouse-server.err.log
Setup ZooKeeper
Creating network "roottestddlalterquery_default" with the default driver
Creating roottestddlalterquery_zoo3_1 ... done
Creating roottestddlalterquery_zoo1_1 ... done
Creating roottestddlalterquery_zoo2_1 ... done
Can't connect to ZooKeeper Connection time-out
Can't connect to ZooKeeper Connection time-out
Can't connect to ZooKeeper Connection time-out
Can't connect to ZooKeeper Connection time-out
Can't connect to ZooKeeper Connection time-out
Can't connect to ZooKeeper Connection time-out
Can't connect to ZooKeeper Connection time-out
Can't connect to ZooKeeper Connection time-out
Failed to start cluster:
Cannot wait ZooKeeper container
Traceback (most recent call last):
  File "/ClickHouse/tests/integration/helpers/cluster.py", line 604, in start
    self.wait_zookeeper_to_start(120)
  File "/ClickHouse/tests/integration/helpers/cluster.py", line 477, in wait_zookeeper_to_start
    raise Exception("Cannot wait ZooKeeper container")
Exception: Cannot wait ZooKeeper container
None
Killing roottestddlalterquery_zoo2_1 ... done
Killing roottestddlalterquery_zoo1_1 ... done
Killing roottestddlalterquery_zoo3_1 ... done
Removing roottestddlalterquery_zoo2_1 ... done
Removing roottestddlalterquery_zoo1_1 ... done
Removing roottestddlalterquery_zoo3_1 ... done
Removing network roottestddlalterquery_default
E

=================================================================================================================================== ERRORS ===================================================================================================================================
________________________________________________________________________________________________________________________ ERROR at setup of test_alter ________________________________________________________________________________________________________________________

    @pytest.fixture(scope="module")
    def started_cluster():
        try:
>           cluster.start()

test_ddl_alter_query/test.py:16:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
helpers/cluster.py:604: in start
    self.wait_zookeeper_to_start(120)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <helpers.cluster.ClickHouseCluster object at 0x7f43e71382b0>, timeout = 120

    def wait_zookeeper_to_start(self, timeout=60):
        start = time.time()
        while time.time() - start < timeout:
            try:
                for instance in ['zoo1', 'zoo2', 'zoo3']:
                    conn = self.get_kazoo_client(instance)
                    conn.get_children('/')
                print("All instances of ZooKeeper started")
                return
            except Exception as ex:
                print("Can't connect to ZooKeeper " + str(ex))
                time.sleep(0.5)

>       raise Exception("Cannot wait ZooKeeper container")
E       Exception: Cannot wait ZooKeeper container

helpers/cluster.py:477: Exception
----------------------------------------------------------------------------------------------------------------------------- Captured log setup -----------------------------------------------------------------------------------------------------------------------------
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:515 Failed connecting to Zookeeper within the connection retry policy.
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:515 Failed connecting to Zookeeper within the connection retry policy.
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:515 Failed connecting to Zookeeper within the connection retry policy.
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:515 Failed connecting to Zookeeper within the connection retry policy.
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:515 Failed connecting to Zookeeper within the connection retry policy.
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:515 Failed connecting to Zookeeper within the connection retry policy.
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:515 Failed connecting to Zookeeper within the connection retry policy.
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:611 Connection dropped: socket connection error: Connection timed out
WARNING  kazoo.client:connection.py:515 Failed connecting to Zookeeper within the connection retry policy.
========================================================================================================================== short test summary info ===========================================================================================================================
ERROR test_ddl_alter_query/test.py::test_alter - Exception: Cannot wait ZooKeeper container
======================================================================================================================== 1 error in 139.56s (0:02:19) ========================================================================================================================
```

5.   zookeeper process
```
root@A03-R05-I24-118-035PFKE:/ClickHouse/tests/integration# ps -ef | grep zookeeper
1000        659    610  0 05:37 ?        00:00:01 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java -Dzookeeper.log.dir=. -Dzookeeper.root.logger=INFO,CONSOLE -cp /zookeeper-3.4.12/bin/../build/classes:/zookeeper-3.4.12/bin/../build/lib/*.jar:/zookeeper-3.4.12/bin/../lib/slf4j-log4j12-1.7.25.jar:/zookeeper-3.4.12/bin/../lib/slf4j-api-1.7.25.jar:/zookeeper-3.4.12/bin/../lib/netty-3.10.6.Final.jar:/zookeeper-3.4.12/bin/../lib/log4j-1.2.17.jar:/zookeeper-3.4.12/bin/../lib/jline-0.9.94.jar:/zookeeper-3.4.12/bin/../lib/audience-annotations-0.5.0.jar:/zookeeper-3.4.12/bin/../zookeeper-3.4.12.jar:/zookeeper-3.4.12/bin/../src/java/lib/*.jar:/conf: -Dzookeeper.forceSync=no -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.local.only=false org.apache.zookeeper.server.quorum.QuorumPeerMain /conf/zoo.cfg
1000        674    554  0 05:37 ?        00:00:01 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java -Dzookeeper.log.dir=. -Dzookeeper.root.logger=INFO,CONSOLE -cp /zookeeper-3.4.12/bin/../build/classes:/zookeeper-3.4.12/bin/../build/lib/*.jar:/zookeeper-3.4.12/bin/../lib/slf4j-log4j12-1.7.25.jar:/zookeeper-3.4.12/bin/../lib/slf4j-api-1.7.25.jar:/zookeeper-3.4.12/bin/../lib/netty-3.10.6.Final.jar:/zookeeper-3.4.12/bin/../lib/log4j-1.2.17.jar:/zookeeper-3.4.12/bin/../lib/jline-0.9.94.jar:/zookeeper-3.4.12/bin/../lib/audience-annotations-0.5.0.jar:/zookeeper-3.4.12/bin/../zookeeper-3.4.12.jar:/zookeeper-3.4.12/bin/../src/java/lib/*.jar:/conf: -Dzookeeper.forceSync=no -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.local.only=false org.apache.zookeeper.server.quorum.QuorumPeerMain /conf/zoo.cfg
1000        865    712  0 05:37 ?        00:00:02 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java -Dzookeeper.log.dir=. -Dzookeeper.root.logger=INFO,CONSOLE -cp /zookeeper-3.4.12/bin/../build/classes:/zookeeper-3.4.12/bin/../build/lib/*.jar:/zookeeper-3.4.12/bin/../lib/slf4j-log4j12-1.7.25.jar:/zookeeper-3.4.12/bin/../lib/slf4j-api-1.7.25.jar:/zookeeper-3.4.12/bin/../lib/netty-3.10.6.Final.jar:/zookeeper-3.4.12/bin/../lib/log4j-1.2.17.jar:/zookeeper-3.4.12/bin/../lib/jline-0.9.94.jar:/zookeeper-3.4.12/bin/../lib/audience-annotations-0.5.0.jar:/zookeeper-3.4.12/bin/../zookeeper-3.4.12.jar:/zookeeper-3.4.12/bin/../src/java/lib/*.jar:/conf: -Dzookeeper.forceSync=no -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.local.only=false org.apache.zookeeper.server.quorum.QuorumPeerMain /conf/zoo.cfg
root       3242      1  0 06:09 pts/0    00:00:00 grep --color=auto zookeeper
```

**Comment by KochetovNicolai** [comment]
Hi!
Integration tests try to start it's own docker container with zookeeper.
I suspect that if you already has running zookeeper on your server, it can prevent running zookeeper from docker somehow.
Also, why do you have 3 zookeeper processes running on the same server?

**Comment by marising** [comment]
It's seems that the 3 ZooKeeper processes are created by the runner. But I don’t understand why clickhouse can’t connect to zookeeper.
