### ISSUE TITLE
Logical error: Block structure mismatch in QueryPipeline::unitePipelines stream: different columns

### ISSUE THREAD

**Issue by songenjie** [ClickHouse/ClickHouse#23029]
**Describe the bug**
TLPHaving of Sqlancer test

- log [link](https://clickhouse-test-reports.s3.yandex.net/22706/520f4f39eccfcc16491fbc58d9cb44856deb5f53/sqlancer_test/TLPHaving.err)
```
+ java -jar target/sqlancer-1.1.0.jar --num-threads 10 --timeout-seconds 300 --num-queries 1000 --username default --password '' clickhouse --oracle TLPHaving
+ tee /test_output/TLPHaving.out
java.lang.AssertionError: SELECT MAX(((t0.c0)=(t0.c0))), (MIN(t0.c0)) and ((- (COUNT((t0.c0) OR (t0.c0))))), t0.c0, (- (t0.c0)), MIN(t0.c0) FROM t0 GROUP BY t0.c0 HAVING MAX(((t0.c0)>(''))) UNION ALL SELECT MAX(((t0.c0)==(t0.c0))), (MIN(t0.c0)) and ((- (COUNT((t0.c0) OR (t0.c0))))), t0.c0, (- (t0.c0)), MIN(t0.c0) FROM t0 GROUP BY t0.c0 HAVING (NOT (MAX(((t0.c0)>(''))))) UNION ALL SELECT MAX(((t0.c0)=(t0.c0))), (MIN(t0.c0)) and ((- (COUNT((t0.c0) OR (t0.c0))))), t0.c0, (- (t0.c0)), MIN(t0.c0) FROM t0 GROUP BY t0.c0 HAVING ((MAX(((t0.c0)>('')))) IS NULL) SETTINGS aggregate_functions_null_for_empty=1, enable_optimize_predicate_expression=0;
	at sqlancer.common.query.SQLQueryAdapter.checkException(SQLQueryAdapter.java:100)
	at sqlancer.common.query.SQLQueryAdapter.executeAndGet(SQLQueryAdapter.java:131)
	at sqlancer.ComparatorHelper.getResultSetFirstColumnAsString(ComparatorHelper.java:54)
	at sqlancer.clickhouse.oracle.tlp.ClickHouseTLPHavingOracle.check(ClickHouseTLPHavingOracle.java:66)
	at sqlancer.ProviderAdapter.generateAndTestDatabase(ProviderAdapter.java:49)
	at sqlancer.Main$DBMSExecutor.run(Main.java:323)
	at sqlancer.Main$2.run(Main.java:507)
	at sqlancer.Main$2.runThread(Main.java:485)
	at sqlancer.Main$2.run(Main.java:475)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: localhost, port: 8123; localhost:8123 failed to respond
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.getException(ClickHouseExceptionSpecifier.java:91)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:55)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:24)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.getInputStream(ClickHouseStatementImpl.java:633)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:117)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:100)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:95)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:90)
	at sqlancer.common.query.SQLQueryAdapter.executeAndGet(SQLQueryAdapter.java:121)
	... 10 more
Caused by: org.apache.http.NoHttpResponseException: localhost:8123 failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.getInputStream(ClickHouseStatementImpl.java:614)
	... 15 more
```

**Comment by tavplubix** [comment]
```
avtokmakov-dev.sas.yp-c.yandex.net :) CREATE TABLE t0 (c0 String) ENGINE = Log() ;

avtokmakov-dev.sas.yp-c.yandex.net :) INSERT INTO t0(c0) VALUES ('ug9'), ('Lc\\.'), ('l.
:-] P'), ('wz>
:-] am');

avtokmakov-dev.sas.yp-c.yandex.net :) INSERT INTO t0(c0) VALUES ('AN'), ('');

avtokmakov-dev.sas.yp-c.yandex.net :) INSERT INTO t0(c0) VALUES ('?E2?>?'), ('uHCK');

avtokmakov-dev.sas.yp-c.yandex.net :) INSERT INTO t0(c0) VALUES (''), (''), ('^');

avtokmakov-dev.sas.yp-c.yandex.net :) INSERT INTO t0(c0) VALUES (''), ('E'), ('/9');

avtokmakov-dev.sas.yp-c.yandex.net :) INSERT INTO t0(c0) VALUES ('(|P)T'), ('1070269151'), (']|n'), ('J^');

avtokmakov-dev.sas.yp-c.yandex.net :) SELECT (((t0.c0) IS NULL)) or (COUNT('
:-] ?pVa')) FROM t0 GROUP BY t0.c0 HAVING ((t0.c0) IS NULL) UNION ALL SELECT (((t0.c0) IS NULL)) or (COUNT('
:-] ?pVa')) FROM t0 GROUP BY t0.c0 HAVING (NOT (((t0.c0) IS NULL))) UNION ALL SELECT (((t0.c0) IS NULL)) or (COUNT('
:-] ?pVa')) FROM t0 GROUP BY t0.c0 HAVING ((((t0.c0) IS NULL)) IS NULL) SETTINGS aggregate_functions_null_for_empty=1, enable_optimize_predicate_expression=0;

SELECT isNull(t0.c0) OR COUNT('\n?pVa')
FROM t0
GROUP BY t0.c0
HAVING isNull(t0.c0)
UNION ALL
SELECT isNull(t0.c0) OR COUNT('\n?pVa')
FROM t0
GROUP BY t0.c0
HAVING NOT isNull(t0.c0)
UNION ALL
SELECT isNull(t0.c0) OR COUNT('\n?pVa')
FROM t0
GROUP BY t0.c0
HAVING isNull(isNull(t0.c0))
SETTINGS aggregate_functions_null_for_empty = 1, enable_optimize_predicate_expression = 0

Query id: 4f592dae-b34d-4fbf-aa63-c55b3236a2a9

[avtokmakov-dev.sas.yp-c.yandex.net] 2021.04.13 13:23:18.183516 [ 13687 ] {4f592dae-b34d-4fbf-aa63-c55b3236a2a9} <Fatal> : Logical error: 'Block structure mismatch in QueryPipeline::unitePipelines stream: different columns:
or(isNull(c0), count()) UInt8 UInt8(size = 0)
or(isNull(c0), count()) UInt8 Const(size = 0, UInt8(size = 1))'.
[avtokmakov-dev.sas.yp-c.yandex.net] 2021.04.13 13:23:18.185263 [ 25763 ] <Fatal> BaseDaemon: ########################################
[avtokmakov-dev.sas.yp-c.yandex.net] 2021.04.13 13:23:18.185739 [ 25763 ] <Fatal> BaseDaemon: (version 21.5.1.1, build id: 5B9CF526898862D8F41F6361F658AAEDA279D1A2) (from thread 13687) (query_id: 4f592dae-b34d-4fbf-aa63-c55b3236a2a9) Received signal Aborted (6)
[avtokmakov-dev.sas.yp-c.yandex.net] 2021.04.13 13:23:18.186145 [ 25763 ] <Fatal> BaseDaemon: 
[avtokmakov-dev.sas.yp-c.yandex.net] 2021.04.13 13:23:18.186551 [ 25763 ] <Fatal> BaseDaemon: Stack trace: 0x7f66d8ce518b 0x7f66d8cc4859 0x93ad1c6 0x93ad2d5 0x121741a9 0x121717d6 0x12170f35 0x130440df 0x1327b527 0x13268056 0x126d8295 0x1282e1f9 0x1282c385 0x12fd14bd 0x12fddcd8 0x1752b9bc 0x1752c1c0 0x17657723 0x1765459d 0x17653428 0x7f66d8e9a609 0x7f66d8dc1103
[avtokmakov-dev.sas.yp-c.yandex.net] 2021.04.13 13:23:18.188568 [ 25763 ] <Fatal> BaseDaemon: 4. /build/glibc-YYA7BZ/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51: __GI_raise @ 0x4618b in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.31.so
[avtokmakov-dev.sas.yp-c.yandex.net] 2021.04.13 13:23:18.194091 [ 25763 ] <Fatal> BaseDaemon: 5. /build/glibc-YYA7BZ/glibc-2.31/stdlib/abort.c:81: __GI_abort @ 0x25859 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.31.so
[avtokmakov-dev.sas.yp-c.yandex.net] 2021.04.13 13:23:18.338867 [ 25763 ] <Fatal> BaseDaemon: 6. /home/avtokmakov/ch/ClickHouse/build_debug/../src/Common/Exception.cpp:51: DB::handle_error_code(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool, std::__1::vector<void*, std::__1::allocator<void*> > const&) @ 0x93ad1c6 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
[avtokmakov-dev.sas.yp-c.yandex.net] 2021.04.13 13:23:18.466578 [ 25763 ] <Fatal> BaseDaemon: 7. /home/avtokmakov/ch/ClickHouse/build_debug/../src/Common/Exception.cpp:58: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x93ad2d5 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
[avtokmakov-dev.sas.yp-c.yandex.net] 2021.04.13 13:23:18.638498 [ 25763 ] <Fatal> BaseDaemon: 8. /home/avtokmakov/ch/ClickHouse/build_debug/../src/Core/Block.cpp:492: void DB::checkBlockStructure<void>(DB::Block const&, DB::Block const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::'lambda'(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) const @ 0x121741a9 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
[avtokmakov-dev.sas.yp-c.yandex.net] 2021.04.13 13:23:18.810436 [ 25763 ] <Fatal> BaseDaemon: 9. /home/avtokmakov/ch/ClickHouse/build_debug/../src/Core/Block.cpp:519: void DB::checkBlockStructure<void>(DB::Block const&, DB::Block const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x121717d6 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
[avtokmakov-dev.sas.yp-c.yandex.net] 2021.04.13 13:23:18.982957 [ 25763 ] <Fatal> BaseDaemon: 10. /home/avtokmakov/ch/ClickHouse/build_debug/../src/Core/Block.cpp:547: DB::assertBlocksHaveEqualStructure(DB::Block const&, DB::Block const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x12170f35 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
[avtokmakov-dev.sas.yp-c.yandex.net] 2021.04.13 13:23:19.429758 [ 25763 ] <Fatal> BaseDaemon: 11. /home/avtokmakov/ch/ClickHouse/build_debug/../src/Processors/QueryPipeline.cpp:235: DB::QueryPipeline::unitePipelines(std::__1::vector<std::__1::unique_ptr<DB::QueryPipeline, std::__1::default_delete<DB::QueryPipeline> >, std::__1::allocator<std::__1::unique_ptr<DB::QueryPipeline, std::__1::default_delete<DB::QueryPipeline> > > >, unsigned long, std::__1::vector<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor> > >*) @ 0x130440df in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
[avtokmakov-dev.sas.yp-c.yandex.net] 2021.04.13 13:23:19.637869 [ 25763 ] <Fatal> BaseDaemon: 12. /home/avtokmakov/ch/ClickHouse/build_debug/../src/Processors/QueryPlan/UnionStep.cpp:50: DB::UnionStep::updatePipeline(std::__1::vector<std::__1::unique_ptr<DB::QueryPipeline, std::__1::default_delete<DB::QueryPipeline> >, std::__1::allocator<std::__1::unique_ptr<DB::QueryPipeline, std::__1::default_delete<DB::QueryPipeline> > > >, DB::BuildQueryPipelineSettings const&) @ 0x1327b527 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
[avtokmakov-dev.sas.yp-c.yandex.net] 2021.04.13 13:23:19.841444 [ 25763 ] <Fatal> BaseDaemon: 13. /home/avtokmakov/ch/ClickHouse/build_debug/../src/Processors/QueryPlan/QueryPlan.cpp:167: DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&) @ 0x13268056 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
[avtokmakov-dev.sas.yp-c.yandex.net] 2021.04.13 13:23:20.318320 [ 25763 ] <Fatal> BaseDaemon: 14. /home/avtokmakov/ch/ClickHouse/build_debug/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:313: DB::InterpreterSelectWithUnionQuery::execute() @ 0x126d8295 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
[avtokmakov-dev.sas.yp-c.yandex.net] 2021.04.13 13:23:20.934417 [ 25763 ] <Fatal> BaseDaemon: 15. /home/avtokmakov/ch/ClickHouse/build_debug/../src/Interpreters/executeQuery.cpp:561: DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool, DB::ReadBuffer*) @ 0x1282e1f9 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
[avtokmakov-dev.sas.yp-c.yandex.net] 2021.04.13 13:23:21.590522 [ 25763 ] <Fatal> BaseDaemon: 16. /home/avtokmakov/ch/ClickHouse/build_debug/../src/Interpreters/executeQuery.cpp:919: DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool) @ 0x1282c385 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
[avtokmakov-dev.sas.yp-c.yandex.net] 2021.04.13 13:23:22.244622 [ 25763 ] <Fatal> BaseDaemon: 17. /home/avtokmakov/ch/ClickHouse/build_debug/../src/Server/TCPHandler.cpp:290: DB::TCPHandler::runImpl() @ 0x12fd14bd in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
[avtokmakov-dev.sas.yp-c.yandex.net] 2021.04.13 13:23:22.944027 [ 25763 ] <Fatal> BaseDaemon: 18. /home/avtokmakov/ch/ClickHouse/build_debug/../src/Server/TCPHandler.cpp:1548: DB::TCPHandler::run() @ 0x12fddcd8 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
[avtokmakov-dev.sas.yp-c.yandex.net] 2021.04.13 13:23:22.999468 [ 25763 ] <Fatal> BaseDaemon: 19. /home/avtokmakov/ch/ClickHouse/build_debug/../contrib/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x1752b9bc in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
[avtokmakov-dev.sas.yp-c.yandex.net] 2021.04.13 13:23:23.094685 [ 25763 ] <Fatal> BaseDaemon: 20. /home/avtokmakov/ch/ClickHouse/build_debug/../contrib/poco/Net/src/TCPServerDispatcher.cpp:113: Poco::Net::TCPServerDispatcher::run() @ 0x1752c1c0 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
[avtokmakov-dev.sas.yp-c.yandex.net] 2021.04.13 13:23:23.177874 [ 25763 ] <Fatal> BaseDaemon: 21. /home/avtokmakov/ch/ClickHouse/build_debug/../contrib/poco/Foundation/src/ThreadPool.cpp:199: Poco::PooledThread::run() @ 0x17657723 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
[avtokmakov-dev.sas.yp-c.yandex.net] 2021.04.13 13:23:23.254929 [ 25763 ] <Fatal> BaseDaemon: 22. /home/avtokmakov/ch/ClickHouse/build_debug/../contrib/poco/Foundation/src/Thread.cpp:56: Poco::(anonymous namespace)::RunnableHolder::run() @ 0x1765459d in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
[avtokmakov-dev.sas.yp-c.yandex.net] 2021.04.13 13:23:23.331178 [ 25763 ] <Fatal> BaseDaemon: 23. /home/avtokmakov/ch/ClickHouse/build_debug/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345: Poco::ThreadImpl::runnableEntry(void*) @ 0x17653428 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
[avtokmakov-dev.sas.yp-c.yandex.net] 2021.04.13 13:23:23.331888 [ 25763 ] <Fatal> BaseDaemon: 24. start_thread @ 0x9609 in /lib/x86_64-linux-gnu/libpthread-2.31.so
[avtokmakov-dev.sas.yp-c.yandex.net] 2021.04.13 13:23:23.332750 [ 25763 ] <Fatal> BaseDaemon: 25. /build/glibc-YYA7BZ/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:97: __clone @ 0x122103 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.31.so
[avtokmakov-dev.sas.yp-c.yandex.net] 2021.04.13 13:23:25.608526 [ 25763 ] <Fatal> BaseDaemon: Calculated checksum of the binary: D0ADF264983999AAA2CBE553CF87E911. There is no information about the reference checksum.

```

**Comment by qoega** [comment]
Same there https://clickhouse-test-reports.s3.yandex.net/23021/445591b73e45f7fdaf1737aba89dbfb894ca4098/sqlancer_test.html#fail1

**Comment by alexey-milovidov** [comment]
```
CREATE TEMPORARY TABLE t (c String);

SELECT isNull(c) OR COUNT(1)
FROM t
GROUP BY c
HAVING isNull(c)
UNION ALL
SELECT isNull(c) OR COUNT(1)
FROM t
GROUP BY c
HAVING isNull(isNull(c))
SETTINGS enable_optimize_predicate_expression = 0
```

**Comment by alexey-milovidov** [comment]
```
SELECT isNull(c) OR COUNT(1) AS x　FROM t　GROUP BY c　HAVING isNull(c)　UNION ALL　SELECT 0　SETTINGS enable_optimize_predicate_expression = 0
```
