### ISSUE TITLE
base64 (or similar) encoding for FixedString JSON 

### ISSUE THREAD

**Issue by leoluk** [ClickHouse/ClickHouse#2370]
ClickHouse encodes FixedStrings as regular UTF-8 strings in JSON output:

```
SELECT IPv6StringToNum('2001:4860:4860:0:0:0:0:8888')
FORMAT JSONEachRow

{"IPv6StringToNum('2001:4860:4860:0:0:0:0:8888')":" \u0001H`H`\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"}

1 rows in set. Elapsed: 0.002 sec. 
```

However, this is invalid UTF-8 and many language implementations will be unable to marshal/unmarshal them:

```
$ clickhouse-client <<<"SELECT IPv6StringToNum('2001:4860:4860:0:0:0:0:8888') FORMAT JSONEachRow" > output.json 
$ python3
Python 3.4.5 (default, Dec 11 2017, 14:22:24) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import json
>>> json.load(open('output.json'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.4/json/__init__.py", line 265, in load
    return loads(fp.read(),
  File "/usr/lib64/python3.4/codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x88 in position 110: invalid start byte
```

From what I can tell, most languages either refuse to encode byte strings, or serialize them as base64 values. For better compatibility, it would be desirable to support encoding them as base64 or hex/unhex. 

(I suppose it's possible to use a materialized view with unhex() to do the conversion, but it feels like a workaround)

**Comment by leoluk** [comment]
This works with Python 2, but not with Python 3:

```
clickhouse-client --query "SELECT IPv6StringToNum('2001:4860:4860:0:0:0:0:8888') FORMAT JSONEachRow" | python3 -c "import json,sys,pprint; pprint.pprint( json.loads(sys.stdin.read(),encoding='latin1') )"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python3.4/codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x88 in position 110: invalid start byte
```

JSON does not support unencoded binary data, so for better interoperability, it would have to be encoded.

**Comment by filimonov** [comment]
base64Encode, base64Decode, tryBase64Decode is supported since 18.16. 
Does it satisfy your needs?

**Comment by qoega** [comment]
I believe it can be considered fixed.
``` bash
clickhouse-client --query "SELECT base64Encode(toString(IPv6StringToNum('2001:4860:4860:0:0:0:0:8888'))) FORMAT JSONEachRow" | python3 -c "import json,sys,pprint; pprint.pprint( json.loads(sys.stdin.read(),encoding='latin1') )"
{"base64Encode(toString(IPv6StringToNum('2001:4860:4860:0:0:0:0:8888')))": 'IAFIYEhgAAAAAAAAAACIiA=='}
```

At this moment base64Encode works only with strings. If anyone needs to have base64Encode for other data types she can make new issue with this feature.
