### ISSUE TITLE
Create connection with empty http head value lead to a ClickHouseUnknownException

### ISSUE THREAD

**Issue by clowdrgn** [ClickHouse/ClickHouse#24268]
You have to provide the following information whenever possible.

**Describe the bug**
When I send a request with any empty header value. Server response with 400 UnkownException. But I think empty header value should't effect the response.

**Does it reproduce on recent release?**
[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**How to reproduce**
Use apache httpClient 4.5.3, send any header with empty value. tcp dump:
![image](https://user-images.githubusercontent.com/9083547/118765387-93980a80-b8ad-11eb-8309-f12efa5e2eed.png)

* Which ClickHouse server version to use
21.3.3

* Which interface to use, if matters

When create connection using jdbc, client had a aop method add a empty header value named sw8-correlation. 
execute "select timezone(), version()  FORMAT TabSeparatedWithNamesAndTypes"
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: xxxx, port: 8123; HTTP/1.1 400 Bad Request
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.getException(ClickHouseExceptionSpecifier.java:92)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:56)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:25)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.checkForErrorAndThrow(ClickHouseStatementImpl.java:1092)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.getInputStream(ClickHouseStatementImpl.java:773)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.getLastInputStream(ClickHouseStatementImpl.java:691)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:340)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:324)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:319)
**Expected behavior**
should connect successfully

**Error message and/or stacktrace**
![image](https://user-images.githubusercontent.com/9083547/118765132-3439fa80-b8ad-11eb-9999-7966c2a3dfc8.png)

**Additional context**

**Comment by MaxWk** [comment]
looks like duplicate with https://github.com/ClickHouse/ClickHouse/issues/23901

**Comment by abyss7** [comment]
> looks like duplicate with #23901

It is.
