### ISSUE TITLE
Crash when chaining different uniq*State

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#24461]
**Describe the bug**

Chaining **different** uniqXXXXState calls (uniqState, uniqExactState, uniqThetaState, uniqHLL12State or uniqCombinedState) crashes the server.

**Does it reproduce on recent release?**

Yes. I've tested 20.7 and current master/HEAD.

**How to reproduce**

Example with a query:

```sql
SELECT
    id,
    uniqState(s)
FROM
(
    SELECT
        number % 10 as id,
        uniqExactState(number) as s
    FROM
    (
        SELECT number
        FROM system.numbers
        LIMIT 1000
    )
    GROUP BY number
)
GROUP BY id
```

The other way around (uniqState -> uniqExactState) also crashes, as well as other combinations with other uniq*State.

Same can be done using a table:
```sql
DROP TABLE IF EXISTS uniq_crash_table;

CREATE TABLE uniq_crash_table
(
    `id` Int64,
    `hits` AggregateFunction(uniq, UInt64)
)
ENGINE = AggregatingMergeTree
PARTITION BY id
ORDER BY id AS
SELECT
    number % 10 AS id,
    uniqState(number) AS hits
FROM
(
    SELECT number
    FROM system.numbers
    LIMIT 1000
)
GROUP BY number

SELECT
    id,
    uniqExactState(hits)
FROM uniq_crash_table
GROUP BY id
```

**Expected behavior**

The server shouldn't crash. If the SQL is invalid then an exception should be raised instead.

**Error message and/or stacktrace**

Different queries crash in different parts, for example when running the first query from above you get an error like this in the clickhouse-client:
```
Exception on client:
Code: 173. DB::ErrnoException: Allocator: Cannot mmap 1.00 TiB., errno: 12, strerror: Cannot allocate memory: while receiving packet from localhost:9000

Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 21.7.1 revision 54448.
```

And the coredump looks like this:

```
(gdb) bt
#0  0x00007f2685cacd22 in raise () from /usr/lib/libc.so.6
#1  0x00007f2685c96862 in abort () from /usr/lib/libc.so.6
#2  0x00007f2687701fd4 in terminate_handler () at ../base/daemon/BaseDaemon.cpp:432
#3  0x00007f2685e7d888 in std::__terminate (func=0x2) at ../contrib/libcxxabi/src/cxa_handlers.cpp:59
#4  0x00007f2685e7d7ea in std::terminate () at ../contrib/libcxxabi/src/cxa_handlers.cpp:88
#5  0x00007f2683ee213b in __clang_call_terminate () from /mnt/ch/ClickHouse/build/src/AggregateFunctions/libclickhouse_aggregate_functions.so
#6  0x00007f2685579690 in HashTable<unsigned long, HashTableCell<unsigned long, HashCRC32<unsigned long>, HashTableNoState>, HashCRC32<unsigned long>, HashTableGrower<4ul>, AllocatorWithStackMemory<Allocator<true, true>, 128ul, 1ul> >::~HashTable (
    this=0x7f258483f0a0) at ../src/Common/HashTable/HashTable.h:703
#7  DB::AggregateFunctionUniqExactData<unsigned long>::~AggregateFunctionUniqExactData (this=0x7f258483f0a0) at ../src/AggregateFunctions/AggregateFunctionUniq.h:93
#8  DB::IAggregateFunctionDataHelper<DB::AggregateFunctionUniqExactData<unsigned long>, DB::AggregateFunctionUniq<unsigned long, DB::AggregateFunctionUniqExactData<unsigned long> > >::destroy (this=<optimized out>, place=0x7f258483f0a0 "")
    at ../src/AggregateFunctions/IAggregateFunction.h:443
#9  0x00007f267960cdbc in DB::ColumnAggregateFunction::~ColumnAggregateFunction (this=0x7f2566fbc980) at ../src/Columns/ColumnAggregateFunction.cpp:80
#10 0x00007f267960cf8e in DB::ColumnAggregateFunction::~ColumnAggregateFunction (this=0x7f2566fbc980) at ../src/Columns/ColumnAggregateFunction.cpp:77
#11 0x00007f2687eb8c32 in boost::sp_adl_block::intrusive_ptr_release<DB::IColumn, boost::sp_adl_block::thread_safe_counter> (p=<optimized out>) at ../contrib/boost/boost/smart_ptr/intrusive_ref_counter.hpp:173
#12 boost::intrusive_ptr<DB::IColumn const>::~intrusive_ptr (this=0x7f25831a4770) at ../contrib/boost/boost/smart_ptr/intrusive_ptr.hpp:98
#13 DB::ColumnWithTypeAndName::~ColumnWithTypeAndName (this=0x7f25831a4770) at ../src/Core/ColumnWithTypeAndName.h:19
#14 std::__1::allocator<DB::ColumnWithTypeAndName>::destroy (this=0x7f258edf0a50, __p=0x7f25831a4770) at ../contrib/libcxx/include/memory:891
#15 std::__1::allocator_traits<std::__1::allocator<DB::ColumnWithTypeAndName> >::__destroy<DB::ColumnWithTypeAndName> (__a=..., __p=0x7f25831a4770) at ../contrib/libcxx/include/__memory/allocator_traits.h:539
#16 std::__1::allocator_traits<std::__1::allocator<DB::ColumnWithTypeAndName> >::destroy<DB::ColumnWithTypeAndName> (__a=..., __p=0x7f25831a4770) at ../contrib/libcxx/include/__memory/allocator_traits.h:487
#17 std::__1::__vector_base<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >::__destruct_at_end (this=0x7f258edf0a40, __new_last=0x7f25831a4740) at ../contrib/libcxx/include/vector:428
#18 std::__1::__vector_base<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >::clear (this=0x7f258edf0a40) at ../contrib/libcxx/include/vector:371
#19 std::__1::__vector_base<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >::~__vector_base (this=0x7f258edf0a40) at ../contrib/libcxx/include/vector:465
#20 std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >::~vector (this=0x7f258edf0a40) at ../contrib/libcxx/include/vector:557
#21 DB::Block::~Block (this=0x7f258edf0a40) at ../src/Core/Block.h:25
#22 0x00007f26783e29b9 in DB::TCPHandler::processOrdinaryQueryWithProcessors (this=<optimized out>, this@entry=0x7f2583167500) at ../src/Server/TCPHandler.cpp:722
#23 0x00007f26783dd487 in DB::TCPHandler::runImpl (this=0x7f2583167500) at ../src/Server/TCPHandler.cpp:331
#24 0x00007f26783e90a9 in DB::TCPHandler::run (this=0x7f2583167500) at ../src/Server/TCPHandler.cpp:1621
#25 0x00007f26869b110c in Poco::Net::TCPServerConnection::start (this=0x2) at ../contrib/poco/Net/src/TCPServerConnection.cpp:43
#26 0x00007f26869b1647 in Poco::Net::TCPServerDispatcher::run (this=0x7f2583d8d800) at ../contrib/poco/Net/src/TCPServerDispatcher.cpp:115
#27 0x00007f268668ddaa in Poco::PooledThread::run (this=0x7f266f769380) at ../contrib/poco/Foundation/src/ThreadPool.cpp:199
#28 0x00007f268668b660 in Poco::ThreadImpl::runnableEntry (pThread=0x7f266f7693b8) at ../contrib/poco/Foundation/src/Thread_POSIX.cpp:345
#29 0x00007f2685f9c259 in start_thread () from /usr/lib/libpthread.so.0
#30 0x00007f2685d6e5e3 in clone () from /usr/lib/libc.so.6
```

Any pointers on where to look to fix this myself are also appreciated.

**Comment by Algunenano** [comment]
Here is an msan report of the query in case it's helpful:

```
==146744==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x9a555b4 in DB::writeVarUInt(unsigned long, DB::WriteBuffer&) /mnt/ch/ClickHouse/build/../src/IO/VarInt.h
    #1 0xc846655 in HashTable<unsigned long, HashTableCell<unsigned long, HashCRC32<unsigned long>, HashTableNoState>, HashCRC32<unsigned long>, HashTableGrower<4ul>, AllocatorWithStackMemory<Allocator<true, true>, 128ul, 1ul> >::write(DB::WriteBuffer&) const /mnt/ch/ClickHouse/build/../src/Common/HashTable/HashTable.h:1179:9
    #2 0xc846655 in DB::AggregateFunctionUniq<unsigned long, DB::AggregateFunctionUniqExactData<unsigned long> >::serialize(char const*, DB::WriteBuffer&) const /mnt/ch/ClickHouse/build/../src/AggregateFunctions/AggregateFunctionUniq.h:246:31
    #3 0x3076dbdb in DB::SerializationAggregateFunction::serializeBinaryBulk(DB::IColumn const&, DB::WriteBuffer&, unsigned long, unsigned long) const /mnt/ch/ClickHouse/build/../src/DataTypes/Serializations/SerializationAggregateFunction.cpp:77:19
    #4 0x30761f0a in DB::ISerialization::serializeBinaryBulkWithMultipleStreams(DB::IColumn const&, unsigned long, unsigned long, DB::ISerialization::SerializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::SerializeBinaryBulkState>&) const /mnt/ch/ClickHouse/build/../src/DataTypes/Serializations/ISerialization.cpp:82:9
    #5 0x32705732 in DB::writeData(DB::IDataType const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&, DB::WriteBuffer&, unsigned long, unsigned long) /mnt/ch/ClickHouse/build/../src/DataStreams/NativeBlockOutputStream.cpp:60:20
    #6 0x32705732 in DB::NativeBlockOutputStream::write(DB::Block const&) /mnt/ch/ClickHouse/build/../src/DataStreams/NativeBlockOutputStream.cpp:126:13
    #7 0x354aa517 in DB::TCPHandler::sendData(DB::Block const&) /mnt/ch/ClickHouse/build/../src/Server/TCPHandler.cpp:1504:26
    #8 0x354a1b67 in DB::TCPHandler::processOrdinaryQueryWithProcessors() /mnt/ch/ClickHouse/build/../src/Server/TCPHandler.cpp:698:21
    #9 0x35485654 in DB::TCPHandler::runImpl() /mnt/ch/ClickHouse/build/../src/Server/TCPHandler.cpp:331:17
    #10 0x354ca958 in DB::TCPHandler::run() /mnt/ch/ClickHouse/build/../src/Server/TCPHandler.cpp:1621:9
    #11 0x4267f18a in Poco::Net::TCPServerConnection::start() /mnt/ch/ClickHouse/build/../contrib/poco/Net/src/TCPServerConnection.cpp:43:3
    #12 0x42680870 in Poco::Net::TCPServerDispatcher::run() /mnt/ch/ClickHouse/build/../contrib/poco/Net/src/TCPServerDispatcher.cpp:115:20
    #13 0x42b70064 in Poco::PooledThread::run() /mnt/ch/ClickHouse/build/../contrib/poco/Foundation/src/ThreadPool.cpp:199:14
    #14 0x42b6ae08 in Poco::(anonymous namespace)::RunnableHolder::run() /mnt/ch/ClickHouse/build/../contrib/poco/Foundation/src/Thread.cpp:55:11
    #15 0x42b66b80 in Poco::ThreadImpl::runnableEntry(void*) /mnt/ch/ClickHouse/build/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345:27
    #16 0x7f4969d39258 in start_thread (/usr/lib/libpthread.so.0+0x9258)
    #17 0x7f4969c625e2 in clone (/usr/lib/libc.so.6+0xfe5e2)

  Uninitialized value was created by a heap allocation
    #0 0x98af713 in malloc (/mnt/ch/ClickHouse/build/programs/clickhouse+0x98af713)
    #1 0x9b56b01 in Allocator<false, false>::allocNoTrack(unsigned long, unsigned long) /mnt/ch/ClickHouse/build/../src/Common/Allocator.h:227:27
    #2 0xa50fee3 in Allocator<false, false>::alloc(unsigned long, unsigned long) /mnt/ch/ClickHouse/build/../src/Common/Allocator.h:96:16
    #3 0xa50fee3 in DB::Arena::MemoryChunk::MemoryChunk(unsigned long, DB::Arena::MemoryChunk*) /mnt/ch/ClickHouse/build/../src/Common/Arena.h:54:64
    #4 0x1b5d59a3 in std::__1::shared_ptr<DB::Arena> std::__1::allocate_shared<DB::Arena, std::__1::allocator<DB::Arena>, void>(std::__1::allocator<DB::Arena> const&) (/mnt/ch/ClickHouse/build/programs/clickhouse+0x1b5d59a3)
    #5 0x321b1029 in std::__1::shared_ptr<DB::Arena> std::__1::make_shared<DB::Arena, void>() /mnt/ch/ClickHouse/build/../contrib/libcxx/include/memory:3369:12
    #6 0x321b1029 in DB::AggregatedDataVariants::AggregatedDataVariants() /mnt/ch/ClickHouse/build/../src/Interpreters/Aggregator.h:637:52
    #7 0x34bd8ef8 in void std::__1::allocator<DB::AggregatedDataVariants>::construct<DB::AggregatedDataVariants>(DB::AggregatedDataVariants*) /mnt/ch/ClickHouse/build/../contrib/libcxx/include/memory:886:28
    #8 0x34bd8ef8 in void std::__1::allocator_traits<std::__1::allocator<DB::AggregatedDataVariants> >::__construct<DB::AggregatedDataVariants>(std::__1::integral_constant<bool, true>, std::__1::allocator<DB::AggregatedDataVariants>&, DB::AggregatedDataVariants*) /mnt/ch/ClickHouse/build/../contrib/libcxx/include/__memory/allocator_traits.h:519:21
    #9 0x34bd8ef8 in void std::__1::allocator_traits<std::__1::allocator<DB::AggregatedDataVariants> >::construct<DB::AggregatedDataVariants>(std::__1::allocator<DB::AggregatedDataVariants>&, DB::AggregatedDataVariants*) /mnt/ch/ClickHouse/build/../contrib/libcxx/include/__memory/allocator_traits.h:481:14
    #10 0x34bd8ef8 in std::__1::__shared_ptr_emplace<DB::AggregatedDataVariants, std::__1::allocator<DB::AggregatedDataVariants> >::__shared_ptr_emplace<>(std::__1::allocator<DB::AggregatedDataVariants>) /mnt/ch/ClickHouse/build/../contrib/libcxx/include/memory:2594:9
    #11 0x34bd8ef8 in std::__1::shared_ptr<DB::AggregatedDataVariants> std::__1::allocate_shared<DB::AggregatedDataVariants, std::__1::allocator<DB::AggregatedDataVariants>, void>(std::__1::allocator<DB::AggregatedDataVariants> const&) /mnt/ch/ClickHouse/build/../contrib/libcxx/include/memory:3360:55
    #12 0x34bd8ef8 in std::__1::shared_ptr<DB::AggregatedDataVariants> std::__1::make_shared<DB::AggregatedDataVariants, void>() /mnt/ch/ClickHouse/build/../contrib/libcxx/include/memory:3369:12
    #13 0x34bd81bf in DB::ManyAggregatedData::ManyAggregatedData(unsigned long) /mnt/ch/ClickHouse/build/../src/Processors/Transforms/AggregatingTransform.h:54:20
    #14 0x35cc75c2 in std::__1::__unique_if<DB::ManyAggregatedData>::__unique_single std::__1::make_unique<DB::ManyAggregatedData, int>(int&&) /mnt/ch/ClickHouse/build/../contrib/libcxx/include/memory:2068:32
    #15 0x35cc75c2 in DB::AggregatingTransform::AggregatingTransform(DB::Block, std::__1::shared_ptr<DB::AggregatingTransformParams>) /mnt/ch/ClickHouse/build/../src/Processors/Transforms/AggregatingTransform.cpp:393:7
    #16 0x35f28ce8 in void std::__1::allocator<DB::AggregatingTransform>::construct<DB::AggregatingTransform, DB::Block const&, std::__1::shared_ptr<DB::AggregatingTransformParams>&>(DB::AggregatingTransform*, DB::Block const&, std::__1::shared_ptr<DB::AggregatingTransformParams>&) /mnt/ch/ClickHouse/build/../contrib/libcxx/include/memory:886:28
    #17 0x35f28ce8 in void std::__1::allocator_traits<std::__1::allocator<DB::AggregatingTransform> >::__construct<DB::AggregatingTransform, DB::Block const&, std::__1::shared_ptr<DB::AggregatingTransformParams>&>(std::__1::integral_constant<bool, true>, std::__1::allocator<DB::AggregatingTransform>&, DB::AggregatingTransform*, DB::Block const&, std::__1::shared_ptr<DB::AggregatingTransformParams>&) /mnt/ch/ClickHouse/build/../contrib/libcxx/include/__memory/allocator_traits.h:519:21
    #18 0x35f28ce8 in void std::__1::allocator_traits<std::__1::allocator<DB::AggregatingTransform> >::construct<DB::AggregatingTransform, DB::Block const&, std::__1::shared_ptr<DB::AggregatingTransformParams>&>(std::__1::allocator<DB::AggregatingTransform>&, DB::AggregatingTransform*, DB::Block const&, std::__1::shared_ptr<DB::AggregatingTransformParams>&) /mnt/ch/ClickHouse/build/../contrib/libcxx/include/__memory/allocator_traits.h:481:14
    #19 0x35f28ce8 in std::__1::__shared_ptr_emplace<DB::AggregatingTransform, std::__1::allocator<DB::AggregatingTransform> >::__shared_ptr_emplace<DB::Block const&, std::__1::shared_ptr<DB::AggregatingTransformParams>&>(std::__1::allocator<DB::AggregatingTransform>, DB::Block const&, std::__1::shared_ptr<DB::AggregatingTransformParams>&) /mnt/ch/ClickHouse/build/../contrib/libcxx/include/memory:2594:9
    #20 0x35f28ce8 in std::__1::shared_ptr<DB::AggregatingTransform> std::__1::allocate_shared<DB::AggregatingTransform, std::__1::allocator<DB::AggregatingTransform>, DB::Block const&, std::__1::shared_ptr<DB::AggregatingTransformParams>&, void>(std::__1::allocator<DB::AggregatingTransform> const&, DB::Block const&, std::__1::shared_ptr<DB::AggregatingTransformParams>&) /mnt/ch/ClickHouse/build/../contrib/libcxx/include/memory:3360:55
    #21 0x35f1bb60 in std::__1::shared_ptr<DB::AggregatingTransform> std::__1::make_shared<DB::AggregatingTransform, DB::Block const&, std::__1::shared_ptr<DB::AggregatingTransformParams>&, void>(DB::Block const&, std::__1::shared_ptr<DB::AggregatingTransformParams>&) /mnt/ch/ClickHouse/build/../contrib/libcxx/include/memory:3369:12
    #22 0x35f1bb60 in DB::AggregatingStep::transformPipeline(DB::QueryPipeline&, DB::BuildQueryPipelineSettings const&)::$_4::operator()(DB::Block const&) const /mnt/ch/ClickHouse/build/../src/Processors/QueryPlan/AggregatingStep.cpp:154:20
    #23 0x35f1bb60 in decltype(std::__1::forward<DB::AggregatingStep::transformPipeline(DB::QueryPipeline&, DB::BuildQueryPipelineSettings const&)::$_4&>(fp)(std::__1::forward<DB::Block const&>(fp0))) std::__1::__invoke<DB::AggregatingStep::transformPipeline(DB::QueryPipeline&, DB::BuildQueryPipelineSettings const&)::$_4&, DB::Block const&>(DB::AggregatingStep::transformPipeline(DB::QueryPipeline&, DB::BuildQueryPipelineSettings const&)::$_4&, DB::Block const&) /mnt/ch/ClickHouse/build/../contrib/libcxx/include/type_traits:3676:1
    #24 0x35f1bb60 in std::__1::shared_ptr<DB::IProcessor> std::__1::__invoke_void_return_wrapper<std::__1::shared_ptr<DB::IProcessor> >::__call<DB::AggregatingStep::transformPipeline(DB::QueryPipeline&, DB::BuildQueryPipelineSettings const&)::$_4&, DB::Block const&>(DB::AggregatingStep::transformPipeline(DB::QueryPipeline&, DB::BuildQueryPipelineSettings const&)::$_4&, DB::Block const&) /mnt/ch/ClickHouse/build/../contrib/libcxx/include/__functional_base:317:16
    #25 0x35f1bb60 in std::__1::__function::__default_alloc_func<DB::AggregatingStep::transformPipeline(DB::QueryPipeline&, DB::BuildQueryPipelineSettings const&)::$_4, std::__1::shared_ptr<DB::IProcessor> (DB::Block const&)>::operator()(DB::Block const&) /mnt/ch/ClickHouse/build/../contrib/libcxx/include/functional:1608:12
    #26 0x35f1bb60 in std::__1::shared_ptr<DB::IProcessor> std::__1::__function::__policy_invoker<std::__1::shared_ptr<DB::IProcessor> (DB::Block const&)>::__call_impl<std::__1::__function::__default_alloc_func<DB::AggregatingStep::transformPipeline(DB::QueryPipeline&, DB::BuildQueryPipelineSettings const&)::$_4, std::__1::shared_ptr<DB::IProcessor> (DB::Block const&)> >(std::__1::__function::__policy_storage const*, DB::Block const&) /mnt/ch/ClickHouse/build/../contrib/libcxx/include/functional:2089:16
    #27 0x355e1acf in std::__1::__function::__policy_func<std::__1::shared_ptr<DB::IProcessor> (DB::Block const&)>::operator()(DB::Block const&) const /mnt/ch/ClickHouse/build/../contrib/libcxx/include/functional:2221:16
    #28 0x355e1acf in std::__1::function<std::__1::shared_ptr<DB::IProcessor> (DB::Block const&)>::operator()(DB::Block const&) const /mnt/ch/ClickHouse/build/../contrib/libcxx/include/functional:2560:12
    #29 0x355e1acf in DB::Pipe::addSimpleTransform(std::__1::function<std::__1::shared_ptr<DB::IProcessor> (DB::Block const&)> const&)::$_2::operator()(DB::Block const&, DB::Pipe::StreamType) const /mnt/ch/ClickHouse/build/../src/Processors/Pipe.cpp:666:78
    #30 0x355e1acf in decltype(std::__1::forward<DB::Pipe::addSimpleTransform(std::__1::function<std::__1::shared_ptr<DB::IProcessor> (DB::Block const&)> const&)::$_2&>(fp)(std::__1::forward<DB::Block const&>(fp0), std::__1::forward<DB::Pipe::StreamType>(fp0))) std::__1::__invoke<DB::Pipe::addSimpleTransform(std::__1::function<std::__1::shared_ptr<DB::IProcessor> (DB::Block const&)> const&)::$_2&, DB::Block const&, DB::Pipe::StreamType>(DB::Pipe::addSimpleTransform(std::__1::function<std::__1::shared_ptr<DB::IProcessor> (DB::Block const&)> const&)::$_2&, DB::Block const&, DB::Pipe::StreamType&&) /mnt/ch/ClickHouse/build/../contrib/libcxx/include/type_traits:3676:1
    #31 0x355e1acf in std::__1::shared_ptr<DB::IProcessor> std::__1::__invoke_void_return_wrapper<std::__1::shared_ptr<DB::IProcessor> >::__call<DB::Pipe::addSimpleTransform(std::__1::function<std::__1::shared_ptr<DB::IProcessor> (DB::Block const&)> const&)::$_2&, DB::Block const&, DB::Pipe::StreamType>(DB::Pipe::addSimpleTransform(std::__1::function<std::__1::shared_ptr<DB::IProcessor> (DB::Block const&)> const&)::$_2&, DB::Block const&, DB::Pipe::StreamType&&) /mnt/ch/ClickHouse/build/../contrib/libcxx/include/__functional_base:317:16
    #32 0x355e1acf in std::__1::__function::__default_alloc_func<DB::Pipe::addSimpleTransform(std::__1::function<std::__1::shared_ptr<DB::IProcessor> (DB::Block const&)> const&)::$_2, std::__1::shared_ptr<DB::IProcessor> (DB::Block const&, DB::Pipe::StreamType)>::operator()(DB::Block const&, DB::Pipe::StreamType&&) /mnt/ch/ClickHouse/build/../contrib/libcxx/include/functional:1608:12
    #33 0x355e1acf in std::__1::shared_ptr<DB::IProcessor> std::__1::__function::__policy_invoker<std::__1::shared_ptr<DB::IProcessor> (DB::Block const&, DB::Pipe::StreamType)>::__call_impl<std::__1::__function::__default_alloc_func<DB::Pipe::addSimpleTransform(std::__1::function<std::__1::shared_ptr<DB::IProcessor> (DB::Block const&)> const&)::$_2, std::__1::shared_ptr<DB::IProcessor> (DB::Block const&, DB::Pipe::StreamType)> >(std::__1::__function::__policy_storage const*, DB::Block const&, DB::Pipe::StreamType) /mnt/ch/ClickHouse/build/../contrib/libcxx/include/functional:2089:16
    #34 0x355d3528 in std::__1::__function::__policy_func<std::__1::shared_ptr<DB::IProcessor> (DB::Block const&, DB::Pipe::StreamType)>::operator()(DB::Block const&, DB::Pipe::StreamType&&) const /mnt/ch/ClickHouse/build/../contrib/libcxx/include/functional:2221:16
    #35 0x355d3528 in std::__1::function<std::__1::shared_ptr<DB::IProcessor> (DB::Block const&, DB::Pipe::StreamType)>::operator()(DB::Block const&, DB::Pipe::StreamType) const /mnt/ch/ClickHouse/build/../contrib/libcxx/include/functional:2560:12
    #36 0x355d3528 in DB::Pipe::addSimpleTransform(std::__1::function<std::__1::shared_ptr<DB::IProcessor> (DB::Block const&, DB::Pipe::StreamType)> const&)::$_1::operator()(DB::OutputPort*&, DB::Pipe::StreamType) const /mnt/ch/ClickHouse/build/../src/Processors/Pipe.cpp:620:26
    #37 0x355d2deb in DB::Pipe::addSimpleTransform(std::__1::function<std::__1::shared_ptr<DB::IProcessor> (DB::Block const&, DB::Pipe::StreamType)> const&) /mnt/ch/ClickHouse/build/../src/Processors/Pipe.cpp:656:9
    #38 0x355d54f6 in DB::Pipe::addSimpleTransform(std::__1::function<std::__1::shared_ptr<DB::IProcessor> (DB::Block const&)> const&) /mnt/ch/ClickHouse/build/../src/Processors/Pipe.cpp:666:5
    #39 0x3560cd61 in DB::QueryPipeline::addSimpleTransform(std::__1::function<std::__1::shared_ptr<DB::IProcessor> (DB::Block const&)> const&) /mnt/ch/ClickHouse/build/../src/Processors/QueryPipeline.cpp:85:10
    #40 0x35f16c85 in DB::AggregatingStep::transformPipeline(DB::QueryPipeline&, DB::BuildQueryPipelineSettings const&) /mnt/ch/ClickHouse/build/../src/Processors/QueryPlan/AggregatingStep.cpp:152:18
    #41 0x35fcf45c in DB::ITransformingStep::updatePipeline(std::__1::vector<std::__1::unique_ptr<DB::QueryPipeline, std::__1::default_delete<DB::QueryPipeline> >, std::__1::allocator<std::__1::unique_ptr<DB::QueryPipeline, std::__1::default_delete<DB::QueryPipeline> > > >, DB::BuildQueryPipelineSettings const&) /mnt/ch/ClickHouse/build/../src/Processors/QueryPlan/ITransformingStep.cpp:48:9
    #42 0x3603cf8f in DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&) /mnt/ch/ClickHouse/build/../src/Processors/QueryPlan/QueryPlan.cpp:168:47
    #43 0x32735fe4 in DB::InterpreterSelectWithUnionQuery::execute() /mnt/ch/ClickHouse/build/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:313:32
    #44 0x32f179a9 in DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool, DB::ReadBuffer*) /mnt/ch/ClickHouse/build/../src/Interpreters/executeQuery.cpp:561:32

SUMMARY: MemorySanitizer: use-of-uninitialized-value /mnt/ch/ClickHouse/build/../src/IO/VarInt.h in DB::writeVarUInt(unsigned long, DB::WriteBuffer&)
```

**Comment by filimonov** [comment]
Of course crash is not acceptable, but building state on the top of some other state is kinda odd. Do you have any practical use case when it may be needed?

Maybe we can just forbid it, instead of fixing it?

**Comment by Algunenano** [comment]
> Of course crash is not acceptable, but building state on the top of some other state is kinda odd. Do you have any practical use case when it may be needed?

Not at all, this originally comes from an error in a larger SQL.

> Maybe we can just forbid it, instead of fixing it?

I don't see an issue with that. Would that also forbid calling Agg2Final over Agg1State (which I also don't see an issue with)?

**Comment by filimonov** [comment]
> Would that also forbid calling Agg2Merge over Agg1State (which I also don't see an issue with)?

It should be already forbidden:
```
SELECT uniqMerge(s)
FROM
(
    SELECT uniqCombinedState(number) AS s
    FROM numbers(10)
)

Query id: bf9217ed-01ef-455e-972d-388c68eb375b


0 rows in set. Elapsed: 0.007 sec. 

Received exception from server (version 21.6.1):
Code: 43. DB::Exception: Received from localhost:9000. DB::Exception: Illegal type AggregateFunction(uniqCombined, UInt64) of argument for aggregate function with Merge suffix, because it corresponds to different aggregate function: uniqCombined instead of uniq. 
```
