### ISSUE TITLE
AST fuzzer (UBSan): shift exponent 75 is too large for 64-bit type 'uint64_t' (aka 'unsigned long')

### ISSUE THREAD

**Issue by Avogar** [ClickHouse/ClickHouse#24811]
https://clickhouse-test-reports.s3.yandex.net/24539/b31390799a05a98259f7556297fbb1f2e34aa671/fuzzer_ubsan/report.html#fail1

Query to reproduce:
```sql
SELECT *  FROM values('val Map(UInt128, UInt128)', map(1025, 3.4028234663852886e38))
```

Trace:
```
2021.05.26 19:35:57.052556 [ 47 ] {236d31e7-e251-4723-8c9a-e9f2d17bd8d9} <Debug> executeQuery: (from [::1]:56394, using production parser) SELECT map('0.0001048575', '65537'), map(-9223372036854775807, NULL) FROM values('val Map(UInt128, UInt128)', map(1025, 3.4028234663852886e38))
2021.05.26 19:35:57.052731 [ 47 ] {236d31e7-e251-4723-8c9a-e9f2d17bd8d9} <Trace> ContextAccess (default): Access granted: CREATE TEMPORARY TABLE ON *.*
../base/common/../common/DecomposedFloat.h:158:26: runtime error: shift exponent 75 is too large for 64-bit type 'uint64_t' (aka 'unsigned long')
    #0 0x140402bb in int DecomposedFloat<double>::compare<wide::integer<128ul, unsigned int> >(wide::integer<128ul, unsigned int>) (/workspace/clickhouse+0x140402bb)
    #1 0x1403fcc9 in bool accurate::convertNumeric<double, wide::integer<128ul, unsigned int> >(double, wide::integer<128ul, unsigned int>&) (/workspace/clickhouse+0x1403fcc9)
    #2 0x1ca673d0 in DB::Field DB::(anonymous namespace)::convertNumericTypeImpl<double, wide::integer<128ul, unsigned int> >(DB::Field const&) obj-x86_64-linux-gnu/../src/Interpreters/convertFieldToType.cpp:55:10
    #3 0x1ca673d0 in DB::Field DB::(anonymous namespace)::convertNumericType<wide::integer<128ul, unsigned int> >(DB::Field const&, DB::IDataType const&) obj-x86_64-linux-gnu/../src/Interpreters/convertFieldToType.cpp:68:16
    #4 0x1ca6476b in DB::(anonymous namespace)::convertFieldToTypeImpl(DB::Field const&, DB::IDataType const&, DB::IDataType const*) obj-x86_64-linux-gnu/../src/Interpreters/convertFieldToType.cpp:172:44
    #5 0x1ca634bc in DB::convertFieldToType(DB::Field const&, DB::IDataType const&, DB::IDataType const*) obj-x86_64-linux-gnu/../src/Interpreters/convertFieldToType.cpp
    #6 0x1ca6452e in DB::(anonymous namespace)::convertFieldToTypeImpl(DB::Field const&, DB::IDataType const&, DB::IDataType const*) obj-x86_64-linux-gnu/../src/Interpreters/convertFieldToType.cpp:328:36
    #7 0x1ca634bc in DB::convertFieldToType(DB::Field const&, DB::IDataType const&, DB::IDataType const*) obj-x86_64-linux-gnu/../src/Interpreters/convertFieldToType.cpp
    #8 0x1ca66586 in DB::convertFieldToTypeOrThrow(DB::Field const&, DB::IDataType const&, DB::IDataType const*) obj-x86_64-linux-gnu/../src/Interpreters/convertFieldToType.cpp:422:23
    #9 0x1b868db9 in DB::parseAndInsertValues(std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, std::__1::vector<std::__1::shared_ptr<DB::IAST>, std::__1::allocator<std::__1::shared_ptr<DB::IAST> > > const&, DB::Block const&, std::__1::shared_ptr<DB::Context>) obj-x86_64-linux-gnu/../src/TableFunctions/TableFunctionValues.cpp:41:27
    #10 0x1b868897 in DB::TableFunctionValues::executeImpl(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ColumnsDescription) const obj-x86_64-linux-gnu/../src/TableFunctions/TableFunctionValues.cpp:114:5
    #11 0x1bf845b3 in DB::ITableFunction::execute(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ColumnsDescription) const obj-x86_64-linux-gnu/../src/TableFunctions/ITableFunction.cpp:24:16
    #12 0x1c097ab9 in DB::Context::executeTableFunction(std::__1::shared_ptr<DB::IAST> const&) obj-x86_64-linux-gnu/../src/Interpreters/Context.cpp:1066:35
    #13 0x1c86e9fe in DB::JoinedTables::getLeftTableStorage() obj-x86_64-linux-gnu/../src/Interpreters/JoinedTables.cpp:161:44
    #14 0x1c56b7b6 in DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:319:33
    #15 0x1c56a950 in DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:160:7
    #16 0x1c81a1bb in std::__1::__unique_if<DB::InterpreterSelectQuery>::__unique_single std::__1::make_unique<DB::InterpreterSelectQuery, std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>&, DB::SelectQueryOptions&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&>(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>&, DB::SelectQueryOptions&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2068:32
    #17 0x1c817684 in DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter(std::__1::shared_ptr<DB::IAST> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:212:16
    #18 0x1c815ba9 in DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:134:13
    #19 0x1c273389 in std::__1::__unique_if<DB::InterpreterSelectWithUnionQuery>::__unique_single std::__1::make_unique<DB::InterpreterSelectWithUnionQuery, std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>&, DB::SelectQueryOptions const&>(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>&, DB::SelectQueryOptions const&) obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2068:32
    #20 0x1c271e68 in DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterFactory.cpp:110:16
    #21 0x1ca86616 in DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool, DB::ReadBuffer*) obj-x86_64-linux-gnu/../src/Interpreters/executeQuery.cpp:531:28
    #22 0x1ca8527e in DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool) obj-x86_64-linux-gnu/../src/Interpreters/executeQuery.cpp:920:30
    #23 0x1d5e52cd in DB::TCPHandler::runImpl() obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:312:24
    #24 0x1d60170c in DB::TCPHandler::run() obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:1621:9
    #25 0x1e5ec26b in Poco::Net::TCPServerConnection::start() obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerConnection.cpp:43:3
    #26 0x1e5ec74b in Poco::Net::TCPServerDispatcher::run() obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerDispatcher.cpp:115:20
    #27 0x1e6d8e39 in Poco::PooledThread::run() obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/ThreadPool.cpp:199:14
    #28 0x1e6d69eb in Poco::ThreadImpl::runnableEntry(void*) obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345:27
    #29 0x7fa449a2d608 in start_thread /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477:8
    #30 0x7fa449954292 in clone /build/glibc-eX1tMB/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../base/common/../common/DecomposedFloat.h:158:26 in 
2021.05.26 19:35:58.043728 [ 43 ] {} <Trace> BaseDaemon: Received signal -3
2021.05.26 19:35:58.044207 [ 154 ] {} <Fatal> BaseDaemon: ########################################
2021.05.26 19:35:58.044371 [ 154 ] {} <Fatal> BaseDaemon: (version 21.7.1.6965, build id: 5435E2F48F9794AFF2A2117D866EBACDF9B2115E) (from thread 47) (query_id: 236d31e7-e251-4723-8c9a-e9f2d17bd8d9) Received signal Unknown signal (-3)
2021.05.26 19:35:58.044425 [ 154 ] {} <Fatal> BaseDaemon: Sanitizer trap.
2021.05.26 19:35:58.044547 [ 154 ] {} <Fatal> BaseDaemon: Stack trace: 0xf6dba65 0x1b9c7f36 0xf69cf56 0xf6a9f6f 0x140402bc 0x1403fcca 0x1ca673d1 0x1ca6476c 0x1ca634bd 0x1ca6452f 0x1ca634bd 0x1ca66587 0x1b868dba 0x1b868898 0x1bf845b4 0x1c097aba 0x1c86e9ff 0x1c56b7b7 0x1c56a951 0x1c81a1bc 0x1c817685 0x1c815baa 0x1c27338a 0x1c271e69 0x1ca86617 0x1ca8527f 0x1d5e52ce 0x1d60170d 0x1e5ec26c 0x1e5ec74c 0x1e6d8e3a 0x1e6d69ec
2021.05.26 19:35:58.064315 [ 154 ] {} <Fatal> BaseDaemon: 0.1. inlined from ./obj-x86_64-linux-gnu/../src/Common/StackTrace.cpp:304: StackTrace::tryCapture()
2021.05.26 19:35:58.064380 [ 154 ] {} <Fatal> BaseDaemon: 0. ../src/Common/StackTrace.cpp:265: StackTrace::StackTrace() @ 0xf6dba65 in /workspace/clickhouse
2021.05.26 19:35:58.128364 [ 154 ] {} <Fatal> BaseDaemon: 1. ./obj-x86_64-linux-gnu/../base/daemon/BaseDaemon.cpp:381: sanitizerDeathCallback() @ 0x1b9c7f36 in /workspace/clickhouse
2021.05.26 19:35:59.077469 [ 154 ] {} <Fatal> BaseDaemon: 2. __sanitizer::Die() @ 0xf69cf56 in /workspace/clickhouse
2021.05.26 19:35:59.995004 [ 154 ] {} <Fatal> BaseDaemon: 3. ? @ 0xf6a9f6f in /workspace/clickhouse
2021.05.26 19:36:00.883093 [ 154 ] {} <Fatal> BaseDaemon: 4. int DecomposedFloat<double>::compare<wide::integer<128ul, unsigned int> >(wide::integer<128ul, unsigned int>) @ 0x140402bc in /workspace/clickhouse
2021.05.26 19:36:01.761408 [ 154 ] {} <Fatal> BaseDaemon: 5. bool accurate::convertNumeric<double, wide::integer<128ul, unsigned int> >(double, wide::integer<128ul, unsigned int>&) @ 0x1403fcca in /workspace/clickhouse
2021.05.26 19:36:01.790389 [ 154 ] {} <Fatal> BaseDaemon: 6.1. inlined from ./obj-x86_64-linux-gnu/../src/Interpreters/convertFieldToType.cpp:55: DB::Field DB::(anonymous namespace)::convertNumericTypeImpl<double, wide::integer<128ul, unsigned int> >(DB::Field const&)
2021.05.26 19:36:01.790436 [ 154 ] {} <Fatal> BaseDaemon: 6. ../src/Interpreters/convertFieldToType.cpp:68: DB::Field DB::(anonymous namespace)::convertNumericType<wide::integer<128ul, unsigned int> >(DB::Field const&, DB::IDataType const&) @ 0x1ca673d1 in /workspace/clickhouse
2021.05.26 19:36:01.818473 [ 154 ] {} <Fatal> BaseDaemon: 7. ./obj-x86_64-linux-gnu/../src/Interpreters/convertFieldToType.cpp:0: DB::(anonymous namespace)::convertFieldToTypeImpl(DB::Field const&, DB::IDataType const&, DB::IDataType const*) @ 0x1ca6476c in /workspace/clickhouse
2021.05.26 19:36:01.844733 [ 154 ] {} <Fatal> BaseDaemon: 8. ./obj-x86_64-linux-gnu/../src/Interpreters/convertFieldToType.cpp:0: DB::convertFieldToType(DB::Field const&, DB::IDataType const&, DB::IDataType const*) @ 0x1ca634bd in /workspace/clickhouse
2021.05.26 19:36:01.873487 [ 154 ] {} <Fatal> BaseDaemon: 9.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/vector:1550: std::__1::vector<DB::Field, AllocatorWithMemoryTracking<DB::Field> >::operator[](unsigned long)
2021.05.26 19:36:01.873573 [ 154 ] {} <Fatal> BaseDaemon: 9. ../src/Interpreters/convertFieldToType.cpp:328: DB::(anonymous namespace)::convertFieldToTypeImpl(DB::Field const&, DB::IDataType const&, DB::IDataType const*) @ 0x1ca6452f in /workspace/clickhouse
2021.05.26 19:36:01.899971 [ 154 ] {} <Fatal> BaseDaemon: 10. ./obj-x86_64-linux-gnu/../src/Interpreters/convertFieldToType.cpp:0: DB::convertFieldToType(DB::Field const&, DB::IDataType const&, DB::IDataType const*) @ 0x1ca634bd in /workspace/clickhouse
2021.05.26 19:36:01.931036 [ 154 ] {} <Fatal> BaseDaemon: 11. ./obj-x86_64-linux-gnu/../src/Interpreters/convertFieldToType.cpp:424: DB::convertFieldToTypeOrThrow(DB::Field const&, DB::IDataType const&, DB::IDataType const*) @ 0x1ca66587 in /workspace/clickhouse
2021.05.26 19:36:01.980591 [ 154 ] {} <Fatal> BaseDaemon: 12. ./obj-x86_64-linux-gnu/../src/TableFunctions/TableFunctionValues.cpp:0: DB::parseAndInsertValues(std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, std::__1::vector<std::__1::shared_ptr<DB::IAST>, std::__1::allocator<std::__1::shared_ptr<DB::IAST> > > const&, DB::Block const&, std::__1::shared_ptr<DB::Context>) @ 0x1b868dba in /workspace/clickhouse
2021.05.26 19:36:02.027173 [ 154 ] {} <Fatal> BaseDaemon: 13. ./obj-x86_64-linux-gnu/../src/TableFunctions/TableFunctionValues.cpp:0: DB::TableFunctionValues::executeImpl(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ColumnsDescription) const @ 0x1b868898 in /workspace/clickhouse
2021.05.26 19:36:02.106290 [ 154 ] {} <Fatal> BaseDaemon: 14. ./obj-x86_64-linux-gnu/../src/TableFunctions/ITableFunction.cpp:0: DB::ITableFunction::execute(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ColumnsDescription) const @ 0x1bf845b4 in /workspace/clickhouse
2021.05.26 19:36:02.286220 [ 154 ] {} <Fatal> BaseDaemon: 15.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:3120: shared_ptr
2021.05.26 19:36:02.286307 [ 154 ] {} <Fatal> BaseDaemon: 15.2. inlined from ../contrib/libcxx/include/memory:3243: std::__1::shared_ptr<DB::IStorage>::operator=(std::__1::shared_ptr<DB::IStorage>&&)
2021.05.26 19:36:02.286350 [ 154 ] {} <Fatal> BaseDaemon: 15. ../src/Interpreters/Context.cpp:1066: DB::Context::executeTableFunction(std::__1::shared_ptr<DB::IAST> const&) @ 0x1c097aba in /workspace/clickhouse
2021.05.26 19:36:02.349083 [ 154 ] {} <Fatal> BaseDaemon: 16. ./obj-x86_64-linux-gnu/../src/Interpreters/JoinedTables.cpp:0: DB::JoinedTables::getLeftTableStorage() @ 0x1c86e9ff in /workspace/clickhouse
2021.05.26 19:36:02.535824 [ 154 ] {} <Fatal> BaseDaemon: 17. ./obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:319: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&) @ 0x1c56b7b7 in /workspace/clickhouse
2021.05.26 19:36:02.715830 [ 154 ] {} <Fatal> BaseDaemon: 18. ./obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:160: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x1c56a951 in /workspace/clickhouse
2021.05.26 19:36:02.789386 [ 154 ] {} <Fatal> BaseDaemon: 19. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2068: std::__1::__unique_if<DB::InterpreterSelectQuery>::__unique_single std::__1::make_unique<DB::InterpreterSelectQuery, std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>&, DB::SelectQueryOptions&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&>(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>&, DB::SelectQueryOptions&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x1c81a1bc in /workspace/clickhouse
2021.05.26 19:36:02.855660 [ 154 ] {} <Fatal> BaseDaemon: 20. ./obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:212: DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter(std::__1::shared_ptr<DB::IAST> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x1c817685 in /workspace/clickhouse
2021.05.26 19:36:02.921865 [ 154 ] {} <Fatal> BaseDaemon: 21. ./obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:134: DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x1c815baa in /workspace/clickhouse
2021.05.26 19:36:02.980284 [ 154 ] {} <Fatal> BaseDaemon: 22. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:0: std::__1::__unique_if<DB::InterpreterSelectWithUnionQuery>::__unique_single std::__1::make_unique<DB::InterpreterSelectWithUnionQuery, std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>&, DB::SelectQueryOptions const&>(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>&, DB::SelectQueryOptions const&) @ 0x1c27338a in /workspace/clickhouse
2021.05.26 19:36:03.037903 [ 154 ] {} <Fatal> BaseDaemon: 23.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:1649: std::__1::unique_ptr<DB::InterpreterSelectWithUnionQuery, std::__1::default_delete<DB::InterpreterSelectWithUnionQuery> >::release()
2021.05.26 19:36:03.037954 [ 154 ] {} <Fatal> BaseDaemon: 23.2. inlined from ../contrib/libcxx/include/memory:1563: unique_ptr<DB::InterpreterSelectWithUnionQuery, std::__1::default_delete<DB::InterpreterSelectWithUnionQuery>, void, void>
2021.05.26 19:36:03.037997 [ 154 ] {} <Fatal> BaseDaemon: 23. ../src/Interpreters/InterpreterFactory.cpp:110: DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) @ 0x1c271e69 in /workspace/clickhouse
2021.05.26 19:36:03.139993 [ 154 ] {} <Fatal> BaseDaemon: 24. ./obj-x86_64-linux-gnu/../src/Interpreters/executeQuery.cpp:531: DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool, DB::ReadBuffer*) @ 0x1ca86617 in /workspace/clickhouse
2021.05.26 19:36:03.245915 [ 154 ] {} <Fatal> BaseDaemon: 25. ./obj-x86_64-linux-gnu/../src/Interpreters/executeQuery.cpp:920: DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool) @ 0x1ca8527f in /workspace/clickhouse
2021.05.26 19:36:03.348523 [ 154 ] {} <Fatal> BaseDaemon: 26. ./obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:312: DB::TCPHandler::runImpl() @ 0x1d5e52ce in /workspace/clickhouse
2021.05.26 19:36:03.464914 [ 154 ] {} <Fatal> BaseDaemon: 27. ./obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:1623: DB::TCPHandler::run() @ 0x1d60170d in /workspace/clickhouse
2021.05.26 19:36:03.468664 [ 154 ] {} <Fatal> BaseDaemon: 28. ./obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x1e5ec26c in /workspace/clickhouse
2021.05.26 19:36:03.479032 [ 154 ] {} <Fatal> BaseDaemon: 29. ./obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerDispatcher.cpp:114: Poco::Net::TCPServerDispatcher::run() @ 0x1e5ec74c in /workspace/clickhouse
2021.05.26 19:36:03.488401 [ 154 ] {} <Fatal> BaseDaemon: 30.1. inlined from ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/include/Poco/ScopedLock.h:36: ScopedLock
2021.05.26 19:36:03.488430 [ 154 ] {} <Fatal> BaseDaemon: 30. ../contrib/poco/Foundation/src/ThreadPool.cpp:213: Poco::PooledThread::run() @ 0x1e6d8e3a in /workspace/clickhouse
2021.05.26 19:36:03.496942 [ 154 ] {} <Fatal> BaseDaemon: 31.1. inlined from ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/include/Poco/SharedPtr.h:156: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable> >::assign(Poco::Runnable*)
2021.05.26 19:36:03.496971 [ 154 ] {} <Fatal> BaseDaemon: 31.2. inlined from ../contrib/poco/Foundation/include/Poco/SharedPtr.h:208: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable> >::operator=(Poco::Runnable*)
2021.05.26 19:36:03.497010 [ 154 ] {} <Fatal> BaseDaemon: 31. ../contrib/poco/Foundation/src/Thread_POSIX.cpp:360: Poco::ThreadImpl::runnableEntry(void*) @ 0x1e6d69ec in /workspace/clickhouse
2021.05.26 19:36:03.725536 [ 154 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: E93DEDF25B70F2187C4784AA5A6155F7. There is no information about the reference checksum.

```

**Comment by alexey-milovidov** [comment]
#24283
