### ISSUE TITLE
Is there any best practice for running functional-test in docker?

### ISSUE THREAD

**Issue by hssrs** [ClickHouse/ClickHouse#26016]
We made some adaptive and intrusive modifications to the ClickHouse source code, so we wanted to test ClickHouse locally. I found that the integration test has a ReadMe file, which is helpful. I was able to run the integration test in docker successfully, but I didn’t find the instructions for running functional-test **in docker**.
The reason why I want to run with docker is because I encountered some environmental problems when running locally:
```
export PATH=$PATH:/clickhouse/build/programs 
"/clickhouse/build/programs/clickhouse" --server -C /clickhouse/programs/server/config.xml & sleep 5
"/clickhouse/tests/clickhouse-test" -j16 --no-zookeeper --no-shard --no-stateful --use-skip-list > /clickhouse/tests/function_test_log
``` 

we get some FAIL cases in function_test_log, for example:

```
00825_protobuf_format_enum_mapping:                                     [ FAIL ] - return code 1
Traceback (most recent call last):
  File "/clickhouse/tests/queries/0_stateless/helpers/protobuf_length_delimited_encoder.py", line 174, in <module>
    decode_and_check(input, output, args.format_schema)
  File "/clickhouse/tests/queries/0_stateless/helpers/protobuf_length_delimited_encoder.py", line 126, in decode_and_check
    decode(tmp_input, tmp_decoded, format_schema)
  File "/clickhouse/tests/queries/0_stateless/helpers/protobuf_length_delimited_encoder.py", line 77, in decode
    shell=False) as proc:
  File "/usr/lib64/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'protoc': 'protoc'
, result:

Second
Third
First
First
Second

Binary representation:
00000000  02 08 01 02 08 64 00 00  02 08 01                 |.....d.....|
0000000b

OR

01676_long_clickhouse_client_autocomplete:                              [ FAIL ] - result differs with reference:
--- /clickhouse/tests/queries/0_stateless/01676_long_clickhouse_client_autocomplete.reference   2021-07-05 20:00:17.271835663 +0800
+++ /clickhouse/tests/queries/0_stateless/01676_long_clickhouse_client_autocomplete.stdout      2021-07-05 22:40:07.743460581 +0800
@@ -0,0 +1,2 @@
+[FAIL] test_shard_localhost (positive)
+[FAIL] default_path_test (positive)
``` 

It looks like some tools are not installed, so I think we may need to use the docker  from your side, e.g. `yandex/clickhouse-stateless-test` , but I am very new to docker and fail to make it run.
```
docker run -it yandex/clickhouse-stateless-test:latest /bin/bash
```
Should I rebuild the docker since I have modified the source code?
Is there any document or practice that I can learn how to run the functional-test **in docker**? 
Thank in advance！

**Comment by hssrs** [comment]
**Update:**
   After trying to look at `image.json` in the docker directory, I found an image called `yandex/clickhouse-stateless-test`, so I tried to run the functional test this way:

```
# function_test_helper.sh
export PATH=$PATH:/clickhouse/build/programs
"/clickhouse/build/programs/clickhouse" --server -C /clickhouse/programs/server/config.xml & sleep 5
"/clickhouse/tests/clickhouse-test" -j16 --no-zookeeper --no-shard --no-stateful --use-skip-list > /clickhouse/function_test_log
```
Then in the local machine:
```
docker run --name="functional-test" -v /clickhouse/:/clickhouse  yandex/clickhouse-stateless-test:latest  /function_test_helper.sh
```
It did run, but still get  some strange error, for example:
```
01636_nullable_fuzz2:                                                   [ FAIL ] - return code 23
[72bb0fac2fc7] 2021.07.08 23:18:00.626820 [ 486 ] {09c18b13-04a3-493c-b633-c9402ed15ef7} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 210, e.displayText() = DB::NetException: Connection refused (127.0.0.3:9000) (version 21.3.12.1)
[72bb0fac2fc7] 2021.07.08 23:18:00.628061 [ 486 ] {09c18b13-04a3-493c-b633-c9402ed15ef7} <Warning> ConnectionPoolWithFailover: Connection failed at try №2, reason: Code: 210, e.displayText() = DB::NetException: Connection refused (127.0.0.3:9000) (version 21.3.12.1)
[72bb0fac2fc7] 2021.07.08 23:18:00.629173 [ 486 ] {09c18b13-04a3-493c-b633-c9402ed15ef7} <Warning> ConnectionPoolWithFailover: Connection failed at try №3, reason: Code: 210, e.displayText() = DB::NetException: Connection refused (127.0.0.3:9000) (version 21.3.12.1)
[72bb0fac2fc7] 2021.07.08 23:18:00.638765 [ 7938 ] {09c18b13-04a3-493c-b633-c9402ed15ef7} <Error> executeQuery: Code: 279, e.displayText() = DB::NetException: All connection tries failed. Log:

Code: 210, e.displayText() = DB::NetException: Connection refused (127.0.0.3:9000) (version 21.3.12.1)
Code: 210, e.displayText() = DB::NetException: Connection refused (127.0.0.3:9000) (version 21.3.12.1)
Code: 210, e.displayText() = DB::NetException: Connection refused (127.0.0.3:9000) (version 21.3.12.1)

: While executing Remote (version 21.3.12.1) (from 127.0.0.1:52318) (comment: /clickhouse/tests/queries/0_stateless/01636_nullable_fuzz2.sql) (in query: SELECT EventDate FROM ( SELECT EventDate FROM tracking_events_tmp AS t1 WHERE (EventDate >= toDate('2020-07-09')) AND (EventDate <= toDate('2020-07-11')) AND (APIKey = 2) GROUP BY EventDate ) FULL OUTER JOIN ( SELECT EventDate FROM remote('127.0.0.{1,3}', currentDatabase(), open_events_tmp) AS t2 WHERE (EventDate <= toDate('2020-07-12')) AND (APIKey = 2) GROUP BY EventDate WITH TOTALS ) USING (EventDate) ORDER BY EventDate ASC SETTINGS totals_mode = 'after_having_auto', group_by_overflow_mode = 'any', max_rows_to_group_by = 10000000, joined_subquery_requires_alias = 0;), Stack trace (when copying this message, always include the lines below):

0. /u01/codehub_artifacts/clickhouse/build/../contrib/libcxx/include/exception:133: std::exception::capture() @ 0x7a1cd39 in /clickhouse/build/programs/clickhouse
1. /u01/codehub_artifacts/clickhouse/build/../contrib/libcxx/include/exception:111: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1b68e044 in /clickhouse/build/programs/clickhouse
2. /u01/codehub_artifacts/clickhouse/build/../src/Common/Exception.cpp:55: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x7a14787 in /clickhouse/build/programs/clickhouse
3. /u01/codehub_artifacts/clickhouse/build/../src/Common/NetException.h:12: DB::NetException::NetException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x7b63051 in /clickhouse/build/programs/clickhouse
4. /u01/codehub_artifacts/clickhouse/build/../src/Common/PoolWithFailoverBase.h:291: PoolWithFailoverBase<DB::IConnectionPool>::getMany(unsigned long, unsigned long, unsigned long, unsigned long, bool, std::__1::function<PoolWithFailoverBase<DB::IConnectionPool>::TryResult (DB::IConnectionPool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)> const&, std::__1::function<unsigned long (unsigned long)> const&) @ 0x15808c3c in /clickhouse/build/programs/clickhouse
5. /u01/codehub_artifacts/clickhouse/build/../src/Client/ConnectionPoolWithFailover.cpp:233: DB::ConnectionPoolWithFailover::getManyImpl(DB::Settings const*, DB::PoolMode, std::__1::function<PoolWithFailoverBase<DB::IConnectionPool>::TryResult (DB::IConnectionPool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)> const&) @ 0x15801db0 in /clickhouse/build/programs/clickhouse
6. /u01/codehub_artifacts/clickhouse/build/../src/Client/ConnectionPoolWithFailover.cpp:164: DB::ConnectionPoolWithFailover::getManyChecked(DB::ConnectionTimeouts const&, DB::Settings const*, DB::PoolMode, DB::QualifiedTableName const&) @ 0x15801703 in /clickhouse/build/programs/clickhouse
7. /u01/codehub_artifacts/clickhouse/build/../src/DataStreams/RemoteQueryExecutor.cpp:82: DB::RemoteQueryExecutor::RemoteQueryExecutor(std::__1::shared_ptr<DB::ConnectionPoolWithFailover> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Block const&, DB::Context const&, std::__1::shared_ptr<DB::Throttler> const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, DB::Block, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, DB::Block> > > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<DB::IStorage>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::shared_ptr<DB::IStorage> > > > const&, DB::QueryProcessingStage::Enum)::'lambda'()::operator()() const @ 0x1406032a in /clickhouse/build/programs/clickhouse

OR

01791_dist_INSERT_block_structure_mismatch:                             [ FAIL ] - having exception:
<Warning> DistributedBlockOutputStream: Structure does not match (remote: n Int8 Int8(size = 0), local: n UInt64 UInt64(size = 1)), implicit conversion will be done.
<Error> executeQuery: Code: 210, e.displayText() = DB::NetException: Connection refused (127.0.0.2:9000): Insertion status:
Wrote 1 blocks and 1 rows on shard 0 replica 0, 127.0.0.1:9000 (average 6 ms per block)
Wrote 0 blocks and 0 rows on shard 1 replica 0, 127.0.0.2:9000 (average 1 ms per block)
 (version 21.3.12.1) (from 127.0.0.1:49050) (comment: '/clickhouse/tests/queries/0_stateless/01866_datetime64_cmp_with_constant.sql') (in query: INSERT INTO dist_01683 VALUES ), Stack trace (when copying this message, always include the lines below):

0. /u01/codehub_artifacts/clickhouse/build/../contrib/libcxx/include/exception:133: std::exception::capture() @ 0x7a1cd39 in /clickhouse/build/programs/clickhouse
<char> > const&, int) @ 0x1b68e044 in /clickhouse/build/programs/clickhouse
<char> > const&, int, bool) @ 0x7a14787 in /clickhouse/build/programs/clickhouse
<char> > const&, int) @ 0x7b63051 in /clickhouse/build/programs/clickhouse
4. /u01/codehub_artifacts/clickhouse/build/../src/Client/Connection.cpp:129: DB::Connection::connect(DB::ConnectionTimeouts const&) @ 0x157e6040 in /clickhouse/build/programs/clickhouse
5. /u01/codehub_artifacts/clickhouse/build/../src/Client/Connection.cpp:324: DB::Connection::forceConnected(DB::ConnectionTimeouts const&) @ 0x157e7e40 in /clickhouse/build/programs/clickhouse
6. /u01/codehub_artifacts/clickhouse/build/../src/Client/ConnectionPool.h:92: DB::ConnectionPool::get(DB::ConnectionTimeouts const&, DB::Settings const*, bool) @ 0x7c76b22 in /clickhouse/build/programs/clickhouse
7. /u01/codehub_artifacts/clickhouse/build/../src/Storages/Distributed/DistributedBlockOutputStream.cpp:266: DB::DistributedBlockOutputStream::runWritingJob(DB::DistributedBlockOutputStream::JobReplica&, DB::Block const&, unsigned long)::'lambda'()::operator()() const @ 0x1520b54c in /clickhouse/build/programs/clickhouse
<DB::DistributedBlockOutputStream::runWritingJob(DB::DistributedBlockOutputStream::JobReplica&, DB::Block const&, unsigned long)::'lambda'()&>(DB::DistributedBlockOutputStream::runWritingJob(DB::DistributedBlockOutputStream::JobReplica&, DB::Block const&, unsigned long)::'lambda'()&) @ 0x15216d3d in /clickhouse/build/programs/clickhouse
<DB::DistributedBlockOutputStream::runWritingJob(DB::DistributedBlockOutputStream::JobReplica&, DB::Block const&, unsigned long)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x15216b10 in /clickhouse/build/programs/clickhouse
<void ()>::operator()() const @ 0x7a60211 in /clickhouse/build/programs/clickhouse
<ThreadFromGlobalPool, void*>) @ 0x7ac16d3 in /clickhouse/build/programs/clickhouse
<unsigned long>)::'lambda1'()::operator()() const @ 0x7ac61be in /clickhouse/build/programs/clickhouse
<unsigned long>)::'lambda1'()&&...)::'lambda'()::operator()() @ 0x7accf99 in /clickhouse/build/programs/clickhouse
<unsigned long>)::'lambda1'()&&...)::'lambda'()&>(void&&...) @ 0x7ad39a2 in /clickhouse/build/programs/clickhouse
<unsigned long>)::'lambda1'()&&...)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x7ad35a3 in /clickhouse/build/programs/clickhouse
<void ()>::operator()() const @ 0x7a60211 in /clickhouse/build/programs/clickhouse
<std::__1::thread, void*>) @ 0x7abfd93 in /clickhouse/build/programs/clickhouse
<unsigned long>)::'lambda1'()::operator()() const @ 0x7ac2778 in /clickhouse/build/programs/clickhouse
<unsigned long>)::'lambda1'()> >(void*) @ 0x7acecfa in /clickhouse/build/programs/clickhouse
20. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
21. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so

Received exception from server (version 21.3.12):
Code: 210. DB::Exception: Received from localhost:9000. DB::Exception: Connection refused (127.0.0.2:9000): Insertion status:
Wrote 1 blocks and 1 rows on shard 0 replica 0, 127.0.0.1:9000 (average 6 ms per block)
Wrote 0 blocks and 0 rows on shard 1 replica 0, 127.0.0.2:9000 (average 1 ms per block)
.
```

I have no idea how to fix it or what should I do to confirm if this is due to the environment?

**Comment by bkuschel** [comment]
listen_host set to 0.0.0.0 won't work from the docker container unless you export the ports. If you don't want to do that, you'll have to set the listen_host to be 127.0.0.1 and 127.0.0.2 etc. I believe they go all the way up to 127.0.0.12 for the functional tests, so you'd after add that entire range as listen_hosts.

**Comment by alexey-milovidov** [comment]
These configuration files describing how the tests run in our CI: https://github.com/ClickHouse/ClickHouse/tree/master/.github/workflows
