### ISSUE TITLE
clickhouse-client systematically killed by oom

### ISSUE THREAD

**Issue by w4x-gh** [ClickHouse/ClickHouse#26033]
ClickHouse client version 21.5.5.12 is systematically killed when I execute any command. 

System details: debian buster with 16G RAM
Clickhouse server version: 21.5.5 revision 54448

Bug:
root@debian:~# clickhouse-client --ask-password
ClickHouse client version 21.5.5.12 (official build).
Password for user (default): 
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 21.5.5 revision 54448.

debian :) show databases
Killed
root@debian:~# 

dmesg log:
[ts] Out of memory: Kill process 23121 (clickhouse-clie) score 799 or sacrifice child
[ts] Killed process 23121 (clickhouse-clie) total-vm:26893548kB, anon-rss:14503432kB, file-rss:44304kB, shmem-rss:0kB
[ts] oom_reaper: reaped process 23121 (clickhouse-clie), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB

The server is running fine and has not at any point suffered been stopped. 

I've looked up similar issues faced by users and they are all related to the clickhouse server not the client. 
This also means that nothing meaningful is logged when the client is killed.

**Comment by alexey-milovidov** [comment]
What happens if you run `curl 'http://localhost:8123/' -d 'SHOW DATABASES'`?
Could you please paste server logs corresponding to this query?

**Comment by w4x-gh** [comment]
The request: 
debian:~# curl 'http://localhost:8123/?user=default&password=somepwd' -d 'SHOW DATABASES'
mychdb
default
system

The logs: 

2021.07.07 13:12:07.822396 [ 23062 ] {} <Trace> HTTPHandler-factory: HTTP Request for HTTPHandler-factory. Method: POST, Address: [::1]:46146, User-Agent: curl/7.64.0, Length: 14, Content Type: application/x-www-form-urlencoded, Transfer Encoding: identity, X-Forwarded-For: (none)
2021.07.07 13:12:07.822678 [ 23062 ] {} <Trace> DynamicQueryHandler: Request URI: /?user=default&password=somepwd
2021.07.07 13:12:07.822984 [ 23062 ] {} <Trace> ContextAccess (default): Settings: readonly=0, allow_ddl=true, allow_introspection_functions=false
2021.07.07 13:12:07.823050 [ 23062 ] {} <Trace> ContextAccess (default): List of all grants: GRANT SHOW, SELECT, INSERT, ALTER, CREATE, DROP, TRUNCATE, OPTIMIZE, KILL QUERY, SYSTEM, dictGet, INTROSPECTION, SOURCES ON *.*
2021.07.07 13:12:07.823076 [ 23062 ] {} <Trace> ContextAccess (default): List of all grants including implicit: GRANT SHOW, SELECT, INSERT, ALTER, CREATE, DROP, TRUNCATE, OPTIMIZE, KILL QUERY, SYSTEM, dictGet, INTROSPECTION, SOURCES ON *.*
2021.07.07 13:12:07.823596 [ 23062 ] {3b9b2fb3-1a71-4bea-991f-6102983c122c} <Debug> executeQuery: (from [::1]:46146, using production parser) SHOW DATABASES
2021.07.07 13:12:07.824082 [ 23062 ] {3b9b2fb3-1a71-4bea-991f-6102983c122c} <Debug> executeQuery: (internal) SELECT name FROM system.databases
2021.07.07 13:12:07.824744 [ 23062 ] {3b9b2fb3-1a71-4bea-991f-6102983c122c} <Trace> ContextAccess (default): Access granted: SELECT(name) ON system.databases
2021.07.07 13:12:07.824892 [ 23062 ] {3b9b2fb3-1a71-4bea-991f-6102983c122c} <Trace> ContextAccess (default): Access granted: SHOW DATABASES ON *.*
2021.07.07 13:12:07.825083 [ 23062 ] {3b9b2fb3-1a71-4bea-991f-6102983c122c} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2021.07.07 13:12:07.825565 [ 23062 ] {3b9b2fb3-1a71-4bea-991f-6102983c122c} <Trace> ParallelFormattingOutputFormat: Parallel formatting is being used
2021.07.07 13:12:07.826718 [ 23062 ] {3b9b2fb3-1a71-4bea-991f-6102983c122c} <Information> executeQuery: Read 3 rows, 414.00 B in 0.003020786 sec., 993 rows/sec., 133.84 KiB/sec.
2021.07.07 13:12:07.827108 [ 23062 ] {3b9b2fb3-1a71-4bea-991f-6102983c122c} <Debug> DynamicQueryHandler: Done processing query
2021.07.07 13:12:07.827175 [ 23062 ] {3b9b2fb3-1a71-4bea-991f-6102983c122c} <Debug> MemoryTracker: Peak memory usage (for query): 3.00 MiB.
2021.07.07 13:12:07.827206 [ 23062 ] {} <Debug> MemoryTracker: Peak memory usage (for query): 3.00 MiB.
2021.07.07 13:12:11.920887 [ 23074 ] {} <Trace> SystemLog (system.query_thread_log): Flushing system log, 3 entries to flush up to offset 4497
2021.07.07 13:12:11.922890 [ 23074 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 92.97 GiB.
2021.07.07 13:12:11.931714 [ 23074 ] {} <Trace> system.query_thread_log: Renaming temporary part tmp_insert_202107_502_502_0 to 202107_52262_52262_0.
2021.07.07 13:12:11.932066 [ 23074 ] {} <Trace> SystemLog (system.query_thread_log): Flushed system log up to offset 4497
^C

**Comment by alexey-milovidov** [comment]
Ok. The server processed this request successfully with neglible amount of allocated RAM.

It remains in question why the client allocates so much RAM on the same request.
Does it die instantly or it takes several seconds?

You can stop clickhouse-client with gdb during this several seconds and print stack traces:
`sudo gdb -batch -ex 'thread apply all backtrace' -p $(pidof clickhouse-client)`
and show the result.

**Comment by w4x-gh** [comment]
1/ Before password entry:

root@debian:~# gdb -batch -ex 'thread apply all backtrace' -p 14363
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007fca3a95450e in __libc_read (fd=5, buf=0x7ffc5116558b, nbytes=1) at ../sysdeps/unix/sysv/linux/read.c:26
26	../sysdeps/unix/sysv/linux/read.c: No such file or directory.

Thread 1 (Thread 0x7fca3a5fa000 (LWP 14363)):
#0  0x00007fca3a95450e in __libc_read (fd=5, buf=0x7ffc5116558b, nbytes=1) at ../sysdeps/unix/sysv/linux/read.c:26
#1  0x000000000e997540 in readpassphrase ()
#2  0x000000000889d0cd in DB::ConnectionParameters::ConnectionParameters(Poco::Util::AbstractConfiguration const&) ()
#3  0x0000000008869025 in DB::Client::connect() ()
#4  0x0000000008865c30 in DB::Client::mainImpl() ()
#5  0x0000000008862d94 in DB::Client::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) ()
#6  0x0000000012434483 in Poco::Util::Application::run() ()
#7  0x0000000008856f4f in mainEntryClickHouseClient(int, char**) ()
#8  0x000000000879839e in main ()
[Inferior 1 (process 14363) detached]

2/ After password entry and client prompt is ready to accept commands:

root@debian:~# gdb -batch -ex 'thread apply all backtrace' -p 14363
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007fca3a873037 in __GI___select (nfds=8, readfds=0x7ffc51165f88, writefds=0x0, exceptfds=0x0, timeout=0x0) at ../sysdeps/unix/sysv/linux/select.c:41
41	../sysdeps/unix/sysv/linux/select.c: No such file or directory.

Thread 1 (Thread 0x7fca3a5fa000 (LWP 14363)):
#0  0x00007fca3a873037 in __GI___select (nfds=8, readfds=0x7ffc51165f88, writefds=0x0, exceptfds=0x0, timeout=0x0) at ../sysdeps/unix/sysv/linux/select.c:41
#1  0x00000000125c3fee in replxx::Terminal::wait_for_input(long) ()
#2  0x00000000125af11b in replxx::Replxx::ReplxxImpl::read_char(replxx::Replxx::ReplxxImpl::HINT_ACTION) ()
#3  0x00000000125b1b8c in replxx::Replxx::ReplxxImpl::get_input_line() ()
#4  0x00000000125b140c in replxx::Replxx::ReplxxImpl::input(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) ()
#5  0x00000000123b4f36 in ReplxxLineReader::readOneLine(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) ()
#6  0x00000000123b1c9d in LineReader::readLine(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) ()
#7  0x0000000008867699 in DB::Client::mainImpl() ()
#8  0x0000000008862d94 in DB::Client::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) ()
#9  0x0000000012434483 in Poco::Util::Application::run() ()
#10 0x0000000008856f4f in mainEntryClickHouseClient(int, char**) ()
#11 0x000000000879839e in main ()
[Inferior 1 (process 14363) detached]

**Comment by alexey-milovidov** [comment]
@w4x-gh I need this report at the moment before OOM happens.

**Comment by filimonov** [comment]
Also - share full fragment of oomkiller logs (including 'Call Trace' fragment)

**Comment by alexey-milovidov** [comment]
No info.

**Comment by w4x-gh** [comment]
Hi, can you please reopen this issue. I'm sorry for disappearing, was not in a position to provide more info.

GDB results (in interactive mode, with the same options ie. thread apply all backtrace (basically same as before)


```
Attaching to process 855
Reading symbols from /usr/bin/clickhouse...(no debugging symbols found)...done.
Reading symbols from /lib/x86_64-linux-gnu/libpthread.so.0...Reading symbols from /usr/lib/debug/.build-id/e9/1114987a0147bd050addbd591eb8994b29f4b3.debug...done.
done.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Reading symbols from /lib/x86_64-linux-gnu/librt.so.1...Reading symbols from /usr/lib/debug/.build-id/5d/cf98ad684962be494af28a1051793fd39e4ebc.debug...done.
done.
Reading symbols from /lib/x86_64-linux-gnu/libdl.so.2...Reading symbols from /usr/lib/debug/.build-id/d3/583c742dd47aaa860c5ae0c0c5bdbcd2d54f61.debug...done.
done.
Reading symbols from /lib/x86_64-linux-gnu/libc.so.6...Reading symbols from /usr/lib/debug/.build-id/18/b9a9a8c523e5cfe5b5d946d605d09242f09798.debug...done.
done.
Reading symbols from /lib/x86_64-linux-gnu/libm.so.6...Reading symbols from /usr/lib/debug/.build-id/88/5dda4b4a5cea600e7b5b98c1ad86996c8d2299.debug...done.
done.
Reading symbols from /lib64/ld-linux-x86-64.so.2...Reading symbols from /usr/lib/debug/.build-id/f2/5dfd7b95be4ba386fd71080accae8c0732b711.debug...done.
done.
Reading symbols from /lib/x86_64-linux-gnu/libnss_files.so.2...Reading symbols from /usr/lib/debug/.build-id/4b/ff8b782e1602c596e856bdef06e642e50e7fa7.debug...done.
done.
0x00007f8fd459c037 in __GI___select (nfds=8, readfds=0x7ffed2009c68, writefds=0x0, exceptfds=0x0, timeout=0x0)
    at ../sysdeps/unix/sysv/linux/select.c:41
41	../sysdeps/unix/sysv/linux/select.c: No such file or directory.
(gdb) continue
Continuing.
^C
Program received signal SIGINT, Interrupt.
0x00007f8fd459c037 in __GI___select (nfds=8, readfds=0x7ffed2009c68, writefds=0x0, exceptfds=0x0, timeout=0x0)
    at ../sysdeps/unix/sysv/linux/select.c:41
41	in ../sysdeps/unix/sysv/linux/select.c
(gdb) set logging on
Copying output to gdb.txt.
(gdb) thread apply all backtrace

Thread 1 (Thread 0x7f8fd4323ac0 (LWP 855)):
#0  0x00007f8fd459c037 in __GI___select (nfds=8, readfds=0x7ffed2009c68, writefds=0x0, exceptfds=0x0, 
    timeout=0x0) at ../sysdeps/unix/sysv/linux/select.c:41
#1  0x000000001351c86e in replxx::Terminal::wait_for_input(long) ()
#2  0x0000000013507c9b in replxx::Replxx::ReplxxImpl::read_char(replxx::Replxx::ReplxxImpl::HINT_ACTION) ()
#3  0x000000001350a70c in replxx::Replxx::ReplxxImpl::get_input_line() ()
#4  0x0000000013509f8c in replxx::Replxx::ReplxxImpl::input(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) ()
#5  0x000000001331ddd6 in ReplxxLineReader::readOneLine(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) ()
#6  0x000000001331aa1d in LineReader::readLine(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) ()
#7  0x0000000008dfda77 in DB::Client::mainImpl() ()
#8  0x0000000008dfa3b4 in DB::Client::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) ()
#9  0x0000000013394743 in Poco::Util::Application::run() ()
#10 0x0000000008dee38f in mainEntryClickHouseClient(int, char**) ()
#11 0x0000000008d2b95e in main ()
(gdb) continue 
Continuing.

Program terminated with signal SIGKILL, Killed.
The program no longer exists.
(gdb) set logging off 
Done logging to gdb.txt.
(gdb) quit

```

As for the oom killer logs: 

````

[1168512.299583] BgSchPool invoked oom-killer: gfp_mask=0x6200ca(GFP_HIGHUSER_MOVABLE), nodemask=(null), order=0, oom_score_adj=0
[1168512.299587] BgSchPool cpuset=/ mems_allowed=0
[1168512.299595] CPU: 3 PID: 1359 Comm: BgSchPool Not tainted 4.19.0-17-amd64 #1 Debian 4.19.194-3
[1168512.299596] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS rel-1.14.0-0-g155821a1990b-prebuilt.qemu.org 04/01/2014
[1168512.299598] Call Trace:
[1168512.299633]  dump_stack+0x66/0x81
[1168512.299638]  dump_header+0x6b/0x283
[1168512.299644]  ? do_try_to_free_pages+0x2ec/0x370
[1168512.299647]  oom_kill_process.cold.30+0xb/0x1cf
[1168512.299653]  ? oom_badness+0xee/0x140
[1168512.299657]  out_of_memory+0x1a5/0x450
[1168512.299661]  __alloc_pages_slowpath+0xbd8/0xcb0
[1168512.299666]  __alloc_pages_nodemask+0x28b/0x2b0
[1168512.299670]  filemap_fault+0x333/0x780
[1168512.299674]  ? filemap_map_pages+0x1ed/0x3a0
[1168512.299710]  ext4_filemap_fault+0x2c/0x40 [ext4]
[1168512.299715]  __do_fault+0x36/0x130
[1168512.299718]  __handle_mm_fault+0xdf9/0x11f0
[1168512.299723]  handle_mm_fault+0xd6/0x200
[1168512.299726]  __do_page_fault+0x249/0x4f0
[1168512.299732]  ? async_page_fault+0x8/0x30
[1168512.299735]  async_page_fault+0x1e/0x30
[1168512.299739] RIP: 0033:0x7f36598ed3f9
[1168512.299763] Code: Bad RIP value.
[1168512.299765] RSP: 002b:00007f35f7404670 EFLAGS: 00010282
[1168512.299768] RAX: ffffffffffffff92 RBX: 00007f36387391c8 RCX: 00007f36598ed3f9
[1168512.299769] RDX: 0000000000000000 RSI: 0000000000000080 RDI: 00007f36387391f0
[1168512.299771] RBP: 0000000000000000 R08: 0000000000000000 R09: 00070c9bdfeb1b59
[1168512.299772] R10: 00007f35f74046c0 R11: 0000000000000282 R12: 00007f36387391f0
[1168512.299774] R13: 00007f35f7404768 R14: 00007f36387391a0 R15: 0000000000000002
[1168512.299777] Mem-Info:
[1168512.299784] active_anon:3569185 inactive_anon:398610 isolated_anon:0
                  active_file:179 inactive_file:96 isolated_file:0
                  unevictable:50248 dirty:0 writeback:42 unstable:0
                  slab_reclaimable:9677 slab_unreclaimable:16109
                  mapped:50399 shmem:113 pagetables:14341 bounce:0
                  free:33730 free_pcp:4 free_cma:0
[1168512.299789] Node 0 active_anon:14276740kB inactive_anon:1594440kB active_file:716kB inactive_file:384kB unevictable:200992kB isolated(anon):0kB isolated(file):0kB mapped:201596kB dirty:0kB writeback:168kB shmem:452kB shmem_thp: 0kB shmem_pmdmapped: 0kB anon_thp: 6737920kB writeback_tmp:0kB unstable:0kB all_unreclaimable? no
[1168512.299791] Node 0 DMA free:15900kB min:64kB low:80kB high:96kB active_anon:0kB inactive_anon:0kB active_file:0kB inactive_file:0kB unevictable:0kB writepending:0kB present:15992kB managed:15908kB mlocked:0kB kernel_stack:0kB pagetables:0kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
[1168512.299797] lowmem_reserve[]: 0 2963 15994 15994 15994
[1168512.299800] Node 0 DMA32 free:64500kB min:12508kB low:15632kB high:18756kB active_anon:2999068kB inactive_anon:0kB active_file:0kB inactive_file:0kB unevictable:0kB writepending:0kB present:3129192kB managed:3063624kB mlocked:0kB kernel_stack:0kB pagetables:12kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
[1168512.299805] lowmem_reserve[]: 0 0 13030 13030 13030
[1168512.299808] Node 0 Normal free:54520kB min:55004kB low:68752kB high:82500kB active_anon:11277168kB inactive_anon:1594440kB active_file:400kB inactive_file:284kB unevictable:200992kB writepending:168kB present:13631488kB managed:13347516kB mlocked:200992kB kernel_stack:5472kB pagetables:57352kB bounce:0kB free_pcp:16kB local_pcp:0kB free_cma:0kB
[1168512.299813] lowmem_reserve[]: 0 0 0 0 0
[1168512.299816] Node 0 DMA: 1*4kB (U) 1*8kB (U) 1*16kB (U) 0*32kB 2*64kB (U) 1*128kB (U) 1*256kB (U) 0*512kB 1*1024kB (U) 1*2048kB (M) 3*4096kB (M) = 15900kB
[1168512.299827] Node 0 DMA32: 7*4kB (UM) 7*8kB (UM) 8*16kB (UME) 7*32kB (UME) 7*64kB (UE) 3*128kB (UE) 3*256kB (UE) 8*512kB (UME) 9*1024kB (UME) 4*2048kB (ME) 10*4096kB (UE) = 64500kB
[1168512.299839] Node 0 Normal: 3119*4kB (UME) 253*8kB (UME) 153*16kB (UME) 216*32kB (UME) 117*64kB (UME) 40*128kB (UME) 25*256kB (UME) 1*512kB (M) 12*1024kB (UM) 0*2048kB 0*4096kB = 55668kB
[1168512.299851] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=1048576kB
[1168512.299853] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=2048kB
[1168512.299854] 156596 total pagecache pages
[1168512.299857] 105941 pages in swap cache
[1168512.299858] Swap cache stats: add 1541918, delete 1435939, find 262984/507436
[1168512.299860] Free swap  = 0kB
[1168512.299861] Total swap = 2002940kB
[1168512.299862] 4194168 pages RAM
[1168512.299863] 0 pages HighMem/MovableOnly
[1168512.299864] 87406 pages reserved
[1168512.299865] 0 pages hwpoisoned
[1168512.299866] Tasks state (memory values in pages):

[1168512.299986] Out of memory: Kill process 855 (clickhouse-clie) score 841 or sacrifice child
[1168512.300112] Killed process 855 (clickhouse-clie) total-vm:26922688kB, anon-rss:14843692kB, file-rss:49000kB, shmem-rss:0kB
[1168512.749820] oom_reaper: reaped process 855 (clickhouse-clie), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

**Comment by filimonov** [comment]
May be related to the history file bad processing after upgrade from old clickhouse versions (pre 19).

Check the size of clickhouse history file. 

```
ls -la ~/.clickhouse-history
```

If it's huge - just remove/rename it.

**Comment by w4x-gh** [comment]
I history file was 496MB and renaming it seems  to have solved the issue. 
```
root@debian:~# du -sh ~/.clickhouse-client-history
496M    /root/.clickhouse-client-history
```
The client is now snappy and has not been killed by oom reaper. 

Thanks for your help
