### ISSUE TITLE
Logical error: 'Number of rows mismatch after evaluation of batch of constant expressions

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#27620]
Fuzz Report: https://clickhouse-test-reports.s3.yandex.net/27525/9b81c075c636d170ba3aba1e26ef10d5161aacb6/fuzzer_debug/report.html#fail1
CI: https://github.com/ClickHouse/ClickHouse/pull/27525

**Describe the bug**

Logical error when doing crazy stuff in the partition expresion of `ALTER TABLE .. ATTACH PARTITION`.

**How to reproduce**

SQL (removed the replication since it reproduces without it):

```sql
CREATE TABLE restore_01640 (`i` Int64, `d` Date, `s` String) ENGINE = MergeTree PARTITION BY toYYYYMM(d) ORDER BY i


ALTER TABLE restore_01640
    ATTACH PARTITION tuple(toYYYYMM(toDate([arrayJoin([arrayJoin([arrayJoin([arrayJoin([3, materialize(NULL), arrayJoin([1025, materialize(NULL), materialize(NULL)]), NULL])])]), materialize(NULL)])], NULL)))
```

Logs (local debug build):

```
2021.08.12 16:30:46.289959 [ 289174 ] {663a90c8-e005-490b-9bac-f28cc2e0bcac} <Fatal> : Logical error: 'Number of rows mismatch after evaluation of batch of constant expressions: got 24 rows for 1 expressions'.
2021.08.12 16:30:46.291616 [ 289556 ] {} <Fatal> BaseDaemon: ########################################
2021.08.12 16:30:46.292056 [ 289556 ] {} <Fatal> BaseDaemon: (version 21.9.1.1, build id: EFCA7A36EA9E1FD327B97AC39980BCB6BFE9C1AC) (from thread 289174) (query_id: 663a90c8-e005-490b-9bac-f28cc2e0bcac) Received signal Aborted (6)
2021.08.12 16:30:46.292859 [ 289556 ] {} <Fatal> BaseDaemon: 
2021.08.12 16:30:46.293793 [ 289556 ] {} <Fatal> BaseDaemon: Stack trace: 0x7fe4becb9d22 0x7fe4beca3862 0x128ce859 0x128ce992 0x1f9fa8af 0x1f9eec2b 0x1f645800 0x1f645531 0x1b583174 0x1d9d6980 0x1f1324c9 0x1f14363e 0x1dfd1df3 0x1e99fb32 0x1e99dc1e 0x1f5eb167 0x1f5f8e52 0x23f9ff99 0x23fa0834 0x24105881 0x24101eba 0x24100b3a 0x7fe4bee64259 0x7fe4bed7b5e3
2021.08.12 16:30:46.294536 [ 289556 ] {} <Fatal> BaseDaemon: 4. raise @ 0x3cd22 in /usr/lib/libc-2.33.so
2021.08.12 16:30:46.294656 [ 289556 ] {} <Fatal> BaseDaemon: 5. __GI_abort @ 0x26862 in /usr/lib/libc-2.33.so
2021.08.12 16:30:46.465110 [ 289556 ] {} <Fatal> BaseDaemon: 6. /mnt/ch/ClickHouse/src/Common/Exception.cpp:53: DB::handle_error_code(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool, std::__1::vector<void*, std::__1::allocator<void*> > const&) @ 0x128ce859 in /mnt/ch/ClickHouse/build_head_asserts/programs/clickhouse
2021.08.12 16:30:46.618264 [ 289556 ] {} <Fatal> BaseDaemon: 7. /mnt/ch/ClickHouse/src/Common/Exception.cpp:60: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x128ce992 in /mnt/ch/ClickHouse/build_head_asserts/programs/clickhouse
2021.08.12 16:30:47.014001 [ 289556 ] {} <Fatal> BaseDaemon: 8. /mnt/ch/ClickHouse/src/Processors/Formats/Impl/ConstantExpressionTemplate.cpp:603: DB::ConstantExpressionTemplate::evaluateAll(DB::BlockMissingValues&, unsigned long, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) @ 0x1f9fa8af in /mnt/ch/ClickHouse/build_head_asserts/programs/clickhouse
2021.08.12 16:30:47.248423 [ 289556 ] {} <Fatal> BaseDaemon: 9. /mnt/ch/ClickHouse/src/Processors/Formats/Impl/ValuesBlockInputFormat.cpp:82: DB::ValuesBlockInputFormat::generate() @ 0x1f9eec2b in /mnt/ch/ClickHouse/build_head_asserts/programs/clickhouse
2021.08.12 16:30:47.324152 [ 289556 ] {} <Fatal> BaseDaemon: 10. /mnt/ch/ClickHouse/src/Processors/ISource.cpp:79: DB::ISource::tryGenerate() @ 0x1f645800 in /mnt/ch/ClickHouse/build_head_asserts/programs/clickhouse
2021.08.12 16:30:47.398163 [ 289556 ] {} <Fatal> BaseDaemon: 11. /mnt/ch/ClickHouse/src/Processors/ISource.cpp:53: DB::ISource::work() @ 0x1f645531 in /mnt/ch/ClickHouse/build_head_asserts/programs/clickhouse
2021.08.12 16:30:47.651000 [ 289556 ] {} <Fatal> BaseDaemon: 12. /mnt/ch/ClickHouse/src/Processors/Formats/InputStreamFromInputFormat.h:49: DB::InputStreamFromInputFormat::readImpl() @ 0x1b583174 in /mnt/ch/ClickHouse/build_head_asserts/programs/clickhouse
2021.08.12 16:30:47.776087 [ 289556 ] {} <Fatal> BaseDaemon: 13. /mnt/ch/ClickHouse/src/DataStreams/IBlockInputStream.cpp:57: DB::IBlockInputStream::read() @ 0x1d9d6980 in /mnt/ch/ClickHouse/build_head_asserts/programs/clickhouse
2021.08.12 16:30:48.000187 [ 289456 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 1.13 GiB, peak 1.13 GiB, will set to 1.17 GiB (RSS), difference: 43.05 MiB
2021.08.12 16:30:48.569010 [ 289556 ] {} <Fatal> BaseDaemon: 14. /mnt/ch/ClickHouse/src/Storages/MergeTree/MergeTreeData.cpp:3264: DB::MergeTreeData::getPartitionIDFromQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>) const @ 0x1f1324c9 in /mnt/ch/ClickHouse/build_head_asserts/programs/clickhouse
2021.08.12 16:30:49.000644 [ 289456 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 1.17 GiB, peak 1.17 GiB, will set to 1.20 GiB (RSS), difference: 26.57 MiB
2021.08.12 16:30:49.313826 [ 289556 ] {} <Fatal> BaseDaemon: 15. /mnt/ch/ClickHouse/src/Storages/MergeTree/MergeTreeData.cpp:2942: DB::MergeTreeData::checkAlterPartitionIsPossible(std::__1::vector<DB::PartitionCommand, std::__1::allocator<DB::PartitionCommand> > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::Settings const&) const @ 0x1f14363e in /mnt/ch/ClickHouse/build_head_asserts/programs/clickhouse
2021.08.12 16:30:49.735086 [ 289556 ] {} <Fatal> BaseDaemon: 16. /mnt/ch/ClickHouse/src/Interpreters/InterpreterAlterQuery.cpp:118: DB::InterpreterAlterQuery::execute() @ 0x1dfd1df3 in /mnt/ch/ClickHouse/build_head_asserts/programs/clickhouse
2021.08.12 16:30:50.000187 [ 289456 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 1.20 GiB, peak 1.20 GiB, will set to 1.20 GiB (RSS), difference: 5.61 MiB
2021.08.12 16:30:50.116492 [ 289556 ] {} <Fatal> BaseDaemon: 17. /mnt/ch/ClickHouse/src/Interpreters/executeQuery.cpp:560: DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool, DB::ReadBuffer*) @ 0x1e99fb32 in /mnt/ch/ClickHouse/build_head_asserts/programs/clickhouse
2021.08.12 16:30:50.520935 [ 289556 ] {} <Fatal> BaseDaemon: 18. /mnt/ch/ClickHouse/src/Interpreters/executeQuery.cpp:909: DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool) @ 0x1e99dc1e in /mnt/ch/ClickHouse/build_head_asserts/programs/clickhouse
2021.08.12 16:30:50.708409 [ 289173 ] {} <Trace> NuKeeperTCPHandler: Received heartbeat for session #51
2021.08.12 16:30:50.947236 [ 289556 ] {} <Fatal> BaseDaemon: 19. /mnt/ch/ClickHouse/src/Server/TCPHandler.cpp:313: DB::TCPHandler::runImpl() @ 0x1f5eb167 in /mnt/ch/ClickHouse/build_head_asserts/programs/clickhouse
2021.08.12 16:30:51.396052 [ 289556 ] {} <Fatal> BaseDaemon: 20. /mnt/ch/ClickHouse/src/Server/TCPHandler.cpp:1650: DB::TCPHandler::run() @ 0x1f5f8e52 in /mnt/ch/ClickHouse/build_head_asserts/programs/clickhouse
2021.08.12 16:30:51.439463 [ 289556 ] {} <Fatal> BaseDaemon: 21. /mnt/ch/ClickHouse/contrib/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x23f9ff99 in /mnt/ch/ClickHouse/build_head_asserts/programs/clickhouse
2021.08.12 16:30:51.505115 [ 289556 ] {} <Fatal> BaseDaemon: 22. /mnt/ch/ClickHouse/contrib/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x23fa0834 in /mnt/ch/ClickHouse/build_head_asserts/programs/clickhouse
2021.08.12 16:30:51.566883 [ 289556 ] {} <Fatal> BaseDaemon: 23. /mnt/ch/ClickHouse/contrib/poco/Foundation/src/ThreadPool.cpp:199: Poco::PooledThread::run() @ 0x24105881 in /mnt/ch/ClickHouse/build_head_asserts/programs/clickhouse
2021.08.12 16:30:51.621171 [ 289556 ] {} <Fatal> BaseDaemon: 24. /mnt/ch/ClickHouse/contrib/poco/Foundation/src/Thread.cpp:56: Poco::(anonymous namespace)::RunnableHolder::run() @ 0x24101eba in /mnt/ch/ClickHouse/build_head_asserts/programs/clickhouse
2021.08.12 16:30:51.674629 [ 289556 ] {} <Fatal> BaseDaemon: 25. /mnt/ch/ClickHouse/contrib/poco/Foundation/src/Thread_POSIX.cpp:345: Poco::ThreadImpl::runnableEntry(void*) @ 0x24100b3a in /mnt/ch/ClickHouse/build_head_asserts/programs/clickhouse
2021.08.12 16:30:51.674981 [ 289556 ] {} <Fatal> BaseDaemon: 26. start_thread @ 0x9259 in /usr/lib/libpthread-2.33.so
2021.08.12 16:30:51.675255 [ 289556 ] {} <Fatal> BaseDaemon: 27. __clone @ 0xfe5e3 in /usr/lib/libc-2.33.so
2021.08.12 16:30:52.491378 [ 289556 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: 86B7BA64FBE12BFAAEB8E058814D980F. There is no information about the reference checksum.
```

Backtrace from the coredump:
```
(gdb) bt
#0  0x00007fe4becb9d22 in raise () from /usr/lib/libc.so.6
#1  0x00007fe4beca3862 in abort () from /usr/lib/libc.so.6
#2  0x00000000128ce859 in DB::handle_error_code (msg=..., code=49, remote=false, trace=...) at /mnt/ch/ClickHouse/src/Common/Exception.cpp:49
#3  0x00000000128ce992 in DB::Exception::Exception (this=0x7fe3c7124f80, msg=..., code=49, remote_=false) at /mnt/ch/ClickHouse/src/Common/Exception.cpp:60
#4  0x000000001f9fa8af in DB::ConstantExpressionTemplate::evaluateAll (this=0x7fe395603dc0, nulls=..., column_idx=0, expected_type=..., offset=0) at /mnt/ch/ClickHouse/src/Processors/Formats/Impl/ConstantExpressionTemplate.cpp:603
#5  0x000000001f9eec2b in DB::ValuesBlockInputFormat::generate (this=0x7fe37c12ee18) at /mnt/ch/ClickHouse/src/Processors/Formats/Impl/ValuesBlockInputFormat.cpp:82
#6  0x000000001f645800 in DB::ISource::tryGenerate (this=0x7fe37c12ee18) at /mnt/ch/ClickHouse/src/Processors/ISource.cpp:79
#7  0x000000001f645531 in DB::ISource::work (this=0x7fe37c12ee18) at /mnt/ch/ClickHouse/src/Processors/ISource.cpp:53
#8  0x000000001b583174 in DB::InputStreamFromInputFormat::readImpl (this=0x7fe3c703f898) at /mnt/ch/ClickHouse/src/Processors/Formats/InputStreamFromInputFormat.h:48
#9  0x000000001d9d6980 in DB::IBlockInputStream::read (this=0x7fe3c703f898) at /mnt/ch/ClickHouse/src/DataStreams/IBlockInputStream.cpp:57
#10 0x000000001f1324c9 in DB::MergeTreeData::getPartitionIDFromQuery (this=0x7fe3c705c600, ast=..., local_context=...) at /mnt/ch/ClickHouse/src/Storages/MergeTree/MergeTreeData.cpp:3264
#11 0x000000001f14363e in DB::MergeTreeData::checkAlterPartitionIsPossible (this=0x7fe3c705c600, commands=..., settings=...) at /mnt/ch/ClickHouse/src/Storages/MergeTree/MergeTreeData.cpp:2942
#12 0x000000001dfd1df3 in DB::InterpreterAlterQuery::execute (this=0x7fe373360140) at /mnt/ch/ClickHouse/src/Interpreters/InterpreterAlterQuery.cpp:118
#13 0x000000001e99fb32 in DB::executeQueryImpl (
    begin=0x7fe3c7110600 "ALTER TABLE restore_01640\n    ATTACH PARTITION tuple(toYYYYMM(toDate([arrayJoin([arrayJoin([arrayJoin([arrayJoin([3, materialize(NULL), arrayJoin([1025, materialize(NULL), materialize(NULL)]), NULL])]"..., 
    end=0x7fe3c71106ea "", context=..., internal=false, stage=DB::QueryProcessingStage::Complete, has_query_tail=false, istr=0x0) at /mnt/ch/ClickHouse/src/Interpreters/executeQuery.cpp:560
#14 0x000000001e99dc1e in DB::executeQuery (query=..., context=..., internal=false, stage=DB::QueryProcessingStage::Complete, may_have_embedded_data=true) at /mnt/ch/ClickHouse/src/Interpreters/executeQuery.cpp:909
#15 0x000000001f5eb167 in DB::TCPHandler::runImpl (this=0x7fe3c7064e00) at /mnt/ch/ClickHouse/src/Server/TCPHandler.cpp:313
#16 0x000000001f5f8e52 in DB::TCPHandler::run (this=0x7fe3c7064e00) at /mnt/ch/ClickHouse/src/Server/TCPHandler.cpp:1650
#17 0x0000000023f9ff99 in Poco::Net::TCPServerConnection::start (this=0x7fe3c7064e00) at /mnt/ch/ClickHouse/contrib/poco/Net/src/TCPServerConnection.cpp:43
#18 0x0000000023fa0834 in Poco::Net::TCPServerDispatcher::run (this=0x7fe37a55c100) at /mnt/ch/ClickHouse/contrib/poco/Net/src/TCPServerDispatcher.cpp:115
#19 0x0000000024105881 in Poco::PooledThread::run (this=0x7fe4bd106280) at /mnt/ch/ClickHouse/contrib/poco/Foundation/src/ThreadPool.cpp:199
#20 0x0000000024101eba in Poco::(anonymous namespace)::RunnableHolder::run (this=0x7fe4bde01700) at /mnt/ch/ClickHouse/contrib/poco/Foundation/src/Thread.cpp:55
#21 0x0000000024100b3a in Poco::ThreadImpl::runnableEntry (pThread=0x7fe4bd1062b8) at /mnt/ch/ClickHouse/contrib/poco/Foundation/src/Thread_POSIX.cpp:345
#22 0x00007fe4bee64259 in start_thread () from /usr/lib/libpthread.so.0
#23 0x00007fe4bed7b5e3 in clone () from /usr/lib/libc.so.6
```

**Comment by alexey-milovidov** [comment]
@Algunenano It is due to `arrayJoin` and it is easy to fix.
Simply add the check that no arrayJoins and subqueries exist, similarly to the check for primary key, partition key in MergeTree.

**Comment by alexey-milovidov** [comment]
@vdimir Labeling it as a bug is incorrect. It is not a bug. The server correctly returns exception to user on user error.
But our own debug check is triggered for debug build, that this type of exception should not happen.
