### ISSUE TITLE
Segmentation fault while responding to an HTTP client?

### ISSUE THREAD

**Issue by depressed-pho** [ClickHouse/ClickHouse#27833]
**Describe the bug**

Our instance of ClickHouse server crashed for attempting an invalid write. We are sorry that we don't know exactly what the server was doing when, nor we know how to reproduce the crash. The only clue we have is a backtrace of the crashed thread.

**Does it reproduce on recent release?**

It happened on 21.5.5.12-stable.

**Error message and/or stacktrace**

```
Program terminated with signal 11, Segmentation fault.
#0  0x000000000b1463cc in std::ostream::sentry::sentry(std::ostream&) ()
(gdb) bt
#0  0x000000000b1463cc in std::ostream::sentry::sentry(std::ostream&) ()
#1  0x000000000b146701 in std::ostream::write(char const*, long) ()
#2  0x0000000009d625c4 in DB::WriteBufferFromOStream::nextImpl() ()
#3  0x00000000090c47c2 in DB::WriteBufferFromHTTPServerResponse::nextImpl() ()
#4  0x00000000090c4a43 in DB::WriteBufferFromHTTPServerResponse::finalize() ()
#5  0x00000000033c15e3 in DB::InterserverIOHTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&)::{lambda(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)#1}::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const ()
#6  0x00000000033c199b in DB::InterserverIOHTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) [clone .cold] ()
#7  0x00000000097d9d6e in DB::HTTPServerConnection::run() ()
#8  0x000000000a1ff607 in Poco::Net::TCPServerConnection::start() ()
#9  0x000000000a1ffcc8 in Poco::Net::TCPServerDispatcher::run() ()
#10 0x000000000a30089f in Poco::PooledThread::run() ()
#11 0x000000000a2fd809 in Poco::ThreadImpl::runnableEntry(void*) ()
#12 0x00007f34407d3ea5 in ?? ()
#13 0x0000000000000000 in ?? ()
```

**Comment by filimonov** [comment]
Non-standard build? Can not map addresses from the stacktrace to the official build of 21.5.5.12-stable...

**Comment by alexey-milovidov** [comment]
There was similar issue in one of minor releases long time ago.
Need to upgrade to version 21.8.
