### ISSUE TITLE
hadoop2.7.2,   ClickHouse write data to hdfs fail.  Failed to read expected SASL data transfer protection handshake 

### ISSUE THREAD

**Issue by jiangjiguang** [ClickHouse/ClickHouse#27897]
> Make sure to check documentation https://clickhouse.yandex/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.
We have hadoop cluster that opens sasl , and the version of hadoop is 2.7.2. But when ClickHouse write data to HDFS failed, the error is (the log is from datanode):
 021-08-19 19:40:54,848 INFO org.apache.hadoop.hdfs.server.datanode.DataNode: Failed to read expected SASL data transfer protection handshake from client at /10.x.xxx.xxx:46864. Perhaps theclient is running an older version of Hadoop which does not support SASL data transfer protection
 2021-08-19 19:40:55,602 ERROR org.apache.hadoop.hdfs.server.datanode.DataNode: BlockSender.sendChunks() exception:
java.io.IOException: 断开的管道
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
        at sun.nio.ch.IOUtil.write(IOUtil.java:65)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
        at org.apache.hadoop.net.SocketOutputStream$Writer.performIO(SocketOutputStream.java:63)
        at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:142)
        at org.apache.hadoop.net.SocketOutputStream.write(SocketOutputStream.java:159)
        at org.apache.hadoop.net.SocketOutputStream.write(SocketOutputStream.java:117)
        at java.io.DataOutputStream.write(DataOutputStream.java:107)
        at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
        at org.apache.hadoop.security.SaslOutputStream.write(SaslOutputStream.java:190)
        at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
        at java.io.DataOutputStream.write(DataOutputStream.java:107)

**Comment by kssenii** [comment]
Hi. It is written in documentation [here](https://clickhouse.tech/docs/en/engines/table-engines/integrations/hdfs/#kerberos-support):
`Note that due to libhdfs3 limitations only old-fashioned approach is supported,
datanode communications are not secured by SASL`.
So SASL is not supported.

**Comment by jiangjiguang** [comment]
is there a planning when can support SASL?

**Comment by kssenii** [comment]
> is there a planning when can support SASL?

No, only if will appear a better c++ hdfs library which supports it.

**Comment by jiangjiguang** [comment]
I got it, thanks
