### ISSUE TITLE
Session expired (Session expired)

### ISSUE THREAD

**Issue by kendn1993** [ClickHouse/ClickHouse#28320]
> A clear and concise description of what works not as it is supposed to.

**How to reproduce**
Executing a query will periodically throw an exception

* Which ClickHouse server version to use
* version 20.5.4.40
 
* Queries to run that lead to unexpected result
SELECT SUM(num) from (select count(1) as num from default.device_param_raw  UNION ALL select count(1) as num from default.live_weather UNION ALL select count(1) as num from default.forecast_hourly_weather UNION ALL select count(1) as num from default.zjk_air_quality_pollution_hourly_data UNION ALL select count(1) as num from default.zjk_fire_device_raw_data UNION ALL select count(1) as num from default.zjk_air_quality_device_raw_data) as a;

**Expected behavior**
 SUM(num)

> A clear and concise description of what you expected to happen.

**Error message and/or stacktrace**
**user server**

ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 999, host: 10.80.43.71, port: 8123; Code: 999, e.displayText() = DB::Exception: Received from p2mysql1:9000. DB::Exception: Session expired (Session expired). (version 20.5.4.40)

	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:58)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:28)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.checkForErrorAndThrow(ClickHouseStatementImpl.java:875)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.getInputStream(ClickHouseStatementImpl.java:616)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:117)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:100)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:95)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:90)
	at com.chinaentropy.sensorcloud.data_intergration.utils.CkHouseConnection.distributeQuery(CkHouseConnection.java:53)
	at com.chinaentropy.sensorcloud.data_intergration.service.impl.SystemFrontPageServiceImpl.cronClean(SystemFrontPageServiceImpl.java:283)
	at sun.reflect.GeneratedMethodAccessor107.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Throwable: Code: 999, e.displayText() = DB::Exception: Received from p2mysql1:9000. DB::Exception: Session expired (Session expired). (version 20.5.4.40)

	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:53)
	... 21 more

**the clickhouse server**

2021.08.30 13:42:38.869538 [ 2507 ] {} <Error> zkutil::EphemeralNodeHolder::~EphemeralNodeHolder(): Code: 999, e.displayText() = Coordination::Exception: Session expired (Session expired), Stack trace (when copyingthis message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xcc3083c in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x5a54619 in /usr/bin/clickhouse
2. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error, int) @ 0xa9d3a64 in /usr/bin/clickhouse
3. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error) @ 0xa9d40fa in /usr/bin/clickhouse
4. ? @ 0x57d9a24 in /usr/bin/clickhouse
5. Coordination::ZooKeeper::remove(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, std::__1::function<void (Coordination::RemoveResponse const&)>) @ 0xa9ec61c in /usr/bin/clickhouse
6. zkutil::ZooKeeper::tryRemove(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xa9da2e7 in /usr/bin/clickhouse
7. std::__1::__shared_ptr_emplace<zkutil::EphemeralNodeHolder, std::__1::allocator<zkutil::EphemeralNodeHolder> >::__on_zero_shared() @ 0x5b41a4a in /usr/bin/clickhouse
8. DB::ReplicatedMergeTreeRestartingThread::partialShutdown() @ 0xa2af09a in /usr/bin/clickhouse
9. DB::ReplicatedMergeTreeRestartingThread::run() @ 0xa2b410e in /usr/bin/clickhouse
10. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0xa562f72 in /usr/bin/clickhouse
11. DB::BackgroundSchedulePool::threadFunction() @ 0xa56339a in /usr/bin/clickhouse
12. ? @ 0xa56349f in /usr/bin/clickhouse
13. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x5a5e12d in /usr/bin/clickhouse
14. ? @ 0x5a5c7af in /usr/bin/clickhouse
15. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
16. clone @ 0xfe96d in /usr/lib64/libc-2.17.so
 (version 20.5.4.40)

> If applicable, add screenshots to help explain your problem.

**Additional context**

> Add any other context about the problem here.

**Comment by filimonov** [comment]
> version 20.5.4.40

That version is not supported. Please update.

> Session expired 

If it happens rare - it is the normal situation (clickhouse lost the connection to zookeeper). A retry should help. 
https://github.com/ClickHouse/ClickHouse/issues/5746#issuecomment-619629404

If it happens with every query - you need to check all zookeeper-related the log messages BEFORE that 'Session expired' message in clickhouse logs, and check zookeeper logs at the same timestamp.

**Comment by kendn1993** [comment]
Thank you for your answer
