### ISSUE TITLE
Merge join:  reference binding to null pointer of type 'DB::ColumnWithTypeAndName'

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#28660]
https://clickhouse-test-reports.s3.yandex.net/0/2178ed21df53fc60bb039acb5ad668378db2a2ca/fuzzer_ubsan/report.html#fail1

```
2021.09.06 14:56:03.814818 [ 50 ] {4726dace-8168-48b6-85b1-4ce890c88790} <Debug> executeQuery: (from [::1]:39686) SELECT count(NULL) = -9223372036854775807 FROM (SELECT [NULL, NULL, NULL, NULL, NULL], [NULL, NULL, NULL, NULL, '102.5', NULL], count('10485.77'), [NULL, NULL, NULL, 10.000100135803223], '92233720368547758.07', [NULL, NULL, NULL]) AS js1 ALL RIGHT JOIN (SELECT number AS s FROM numbers(257, 2)) AS js2 USING (s)
2021.09.06 14:56:03.815385 [ 50 ] {4726dace-8168-48b6-85b1-4ce890c88790} <Trace> ContextAccess (default): Access granted: SELECT(dummy) ON system.one
2021.09.06 14:56:03.815542 [ 50 ] {4726dace-8168-48b6-85b1-4ce890c88790} <Trace> ContextAccess (default): Access granted: CREATE TEMPORARY TABLE ON *.*
2021.09.06 14:56:03.816234 [ 50 ] {4726dace-8168-48b6-85b1-4ce890c88790} <Trace> ContextAccess (default): Access granted: SELECT(dummy) ON system.one
2021.09.06 14:56:03.816793 [ 50 ] {4726dace-8168-48b6-85b1-4ce890c88790} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2021.09.06 14:56:03.817200 [ 50 ] {4726dace-8168-48b6-85b1-4ce890c88790} <Trace> ContextAccess (default): Access granted: SELECT(dummy) ON system.one
2021.09.06 14:56:03.817305 [ 50 ] {4726dace-8168-48b6-85b1-4ce890c88790} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2021.09.06 14:56:03.817340 [ 50 ] {4726dace-8168-48b6-85b1-4ce890c88790} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2021.09.06 14:56:03.817366 [ 50 ] {4726dace-8168-48b6-85b1-4ce890c88790} <Debug> JoiningTransform: Before join block: ''
2021.09.06 14:56:03.817382 [ 50 ] {4726dace-8168-48b6-85b1-4ce890c88790} <Debug> JoiningTransform: After join block: ''
2021.09.06 14:56:03.817607 [ 50 ] {4726dace-8168-48b6-85b1-4ce890c88790} <Debug> JoiningTransform: Before join block: ''
2021.09.06 14:56:03.817630 [ 50 ] {4726dace-8168-48b6-85b1-4ce890c88790} <Debug> JoiningTransform: After join block: ''

../contrib/libcxx/include/vector:1550:12: runtime error: reference binding to null pointer of type 'DB::ColumnWithTypeAndName'

    #0 0x1a703df4 in DB::Block::getByPosition(unsigned long) (/workspace/clickhouse+0x1a703df4)
    #1 0x1e956cf6 in DB::NotJoinedBlocks::NotJoinedBlocks(std::__1::unique_ptr<DB::NotJoinedBlocks::RightColumnsFiller, std::__1::default_delete<DB::NotJoinedBlocks::RightColumnsFiller> >, DB::Block const&, unsigned long, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > const&) obj-x86_64-linux-gnu/../src/Interpreters/join_common.cpp:535:46
    #2 0x1e70b9eb in std::__1::__shared_ptr_emplace<DB::NotJoinedBlocks, std::__1::allocator<DB::NotJoinedBlocks> >::__shared_ptr_emplace<std::__1::unique_ptr<DB::NotJoinedMerge, std::__1::default_delete<DB::NotJoinedMerge> >, DB::Block const&, unsigned long&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > >(std::__1::allocator<DB::NotJoinedBlocks>, std::__1::unique_ptr<DB::NotJoinedMerge, std::__1::default_delete<DB::NotJoinedMerge> >&&, DB::Block const&, unsigned long&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >&&) obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2594:9
    #3 0x1e70b814 in std::__1::shared_ptr<DB::NotJoinedBlocks> std::__1::allocate_shared<DB::NotJoinedBlocks, std::__1::allocator<DB::NotJoinedBlocks>, std::__1::unique_ptr<DB::NotJoinedMerge, std::__1::default_delete<DB::NotJoinedMerge> >, DB::Block const&, unsigned long&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >, void>(std::__1::allocator<DB::NotJoinedBlocks> const&, std::__1::unique_ptr<DB::NotJoinedMerge, std::__1::default_delete<DB::NotJoinedMerge> >&&, DB::Block const&, unsigned long&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >&&) obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:3360:55
    #4 0x1e6f2978 in std::__1::shared_ptr<DB::NotJoinedBlocks> std::__1::make_shared<DB::NotJoinedBlocks, std::__1::unique_ptr<DB::NotJoinedMerge, std::__1::default_delete<DB::NotJoinedMerge> >, DB::Block const&, unsigned long&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >, void>(std::__1::unique_ptr<DB::NotJoinedMerge, std::__1::default_delete<DB::NotJoinedMerge> >&&, DB::Block const&, unsigned long&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >&&) obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:3369:12
    #5 0x1e6f2978 in DB::MergeJoin::getNonJoinedBlocks(DB::Block const&, unsigned long) const obj-x86_64-linux-gnu/../src/Interpreters/MergeJoin.cpp:1098:16
    #6 0x1f8b4b8e in DB::JoiningTransform::work() obj-x86_64-linux-gnu/../src/Processors/Transforms/JoiningTransform.cpp:126:39
    #7 0x1f5e2cf8 in DB::executeJob(DB::IProcessor*) obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:88:20
    #8 0x1f5e2be6 in DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0::operator()() const obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:105:13
    #9 0x1f5e2be6 in decltype(std::__1::forward<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(fp)()) std::__1::__invoke<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&) obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3676:1
    #10 0x1f5e1533 in std::__1::__function::__policy_func<void ()>::operator()() const obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2221:16
    #11 0x1f5e1533 in std::__1::function<void ()>::operator()() const obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2560:12
    #12 0x1f5e1533 in DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:597:17
    #13 0x1f5dfde9 in DB::PipelineExecutor::executeSingleThread(unsigned long, unsigned long) obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:485:5
    #14 0x1f5dfde9 in DB::PipelineExecutor::executeImpl(unsigned long) obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:824:9
    #15 0x1f5df899 in DB::PipelineExecutor::execute(unsigned long) obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:407:9
    #16 0x1f5f39c3 in DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long) obj-x86_64-linux-gnu/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:80:24
    #17 0x1f5f3906 in DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0::operator()() const obj-x86_64-linux-gnu/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:107:13
    #18 0x1f5f3906 in decltype(std::__1::forward<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(fp)()) std::__1::__invoke_constexpr<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&) obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3682:1
    #19 0x1f5f37b1 in decltype(auto) std::__1::__apply_tuple_impl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>) obj-x86_64-linux-gnu/../contrib/libcxx/include/tuple:1415:1
    #20 0x1f5f37b1 in decltype(auto) std::__1::apply<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&) obj-x86_64-linux-gnu/../contrib/libcxx/include/tuple:1424:1
    #21 0x1f5f37b1 in ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()::operator()() obj-x86_64-linux-gnu/../src/Common/ThreadPool.h:182:13
    #22 0x1f5f37b1 in decltype(std::__1::forward<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(fp)()) std::__1::__invoke<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&) obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3676:1
    #23 0x10642e7e in std::__1::function<void ()>::operator()() const obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2560:12
    #24 0x10642e7e in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) obj-x86_64-linux-gnu/../src/Common/ThreadPool.cpp:270:17
    #25 0x10646635 in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()::operator()() const obj-x86_64-linux-gnu/../src/Common/ThreadPool.cpp:136:73
    #26 0x10646635 in decltype(std::__1::forward<void>(fp)(std::__1::forward<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(fp0)...)) std::__1::__invoke<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...) obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3676:1
    #27 0x10646635 in void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>&, std::__1::__tuple_indices<>) obj-x86_64-linux-gnu/../contrib/libcxx/include/thread:280:5
    #28 0x10646635 in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) obj-x86_64-linux-gnu/../contrib/libcxx/include/thread:291:5
    #29 0x7f356ecc4608 in start_thread /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477:8
    #30 0x7f356ebeb292 in clone /build/glibc-eX1tMB/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../contrib/libcxx/include/vector:1550:12 in 
2021.09.06 14:56:05.109415 [ 44 ] {} <Trace> BaseDaemon: Received signal -3
2021.09.06 14:56:05.109595 [ 282 ] {} <Fatal> BaseDaemon: ########################################
2021.09.06 14:56:05.109700 [ 282 ] {} <Fatal> BaseDaemon: (version 21.10.1.8007 (official build), build id: 34020B13AD6896E807BA1EA7A153DC42C638DC25) (from thread 272) (query_id: 4726dace-8168-48b6-85b1-4ce890c88790) Received signal Unknown signal (-3)
2021.09.06 14:56:05.109768 [ 282 ] {} <Fatal> BaseDaemon: Sanitizer trap.
2021.09.06 14:56:05.109851 [ 282 ] {} <Fatal> BaseDaemon: Stack trace: 0x1060ed05 0x1d6fd136 0x105ce896 0x105da0bf 0x1a703df5 0x1e956cf7 0x1e70b9ec 0x1e70b815 0x1e6f2979 0x1f8b4b8f 0x1f5e2cf9 0x1f5e2be7 0x1f5e1534 0x1f5dfdea 0x1f5df89a 0x1f5f39c4 0x1f5f3907 0x1f5f37b2 0x10642e7f 0x10646636 0x7f356ecc4609 0x7f356ebeb293
2021.09.06 14:56:05.127880 [ 282 ] {} <Fatal> BaseDaemon: 0.1. inlined from ./obj-x86_64-linux-gnu/../src/Common/StackTrace.cpp:304: StackTrace::tryCapture()
2021.09.06 14:56:05.127921 [ 282 ] {} <Fatal> BaseDaemon: 0. ../src/Common/StackTrace.cpp:265: StackTrace::StackTrace() @ 0x1060ed05 in /workspace/clickhouse
2021.09.06 14:56:05.192116 [ 282 ] {} <Fatal> BaseDaemon: 1. ./obj-x86_64-linux-gnu/../base/daemon/BaseDaemon.cpp:396: sanitizerDeathCallback() @ 0x1d6fd136 in /workspace/clickhouse
2021.09.06 14:56:06.287402 [ 282 ] {} <Fatal> BaseDaemon: 2. __sanitizer::Die() @ 0x105ce896 in /workspace/clickhouse
2021.09.06 14:56:07.355057 [ 282 ] {} <Fatal> BaseDaemon: 3. ? @ 0x105da0bf in /workspace/clickhouse
2021.09.06 14:56:08.446230 [ 282 ] {} <Fatal> BaseDaemon: 4. ? @ 0x1a703df5 in /workspace/clickhouse
2021.09.06 14:56:08.483781 [ 282 ] {} <Fatal> BaseDaemon: 5. ./obj-x86_64-linux-gnu/../src/Interpreters/join_common.cpp:535: DB::NotJoinedBlocks::NotJoinedBlocks(std::__1::unique_ptr<DB::NotJoinedBlocks::RightColumnsFiller, std::__1::default_delete<DB::NotJoinedBlocks::RightColumnsFiller> >, DB::Block const&, unsigned long, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > const&) @ 0x1e956cf7 in /workspace/clickhouse
2021.09.06 14:56:08.542803 [ 97 ] {} <Trace> SystemLog (system.metric_log): Flushing system log, 8 entries to flush up to offset 667
2021.09.06 14:56:08.559602 [ 97 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 4.64 TiB.
2021.09.06 14:56:08.565451 [ 97 ] {} <Trace> system.metric_log (952770a8-5da4-40f3-9527-70a85da470f3): Renaming temporary part tmp_insert_202109_90_90_0 to 202109_90_90_0.
2021.09.06 14:56:08.566531 [ 97 ] {} <Trace> SystemLog (system.metric_log): Flushed system log up to offset 667
2021.09.06 14:56:08.571766 [ 282 ] {} <Fatal> BaseDaemon: 6. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2598: std::__1::__shared_ptr_emplace<DB::NotJoinedBlocks, std::__1::allocator<DB::NotJoinedBlocks> >::__shared_ptr_emplace<std::__1::unique_ptr<DB::NotJoinedMerge, std::__1::default_delete<DB::NotJoinedMerge> >, DB::Block const&, unsigned long&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > >(std::__1::allocator<DB::NotJoinedBlocks>, std::__1::unique_ptr<DB::NotJoinedMerge, std::__1::default_delete<DB::NotJoinedMerge> >&&, DB::Block const&, unsigned long&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >&&) @ 0x1e70b9ec in /workspace/clickhouse
2021.09.06 14:56:08.653642 [ 282 ] {} <Fatal> BaseDaemon: 7.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/__memory/utilities.h:68: std::__1::__allocation_guard<std::__1::allocator<std::__1::__shared_ptr_emplace<DB::NotJoinedBlocks, std::__1::allocator<DB::NotJoinedBlocks> > > >::__release_ptr()
2021.09.06 14:56:08.653690 [ 282 ] {} <Fatal> BaseDaemon: 7. ../contrib/libcxx/include/memory:3361: std::__1::shared_ptr<DB::NotJoinedBlocks> std::__1::allocate_shared<DB::NotJoinedBlocks, std::__1::allocator<DB::NotJoinedBlocks>, std::__1::unique_ptr<DB::NotJoinedMerge, std::__1::default_delete<DB::NotJoinedMerge> >, DB::Block const&, unsigned long&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >, void>(std::__1::allocator<DB::NotJoinedBlocks> const&, std::__1::unique_ptr<DB::NotJoinedMerge, std::__1::default_delete<DB::NotJoinedMerge> >&&, DB::Block const&, unsigned long&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >&&) @ 0x1e70b815 in /workspace/clickhouse
2021.09.06 14:56:08.726801 [ 282 ] {} <Fatal> BaseDaemon: 8. ./obj-x86_64-linux-gnu/../src/Interpreters/MergeJoin.cpp:0: DB::MergeJoin::getNonJoinedBlocks(DB::Block const&, unsigned long) const @ 0x1e6f2979 in /workspace/clickhouse
2021.09.06 14:56:08.755215 [ 282 ] {} <Fatal> BaseDaemon: 9. ./obj-x86_64-linux-gnu/../src/Processors/Transforms/JoiningTransform.cpp:126: DB::JoiningTransform::work() @ 0x1f8b4b8f in /workspace/clickhouse
2021.09.06 14:56:08.831935 [ 282 ] {} <Fatal> BaseDaemon: 10. ./obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:96: DB::executeJob(DB::IProcessor*) @ 0x1f5e2cf9 in /workspace/clickhouse
2021.09.06 14:56:08.907366 [ 282 ] {} <Fatal> BaseDaemon: 11.1. inlined from ./obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:108: operator()
2021.09.06 14:56:08.907404 [ 282 ] {} <Fatal> BaseDaemon: 11. ../contrib/libcxx/include/type_traits:3676: decltype(std::__1::forward<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(fp)()) std::__1::__invoke<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&) @ 0x1f5e2be7 in /workspace/clickhouse
2021.09.06 14:56:08.979469 [ 282 ] {} <Fatal> BaseDaemon: 12.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:0: std::__1::__function::__policy_func<void ()>::operator()() const
2021.09.06 14:56:08.979520 [ 282 ] {} <Fatal> BaseDaemon: 12.2. inlined from ../contrib/libcxx/include/functional:2560: std::__1::function<void ()>::operator()() const
2021.09.06 14:56:08.979542 [ 282 ] {} <Fatal> BaseDaemon: 12. ../src/Processors/Executors/PipelineExecutor.cpp:597: DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0x1f5e1534 in /workspace/clickhouse
2021.09.06 14:56:09.000124 [ 245 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 2.93 GiB, peak 2.94 GiB, will set to 2.97 GiB (RSS), difference: 37.14 MiB
2021.09.06 14:56:09.046631 [ 282 ] {} <Fatal> BaseDaemon: 13.1. inlined from ./obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:0: DB::PipelineExecutor::executeSingleThread(unsigned long, unsigned long)
2021.09.06 14:56:09.046675 [ 282 ] {} <Fatal> BaseDaemon: 13. ../src/Processors/Executors/PipelineExecutor.cpp:824: DB::PipelineExecutor::executeImpl(unsigned long) @ 0x1f5dfdea in /workspace/clickhouse
2021.09.06 14:56:09.117606 [ 282 ] {} <Fatal> BaseDaemon: 14. ./obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:410: DB::PipelineExecutor::execute(unsigned long) @ 0x1f5df89a in /workspace/clickhouse
2021.09.06 14:56:09.155877 [ 282 ] {} <Fatal> BaseDaemon: 15. ./obj-x86_64-linux-gnu/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:0: DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long) @ 0x1f5f39c4 in /workspace/clickhouse
2021.09.06 14:56:09.193868 [ 282 ] {} <Fatal> BaseDaemon: 16. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3682: decltype(std::__1::forward<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(fp)()) std::__1::__invoke_constexpr<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&) @ 0x1f5f3907 in /workspace/clickhouse
2021.09.06 14:56:09.231592 [ 282 ] {} <Fatal> BaseDaemon: 17.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/tuple:0: operator()
2021.09.06 14:56:09.231639 [ 282 ] {} <Fatal> BaseDaemon: 17. ../contrib/libcxx/include/type_traits:3676: decltype(std::__1::forward<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(fp)()) std::__1::__invoke<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&) @ 0x1f5f37b2 in /workspace/clickhouse
2021.09.06 14:56:09.245904 [ 282 ] {} <Fatal> BaseDaemon: 18.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2533: std::__1::function<void ()>::operator=(std::nullptr_t)
2021.09.06 14:56:09.245933 [ 282 ] {} <Fatal> BaseDaemon: 18. ../src/Common/ThreadPool.cpp:273: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x10642e7f in /workspace/clickhouse
2021.09.06 14:56:09.261592 [ 282 ] {} <Fatal> BaseDaemon: 19. ./obj-x86_64-linux-gnu/../src/Common/ThreadPool.cpp:0: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) @ 0x10646636 in /workspace/clickhouse
2021.09.06 14:56:09.261658 [ 282 ] {} <Fatal> BaseDaemon: 20. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
2021.09.06 14:56:09.261766 [ 282 ] {} <Fatal> BaseDaemon: 21. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.09.06 14:56:09.507425 [ 282 ] {} <Fatal> BaseDaemon: Checksum of the binary: D0CDFD0A8557841B736D34977B3C3698, integrity check passed.
```

**Comment by alexey-milovidov** [comment]
@vdimir Maybe you can take a look?
