### ISSUE TITLE
Reading Native block with malformed LowCardinality column could lead to crashes

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#28856]
Related to https://github.com/mymarilyn/clickhouse-driver/issues/249

```
(gdb) bt
#0  inline_memcpy (dst_=0x7ff515b222f1, src_=<optimized out>, size=18446744073709327088) at ../base/glibc-compatibility/memcpy/memcpy.h:197
#1  memcpy (dst=0x7ff515b222f1, src=<optimized out>, size=<optimized out>) at ../base/glibc-compatibility/memcpy/memcpy.cpp:5
#2  0x000000000fb314a3 in DB::ColumnString::insertData (this=0x7ff4390fac40, pos=0x464e860 <DB::empty_pod_array+16> "", length=18446744073709551615) at ../src/Columns/ColumnString.h:165
#3  DB::ReverseIndex<unsigned long, DB::ColumnString>::insert (this=<optimized out>, this@entry=0x7ff4715aada8, data=...) at ../src/Columns/ReverseIndex.h:508
#4  0x000000000fb3042e in DB::ColumnUnique<DB::ColumnString>::uniqueInsertRangeImpl<char8_t>(DB::IColumn const&, unsigned long, unsigned long, unsigned long, DB::ColumnVector<char8_t>::MutablePtr&&, DB::ReverseIndex<unsigned long, DB::ColumnString>*, unsigned long)::{lambda(StringRef const&, DB::ReverseIndex<unsigned long, DB::ColumnString>&)#1}::operator()(StringRef const&, DB::ReverseIndex<unsigned long, DB::ColumnString>&) const (this=<optimized out>, ref=..., cur_index=...) at ../src/Columns/ColumnUnique.h:540
#5  DB::ColumnUnique<DB::ColumnString>::uniqueInsertRangeImpl<char8_t> (this=<optimized out>, this@entry=0x7ff4715aad80, src=..., start=<optimized out>, length=<optimized out>, 
    num_added_rows=num_added_rows@entry=0, positions_column=..., secondary_index=<optimized out>, max_dictionary_size=<optimized out>) at ../src/Columns/ColumnUnique.h:570
#6  0x000000000fb2ef5b in DB::ColumnUnique<DB::ColumnString>::uniqueInsertRangeFrom(DB::IColumn const&, unsigned long, unsigned long)::{lambda(auto:1)#1}::operator()<char8_t>(char8_t) const (
    this=0x7ff4847f3448, x=0 '\000') at ../src/Columns/ColumnUnique.h:592
#7  DB::ColumnUnique<DB::ColumnString>::uniqueInsertRangeFrom (this=0x7ff4715aad80, src=..., start=<optimized out>, length=<optimized out>) at ../src/Columns/ColumnUnique.h:600
#8  0x00000000103d9341 in DB::ColumnLowCardinality::Dictionary::compact (this=this@entry=0x7ff471568fd0, positions=...) at ../src/Columns/ColumnLowCardinality.cpp:865
#9  0x00000000103d9209 in DB::ColumnLowCardinality::compactInplace (this=this@entry=0x7ff471568fc0) at ../src/Columns/ColumnLowCardinality.cpp:507
#10 0x00000000103d9119 in DB::ColumnLowCardinality::cutAndCompact (this=<optimized out>, start=<optimized out>, length=<optimized out>) at ../src/Columns/ColumnLowCardinality.cpp:499
#11 0x000000000fbafd7c in DB::SerializationLowCardinality::serializeBinaryBulkWithMultipleStreams (this=0x7ff4390fa8d8, column=..., offset=0, limit=<optimized out>, settings=..., state=...)
    at ../src/DataTypes/Serializations/SerializationLowCardinality.cpp:513
#12 0x000000001082f3ed in DB::(anonymous namespace)::writeColumnSingleGranule(DB::ColumnWithTypeAndName const&, std::__1::shared_ptr<DB::ISerialization const> const&, std::__1::function<DB::WriteBuffer* (DB::ISerialization::SubstreamPath const&)>, unsigned long, unsigned long) (column=..., serialization=..., stream_getter=..., from_row=0, number_of_rows=1)
    at ../src/Storages/MergeTree/MergeTreeDataPartWriterCompact.cpp:121
#13 DB::MergeTreeDataPartWriterCompact::writeDataBlock (this=this@entry=0x7ff4390fb000, block=..., granules=...) at ../src/Storages/MergeTree/MergeTreeDataPartWriterCompact.cpp:206
#14 0x000000001082ef1c in DB::MergeTreeDataPartWriterCompact::writeDataBlockPrimaryIndexAndSkipIndices (this=this@entry=0x7ff4390fb000, block=..., granules_to_write=...)
    at ../src/Storages/MergeTree/MergeTreeDataPartWriterCompact.cpp:158
#15 0x000000001082f875 in DB::MergeTreeDataPartWriterCompact::finishDataSerialization (this=this@entry=0x7ff4390fb000, checksums=..., sync=false)
    at ../src/Storages/MergeTree/MergeTreeDataPartWriterCompact.cpp:230
#16 0x0000000010830141 in DB::MergeTreeDataPartWriterCompact::finish (this=0x7ff4390fb000, checksums=..., sync=<optimized out>) at ../src/Storages/MergeTree/MergeTreeDataPartWriterCompact.cpp:360
#17 0x00000000108d00fb in DB::MergedBlockOutputStream::writeSuffixAndFinalizePart (this=0x7ff4847f3f28, new_part=..., sync=false, total_columns_list=0x0, additional_column_checksums=<optimized out>)
    at ../src/Storages/MergeTree/MergedBlockOutputStream.cpp:72
#18 0x00000000108599ba in DB::MergeTreeDataWriter::writeTempPart (this=<optimized out>, block_with_partition=..., metadata_snapshot=..., context=...)
    at ../src/Storages/MergeTree/MergeTreeDataWriter.cpp:442
#19 0x0000000010957e10 in DB::MergeTreeSink::consume (this=0x7ff4715e2418, chunk=...) at ../src/Storages/MergeTree/MergeTreeSink.cpp:27
#20 0x0000000010a28581 in DB::ISink::work (this=0xf) at ../src/Processors/ISink.cpp:47
#21 0x000000000ffc6435 in DB::PushingToSinkBlockOutputStream::write (this=0x7ff4715aa258, block=...) at ../src/DataStreams/PushingToSinkBlockOutputStream.h:40
#22 0x000000000ffcb432 in DB::PushingToViewsBlockOutputStream::write (this=0x7ff4715d7018, block=...) at ../src/DataStreams/PushingToViewsBlockOutputStream.cpp:255
#23 0x000000000ffc836b in DB::AddingDefaultBlockOutputStream::write (this=0x7ff4715a23d8, block=...) at ../src/DataStreams/AddingDefaultBlockOutputStream.cpp:25
#24 0x000000000ffc7aec in DB::SquashingBlockOutputStream::finalize (this=0x7ff4715d7118) at ../src/DataStreams/SquashingBlockOutputStream.cpp:30
#25 0x000000000ffc7b89 in DB::SquashingBlockOutputStream::writeSuffix (this=0x7ff4715d7118) at ../src/DataStreams/SquashingBlockOutputStream.cpp:50
#26 0x00000000109fc8df in DB::TCPHandler::processInsertQuery (this=this@entry=0x7ff4715b0000, connection_settings=...) at ../src/Server/TCPHandler.cpp:603
#27 0x00000000109f7dad in DB::TCPHandler::runImpl (this=0x7ff4715b0000) at ../src/Server/TCPHandler.cpp:345
#28 0x0000000010a03219 in DB::TCPHandler::run (this=0x7ff4715b0000) at ../src/Server/TCPHandler.cpp:1670
#29 0x0000000012b7fb27 in Poco::Net::TCPServerConnection::start (this=0xf) at ../contrib/poco/Net/src/TCPServerConnection.cpp:43
#30 0x0000000012b7ffbc in Poco::Net::TCPServerDispatcher::run (this=0x7ff478325200) at ../contrib/poco/Net/src/TCPServerDispatcher.cpp:115
#31 0x0000000012c66e59 in Poco::PooledThread::run (this=0x7ff515a2d300) at ../contrib/poco/Foundation/src/ThreadPool.cpp:199
#32 0x0000000012c64b66 in Poco::ThreadImpl::runnableEntry (pThread=0x7ff515a2d338) at ../contrib/poco/Foundation/src/Thread_POSIX.cpp:345
#33 0x00007ff516ae6609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#34 0x00007ff5169fc293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

Fixed in https://github.com/ClickHouse/ClickHouse/pull/27827  (21.10)

**Comment by alexey-milovidov** [comment]
Need to backport the change.

**Comment by filimonov** [comment]
Example exception on 21.10:
```
DB::Exception: Index for LowCardinality is out of range. Dictionary size is 1, but found index with value 255. Stack trace:

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x9440eba in /usr/lib/debug/.build-id/ba/25f6646c3be7aa95f452ec85461e96178aa365.debug
1. DB::Exception::Exception<unsigned long&, unsigned long&>(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long&, unsigned long&) @ 0x10601a3a in /usr/lib/debug/.build-id/ba/25f6646c3be7aa95f452ec85461e96178aa365.debug
2. DB::ColumnLowCardinality::insertRangeFromDictionaryEncodedColumn(DB::IColumn const&, DB::IColumn const&) @ 0x1113778c in /usr/lib/debug/.build-id/ba/25f6646c3be7aa95f452ec85461e96178aa365.debug
3. DB::SerializationLowCardinality::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >*) const @ 0x106d6297 in /usr/lib/debug/.build-id/ba/25f6646c3be7aa95f452ec85461e96178aa365.debug
4. DB::NativeBlockInputStream::readData(DB::IDataType const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, DB::ReadBuffer&, unsigned long, double) @ 0x10eb9bda in /usr/lib/debug/.build-id/ba/25f6646c3be7aa95f452ec85461e96178aa365.debug
5. DB::NativeBlockInputStream::readImpl() @ 0x10ebaa82 in /usr/lib/debug/.build-id/ba/25f6646c3be7aa95f452ec85461e96178aa365.debug
6. DB::IBlockInputStream::read() @ 0x105f4de6 in /usr/lib/debug/.build-id/ba/25f6646c3be7aa95f452ec85461e96178aa365.debug
7. DB::TCPHandler::receiveData(bool) @ 0x119555e2 in /usr/lib/debug/.build-id/ba/25f6646c3be7aa95f452ec85461e96178aa365.debug
8. DB::TCPHandler::receivePacket() @ 0x1194aaab in /usr/lib/debug/.build-id/ba/25f6646c3be7aa95f452ec85461e96178aa365.debug
9. DB::TCPHandler::readDataNext() @ 0x1194cc6f in /usr/lib/debug/.build-id/ba/25f6646c3be7aa95f452ec85461e96178aa365.debug
10. DB::TCPHandler::processInsertQuery() @ 0x1194b008 in /usr/lib/debug/.build-id/ba/25f6646c3be7aa95f452ec85461e96178aa365.debug
11. DB::TCPHandler::runImpl() @ 0x1194455f in /usr/lib/debug/.build-id/ba/25f6646c3be7aa95f452ec85461e96178aa365.debug
12. DB::TCPHandler::run() @ 0x11956c19 in /usr/lib/debug/.build-id/ba/25f6646c3be7aa95f452ec85461e96178aa365.debug
13. Poco::Net::TCPServerConnection::start() @ 0x1452086f in /usr/lib/debug/.build-id/ba/25f6646c3be7aa95f452ec85461e96178aa365.debug
14. Poco::Net::TCPServerDispatcher::run() @ 0x145222fa in /usr/lib/debug/.build-id/ba/25f6646c3be7aa95f452ec85461e96178aa365.debug
15. Poco::PooledThread::run() @ 0x14654459 in /usr/lib/debug/.build-id/ba/25f6646c3be7aa95f452ec85461e96178aa365.debug
16. Poco::ThreadImpl::runnableEntry(void*) @ 0x146506ea in /usr/lib/debug/.build-id/ba/25f6646c3be7aa95f452ec85461e96178aa365.debug
17. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
18. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
```

**Comment by vmihailenco** [comment]
@filimonov I guess it is not possible to include a column name in such exceptions? E.g. catch the exception on the upper level where the column name is available and enrich the message with some details...

**Comment by filimonov** [comment]
> @filimonov I guess it is not possible to include a column name in such exceptions? E.g. catch the exception on the upper level where the column name is available and enrich the message with some details...

Should be possible, but not necessary that it will be a clear & simple thing.
Let's forward that question to @KochetovNicolai - he knows that code the best.

**Comment by alexey-milovidov** [comment]
@filimonov We have backported it to 21.7, 21.8 and 21.9.

But unfortunately it has conflict in version 21.3. Looks like it is easy to resolve, but I will appreciate your help: #28860

All other users are strongly adviced to upgrade to version 21.9 to resolve this vulnerability.
