### ISSUE TITLE
Insert queries stopped for max_concurrent_queries don't clear

### ISSUE THREAD

**Issue by genzgd** [ClickHouse/ClickHouse#28999]
ClickHouse version 21.8.3

Since we upgraded from 21.4.4 we've seen insert queries get hung up at least three different times.  The behavior each time was similar -- INSERTs would begin fail with the exception `Too many simultaneous queries. Maximum: 64 (version 21.8.3.44`.  A few additional inserts also failed with zookeeper timeouts, so zookeeper connectivity could also be a factor.

Other "read" queries were also happening at the time, as we usually only have at most a dozen or so simultaneous INSERTs.  So the original error is probably correct.

The issue is the insert processes/queries remain in the queue.  Even after 10+ minutes the first "failed" insert was still in the system.processes table.  It seems like there is some combination of circumstances that is not cleaning up these failed inserts, and eventually all 64 query "slots" are filled with failed inserts, and all subsequent INSERT queries fail with the the "too many simultaneous queries" exception.  The system.processes table contains 64 insert queries.

 I'll try to capture more data next time it happens, but so far we've just restarted ClickHouse (on our production machines) to get our writes working again.

**Comment by genzgd** [comment]
This has happened again.  It seems like there might be a problem with the ReplicatedMergeTreeCleanupThread?

These inserts don't seem like they'll ever complete

```
SELECT
    elapsed,
    substring(query, 1, 50),
    is_cancelled
FROM system.processes

Query id: a9e35b24-d1e5-4aae-a2ac-3ca6c47c2041

┌────────elapsed─┬─substring(query, 1, 50)────────────────────────────┬─is_cancelled─┐
│  1700.92009412 │ INSERT INTO comcast_xcr.atsec_chi (datetime,ms,chi │            0 │
│ 1695.075421002 │ INSERT INTO comcast_rio.access_logs (datetime,host │            0 │
│ 1693.054853003 │ INSERT INTO comcast_xcr.atsec_chi (datetime,ms,chi │            0 │
│ 1692.867860464 │ INSERT INTO comcast_xcr.atsec_chi (datetime,ms,chi │            0 │
│ 1689.509855477 │ INSERT INTO comcast_rio.access_logs (datetime,host │            0 │
│ 1687.308893365 │ INSERT INTO comcast_xcr.atsec_chi (datetime,ms,chi │            0 │
│ 1685.293482039 │ INSERT INTO comcast_xcr.atsec_chi (datetime,ms,chi │            0 │
│ 1683.286413973 │ INSERT INTO comcast_xcr.conn_states FORMAT JSONEac │            0 │
│ 1683.143175072 │ INSERT INTO comcast_xcr.atsec_chi (datetime,ms,chi │            0 │
│ 1675.162376104 │ INSERT INTO comcast_xcr.atsec_chi (datetime,ms,chi │            0 │
│  1674.76064332 │ INSERT INTO comcast_xcr.atsec_chi (datetime,ms,chi │            0 │
│ 1673.035788847 │ INSERT INTO comcast_rio.access_logs (datetime,host │            0 │
│ 1672.800107836 │ INSERT INTO comcast_rio.access_logs (datetime,host │            0 │
│ 1669.227304495 │ INSERT INTO comcast_xcr.atsec_chi (datetime,ms,chi │            0 │
│ 1667.656156677 │ INSERT INTO comcast_xcr.conn_states FORMAT JSONEac │            0 │
│ 1667.504055596 │ INSERT INTO comcast_xcr.atsec_chi (datetime,ms,chi │            0 │
│ 1667.461580476 │ INSERT INTO comcast_xcr.conn_states FORMAT JSONEac │            0 │
│ 1665.266649583 │ INSERT INTO comcast_xcr.atsec_chi (datetime,ms,chi │            0 │
│ 1663.895833665 │ INSERT INTO comcast_xcr.loadstate FORMAT JSONEachR │            0 │
│ 1662.377619232 │ INSERT INTO comcast_rio.access_logs (datetime,host │            0 │
│ 1660.319099661 │ INSERT INTO comcast_xcr.tr_dns (datetime,ms,chi,rh │            0 │
│ 1657.277573496 │ INSERT INTO comcast_xcr.atsec_chi (datetime,ms,chi │            0 │
│ 1656.849454902 │ INSERT INTO comcast_xcr.atsec_chi (datetime,ms,chi │            0 │
│ 1656.261206417 │ INSERT INTO comcast_rio.access_logs (datetime,host │            0 │
│ 1651.771234008 │ INSERT INTO comcast_xcr.conn_states FORMAT JSONEac │            0 │
│  1651.64624751 │ INSERT INTO comcast_xcr.conn_states FORMAT JSONEac │            0 │
│ 1648.255735736 │ INSERT INTO comcast_xcr.loadstate FORMAT JSONEachR │            0 │
│ 1644.668217313 │ INSERT INTO comcast_xcr.tr_dns (datetime,ms,chi,rh │            0 │
│ 1643.063452326 │ INSERT INTO comcast_xcr.atsec_chi (datetime,ms,chi │            0 │
│ 1640.416713967 │ INSERT INTO comcast_cdn.cacheperf FORMAT JSONEachR │            0 │
│ 1640.272679097 │ INSERT INTO comcast_xcr.atsec_chi (datetime,ms,chi │            0 │
│  1639.06568923 │ INSERT INTO comcast_rio.access_logs (datetime,host │            0 │
│  1638.63938877 │ INSERT INTO comcast_xcr.atsec_chi (datetime,ms,chi │            0 │
│ 1631.635578116 │ INSERT INTO comcast_rio.access_logs (datetime,host │            0 │
│ 1631.053307113 │ INSERT INTO comcast_xcr.atsec_chi (datetime,ms,chi │            0 │
│ 1629.828225867 │ INSERT INTO comcast_xcr.conn_states FORMAT JSONEac │            0 │
│ 1628.968584294 │ INSERT INTO comcast_xcr.conn_states FORMAT JSONEac │            0 │
│ 1628.161812517 │ INSERT INTO comcast_xcr.atsec_chi (datetime,ms,chi │            0 │
│ 1625.185312546 │ INSERT INTO comcast_rio.access_logs (datetime,host │            0 │
│ 1625.055884154 │ INSERT INTO comcast_xcr.atsec_chi (datetime,ms,chi │            0 │
│ 1624.759391102 │ INSERT INTO comcast_cdn.cacheperf FORMAT JSONEachR │            0 │
│ 1622.567926796 │ INSERT INTO comcast_rio.access_logs (datetime,host │            0 │
│ 1622.498785237 │ INSERT INTO comcast_xcr.atsec_chi (datetime,ms,chi │            0 │
│ 1621.208688202 │ INSERT INTO comcast_vista.atsec (datetime,ms,chi,s │            0 │
│ 1620.568184454 │ INSERT INTO comcast_xcr.atsec_chi (datetime,ms,chi │            0 │
│ 1619.503430729 │ INSERT INTO comcast_xcr.loadstate FORMAT JSONEachR │            0 │
│ 1617.585695495 │ INSERT INTO varnish.linear_access_logs (datetime,h │            0 │
│  1615.18129411 │ INSERT INTO comcast_rio.access_logs (datetime,host │            0 │
│  1613.99853682 │ INSERT INTO comcast_xcr.conn_states FORMAT JSONEac │            0 │
│ 1613.204636833 │ INSERT INTO comcast_xcr.conn_states FORMAT JSONEac │            0 │
│ 1613.176785723 │ INSERT INTO comcast_xcr.atsec_chi (datetime,ms,chi │            0 │
│ 1610.332861492 │ INSERT INTO comcast_xcr.atsec_chi (datetime,ms,chi │            0 │
│ 1609.057709753 │ INSERT INTO comcast_cdn.cacheperf FORMAT JSONEachR │            0 │
│ 1608.807804907 │ INSERT INTO comcast_rio.access_logs (datetime,host │            0 │
│ 1607.053160427 │ INSERT INTO comcast_xcr.atsec_chi (datetime,ms,chi │            0 │
│ 1606.251604553 │ INSERT INTO comcast_rio.access_logs (datetime,host │            0 │
│ 1605.471347748 │ INSERT INTO comcast_vista.atsec (datetime,ms,chi,s │            0 │
│  944.856826477 │ INSERT INTO comcast_xcr.tr_dns (datetime,ms,chi,rh │            0 │
│  809.186367821 │ INSERT INTO comcast_xcr.ats_manager FORMAT JSONEac │            0 │
│  330.011177772 │ INSERT INTO varnish.linear_access_logs (datetime,h │            0 │
│  313.534999686 │ INSERT INTO comcast_xcr.atsec_chi (datetime,ms,chi │            0 │
│  182.932284858 │ INSERT INTO comcast_vista.atsec (datetime,ms,chi,s │            0 │
│  178.808820584 │ INSERT INTO comcast_xcr.loadstate FORMAT JSONEachR │            0 │
│   41.246202773 │ INSERT INTO comcast_xcr.tr_http (datetime,ms,chi,r │            0 │
│    0.000867975 │ select elapsed, substring(query, 1, 50), is_cancel │            0 │
└────────────────┴────────────────────────────────────────────────────┴──────────────┘
```

some additional errors:

```
2021.09.15 21:27:32.777636 [ 1827374 ] {3f284a27-9f7d-440d-a760-df9afcf8e091} <Error> DynamicQueryHandler: Code: 999, e.displayText() = DB::Exception: Cannot allocate block number in ZooKeeper: Coordination::Exception: Cannot push request to queue within operation timeout (Operation timeout), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8f9b87a in /usr/bin/clickhouse
1. DB::StorageReplicatedMergeTree::allocateBlockNumber(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<zkutil::ZooKeeper> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0x10a80117 in /usr/bin/clickhouse
2. DB::ReplicatedMergeTreeBlockOutputStream::commitPart(std::__1::shared_ptr<zkutil::ZooKeeper>&, std::__1::shared_ptr<DB::IMergeTreeDataPart>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x10e23952 in /usr/bin/clickhouse
3. DB::ReplicatedMergeTreeBlockOutputStream::write(DB::Block const&) @ 0x10e22ddd in /usr/bin/clickhouse
4. DB::PushingToViewsBlockOutputStream::write(DB::Block const&) @ 0x103851d2 in /usr/bin/clickhouse
5. DB::AddingDefaultBlockOutputStream::write(DB::Block const&) @ 0x1038ef2b in /usr/bin/clickhouse
6. DB::SquashingBlockOutputStream::finalize() @ 0x1038f5ac in /usr/bin/clickhouse
7. DB::SquashingBlockOutputStream::writeSuffix() @ 0x1038f649 in /usr/bin/clickhouse
8. DB::copyData(DB::IBlockInputStream&, DB::IBlockOutputStream&, std::__1::atomic<bool>*) @ 0xfdafa5d in /usr/bin/clickhouse
9. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, std::__1::optional<DB::FormatSettings> const&) @ 0x107413a9 in /usr/bin/clickhouse
10. DB::HTTPHandler::processQuery(std::__1::shared_ptr<DB::Context>, DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0x10f68d2d in /usr/bin/clickhouse
11. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x10f6c489 in /usr/bin/clickhouse
12. DB::HTTPServerConnection::run() @ 0x10fee050 in /usr/bin/clickhouse
13. Poco::Net::TCPServerConnection::start() @ 0x13b5bc0f in /usr/bin/clickhouse
14. Poco::Net::TCPServerDispatcher::run() @ 0x13b5d69a in /usr/bin/clickhouse
15. Poco::PooledThread::run() @ 0x13c90519 in /usr/bin/clickhouse
16. Poco::ThreadImpl::runnableEntry(void*) @ 0x13c8c7aa in /usr/bin/clickhouse
17. start_thread @ 0x814a in /usr/lib64/libpthread-2.28.so
18. __clone @ 0xfcf23 in /usr/lib64/libc-2.28.so
 (version 21.8.3.44 (official build))
```

```
2021.09.15 21:31:17.762303 [ 4178756 ] {} <Error> comcast_xcr.ansible_pull (ReplicatedMergeTreeCleanupThread): void DB::ReplicatedMergeTreeCleanupThread::run(): Code: 999, e.displayText() = Coordination::Exception: Cannot push request to queue within operation timeout (Operation timeout), Stac
k trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8f9b87a in /usr/bin/clickhouse
1. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error, int) @ 0x113c9c15 in /usr/bin/clickhouse
2. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error) @ 0x113c9ea2 in /usr/bin/clickhouse
3. Coordination::ZooKeeper::pushRequest(Coordination::ZooKeeper::RequestInfo&&) @ 0x114114cc in /usr/bin/clickhouse
4. Coordination::ZooKeeper::exists(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (Coordination::ExistsResponse const&)>, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x11412834 in /usr/bin/clickhouse
5. zkutil::ZooKeeper::asyncTryExistsNoThrow(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x113d2505 in /usr/bin/clickhouse
6. zkutil::ZooKeeper::existsImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Stat*, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x113d2178 in /usr/bin/clickhouse
7. zkutil::ZooKeeper::existsWatch(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Stat*, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x113d278e in /usr/bin/clickhouse
8. zkutil::ZooKeeper::exists(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Stat*, std::__1::shared_ptr<Poco::Event> const&) @ 0x113ce176 in /usr/bin/clickhouse
9. DB::ReplicatedMergeTreeCleanupThread::clearOldLogs() @ 0x10e2b9ac in /usr/bin/clickhouse
10. DB::ReplicatedMergeTreeCleanupThread::iterate() @ 0x10e2b81e in /usr/bin/clickhouse
11. DB::ReplicatedMergeTreeCleanupThread::run() @ 0x10e2a402 in /usr/bin/clickhouse
12. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0xffef8a0 in /usr/bin/clickhouse
13. DB::BackgroundSchedulePool::threadFunction() @ 0xfff1917 in /usr/bin/clickhouse
14. ? @ 0xfff2694 in /usr/bin/clickhouse
15. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x8fdc4ff in /usr/bin/clickhouse
16. ? @ 0x8fdfde3 in /usr/bin/clickhouse
17. start_thread @ 0x814a in /usr/lib64/libpthread-2.28.so
18. __clone @ 0xfcf23 in /usr/lib64/libc-2.28.so
 (version 21.8.3.44 (official build))
```

**Comment by genzgd** [comment]
The first exception in the log was this:

```
2021.09.15 21:02:37.507558 [ 1890945 ] {} <Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 107, e.displayText() = Net Exception: Socket is not connected, Stack trace (when copying this message, always include the lines below):

0. Poco::Net::SocketImpl::error(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x13b5494e in /usr/bin/clickhouse
1. Poco::Net::SocketImpl::peerAddress() @ 0x13b56b96 in /usr/bin/clickhouse
2. DB::HTTPServerRequest::HTTPServerRequest(std::__1::shared_ptr<DB::Context const>, DB::HTTPServerResponse&, Poco::Net::HTTPServerSession&) @ 0x10feef6b in /usr/bin/clickhouse
3. DB::HTTPServerConnection::run() @ 0x10feddce in /usr/bin/clickhouse
4. Poco::Net::TCPServerConnection::start() @ 0x13b5bc0f in /usr/bin/clickhouse
5. Poco::Net::TCPServerDispatcher::run() @ 0x13b5d69a in /usr/bin/clickhouse
6. Poco::PooledThread::run() @ 0x13c90519 in /usr/bin/clickhouse
7. Poco::ThreadImpl::runnableEntry(void*) @ 0x13c8c7aa in /usr/bin/clickhouse
8. start_thread @ 0x814a in /usr/lib64/libpthread-2.28.so
9. __clone @ 0xfcf23 in /usr/lib64/libc-2.28.so
 (version 21.8.3.44 (official build))
```

After that there are various zookeeper related exceptions:

```
2021.09.15 21:03:00.729935 [ 4179374 ] {} <Error> comcast_xcr.atsec_svc_host_1m: auto DB::StorageReplicatedMergeTree::processQueueEntry(ReplicatedMergeTreeQueue::SelectedEntryPtr)::(anonymous class)::operator()(DB::StorageReplicatedMergeTree::LogEntryPtr &) const: Code: 999, e.displayText() = Coordination::Exception: Operation timeout, path: /clickhouse/tables/07/comcast_xcr.atsec_svc_host_1m_v2/replicas/cdn-maple-as-112/host, Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8f9b87a in /usr/bin/clickhouse
1. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error, int) @ 0x113c9c15 in /usr/bin/clickhouse
2. Coordination::Exception::Exception(Coordination::Error, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x113ca28e in /usr/bin/clickhouse
3. zkutil::ZooKeeper::tryGetWatch(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, Coordination::Stat*, std::__1::function<void (Coordination::WatchResponse const&)>, Coordination::Error*) @ 0x113d352c in /usr/bin/clickhouse
4. zkutil::ZooKeeper::tryGet(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, Coordination::Stat*, std::__1::shared_ptr<Poco::Event> const&, Coordination::Error*) @ 0x113d3209 in /usr/bin/clickhouse
5. zkutil::ZooKeeper::get(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Stat*, std::__1::shared_ptr<Poco::Event> const&) @ 0x113d2fba in /usr/bin/clickhouse
6. DB::StorageReplicatedMergeTree::fetchPart(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, std::__1::shared_ptr<zkutil::ZooKeeper>) @ 0x10a3ec84 in /usr/bin/clickhouse
7. DB::StorageReplicatedMergeTree::executeFetch(DB::ReplicatedMergeTreeLogEntry&) @ 0x10a37949 in /usr/bin/clickhouse
8. DB::StorageReplicatedMergeTree::executeLogEntry(DB::ReplicatedMergeTreeLogEntry&) @ 0x10a176f4 in /usr/bin/clickhouse
9. ? @ 0x10ad699f in /usr/bin/clickhouse
10. DB::ReplicatedMergeTreeQueue::processEntry(std::__1::function<std::__1::shared_ptr<zkutil::ZooKeeper> ()>, std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&, std::__1::function<bool (std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>) @ 0x10e6a3ec in /usr/bin/clickhouse
11. DB::StorageReplicatedMergeTree::processQueueEntry(std::__1::shared_ptr<DB::ReplicatedMergeTreeQueue::SelectedEntry>) @ 0x10a61a9d in /usr/bin/clickhouse
12. ? @ 0x10c20a37 in /usr/bin/clickhouse
13. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x8fdf218 in /usr/bin/clickhouse
14. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...)::'lambda'()::operator()() @ 0x8fe0dbf in /usr/bin/clickhouse
15. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x8fdc4ff in /usr/bin/clickhouse
16. ? @ 0x8fdfde3 in /usr/bin/clickhouse
17. start_thread @ 0x814a in /usr/lib64/libpthread-2.28.so
18. __clone @ 0xfcf23 in /usr/lib64/libc-2.28.so
 (version 21.8.3.44 (official build))
```

The hung processes/queries make the box unusable and we have to restart clickhouse.

**Comment by SaltTan** [comment]
Could you upgrade to 21.8.5.7?

**Comment by genzgd** [comment]
Happy to do that, is there a particular fix in that version you think might help?

**Comment by gyfis** [comment]
We're seeing the same issue on v21.6.9.7-stable.

**Comment by gyfis** [comment]
We updated to v21.8.5.7-lts, but this bug happened again for us.

**Comment by tavplubix** [comment]
Can be related: #28195

Could you please execute
```
$ clickhouse-client --allow_introspection_functions=1 -q "SELECT thread_name, thread_id, arrayStringConcat(arrayMap(x, y -> concat(x, ': ', y), arrayMap(x -> addressToLine(x), trace), arrayMap(x -> demangle(addressToSymbol(x)), trace)), '\n') as trace FROM system.stack_trace format Vertical" | tee stacktraces.txt
```
or (if the query above will not work for some reason)
```
$ sudo gdb -batch -ex 'thread apply all bt' -p $(pidof clickhouse-server) | tee stacktraces.txt
```
next time it will happen again and share the output/content of stacktraces.txt?

**Comment by genzgd** [comment]
We'll try to capture this the next time it happens.  Our network has been more stable the last couple of weeks so we've seen fewer zookeeper disconnects, and accordingly "too many simultaneous queries" has only happened once since my last comment (on a box that was still running 21.8.3)

**Comment by genzgd** [comment]
This happened again tonight after some zookeeper problems.  Trying to execute the clickhouse-client debug query fails with "too many simultaneous queries" while the server is in this state.  Attach the requested gdb output.

[stacktraces.txt](https://github.com/ClickHouse/ClickHouse/files/7263899/stacktraces.txt)

**Comment by genzgd** [comment]
Actually this happened on multiple boxes using the same zookeeper cluster, including a box recently upgraded to 21.8.8.  Also could not execute any additional clickhouse queries, gdb output attached.

[stacktraces21_8_8.txt](https://github.com/ClickHouse/ClickHouse/files/7263927/stacktraces21_8_8.txt)

**Comment by tavplubix** [comment]
Thanks! Yes, it looks like the issue described here: https://github.com/ClickHouse/ClickHouse/pull/27529#issuecomment-905789828

There is one thread owning `push_request_mutex` and waiting on requests queue:
```
Thread 62 (Thread 0x7f9e8f7f8700 (LWP 3483472)):
#0  0x00007f9ed410c6e8 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x0000000013c98478 in Poco::SemaphoreImpl::waitImpl(long) ()
#2  0x000000001142b3b9 in ConcurrentBoundedQueue<Coordination::ZooKeeper::RequestInfo>::tryPush(Coordination::ZooKeeper::RequestInfo const&, unsigned long) ()
#3  0x000000001142b0d5 in Coordination::ZooKeeper::pushRequest(Coordination::ZooKeeper::RequestInfo&&) ()
#4  0x000000001142c593 in Coordination::ZooKeeper::exists(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (Coordination::ExistsResponse const&)>, std::__1::function<void (Coordination::WatchResponse const&)>) ()
#5  0x00000000113ec7e5 in zkutil::ZooKeeper::asyncTryExistsNoThrow(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (Coordination::WatchResponse const&)>) ()
...
```
And many threads are trying to push request:
```
$ grep -Fac "Coordination::ZooKeeper::pushRequest" stacktraces21_8_8.txt
211
```

One thread is trying to finalize ZooKeeper connection, but it cannot lock `push_request_mutex`:
```
Thread 140 (Thread 0x7f9e5457e700 (LWP 3483551)):
#0  0x00007f9ed410f65d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007f9ed4108979 in pthread_mutex_lock () from /lib64/libpthread.so.0
#2  0x00000000158fc611 in std::__1::mutex::lock() ()
#3  0x000000001142af96 in ?? ()
#4  0x00000000114244d6 in Coordination::ZooKeeper::finalize(bool, bool) ()
#5  0x0000000011429908 in Coordination::ZooKeeper::receiveThread() ()
...
```

We will backport #28195
