### ISSUE TITLE
../base/common/../common/wide_integer_impl.h:279:42: runtime error: 1.84467e+19 is outside the range of representable values of type 'unsigned long'

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#29039]
https://clickhouse-test-reports.s3.yandex.net/28817/4993c7c527e82540694c1c1771b528cf17903f0a/fuzzer_ubsan/report.html#fail1
```
../base/common/../common/wide_integer_impl.h:279:42: runtime error: 1.84467e+19 is outside the range of representable values of type 'unsigned long'
    #0 0x10f55a67 in void wide::integer<256ul, unsigned int>::_impl::set_multiplier<double>(wide::integer<256ul, unsigned int>&, double) (/workspace/clickhouse+0x10f55a67)
    #1 0x10f55842 in void wide::integer<256ul, unsigned int>::_impl::set_multiplier<double>(wide::integer<256ul, unsigned int>&, double) (/workspace/clickhouse+0x10f55842)
    #2 0x10f55555 in void wide::integer<256ul, unsigned int>::_impl::set_multiplier<long double>(wide::integer<256ul, unsigned int>&, long double) (/workspace/clickhouse+0x10f55555)
    #3 0x10f55446 in wide::integer<256ul, unsigned int>::_impl::wide_integer_from_builtin(wide::integer<256ul, unsigned int>&, double) (/workspace/clickhouse+0x10f55446)
    #4 0x10f600ad in COW<DB::IColumn>::immutable_ptr<DB::IColumn> DB::ConvertImpl<DB::DataTypeNumber<double>, DB::DataTypeNumber<wide::integer<256ul, unsigned int> >, DB::NameToUInt256, DB::ConvertDefaultBehaviorTag>::execute<void*>(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, void*) (/workspace/clickhouse+0x10f600ad)
    #5 0x10f5bcfb in bool DB::FunctionConvert<DB::DataTypeNumber<wide::integer<256ul, unsigned int> >, DB::NameToUInt256, DB::ToNumberMonotonicity<wide::integer<256ul, unsigned int> > >::executeInternal(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const::'lambda'(auto const&, auto const&)::operator()<DB::TypePair<DB::DataTypeNumber<double>, DB::DataTypeNumber<wide::integer<256ul, unsigned int> > >, DB::ConvertDefaultBehaviorTag>(auto const&, auto const&) const (/workspace/clickhouse+0x10f5bcfb)
    #6 0x10f4f966 in bool DB::callOnIndexAndDataType<DB::DataTypeNumber<wide::integer<256ul, unsigned int> >, DB::FunctionConvert<DB::DataTypeNumber<wide::integer<256ul, unsigned int> >, DB::NameToUInt256, DB::ToNumberMonotonicity<wide::integer<256ul, unsigned int> > >::executeInternal(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const::'lambda'(auto const&, auto const&)&, DB::ConvertDefaultBehaviorTag>(DB::TypeIndex, auto&&, DB::ConvertDefaultBehaviorTag&&) (/workspace/clickhouse+0x10f4f966)
    #7 0x10f4f20b in DB::FunctionConvert<DB::DataTypeNumber<wide::integer<256ul, unsigned int> >, DB::NameToUInt256, DB::ToNumberMonotonicity<wide::integer<256ul, unsigned int> > >::executeInternal(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/workspace/clickhouse+0x10f4f20b)
    #8 0x10f4df62 in DB::FunctionConvert<DB::DataTypeNumber<wide::integer<256ul, unsigned int> >, DB::NameToUInt256, DB::ToNumberMonotonicity<wide::integer<256ul, unsigned int> > >::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/workspace/clickhouse+0x10f4df62)
    #9 0x10cfb76f in DB::FunctionToExecutableFunctionAdaptor::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/workspace/clickhouse+0x10cfb76f)
    #10 0x1a4eea74 in DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const obj-x86_64-linux-gnu/../src/Functions/IFunction.cpp:217:15
    #11 0x1a4ef7eb in DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const obj-x86_64-linux-gnu/../src/Functions/IFunction.cpp:260:22
    #12 0x1ac4340d in DB::executeAction(DB::ExpressionActions::Action const&, DB::(anonymous namespace)::ExecutionContext&, bool) obj-x86_64-linux-gnu/../src/Interpreters/ExpressionActions.cpp:601:60
    #13 0x1ac414c1 in DB::ExpressionActions::execute(DB::Block&, unsigned long&, bool) const obj-x86_64-linux-gnu/../src/Interpreters/ExpressionActions.cpp:718:13
    #14 0x1c45d7e5 in DB::ExpressionTransform::transform(DB::Chunk&) obj-x86_64-linux-gnu/../src/Processors/Transforms/ExpressionTransform.cpp:23:17
    #15 0x170688ca in DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) obj-x86_64-linux-gnu/../src/Processors/ISimpleTransform.h:42:9
    #16 0x1c1636ac in DB::ISimpleTransform::work() obj-x86_64-linux-gnu/../src/Processors/ISimpleTransform.cpp:89:9
    #17 0x1c1b18f8 in DB::executeJob(DB::IProcessor*) obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:88:20
    #18 0x1c1b17e6 in DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0::operator()() const obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:105:13
    #19 0x1c1b17e6 in decltype(std::__1::forward<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(fp)()) std::__1::__invoke<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&) obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3676:1
    #20 0x1c1afd87 in std::__1::__function::__policy_func<void ()>::operator()() const obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2221:16
    #21 0x1c1afd87 in std::__1::function<void ()>::operator()() const obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2560:12
    #22 0x1c1afd87 in DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:597:17
    #23 0x1c1ae747 in DB::PipelineExecutor::executeSingleThread(unsigned long, unsigned long) obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:485:5
    #24 0x1c1ae747 in DB::PipelineExecutor::executeImpl(unsigned long) obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:824:9
    #25 0x1c1ae13c in DB::PipelineExecutor::execute(unsigned long) obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:407:9
    #26 0x1c1be966 in DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long) obj-x86_64-linux-gnu/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:80:24
    #27 0x1c1be8d3 in DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0::operator()() const obj-x86_64-linux-gnu/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:107:13
    #28 0x1c1be8d3 in decltype(std::__1::forward<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(fp)()) std::__1::__invoke_constexpr<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&) obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3682:1
    #29 0x1c1be75a in decltype(auto) std::__1::__apply_tuple_impl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>) obj-x86_64-linux-gnu/../contrib/libcxx/include/tuple:1415:1
    #30 0x1c1be75a in decltype(auto) std::__1::apply<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&) obj-x86_64-linux-gnu/../contrib/libcxx/include/tuple:1424:1
    #31 0x1c1be75a in ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()::operator()() obj-x86_64-linux-gnu/../src/Common/ThreadPool.h:188:13
    #32 0x1c1be75a in decltype(std::__1::forward<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(fp)()) std::__1::__invoke<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&) obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3676:1
    #33 0xc6b0559 in std::__1::__function::__policy_func<void ()>::operator()() const obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2221:16
    #34 0xc6b0559 in std::__1::function<void ()>::operator()() const obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2560:12
    #35 0xc6b0559 in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) obj-x86_64-linux-gnu/../src/Common/ThreadPool.cpp:273:17
    #36 0xc6b2f61 in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()::operator()() const obj-x86_64-linux-gnu/../src/Common/ThreadPool.cpp:138:73
    #37 0xc6b2f61 in decltype(std::__1::forward<void>(fp)()) std::__1::__invoke<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&) obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3676:1
    #38 0xc6b2f61 in void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>&, std::__1::__tuple_indices<>) obj-x86_64-linux-gnu/../contrib/libcxx/include/thread:280:5
    #39 0xc6b2f61 in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) obj-x86_64-linux-gnu/../contrib/libcxx/include/thread:291:5
    #40 0x7fdd2014c608 in start_thread /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477:8
    #41 0x7fdd20073292 in __clone /build/glibc-eX1tMB/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../base/common/../common/wide_integer_impl.h:279:42 in 
```

**Comment by alexey-milovidov** [comment]
You forgot to attach the info about the query.

**Comment by Avogar** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/41044/63e992d52d3e71fc8e3491a995732e68c9be204f/fuzzer_astfuzzerubsan//report.html

Query:
```
select toInt128(1.157920892373162e77)
```

**Comment by tavplubix** [comment]
Great, now we have the query, but nothing stops as from waiting one more year and closing this issue again with no resolution and a comment like "the report is too old and have not been reproduced for a long time, probably it was fixed somewhere"
