### ISSUE TITLE
Segfault in StorageEmbeddedRocksDB

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#29227]
https://clickhouse-test-reports.s3.yandex.net/29044/5be9ad2b09c7d10ba80da573b971794aac7837b7/stress_test_(address).html#fail1

```
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.17 20:15:11.395839 [ 22744 ] {} <Fatal> BaseDaemon: ########################################
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.17 20:15:11.587120 [ 22744 ] {} <Fatal> BaseDaemon: (version 21.11.1.8105, build id: 3CD890B84455123690A5C1FA040744E6D5606EF9) (from thread 3639) (query_id: 187001bc-4862-43ca-9fe5-bd6d48975562) Received signal Segmentation fault (11)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.17 20:15:11.593330 [ 22744 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Address not mapped to object.
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.17 20:15:11.596015 [ 22744 ] {} <Fatal> BaseDaemon: Stack trace: 0x31539d06 0x315870e9 0x219b3422 0x219a71b5 0x214fdd4d 0x245cf08a 0x23428006 0x23419cc0 0x23418aa2 0x23a7b79e 0x23a7dac4 0x23ff3910 0x23fee7a0 0x2582f984 0x25855da0 0x2cd25d2f 0x2cd26a21 0x2d01cfe6 0x2d0164fa 0x7fea4aed3609 0x7fea4adfa293
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.17 20:15:17.791030 [ 22771 ] {} <Fatal> BaseDaemon: ########################################
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.17 20:15:17.791811 [ 22771 ] {} <Fatal> BaseDaemon: (version 21.11.1.8105, build id: 3CD890B84455123690A5C1FA040744E6D5606EF9) (from thread 1184) (query_id: 0df5bbc8-1c02-4150-ae3f-831eb83967d0) Received signal Aborted (6)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.17 20:15:17.796426 [ 22771 ] {} <Fatal> BaseDaemon: 
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.17 20:15:17.799269 [ 22771 ] {} <Fatal> BaseDaemon: Stack trace: 0x7fea4ad1e18b 0x7fea4acfd859 0x31fc61aa 0x31509f0e 0x3150ac0e 0x219adde0 0x219b008d 0x22c54af6 0x22c516db 0x22c509c8 0x23ff3910 0x23fee7a0 0x2582f984 0x25855da0 0x2cd25d2f 0x2cd26a21 0x2d01cfe6 0x2d0164fa 0x7fea4aed3609 0x7fea4adfa293
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.17 20:15:17.839371 [ 22771 ] {} <Fatal> BaseDaemon: 3. gsignal @ 0x4618b in /usr/lib/x86_64-linux-gnu/libc-2.31.so
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.17 20:15:17.887459 [ 22771 ] {} <Fatal> BaseDaemon: 4. abort @ 0x25859 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.17 20:15:18.358134 [ 22771 ] {} <Fatal> BaseDaemon: 5.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/string:1444: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__is_long() const
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.17 20:15:18.360867 [ 22771 ] {} <Fatal> BaseDaemon: 5.2. inlined from ../contrib/libcxx/include/string:1538: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__get_pointer() const
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.17 20:15:18.362911 [ 22771 ] {} <Fatal> BaseDaemon: 5.3. inlined from ../contrib/libcxx/include/string:1264: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::data() const
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.17 20:15:18.363727 [ 22771 ] {} <Fatal> BaseDaemon: 5.4. inlined from ../contrib/libcxx/include/string:1262: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::c_str() const
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.17 20:15:18.366246 [ 22771 ] {} <Fatal> BaseDaemon: 5.5. inlined from ../contrib/rocksdb/port/port_posix.cc:51: rocksdb::port::PthreadCall(char const*, int)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.17 20:15:18.367026 [ 22771 ] {} <Fatal> BaseDaemon: 5. ../contrib/rocksdb/port/port_posix.cc:77: rocksdb::port::Mutex::~Mutex() @ 0x31fc61aa in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.17 20:15:20.655199 [ 22771 ] {} <Fatal> BaseDaemon: 6. ./obj-x86_64-linux-gnu/../contrib/rocksdb/db/db_impl/db_impl.cc:721: rocksdb::DBImpl::~DBImpl() @ 0x31509f0e in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.17 20:15:22.584279 [ 22744 ] {} <Fatal> BaseDaemon: 3. ./obj-x86_64-linux-gnu/../contrib/rocksdb/db/db_impl/db_impl.cc:3242: rocksdb::DBImpl::GetOptions(rocksdb::ColumnFamilyHandle*) const @ 0x31539d06 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.17 20:15:24.257962 [ 22771 ] {} <Fatal> BaseDaemon: 7. ./obj-x86_64-linux-gnu/../contrib/rocksdb/db/db_impl/db_impl.cc:716: rocksdb::DBImpl::~DBImpl() @ 0x3150ac0e in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.17 20:15:25.652398 [ 22744 ] {} <Fatal> BaseDaemon: 4. ./obj-x86_64-linux-gnu/../contrib/rocksdb/include/rocksdb/db.h:1259: rocksdb::DB::GetOptions() const @ 0x315870e9 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.17 20:15:26.439372 [ 22771 ] {} <Fatal> BaseDaemon: 8. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:0: DB::StorageEmbeddedRocksDB::initDb() @ 0x219adde0 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.17 20:15:26.579350 [ 22744 ] {} <Fatal> BaseDaemon: 5. ./obj-x86_64-linux-gnu/../src/Storages/RocksDB/StorageEmbeddedRocksDB.cpp:463: DB::StorageEmbeddedRocksDB::getRocksDBStatistics() const @ 0x219b3422 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.17 20:15:27.284973 [ 22771 ] {} <Fatal> BaseDaemon: 9. ./obj-x86_64-linux-gnu/../src/Storages/RocksDB/StorageEmbeddedRocksDB.cpp:0: DB::StorageEmbeddedRocksDB::truncate(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>, DB::TableExclusiveLockHolder&) @ 0x219b008d in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.17 20:15:28.119433 [ 22744 ] {} <Fatal> BaseDaemon: 6. ./obj-x86_64-linux-gnu/../src/Storages/RocksDB/StorageSystemRocksDB.cpp:0: DB::StorageSystemRocksDB::fillData(std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, std::__1::shared_ptr<DB::Context const>, DB::SelectQueryInfo const&) const @ 0x219a71b5 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.17 20:15:28.536641 [ 22771 ] {} <Fatal> BaseDaemon: 10. ./obj-x86_64-linux-gnu/../src/Interpreters/InterpreterDropQuery.cpp:207: DB::InterpreterDropQuery::executeToTableImpl(DB::ASTDropQuery&, std::__1::shared_ptr<DB::IDatabase>&, StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>&) @ 0x22c54af6 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.17 20:15:28.841604 [ 22771 ] {} <Fatal> BaseDaemon: 11. ./obj-x86_64-linux-gnu/../src/Interpreters/InterpreterDropQuery.cpp:86: DB::InterpreterDropQuery::executeToTable(DB::ASTDropQuery&) @ 0x22c516db in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.17 20:15:28.946739 [ 22771 ] {} <Fatal> BaseDaemon: 12. ./obj-x86_64-linux-gnu/../src/Interpreters/InterpreterDropQuery.cpp:0: DB::InterpreterDropQuery::execute() @ 0x22c509c8 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.17 20:15:29.687136 [ 22744 ] {} <Fatal> BaseDaemon: 7.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/vector:658: std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >::size() const
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.17 20:15:29.691227 [ 22744 ] {} <Fatal> BaseDaemon: 7.2. inlined from ../contrib/libcxx/include/vector:1566: std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >::at(unsigned long)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.17 20:15:29.693257 [ 22744 ] {} <Fatal> BaseDaemon: 7. ../src/Storages/System/IStorageSystemOneBlock.h:63: DB::IStorageSystemOneBlock<DB::StorageSystemRocksDB>::read(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) @ 0x214fdd4d in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.09.17 20:15:33.125039 [ 517 ] {} <Fatal> Application: Child process was terminated by signal 11.
```

**Comment by zhanglistar** [comment]
Easily repeatable?

**Comment by tavplubix** [comment]
No, I don't know how to reproduce it

**Comment by filimonov** [comment]
> Easily repeatable?

That happened during TRUNCATE command for RocksDB table from that line,
https://github.com/ClickHouse/ClickHouse/blob/512786346c5d615e512b8cea1c237699d1fe7153/tests/queries/0_stateless/01504_rocksdb.sql#L46

And simultaneously some other query on RocksDB table (probably the other one) was executed.

```
Thread 670 (Thread 0x7fe7b7b2e700 (LWP 3639)):
#0  0x0000000031539d06 in rocksdb::DBImpl::GetOptions (this=<optimized out>, column_family=<optimized out>) at ../contrib/rocksdb/db/db_impl/db_impl.cc:3242
#1  0x00000000315870e9 in rocksdb::DB::GetOptions (this=0x6220001c5100) at ../contrib/rocksdb/include/rocksdb/db.h:1259
#2  0x00000000219b3422 in DB::StorageEmbeddedRocksDB::getRocksDBStatistics (this=<optimized out>) at ../src/Storages/RocksDB/StorageEmbeddedRocksDB.cpp:463
#3  0x00000000219a71b5 in DB::StorageSystemRocksDB::fillData (this=<optimized out>, res_columns=..., context=..., query_info=...) at ../src/Storages/RocksDB/StorageSystemRocksDB.cpp:105
#4  0x00000000214fdd4d in DB::IStorageSystemOneBlock<DB::StorageSystemRocksDB>::read (this=<optimized out>, column_names=..., metadata_snapshot=..., query_info=..., context=...) at ../src/Storages/System/IStorageSystemOneBlock.h:61
#5  0x00000000245cf08a in DB::IStorage::read (this=<optimized out>, query_plan=..., column_names=..., metadata_snapshot=..., query_info=..., context=..., processed_stage=<optimized out>, max_block_size=<optimized out>, num_streams=<optimized out>) at ../src/Storages/IStorage.cpp:108
#6  0x0000000023428006 in DB::InterpreterSelectQuery::executeFetchColumns (this=0x61c005ccb080, processing_stage=<optimized out>, query_plan=...) at ../src/Interpreters/InterpreterSelectQuery.cpp:1984
#7  0x0000000023419cc0 in DB::InterpreterSelectQuery::executeImpl (this=0x61c005ccb080, query_plan=..., prepared_input=..., prepared_pipe=...) at ../src/Interpreters/InterpreterSelectQuery.cpp:1037
#8  0x0000000023418aa2 in DB::InterpreterSelectQuery::buildQueryPlan (this=0x61c005ccb080, query_plan=...) at ../src/Interpreters/InterpreterSelectQuery.cpp:580
#9  0x0000000023a7b79e in DB::InterpreterSelectWithUnionQuery::buildQueryPlan (this=0x6110011857c0, query_plan=...) at ../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:254
#10 0x0000000023a7dac4 in DB::InterpreterSelectWithUnionQuery::execute (this=<optimized out>) at ../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:321
#11 0x0000000023ff3910 in DB::executeQueryImpl (begin=<optimized out>, end=<optimized out>, context=..., internal=false, stage=<optimized out>, istr=<optimized out>) at ../src/Interpreters/executeQuery.cpp:633
#12 0x0000000023fee7a0 in DB::executeQuery (query=..., context=..., internal=<optimized out>, stage=<optimized out>) at ../src/Interpreters/executeQuery.cpp:993
#13 0x000000002582f984 in DB::TCPHandler::runImpl (this=0x61a001992680) at ../src/Server/TCPHandler.cpp:290
#14 0x0000000025855da0 in DB::TCPHandler::run (this=0x61a001992680) at ../src/Server/TCPHandler.cpp:1661
#15 0x000000002cd25d2f in Poco::Net::TCPServerConnection::start (this=0x0) at ../contrib/poco/Net/src/TCPServerConnection.cpp:43
#16 0x000000002cd26a21 in Poco::Net::TCPServerDispatcher::run (this=<optimized out>) at ../contrib/poco/Net/src/TCPServerDispatcher.cpp:115
#17 0x000000002d01cfe6 in Poco::PooledThread::run (this=<optimized out>) at ../contrib/poco/Foundation/src/ThreadPool.cpp:199
#18 0x000000002d0164fa in Poco::ThreadImpl::runnableEntry (pThread=0x61600027c0b8) at ../contrib/poco/Foundation/src/Thread_POSIX.cpp:345
#19 0x00007fea4aed3609 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#20 0x00007fea4adfa293 in clone () from /lib/x86_64-linux-gnu/libc.so.6



Thread 252 (Thread 0x7fe8eb403700 (LWP 1184)):
#0  0x0000000031b1ab98 in rocksdb::HistogramStat::HistogramStat (this=0x7fe74dec8fb0) at ../contrib/rocksdb/monitoring/histogram.cc:65
#1  0x0000000031b320f6 in rocksdb::HistogramImpl::HistogramImpl (this=<optimized out>) at ../contrib/rocksdb/monitoring/histogram.h:120
#2  rocksdb::StatisticsImpl::StatisticsData::StatisticsData (this=0x7fe74dec3b00) at ../contrib/rocksdb/monitoring/statistics.h:83
#3  rocksdb::CoreLocalArray<rocksdb::StatisticsImpl::StatisticsData>::CoreLocalArray (this=this@entry=0x60b002769930) at ../contrib/rocksdb/util/core_local.h:51
#4  0x0000000031b32cdd in rocksdb::StatisticsImpl::StatisticsImpl (this=0x60b0027698e8, stats=...) at ../contrib/rocksdb/monitoring/statistics.cc:271
#5  std::__1::allocator<rocksdb::StatisticsImpl>::construct<rocksdb::StatisticsImpl, decltype(nullptr)>(rocksdb::StatisticsImpl*, decltype(nullptr)&&) (__p=0x60b0027698e8, this=<optimized out>, __args=<optimized out>) at ../contrib/libcxx/include/memory:886
#6  std::__1::allocator_traits<std::__1::allocator<rocksdb::StatisticsImpl> >::__construct<rocksdb::StatisticsImpl, decltype(nullptr)>(std::__1::integral_constant<bool, true>, std::__1::allocator<rocksdb::StatisticsImpl>&, rocksdb::StatisticsImpl*, decltype(nullptr)&&) (__p=0x60b0027698e8, __a=..., __args=<optimized out>) at ../contrib/libcxx/include/__memory/allocator_traits.h:519
#7  std::__1::allocator_traits<std::__1::allocator<rocksdb::StatisticsImpl> >::construct<rocksdb::StatisticsImpl, decltype(nullptr)>(std::__1::allocator<rocksdb::StatisticsImpl>&, rocksdb::StatisticsImpl*, decltype(nullptr)&&) (__p=0x60b0027698e8, __a=..., __args=<optimized out>) at ../contrib/libcxx/include/__memory/allocator_traits.h:481
#8  std::__1::__shared_ptr_emplace<rocksdb::StatisticsImpl, std::__1::allocator<rocksdb::StatisticsImpl> >::__shared_ptr_emplace<decltype(nullptr)>(std::__1::allocator<rocksdb::StatisticsImpl>, decltype(nullptr)&&) (this=0x60b0027698d0, __a=..., __args=<optimized out>) at ../contrib/libcxx/include/memory:2594
#9  std::__1::allocate_shared<rocksdb::StatisticsImpl, std::__1::allocator<rocksdb::StatisticsImpl>, decltype(nullptr), void>(std::__1::allocator<rocksdb::StatisticsImpl> const&, decltype(nullptr)&&) (__a=..., __args=<optimized out>) at ../contrib/libcxx/include/memory:3360
#10 0x0000000031b2ed44 in std::__1::make_shared<rocksdb::StatisticsImpl, decltype(nullptr), void>(decltype(nullptr)&&) (__args=<optimized out>) at ../contrib/libcxx/include/memory:3369
#11 rocksdb::CreateDBStatistics () at ../contrib/rocksdb/monitoring/statistics.cc:268
#12 0x00000000219ab460 in DB::StorageEmbeddedRocksDB::initDb (this=<optimized out>) at ../src/Storages/RocksDB/StorageEmbeddedRocksDB.cpp:302
#13 0x00000000219b008d in DB::StorageEmbeddedRocksDB::truncate (this=0x612000e866c0) at ../src/Storages/RocksDB/StorageEmbeddedRocksDB.cpp:291
#14 0x0000000022c54af6 in DB::InterpreterDropQuery::executeToTableImpl (this=<optimized out>, query=..., db=..., uuid_to_wait=...) at ../src/Interpreters/InterpreterDropQuery.cpp:207
#15 0x0000000022c516db in DB::InterpreterDropQuery::executeToTable (this=0x7fe8eb3f5000, query=...) at ../src/Interpreters/InterpreterDropQuery.cpp:85
#16 0x0000000022c509c8 in DB::InterpreterDropQuery::execute (this=0x604001d6ac50) at ../src/Interpreters/InterpreterDropQuery.cpp:62
#17 0x0000000023ff3910 in DB::executeQueryImpl (begin=<optimized out>, end=<optimized out>, context=..., internal=false, stage=<optimized out>, istr=<optimized out>) at ../src/Interpreters/executeQuery.cpp:633
#18 0x0000000023fee7a0 in DB::executeQuery (query=..., context=..., internal=<optimized out>, stage=<optimized out>) at ../src/Interpreters/executeQuery.cpp:993
#19 0x000000002582f984 in DB::TCPHandler::runImpl (this=0x61a000022e80) at ../src/Server/TCPHandler.cpp:290
#20 0x0000000025855da0 in DB::TCPHandler::run (this=0x61a000022e80) at ../src/Server/TCPHandler.cpp:1661
#21 0x000000002cd25d2f in Poco::Net::TCPServerConnection::start (this=0x7fe74dec9340) at ../contrib/poco/Net/src/TCPServerConnection.cpp:43
#22 0x000000002cd26a21 in Poco::Net::TCPServerDispatcher::run (this=<optimized out>) at ../contrib/poco/Net/src/TCPServerDispatcher.cpp:115
#23 0x000000002d01cfe6 in Poco::PooledThread::run (this=<optimized out>) at ../contrib/poco/Foundation/src/ThreadPool.cpp:199
#24 0x000000002d0164fa in Poco::ThreadImpl::runnableEntry (pThread=0x616000271eb8) at ../contrib/poco/Foundation/src/Thread_POSIX.cpp:345
#25 0x00007fea4aed3609 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#26 0x00007fea4adfa293 in clone () from /lib/x86_64-linux-gnu/libc.so.6
```
