### ISSUE TITLE
MergeTreeDataMergerMutator::selectAllPartsToMergeWithinPartition

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#29809]
```
../src/Storages/MergeTree/MergeTreeDataMergerMutator.cpp:393:26: runtime error: 1.84467e+19 is outside the range of representable values of type 'unsigned long'
    #0 0x1c257b20 in DB::MergeTreeDataMergerMutator::selectAllPartsToMergeWithinPartition(std::__1::shared_ptr<DB::FutureMergedMutatedPart>, unsigned long&, std::__1::function<bool (std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*)> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, bool) obj-x86_64-linux-gnu/../src/Storages/MergeTree/MergeTreeDataMergerMutator.cpp:393:26
    #1 0x1c473d10 in DB::StorageMergeTree::selectPartsToMerge(std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>&, std::__1::unique_lock<std::__1::mutex>&, bool, DB::SelectPartsDecision*) obj-x86_64-linux-gnu/../src/Storages/StorageMergeTree.cpp:746:46
    #2 0x1c475119 in DB::StorageMergeTree::merge(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, bool, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, bool) obj-x86_64-linux-gnu/../src/Storages/StorageMergeTree.cpp:820:30
    #3 0x1c47a82a in DB::StorageMergeTree::optimize(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::IAST> const&, bool, bool, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::Context const>) obj-x86_64-linux-gnu/../src/Storages/StorageMergeTree.cpp:1170:18
    #4 0x1b4a030b in DB::InterpreterOptimizeQuery::execute() obj-x86_64-linux-gnu/../src/Interpreters/InterpreterOptimizeQuery.cpp:72:12
    #5 0x1ba0f310 in DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) obj-x86_64-linux-gnu/../src/Interpreters/executeQuery.cpp:635:32
    #6 0x1ba0c929 in DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) obj-x86_64-linux-gnu/../src/Interpreters/executeQuery.cpp:950:30
    #7 0x1c60e0b2 in DB::TCPHandler::runImpl() obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:292:24
    #8 0x1c6271b5 in DB::TCPHandler::run() obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:1641:9
    #9 0x1d3cf78b in Poco::Net::TCPServerConnection::start() obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerConnection.cpp:43:3
    #10 0x1d3cfc24 in Poco::Net::TCPServerDispatcher::run() obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerDispatcher.cpp:115:20
    #11 0x1d4c01a6 in Poco::PooledThread::run() obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/ThreadPool.cpp:199:14
    #12 0x1d4bda6b in Poco::ThreadImpl::runnableEntry(void*) obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345:27
    #13 0x7f987f95f608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x9608)
    #14 0x7f987f886292 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x122292)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../src/Storages/MergeTree/MergeTreeDataMergerMutator.cpp:393:26
```

```
2021.10.06 17:05:24.551032 [ 208 ] {} <Fatal> BaseDaemon: ########################################
2021.10.06 17:05:24.551206 [ 208 ] {} <Fatal> BaseDaemon: (version 21.11.1.1, build id: 08ED26ACFD1B086D5E26FB8818BB508EF7FB912D) (from thread 55) (query_id: c9da8656-e8e5-4a86-b679-63cbf20133ba) Received signal Unknown signal (-3)
2021.10.06 17:05:24.551243 [ 208 ] {} <Fatal> BaseDaemon: Sanitizer trap.
2021.10.06 17:05:24.551302 [ 208 ] {} <Fatal> BaseDaemon: Stack trace: 0xc824f6a 0x1a8206d1 0xc7e68a6 0xc7f54af 0x1c257b21 0x1c473d11 0x1c47511a 0x1c47a82b 0x1b4a030c 0x1ba0f311 0x1ba0c92a 0x1c60e0b3 0x1c6271b6 0x1d3cf78c 0x1d3cfc25 0x1d4c01a7 0x1d4bda6c 0x7f987f95f609 0x7f987f886293
2021.10.06 17:05:24.607103 [ 208 ] {} <Fatal> BaseDaemon: 0.1. inlined from ./obj-x86_64-linux-gnu/../src/Common/StackTrace.cpp:303: StackTrace::tryCapture()
2021.10.06 17:05:24.607154 [ 208 ] {} <Fatal> BaseDaemon: 0. ../src/Common/StackTrace.cpp:264: StackTrace::StackTrace() @ 0xc824f6a in /usr/bin/clickhouse
2021.10.06 17:05:24.666044 [ 208 ] {} <Fatal> BaseDaemon: 1. ./obj-x86_64-linux-gnu/../base/daemon/BaseDaemon.cpp:400: sanitizerDeathCallback() @ 0x1a8206d1 in /usr/bin/clickhouse
2021.10.06 17:05:26.143256 [ 208 ] {} <Fatal> BaseDaemon: 2. __sanitizer::Die() @ 0xc7e68a6 in /usr/bin/clickhouse
2021.10.06 17:05:27.086677 [ 208 ] {} <Fatal> BaseDaemon: 3. ? @ 0xc7f54af in /usr/bin/clickhouse
2021.10.06 17:05:27.161882 [ 208 ] {} <Fatal> BaseDaemon: 4. ./obj-x86_64-linux-gnu/../src/Storages/MergeTree/MergeTreeDataMergerMutator.cpp:0: DB::MergeTreeDataMergerMutator::selectAllPartsToMergeWithinPartition(std::__1::shared_ptr<DB::FutureMergedMutatedPart>, unsigned long&, std::__1::function<bool (std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*)> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, bool) @ 0x1c257b21 in /usr/bin/clickhouse
2021.10.06 17:05:27.243601 [ 208 ] {} <Fatal> BaseDaemon: 5. ./obj-x86_64-linux-gnu/../src/Storages/StorageMergeTree.cpp:746: DB::StorageMergeTree::selectPartsToMerge(std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>&, std::__1::unique_lock<std::__1::mutex>&, bool, DB::SelectPartsDecision*) @ 0x1c473d11 in /usr/bin/clickhouse
2021.10.06 17:05:27.298018 [ 208 ] {} <Fatal> BaseDaemon: 6. ./obj-x86_64-linux-gnu/../src/Storages/StorageMergeTree.cpp:0: DB::StorageMergeTree::merge(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, bool, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, bool) @ 0x1c47511a in /usr/bin/clickhouse
2021.10.06 17:05:27.374069 [ 208 ] {} <Fatal> BaseDaemon: 7. ./obj-x86_64-linux-gnu/../src/Storages/StorageMergeTree.cpp:1170: DB::StorageMergeTree::optimize(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::IAST> const&, bool, bool, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::Context const>) @ 0x1c47a82b in /usr/bin/clickhouse
2021.10.06 17:05:27.435810 [ 208 ] {} <Fatal> BaseDaemon: 8.1. inlined from ./obj-x86_64-linux-gnu/../src/DataStreams/BlockIO.h:14: BlockIO
2021.10.06 17:05:27.435878 [ 208 ] {} <Fatal> BaseDaemon: 8. ../src/Interpreters/InterpreterOptimizeQuery.cpp:74: DB::InterpreterOptimizeQuery::execute() @ 0x1b4a030c in /usr/bin/clickhouse
2021.10.06 17:05:27.494310 [ 208 ] {} <Fatal> BaseDaemon: 9. ./obj-x86_64-linux-gnu/../src/Interpreters/executeQuery.cpp:0: DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x1ba0f311 in /usr/bin/clickhouse
2021.10.06 17:05:27.553665 [ 208 ] {} <Fatal> BaseDaemon: 10. ./obj-x86_64-linux-gnu/../src/Interpreters/executeQuery.cpp:950: DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x1ba0c92a in /usr/bin/clickhouse
2021.10.06 17:05:27.599928 [ 208 ] {} <Fatal> BaseDaemon: 11. ./obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:292: DB::TCPHandler::runImpl() @ 0x1c60e0b3 in /usr/bin/clickhouse
2021.10.06 17:05:27.646965 [ 208 ] {} <Fatal> BaseDaemon: 12. ./obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:1643: DB::TCPHandler::run() @ 0x1c6271b6 in /usr/bin/clickhouse
2021.10.06 17:05:27.650629 [ 208 ] {} <Fatal> BaseDaemon: 13. ./obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x1d3cf78c in /usr/bin/clickhouse
2021.10.06 17:05:27.656948 [ 208 ] {} <Fatal> BaseDaemon: 14.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:1397: std::__1::default_delete<Poco::Net::TCPServerConnection>::operator()(Poco::Net::TCPServerConnection*) const
2021.10.06 17:05:27.657003 [ 208 ] {} <Fatal> BaseDaemon: 14.2. inlined from ../contrib/libcxx/include/memory:1658: std::__1::unique_ptr<Poco::Net::TCPServerConnection, std::__1::default_delete<Poco::Net::TCPServerConnection> >::reset(Poco::Net::TCPServerConnection*)
2021.10.06 17:05:27.657042 [ 208 ] {} <Fatal> BaseDaemon: 14.3. inlined from ../contrib/libcxx/include/memory:1612: ~unique_ptr
2021.10.06 17:05:27.657086 [ 208 ] {} <Fatal> BaseDaemon: 14. ../contrib/poco/Net/src/TCPServerDispatcher.cpp:116: Poco::Net::TCPServerDispatcher::run() @ 0x1d3cfc25 in /usr/bin/clickhouse
2021.10.06 17:05:27.664822 [ 208 ] {} <Fatal> BaseDaemon: 15. ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/ThreadPool.cpp:213: Poco::PooledThread::run() @ 0x1d4c01a7 in /usr/bin/clickhouse
2021.10.06 17:05:27.673266 [ 208 ] {} <Fatal> BaseDaemon: 16.1. inlined from ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/include/Poco/SharedPtr.h:156: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable> >::assign(Poco::Runnable*)
2021.10.06 17:05:27.673335 [ 208 ] {} <Fatal> BaseDaemon: 16.2. inlined from ../contrib/poco/Foundation/include/Poco/SharedPtr.h:208: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable> >::operator=(Poco::Runnable*)
2021.10.06 17:05:27.673385 [ 208 ] {} <Fatal> BaseDaemon: 16. ../contrib/poco/Foundation/src/Thread_POSIX.cpp:360: Poco::ThreadImpl::runnableEntry(void*) @ 0x1d4bda6c in /usr/bin/clickhouse
2021.10.06 17:05:27.673474 [ 208 ] {} <Fatal> BaseDaemon: 17. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
2021.10.06 17:05:27.673539 [ 208 ] {} <Fatal> BaseDaemon: 18. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.10.06 17:05:27.942158 [ 208 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: 2C40522105E21EC1B84BBAB0443014C0. There is no information about the reference checksum.
```

**Comment by alexey-milovidov** [comment]
IIRC we have fixed it.
