### ISSUE TITLE
AggregationCommon.h:97:35: runtime error: downcast of address which does not point to an object of type 'const DB::ColumnVectorHelper'

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#29885]
https://clickhouse-test-reports.s3.yandex.net/29804/90cc63aecd37ffe7a3f6497b462be55540bc70a5/fuzzer_ubsan/report.html#fail1

```
2021.10.08 01:36:26.272326 [ 86 ] {c4bfe9b4-b173-4034-9564-ef4b6140e81f} <Debug> executeQuery: (from [::1]:49682) SELECT inf, number FROM numbers(2) INTERSECT SELECT inf, number FROM numbers(0)
2021.10.08 01:36:26.272526 [ 86 ] {c4bfe9b4-b173-4034-9564-ef4b6140e81f} <Trace> ContextAccess (default): Access granted: CREATE TEMPORARY TABLE ON *.*
2021.10.08 01:36:26.272860 [ 86 ] {c4bfe9b4-b173-4034-9564-ef4b6140e81f} <Trace> ContextAccess (default): Access granted: CREATE TEMPORARY TABLE ON *.*
2021.10.08 01:36:26.273178 [ 86 ] {c4bfe9b4-b173-4034-9564-ef4b6140e81f} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2021.10.08 01:36:26.273268 [ 86 ] {c4bfe9b4-b173-4034-9564-ef4b6140e81f} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
../src/Interpreters/AggregationCommon.h:97:35: runtime error: downcast of address 0x7f5d980148c0 which does not point to an object of type 'const DB::ColumnVectorHelper'
0x7f5d980148c0: note: object is of type 'DB::ColumnConst'
 00 00 00 00  90 7c c5 08 00 00 00 00  01 00 00 00 5d 7f 00 00  20 86 3d 9b 5f 7f 00 00  02 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'DB::ColumnConst'
2021.10.08 01:36:26.792315 [ 151 ] {} <Trace> SystemLog (system.query_log): Flushing system log, 1606 entries to flush up to offset 397019
2021.10.08 01:36:26.799251 [ 87 ] {} <Trace> KeeperTCPHandler: Received heartbeat for session #1
2021.10.08 01:36:26.876509 [ 151 ] {} <Debug> DiskLocal: Reserving 6.44 MiB on disk `default`, having unreserved 2.27 TiB.
2021.10.08 01:36:26.894697 [ 151 ] {} <Trace> system.query_log (5b1fa2ed-6727-41c7-9b1f-a2ed672731c7): Renaming temporary part tmp_insert_202110_404_404_0 to 202110_404_404_0.
2021.10.08 01:36:26.895609 [ 151 ] {} <Trace> SystemLog (system.query_log): Flushed system log up to offset 397019
2021.10.08 01:36:27.000262 [ 293 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 5.60 GiB, peak 9.15 GiB, will set to 5.62 GiB (RSS), difference: 12.93 MiB
2021.10.08 01:36:27.638920 [ 152 ] {} <Trace> SystemLog (system.query_thread_log): Flushing system log, 2593 entries to flush up to offset 574493
2021.10.08 01:36:27.661463 [ 152 ] {} <Debug> DiskLocal: Reserving 2.20 MiB on disk `default`, having unreserved 2.27 TiB.
2021.10.08 01:36:27.668568 [ 152 ] {} <Trace> system.query_thread_log (f13e431a-e259-444c-b13e-431ae259544c): Renaming temporary part tmp_insert_202110_404_404_0 to 202110_404_404_0.
2021.10.08 01:36:27.669107 [ 152 ] {} <Trace> SystemLog (system.query_thread_log): Flushed system log up to offset 574493
2021.10.08 01:36:28.000137 [ 293 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 5.61 GiB, peak 9.15 GiB, will set to 5.62 GiB (RSS), difference: 8.43 MiB
    #0 0x197a7052 in void DB::fillFixedBatch<unsigned long, wide::integer<128ul, unsigned int> >(unsigned long, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> > const&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, DB::PODArray<wide::integer<128ul, unsigned int>, 4096ul, Allocator<false, false>, 15ul, 16ul>&, unsigned long&) (/workspace/clickhouse+0x197a7052)
    #1 0x197a69c9 in void DB::packFixedBatch<wide::integer<128ul, unsigned int> >(unsigned long, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> > const&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, DB::PODArray<wide::integer<128ul, unsigned int>, 4096ul, Allocator<false, false>, 15ul, 16ul>&) (/workspace/clickhouse+0x197a69c9)
    #2 0x1ce53e60 in DB::ColumnsHashing::HashMethodKeysFixed<wide::integer<128ul, unsigned int>, wide::integer<128ul, unsigned int>, void, false, false, true, false>::HashMethodKeysFixed(std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> > const&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, std::__1::shared_ptr<DB::ColumnsHashing::HashMethodContext> const&) obj-x86_64-linux-gnu/../src/Common/ColumnsHashing.h:524:13
    #3 0x1e03fdfc in unsigned long DB::IntersectOrExceptTransform::buildFilter<DB::SetMethodKeysFixed<HashSetTable<wide::integer<128ul, unsigned int>, HashTableCell<wide::integer<128ul, unsigned int>, UInt128HashCRC32, HashTableNoState>, UInt128HashCRC32, HashTableGrower<8ul>, Allocator<true, true> >, false> >(DB::SetMethodKeysFixed<HashSetTable<wide::integer<128ul, unsigned int>, HashTableCell<wide::integer<128ul, unsigned int>, UInt128HashCRC32, HashTableNoState>, UInt128HashCRC32, HashTableGrower<8ul>, Allocator<true, true> >, false>&, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> > const&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>&, unsigned long, DB::SetVariantsTemplate<DB::NonClearableSet>&) const obj-x86_64-linux-gnu/../src/Processors/Transforms/IntersectOrExceptTransform.cpp:108:28
    #4 0x1e036e8f in DB::IntersectOrExceptTransform::filter(DB::Chunk&) obj-x86_64-linux-gnu/../src/Processors/Transforms/IntersectOrExceptTransform.cpp:184:13
    #5 0x1e0357c4 in DB::IntersectOrExceptTransform::work() obj-x86_64-linux-gnu/../src/Processors/Transforms/IntersectOrExceptTransform.cpp:86:9
    #6 0x1dc9be98 in DB::executeJob(DB::IProcessor*) obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:88:20
    #7 0x1dc9bd86 in DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0::operator()() const obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:105:13
    #8 0x1dc9bd86 in decltype(std::__1::forward<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(fp)()) std::__1::__invoke<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&) obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3676:1
    #9 0x1dc9a327 in std::__1::__function::__policy_func<void ()>::operator()() const obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2221:16
    #10 0x1dc9a327 in std::__1::function<void ()>::operator()() const obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2560:12
    #11 0x1dc9a327 in DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:599:17
    #12 0x1dc9c769 in DB::PipelineExecutor::executeSingleThread(unsigned long, unsigned long) obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:487:5
    #13 0x1dc9c769 in DB::PipelineExecutor::executeImpl(unsigned long)::$_4::operator()() const obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:790:21
    #14 0x1dc9c769 in decltype(std::__1::forward<DB::PipelineExecutor::executeImpl(unsigned long)::$_4&>(fp)()) std::__1::__invoke_constexpr<DB::PipelineExecutor::executeImpl(unsigned long)::$_4&>(DB::PipelineExecutor::executeImpl(unsigned long)::$_4&) obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3682:1
    #15 0x1dc9c642 in decltype(auto) std::__1::__apply_tuple_impl<DB::PipelineExecutor::executeImpl(unsigned long)::$_4&, std::__1::tuple<>&>(DB::PipelineExecutor::executeImpl(unsigned long)::$_4&, std::__1::tuple<>&, std::__1::__tuple_indices<>) obj-x86_64-linux-gnu/../contrib/libcxx/include/tuple:1415:1
    #16 0x1dc9c642 in decltype(auto) std::__1::apply<DB::PipelineExecutor::executeImpl(unsigned long)::$_4&, std::__1::tuple<>&>(DB::PipelineExecutor::executeImpl(unsigned long)::$_4&, std::__1::tuple<>&) obj-x86_64-linux-gnu/../contrib/libcxx/include/tuple:1424:1
    #17 0x1dc9c642 in ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PipelineExecutor::executeImpl(unsigned long)::$_4>(DB::PipelineExecutor::executeImpl(unsigned long)::$_4&&)::'lambda'()::operator()() obj-x86_64-linux-gnu/../src/Common/ThreadPool.h:188:13
    #18 0x1dc9c642 in decltype(std::__1::forward<DB::PipelineExecutor::executeImpl(unsigned long)::$_4>(fp)()) std::__1::__invoke<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PipelineExecutor::executeImpl(unsigned long)::$_4>(DB::PipelineExecutor::executeImpl(unsigned long)::$_4&&)::'lambda'()&>(DB::PipelineExecutor::executeImpl(unsigned long)::$_4&&) obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3676:1
    #19 0xd3a7f19 in std::__1::__function::__policy_func<void ()>::operator()() const obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2221:16
    #20 0xd3a7f19 in std::__1::function<void ()>::operator()() const obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2560:12
    #21 0xd3a7f19 in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) obj-x86_64-linux-gnu/../src/Common/ThreadPool.cpp:274:17
    #22 0xd3aa921 in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()::operator()() const obj-x86_64-linux-gnu/../src/Common/ThreadPool.cpp:139:73
    #23 0xd3aa921 in decltype(std::__1::forward<void>(fp)()) std::__1::__invoke<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&) obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3676:1
    #24 0xd3aa921 in void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>&, std::__1::__tuple_indices<>) obj-x86_64-linux-gnu/../contrib/libcxx/include/thread:280:5
    #25 0xd3aa921 in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) obj-x86_64-linux-gnu/../contrib/libcxx/include/thread:291:5
    #26 0x7f63f7f42608 in start_thread /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477:8
    #27 0x7f63f7e69292 in __clone /build/glibc-eX1tMB/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../src/Interpreters/AggregationCommon.h:97:35 in 
2021.10.08 01:36:29.204626 [ 40 ] {} <Trace> BaseDaemon: Received signal -3
2021.10.08 01:36:29.204885 [ 604 ] {} <Fatal> BaseDaemon: ########################################
2021.10.08 01:36:29.205014 [ 604 ] {} <Fatal> BaseDaemon: (version 21.11.1.8340, build id: 883C21F92B1A606829076A906F2EA35CE47DE3B2) (from thread 359) (query_id: c4bfe9b4-b173-4034-9564-ef4b6140e81f) Received signal Unknown signal (-3)
2021.10.08 01:36:29.205061 [ 604 ] {} <Fatal> BaseDaemon: Sanitizer trap.
2021.10.08 01:36:29.205135 [ 604 ] {} <Fatal> BaseDaemon: Stack trace: 0xd37926a 0x1be0a271 0xd33aba6 0xd34c8d9 0x197a7053 0x197a69ca 0x1ce53e61 0x1e03fdfd 0x1e036e90 0x1e0357c5 0x1dc9be99 0x1dc9bd87 0x1dc9a328 0x1dc9c76a 0x1dc9c643 0xd3a7f1a 0xd3aa922 0x7f63f7f42609 0x7f63f7e69293
2021.10.08 01:36:29.216792 [ 604 ] {} <Fatal> BaseDaemon: 0.1. inlined from ./obj-x86_64-linux-gnu/../src/Common/StackTrace.cpp:303: StackTrace::tryCapture()
2021.10.08 01:36:29.216831 [ 604 ] {} <Fatal> BaseDaemon: 0. ../src/Common/StackTrace.cpp:264: StackTrace::StackTrace() @ 0xd37926a in /workspace/clickhouse
2021.10.08 01:36:29.241333 [ 604 ] {} <Fatal> BaseDaemon: 1. ./obj-x86_64-linux-gnu/../base/daemon/BaseDaemon.cpp:400: sanitizerDeathCallback() @ 0x1be0a271 in /workspace/clickhouse
2021.10.08 01:36:30.000175 [ 293 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 5.62 GiB, peak 9.15 GiB, will set to 5.74 GiB (RSS), difference: 128.75 MiB
2021.10.08 01:36:30.481869 [ 604 ] {} <Fatal> BaseDaemon: 2. __sanitizer::Die() @ 0xd33aba6 in /workspace/clickhouse
2021.10.08 01:36:31.000131 [ 293 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 5.74 GiB, peak 9.15 GiB, will set to 5.93 GiB (RSS), difference: 189.75 MiB
2021.10.08 01:36:31.130606 [ 156 ] {} <Debug> DiskLocal: Reserving 4.39 MiB on disk `default`, having unreserved 2.27 TiB.
2021.10.08 01:36:31.138206 [ 156 ] {} <Trace> system.text_log (167da525-3faa-4b51-967d-a5253faa7b51): Renaming temporary part tmp_insert_202110_443_443_0 to 202110_443_443_0.
2021.10.08 01:36:31.563977 [ 157 ] {} <Trace> SystemLog (system.metric_log): Flushing system log, 8 entries to flush up to offset 3336
2021.10.08 01:36:31.586845 [ 157 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 2.27 TiB.
2021.10.08 01:36:31.593184 [ 157 ] {} <Trace> system.metric_log (4783fde8-527e-420c-8783-fde8527e920c): Renaming temporary part tmp_insert_202110_443_443_0 to 202110_443_443_0.
2021.10.08 01:36:31.594805 [ 157 ] {} <Trace> SystemLog (system.metric_log): Flushed system log up to offset 3336
2021.10.08 01:36:31.721917 [ 604 ] {} <Fatal> BaseDaemon: 3. ? @ 0xd34c8d9 in /workspace/clickhouse
2021.10.08 01:36:32.000135 [ 293 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 5.92 GiB, peak 9.15 GiB, will set to 5.93 GiB (RSS), difference: 11.18 MiB
2021.10.08 01:36:32.928205 [ 158 ] {} <Trace> SystemLog (system.asynchronous_metric_log): Flushing system log, 9548 entries to flush up to offset 4550416
2021.10.08 01:36:32.935541 [ 158 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 2.27 TiB.
2021.10.08 01:36:32.937504 [ 158 ] {} <Trace> system.asynchronous_metric_log (e874de4b-d37a-49dd-a874-de4bd37a39dd): Renaming temporary part tmp_insert_202110_476_476_0 to 202110_476_476_0.
2021.10.08 01:36:32.937757 [ 158 ] {} <Trace> SystemLog (system.asynchronous_metric_log): Flushed system log up to offset 4550416
2021.10.08 01:36:32.954677 [ 604 ] {} <Fatal> BaseDaemon: 4. void DB::fillFixedBatch<unsigned long, wide::integer<128ul, unsigned int> >(unsigned long, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> > const&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, DB::PODArray<wide::integer<128ul, unsigned int>, 4096ul, Allocator<false, false>, 15ul, 16ul>&, unsigned long&) @ 0x197a7053 in /workspace/clickhouse
2021.10.08 01:36:34.196806 [ 604 ] {} <Fatal> BaseDaemon: 5. void DB::packFixedBatch<wide::integer<128ul, unsigned int> >(unsigned long, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> > const&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, DB::PODArray<wide::integer<128ul, unsigned int>, 4096ul, Allocator<false, false>, 15ul, 16ul>&) @ 0x197a69ca in /workspace/clickhouse
2021.10.08 01:36:34.257107 [ 604 ] {} <Fatal> BaseDaemon: 6. ./obj-x86_64-linux-gnu/../src/Common/ColumnsHashing.h:524: DB::ColumnsHashing::HashMethodKeysFixed<wide::integer<128ul, unsigned int>, wide::integer<128ul, unsigned int>, void, false, false, true, false>::HashMethodKeysFixed(std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> > const&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, std::__1::shared_ptr<DB::ColumnsHashing::HashMethodContext> const&) @ 0x1ce53e61 in /workspace/clickhouse
2021.10.08 01:36:34.290624 [ 604 ] {} <Fatal> BaseDaemon: 7. ./obj-x86_64-linux-gnu/../src/Processors/Transforms/IntersectOrExceptTransform.cpp:0: unsigned long DB::IntersectOrExceptTransform::buildFilter<DB::SetMethodKeysFixed<HashSetTable<wide::integer<128ul, unsigned int>, HashTableCell<wide::integer<128ul, unsigned int>, UInt128HashCRC32, HashTableNoState>, UInt128HashCRC32, HashTableGrower<8ul>, Allocator<true, true> >, false> >(DB::SetMethodKeysFixed<HashSetTable<wide::integer<128ul, unsigned int>, HashTableCell<wide::integer<128ul, unsigned int>, UInt128HashCRC32, HashTableNoState>, UInt128HashCRC32, HashTableGrower<8ul>, Allocator<true, true> >, false>&, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> > const&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>&, unsigned long, DB::SetVariantsTemplate<DB::NonClearableSet>&) const @ 0x1e03fdfd in /workspace/clickhouse
2021.10.08 01:36:34.318954 [ 604 ] {} <Fatal> BaseDaemon: 8. ./obj-x86_64-linux-gnu/../src/Processors/Transforms/IntersectOrExceptTransform.cpp:184: DB::IntersectOrExceptTransform::filter(DB::Chunk&) @ 0x1e036e90 in /workspace/clickhouse
2021.10.08 01:36:34.347195 [ 604 ] {} <Fatal> BaseDaemon: 9. ./obj-x86_64-linux-gnu/../src/Processors/Transforms/IntersectOrExceptTransform.cpp:87: DB::IntersectOrExceptTransform::work() @ 0x1e0357c5 in /workspace/clickhouse
2021.10.08 01:36:34.384868 [ 604 ] {} <Fatal> BaseDaemon: 10. ./obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:96: DB::executeJob(DB::IProcessor*) @ 0x1dc9be99 in /workspace/clickhouse
2021.10.08 01:36:34.421259 [ 604 ] {} <Fatal> BaseDaemon: 11.1. inlined from ./obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:108: operator()
2021.10.08 01:36:34.421298 [ 604 ] {} <Fatal> BaseDaemon: 11. ../contrib/libcxx/include/type_traits:3676: decltype(std::__1::forward<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(fp)()) std::__1::__invoke<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&) @ 0x1dc9bd87 in /workspace/clickhouse
2021.10.08 01:36:34.453360 [ 604 ] {} <Fatal> BaseDaemon: 12. ./obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:606: DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0x1dc9a328 in /workspace/clickhouse
2021.10.08 01:36:34.490540 [ 604 ] {} <Fatal> BaseDaemon: 13.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2851: std::__1::shared_ptr<DB::ThreadGroupStatus>::operator bool() const
2021.10.08 01:36:34.490570 [ 604 ] {} <Fatal> BaseDaemon: 13.2. inlined from ../src/Processors/Executors/PipelineExecutor.cpp:783: operator()
2021.10.08 01:36:34.490595 [ 604 ] {} <Fatal> BaseDaemon: 13.3. inlined from ../base/base/../base/scope_guard.h:94: basic_scope_guard<DB::PipelineExecutor::executeImpl(unsigned long)::$_4::operator()() const::'lambda'()>::invoke()
2021.10.08 01:36:34.490617 [ 604 ] {} <Fatal> BaseDaemon: 13.4. inlined from ../base/base/../base/scope_guard.h:44: ~basic_scope_guard
2021.10.08 01:36:34.490639 [ 604 ] {} <Fatal> BaseDaemon: 13.5. inlined from ../src/Processors/Executors/PipelineExecutor.cpp:798: operator()
2021.10.08 01:36:34.490660 [ 604 ] {} <Fatal> BaseDaemon: 13. ../contrib/libcxx/include/type_traits:3682: decltype(std::__1::forward<DB::PipelineExecutor::executeImpl(unsigned long)::$_4&>(fp)()) std::__1::__invoke_constexpr<DB::PipelineExecutor::executeImpl(unsigned long)::$_4&>(DB::PipelineExecutor::executeImpl(unsigned long)::$_4&) @ 0x1dc9c76a in /workspace/clickhouse
2021.10.08 01:36:34.527589 [ 604 ] {} <Fatal> BaseDaemon: 14.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/tuple:0: operator()
2021.10.08 01:36:34.527646 [ 604 ] {} <Fatal> BaseDaemon: 14. ../contrib/libcxx/include/type_traits:3676: decltype(std::__1::forward<DB::PipelineExecutor::executeImpl(unsigned long)::$_4>(fp)()) std::__1::__invoke<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PipelineExecutor::executeImpl(unsigned long)::$_4>(DB::PipelineExecutor::executeImpl(unsigned long)::$_4&&)::'lambda'()&>(DB::PipelineExecutor::executeImpl(unsigned long)::$_4&&) @ 0x1dc9c643 in /workspace/clickhouse
2021.10.08 01:36:34.542557 [ 604 ] {} <Fatal> BaseDaemon: 15.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2533: std::__1::function<void ()>::operator=(std::nullptr_t)
2021.10.08 01:36:34.542596 [ 604 ] {} <Fatal> BaseDaemon: 15. ../src/Common/ThreadPool.cpp:277: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xd3a7f1a in /workspace/clickhouse
2021.10.08 01:36:34.559726 [ 604 ] {} <Fatal> BaseDaemon: 16. ./obj-x86_64-linux-gnu/../src/Common/ThreadPool.cpp:0: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) @ 0xd3aa922 in /workspace/clickhouse
2021.10.08 01:36:34.559793 [ 604 ] {} <Fatal> BaseDaemon: 17. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
2021.10.08 01:36:34.559838 [ 604 ] {} <Fatal> BaseDaemon: 18. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.10.08 01:36:34.922434 [ 604 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: 1C26B2373B662DEE1203345C32456C8B. There is no information about the reference checksum.
```

**Comment by alexey-milovidov** [comment]
Duplicate of #32474.
