### ISSUE TITLE
base/glibc-compatibility/musl/pow.c:291:35: runtime error: division by zero

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#29893]
There is comment that x2 should not be zero and clang could incorrectly trigger division by 0 without barrier, but we can see that in clang-13 build with undefined sanitizer it is still triggered

https://github.com/ClickHouse/ClickHouse/blob/master/base/glibc-compatibility/musl/pow.c#L285-L292

```
../base/glibc-compatibility/musl/pow.c:291:35: runtime error: division by zero
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../base/glibc-compatibility/musl/pow.c:291:35 in
[Inferior 1 (process 28251) exited with code 01]
(gdb) run
Starting program: /home/qoega/undefined-ch/output/binary/clickhouse --version
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, pow (x=<optimized out>, y=-3) at ../base/glibc-compatibility/musl/pow.c:291
291	in ../base/glibc-compatibility/musl/pow.c
(gdb) bt full
#0  pow (x=<optimized out>, y=-3) at ../base/glibc-compatibility/musl/pow.c:291
        x2 = 0
        sign_bias = 0
        ix = 0
        iy = 13837309855095848960
        topx = 0
        topy = <optimized out>
        hi = <optimized out>
        ylo = <optimized out>
        yhi = <optimized out>
        llo = <optimized out>
        lo = <optimized out>
        lhi = <optimized out>
        elo = <optimized out>
        ehi = <optimized out>
#1  0x00000000171efd63 in _GLOBAL__sub_I_fdr_compile.cpp ()
No symbol table info available.
#2  0x000000001e41c57d in __libc_csu_init ()
No symbol table info available.
#3  0x00007ffff73d8b88 in __libc_start_main (main=0xcb8c180 <main(int, char**)>, argc=2, argv=0x7fffffffe2f8, init=0x1e41c530 <__libc_csu_init>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe2e8) at ../csu/libc-start.c:266
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, 140737341392376, 2097152, 12884901901, 0, 5, 2, 140737488347896}, mask_was_saved = -7408}}, priv = {pad = {0x7ffff779e630, 0x2, 0x7ffff7de38d3 <_dl_init+259>, 0x7ffff7dd1d70}, data = {prev = 0x7ffff779e630, cleanup = 0x2, canceltype = -136431405}}}
        not_first_call = <optimized out>
#4  0x000000000cb67eae in _start ()
No symbol table info available.
```

**Comment by alexey-milovidov** [comment]
No steps to reproduce.
