### ISSUE TITLE
`clickhouse-local` creates unnecessary threads

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#30249]
```
milovidov@mtlog-perftest03j:~$ clickhouse-local --query "SELECT 1"
1

milovidov@mtlog-perftest03j:~$ strace -e trace=clone clickhouse-local --query "SELECT 1"  
clone(child_stack=0x7f65c7c2abb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65c7c339d0, tls=0x7f65c7c33700, child_tidptr=0x7f65c7c339d0) = 638102
clone(child_stack=0x7f65c7429bb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65c74329d0, tls=0x7f65c7432700, child_tidptr=0x7f65c74329d0) = 638103
clone(child_stack=0x7f65c6c28bb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65c6c319d0, tls=0x7f65c6c31700, child_tidptr=0x7f65c6c319d0) = 638104
clone(child_stack=0x7f65c59f6bb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65c59ff9d0, tls=0x7f65c59ff700, child_tidptr=0x7f65c59ff9d0) = 638105
clone(child_stack=0x7f65c4bf6bb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65c4bff9d0, tls=0x7f65c4bff700, child_tidptr=0x7f65c4bff9d0) = 638106
clone(child_stack=0x7f65c43f5bb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65c43fe9d0, tls=0x7f65c43fe700, child_tidptr=0x7f65c43fe9d0) = 638107
clone(child_stack=0x7f65c3bf4bb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65c3bfd9d0, tls=0x7f65c3bfd700, child_tidptr=0x7f65c3bfd9d0) = 638108
clone(child_stack=0x7f65c2df6bb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65c2dff9d0, tls=0x7f65c2dff700, child_tidptr=0x7f65c2dff9d0) = 638109
clone(child_stack=0x7f65c1df6bb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65c1dff9d0, tls=0x7f65c1dff700, child_tidptr=0x7f65c1dff9d0) = 638110
clone(child_stack=0x7f65c0df6bb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65c0dff9d0, tls=0x7f65c0dff700, child_tidptr=0x7f65c0dff9d0) = 638111
clone(child_stack=0x7f65c01f6bb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65c01ff9d0, tls=0x7f65c01ff700, child_tidptr=0x7f65c01ff9d0) = 638112
clone(child_stack=0x7f65beff6bb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65befff9d0, tls=0x7f65befff700, child_tidptr=0x7f65befff9d0) = 638113
clone(child_stack=0x7f65be7f5bb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65be7fe9d0, tls=0x7f65be7fe700, child_tidptr=0x7f65be7fe9d0) = 638114
clone(child_stack=0x7f65bdff4bb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65bdffd9d0, tls=0x7f65bdffd700, child_tidptr=0x7f65bdffd9d0) = 638115
clone(child_stack=0x7f65bd7f3bb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65bd7fc9d0, tls=0x7f65bd7fc700, child_tidptr=0x7f65bd7fc9d0) = 638116
clone(child_stack=0x7f65bcff2bb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65bcffb9d0, tls=0x7f65bcffb700, child_tidptr=0x7f65bcffb9d0) = 638117
clone(child_stack=0x7f65bc7f1bb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65bc7fa9d0, tls=0x7f65bc7fa700, child_tidptr=0x7f65bc7fa9d0) = 638118
clone(child_stack=0x7f65bbff0bb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65bbff99d0, tls=0x7f65bbff9700, child_tidptr=0x7f65bbff99d0) = 638119
clone(child_stack=0x7f65bb7efbb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65bb7f89d0, tls=0x7f65bb7f8700, child_tidptr=0x7f65bb7f89d0) = 638120
clone(child_stack=0x7f65bafeebb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65baff79d0, tls=0x7f65baff7700, child_tidptr=0x7f65baff79d0) = 638121
clone(child_stack=0x7f65ba7edbb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65ba7f69d0, tls=0x7f65ba7f6700, child_tidptr=0x7f65ba7f69d0) = 638122
clone(child_stack=0x7f65b9fecbb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65b9ff59d0, tls=0x7f65b9ff5700, child_tidptr=0x7f65b9ff59d0) = 638123
clone(child_stack=0x7f65b97ebbb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65b97f49d0, tls=0x7f65b97f4700, child_tidptr=0x7f65b97f49d0) = 638124
clone(child_stack=0x7f65b8feabb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65b8ff39d0, tls=0x7f65b8ff3700, child_tidptr=0x7f65b8ff39d0) = 638125
clone(child_stack=0x7f65b87e9bb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65b87f29d0, tls=0x7f65b87f2700, child_tidptr=0x7f65b87f29d0) = 638126
clone(child_stack=0x7f65b7fe8bb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65b7ff19d0, tls=0x7f65b7ff1700, child_tidptr=0x7f65b7ff19d0) = 638127
clone(child_stack=0x7f65b77e7bb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65b77f09d0, tls=0x7f65b77f0700, child_tidptr=0x7f65b77f09d0) = 638128
clone(child_stack=0x7f65b6fe6bb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65b6fef9d0, tls=0x7f65b6fef700, child_tidptr=0x7f65b6fef9d0) = 638129
clone(child_stack=0x7f65b67e5bb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65b67ee9d0, tls=0x7f65b67ee700, child_tidptr=0x7f65b67ee9d0) = 638130
clone(child_stack=0x7f65b5fe4bb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65b5fed9d0, tls=0x7f65b5fed700, child_tidptr=0x7f65b5fed9d0) = 638131
clone(child_stack=0x7f65b57e3bb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65b57ec9d0, tls=0x7f65b57ec700, child_tidptr=0x7f65b57ec9d0) = 638132
clone(child_stack=0x7f65b4fe2bb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65b4feb9d0, tls=0x7f65b4feb700, child_tidptr=0x7f65b4feb9d0) = 638133
clone(child_stack=0x7f65b47e1bb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65b47ea9d0, tls=0x7f65b47ea700, child_tidptr=0x7f65b47ea9d0) = 638134
clone(child_stack=0x7f65b3fe0bb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65b3fe99d0, tls=0x7f65b3fe9700, child_tidptr=0x7f65b3fe99d0) = 638135
clone(child_stack=0x7f65b37dfbb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65b37e89d0, tls=0x7f65b37e8700, child_tidptr=0x7f65b37e89d0) = 638136
clone(child_stack=0x7f65b2fdebb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65b2fe79d0, tls=0x7f65b2fe7700, child_tidptr=0x7f65b2fe79d0) = 638137
clone(child_stack=0x7f65b27ddbb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65b27e69d0, tls=0x7f65b27e6700, child_tidptr=0x7f65b27e69d0) = 638138
clone(child_stack=0x7f65b1fdcbb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65b1fe59d0, tls=0x7f65b1fe5700, child_tidptr=0x7f65b1fe59d0) = 638139
clone(child_stack=0x7f65b17dbbb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65b17e49d0, tls=0x7f65b17e4700, child_tidptr=0x7f65b17e49d0) = 638140
clone(child_stack=0x7f65b09f6bb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65b09ff9d0, tls=0x7f65b09ff700, child_tidptr=0x7f65b09ff9d0) = 638141
clone(child_stack=0x7f65b01f5bb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65b01fe9d0, tls=0x7f65b01fe700, child_tidptr=0x7f65b01fe9d0) = 638142
clone(child_stack=0x7f65ae1a6bb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65ae1af9d0, tls=0x7f65ae1af700, child_tidptr=0x7f65ae1af9d0) = 638143
clone(child_stack=0x7f65ad9a5bb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65ad9ae9d0, tls=0x7f65ad9ae700, child_tidptr=0x7f65ad9ae9d0) = 638144
clone(child_stack=0x7f65ad1a4bb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f65ad1ad9d0, tls=0x7f65ad1ad700, child_tidptr=0x7f65ad1ad9d0) = 638145
1
+++ exited with 0 +++

milovidov@mtlog-perftest03j:~$ gdb --args clickhouse-local --query "SELECT 1"
GNU gdb (Ubuntu 8.2-0ubuntu1~18.04) 8.2
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from clickhouse-local...catch sysdone.
(gdb) catch syscall clone
Catchpoint 1 (syscall 'clone' [56])
(gdb) r
Starting program: /usr/bin/clickhouse-local --query SELECT\ 1
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Catchpoint 1 (call to syscall clone), clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:78
78      ../sysdeps/unix/sysv/linux/x86_64/clone.S: No such file or directory.
(gdb) bt
#0  clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:78
#1  0x00007f7655b07ec5 in create_thread (thread_ran=<synthetic pointer>, stackaddr=0x7f765322abc0, stopped_start=<synthetic pointer>, attr=0x7ffc5dce51e0, pd=0x7f7653233700)
    at ../sysdeps/unix/sysv/linux/createthread.c:100
#2  __pthread_create_2_1 (newthread=<optimized out>, attr=<optimized out>, start_routine=<optimized out>, arg=0x7f76542476c0) at pthread_create.c:797
#3  0x00000000094d3bdc in std::__1::__libcpp_thread_create (__t=0x7ffc5dce52d0, __func=0x7f76532339d0, __arg=0xffffffffffffffda) at ../contrib/libcxx/include/__threading_support:509
#4  std::__1::thread::thread<ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::{lambda()#2}, , void>(ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::{lambda()#2}&&) (this=this@entry=0x7ffc5dce52d0, __f=...) at ../contrib/libcxx/include/thread:307
#5  0x00000000094d0b6d in ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>) (this=this@entry=0x7f7654290600, job=..., 
    priority=priority@entry=0, wait_microseconds=...) at ../src/Common/ThreadPool.cpp:139
#6  0x00000000094d48c0 in ThreadPoolImpl<std::__1::thread>::scheduleOrThrow(std::__1::function<void ()>, int, unsigned long) (this=0x7f7654290600, job=..., priority=0, wait_microseconds=0)
    at ../src/Common/ThreadPool.cpp:171
#7  ThreadFromGlobalPool::ThreadFromGlobalPool<ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::{lambda()#2}>(ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::{lambda()#2}&&) (this=this@entry=0x7ffc5dce53b0, func=...) at ../src/Common/ThreadPool.h:169
#8  0x00000000094d232e in ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>) (this=0x7f76542687d0, job=..., priority=<optimized out>, 
    wait_microseconds=...) at ../src/Common/ThreadPool.cpp:139
#9  0x00000000094d2002 in ThreadPoolImpl<ThreadFromGlobalPool>::scheduleOrThrowOnError(std::__1::function<void ()>, int) (this=0x3d0f00, job=..., priority=1394817488) at ../src/Common/ThreadPool.cpp:159
#10 0x0000000010cfb74e in DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::MergeTreeBackgroundExecutor (this=0x7f7654268700, name_=..., threads_count_=<optimized out>, 
    max_tasks_count_=<optimized out>, metric_=<optimized out>) at ../src/Storages/MergeTree/MergeTreeBackgroundExecutor.h:173
#11 0x00000000100fc8c9 in shared_ptr_helper<DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue> >::create<char const (&) [12], DB::SettingFieldNumber<unsigned long> const&, unsigned long const&, unsigned long const&> (args=@0x476adf0: 6, args=@0x476adf0: 6, args=@0x476adf0: 6, args=@0x476adf0: 6) at ../base/base/../base/shared_ptr_helper.h:17
#12 0x00000000100f8ea3 in DB::Context::initializeBackgroundExecutors (this=0x7f765438f000) at ../src/Interpreters/Context.cpp:2851
#13 0x000000000955cd6b in DB::LocalServer::processConfig (this=0x7ffc5dce5b60) at ../programs/local/LocalServer.cpp:530
#14 0x000000000955bf90 in DB::LocalServer::main (this=0x7ffc5dce5b60) at ../programs/local/LocalServer.cpp:443
#15 0x0000000013169e83 in Poco::Util::Application::run (this=0x7ffc5dce5b60) at ../contrib/poco/Util/src/Application.cpp:334
#16 0x0000000009561137 in mainEntryClickHouseLocal (argc=<optimized out>, argv=<optimized out>) at ../programs/local/LocalServer.cpp:725
#17 0x0000000009497721 in main (argc_=<optimized out>, argv_=<optimized out>) at ../programs/main.cpp:372
(gdb) quit
A debugging session is active.

        Inferior 1 [process 638282] will be killed.

Quit anyway? (y or n) y
```

**Comment by nikitamikhaylov** [comment]
I think these threads are background threads for *MergeTree tables. They are stored in global context and initialized at startup.

**Comment by alexey-milovidov** [comment]
They should not be initialized at startup for clickhouse-local if there is no MergeTree tables.
