### ISSUE TITLE
Hung check failed: `UserDefinedFunction::executeImpl` and `ParallelParsingInputFormat::generate`

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#30375]
https://clickhouse-test-reports.s3.yandex.net/0/4396daeb1f465cf498fb708c25e7b1f9c60a3281/stress_test_(address).html#fail1

Query:
```
    {
        "is_initial_query": 1,
        "user": "default",
        "query_id": "3d3ec28d-b21e-4f36-8476-13f7b06f7711",
        "address": "::1",
        "port": 55368,
        "initial_user": "default",
        "initial_query_id": "3d3ec28d-b21e-4f36-8476-13f7b06f7711",
        "initial_address": "::1",
        "initial_port": 55368,
        "interface": 1,
        "os_user": "",
        "client_hostname": "d35fe21659ef",
        "client_name": "ClickHouse ",
        "client_revision": "54450",
        "client_version_major": "21",
        "client_version_minor": "11",
        "client_version_patch": "1",
        "http_method": 0,
        "http_user_agent": "",
        "http_referer": "",
        "forwarded_for": "",
        "quota_key": "",
        "elapsed": 2979.419847468,
        "is_cancelled": 0,
        "read_rows": "0",
        "read_bytes": "0",
        "total_rows_approx": "0",
        "written_rows": "0",
        "written_bytes": "0",
        "memory_usage": "5247051",
        "peak_memory_usage": "5247051",
        "query": "SELECT test_function(2, 2);",
        "thread_ids": [
            "17094",
            "31375"
        ],
        "ProfileEvents": {
            "Query": "1",
            "SelectQuery": "1",
            "ReadBufferFromFileDescriptorRead": "1",
            "IOBufferAllocs": "3",
            "IOBufferAllocBytes": "3145728",
            "ContextLock": "8",
            "RWLockAcquiredReadLocks": "1"
        },
        "Settings": {
            "connect_timeout_with_failover_ms": "2000",
            "connect_timeout_with_failover_secure_ms": "3000",
            "idle_connection_timeout": "36000",
            "replication_wait_for_inactive_replica_timeout": "30",
            "load_balancing": "random",
            "log_queries": "1",
            "insert_quorum_timeout": "60000",
            "fsync_metadata": "0",
            "http_send_timeout": "60",
            "http_receive_timeout": "60",
            "opentelemetry_start_trace_probability": "0.1",
            "max_memory_usage": "10000000000",
            "max_untracked_memory": "1048576",
            "memory_profiler_step": "1048576",
            "log_comment": "02043_user_defined_executable_function_implicit_cast.sql",
            "send_logs_level": "warning",
            "database_atomic_wait_for_drop_and_detach_synchronously": "1",
            "async_insert_busy_timeout_ms": "5000"
        },
        "current_database": "test_25"
    },
```

Stacktraces:
```
Thread 831 (Thread 0x7fe33dd7c700 (LWP 31375)):
#0  0x00007fe796e0236c in read () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x000000000b9eae60 in read ()
#2  0x000000000bb99515 in DB::ReadBufferFromFileDescriptor::nextImpl (this=<optimized out>) at ../src/IO/ReadBufferFromFileDescriptor.cpp:68
#3  0x000000000bbe4b90 in DB::ReadBuffer::next (this=0x618003ca8510) at ../src/IO/ReadBuffer.h:62
#4  DB::ReadBuffer::eof (this=0x618003ca8510) at ../src/IO/ReadBuffer.h:93
#5  DB::loadAtPosition (in=..., memory=..., current=@0x7fe33dd74800: 0x7fe600716800 '\276' <repeats 200 times>...) at ../src/IO/ReadHelpers.cpp:1153
#6  0x000000002805f589 in DB::fileSegmentationEngineTabSeparatedImpl (in=..., memory=..., min_chunk_size=<optimized out>) at ../src/Processors/Formats/Impl/TabSeparatedRowInputFormat.cpp:444
#7  0x0000000027eb95c9 in std::__1::__function::__policy_func<std::__1::pair<bool, unsigned long> (DB::ReadBuffer&, DB::Memory<Allocator<false, false> >&, unsigned long)>::operator()(DB::ReadBuffer&, DB::Memory<Allocator<false, false> >&, unsigned long&&) const (this=0x619004fb01a8, __args=<optimized out>, __args=<optimized out>, __args=<optimized out>) at ../contrib/libcxx/include/functional:2221
#8  std::__1::function<std::__1::pair<bool, unsigned long> (DB::ReadBuffer&, DB::Memory<Allocator<false, false> >&, unsigned long)>::operator()(DB::ReadBuffer&, DB::Memory<Allocator<false, false> >&, unsigned long) const (this=0x619004fb01a8, __arg=140632645444460, __arg=140632645444460, __arg=140632645444460) at ../contrib/libcxx/include/functional:2560
#9  DB::ParallelParsingInputFormat::segmentatorThreadFunction (this=<optimized out>, thread_group=...) at ../src/Processors/Formats/Impl/ParallelParsingInputFormat.cpp:40
#10 0x0000000027ec6661 in std::__1::__invoke_constexpr<void (DB::ParallelParsingInputFormat::*&)(std::__1::shared_ptr<DB::ThreadGroupStatus>), DB::ParallelParsingInputFormat*&, std::__1::shared_ptr<DB::ThreadGroupStatus>&, void> (__a0=@0x7fe33dd74b40: 0x619004fb0098, __args=..., __f=<optimized out>) at ../contrib/libcxx/include/type_traits:3624
#11 std::__1::__apply_tuple_impl<void (DB::ParallelParsingInputFormat::*&)(std::__1::shared_ptr<DB::ThreadGroupStatus>), std::__1::tuple<DB::ParallelParsingInputFormat*, std::__1::shared_ptr<DB::ThreadGroupStatus> >&, 0ul, 1ul> (__t=..., __f=<optimized out>) at ../contrib/libcxx/include/tuple:1415
#12 std::__1::apply<void (DB::ParallelParsingInputFormat::*&)(std::__1::shared_ptr<DB::ThreadGroupStatus>), std::__1::tuple<DB::ParallelParsingInputFormat*, std::__1::shared_ptr<DB::ThreadGroupStatus> >&> (__t=..., __f=<optimized out>) at ../contrib/libcxx/include/tuple:1424
#13 ThreadFromGlobalPool::ThreadFromGlobalPool<void (DB::ParallelParsingInputFormat::*)(std::__1::shared_ptr<DB::ThreadGroupStatus>), DB::ParallelParsingInputFormat*, std::__1::shared_ptr<DB::ThreadGroupStatus> >(void (DB::ParallelParsingInputFormat::*&&)(std::__1::shared_ptr<DB::ThreadGroupStatus>), DB::ParallelParsingInputFormat*&&, std::__1::shared_ptr<DB::ThreadGroupStatus>&&)::{lambda()#1}::operator()() (this=<optimized out>) at ../src/Common/ThreadPool.h:188
#14 0x000000000bba1de7 in std::__1::__function::__policy_func<void ()>::operator()() const (this=0x7fe33dd74f60) at ../contrib/libcxx/include/functional:2221
#15 std::__1::function<void ()>::operator()() const (this=0x7fe33dd74f60) at ../contrib/libcxx/include/functional:2560
#16 ThreadPoolImpl<std::__1::thread>::worker (this=<optimized out>, thread_it=...) at ../src/Common/ThreadPool.cpp:274
#17 0x000000000bbaa157 in ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::{lambda()#2}::operator()() const (this=<optimized out>) at ../src/Common/ThreadPool.cpp:139
#18 std::__1::__invoke<ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::{lambda()#2}> (__f=...) at ../contrib/libcxx/include/type_traits:3676
#19 std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::{lambda()#2}>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::{lambda()#2}>&, std::__1::__tuple_indices<>) (__t=...) at ../contrib/libcxx/include/thread:280
#20 std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::{lambda()#2}> >(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::{lambda()#2}>) (__vp=<optimized out>) at ../contrib/libcxx/include/thread:291
#21 0x00007fe796df7609 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#22 0x00007fe796d1e293 in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 855 (Thread 0x7fe54e796700 (LWP 17094)):
#0  0x00007fe796dfe376 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000034f858f8 in std::__1::__libcpp_condvar_wait (__cv=0x619004fb0280, __m=0x80) at ../contrib/libcxx/include/__threading_support:436
#2  std::__1::condition_variable::wait (this=0x619004fb0280, lk=...) at ../contrib/libcxx/src/condition_variable.cpp:44
#3  0x0000000027ebc9fa in std::__1::condition_variable::wait<DB::ParallelParsingInputFormat::generate()::$_3>(std::__1::unique_lock<std::__1::mutex>&, DB::ParallelParsingInputFormat::generate()::$_3) (this=0x619004fb0258, __lk=..., __pred=...) at ../contrib/libcxx/include/__mutex_base:406
#4  DB::ParallelParsingInputFormat::generate (this=<optimized out>) at ../src/Processors/Formats/Impl/ParallelParsingInputFormat.cpp:180
#5  0x0000000027c83df0 in DB::ISource::tryGenerate (this=0x619004fb0098) at ../src/Processors/ISource.cpp:79
#6  0x0000000027c830ba in DB::ISource::work (this=0x619004fb0098) at ../src/Processors/ISource.cpp:53
#7  0x0000000027cc9a56 in DB::executeJob (processor=0x619004fb0098) at ../src/Processors/Executors/PipelineExecutor.cpp:88
#8  DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0::operator()() const (this=0x612001f575b0) at ../src/Processors/Executors/PipelineExecutor.cpp:105
#9  std::__1::__invoke<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&> (__f=...) at ../contrib/libcxx/include/type_traits:3676
#10 std::__1::__invoke_void_return_wrapper<void>::__call<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&) (__args=...) at ../contrib/libcxx/include/__functional_base:348
#11 std::__1::__function::__default_alloc_func<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0, void ()>::operator()() (this=0x612001f575b0) at ../contrib/libcxx/include/functional:1608
#12 std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0, void ()> >(std::__1::__function::__policy_storage const*) (__buf=0x612001f575b0) at ../contrib/libcxx/include/functional:2089
#13 0x0000000027cc4791 in std::__1::__function::__policy_func<void ()>::operator()() const (this=0xfffffffffffffe70) at ../contrib/libcxx/include/functional:2221
#14 std::__1::function<void ()>::operator()() const (this=0xfffffffffffffe70) at ../contrib/libcxx/include/functional:2560
#15 DB::PipelineExecutor::executeStepImpl (this=0x614003e11c58, thread_num=<optimized out>, num_threads=<optimized out>, yield_flag=<optimized out>) at ../src/Processors/Executors/PipelineExecutor.cpp:599
#16 0x0000000027cc12fd in DB::PipelineExecutor::executeStep (this=0x614003e11c58, yield_flag=<optimized out>) at ../src/Processors/Executors/PipelineExecutor.cpp:440
#17 0x0000000027ce7b9f in DB::PullingPipelineExecutor::pull (this=0x60400281c690, chunk=...) at ../src/Processors/Executors/PullingPipelineExecutor.cpp:47
#18 0x000000001ea6a276 in DB::ShellCommandSource::generate (this=0x61700253fc80) at ../src/Processors/Sources/ShellCommandSource.h:126
#19 0x0000000027c83df0 in DB::ISource::tryGenerate (this=0x61700253fc80) at ../src/Processors/ISource.cpp:79
#20 0x0000000027c830ba in DB::ISource::work (this=0x61700253fc80) at ../src/Processors/ISource.cpp:53
#21 0x0000000028259e46 in DB::SourceWithProgress::work (this=0x61700253fc80) at ../src/Processors/Sources/SourceWithProgress.cpp:65
#22 0x0000000027cc9a56 in DB::executeJob (processor=0x61700253fc80) at ../src/Processors/Executors/PipelineExecutor.cpp:88
#23 DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0::operator()() const (this=0x612002f98a30) at ../src/Processors/Executors/PipelineExecutor.cpp:105
#24 std::__1::__invoke<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&> (__f=...) at ../contrib/libcxx/include/type_traits:3676
#25 std::__1::__invoke_void_return_wrapper<void>::__call<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&) (__args=...) at ../contrib/libcxx/include/__functional_base:348
#26 std::__1::__function::__default_alloc_func<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0, void ()>::operator()() (this=0x612002f98a30) at ../contrib/libcxx/include/functional:1608
#27 std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0, void ()> >(std::__1::__function::__policy_storage const*) (__buf=0x612002f98a30) at ../contrib/libcxx/include/functional:2089
#28 0x0000000027cc4791 in std::__1::__function::__policy_func<void ()>::operator()() const (this=0xfffffffffffffe70) at ../contrib/libcxx/include/functional:2221
#29 std::__1::function<void ()>::operator()() const (this=0xfffffffffffffe70) at ../contrib/libcxx/include/functional:2560
#30 DB::PipelineExecutor::executeStepImpl (this=0x6140025bc458, thread_num=<optimized out>, num_threads=<optimized out>, yield_flag=<optimized out>) at ../src/Processors/Executors/PipelineExecutor.cpp:599
#31 0x0000000027cc12fd in DB::PipelineExecutor::executeStep (this=0x6140025bc458, yield_flag=<optimized out>) at ../src/Processors/Executors/PipelineExecutor.cpp:440
#32 0x0000000027ce7b9f in DB::PullingPipelineExecutor::pull (this=0x7fe54e780210, chunk=...) at ../src/Processors/Executors/PullingPipelineExecutor.cpp:47
#33 0x0000000027ce8660 in DB::PullingPipelineExecutor::pull (this=0x7fe54e780210, block=...) at ../src/Processors/Executors/PullingPipelineExecutor.cpp:58
#34 0x00000000262636ef in DB::UserDefinedFunction::executeImpl (this=<optimized out>, arguments=..., result_type=..., input_rows_count=<optimized out>) at ../src/Interpreters/UserDefinedExecutableFunctionFactory.cpp:127
#35 0x0000000011b7c8f5 in DB::IFunction::executeImplDryRun(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const ()
#36 0x0000000011b7bf4c in DB::FunctionToExecutableFunctionAdaptor::executeDryRunImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const ()
#37 0x000000002398bc7b in DB::IExecutableFunction::executeWithoutLowCardinalityColumns (this=0x60300163e370, args=..., result_type=..., input_rows_count=1, dry_run=<optimized out>) at ../src/Functions/IFunction.cpp:215
#38 0x000000002398ab8e in DB::IExecutableFunction::defaultImplementationForConstantArguments (this=0x60300163e370, args=..., result_type=..., input_rows_count=<optimized out>, dry_run=<optimized out>) at ../src/Functions/IFunction.cpp:161
#39 0x000000002398bbc5 in DB::IExecutableFunction::executeWithoutLowCardinalityColumns (this=0x60300163e370, args=..., result_type=..., input_rows_count=1, dry_run=<optimized out>) at ../src/Functions/IFunction.cpp:207
#40 0x000000002398cc25 in DB::IExecutableFunction::execute (this=<optimized out>, arguments=..., result_type=..., input_rows_count=<optimized out>, dry_run=<optimized out>) at ../src/Functions/IFunction.cpp:260
#41 0x00000000246ef33d in DB::ActionsDAG::addFunction (this=<optimized out>, function=..., children=..., result_name=...) at ../src/Interpreters/ActionsDAG.cpp:198
#42 0x0000000024d34f95 in DB::ScopeStack::addFunction (this=<optimized out>, function=..., argument_names=..., result_name=...) at ../src/Interpreters/ActionsVisitor.cpp:577
#43 0x0000000024d456a8 in DB::ActionsMatcher::Data::addFunction (this=<optimized out>, function=..., argument_names=..., result_name=...) at ../src/Interpreters/ActionsVisitor.h:169
#44 DB::ActionsMatcher::visit (node=..., ast=..., data=...) at ../src/Interpreters/ActionsVisitor.cpp:1067
#45 0x0000000024d363c3 in DB::ActionsMatcher::visit (ast=..., data=...) at ../src/Interpreters/ActionsVisitor.cpp:634
#46 0x0000000024d4e1b4 in DB::ActionsMatcher::visit (expression_list=..., data=...) at ../src/Interpreters/ActionsVisitor.cpp:736
#47 0x0000000024cf2298 in DB::InDepthNodeVisitor<DB::ActionsMatcher, true, false, std::__1::shared_ptr<DB::IAST> const>::visit (this=<optimized out>, ast=...) at ../src/Interpreters/InDepthNodeVisitor.h:34
#48 0x0000000024cc84bb in DB::ExpressionAnalyzer::getRootActions (this=<optimized out>, ast=..., no_subqueries=<optimized out>, actions=..., only_consts=<optimized out>) at ../src/Interpreters/ExpressionAnalyzer.cpp:467
#49 0x0000000024cdd876 in DB::SelectQueryExpressionAnalyzer::appendSelect (this=0x616001e54380, chain=..., only_types=<optimized out>) at ../src/Interpreters/ExpressionAnalyzer.cpp:1203
#50 0x0000000024ce8232 in DB::ExpressionAnalysisResult::ExpressionAnalysisResult (this=0x7fe54e784eb0, query_analyzer=..., metadata_snapshot=..., first_stage_=<optimized out>, second_stage_=<optimized out>, only_types=<optimized out>, filter_info_=..., source_header=...) at ../src/Interpreters/ExpressionAnalyzer.cpp:1617
#51 0x00000000255b187e in DB::InterpreterSelectQuery::getSampleBlockImpl (this=<optimized out>) at ../src/Interpreters/InterpreterSelectQuery.cpp:627
#52 0x000000002559fe8e in DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&)::$_1::operator()(bool) const (this=0xc38006cdba8, try_move_to_prewhere=<optimized out>) at ../src/Interpreters/InterpreterSelectQuery.cpp:492
#53 0x000000002559403c in DB::InterpreterSelectQuery::InterpreterSelectQuery (this=<optimized out>, query_ptr_=..., context_=..., input_pipe_=..., storage_=..., options_=..., required_result_column_names=..., metadata_snapshot_=...) at ../src/Interpreters/InterpreterSelectQuery.cpp:495
#54 0x0000000025590957 in DB::InterpreterSelectQuery::InterpreterSelectQuery (this=<optimized out>, query_ptr_=..., context_=..., options_=..., required_result_column_names_=...) at ../src/Interpreters/InterpreterSelectQuery.cpp:157
#55 0x0000000025d48de1 in std::__1::make_unique<DB::InterpreterSelectQuery, std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>&, DB::SelectQueryOptions&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&> (__args=..., __args=..., __args=..., __args=...) at ../contrib/libcxx/include/memory:2068
#56 DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter (this=this@entry=0x6110019a5540, ast_ptr_=..., current_required_result_column_names=...) at ../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:216
#57 0x0000000025d45134 in DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery (this=<optimized out>, query_ptr_=..., context_=..., options_=..., required_result_column_names=...) at ../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:138
#58 0x0000000025498105 in std::__1::make_unique<DB::InterpreterSelectWithUnionQuery, std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>&, DB::SelectQueryOptions const&> (__args=..., __args=..., __args=...) at ../contrib/libcxx/include/memory:2068
#59 DB::InterpreterFactory::get (query=..., context=..., options=...) at ../src/Interpreters/InterpreterFactory.cpp:118
#60 0x00000000262f1762 in DB::executeQueryImpl (begin=<optimized out>, end=<optimized out>, context=..., internal=false, stage=<optimized out>, istr=<optimized out>) at ../src/Interpreters/executeQuery.cpp:602
#61 0x00000000262ede11 in DB::executeQuery (query=..., context=..., internal=<optimized out>, stage=<optimized out>) at ../src/Interpreters/executeQuery.cpp:947
#62 0x0000000027bbdb76 in DB::TCPHandler::runImpl (this=0x61a003457880) at ../src/Server/TCPHandler.cpp:316
#63 0x0000000027bebb40 in DB::TCPHandler::run (this=0x61a003457880) at ../src/Server/TCPHandler.cpp:1837
#64 0x000000002f13ee4f in Poco::Net::TCPServerConnection::start (this=0x619004fb0280) at ../contrib/poco/Net/src/TCPServerConnection.cpp:43
#65 0x000000002f13fb41 in Poco::Net::TCPServerDispatcher::run (this=<optimized out>) at ../contrib/poco/Net/src/TCPServerDispatcher.cpp:115
#66 0x000000002f436026 in Poco::PooledThread::run (this=<optimized out>) at ../contrib/poco/Foundation/src/ThreadPool.cpp:199
#67 0x000000002f42f53a in Poco::ThreadImpl::runnableEntry (pThread=0x6160002805b8) at ../contrib/poco/Foundation/src/Thread_POSIX.cpp:345
#68 0x00007fe796df7609 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#69 0x00007fe796d1e293 in clone () from /lib/x86_64-linux-gnu/libc.so.6
```
Seems like UDF script process is terminated, but Buffer is still trying to read from pipe.

cc: @kitaisreal

**Comment by kitaisreal** [comment]
If script signalled, or too slow, or there were issue during script startup, ClickHouse will not hung. Fixed in https://github.com/ClickHouse/ClickHouse/pull/30957.
