### ISSUE TITLE
ExpressionAnalyzer.cpp:555: member access within address which does not point to an object of type 'const DB::ASTFunction' 

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#30683]
https://clickhouse-test-reports.s3.yandex.net/30651/70097b5c4e26a5422d9fc1a795a493b96bb5521d/fuzzer_ubsan/report.html#fail1

```
../src/Interpreters/ExpressionAnalyzer.cpp:555:19: runtime error: member access within address 0x7f9ba926f8b8 which does not point to an object of type 'const DB::ASTFunction'
0x7f9ba926f8b8: note: object is of type 'DB::IAST'
 00 00 00 00  08 d3 1b 09 00 00 00 00  b8 f8 26 a9 9b 7f 00 00  a0 f8 26 a9 9b 7f 00 00  f0 a1 79 92
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'DB::IAST'
    #0 0x1c7433ca in DB::ExpressionAnalyzer::makeAggregateDescriptions(std::__1::shared_ptr<DB::ActionsDAG>&, std::__1::vector<DB::AggregateDescription, std::__1::allocator<DB::AggregateDescription> >&) obj-x86_64-linux-gnu/../src/Interpreters/ExpressionAnalyzer.cpp:555:19
    #1 0x1c741a24 in DB::ExpressionAnalyzer::analyzeAggregation(std::__1::shared_ptr<DB::ActionsDAG>&) obj-x86_64-linux-gnu/../src/Interpreters/ExpressionAnalyzer.cpp:325:5
    #2 0x1c740e08 in DB::ExpressionAnalyzer::ExpressionAnalyzer(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::TreeRewriterResult const> const&, std::__1::shared_ptr<DB::Context const>, unsigned long, bool, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, DB::SubqueryForSet, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, DB::SubqueryForSet> > >, std::__1::unordered_map<DB::PreparedSetKey, std::__1::shared_ptr<DB::Set>, DB::PreparedSetKey::Hash, std::__1::equal_to<DB::PreparedSetKey>, std::__1::allocator<std::__1::pair<DB::PreparedSetKey const, std::__1::shared_ptr<DB::Set> > > >) obj-x86_64-linux-gnu/../src/Interpreters/ExpressionAnalyzer.cpp:254:5
    #3 0x1c75d91e in DB::ExpressionAnalyzer::ExpressionAnalyzer(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::TreeRewriterResult const> const&, std::__1::shared_ptr<DB::Context const>) obj-x86_64-linux-gnu/../src/Interpreters/ExpressionAnalyzer.h:101:11
    #4 0x1d7bc0c6 in DB::KeyCondition::getBlockWithConstants(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::TreeRewriterResult const> const&, std::__1::shared_ptr<DB::Context const>) obj-x86_64-linux-gnu/../src/Storages/MergeTree/KeyCondition.cpp:439:44
    #5 0x1d7bc4e9 in DB::KeyCondition::KeyCondition(DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::ExpressionActions> const&, bool, bool) obj-x86_64-linux-gnu/../src/Storages/MergeTree/KeyCondition.cpp:478:34
    #6 0x1d89a9d2 in DB::PartitionPruner::PartitionPruner(std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>, bool) obj-x86_64-linux-gnu/../src/Storages/MergeTree/PartitionPruner.h:29:11
    #7 0x1d831219 in DB::MergeTreeData::totalRowsByPartitionPredicateImpl(DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const> > > const&) const obj-x86_64-linux-gnu/../src/Storages/MergeTree/MergeTreeData.cpp:848:21
    #8 0x1dacd8dc in DB::StorageMergeTree::totalRowsByPartitionPredicate(DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>) const obj-x86_64-linux-gnu/../src/Storages/StorageMergeTree.cpp:222:12
    #9 0x1cb2d65f in DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::QueryPlan&) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:1764:33
    #10 0x1cb2620e in DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::__1::optional<DB::Pipe>) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:1011:9
    #11 0x1cb25438 in DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:560:5
    #12 0x1cdc27bc in DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:262:38
    #13 0x1cdc3939 in DB::InterpreterSelectWithUnionQuery::execute() obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:329:5
    #14 0x1d0736d0 in DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) obj-x86_64-linux-gnu/../src/Interpreters/executeQuery.cpp:632:32
    #15 0x1d070ce9 in DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) obj-x86_64-linux-gnu/../src/Interpreters/executeQuery.cpp:947:30
    #16 0x1dc7c21c in DB::TCPHandler::runImpl() obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:316:24
    #17 0x1dc97cb5 in DB::TCPHandler::run() obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:1837:9
    #18 0x1ea679ab in Poco::Net::TCPServerConnection::start() obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerConnection.cpp:43:3
    #19 0x1ea67e44 in Poco::Net::TCPServerDispatcher::run() obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerDispatcher.cpp:115:20
    #20 0x1eb58366 in Poco::PooledThread::run() obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/ThreadPool.cpp:199:14
    #21 0x1eb55c2b in Poco::ThreadImpl::runnableEntry(void*) obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345:27
    #22 0x7fa0424a2608 in start_thread /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477:8
    #23 0x7fa0423c9292 in __clone /build/glibc-eX1tMB/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../src/Interpreters/ExpressionAnalyzer.cpp:555:19 in 
2021.10.25 22:13:09.193458 [ 43 ] {} <Trace> BaseDaemon: Received signal -3
2021.10.25 22:13:09.193658 [ 460 ] {} <Fatal> BaseDaemon: ########################################
2021.10.25 22:13:09.193736 [ 460 ] {} <Fatal> BaseDaemon: (version 21.11.1.8558, build id: 024681AF387E7B05A6FD27C407AE8067E84BF856) (from thread 109) (query_id: 13ae7423-1e08-428a-b9be-a1b2f51e5b3c) Received signal Unknown signal (-3)
2021.10.25 22:13:09.193781 [ 460 ] {} <Fatal> BaseDaemon: Sanitizer trap.
2021.10.25 22:13:09.193870 [ 460 ] {} <Fatal> BaseDaemon: Stack trace: 0xd33c8ca 0x1be75c11 0xd2fde26 0xd30fb59 0x1c7433cb 0x1c741a25 0x1c740e09 0x1c75d91f 0x1d7bc0c7 0x1d7bc4ea 0x1d89a9d3 0x1d83121a 0x1dacd8dd 0x1cb2d660 0x1cb2620f 0x1cb25439 0x1cdc27bd 0x1cdc393a 0x1d0736d1 0x1d070cea 0x1dc7c21d 0x1dc97cb6 0x1ea679ac 0x1ea67e45 0x1eb58367 0x1eb55c2c 0x7fa0424a2609 0x7fa0423c9293
2021.10.25 22:13:09.206170 [ 460 ] {} <Fatal> BaseDaemon: 0.1. inlined from ./obj-x86_64-linux-gnu/../src/Common/StackTrace.cpp:305: StackTrace::tryCapture()
2021.10.25 22:13:09.206198 [ 460 ] {} <Fatal> BaseDaemon: 0. ../src/Common/StackTrace.cpp:266: StackTrace::StackTrace() @ 0xd33c8ca in /workspace/clickhouse
2021.10.25 22:13:09.231514 [ 460 ] {} <Fatal> BaseDaemon: 1. ./obj-x86_64-linux-gnu/../base/daemon/BaseDaemon.cpp:400: sanitizerDeathCallback() @ 0x1be75c11 in /workspace/clickhouse
2021.10.25 22:13:09.420267 [ 153 ] {} <Trace> SystemLog (system.query_log): Flushing system log, 1117 entries to flush up to offset 569898
2021.10.25 22:13:09.475134 [ 153 ] {} <Debug> DiskLocal: Reserving 3.63 MiB on disk `default`, having unreserved 1.01 TiB.
2021.10.25 22:13:09.485723 [ 153 ] {} <Trace> system.query_log (00db6041-f907-4566-80db-6041f9077566): Renaming temporary part tmp_insert_202110_329_329_0 to 202110_329_329_0.
2021.10.25 22:13:09.486401 [ 153 ] {} <Trace> SystemLog (system.query_log): Flushed system log up to offset 569898
2021.10.25 22:13:09.758263 [ 158 ] {} <Debug> DiskLocal: Reserving 6.40 MiB on disk `default`, having unreserved 1.01 TiB.
2021.10.25 22:13:09.772834 [ 158 ] {} <Trace> system.text_log (77b1fdb0-6fe4-4560-b7b1-fdb06fe43560): Renaming temporary part tmp_insert_202110_332_332_0 to 202110_332_332_0.
2021.10.25 22:13:10.000132 [ 295 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 7.12 GiB, peak 7.52 GiB, will set to 7.27 GiB (RSS), difference: 152.09 MiB
2021.10.25 22:13:10.497119 [ 460 ] {} <Fatal> BaseDaemon: 2. __sanitizer::Die() @ 0xd2fde26 in /workspace/clickhouse
2021.10.25 22:13:10.644700 [ 102 ] {} <Trace> system.query_thread_log (ceb36874-beca-4863-8eb3-6874beca5863): Found 8 old parts to remove.
2021.10.25 22:13:10.644762 [ 102 ] {} <Debug> system.query_thread_log (ceb36874-beca-4863-8eb3-6874beca5863): Removing part from filesystem 202110_224_240_3
2021.10.25 22:13:10.647401 [ 102 ] {} <Debug> system.query_thread_log (ceb36874-beca-4863-8eb3-6874beca5863): Removing part from filesystem 202110_241_257_3
2021.10.25 22:13:10.649772 [ 102 ] {} <Debug> system.query_thread_log (ceb36874-beca-4863-8eb3-6874beca5863): Removing part from filesystem 202110_258_263_1
2021.10.25 22:13:10.651682 [ 102 ] {} <Debug> system.query_thread_log (ceb36874-beca-4863-8eb3-6874beca5863): Removing part from filesystem 202110_264_264_0
2021.10.25 22:13:10.651925 [ 102 ] {} <Debug> system.query_thread_log (ceb36874-beca-4863-8eb3-6874beca5863): Removing part from filesystem 202110_265_265_0
2021.10.25 22:13:10.652187 [ 102 ] {} <Debug> system.query_thread_log (ceb36874-beca-4863-8eb3-6874beca5863): Removing part from filesystem 202110_266_266_0
2021.10.25 22:13:10.652440 [ 102 ] {} <Debug> system.query_thread_log (ceb36874-beca-4863-8eb3-6874beca5863): Removing part from filesystem 202110_267_267_0
2021.10.25 22:13:10.652692 [ 102 ] {} <Debug> system.query_thread_log (ceb36874-beca-4863-8eb3-6874beca5863): Removing part from filesystem 202110_268_268_0
2021.10.25 22:13:11.000127 [ 295 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 7.27 GiB, peak 7.52 GiB, will set to 7.46 GiB (RSS), difference: 189.78 MiB
2021.10.25 22:13:11.454040 [ 105 ] {} <Trace> system.text_log (77b1fdb0-6fe4-4560-b7b1-fdb06fe43560): Found 7 old parts to remove.
2021.10.25 22:13:11.454094 [ 105 ] {} <Debug> system.text_log (77b1fdb0-6fe4-4560-b7b1-fdb06fe43560): Removing part from filesystem 202110_249_254_1
2021.10.25 22:13:11.455692 [ 105 ] {} <Debug> system.text_log (77b1fdb0-6fe4-4560-b7b1-fdb06fe43560): Removing part from filesystem 202110_255_259_1
2021.10.25 22:13:11.457124 [ 105 ] {} <Debug> system.text_log (77b1fdb0-6fe4-4560-b7b1-fdb06fe43560): Removing part from filesystem 202110_260_264_1
2021.10.25 22:13:11.458739 [ 105 ] {} <Debug> system.text_log (77b1fdb0-6fe4-4560-b7b1-fdb06fe43560): Removing part from filesystem 202110_265_265_0
2021.10.25 22:13:11.459014 [ 105 ] {} <Debug> system.text_log (77b1fdb0-6fe4-4560-b7b1-fdb06fe43560): Removing part from filesystem 202110_266_266_0
2021.10.25 22:13:11.459799 [ 105 ] {} <Debug> system.text_log (77b1fdb0-6fe4-4560-b7b1-fdb06fe43560): Removing part from filesystem 202110_267_267_0
2021.10.25 22:13:11.460591 [ 105 ] {} <Debug> system.text_log (77b1fdb0-6fe4-4560-b7b1-fdb06fe43560): Removing part from filesystem 202110_268_268_0
2021.10.25 22:13:11.748278 [ 460 ] {} <Fatal> BaseDaemon: 3. ? @ 0xd30fb59 in /workspace/clickhouse
2021.10.25 22:13:11.819459 [ 460 ] {} <Fatal> BaseDaemon: 4. ./obj-x86_64-linux-gnu/../src/Interpreters/ExpressionAnalyzer.cpp:0: DB::ExpressionAnalyzer::makeAggregateDescriptions(std::__1::shared_ptr<DB::ActionsDAG>&, std::__1::vector<DB::AggregateDescription, std::__1::allocator<DB::AggregateDescription> >&) @ 0x1c7433cb in /workspace/clickhouse
2021.10.25 22:13:11.886155 [ 460 ] {} <Fatal> BaseDaemon: 5.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/vector:664: std::__1::vector<DB::AggregateDescription, std::__1::allocator<DB::AggregateDescription> >::empty() const
2021.10.25 22:13:11.886182 [ 460 ] {} <Fatal> BaseDaemon: 5. ../src/Interpreters/ExpressionAnalyzer.cpp:326: DB::ExpressionAnalyzer::analyzeAggregation(std::__1::shared_ptr<DB::ActionsDAG>&) @ 0x1c741a25 in /workspace/clickhouse
2021.10.25 22:13:11.951735 [ 460 ] {} <Fatal> BaseDaemon: 6. ./obj-x86_64-linux-gnu/../src/Interpreters/ExpressionAnalyzer.cpp:0: DB::ExpressionAnalyzer::ExpressionAnalyzer(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::TreeRewriterResult const> const&, std::__1::shared_ptr<DB::Context const>, unsigned long, bool, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, DB::SubqueryForSet, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, DB::SubqueryForSet> > >, std::__1::unordered_map<DB::PreparedSetKey, std::__1::shared_ptr<DB::Set>, DB::PreparedSetKey::Hash, std::__1::equal_to<DB::PreparedSetKey>, std::__1::allocator<std::__1::pair<DB::PreparedSetKey const, std::__1::shared_ptr<DB::Set> > > >) @ 0x1c740e09 in /workspace/clickhouse
2021.10.25 22:13:12.000125 [ 295 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 7.46 GiB, peak 7.52 GiB, will set to 7.48 GiB (RSS), difference: 23.32 MiB
2021.10.25 22:13:12.037715 [ 460 ] {} <Fatal> BaseDaemon: 7. ./obj-x86_64-linux-gnu/../src/Interpreters/ExpressionAnalyzer.h:101: DB::ExpressionAnalyzer::ExpressionAnalyzer(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::TreeRewriterResult const> const&, std::__1::shared_ptr<DB::Context const>) @ 0x1c75d91f in /workspace/clickhouse
2021.10.25 22:13:12.247617 [ 460 ] {} <Fatal> BaseDaemon: 8.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:1229: __compressed_pair_elem<nullptr_t, void>
2021.10.25 22:13:12.247664 [ 460 ] {} <Fatal> BaseDaemon: 8.2. inlined from ../contrib/libcxx/include/memory:1314: __compressed_pair<nullptr_t, std::__1::__default_init_tag>
2021.10.25 22:13:12.247716 [ 460 ] {} <Fatal> BaseDaemon: 8.3. inlined from ../contrib/libcxx/include/vector:438: __vector_base
2021.10.25 22:13:12.247772 [ 460 ] {} <Fatal> BaseDaemon: 8.4. inlined from ../contrib/libcxx/include/vector:497: vector
2021.10.25 22:13:12.247819 [ 460 ] {} <Fatal> BaseDaemon: 8. ../src/Storages/MergeTree/KeyCondition.cpp:439: DB::KeyCondition::getBlockWithConstants(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::TreeRewriterResult const> const&, std::__1::shared_ptr<DB::Context const>) @ 0x1d7bc0c7 in /workspace/clickhouse
2021.10.25 22:13:12.458532 [ 460 ] {} <Fatal> BaseDaemon: 9.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2844: std::__1::shared_ptr<DB::TreeRewriterResult const>::operator->() const
2021.10.25 22:13:12.458616 [ 460 ] {} <Fatal> BaseDaemon: 9. ../src/Storages/MergeTree/KeyCondition.cpp:480: DB::KeyCondition::KeyCondition(DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::ExpressionActions> const&, bool, bool) @ 0x1d7bc4ea in /workspace/clickhouse
2021.10.25 22:13:12.637171 [ 460 ] {} <Fatal> BaseDaemon: 10. ./obj-x86_64-linux-gnu/../src/Storages/MergeTree/PartitionPruner.h:29: DB::PartitionPruner::PartitionPruner(std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>, bool) @ 0x1d89a9d3 in /workspace/clickhouse
2021.10.25 22:13:12.815038 [ 460 ] {} <Fatal> BaseDaemon: 11.1. inlined from ./obj-x86_64-linux-gnu/../src/Storages/MergeTree/PartitionPruner.h:37: DB::PartitionPruner::isUseless() const
2021.10.25 22:13:12.815090 [ 460 ] {} <Fatal> BaseDaemon: 11. ../src/Storages/MergeTree/MergeTreeData.cpp:849: DB::MergeTreeData::totalRowsByPartitionPredicateImpl(DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const> > > const&) const @ 0x1d83121a in /workspace/clickhouse
2021.10.25 22:13:12.889823 [ 460 ] {} <Fatal> BaseDaemon: 12. ./obj-x86_64-linux-gnu/../src/Storages/StorageMergeTree.cpp:0: DB::StorageMergeTree::totalRowsByPartitionPredicate(DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>) const @ 0x1dacd8dd in /workspace/clickhouse
2021.10.25 22:13:13.000121 [ 295 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 7.48 GiB, peak 7.52 GiB, will set to 7.52 GiB (RSS), difference: 41.47 MiB
2021.10.25 22:13:13.010849 [ 460 ] {} <Fatal> BaseDaemon: 13. ./obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:0: DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::QueryPlan&) @ 0x1cb2d660 in /workspace/clickhouse
2021.10.25 22:13:13.144687 [ 460 ] {} <Fatal> BaseDaemon: 14. ./obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:1013: DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::__1::optional<DB::Pipe>) @ 0x1cb2620f in /workspace/clickhouse
2021.10.25 22:13:13.277758 [ 460 ] {} <Fatal> BaseDaemon: 15. ./obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:0: DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) @ 0x1cb25439 in /workspace/clickhouse
2021.10.25 22:13:13.319452 [ 460 ] {} <Fatal> BaseDaemon: 16. ./obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:0: DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) @ 0x1cdc27bd in /workspace/clickhouse
2021.10.25 22:13:13.361209 [ 460 ] {} <Fatal> BaseDaemon: 17. ./obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:0: DB::InterpreterSelectWithUnionQuery::execute() @ 0x1cdc393a in /workspace/clickhouse
2021.10.25 22:13:13.418831 [ 460 ] {} <Fatal> BaseDaemon: 18. ./obj-x86_64-linux-gnu/../src/Interpreters/executeQuery.cpp:0: DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x1d0736d1 in /workspace/clickhouse
2021.10.25 22:13:13.482329 [ 460 ] {} <Fatal> BaseDaemon: 19. ./obj-x86_64-linux-gnu/../src/Interpreters/executeQuery.cpp:947: DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x1d070cea in /workspace/clickhouse
2021.10.25 22:13:13.531619 [ 460 ] {} <Fatal> BaseDaemon: 20. ./obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:316: DB::TCPHandler::runImpl() @ 0x1dc7c21d in /workspace/clickhouse
2021.10.25 22:13:13.596949 [ 460 ] {} <Fatal> BaseDaemon: 21. ./obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:1839: DB::TCPHandler::run() @ 0x1dc97cb6 in /workspace/clickhouse
2021.10.25 22:13:13.601560 [ 460 ] {} <Fatal> BaseDaemon: 22. ./obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x1ea679ac in /workspace/clickhouse
2021.10.25 22:13:13.609688 [ 460 ] {} <Fatal> BaseDaemon: 23.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:1397: std::__1::default_delete<Poco::Net::TCPServerConnection>::operator()(Poco::Net::TCPServerConnection*) const
2021.10.25 22:13:13.609729 [ 460 ] {} <Fatal> BaseDaemon: 23.2. inlined from ../contrib/libcxx/include/memory:1658: std::__1::unique_ptr<Poco::Net::TCPServerConnection, std::__1::default_delete<Poco::Net::TCPServerConnection> >::reset(Poco::Net::TCPServerConnection*)
2021.10.25 22:13:13.609779 [ 460 ] {} <Fatal> BaseDaemon: 23.3. inlined from ../contrib/libcxx/include/memory:1612: ~unique_ptr
2021.10.25 22:13:13.609834 [ 460 ] {} <Fatal> BaseDaemon: 23. ../contrib/poco/Net/src/TCPServerDispatcher.cpp:116: Poco::Net::TCPServerDispatcher::run() @ 0x1ea67e45 in /workspace/clickhouse
2021.10.25 22:13:13.618224 [ 460 ] {} <Fatal> BaseDaemon: 24. ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/ThreadPool.cpp:213: Poco::PooledThread::run() @ 0x1eb58367 in /workspace/clickhouse
2021.10.25 22:13:13.626447 [ 460 ] {} <Fatal> BaseDaemon: 25.1. inlined from ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/include/Poco/SharedPtr.h:156: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable> >::assign(Poco::Runnable*)
2021.10.25 22:13:13.626486 [ 460 ] {} <Fatal> BaseDaemon: 25.2. inlined from ../contrib/poco/Foundation/include/Poco/SharedPtr.h:208: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable> >::operator=(Poco::Runnable*)
2021.10.25 22:13:13.626527 [ 460 ] {} <Fatal> BaseDaemon: 25. ../contrib/poco/Foundation/src/Thread_POSIX.cpp:360: Poco::ThreadImpl::runnableEntry(void*) @ 0x1eb55c2c in /workspace/clickhouse
2021.10.25 22:13:13.626641 [ 460 ] {} <Fatal> BaseDaemon: 26. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
2021.10.25 22:13:13.626735 [ 460 ] {} <Fatal> BaseDaemon: 27. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.10.25 22:13:13.996058 [ 460 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: CE366939D8563F8D8C200C0CCDEB5A58. There is no information about the reference checksum.
```

**Comment by Algunenano** [comment]
No reproducer and no recent cases.
