### ISSUE TITLE
Crash in window function with LowCardinality datatype

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#31114]
**Describe what's wrong**

ClickHouse crashes if you execute `max(id) OVER (PARTITION BY id)` over LowCardinality column

**Does it reproduce on recent release?**

Yes.
ClickHouse version 21.11

**How to reproduce**

```
SELECT max(id) OVER (PARTITION BY id) AS id
FROM
(
    SELECT materialize('aaaa') AS id
    FROM numbers_mt(1000000)
)
FORMAT `Null`

Ok.

0 rows in set. Elapsed: 0.144 sec. Processed 1.00 million rows, 8.00 MB (6.95 million rows/s., 55.58 MB/s.)

SELECT max(id) OVER (PARTITION BY id) AS aid
FROM
(
    SELECT materialize(toLowCardinality('aaaa')) AS id
    FROM numbers_mt(1000000)
)
FORMAT `Null`

[ 14776 ] <Fatal> BaseDaemon: ########################################
[ 14776 ] <Fatal> BaseDaemon: (version 21.11.1.8526, build id: 33B572DD4B9C2BE5F65F58755B19729DE40A4869) (from thread 14740) (query_id: d5299144-24c8-4d91-a122-09065f33bbaa) Received signal Segmentation fault (11)
[ 14776 ] <Fatal> BaseDaemon: Address: 0x1 Access: read. Address not mapped to object.
[ 14776 ] <Fatal> BaseDaemon: Stack trace: 0x9b389b0 0x1323afd3 0x1323b45e 0x1324051f 0x13070e9b 0x1306ce51 0x13072e25 0x9b80c57 0x9b8465d 0x7f1fe3050609 0x7f1fe2f4a293
[ 14776 ] <Fatal> BaseDaemon: 2. memcpy @ 0x9b389b0 in /usr/bin/clickhouse
[ 14776 ] <Fatal> BaseDaemon: 3. DB::WindowTransform::updateAggregationState() @ 0x1323afd3 in /usr/bin/clickhouse
[ 14776 ] <Fatal> BaseDaemon: 4. DB::WindowTransform::appendChunk(DB::Chunk&) @ 0x1323b45e in /usr/bin/clickhouse
[ 14776 ] <Fatal> BaseDaemon: 5. DB::WindowTransform::work() @ 0x1324051f in /usr/bin/clickhouse
[ 14776 ] <Fatal> BaseDaemon: 6. ? @ 0x13070e9b in /usr/bin/clickhouse
[ 14776 ] <Fatal> BaseDaemon: 7. DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0x1306ce51 in /usr/bin/clickhouse
[ 14776 ] <Fatal> BaseDaemon: 8. ? @ 0x13072e25 in /usr/bin/clickhouse
[ 14776 ] <Fatal> BaseDaemon: 9. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x9b80c57 in /usr/bin/clickhouse
[ 14776 ] <Fatal> BaseDaemon: 10. ? @ 0x9b8465d in /usr/bin/clickhouse
[ 14776 ] <Fatal> BaseDaemon: 11. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
[ 14776 ] <Fatal> BaseDaemon: 12. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
[ 14776 ] <Fatal> BaseDaemon: Calculated checksum of the binary: 8E1781B29E0174AC66B92E409A0E916E. There is no information about the reference checksum.
```

**Expected behavior**

Both queries works

**Comment by nikitamikhaylov** [comment]
Better stack:

```
Thread 73 "QueryPipelineEx" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff53de9700 (LWP 3168369)]
inline_memcpy (size=86175080, dst_=<optimized out>, src_=<optimized out>) at /home/jakalletti/ClickHouse/ClickHouse/base/glibc-compatibility/memcpy/memcpy.h:188
188                     c0 = _mm_loadu_si128(reinterpret_cast<const __m128i*>(src) + 0);
(gdb) where
#0  inline_memcpy (size=86175080, dst_=<optimized out>, src_=<optimized out>) at /home/jakalletti/ClickHouse/ClickHouse/base/glibc-compatibility/memcpy/memcpy.h:188
#1  memcpy(void * __restrict__, const void * __restrict__, size_t) (dst=0x7ffee4b64000, src=<optimized out>, size=<optimized out>) at /home/jakalletti/ClickHouse/ClickHouse/base/glibc-compatibility/memcpy/memcpy.cpp:5
#2  0x0000000011ad1033 in DB::WindowTransform::updateAggregationState (this=this@entry=0x7ffeee2d9018) at /home/jakalletti/ClickHouse/ClickHouse/src/Processors/Transforms/WindowTransform.cpp:963
#3  0x0000000011ad14be in DB::WindowTransform::appendChunk (this=0x7ffeee2d9018, chunk=...) at /home/jakalletti/ClickHouse/ClickHouse/src/Processors/Transforms/WindowTransform.cpp:1164
#4  0x0000000011ad5b7f in DB::WindowTransform::work (this=0x7ffeee2d9018) at /home/jakalletti/ClickHouse/ClickHouse/src/Processors/Transforms/WindowTransform.cpp:1399
#5  0x00000000119665db in DB::executeJob (processor=0x7ffeee2d9018) at /home/jakalletti/ClickHouse/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:88
#6  DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0::operator()() const (this=0x7fff60a6b1f0) at /home/jakalletti/ClickHouse/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:105
#7  std::__1::__invoke<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&> (__f=...) at /home/jakalletti/ClickHouse/ClickHouse/contrib/libcxx/include/type_traits:3676
#8  std::__1::__invoke_void_return_wrapper<void>::__call<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&) (__args=...)
    at /home/jakalletti/ClickHouse/ClickHouse/contrib/libcxx/include/__functional_base:348
#9  std::__1::__function::__default_alloc_func<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0, void ()>::operator()() (this=0x7fff60a6b1f0)
    at /home/jakalletti/ClickHouse/ClickHouse/contrib/libcxx/include/functional:1608
#10 std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0, void ()> >(std::__1::__function::__policy_storage const*)
    (__buf=0x7fff60a6b1f0) at /home/jakalletti/ClickHouse/ClickHouse/contrib/libcxx/include/functional:2089
#11 0x0000000011964c11 in std::__1::__function::__policy_func<void ()>::operator()() const (this=0x7ffee4b64070) at /home/jakalletti/ClickHouse/ClickHouse/contrib/libcxx/include/functional:2221
#12 std::__1::function<void ()>::operator()() const (this=0x7ffee4b64070) at /home/jakalletti/ClickHouse/ClickHouse/contrib/libcxx/include/functional:2560
#13 DB::PipelineExecutor::executeStepImpl (this=this@entry=0x7ffeee2a78d8, thread_num=<optimized out>, thread_num@entry=0, num_threads=num_threads@entry=1, yield_flag=yield_flag@entry=0x0)
    at /home/jakalletti/ClickHouse/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:599
#14 0x000000001196374a in DB::PipelineExecutor::executeSingleThread (this=0x7ffeee2a78d8, thread_num=0, num_threads=1) at /home/jakalletti/ClickHouse/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:487
#15 DB::PipelineExecutor::executeImpl (this=0x7ffeee2a78d8, num_threads=1) at /home/jakalletti/ClickHouse/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:826
#16 0x00000000119631b9 in DB::PipelineExecutor::execute (this=0x7ffeee2a78d8, num_threads=1) at /home/jakalletti/ClickHouse/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:407
#17 0x000000001196e24a in DB::threadFunction (data=..., thread_group=..., num_threads=1) at /home/jakalletti/ClickHouse/ClickHouse/src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:85
#18 DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0::operator()() const (this=<optimized out>) at /home/jakalletti/ClickHouse/ClickHouse/src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:112
#19 std::__1::__invoke_constexpr<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&> (__f=...) at /home/jakalletti/ClickHouse/ClickHouse/contrib/libcxx/include/type_traits:3682
#20 std::__1::__apply_tuple_impl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>) (__f=..., __t=...) at /home/jakalletti/ClickHouse/ClickHouse/contrib/libcxx/include/tuple:1415
#21 std::__1::apply<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&) (__f=..., __t=...)
    at /home/jakalletti/ClickHouse/ClickHouse/contrib/libcxx/include/tuple:1424
#22 ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::{lambda()#1}::operator()() (
    this=<optimized out>) at /home/jakalletti/ClickHouse/ClickHouse/src/Common/ThreadPool.h:188
#23 std::__1::__invoke<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::{lambda()#1}&>
    (__f=...) at /home/jakalletti/ClickHouse/ClickHouse/contrib/libcxx/include/type_traits:3676
#24 std::__1::__invoke_void_return_wrapper<void>::__call<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::{lambda()#1}&>(ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::{lambda()#1}&) (__args=...) at /home/jakalletti/ClickHouse/ClickHouse/contrib/libcxx/include/__functional_base:348
#25 std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::{lambda()#1}, void ()>::operator()() (this=<optimized out>) at /home/jakalletti/ClickHouse/ClickHouse/contrib/libcxx/include/functional:1608
#26 std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::{lambda()#1}, void ()> >(std::__1::__function::__policy_storage const*) (__buf=<optimized out>)
    at /home/jakalletti/ClickHouse/ClickHouse/contrib/libcxx/include/functional:2089
#27 0x000000000990b98a in std::__1::__function::__policy_func<void ()>::operator()() const (this=0x7fff53de0a10) at /home/jakalletti/ClickHouse/ClickHouse/contrib/libcxx/include/functional:2221
#28 std::__1::function<void ()>::operator()() const (this=0x7fff53de0a10) at /home/jakalletti/ClickHouse/ClickHouse/contrib/libcxx/include/functional:2560
#29 ThreadPoolImpl<std::__1::thread>::worker (this=0x7ffff703e900, thread_it=...) at /home/jakalletti/ClickHouse/ClickHouse/src/Common/ThreadPool.cpp:274
#30 0x000000000990dd6e in ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::{lambda()#2}::operator()() const (this=0x7ffff7097308)
    at /home/jakalletti/ClickHouse/ClickHouse/src/Common/ThreadPool.cpp:139
#31 std::__1::__invoke<ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::{lambda()#2}> (__f=...)
    at /home/jakalletti/ClickHouse/ClickHouse/contrib/libcxx/include/type_traits:3676
#32 std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::{lambda()#2}>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::{lambda()#2}>&, std::__1::__tuple_indices<>) (__t=...) at /home/jakalletti/ClickHouse/ClickHouse/contrib/libcxx/include/thread:280
#33 std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::{lambda()#2}> >(void*) (__vp=0x7ffff7097300) at /home/jakalletti/ClickHouse/ClickHouse/contrib/libcxx/include/thread:291
#34 0x00007ffff7fa2609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#35 0x00007ffff7e9c293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by UnamedRus** [comment]
It reproduces even without PARTITION BY

```
SELECT max(id) OVER () AS aid
FROM
(
    SELECT materialize(toLowCardinality('aaaa')) AS id
    FROM numbers_mt(1000000)
)
FORMAT `Null`

[] 2021.11.18 20:39:22.991678 [ 1148 ] <Fatal> BaseDaemon: ########################################
[] 2021.11.18 20:39:22.991955 [ 1148 ] <Fatal> BaseDaemon: (version 21.12.1.8661 (official build), build id: DD11349CD1691DF51FCA67FBEA8047ECCFAC9775) (from thread 15719) (query_id: 51bc3214-e8ca-4655-b738-c6899522c4d7) Received signal Segmentation fault (11)
[] 2021.11.18 20:39:22.992025 [ 1148 ] <Fatal> BaseDaemon: Address: 0x1 Access: read. Address not mapped to object.
[] 2021.11.18 20:39:22.992082 [ 1148 ] <Fatal> BaseDaemon: Stack trace: 0x9b934f0 0x13359433 0x133598be 0x1335e97f 0x1319059b 0x1318c551 0x13192525 0x9bdb757 0x9bdf15d 0x7f379c9d7609 0x7f379c8d1293
[] 2021.11.18 20:39:22.992166 [ 1148 ] <Fatal> BaseDaemon: 2. memcpy @ 0x9b934f0 in /usr/bin/clickhouse
[] 2021.11.18 20:39:22.993446 [ 1148 ] <Fatal> BaseDaemon: 3. DB::WindowTransform::updateAggregationState() @ 0x13359433 in /usr/bin/clickhouse
[] 2021.11.18 20:39:22.993583 [ 1148 ] <Fatal> BaseDaemon: 4. DB::WindowTransform::appendChunk(DB::Chunk&) @ 0x133598be in /usr/bin/clickhouse
[] 2021.11.18 20:39:22.993666 [ 1148 ] <Fatal> BaseDaemon: 5. DB::WindowTransform::work() @ 0x1335e97f in /usr/bin/clickhouse
[] 2021.11.18 20:39:22.993717 [ 1148 ] <Fatal> BaseDaemon: 6. ? @ 0x1319059b in /usr/bin/clickhouse
[] 2021.11.18 20:39:22.993780 [ 1148 ] <Fatal> BaseDaemon: 7. DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0x1318c551 in /usr/bin/clickhouse
[] 2021.11.18 20:39:22.993904 [ 1148 ] <Fatal> BaseDaemon: 8. ? @ 0x13192525 in /usr/bin/clickhouse
[] 2021.11.18 20:39:22.993950 [ 1148 ] <Fatal> BaseDaemon: 9. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x9bdb757 in /usr/bin/clickhouse
[] 2021.11.18 20:39:22.994001 [ 1148 ] <Fatal> BaseDaemon: 10. ? @ 0x9bdf15d in /usr/bin/clickhouse
[] 2021.11.18 20:39:22.994063 [ 1148 ] <Fatal> BaseDaemon: 11. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
[] 2021.11.18 20:39:22.994123 [ 1148 ] <Fatal> BaseDaemon: 12. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
[] 2021.11.18 20:39:23.374933 [ 1148 ] <Fatal> BaseDaemon: Checksum of the binary: E7A07B6916581A75CFDF5EF8FCC72C05, integrity check passed.
Error on processing query: Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from localhost:9000. (ATTEMPT_TO_READ_AFTER_EOF) (version 21.12.1.8661 (official build))

```

**Comment by UnamedRus** [comment]
Even if it not crash, it produces wrong result:

```
SELECT countIf(CAST(sym, 'String') = 'Red') OVER () AS res
FROM
(
    SELECT CAST(CAST(number % 5, 'Enum8(\'Red\' = 0, \'Blue\' = 1, \'Yellow\' = 2, \'Black\' = 3, \'White\' = 4)'), 'LowCardinality(String)') AS sym
    FROM numbers(10)
)

Query id: fcde0e4b-efc0-4f09-9b86-20bb442b3a31

┌─res─┐
│   2 │
│   2 │
│   2 │
│   2 │
│   2 │
│   2 │
│   2 │
│   2 │
│   2 │
│   2 │
└─────┘


SELECT countIf(sym = 'Red') OVER () AS res
FROM
(
    SELECT CAST(CAST(number % 5, 'Enum8(\'Red\' = 0, \'Blue\' = 1, \'Yellow\' = 2, \'Black\' = 3, \'White\' = 4)'), 'LowCardinality(String)') AS sym
    FROM numbers(10)
)

Query id: 601cf0ba-5c7c-42db-a44a-ebafc181cb03

┌─res─┐
│   5 │
│   5 │
│   5 │
│   5 │
│   5 │
│   5 │
│   5 │
│   5 │
│   5 │
│   5 │
└─────┘
```
