### ISSUE TITLE
AggregationCommon.h:97:35: runtime error: downcast of address which does not point to an object of type ColumnVectorHelper

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#32474]
https://s3.amazonaws.com/clickhouse-test-reports/0/5b06e30ea2cb7d5abdfec2ae1bbaba0603aed09c/fuzzer_astfuzzerubsan,actions//report.html

```
2021.12.09 19:08:59.387460 [ 154 ] {fc5c622d-bb4a-4fb4-8e80-bc9dbc9a20c6} <Debug> executeQuery: (from [::ffff:127.0.0.1]:60978) SELECT 2., * FROM (SELECT 1024, 256 INTERSECT SELECT 100 AND inf, 256)
2021.12.09 19:08:59.387670 [ 154 ] {fc5c622d-bb4a-4fb4-8e80-bc9dbc9a20c6} <Trace> ContextAccess (default): Access granted: SELECT(dummy) ON system.one
2021.12.09 19:08:59.387839 [ 154 ] {fc5c622d-bb4a-4fb4-8e80-bc9dbc9a20c6} <Trace> ContextAccess (default): Access granted: SELECT(dummy) ON system.one
2021.12.09 19:08:59.388012 [ 154 ] {fc5c622d-bb4a-4fb4-8e80-bc9dbc9a20c6} <Trace> ContextAccess (default): Access granted: SELECT(dummy) ON system.one
2021.12.09 19:08:59.388167 [ 154 ] {fc5c622d-bb4a-4fb4-8e80-bc9dbc9a20c6} <Trace> ContextAccess (default): Access granted: SELECT(dummy) ON system.one
2021.12.09 19:08:59.388334 [ 154 ] {fc5c622d-bb4a-4fb4-8e80-bc9dbc9a20c6} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2021.12.09 19:08:59.388407 [ 154 ] {fc5c622d-bb4a-4fb4-8e80-bc9dbc9a20c6} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2021.12.09 19:08:59.388494 [ 154 ] {fc5c622d-bb4a-4fb4-8e80-bc9dbc9a20c6} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
../src/Interpreters/AggregationCommon.h:97:35: runtime error: downcast of address 0x7f848038f4a0 which does not point to an object of type 'const DB::ColumnVectorHelper'
0x7f848038f4a0: note: object is of type 'DB::ColumnConst'
 00 00 00 00  10 e0 58 09 00 00 00 00  01 00 00 00 00 00 00 00  80 0b a5 f2 83 7f 00 00  01 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'DB::ColumnConst'
2021.12.09 19:09:00.386462 [ 179 ] {} <Trace> SystemLog (system.asynchronous_metric_log): Flushing system log, 1442 entries to flush up to offset 307464
2021.12.09 19:09:00.388084 [ 179 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 88.39 GiB.
2021.12.09 19:09:00.388855 [ 179 ] {} <Trace> system.asynchronous_metric_log (746a6d9d-b6b5-4d4e-b46a-6d9db6b59d4e): Renaming temporary part tmp_insert_202112_213_213_0 to 202112_213_213_0.
2021.12.09 19:09:00.389025 [ 282 ] {} <Debug> system.asynchronous_metric_log (746a6d9d-b6b5-4d4e-b46a-6d9db6b59d4e) (MergerMutator): Selected 2 parts from 202112_1_208_77 to 202112_209_209_0
2021.12.09 19:09:00.389061 [ 179 ] {} <Trace> SystemLog (system.asynchronous_metric_log): Flushed system log up to offset 307464
2021.12.09 19:09:00.389084 [ 282 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 88.39 GiB.
2021.12.09 19:09:00.389229 [ 114 ] {746a6d9d-b6b5-4d4e-b46a-6d9db6b59d4e::202112_1_209_78} <Debug> MergeTask::PrepareStage: Merging 2 parts: from 202112_1_208_77 to 202112_209_209_0 into Compact
2021.12.09 19:09:00.389341 [ 114 ] {746a6d9d-b6b5-4d4e-b46a-6d9db6b59d4e::202112_1_209_78} <Debug> MergeTask::PrepareStage: Selected MergeAlgorithm: Horizontal
2021.12.09 19:09:00.389440 [ 114 ] {746a6d9d-b6b5-4d4e-b46a-6d9db6b59d4e::202112_1_209_78} <Debug> MergeTreeSequentialSource: Reading 36 marks from part 202112_1_208_77, total 300254 rows starting from the beginning of the part
2021.12.09 19:09:00.389642 [ 114 ] {746a6d9d-b6b5-4d4e-b46a-6d9db6b59d4e::202112_1_209_78} <Debug> MergeTreeSequentialSource: Reading 2 marks from part 202112_209_209_0, total 1442 rows starting from the beginning of the part
2021.12.09 19:09:00.418689 [ 115 ] {746a6d9d-b6b5-4d4e-b46a-6d9db6b59d4e::202112_1_209_78} <Debug> MergeTask::MergeProjectionsStage: Merge sorted 301696 rows, containing 5 columns (5 merged, 0 gathered) in 0.029498074 sec., 10227650.795099368 rows/sec., 230.88 MiB/sec.
2021.12.09 19:09:00.420247 [ 115 ] {746a6d9d-b6b5-4d4e-b46a-6d9db6b59d4e::202112_1_209_78} <Trace> system.asynchronous_metric_log (746a6d9d-b6b5-4d4e-b46a-6d9db6b59d4e): Renaming temporary part tmp_merge_202112_1_209_78 to 202112_1_209_78.
2021.12.09 19:09:00.420355 [ 115 ] {746a6d9d-b6b5-4d4e-b46a-6d9db6b59d4e::202112_1_209_78} <Trace> system.asynchronous_metric_log (746a6d9d-b6b5-4d4e-b46a-6d9db6b59d4e) (MergerMutator): Merged 2 parts: from 202112_1_208_77 to 202112_209_209_0
2021.12.09 19:09:00.420443 [ 115 ] {} <Debug> MemoryTracker: Peak memory usage Mutate/Merge: 4.00 MiB.
    #0 0x1ad98ebf in void DB::fillFixedBatch<unsigned short, wide::integer<128ul, unsigned int> >(unsigned long, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> > const&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, DB::PODArray<wide::integer<128ul, unsigned int>, 4096ul, Allocator<false, false>, 15ul, 16ul>&, unsigned long&) (/workspace/clickhouse+0x1ad98ebf)
    #1 0x1ad981d1 in void DB::packFixedBatch<wide::integer<128ul, unsigned int> >(unsigned long, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> > const&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, DB::PODArray<wide::integer<128ul, unsigned int>, 4096ul, Allocator<false, false>, 15ul, 16ul>&) (/workspace/clickhouse+0x1ad981d1)
    #2 0x1e4828e0 in DB::ColumnsHashing::HashMethodKeysFixed<wide::integer<128ul, unsigned int>, wide::integer<128ul, unsigned int>, void, false, false, true, false>::HashMethodKeysFixed(std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> > const&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, std::__1::shared_ptr<DB::ColumnsHashing::HashMethodContext> const&) obj-x86_64-linux-gnu/../src/Common/ColumnsHashing.h:524:13
    #3 0x1f846161 in void DB::IntersectOrExceptTransform::addToSet<DB::SetMethodKeysFixed<HashSetTable<wide::integer<128ul, unsigned int>, HashTableCell<wide::integer<128ul, unsigned int>, UInt128HashCRC32, HashTableNoState>, UInt128HashCRC32, HashTableGrower<8ul>, Allocator<true, true> >, false> >(DB::SetMethodKeysFixed<HashSetTable<wide::integer<128ul, unsigned int>, HashTableCell<wide::integer<128ul, unsigned int>, UInt128HashCRC32, HashTableNoState>, UInt128HashCRC32, HashTableGrower<8ul>, Allocator<true, true> >, false>&, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> > const&, unsigned long, DB::SetVariantsTemplate<DB::NonClearableSet>&) const obj-x86_64-linux-gnu/../src/Processors/Transforms/IntersectOrExceptTransform.cpp:97:28
    #4 0x1f842ca9 in DB::IntersectOrExceptTransform::accumulate(DB::Chunk) obj-x86_64-linux-gnu/../src/Processors/Transforms/IntersectOrExceptTransform.cpp:148:13
    #5 0x1f8423ed in DB::IntersectOrExceptTransform::work() obj-x86_64-linux-gnu/../src/Processors/Transforms/IntersectOrExceptTransform.cpp:82:9
    #6 0x1f404558 in DB::executeJob(DB::IProcessor*) obj-x86_64-linux-gnu/../src/Processors/Executors/ExecutionThreadContext.cpp:45:20
    #7 0x1f4043e7 in DB::ExecutionThreadContext::executeTask() obj-x86_64-linux-gnu/../src/Processors/Executors/ExecutionThreadContext.cpp:63:9
    #8 0x1f3f66c0 in DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:213:26
    #9 0x1f3f7947 in DB::PipelineExecutor::executeSingleThread(unsigned long) obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:178:5
    #10 0x1f3f7947 in DB::PipelineExecutor::executeImpl(unsigned long)::$_1::operator()() const obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:311:21
    #11 0x1f3f7947 in decltype(std::__1::forward<DB::PipelineExecutor::executeImpl(unsigned long)::$_1&>(fp)()) std::__1::__invoke_constexpr<DB::PipelineExecutor::executeImpl(unsigned long)::$_1&>(DB::PipelineExecutor::executeImpl(unsigned long)::$_1&) obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3682:1
    #12 0x1f3f7822 in decltype(auto) std::__1::__apply_tuple_impl<DB::PipelineExecutor::executeImpl(unsigned long)::$_1&, std::__1::tuple<>&>(DB::PipelineExecutor::executeImpl(unsigned long)::$_1&, std::__1::tuple<>&, std::__1::__tuple_indices<>) obj-x86_64-linux-gnu/../contrib/libcxx/include/tuple:1415:1
    #13 0x1f3f7822 in decltype(auto) std::__1::apply<DB::PipelineExecutor::executeImpl(unsigned long)::$_1&, std::__1::tuple<>&>(DB::PipelineExecutor::executeImpl(unsigned long)::$_1&, std::__1::tuple<>&) obj-x86_64-linux-gnu/../contrib/libcxx/include/tuple:1424:1
    #14 0x1f3f7822 in ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PipelineExecutor::executeImpl(unsigned long)::$_1>(DB::PipelineExecutor::executeImpl(unsigned long)::$_1&&)::'lambda'()::operator()() obj-x86_64-linux-gnu/../src/Common/ThreadPool.h:188:13
    #15 0x1f3f7822 in decltype(std::__1::forward<DB::PipelineExecutor::executeImpl(unsigned long)::$_1>(fp)()) std::__1::__invoke<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PipelineExecutor::executeImpl(unsigned long)::$_1>(DB::PipelineExecutor::executeImpl(unsigned long)::$_1&&)::'lambda'()&>(DB::PipelineExecutor::executeImpl(unsigned long)::$_1&&) obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3676:1
    #16 0xde8bd19 in std::__1::__function::__policy_func<void ()>::operator()() const obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2221:16
    #17 0xde8bd19 in std::__1::function<void ()>::operator()() const obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2560:12
    #18 0xde8bd19 in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) obj-x86_64-linux-gnu/../src/Common/ThreadPool.cpp:274:17
    #19 0xde8e721 in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()::operator()() const obj-x86_64-linux-gnu/../src/Common/ThreadPool.cpp:139:73
    #20 0xde8e721 in decltype(std::__1::forward<void>(fp)()) std::__1::__invoke<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&) obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3676:1
    #21 0xde8e721 in void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>&, std::__1::__tuple_indices<>) obj-x86_64-linux-gnu/../contrib/libcxx/include/thread:280:5
    #22 0xde8e721 in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) obj-x86_64-linux-gnu/../contrib/libcxx/include/thread:291:5
    #23 0x7f85ec463608 in start_thread /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477:8
    #24 0x7f85ec38a292 in __clone /build/glibc-eX1tMB/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../src/Interpreters/AggregationCommon.h:97:35 in 
2021.12.09 19:09:00.694332 [ 107 ] {} <Trace> BaseDaemon: Received signal -3
2021.12.09 19:09:00.694461 [ 352 ] {} <Fatal> BaseDaemon: ########################################
2021.12.09 19:09:00.694534 [ 352 ] {} <Fatal> BaseDaemon: (version 21.13.1.44, build id: E2243E56E70863BB) (from thread 328) (query_id: fc5c622d-bb4a-4fb4-8e80-bc9dbc9a20c6) Received signal Unknown signal (-3)
2021.12.09 19:09:00.694559 [ 352 ] {} <Fatal> BaseDaemon: Sanitizer trap.
2021.12.09 19:09:00.694614 [ 352 ] {} <Fatal> BaseDaemon: Stack trace: 0xde5ceaa 0x1d37d991 0xde1d8d6 0xde2f619 0x1ad98ec0 0x1ad981d2 0x1e4828e1 0x1f846162 0x1f842caa 0x1f8423ee 0x1f404559 0x1f4043e8 0x1f3f66c1 0x1f3f7948 0x1f3f7823 0xde8bd1a 0xde8e722 0x7f85ec463609 0x7f85ec38a293
2021.12.09 19:09:00.702629 [ 352 ] {} <Fatal> BaseDaemon: 0.1. inlined from ./obj-x86_64-linux-gnu/../src/Common/StackTrace.cpp:305: StackTrace::tryCapture()
2021.12.09 19:09:00.702653 [ 352 ] {} <Fatal> BaseDaemon: 0. ../src/Common/StackTrace.cpp:266: StackTrace::StackTrace() @ 0xde5ceaa in /workspace/clickhouse
2021.12.09 19:09:00.720028 [ 352 ] {} <Fatal> BaseDaemon: 1. ./obj-x86_64-linux-gnu/../base/daemon/BaseDaemon.cpp:391: sanitizerDeathCallback() @ 0x1d37d991 in /workspace/clickhouse
2021.12.09 19:09:01.000105 [ 314 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 3.52 GiB, peak 9.57 GiB, will set to 3.58 GiB (RSS), difference: 71.23 MiB
2021.12.09 19:09:01.500850 [ 352 ] {} <Fatal> BaseDaemon: 2. __sanitizer::Die() @ 0xde1d8d6 in /workspace/clickhouse
2021.12.09 19:09:01.761253 [ 175 ] {} <Trace> SystemLog (system.trace_log): Flushing system log, 56 entries to flush up to offset 16247
2021.12.09 19:09:01.762261 [ 175 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 88.39 GiB.
2021.12.09 19:09:01.762942 [ 175 ] {} <Trace> system.trace_log (41464490-b3a3-4132-8146-4490b3a35132): Renaming temporary part tmp_insert_202112_198_198_0 to 202112_198_198_0.
2021.12.09 19:09:01.763152 [ 175 ] {} <Trace> SystemLog (system.trace_log): Flushed system log up to offset 16247
2021.12.09 19:09:02.000100 [ 314 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 3.58 GiB, peak 9.57 GiB, will set to 3.84 GiB (RSS), difference: 264.16 MiB
2021.12.09 19:09:02.267214 [ 352 ] {} <Fatal> BaseDaemon: 3. ? @ 0xde2f619 in /workspace/clickhouse
2021.12.09 19:09:03.034073 [ 352 ] {} <Fatal> BaseDaemon: 4. void DB::fillFixedBatch<unsigned short, wide::integer<128ul, unsigned int> >(unsigned long, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> > const&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, DB::PODArray<wide::integer<128ul, unsigned int>, 4096ul, Allocator<false, false>, 15ul, 16ul>&, unsigned long&) @ 0x1ad98ec0 in /workspace/clickhouse
2021.12.09 19:09:03.170738 [ 173 ] {} <Trace> SystemLog (system.query_thread_log): Flushing system log, 866 entries to flush up to offset 142134
2021.12.09 19:09:03.178071 [ 173 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 88.39 GiB.
2021.12.09 19:09:03.180819 [ 173 ] {} <Trace> system.query_thread_log (dd67b783-de12-49b6-9d67-b783de12e9b6): Renaming temporary part tmp_insert_202112_163_163_0 to 202112_163_163_0.
2021.12.09 19:09:03.181261 [ 173 ] {} <Trace> SystemLog (system.query_thread_log): Flushed system log up to offset 142134
2021.12.09 19:09:03.729417 [ 143 ] {} <Trace> system.trace_log (41464490-b3a3-4132-8146-4490b3a35132): Found 2 old parts to remove.
2021.12.09 19:09:03.729457 [ 143 ] {} <Debug> system.trace_log (41464490-b3a3-4132-8146-4490b3a35132): Removing part from filesystem 202112_1_130_32
2021.12.09 19:09:03.729736 [ 143 ] {} <Debug> system.trace_log (41464490-b3a3-4132-8146-4490b3a35132): Removing part from filesystem 202112_131_131_0
2021.12.09 19:09:03.801282 [ 352 ] {} <Fatal> BaseDaemon: 5. void DB::packFixedBatch<wide::integer<128ul, unsigned int> >(unsigned long, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> > const&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, DB::PODArray<wide::integer<128ul, unsigned int>, 4096ul, Allocator<false, false>, 15ul, 16ul>&) @ 0x1ad981d2 in /workspace/clickhouse
2021.12.09 19:09:03.842168 [ 352 ] {} <Fatal> BaseDaemon: 6. ./obj-x86_64-linux-gnu/../src/Common/ColumnsHashing.h:524: DB::ColumnsHashing::HashMethodKeysFixed<wide::integer<128ul, unsigned int>, wide::integer<128ul, unsigned int>, void, false, false, true, false>::HashMethodKeysFixed(std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> > const&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, std::__1::shared_ptr<DB::ColumnsHashing::HashMethodContext> const&) @ 0x1e4828e1 in /workspace/clickhouse
2021.12.09 19:09:03.862989 [ 352 ] {} <Fatal> BaseDaemon: 7. ./obj-x86_64-linux-gnu/../src/Processors/Transforms/IntersectOrExceptTransform.cpp:0: void DB::IntersectOrExceptTransform::addToSet<DB::SetMethodKeysFixed<HashSetTable<wide::integer<128ul, unsigned int>, HashTableCell<wide::integer<128ul, unsigned int>, UInt128HashCRC32, HashTableNoState>, UInt128HashCRC32, HashTableGrower<8ul>, Allocator<true, true> >, false> >(DB::SetMethodKeysFixed<HashSetTable<wide::integer<128ul, unsigned int>, HashTableCell<wide::integer<128ul, unsigned int>, UInt128HashCRC32, HashTableNoState>, UInt128HashCRC32, HashTableGrower<8ul>, Allocator<true, true> >, false>&, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> > const&, unsigned long, DB::SetVariantsTemplate<DB::NonClearableSet>&) const @ 0x1f846162 in /workspace/clickhouse
2021.12.09 19:09:03.882587 [ 352 ] {} <Fatal> BaseDaemon: 8. ./obj-x86_64-linux-gnu/../src/Processors/Transforms/IntersectOrExceptTransform.cpp:148: DB::IntersectOrExceptTransform::accumulate(DB::Chunk) @ 0x1f842caa in /workspace/clickhouse
2021.12.09 19:09:03.902041 [ 352 ] {} <Fatal> BaseDaemon: 9.1. inlined from ./obj-x86_64-linux-gnu/../src/Processors/Chunk.h:32: ~Chunk
2021.12.09 19:09:03.902070 [ 352 ] {} <Fatal> BaseDaemon: 9. ../src/Processors/Transforms/IntersectOrExceptTransform.cpp:82: DB::IntersectOrExceptTransform::work() @ 0x1f8423ee in /workspace/clickhouse
2021.12.09 19:09:03.907724 [ 352 ] {} <Fatal> BaseDaemon: 10. ./obj-x86_64-linux-gnu/../src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::executeJob(DB::IProcessor*) @ 0x1f404559 in /workspace/clickhouse
2021.12.09 19:09:03.912849 [ 352 ] {} <Fatal> BaseDaemon: 11. ./obj-x86_64-linux-gnu/../src/Processors/Executors/ExecutionThreadContext.cpp:65: DB::ExecutionThreadContext::executeTask() @ 0x1f4043e8 in /workspace/clickhouse
2021.12.09 19:09:03.927555 [ 352 ] {} <Fatal> BaseDaemon: 12. ./obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:213: DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x1f3f66c1 in /workspace/clickhouse
2021.12.09 19:09:03.943592 [ 352 ] {} <Fatal> BaseDaemon: 13.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2851: std::__1::shared_ptr<DB::ThreadGroupStatus>::operator bool() const
2021.12.09 19:09:03.943618 [ 352 ] {} <Fatal> BaseDaemon: 13.2. inlined from ../src/Processors/Executors/PipelineExecutor.cpp:304: operator()
2021.12.09 19:09:03.943636 [ 352 ] {} <Fatal> BaseDaemon: 13.3. inlined from ../base/base/../base/scope_guard.h:94: basic_scope_guard<DB::PipelineExecutor::executeImpl(unsigned long)::$_1::operator()() const::'lambda'()>::invoke()
2021.12.09 19:09:03.943669 [ 352 ] {} <Fatal> BaseDaemon: 13.4. inlined from ../base/base/../base/scope_guard.h:44: ~basic_scope_guard
2021.12.09 19:09:03.943706 [ 352 ] {} <Fatal> BaseDaemon: 13.5. inlined from ../src/Processors/Executors/PipelineExecutor.cpp:319: operator()
2021.12.09 19:09:03.943743 [ 352 ] {} <Fatal> BaseDaemon: 13. ../contrib/libcxx/include/type_traits:3682: decltype(std::__1::forward<DB::PipelineExecutor::executeImpl(unsigned long)::$_1&>(fp)()) std::__1::__invoke_constexpr<DB::PipelineExecutor::executeImpl(unsigned long)::$_1&>(DB::PipelineExecutor::executeImpl(unsigned long)::$_1&) @ 0x1f3f7948 in /workspace/clickhouse
2021.12.09 19:09:03.959563 [ 352 ] {} <Fatal> BaseDaemon: 14.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/tuple:0: operator()
2021.12.09 19:09:03.959587 [ 352 ] {} <Fatal> BaseDaemon: 14. ../contrib/libcxx/include/type_traits:3676: decltype(std::__1::forward<DB::PipelineExecutor::executeImpl(unsigned long)::$_1>(fp)()) std::__1::__invoke<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PipelineExecutor::executeImpl(unsigned long)::$_1>(DB::PipelineExecutor::executeImpl(unsigned long)::$_1&&)::'lambda'()&>(DB::PipelineExecutor::executeImpl(unsigned long)::$_1&&) @ 0x1f3f7823 in /workspace/clickhouse
2021.12.09 19:09:03.969359 [ 352 ] {} <Fatal> BaseDaemon: 15.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2533: std::__1::function<void ()>::operator=(std::nullptr_t)
2021.12.09 19:09:03.969379 [ 352 ] {} <Fatal> BaseDaemon: 15. ../src/Common/ThreadPool.cpp:277: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xde8bd1a in /workspace/clickhouse
2021.12.09 19:09:03.980747 [ 352 ] {} <Fatal> BaseDaemon: 16. ./obj-x86_64-linux-gnu/../src/Common/ThreadPool.cpp:0: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) @ 0xde8e722 in /workspace/clickhouse
2021.12.09 19:09:03.980771 [ 352 ] {} <Fatal> BaseDaemon: 17. ? @ 0x7f85ec463609 in ?
2021.12.09 19:09:03.980814 [ 352 ] {} <Fatal> BaseDaemon: 18. __clone @ 0x7f85ec38a293 in ?
2021.12.09 19:09:04.000093 [ 314 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 3.84 GiB, peak 9.57 GiB, will set to 3.87 GiB (RSS), difference: 32.32 MiB
2021.12.09 19:09:04.217518 [ 352 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: 8142A36AB98199A5F585210D0B66F15A. There is no information about the reference checksum.
```

**Comment by alexey-milovidov** [comment]
Fixed.
