### ISSUE TITLE
Assertion in Replxx

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#34511]
```
avtokmakov-dev.sas.yp-c.yandex.net :) clickhouse-client: ../contrib/replxx/src/replxx_impl.cxx:1861: int replxx::Replxx::ReplxxImpl::prev_newline_position(int) const: Assertion `( pos_ >= 0 ) && ( pos_ <= _data.length() )' failed.t_view ORDER BY Rows AS SELECT count() AS Rows, max(UTCEventTime) AS MaxHitTime FROM test_table;
Aborted
```

It happens when I press "up" key several times.

Recent history:
```
avtokmakov@avtokmakov-dev:~$ tail -20 ~/.clickhouse-client-history 
### 2022-02-10 23:06:38.270
create table tt (m int) as t
### 2022-02-10 23:07:24.427
create table tt as t engine=Memory
### 2022-02-10 23:09:37.024
SET default_table_engine = 'Memory';
### 2022-02-10 23:09:41.524
CREATE TABLE mem ORDER BY n AS SELECT 1 as n;
### 2022-02-10 23:17:55.834
SET default_table_engine = 'MergeTree';
### 2022-02-10 23:18:00.904
CREATE TABLE test_table (EventDate Date, CounterID UInt32,  UserID UInt64,  EventTime DateTime('Europe/Moscow'), UTCEventTime DateTime('UTC')) PARTITION BY EventDate PRIMARY KEY CounterID;
### 2022-02-10 23:18:07.021
CREATE MATERIALIZED VIEW test_view ORDER BY Rows AS SELECT count() AS Rows, max(UTCEventTime) AS MaxHitTime FROM test_table;
### 2022-02-10 23:18:20.596
create table mv as test_view
### 2022-02-10 23:18:34.740
show create table mv
### 2022-02-10 23:19:53.377
q
```

Stacktarce:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7d9f859 in __GI_abort () at abort.c:79
#2  0x00007ffff7d9f729 in __assert_fail_base (fmt=0x7ffff7f35588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
    assertion=0xd3bfa72 "( pos_ >= 0 ) && ( pos_ <= _data.length() )", file=0xd88dab3 "../contrib/replxx/src/replxx_impl.cxx", line=1861,
    function=0xde49930 "int replxx::Replxx::ReplxxImpl::prev_newline_position(int) const") at assert.c:92
#3  0x00007ffff7db0f36 in __GI___assert_fail (assertion=0xd3bfa72 "( pos_ >= 0 ) && ( pos_ <= _data.length() )",
    file=0xd88dab3 "../contrib/replxx/src/replxx_impl.cxx", line=1861, function=0xde49930 "int replxx::Replxx::ReplxxImpl::prev_newline_position(int) const")
    at assert.c:101
#4  0x000000002a6a98a3 in replxx::Replxx::ReplxxImpl::prev_newline_position (this=0x7ffff7132600, pos_=-1) at ../contrib/replxx/src/replxx_impl.cxx:1861
#5  0x000000002a6a2735 in replxx::Replxx::ReplxxImpl::line_previous (this=0x7ffff7132600) at ../contrib/replxx/src/replxx_impl.cxx:1903
#6  0x000000002a6a1394 in replxx::Replxx::ReplxxImpl::action (this=0x7ffff7132600, actionTrait_=6, handler_=
    @0x7fffffffb408: (replxx::Replxx::ACTION_RESULT (replxx::Replxx::ReplxxImpl::*)(replxx::Replxx::ReplxxImpl * const, char32_t)) 0x2a6a2660 <replxx::Replxx::Replx
xImpl::line_previous(char32_t)>, code_=1114116 U'\x110004') at ../contrib/replxx/src/replxx_impl.cxx:1426
#7  0x000000002a6a083c in replxx::Replxx::ReplxxImpl::invoke (this=0x7ffff7132600, action_=replxx::Replxx::ACTION::LINE_PREVIOUS, code=1114116 U'\x110004')
    at ../contrib/replxx/src/replxx_impl.cxx:363
#8  0x000000002a6baffd in std::__1::__invoke<replxx::Replxx::ACTION_RESULT (replxx::Replxx::ReplxxImpl::*&)(replxx::Replxx::ACTION, char32_t), replxx::Replxx::Replx
xImpl*&, replxx::Replxx::ACTION&, char32_t, void> (__f=
    @0x7ffff71e99c0: (replxx::Replxx::ACTION_RESULT (replxx::Replxx::ReplxxImpl::*)(replxx::Replxx::ReplxxImpl * const, replxx::Replxx::ACTION, char32_t)) 0x2a6a02e
0 <replxx::Replxx::ReplxxImpl::invoke(replxx::Replxx::ACTION, char32_t)>, __a0=@0x7ffff71e99d0: 0x7ffff7132600, __args=@0x7fffffffb744: 1114116 U'\x110004',
    __args=@0x7fffffffb744: 1114116 U'\x110004') at ../contrib/libcxx/include/type_traits:3617
#9  0x000000002a6baf57 in std::__1::__apply_functor<replxx::Replxx::ACTION_RESULT (replxx::Replxx::ReplxxImpl::*)(replxx::Replxx::ACTION, char32_t), std::__1::tuple
<replxx::Replxx::ReplxxImpl*, replxx::Replxx::ACTION, std::__1::placeholders::__ph<1> >, 0ul, 1ul, 2ul, std::__1::tuple<char32_t&&> > (__f=
    @0x7ffff71e99c0: (replxx::Replxx::ACTION_RESULT (replxx::Replxx::ReplxxImpl::*)(replxx::Replxx::ReplxxImpl * const, replxx::Replxx::ACTION, char32_t)) 0x2a6a02e
0 <replxx::Replxx::ReplxxImpl::invoke(replxx::Replxx::ACTION, char32_t)>, __bound_args=..., __args=...) at ../contrib/libcxx/include/functional:2857
#10 0x000000002a6baec6 in std::__1::__bind<replxx::Replxx::ACTION_RESULT (replxx::Replxx::ReplxxImpl::*)(replxx::Replxx::ACTION, char32_t), replxx::Replxx::ReplxxIm
pl*, replxx::Replxx::ACTION, std::__1::placeholders::__ph<1> const&>::operator()<char32_t> (this=0x7ffff71e99c0, __args=@0x7fffffffb744: 1114116 U'\x110004')
    at ../contrib/libcxx/include/functional:2890
#11 0x000000002a6bae52 in std::__1::__invoke<std::__1::__bind<replxx::Replxx::ACTION_RESULT (replxx::Replxx::ReplxxImpl::*)(replxx::Replxx::ACTION, char32_t), replxx::Replxx::ReplxxImpl*, replxx::Replxx::ACTION, std::__1::placeholders::__ph<1> const&>&, char32_t> (__f=..., __args=@0x7fffffffb744: 1114116 U'\x110004')
    at ../contrib/libcxx/include/type_traits:3676
#12 0x000000002a6bae12 in std::__1::__invoke_void_return_wrapper<replxx::Replxx::ACTION_RESULT>::__call<std::__1::__bind<replxx::Replxx::ACTION_RESULT (replxx::Repl
xx::ReplxxImpl::*)(replxx::Replxx::ACTION, char32_t), replxx::Replxx::ReplxxImpl*, replxx::Replxx::ACTION, std::__1::placeholders::__ph<1> const&>&, char32_t> (
    __args=@0x7fffffffb744: 1114116 U'\x110004', __args=@0x7fffffffb744: 1114116 U'\x110004') at ../contrib/libcxx/include/__functional_base:317
#13 0x000000002a6badcd in std::__1::__function::__default_alloc_func<std::__1::__bind<replxx::Replxx::ACTION_RESULT (replxx::Replxx::ReplxxImpl::*)(replxx::Replxx::
ACTION, char32_t), replxx::Replxx::ReplxxImpl*, replxx::Replxx::ACTION, std::__1::placeholders::__ph<1> const&>, replxx::Replxx::ACTION_RESULT (char32_t)>::operator
()(char32_t&&) (this=0x7ffff71e99c0, __arg=@0x7fffffffb744: 1114116 U'\x110004') at ../contrib/libcxx/include/functional:1608
#14 0x000000002a6bad97 in std::__1::__function::__policy_invoker<replxx::Replxx::ACTION_RESULT (char32_t)>::__call_impl<std::__1::__function::__default_alloc_func<s
td::__1::__bind<replxx::Replxx::ACTION_RESULT (replxx::Replxx::ReplxxImpl::*)(replxx::Replxx::ACTION, char32_t), replxx::Replxx::ReplxxImpl*, replxx::Replxx::ACTION
, std::__1::placeholders::__ph<1> const&>, replxx::Replxx::ACTION_RESULT (char32_t)> >(std::__1::__function::__policy_storage const*, char32_t) (
    __buf=0x7ffff708b458, __args=1114116 U'\x110004') at ../contrib/libcxx/include/functional:2089
#15 0x000000002a6c3c7d in std::__1::__function::__policy_func<replxx::Replxx::ACTION_RESULT (char32_t)>::operator()(char32_t&&) const (this=0x7ffff708b458,
    __args=@0x7fffffffb7a4: 1114116 U'\x110004') at ../contrib/libcxx/include/functional:2221
#16 0x000000002a6ae48c in std::__1::function<replxx::Replxx::ACTION_RESULT (char32_t)>::operator()(char32_t) const (this=0x7ffff708b458, __arg=1114116 U'\x110004')
    at ../contrib/libcxx/include/functional:2560
#17 0x000000002a6a663b in replxx::Replxx::ReplxxImpl::get_input_line (this=0x7ffff7132600) at ../contrib/replxx/src/replxx_impl.cxx:1412
#18 0x000000002a6a6127 in replxx::Replxx::ReplxxImpl::input (this=0x7ffff7132600, prompt=...) at ../contrib/replxx/src/replxx_impl.cxx:657
#19 0x000000002a68fbc5 in replxx::Replxx::input (this=0x7fffffffbe68, prompt=...) at ../contrib/replxx/src/replxx.cxx:150
#20 0x000000002a56e555 in ReplxxLineReader::readOneLine (this=0x7fffffffbde0, prompt=...) at ../base/base/ReplxxLineReader.cpp:233
#21 0x000000002a562a43 in LineReader::readLine (this=0x7fffffffbde0, first_prompt=..., second_prompt=...) at ../base/base/LineReader.cpp:129
#22 0x0000000026214dc4 in DB::ClientBase::runInteractive (this=0x7fffffffc3f0) at ../src/Client/ClientBase.cpp:1596
#23 0x0000000017025ccf in DB::Client::main (this=0x7fffffffc3f0) at ../programs/client/Client.cpp:438
#24 0x000000002a5ee985 in Poco::Util::Application::run (this=0x7fffffffc3f0) at ../contrib/poco/Util/src/Application.cpp:334
#25 0x000000001702f7e7 in mainEntryClickHouseClient (argc=1, argv=0x7ffff7001180) at ../programs/client/Client.cpp:1219
#26 0x0000000016eb4265 in main (argc_=2, argv_=0x7fffffffe558) at ../programs/main.cpp:378
```

```
(gdb) up
#4  0x000000002a6a98a3 in replxx::Replxx::ReplxxImpl::prev_newline_position (this=0x7ffff7132600, pos_=-1) at ../contrib/replxx/src/replxx_impl.cxx:1861
(gdb) p pos_
$1 = -1
(gdb) p _data.length()
$2 = 125
(gdb) up
#5  0x000000002a6a2735 in replxx::Replxx::ReplxxImpl::line_previous (this=0x7ffff7132600) at ../contrib/replxx/src/replxx_impl.cxx:1903
(gdb) p prevNewlinePosition
$4 = 0
```

**Comment by tavplubix** [comment]
It's still reproducible
