### ISSUE TITLE
clickhouse 报错问题  "Call getSampleBlock before insert."

### ISSUE THREAD

**Issue by Mr-ZhangJie** [ClickHouse/ClickHouse#34788]
以下报错是在我在使用 java多线程读取本地文件 批量插入数据的时候出现的: 以下错误 偶尔会出现
`java.sql.SQLException: Call getSampleBlock before insert.
	at com.github.housepower.misc.Validate.isTrue(Validate.java:41)
	at com.github.housepower.jdbc.ClickHouseConnection.sendInsertRequest(ClickHouseConnection.java:277)
	at com.github.housepower.jdbc.statement.ClickHousePreparedInsertStatement.executeBatch(ClickHousePreparedInsertStatement.java:154)
	at com.test.clickhouse.ClickhouseApplicationTests.lambda$saveData$0(ClickhouseApplicationTests.java:360)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
2022-02-21 17:08:40.918 ERROR 20024 --- [nPool-worker-13] c.t.c.ClickhouseApplicationTests         : 数据保存 报错 文件 data_collection_30.sql  行号 0
java.sql.SQLException: Call getSampleBlock before insert.
	at com.github.housepower.misc.Validate.isTrue(Validate.java:41)
	at com.github.housepower.jdbc.ClickHouseConnection.sendInsertRequest(ClickHouseConnection.java:277)
	at com.github.housepower.jdbc.statement.ClickHousePreparedInsertStatement.executeBatch(ClickHousePreparedInsertStatement.java:154)
	at com.test.clickhouse.ClickhouseApplicationTests.lambda$saveData$0(ClickhouseApplicationTests.java:360)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)`

![image](https://user-images.githubusercontent.com/42841916/154927283-3099578b-ac0e-4c89-aa05-3ec649ffa81a.png)

**Comment by vdimir** [comment]
Do you use https://github.com/housepower/ClickHouse-Native-JDBC ?  Have you tried https://github.com/ClickHouse/clickhouse-jdbc  for your task ?

**Comment by vdimir** [comment]
Issue is connected with external tool, it's better to ask in the repo of [ClickHouse-Native-JDBC](https://github.com/housepower/ClickHouse-Native-JDBC) or in one of our [community resources](https://clickhouse.com/blog/en/2020/the-clickhouse-community/#resources):

* [Google Groups](https://groups.google.com/g/clickhouse)
* [Slack](https://clickhousedb.slack.com/)
* [Telegram Group](https://t.me/clickhouse_en)

**Comment by Mr-ZhangJie** [comment]
> 你使用https://github.com/housepower/ClickHouse-Native-JDBC吗？您是否 为您的任务尝试过[https://github.com/ClickHouse/clickhouse-jdbc ？](https://github.com/ClickHouse/clickhouse-jdbc)

感谢您的回复,我尝试一下使用您推荐的
