### ISSUE TITLE
run clickhouse-server and  Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by huxiangyang2018** [ClickHouse/ClickHouse#35148]
I built clickhouse in aarch64. Then I run the command "clickhouse-server start ", I got Segmentation fault (core dumped). Later I use gdb to run it, info as follows:

```
[root@localhost programs]# gdb ./clickhouse-server
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-114.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "aarch64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/clickhouse/build-arm64/programs/clickhouse...done.
(gdb) run
Starting program: /home/clickhouse/build-arm64/programs/./clickhouse-server
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Processing configuration file 'config.xml'.
There is no file 'config.xml', will use embedded config.
Logging trace to console
2022.03.09 16:31:24.948032 [ 99955 ] {} <Trace> Pipe: Pipe capacity is 1.00 MiB
[New Thread 0xffffb76c8dd0 (LWP 99959)]
2022.03.09 16:31:25.514098 [ 99955 ] {} <Information> : Starting ClickHouse 22.3.1.1 with revision 54460, build id: 1B1904D092398AC1DD7A63A99AC5622300A58EB1, PID 99955
2022.03.09 16:31:25.514248 [ 99955 ] {} <Information> Application: starting up
2022.03.09 16:31:25.514278 [ 99955 ] {} <Information> Application: OS name: Linux, version: 4.14.0_kernel_perf, architecture: aarch64

Program received signal SIGSEGV, Segmentation fault.
0x0000ffffbe61ea0c in _int_malloc () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-260.el7.aarch64
(gdb) where
#0  0x0000ffffbe61ea0c in _int_malloc () from /lib64/libc.so.6
#1  0x0000ffffbe621068 in malloc () from /lib64/libc.so.6
#2  0x0000000004b6dabc in newImpl (size=184) at ./src/Common/memory.h:23
#3  operator new(unsigned long) (size=184) at ./src/Common/new_delete.cpp:53
#4  0x000000000b614f1c in __libcpp_operator_new<unsigned long> (__args=4, __args@entry=319980544) at ./contrib/libcxx/include/new:235
#5  __libcpp_allocate (__size=4, __size@entry=319980544, __align=8) at ./contrib/libcxx/include/new:261
#6  allocate (this=0x13128408 <DB::FunctionFactory::instance()::ret+144>, __n=23) at ./contrib/libcxx/include/memory:840
#7  allocate (__a=..., __n=23) at ./contrib/libcxx/include/__memory/allocator_traits.h:468
#8  std::__1::__hash_table<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::function<std::__1::shar ed_ptr<DB::IFunctionOverloadResolver> (std::__1::shared_ptr<DB::Context const>)> >, std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>,  std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::function<std::__1::sh ared_ptr<DB::IFunctionOverloadResolver> (std::__1::shared_ptr<DB::Context const>)> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::alloca tor<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::__unordered_map_equal<std::__1::bas ic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::alloc ator<char> >, std::__1::function<std::__1::shared_ptr<DB::IFunctionOverloadResolver> (std::__1::shared_ptr<DB::Context const>)> >, std::__1::equal_to<std::__1::basic_string<ch ar, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>,  std::__1::allocator<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::function<std::__1::shared_ptr< DB::IFunctionOverloadResolver> (std::__1::shared_ptr<DB::Context const>)> > > >::__rehash(unsigned long) (
    this=this@entry=0x13128400 <DB::FunctionFactory::instance()::ret+136>, __nbc=__nbc@entry=23) at ./contrib/libcxx/include/__hash_table:2338
#9  0x000000000b614bd0 in rehash (this=0x13128400 <DB::FunctionFactory::instance()::ret+136>, __n=23) at ./contrib/libcxx/include/__hash_table:2314
#10 std::__1::__hash_table<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::function<std::__1::shar ed_ptr<DB::IFunctionOverloadResolver> (std::__1::shared_ptr<DB::Context const>)> >, std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>,  std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::function<std::__1::sh ared_ptr<DB::IFunctionOverloadResolver> (std::__1::shared_ptr<DB::Context const>)> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::alloca tor<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::__unordered_map_equal<std::__1::bas ic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::alloc ator<char> >, std::__1::function<std::__1::shared_ptr<DB::IFunctionOverloadResolver> (std::__1::shared_ptr<DB::Context const>)> >, std::__1::equal_to<std::__1::basic_string<ch ar, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>,  std::__1::allocator<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::function<std::__1::shared_ptr< DB::IFunctionOverloadResolver> (std::__1::shared_ptr<DB::Context const>)> > > >::__emplace_unique_key_args<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1:: allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<std::__1::shared_ptr<DB::IFunctionOverloadR esolver> (std::__1::shared_ptr<DB::Context const>)>&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char , std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<std::__1::shared_ptr<DB::IFunctionOverloadResolver> (std::__1::shared_ptr<DB::Context con st>)>&) (this=0x13128400 <DB::FunctionFactory::instance()::ret+136>, __k=..., __args=..., __args=...) at ./contrib/libcxx/include/__hash_table:2096
#11 0x000000000b612d7c in __emplace_unique<const std::__1::string &, std::__1::function<std::__1::shared_ptr<DB::IFunctionOverloadResolver> (std::__1::shared_ptr<const DB::Con text>)> &> (this=0x4, __f=..., __s=...) at ./contrib/libcxx/include/__hash_table:1089
#12 emplace<const std::__1::string &, std::__1::function<std::__1::shared_ptr<DB::IFunctionOverloadResolver> (std::__1::shared_ptr<const DB::Context>)> &> (this=0x4,
    __args=..., __args=...) at ./contrib/libcxx/include/unordered_map:1158
#13 DB::FunctionFactory::registerFunction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<std::__1::shared_ptr <DB::IFunctionOverloadResolver> (std::__1::shared_ptr<DB::Context const>)>, DB::IFactoryWithAliases<std::__1::function<std::__1::shared_ptr<DB::IFunctionOverloadResolver> (std ::__1::shared_ptr<DB::Context const>)> >::CaseSensitiveness) (this=0x13128378 <DB::FunctionFactory::instance()::ret>, name=..., creator=..., case_sensitiveness=CaseSensitive)
    at ./src/Functions/FunctionFactory.cpp:34
#14 0x000000000741ae20 in DB::registerFunctionBitAnd(DB::FunctionFactory&) ()
#15 0x00000000068f0a8c in DB::registerFunctionsArithmetic(DB::FunctionFactory&) ()
#16 0x00000000068f0858 in DB::registerFunctions() ()
#17 0x0000000004bd0a88 in DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1 ::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) (this=0xffffffffe7d0) at ./programs/server/Server.cpp:515
#18 0x000000000d04f73c in Poco::Util::Application::run() (this=0xffffffffe7d0) at ./contrib/poco/Util/src/Application.cpp:334
#19 0x0000000004bcf810 in DB::Server::run() (this=0xffffffffe7d0) at ./programs/server/Server.cpp:452
---Type <return> to continue, or q <return> to quit---
#20 0x000000000d06309c in Poco::Util::ServerApplication::run(int, char**) (this=0xffffffffe7d0, argc=1, argv=0x132c1a90) at ./contrib/poco/Util/src/ServerApplication.cpp:611
#21 0x0000000004bcdbd4 in mainEntryClickHouseServer(int, char**) (argc=1, argv=0x132c1a90) at ./programs/server/Server.cpp:183
#22 0x0000000004b6d2c8 in main (argc_=<optimized out>, argv_=<optimized out>) at ./programs/main.cpp:378
```

How should I run it and make it work?

**Comment by filimonov** [comment]
> I built clickhouse in aarch64. 

Does it reproduces with official build? https://clickhouse.com/docs/en/getting-started/install/#from-binaries-non-linux

**Comment by huxiangyang2018** [comment]
> 

I reproduced with official build according to this website.  https://clickhouse.com/docs/en/development/build-cross-arm/

**Comment by huxiangyang2018** [comment]
> Do you have same issue with our build for aarch64? https://builds.clickhouse.com/master/aarch64/clickhouse

No, I don't. I download the official build and it's working on my machine.

**Comment by huxiangyang2018** [comment]
The reason of issue is my llvm is incompletes.  I rebuild llvm and clickhouse, now it's working. Thanks!
