### ISSUE TITLE
Inconsistent sizes of values and offsets in SerializationSparse

### ISSUE THREAD

**Issue by qirui** [ClickHouse/ClickHouse#35513]
###  table ddl ### 
CREATE TABLE alert_event
(
    ......
    `src_is_banned` UInt8,
    `src_is_white` UInt8,
    `protocol` LowCardinality(String),
		......
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(alert_time)
ORDER BY (alert_time,
 src_ip_int,
 dest_ip_int)
SETTINGS index_granularity = 8192,
 ratio_of_defaults_for_sparse_serialization = 0.9;

###  query ### 
SELECT 
       src_ip,
       dest_ip
FROM alert_event 
where alert_time between toDateTime(1646001747) and toDateTime(1648001747)
  and src_is_banned = 0
  and src_is_white = 0  
  and protocol ='UDP'
order by alert_time desc

### error ### 
org.jkiss.dbeaver.model.sql.DBSQLException: SQL 错误 [1002]: ClickHouse exception, code: 1002, host: xxxx, port: 8123; Code: 49. DB::Exception: Inconsistent sizes of values and offsets in SerializationSparse. Offsets size: 1, values size: 1: (while reading column src_is_white): (while reading from part /data/clickhouse/data/store/c20/c20f372f-3b94-4e53-aaa5-72ffbed19b73/20220318_1_499_14/ from mark 1 with max_rows_to_read = 29777): While executing MergeTreeReverse. (LOGICAL_ERROR) (version 22.2.2.1)

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)

	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:513)

	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:444)

	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)

	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:431)

	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:816)

	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3440)

	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)

	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)

	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)

	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4718)

	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)

	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

Caused by: ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: 172.16.130.145, port: 8123; Code: 49. DB::Exception: Inconsistent sizes of values and offsets in SerializationSparse. Offsets size: 1, values size: 1: (while reading column src_is_white): (while reading from part /data/clickhouse/clickhouse/data/store/c20/c20f372f-3b94-4e53-aaa5-72ffbed19b73/20220318_1_499_14/ from mark 1 with max_rows_to_read = 29777): While executing MergeTreeReverse. (LOGICAL_ERROR) (version 22.2.2.1)

	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.getException(ClickHouseExceptionSpecifier.java:91)

	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:55)

	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:28)

	at ru.yandex.clickhouse.ClickHouseStatementImpl.checkForErrorAndThrow(ClickHouseStatementImpl.java:1046)

	at ru.yandex.clickhouse.ClickHouseStatementImpl.getInputStream(ClickHouseStatementImpl.java:737)

	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:196)

	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:166)

	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:161)

	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:156)

	at ru.yandex.clickhouse.ClickHouseStatementImpl.execute(ClickHouseStatementImpl.java:328)

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:130)

	... 12 more

Caused by: java.lang.Throwable: Code: 49. DB::Exception: Inconsistent sizes of values and offsets in SerializationSparse. Offsets size: 1, values size: 1: (while reading column src_is_white): (while reading from part /data/clickhouse/clickhouse/data/store/c20/c20f372f-3b94-4e53-aaa5-72ffbed19b73/20220318_1_499_14/ from mark 1 with max_rows_to_read = 29777): While executing MergeTreeReverse. (LOGICAL_ERROR) (version 22.2.2.1)

	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:53)

	... 22 more

**Comment by Slach** [comment]
@CurtizJ @alexey-milovidov  

after 1 week upgrade from 25.4 to 25.12 got similar error
```
CREATE TABLE xxx.userhistory
(
    `id` Int64,
    `first_name` String,
    `last_name` String,
    `username` String,
    `date` DateTime,
    `deleted` Bool,
    `premium` Bool
)
ENGINE = ReplacingMergeTree
ORDER BY (id, first_name, last_name, username)
SETTINGS storage_policy = 'ssd', index_granularity = 8192

```
it looks like string with size sparse serialization which turned on by default, corrupts data
all some strings field from one table have error

```
2025.12.24 11:59:42.476769 [ 3429998 ] {f6b827c6-3f2c-407f-ab3e-b1b993cb69a2} <Error> ForcedCriticalErrorsLogger: Code: 49. DB::Exception: Inconsistent sizes of values and offsets in SerializationSparse. Offsets size: 28, values size: 1: (while reading column first_name): (while reading from part /store-ssd/clickhouse/store/086/0861677a-e196-457c-bb38-8b1c23484b0d/all_7357674_8115878_3870_8483860/ in table xxx.userhistory (0861677a-e196-457c-bb38-8b1c23484b0d) located on disk disk_ssd of type local, from mark 1653 with max_rows_to_read = 2037, offset = 0). (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000013ef7e9f
1. DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000cb2fb8e
2. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000cb2f580
3. DB::Exception::Exception<unsigned long, unsigned long>(int, FormatStringHelperImpl<std::type_identity<unsigned long>::type, std::type_identity<unsigned long>::type>, unsigned long&&, unsigned long&&) @ 0x0000000013ebc5eb
4. DB::SerializationSparse::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::unordered_map<String, std::unique_ptr<DB::ISerialization::ISubstreamsCacheElement, std::default_delete<DB::ISerialization::ISubstreamsCacheElement>>, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, std::unique_ptr<DB::ISerialization::ISubstreamsCacheElement, std::default_delete<DB::ISerialization::ISubstreamsCacheElement>>>>>*) const @ 0x0000000017c29ce0
5. DB::MergeTreeReaderWide::readRows(unsigned long, unsigned long, bool, unsigned long, unsigned long, std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&) @ 0x000000001a13160b
6. DB::MergeTreeRangeReader::DelayedStream::finalize(std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&) @ 0x000000001a108e59
7. DB::MergeTreeRangeReader::continueReadingChain(DB::MergeTreeRangeReader::ReadResult&, unsigned long&) @ 0x000000001a1147e1
8. DB::MergeTreeReadersChain::read(unsigned long, DB::MarkRanges&, std::vector<DB::MarkRanges, std::allocator<DB::MarkRanges>>&) @ 0x000000001a149ceb
9. DB::MergeTreeReadTask::read() @ 0x000000001a144d79
10. DB::MergeTreeThreadSelectAlgorithm::readFromTask(DB::MergeTreeReadTask&) @ 0x000000001ae13c0c
11. DB::MergeTreeSelectProcessor::readCurrentTask(DB::MergeTreeReadTask&, DB::IMergeTreeSelectAlgorithm&) const @ 0x000000001a1534f8
12. DB::MergeTreeSelectProcessor::read() @ 0x000000001a15541b
13. DB::MergeTreeSource::tryGenerate() @ 0x000000001ae52652
14. DB::ISource::work() @ 0x000000001a84a836
15. DB::ExecutionThreadContext::executeTask() @ 0x000000001a8676d7
16. DB::PipelineExecutor::executeStepImpl(unsigned long, DB::IAcquiredSlot*, std::atomic<bool>*) @ 0x000000001a859c9b
17. void std::__function::__policy_func<void ()>::__call_func[abi:ne210105]<DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0>(std::__function::__policy_storage const*) @ 0x000000001a85dcc3
18. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::worker() @ 0x000000001404b5cb

```
