### ISSUE TITLE
ODBC Engine - SQL Server query fails while retrieving columns following NVARCHAR(MAX) column

### ISSUE THREAD

**Issue by alex-bochkov** [ClickHouse/ClickHouse#35538]
**Describe what's wrong**
Query fails while pulling LOB data from SQL Server table using ODBC engine.
Not quite sure that the issue is on the ClickHouse side - https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/getting-long-data?view=sql-server-ver15
`ODBC Driver 18 for SQL Server` and `ODBC Driver 17 for SQL Server` both return errors.

As a workaround we can place all large columns at the end - it seems to work even with multiple LOB columns.

**Does it reproduce on a recent release?**
Yes

**How to reproduce**
Source SQL Server table:
```sql
CREATE TABLE [dbo].[sourceTable] (
    [PK_id]             INT            NOT NULL,
    [comment]           NVARCHAR (MAX) NOT NULL,
    [MD_createDateTime] DATETIME       NOT NULL,
    [MD_updateDateTime] DATETIME       NOT NULL,
    [MD_version]        INT            NOT NULL,
    CONSTRAINT [PK_sourceTable] PRIMARY KEY CLUSTERED ([PK_id])
);
```
ClickHouse table that works - the `comment` column is at the end
```
CREATE TABLE default.odbc_sourceTable
(   
    `pk_id` Int32,
    `md_createdatetime` DateTime,
    `md_updatedatetime` DateTime,
    `md_version` Int32,
    `comment` String    
)
ENGINE = ODBC(' < removed> ', 'dbo', 'sourceTable');

--query returns data just fine
SELECT * FROM default.odbc_sourceTable
```

ClickHouse table that doesn't work - the `comment` is in the middle
```
CREATE TABLE default.odbc_sourceTable
(   
    `pk_id` Int32,
    `comment` String,
    `md_createdatetime` DateTime,
    `md_updatedatetime` DateTime,
    `md_version` Int32
)
ENGINE = ODBC(' < removed> ', 'dbo', 'sourceTable');

--query fails
SELECT * FROM default.odbc_sourceTable
```
![image](https://user-images.githubusercontent.com/13791336/159729778-5f790e85-1ad2-418e-807c-9c2761f07fc8.png)

**Expected behavior**
The query should succeed regardless of the column order.

**Error message and/or stacktrace**
```
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [86] [07000]: Code: 86. DB::Exception: Received error from remote server /?connection_string= ... removed .. &max_block_size=200. HTTP status code: 500 Internal Server Error, body: �	std::exception. Code: 1001, type: nanodbc::database_error, e.what() = ../contrib/nanodbc/nanodbc/nanodbc.cpp:3172: 0700: [Microsoft][ODBC Driver 18 for SQL Server]Invalid Descriptor Index ,. (RECEIVED_ERROR_FROM_REMOTE_IO_SERVER) (version 22.2.2.1)
, server ClickHouseNode(addr=http:10.0.238.254:8123, db=default)@-823435104

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:513)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:444)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:431)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:816)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3504)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4841)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Code: 86. DB::Exception: Received error from remote server /?connection_string=... removed .. &max_block_size=200. HTTP status code: 500 Internal Server Error, body: �	std::exception. Code: 1001, type: nanodbc::database_error, e.what() = ../contrib/nanodbc/nanodbc/nanodbc.cpp:3172: 0700: [Microsoft][ODBC Driver 18 for SQL Server]Invalid Descriptor Index ,. (RECEIVED_ERROR_FROM_REMOTE_IO_SERVER) (version 22.2.2.1)
, server ClickHouseNode(addr=http:10.0.238.254:8123, db=default)@-823435104
	at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:55)
	at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:70)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.getLastResponse(ClickHouseStatementImpl.java:81)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:268)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.execute(ClickHouseStatementImpl.java:255)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:329)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.lambda$0(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:94)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 12 more
Caused by: java.io.IOException: Code: 86. DB::Exception: Received error from remote server /?connection_string=... removed .. . HTTP status code: 500 Internal Server Error, body: �	std::exception. Code: 1001, type: nanodbc::database_error, e.what() = ../contrib/nanodbc/nanodbc/nanodbc.cpp:3172: 0700: [Microsoft][ODBC Driver 18 for SQL Server]Invalid Descriptor Index ,. (RECEIVED_ERROR_FROM_REMOTE_IO_SERVER) (version 22.2.2.1)
	at com.clickhouse.client.http.HttpUrlConnectionImpl.checkResponse(HttpUrlConnectionImpl.java:130)
	at com.clickhouse.client.http.HttpUrlConnectionImpl.post(HttpUrlConnectionImpl.java:201)
	at com.clickhouse.client.http.ClickHouseHttpClient.postRequest(ClickHouseHttpClient.java:88)
	at com.clickhouse.client.http.ClickHouseHttpClient.execute(ClickHouseHttpClient.java:114)
	at com.clickhouse.client.ClickHouseRequest.execute(ClickHouseRequest.java:1385)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.getLastResponse(ClickHouseStatementImpl.java:76)
	... 18 more
```

**Comment by den-crane** [comment]
It was fixed a long time ago https://github.com/ClickHouse/ClickHouse/issues/21165
What CH version do you use?

**Comment by alex-bochkov** [comment]
I pulled the most recent version from here - https://repo.yandex.ru/clickhouse/deb/stable/main/
`version 22.2.2.1`

**Comment by Avogar** [comment]
@kssenii maybe you can look?

**Comment by kssenii** [comment]
This is specific to mssql. There is the same test case in nanodbc library: https://github.com/nanodbc/nanodbc/pull/227/files#diff-a72292364bf35400c880ebbe2122646d1e340e160c2c16e3dc2fcd20a772358bR400-R401 where it also states: `"it illustrates a canonical sitaution leading to the Invalid Descriptor Index error"`. So queries to mssql require some ordering in column types.

**Comment by alex-bochkov** [comment]
thanks, @kssenii. Closing this.
