### ISSUE TITLE
Segfault without stacktrace in Stress test

### ISSUE THREAD

**Issue by CurtizJ** [ClickHouse/ClickHouse#36547]
1. https://s3.amazonaws.com/clickhouse-test-reports/0/f9faadcfeef67ddb6528994f9db80766b5012fdc/stress_test__thread__actions_.html
2. https://s3.amazonaws.com/clickhouse-test-reports/0/dd2e085ae565553cc15c7e1647d0c0fee589d755/stress_test__thread__actions_.html

**Comment by tavplubix** [comment]
Probably it's because tsan failed to allocate memory, it makes sense to check stderr.log.gz

**Comment by tavplubix** [comment]
Another failure, but this one has core dump:
https://s3.amazonaws.com/clickhouse-test-reports/36676/9d364cdce26b13aa8923fa03ef9f4a7fd70f6ea6/stress_test__thread__actions_.html

**Comment by tavplubix** [comment]
Another segfault in tsan with coredump:
```
2022-06-02 23:54:49 Thread 1128 "clickhouse-serv" received signal SIGSEGV, Segmentation fault.
2022-06-02 23:54:49 [Switching to Thread 0x7f74c34ab700 (LWP 22306)]
2022-06-02 23:54:49 0x000000000b1e7b87 in __tsan_func_entry ()
2022-06-02 23:54:56 Saved corefile core.637
2022-06-02 23:54:56 #0  0x000000000b1e7b87 in __tsan_func_entry ()
2022-06-02 23:54:56 No symbol table info available.
2022-06-02 23:54:56 Backtrace stopped: Cannot access memory at address 0x7f74c3463818
2022-06-02 23:54:56 
2022-06-02 23:54:56 Thread 1128 (Thread 0x7f74c34ab700 (LWP 22306)):
2022-06-02 23:54:56 #0  0x000000000b1e7b87 in __tsan_func_entry ()
2022-06-02 23:54:56 No symbol table info available.
2022-06-02 23:54:56 Backtrace stopped: Cannot access memory at address 0x7f74c3463818
```

https://s3.amazonaws.com/clickhouse-test-reports/0/4d4374193c5ef34f1c7849394b4f4b8f565bdcd0/stress_test__thread__actions_.html

**Comment by tavplubix** [comment]
```
(gdb) disas 0xb1e7b20
Dump of assembler code for function __tsan_func_entry:
   0x000000000b1e7b20 <+0>:	mov    %fs:0xfffffffffffba050,%rax
   0x000000000b1e7b29 <+9>:	mov    (%rax),%rdx
   0x000000000b1e7b2c <+12>:	add    $0x1,%rdx
   0x000000000b1e7b30 <+16>:	mov    %rdx,(%rax)
   0x000000000b1e7b33 <+19>:	test   $0x1fff,%edx
   0x000000000b1e7b39 <+25>:	je     0xb1e7b96 <__tsan_func_entry+118>
   0x000000000b1e7b3b <+27>:	mov    %rdx,%rcx
   0x000000000b1e7b3e <+30>:	shr    $0x2a,%rcx
   0x000000000b1e7b42 <+34>:	and    $0x7,%cl
   0x000000000b1e7b45 <+37>:	mov    $0xffffc000,%esi
   0x000000000b1e7b4a <+42>:	shl    %cl,%esi
   0x000000000b1e7b4c <+44>:	not    %esi
   0x000000000b1e7b4e <+46>:	and    %edx,%esi
   0x000000000b1e7b50 <+48>:	shr    $0x32,%rdx
   0x000000000b1e7b54 <+52>:	and    $0x1fff,%edx
   0x000000000b1e7b5a <+58>:	imul   $0x1130000,%rdx,%rcx
   0x000000000b1e7b61 <+65>:	lea    (%rcx,%rsi,8),%rcx
   0x000000000b1e7b65 <+69>:	movabs $0x2000000000000000,%rdx
   0x000000000b1e7b6f <+79>:	or     %rdi,%rdx
   0x000000000b1e7b72 <+82>:	movabs $0x600000000000,%rsi
   0x000000000b1e7b7c <+92>:	mov    %rdx,(%rsi,%rcx,1)
   0x000000000b1e7b80 <+96>:	mov    0xc8(%rax),%rcx
   0x000000000b1e7b87 <+103>:	mov    %rdi,(%rcx)
   0x000000000b1e7b8a <+106>:	add    $0x8,%rcx
   0x000000000b1e7b8e <+110>:	mov    %rcx,0xc8(%rax)
   0x000000000b1e7b95 <+117>:	ret    
   0x000000000b1e7b96 <+118>:	sub    $0x400,%rsp
   0x000000000b1e7b9d <+125>:	call   0xb1f4050 <__tsan_trace_switch_thunk>
   0x000000000b1e7ba2 <+130>:	add    $0x400,%rsp
   0x000000000b1e7ba9 <+137>:	jmp    0xb1e7b3b <__tsan_func_entry+27>
End of assembler dump.

(gdb) i r rip
rip            0xb1e7b87           0xb1e7b87 <__tsan_func_entry+103>
(gdb) i r rcx
rcx            0x0                 0
(gdb) i r
rax            0x7f74c3465740      140139469100864
rbx            0xdd30d18f000       15200108998656
rcx            0x0                 0
rdx            0x200000000b167d76  2305843009399717238
rsi            0x600000000000      105553116266496
rdi            0xb167d76           186023286
rbp            0x7f74c3463c60      0x7f74c3463c60
rsp            0x7f74c3463818      0x7f74c3463818
r8             0x1                 1
r9             0x57                87
r10            0x53af064           87748708
r11            0x202               514
r12            0xdd30b2b0000       15200076627968
r13            0x2278fa40          578353728
r14            0x600000000004      105553116266500
r15            0xdd30d18f900       15200109000960
rip            0xb1e7b87           0xb1e7b87 <__tsan_func_entry+103>
eflags         0x10202             [ IF RF ]
cs             0x33                51
ss             0x2b                43
ds             0x0                 0
es             0x0                 0
fs             0x0                 0
gs             0x0                 0
k0             0x0                 0
k1             0x0                 0
k2             0x0                 0
k3             0x0                 0
k4             0x0                 0
k5             0x0                 0
k6             0x0                 0
k7             0x0                 0
```

**Comment by tavplubix** [comment]
Looks like https://github.com/google/sanitizers/issues/1195

**Comment by alexey-milovidov** [comment]
Where any of our 3rd-party dependencies is using C11 threading primitives?
This should not happen. If it happens, we need to disable C11 threading primitives on build.

**Comment by tavplubix** [comment]
The only contrib using `thrd_create` is... librdkafka. But we don't have any functional tests with kafka (and AFAIK librdkafka does not have library ctor), so it's weird

**Comment by tavplubix** [comment]
Hm, no, even `librdkafka` does not use them, `WITH_C11THREADS` is not enabled, so it creates own wrappers for functions from pthreads (`contrib/librdkafka/tinycthread.h`)

**Comment by tavplubix** [comment]
This issue disappeared after upgrading to clang-14. Then it appeared again after downgrading to clang-13, so I'm pretty sure it was a bug in tsan. I have not seen suspicious segfaults with tsan after upgrading to clang-15, so let's close this it hope it will never reproduce anymore.
