### ISSUE TITLE
Reference binding to null pointer of type `DB::WindowTransformBlock`

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#37361]
https://s3.amazonaws.com/clickhouse-test-reports/37355/f787dc7097b9da93fc59679548cc4704a4279f85/fuzzer_astfuzzerubsan,actions//report.html

```
 #0 0x245a88f1 in std::__1::deque<DB::WindowTransformBlock, std::__1::allocator<DB::WindowTransformBlock> >::operator[](unsigned long) build_docker/../contrib/libcxx/include/deque:1836:5
    #1 0x245a7fc3 in DB::WindowTransform::blockRowsNumber(DB::RowNumber const&) const build_docker/../src/Processors/Transforms/WindowTransform.h:173:16
    #2 0x2459a363 in DB::WindowTransform::moveRowNumberNoCheck(DB::RowNumber const&, long) const build_docker/../src/Processors/Transforms/WindowTransform.cpp:435:37
    #3 0x245b4870 in DB::WindowTransform::moveRowNumber(DB::RowNumber const&, long) const build_docker/../src/Processors/Transforms/WindowTransform.cpp:496:19
    #4 0x245b4870 in DB::WindowFunctionNthValue::windowInsertResultInto(DB::WindowTransform const*, unsigned long) build_docker/../src/Processors/Transforms/WindowTransform.cpp:2138:59
    #5 0x2459fc79 in DB::WindowTransform::writeOutCurrentRow() build_docker/../src/Processors/Transforms/WindowTransform.cpp:982:38
    #6 0x245a09ed in DB::WindowTransform::appendChunk(DB::Chunk&) build_docker/../src/Processors/Transforms/WindowTransform.cpp:1190:13
    #7 0x245a5793 in DB::WindowTransform::work() build_docker/../src/Processors/Transforms/WindowTransform.cpp:1422:9
    #8 0x241c92b8 in DB::executeJob(DB::IProcessor*) build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:45:20
    #9 0x241c8ff8 in DB::ExecutionThreadContext::executeTask() build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:68:9
    #10 0x241bb620 in DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:217:26
    #11 0x241baf86 in DB::PipelineExecutor::executeSingleThread(unsigned long) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:182:5
    #12 0x241baf86 in DB::PipelineExecutor::executeImpl(unsigned long) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:328:9
    #13 0x241baaec in DB::PipelineExecutor::execute(unsigned long) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:88:9
    #14 0x241cd9a2 in DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long) build_docker/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:78:24
    #15 0x241cd901 in DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0::operator()() const build_docker/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:105:13
    #16 0x241cd901 in decltype(static_cast<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(fp)()) std::__1::__invoke_constexpr<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&) build_docker/../contrib/libcxx/include/type_traits:3648:23
    #17 0x241cd7ba in decltype(auto) std::__1::__apply_tuple_impl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/tuple:1595:1
    #18 0x241cd7ba in decltype(auto) std::__1::apply<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&) build_docker/../contrib/libcxx/include/tuple:1604:1
    #19 0x241cd7ba in ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()::operator()() build_docker/../src/Common/ThreadPool.h:188:13
    #20 0x241cd7ba in decltype(static_cast<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(fp)()) std::__1::__invoke<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&) build_docker/../contrib/libcxx/include/type_traits:3640:23
    #21 0xf94bdf9 in std::__1::__function::__policy_func<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:843:16
    #22 0xf94bdf9 in std::__1::function<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:1184:12
    #23 0xf94bdf9 in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) build_docker/../src/Common/ThreadPool.cpp:281:17
    #24 0xf94e8c1 in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()::operator()() const build_docker/../src/Common/ThreadPool.cpp:143:73
    #25 0xf94e8c1 in decltype(static_cast<void>(fp)()) std::__1::__invoke<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&) build_docker/../contrib/libcxx/include/type_traits:3640:23
    #26 0xf94e8c1 in void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/thread:282:5
    #27 0xf94e8c1 in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) build_docker/../contrib/libcxx/include/thread:293:5
    #28 0x7faa72105608 in start_thread /build/glibc-sMfBJT/glibc-2.31/nptl/pthread_create.c:477:8
    #29 0x7faa7202a162 in __clone /build/glibc-sMfBJT/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95

```

```
2022.05.19 14:49:51.080277 [ 674 ] {} <Fatal> BaseDaemon: ########################################
2022.05.19 14:49:51.080349 [ 674 ] {} <Fatal> BaseDaemon: (version 22.6.1.1, build id: 4A50E3FD081BE78A) (from thread 417) (query_id: 07b6e64a-8c21-4b6a-ab35-3a6cda92c93a) (query: SELECT nth_value(NULL, 1048577) OVER (Rows BETWEEN 1023 FOLLOWING AND UNBOUNDED FOLLOWING)) Received signal Unknown signal (-3)
2022.05.19 14:49:51.080378 [ 674 ] {} <Fatal> BaseDaemon: Sanitizer trap.
2022.05.19 14:49:51.080425 [ 674 ] {} <Fatal> BaseDaemon: Stack trace: 0xf89c52a 0x21841d11 0xf852256 0xf85ec1f 0x245a88f2 0x245a7fc4 0x2459a364 0x245b4871 0x2459fc7a 0x245a09ee 0x245a5794 0x241c92b9 0x241c8ff9 0x241bb621 0x241baf87 0x241baaed 0x241cd9a3 0x241cd902 0x241cd7bb 0xf94bdfa 0xf94e8c2 0x7faa72105609 0x7faa7202a163
2022.05.19 14:49:51.088776 [ 674 ] {} <Fatal> BaseDaemon: 0.1. inlined from ./build_docker/../src/Common/StackTrace.cpp:305: StackTrace::tryCapture()
2022.05.19 14:49:51.088813 [ 674 ] {} <Fatal> BaseDaemon: 0. ../src/Common/StackTrace.cpp:266: StackTrace::StackTrace() @ 0xf89c52a in /workspace/clickhouse
2022.05.19 14:49:51.107436 [ 674 ] {} <Fatal> BaseDaemon: 1. ./build_docker/../src/Daemon/BaseDaemon.cpp:0: sanitizerDeathCallback() @ 0x21841d11 in /workspace/clickhouse
2022.05.19 14:49:52.087242 [ 674 ] {} <Fatal> BaseDaemon: 2. __sanitizer::Die() @ 0xf852256 in /workspace/clickhouse
2022.05.19 14:49:53.052385 [ 674 ] {} <Fatal> BaseDaemon: 3. ? @ 0xf85ec1f in /workspace/clickhouse
2022.05.19 14:49:54.016663 [ 674 ] {} <Fatal> BaseDaemon: 4. ? @ 0x245a88f2 in /workspace/clickhouse
2022.05.19 14:49:54.062983 [ 674 ] {} <Fatal> BaseDaemon: 5. ./build_docker/../src/Processors/Transforms/WindowTransform.h:173: DB::WindowTransform::blockRowsNumber(DB::RowNumber const&) const @ 0x245a7fc4 in /workspace/clickhouse
2022.05.19 14:49:54.107769 [ 674 ] {} <Fatal> BaseDaemon: 6. ./build_docker/../src/Processors/Transforms/WindowTransform.cpp:436: DB::WindowTransform::moveRowNumberNoCheck(DB::RowNumber const&, long) const @ 0x2459a364 in /workspace/clickhouse
2022.05.19 14:49:54.198320 [ 674 ] {} <Fatal> BaseDaemon: 7.1. inlined from ./build_docker/../contrib/libcxx/include/tuple:262: __tuple_leaf<DB::RowNumber &, void>
2022.05.19 14:49:54.198364 [ 674 ] {} <Fatal> BaseDaemon: 7.2. inlined from ../contrib/libcxx/include/tuple:400: __tuple_impl<0UL, 1UL, DB::RowNumber, long, DB::RowNumber &, long &>
2022.05.19 14:49:54.198380 [ 674 ] {} <Fatal> BaseDaemon: 7.3. inlined from ../contrib/libcxx/include/tuple:627: tuple<DB::RowNumber &, long &, 0>
2022.05.19 14:49:54.198398 [ 674 ] {} <Fatal> BaseDaemon: 7.4. inlined from ../src/Processors/Transforms/WindowTransform.cpp:508: DB::WindowTransform::moveRowNumber(DB::RowNumber const&, long) const
2022.05.19 14:49:54.198414 [ 674 ] {} <Fatal> BaseDaemon: 7. ../src/Processors/Transforms/WindowTransform.cpp:2138: DB::WindowFunctionNthValue::windowInsertResultInto(DB::WindowTransform const*, unsigned long) @ 0x245b4871 in /workspace/clickhouse
2022.05.19 14:49:54.243869 [ 674 ] {} <Fatal> BaseDaemon: 8. ./build_docker/../src/Processors/Transforms/WindowTransform.cpp:976: DB::WindowTransform::writeOutCurrentRow() @ 0x2459fc7a in /workspace/clickhouse
2022.05.19 14:49:54.289008 [ 674 ] {} <Fatal> BaseDaemon: 9. ./build_docker/../src/Processors/Transforms/WindowTransform.cpp:1192: DB::WindowTransform::appendChunk(DB::Chunk&) @ 0x245a09ee in /workspace/clickhouse
2022.05.19 14:49:54.335466 [ 674 ] {} <Fatal> BaseDaemon: 10. ./build_docker/../src/Processors/Transforms/WindowTransform.cpp:1440: DB::WindowTransform::work() @ 0x245a5794 in /workspace/clickhouse
2022.05.19 14:49:54.342387 [ 674 ] {} <Fatal> BaseDaemon: 11. ./build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::executeJob(DB::IProcessor*) @ 0x241c92b9 in /workspace/clickhouse
2022.05.19 14:49:54.348825 [ 674 ] {} <Fatal> BaseDaemon: 12. ./build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:70: DB::ExecutionThreadContext::executeTask() @ 0x241c8ff9 in /workspace/clickhouse
2022.05.19 14:49:54.363987 [ 674 ] {} <Fatal> BaseDaemon: 13. ./build_docker/../src/Processors/Executors/PipelineExecutor.cpp:217: DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x241bb621 in /workspace/clickhouse
2022.05.19 14:49:54.377070 [ 674 ] {} <Fatal> BaseDaemon: 14. ./build_docker/../src/Processors/Executors/PipelineExecutor.cpp:330: DB::PipelineExecutor::executeImpl(unsigned long) @ 0x241baf87 in /workspace/clickhouse
2022.05.19 14:49:54.391670 [ 674 ] {} <Fatal> BaseDaemon: 15.1. inlined from ./build_docker/../contrib/libcxx/include/__memory/unique_ptr.h:284: std::__1::unique_ptr<DB::ExecutingGraph, std::__1::default_delete<DB::ExecutingGraph> >::operator->() const
2022.05.19 14:49:54.391710 [ 674 ] {} <Fatal> BaseDaemon: 15. ../src/Processors/Executors/PipelineExecutor.cpp:91: DB::PipelineExecutor::execute(unsigned long) @ 0x241baaed in /workspace/clickhouse
2022.05.19 14:49:54.406728 [ 674 ] {} <Fatal> BaseDaemon: 16. ./build_docker/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:0: DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long) @ 0x241cd9a3 in /workspace/clickhouse
2022.05.19 14:49:54.421694 [ 674 ] {} <Fatal> BaseDaemon: 17. ./build_docker/../contrib/libcxx/include/type_traits:3648: decltype(static_cast<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(fp)()) std::__1::__invoke_constexpr<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&) @ 0x241cd902 in /workspace/clickhouse
2022.05.19 14:49:54.436713 [ 674 ] {} <Fatal> BaseDaemon: 18.1. inlined from ./build_docker/../contrib/libcxx/include/tuple:0: operator()
2022.05.19 14:49:54.436753 [ 674 ] {} <Fatal> BaseDaemon: 18. ../contrib/libcxx/include/type_traits:3640: decltype(static_cast<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(fp)()) std::__1::__invoke<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&) @ 0x241cd7bb in /workspace/clickhouse
2022.05.19 14:49:54.446748 [ 674 ] {} <Fatal> BaseDaemon: 19.1. inlined from ./build_docker/../contrib/libcxx/include/__functional/function.h:1157: std::__1::function<void ()>::operator=(std::nullptr_t)
2022.05.19 14:49:54.446781 [ 674 ] {} <Fatal> BaseDaemon: 19. ../src/Common/ThreadPool.cpp:284: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xf94bdfa in /workspace/clickhouse
2022.05.19 14:49:54.458366 [ 674 ] {} <Fatal> BaseDaemon: 20. ./build_docker/../src/Common/ThreadPool.cpp:0: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) @ 0xf94e8c2 in /workspace/clickhouse
2022.05.19 14:49:54.458398 [ 674 ] {} <Fatal> BaseDaemon: 21. ? @ 0x7faa72105609 in ?
2022.05.19 14:49:54.458416 [ 674 ] {} <Fatal> BaseDaemon: 22. __clone @ 0x7faa7202a163 in ?
2022.05.19 14:49:54.741915 [ 674 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: EC789E67D8738F146E84B5358799B3F7. There is no information about the reference checksum.

```

**Comment by alexey-milovidov** [comment]
Let's revert the n-th value function again.
