### ISSUE TITLE
Exported parquet file is corrupted

### ISSUE THREAD

**Issue by wildmb** [ClickHouse/ClickHouse#37687]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
Data is selected from clickhouse and saved it to file in parquet format. The parquet file looks good if few rows are returned, however, the exported parquet file is corrupted if too many rows.

**How to reproduce**
* Which ClickHouse server version to use
22.3
* Queries to run that lead to unexpected result
```
> brew install parquet-cli
> clickhouse-client --query 'SELECT * FROM system.numbers LIMIT 10000 FORMAT Parquet' > numbers.pq
> parquet meta numbers.pq

File path:  numbers.pq
Created by: parquet-cpp version 1.5.1-SNAPSHOT
Properties: (none)
Schema:
message schema {
  required int64 number (INTEGER(64,false));
}


Row group 0:  count: 10000  5.76 B records  start: 4  total: 56.285 kB
--------------------------------------------------------------------------------
        type      encodings count     avg size   nulls   min / max
number  INT64     S _ R     10000     5.76 B     0       "0" / "9999"

> clickhouse-client --query 'SELECT * FROM system.numbers LIMIT 1000000 FORMAT Parquet' > numbers.pq
> parquet meta numbers.pq
Unknown error
java.io.IOException: can not read class org.apache.parquet.format.FileMetaData: Required field 'version' was not found in serialized data! Struct: org.apache.parquet.format.FileMetaData$FileMetaDataStandardScheme@3116c353
	at org.apache.parquet.format.Util.read(Util.java:365)
	at org.apache.parquet.format.Util.readFileMetaData(Util.java:151)
	at org.apache.parquet.format.converter.ParquetMetadataConverter$3.visit(ParquetMetadataConverter.java:1333)
	at org.apache.parquet.format.converter.ParquetMetadataConverter$3.visit(ParquetMetadataConverter.java:1330)
	at org.apache.parquet.format.converter.ParquetMetadataConverter$NoFilter.accept(ParquetMetadataConverter.java:1155)
	at org.apache.parquet.format.converter.ParquetMetadataConverter.readParquetMetadata(ParquetMetadataConverter.java:1330)
	at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:582)
	at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:527)
	at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:521)
	at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:469)
	at org.apache.parquet.cli.commands.ParquetMetadataCommand.run(ParquetMetadataCommand.java:75)
	at org.apache.parquet.cli.Main.run(Main.java:155)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
	at org.apache.parquet.cli.Main.main(Main.java:185)
Caused by: shaded.parquet.org.apache.thrift.protocol.TProtocolException: Required field 'version' was not found in serialized data! Struct: org.apache.parquet.format.FileMetaData$FileMetaDataStandardScheme@3116c353
	at org.apache.parquet.format.FileMetaData$FileMetaDataStandardScheme.read(FileMetaData.java:1380)
	at org.apache.parquet.format.FileMetaData$FileMetaDataStandardScheme.read(FileMetaData.java:1242)
	at org.apache.parquet.format.FileMetaData.read(FileMetaData.java:1116)
	at org.apache.parquet.format.Util.read(Util.java:362)
	... 13 more
```

**Expected behavior**
The exported parquet file must be valid.

**Error message and/or stacktrace**

**Additional context**

**Comment by Avogar** [comment]
Cannot reproduce. For me everything works ok:
```bash
$ ./clickhouse client --version
ClickHouse client version 22.3.2.1.
$ ./clickhouse client --query 'SELECT * FROM system.numbers LIMIT 1000000 FORMAT Parquet' > numbers.parquet
$ parquet meta numbers.parquet
File path:  numbers.parquet
Created by: parquet-cpp version 1.5.1-SNAPSHOT
Properties: (none)
Schema:
message schema {
  required int64 number (INTEGER(64,false));
}


Row group 0:  count: 65505  6,01 B records  start: 4  total: 384,192 kB
--------------------------------------------------------------------------------
        type      encodings count     avg size   nulls   min / max
number  INT64     S _ R     65505     6,01 B     0       "0" / "65504"

Row group 1:  count: 65505  6,01 B records  start: 393500  total: 384,172 kB
--------------------------------------------------------------------------------
        type      encodings count     avg size   nulls   min / max
number  INT64     S _ R     65505     6,01 B     0       "65505" / "131009"

Row group 2:  count: 65505  6,01 B records  start: 786977  total: 384,182 kB
--------------------------------------------------------------------------------
        type      encodings count     avg size   nulls   min / max
number  INT64     S _ R     65505     6,01 B     0       "131010" / "196514"

Row group 3:  count: 65505  6,01 B records  start: 1180466  total: 384,176 kB
--------------------------------------------------------------------------------
        type      encodings count     avg size   nulls   min / max
number  INT64     S _ R     65505     6,01 B     0       "196515" / "262019"

Row group 4:  count: 65505  6,01 B records  start: 1573950  total: 384,177 kB
--------------------------------------------------------------------------------
        type      encodings count     avg size   nulls   min / max
number  INT64     S _ R     65505     6,01 B     0       "262020" / "327524"

Row group 5:  count: 65505  6,01 B records  start: 1967435  total: 384,175 kB
--------------------------------------------------------------------------------
        type      encodings count     avg size   nulls   min / max
number  INT64     S _ R     65505     6,01 B     0       "327525" / "393029"

Row group 6:  count: 65505  6,01 B records  start: 2360918  total: 384,174 kB
--------------------------------------------------------------------------------
        type      encodings count     avg size   nulls   min / max
number  INT64     S _ R     65505     6,01 B     0       "393030" / "458534"

Row group 7:  count: 65505  6,01 B records  start: 2754400  total: 384,182 kB
--------------------------------------------------------------------------------
        type      encodings count     avg size   nulls   min / max
number  INT64     S _ R     65505     6,01 B     0       "458535" / "524039"

Row group 8:  count: 65505  6,01 B records  start: 3147890  total: 384,186 kB
--------------------------------------------------------------------------------
        type      encodings count     avg size   nulls   min / max
number  INT64     S _ R     65505     6,01 B     0       "524040" / "589544"

Row group 9:  count: 65505  6,01 B records  start: 3541384  total: 384,188 kB
--------------------------------------------------------------------------------
        type      encodings count     avg size   nulls   min / max
number  INT64     S _ R     65505     6,01 B     0       "589545" / "655049"

Row group 10:  count: 65505  6,01 B records  start: 3934881  total: 384,170 kB
--------------------------------------------------------------------------------
        type      encodings count     avg size   nulls   min / max
number  INT64     S _ R     65505     6,01 B     0       "655050" / "720554"

Row group 11:  count: 65505  6,01 B records  start: 4328359  total: 384,197 kB
--------------------------------------------------------------------------------
        type      encodings count     avg size   nulls   min / max
number  INT64     S _ R     65505     6,01 B     0       "720555" / "786059"

Row group 12:  count: 65505  6,01 B records  start: 4721865  total: 384,175 kB
--------------------------------------------------------------------------------
        type      encodings count     avg size   nulls   min / max
number  INT64     S _ R     65505     6,01 B     0       "786060" / "851564"

Row group 13:  count: 65505  6,01 B records  start: 5115348  total: 384,183 kB
--------------------------------------------------------------------------------
        type      encodings count     avg size   nulls   min / max
number  INT64     S _ R     65505     6,01 B     0       "851565" / "917069"

Row group 14:  count: 65505  6,01 B records  start: 5508839  total: 384,172 kB
--------------------------------------------------------------------------------
        type      encodings count     avg size   nulls   min / max
number  INT64     S _ R     65505     6,01 B     0       "917070" / "982574"

Row group 15:  count: 17425  5,89 B records  start: 5902319  total: 100,150 kB
--------------------------------------------------------------------------------
        type      encodings count     avg size   nulls   min / max
number  INT64     S _ R     17425     5,89 B     0       "982575" / "999999"
```

**Comment by Avogar** [comment]
Hexdump of file that was created inside docker container (valid Parquet file):
```
00000000  50 41 52 31 15 04 15 10  15 14 4c 15 02 15 04 12  |PAR1......L.....|
00000010  00 00 08 1c 00 00 00 00  00 00 00 00 15 00 15 06  |................|
00000020  15 0a 2c 15 02 15 04 15  06 15 06 1c 36 00 28 08  |..,.........6.(.|
00000030  00 00 00 00 00 00 00 00  18 08 00 00 00 00 00 00  |................|
00000040  00 00 00 00 00 03 08 01  02 00 26 94 01 1c 15 04  |..........&.....|
00000050  19 35 04 00 06 19 18 06  6e 75 6d 62 65 72 15 02  |.5......number..|
00000060  16 02 16 84 01 16 8c 01  26 38 26 08 1c 36 00 28  |........&8&..6.(|
00000070  08 00 00 00 00 00 00 00  00 18 08 00 00 00 00 00  |................|
00000080  00 00 00 00 19 2c 15 04  15 04 15 02 00 15 00 15  |.....,..........|
00000090  04 15 02 00 00 00 15 02  19 2c 35 00 18 06 73 63  |.........,5...sc|
000000a0  68 65 6d 61 15 02 00 15  04 25 00 18 06 6e 75 6d  |hema.....%...num|
000000b0  62 65 72 25 1c 4c ac 13  40 12 00 00 00 16 02 19  |ber%.L..@.......|
000000c0  1c 19 1c 26 94 01 1c 15  04 19 35 04 00 06 19 18  |...&......5.....|
000000d0  06 6e 75 6d 62 65 72 15  02 16 02 16 84 01 16 8c  |.number.........|
000000e0  01 26 38 26 08 1c 36 00  28 08 00 00 00 00 00 00  |.&8&..6.(.......|
000000f0  00 00 18 08 00 00 00 00  00 00 00 00 00 19 2c 15  |..............,.|
00000100  04 15 04 15 02 00 15 00  15 04 15 02 00 00 00 16  |................|
00000110  84 01 16 02 26 08 16 8c  01 14 00 00 28 22 70 61  |....&.......("pa|
00000120  72 71 75 65 74 2d 63 70  70 20 76 65 72 73 69 6f  |rquet-cpp versio|
00000130  6e 20 31 2e 35 2e 31 2d  53 4e 41 50 53 48 4f 54  |n 1.5.1-SNAPSHOT|
00000140  19 1c 1c 00 00 00 b0 00  00 00 50 41 52 31        |..........PAR1|
0000014e
```

Hexdump of file that was created by running `docker exec -it ... clickhouse-client --query ...` (not valid parquet file):
```
00000000  50 41 52 31 15 04 15 10  15 14 4c 15 02 15 04 12  |PAR1......L.....|
00000010  00 00 08 1c 00 00 00 00  00 00 00 00 15 00 15 06  |................|
00000020  15 0d 0a 2c 15 02 15 04  15 06 15 06 1c 36 00 28  |...,.........6.(|
00000030  08 00 00 00 00 00 00 00  00 18 08 00 00 00 00 00  |................|
00000040  00 00 00 00 00 00 03 08  01 02 00 26 94 01 1c 15  |...........&....|
00000050  04 19 35 04 00 06 19 18  06 6e 75 6d 62 65 72 15  |..5......number.|
00000060  02 16 02 16 84 01 16 8c  01 26 38 26 08 1c 36 00  |.........&8&..6.|
00000070  28 08 00 00 00 00 00 00  00 00 18 08 00 00 00 00  |(...............|
00000080  00 00 00 00 00 19 2c 15  04 15 04 15 02 00 15 00  |......,.........|
00000090  15 04 15 02 00 00 00 15  02 19 2c 35 00 18 06 73  |..........,5...s|
000000a0  63 68 65 6d 61 15 02 00  15 04 25 00 18 06 6e 75  |chema.....%...nu|
000000b0  6d 62 65 72 25 1c 4c ac  13 40 12 00 00 00 16 02  |mber%.L..@......|
000000c0  19 1c 19 1c 26 94 01 1c  15 04 19 35 04 00 06 19  |....&......5....|
000000d0  18 06 6e 75 6d 62 65 72  15 02 16 02 16 84 01 16  |..number........|
000000e0  8c 01 26 38 26 08 1c 36  00 28 08 00 00 00 00 00  |..&8&..6.(......|
000000f0  00 00 00 18 08 00 00 00  00 00 00 00 00 00 19 2c  |...............,|
00000100  15 04 15 04 15 02 00 15  00 15 04 15 02 00 00 00  |................|
00000110  16 84 01 16 02 26 08 16  8c 01 14 00 00 28 22 70  |.....&.......("p|
00000120  61 72 71 75 65 74 2d 63  70 70 20 76 65 72 73 69  |arquet-cpp versi|
00000130  6f 6e 20 31 2e 35 2e 31  2d 53 4e 41 50 53 48 4f  |on 1.5.1-SNAPSHO|
00000140  54 19 1c 1c 00 00 00 b0  00 00 00 50 41 52 31     |T..........PAR1|
0000014f
```

The difference is that the second file contains one extra byte:
Valid file:        `... 15 0a 2c ...`
Not valid file: `... 15 0d 0a 2c ...`

By now I have no idea what is the reason

**Comment by Avogar** [comment]
There is an issue with docker. Similar issue was here: https://github.com/ClickHouse/ClickHouse/issues/9987
Additional byte `0d` is carriage return symbol `\r`. Removing `-t` flag while running docker command solves the problem.

**Comment by wildmb** [comment]
Thanks, @Avogar
