### ISSUE TITLE
UBsan report in OpenTelemetrySpanLog: runtime error: load of value 43, which is not a valid value for type 'Types::Which'

### ISSUE THREAD

**Issue by CurtizJ** [ClickHouse/ClickHouse#38032]
**Describe the bug**
https://s3.amazonaws.com/clickhouse-test-reports/0/cf47b1c96e2dfa3183f9d4ceca5cbb3f29c7be6e/stress_test__undefined__actions_.html

```
../src/Core/Field.h:594:23: runtime error: load of value 43, which is not a valid value for type 'Types::Which'
    #0 0x229fd6c4 in auto DB::Field::dispatch<DB::toString(DB::Field const&)::$_4, DB::Field const&>(DB::toString(DB::Field const&)::$_4&&, DB::Field const&) build_docker/../src/Core/Field.h:594:23
    #1 0x229fd53c in DB::toString(DB::Field const&) build_docker/../src/Core/Field.cpp:552:12
    #2 0x23c1a274 in DB::OpenTelemetrySpanLogElement::appendToBlock(std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&) const build_docker/../src/Interpreters/OpenTelemetrySpanLog.cpp:71:58
    #3 0x23dda26f in DB::SystemLog<DB::OpenTelemetrySpanLogElement>::flushImpl(std::__1::vector<DB::OpenTelemetrySpanLogElement, std::__1::allocator<DB::OpenTelemetrySpanLogElement> > const&, unsigned long) build_docker/../src/Interpreters/SystemLog.cpp:400:18
    #4 0x23dd8aa1 in DB::SystemLog<DB::OpenTelemetrySpanLogElement>::savingThreadFunction() build_docker/../src/Interpreters/SystemLog.cpp:364:17
    #5 0x10019728 in DB::ISystemLog::startup()::$_0::operator()() const build_docker/../src/Common/SystemLogBase.cpp:63:51
    #6 0x10019728 in decltype(static_cast<DB::ISystemLog::startup()::$_0&>(fp)()) std::__1::__invoke_constexpr<DB::ISystemLog::startup()::$_0&>(DB::ISystemLog::startup()::$_0&) build_docker/../contrib/libcxx/include/type_traits:3648:23
    #7 0x10019728 in decltype(auto) std::__1::__apply_tuple_impl<DB::ISystemLog::startup()::$_0&, std::__1::tuple<>&>(DB::ISystemLog::startup()::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/tuple:1595:1
    #8 0x10019728 in decltype(auto) std::__1::apply<DB::ISystemLog::startup()::$_0&, std::__1::tuple<>&>(DB::ISystemLog::startup()::$_0&, std::__1::tuple<>&) build_docker/../contrib/libcxx/include/tuple:1604:1
    #9 0x10019728 in ThreadFromGlobalPool::ThreadFromGlobalPool<DB::ISystemLog::startup()::$_0>(DB::ISystemLog::startup()::$_0&&)::'lambda'()::operator()() build_docker/../src/Common/ThreadPool.h:188:13
    #10 0x10019728 in decltype(static_cast<DB::ISystemLog::startup()::$_0>(fp)()) std::__1::__invoke<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::ISystemLog::startup()::$_0>(DB::ISystemLog::startup()::$_0&&)::'lambda'()&>(DB::ISystemLog::startup()::$_0&&) build_docker/../contrib/libcxx/include/type_traits:3640:23
    #11 0xfe3fc00 in std::__1::__function::__policy_func<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:843:16
    #12 0xfe3fc00 in std::__1::function<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:1184:12
    #13 0xfe3fc00 in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) build_docker/../src/Common/ThreadPool.cpp:281:17
    #14 0xfe427c1 in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()::operator()() const build_docker/../src/Common/ThreadPool.cpp:143:73
    #15 0xfe427c1 in decltype(static_cast<void>(fp)()) std::__1::__invoke<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&) build_docker/../contrib/libcxx/include/type_traits:3640:23
    #16 0xfe427c1 in void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/thread:282:5
    #17 0xfe427c1 in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) build_docker/../contrib/libcxx/include/thread:293:5
    #18 0x7f4cbf2c5608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8608) (BuildId: 7b4536f41cdaa5888408e82d0836e33dcf436466)
    #19 0x7f4cbf1ea132 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x11f132) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)
```

**Comment by tavplubix** [comment]
```
=================================================================
==682==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60604d091a48 at pc 0x00002ae9766f bp 0x7f25d443dd10 sp 0x7f25d443dd08
READ of size 4 at 0x60604d091a48 thread T143 (SystemLogFlush)
    #0 0x2ae9766e in auto DB::Field::dispatch<DB::toString(DB::Field const&)::$_4, DB::Field const&>(DB::toString(DB::Field const&)::$_4&&, DB::Field const&) build_docker/../src/Core/Field.h:594:23
    #1 0x2ae9766e in DB::toString(DB::Field const&) build_docker/../src/Core/Field.cpp:552:12
    #2 0x2d8dc3d7 in DB::OpenTelemetrySpanLogElement::appendToBlock(std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&) const build_docker/../src/Interpreters/OpenTelemetrySpanLog.cpp:71:58
    #3 0x2dbc90fb in DB::SystemLog<DB::OpenTelemetrySpanLogElement>::flushImpl(std::__1::vector<DB::OpenTelemetrySpanLogElement, std::__1::allocator<DB::OpenTelemetrySpanLogElement> > const&, unsigned long) build_docker/../src/Interpreters/SystemLog.cpp:400:18
    #4 0x2dbc6fde in DB::SystemLog<DB::OpenTelemetrySpanLogElement>::savingThreadFunction() build_docker/../src/Interpreters/SystemLog.cpp:364:17
    #5 0xdc7df3d in DB::ISystemLog::startup()::$_0::operator()() const build_docker/../src/Common/SystemLogBase.cpp:63:51
    #6 0xdc7df3d in decltype(static_cast<DB::ISystemLog::startup()::$_0&>(fp)()) std::__1::__invoke_constexpr<DB::ISystemLog::startup()::$_0&>(DB::ISystemLog::startup()::$_0&) build_docker/../contrib/libcxx/include/type_traits:3648:23
    #7 0xdc7df3d in decltype(auto) std::__1::__apply_tuple_impl<DB::ISystemLog::startup()::$_0&, std::__1::tuple<>&>(DB::ISystemLog::startup()::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/tuple:1595:1
    #8 0xdc7df3d in decltype(auto) std::__1::apply<DB::ISystemLog::startup()::$_0&, std::__1::tuple<>&>(DB::ISystemLog::startup()::$_0&, std::__1::tuple<>&) build_docker/../contrib/libcxx/include/tuple:1604:1
    #9 0xdc7df3d in ThreadFromGlobalPool::ThreadFromGlobalPool<DB::ISystemLog::startup()::$_0>(DB::ISystemLog::startup()::$_0&&)::'lambda'()::operator()() build_docker/../src/Common/ThreadPool.h:188:13
    #10 0xdc7df3d in decltype(static_cast<DB::ISystemLog::startup()::$_0>(fp)()) std::__1::__invoke<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::ISystemLog::startup()::$_0>(DB::ISystemLog::startup()::$_0&&)::'lambda'()&>(DB::ISystemLog::startup()::$_0&&) build_docker/../contrib/libcxx/include/type_traits:3640:23
    #11 0xdc7df3d in void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::ISystemLog::startup()::$_0>(DB::ISystemLog::startup()::$_0&&)::'lambda'()&>(ThreadFromGlobalPool::ThreadFromGlobalPool<DB::ISystemLog::startup()::$_0>(DB::ISystemLog::startup()::$_0&&)::'lambda'()&) build_docker/../contrib/libcxx/include/__functional/invoke.h:61:9
    #12 0xdc7df3d in std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::ISystemLog::startup()::$_0>(DB::ISystemLog::startup()::$_0&&)::'lambda'(), void ()>::operator()() build_docker/../contrib/libcxx/include/__functional/function.h:230:12
    #13 0xdc7df3d in void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::ISystemLog::startup()::$_0>(DB::ISystemLog::startup()::$_0&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) build_docker/../contrib/libcxx/include/__functional/function.h:711:16
    #14 0xd87b5c6 in std::__1::__function::__policy_func<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:843:16
    #15 0xd87b5c6 in std::__1::function<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:1184:12
    #16 0xd87b5c6 in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) build_docker/../src/Common/ThreadPool.cpp:281:17
    #17 0xd8836fb in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()::operator()() const build_docker/../src/Common/ThreadPool.cpp:143:73
    #18 0xd8836fb in decltype(static_cast<void>(fp)()) std::__1::__invoke<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&) build_docker/../contrib/libcxx/include/type_traits:3640:23
    #19 0xd8836fb in void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/thread:282:5
    #20 0xd8836fb in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) build_docker/../contrib/libcxx/include/thread:293:5
    #21 0x7f271c35c608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8608) (BuildId: 7b4536f41cdaa5888408e82d0836e33dcf436466)
    #22 0x7f271c281132 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x11f132) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)
```

https://pastila.nl/?005298ed/77a28c99f624ed4d4d9fd3ce2dfd1b8d

https://s3.amazonaws.com/clickhouse-test-reports/38106/9cac78b49865fc83be8255abac3115a63cfd289a/stress_test__address__actions_.html

**Comment by tavplubix** [comment]
Looks related to #37837

**Comment by tavplubix** [comment]
> heap-buffer-overflow on address 0x60604d091a48

It's potential security issue (address is not nullptr) and we're going to make a release soon, so I'd revert it

**Comment by qoega** [comment]
>2022.06.16 00:59:55.279380 [ 180276 ] {} <Fatal> BaseDaemon: (version 22.6.1.1, build id: 4CCD58AF96F208D2) (from thread 832) (no query) Received signal Unknown signal (-3)

no query will make it fun to reproduce..
