### ISSUE TITLE
HedgedConnections: boost fiber assert when running test in debug+asan

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#38143]
```./clickhouse-test -b ~/clickhouse -q queries --order random --no-random-settings -j 10```

```
    void deallocate() noexcept override final {
        BOOST_ASSERT( main_ctx || ( ! main_ctx && terminated) );
        destroy( this);
    }
```

```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7d9e859 in __GI_abort () at abort.c:79
#2  0x00007ffff7d9e729 in __assert_fail_base (fmt=0x7ffff7f34588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x100dcbe0 <str> "main_ctx || ( ! main_ctx && terminated)", file=0x100dbec0 <str> "../contrib/boost/boost/context/fiber_ucontext.hpp", line=268, function=<optimized out>) at assert.c:92
#3  0x00007ffff7db0006 in __GI___assert_fail (assertion=0x100dcbe0 <str> "main_ctx || ( ! main_ctx && terminated)", file=0x100dbec0 <str> "../contrib/boost/boost/context/fiber_ucontext.hpp", line=268, function=0x100dcc40 <__PRETTY_FUNCTION__._ZN5boost7context6detail20fiber_capture_recordINS0_5fiberER10FiberStackN2DB14PacketReceiver7RoutineEE10deallocateEv> "virtual void boost::context::detail::fiber_capture_record<boost::context::fiber, FiberStack &, DB::PacketReceiver::Routine>::deallocate() [Ctx = boost::context::fiber, StackAlloc = FiberStack &, Fn = "...) at assert.c:101
#4  0x0000000045f01b39 in boost::context::detail::fiber_capture_record<boost::context::fiber, FiberStack&, DB::PacketReceiver::Routine>::deallocate (this=0x7ffee9ba9b00) at ../contrib/boost/boost/context/fiber_ucontext.hpp:268
#5  0x00000000401eaba3 in boost::context::fiber::~fiber (this=0x7ffeec9dc840) at ../contrib/boost/boost/context/fiber_ucontext.hpp:450
#6  0x0000000045ef3eb3 in DB::PacketReceiver::cancel (this=0x6160005b4d80) at ../src/Client/PacketReceiver.h:59
#7  0x0000000045ee68de in DB::HedgedConnections::finishProcessReplica (this=0x61a00016aa98, replica=..., disconnect=true) at ../src/Client/HedgedConnections.cpp:562
#8  0x0000000045ee64c4 in DB::HedgedConnections::disconnect (this=0x61a00016aa98) at ../src/Client/HedgedConnections.cpp:206
#9  0x000000004019d9f1 in DB::RemoteQueryExecutor::~RemoteQueryExecutor (this=0x6180002e5898) at ../src/QueryPipeline/RemoteQueryExecutor.cpp:165
#10 0x000000001c57ce8c in std::__1::__destroy_at<DB::RemoteQueryExecutor, 0> (__loc=0x6180002e5898) at ../contrib/libcxx/include/__memory/construct_at.h:56
#11 0x000000001c57cd15 in std::__1::destroy_at<DB::RemoteQueryExecutor, 0> (__loc=0x6180002e5898) at ../contrib/libcxx/include/__memory/construct_at.h:81
#12 0x000000001c57ccf9 in std::__1::allocator_traits<std::__1::allocator<DB::RemoteQueryExecutor> >::destroy<DB::RemoteQueryExecutor, void, void> (__p=0x6180002e5898) at ../contrib/libcxx/include/__memory/allocator_traits.h:317
#13 0x000000001c57c506 in std::__1::__shared_ptr_emplace<DB::RemoteQueryExecutor, std::__1::allocator<DB::RemoteQueryExecutor> >::__on_zero_shared (this=0x6180002e5880) at ../contrib/libcxx/include/__memory/shared_ptr.h:310
#14 0x000000001bf1e07c in std::__1::__shared_count::__release_shared (this=0x6180002e5880) at ../contrib/libcxx/include/__memory/shared_ptr.h:174
#15 0x000000001bf1dfd9 in std::__1::__shared_weak_count::__release_shared (this=0x6180002e5880) at ../contrib/libcxx/include/__memory/shared_ptr.h:216
#16 0x000000001c4cffd6 in std::__1::shared_ptr<DB::RemoteQueryExecutor>::~shared_ptr (this=0x614000838d90) at ../contrib/libcxx/include/__memory/shared_ptr.h:703
#17 0x000000004701c3f4 in DB::RemoteSource::~RemoteSource (this=0x614000838c58) at ../src/Processors/Sources/RemoteSource.cpp:23
#18 0x000000001c57ea45 in std::__1::__destroy_at<DB::RemoteSource, 0> (__loc=0x614000838c58) at ../contrib/libcxx/include/__memory/construct_at.h:56
#19 0x000000001c57e875 in std::__1::destroy_at<DB::RemoteSource, 0> (__loc=0x614000838c58) at ../contrib/libcxx/include/__memory/construct_at.h:81
#20 0x000000001c57e859 in std::__1::allocator_traits<std::__1::allocator<DB::RemoteSource> >::destroy<DB::RemoteSource, void, void> (__p=0x614000838c58) at ../contrib/libcxx/include/__memory/allocator_traits.h:317
#21 0x000000001c57e106 in std::__1::__shared_ptr_emplace<DB::RemoteSource, std::__1::allocator<DB::RemoteSource> >::__on_zero_shared (this=0x614000838c40) at ../contrib/libcxx/include/__memory/shared_ptr.h:310
#22 0x000000001bf1e07c in std::__1::__shared_count::__release_shared (this=0x614000838c40) at ../contrib/libcxx/include/__memory/shared_ptr.h:174
#23 0x000000001bf1dfd9 in std::__1::__shared_weak_count::__release_shared (this=0x614000838c40) at ../contrib/libcxx/include/__memory/shared_ptr.h:216
#24 0x000000001c526296 in std::__1::shared_ptr<DB::IProcessor>::~shared_ptr (this=0x60c000ab3f40) at ../contrib/libcxx/include/__memory/shared_ptr.h:703
#25 0x000000001c5261ac in std::__1::__destroy_at<std::__1::shared_ptr<DB::IProcessor>, 0> (__loc=0x60c000ab3f40) at ../contrib/libcxx/include/__memory/construct_at.h:56
#26 0x000000001c526035 in std::__1::destroy_at<std::__1::shared_ptr<DB::IProcessor>, 0> (__loc=0x60c000ab3f40) at ../contrib/libcxx/include/__memory/construct_at.h:81
#27 0x000000001c526019 in std::__1::allocator_traits<std::__1::allocator<std::__1::shared_ptr<DB::IProcessor> > >::destroy<std::__1::shared_ptr<DB::IProcessor>, void, void> (__p=0x60c000ab3f40) at ../contrib/libcxx/include/__memory/allocator_traits.h:317
#28 0x000000001c525f7d in std::__1::vector<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor> > >::__base_destruct_at_end (this=0x7ffeec9dd598, __new_last=0x60c000ab3f40) at ../contrib/libcxx/include/vector:803
#29 0x000000001c525cfa in std::__1::vector<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor> > >::__clear (this=0x7ffeec9dd598) at ../contrib/libcxx/include/vector:797
#30 0x000000001c5254ae in std::__1::vector<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor> > >::~vector (this=0x7ffeec9dd598) at ../contrib/libcxx/include/vector:401
#31 0x000000004013f040 in DB::QueryPipeline::~QueryPipeline (this=0x7ffeec9dd500) at ../src/QueryPipeline/QueryPipeline.cpp:35
#32 0x000000004014a553 in DB::QueryPipeline::reset (this=0x61a0002bcb50) at ../src/QueryPipeline/QueryPipeline.cpp:539
#33 0x00000000436930ca in DB::BlockIO::onException (this=0x61a0002bcb40) at ../src/QueryPipeline/BlockIO.h:48
#34 0x00000000461dcf93 in DB::TCPHandler::runImpl (this=0x61a0002bc880) at ../src/Server/TCPHandler.cpp:397
#35 0x000000004620333e in DB::TCPHandler::run (this=0x61a0002bc880) at ../src/Server/TCPHandler.cpp:1778
#36 0x00000000519880c8 in Poco::Net::TCPServerConnection::start (this=0x61a0002bc880) at ../contrib/poco/Net/src/TCPServerConnection.cpp:43
#37 0x0000000051988c82 in Poco::Net::TCPServerDispatcher::run (this=0x611000598ac0) at ../contrib/poco/Net/src/TCPServerDispatcher.cpp:115
#38 0x0000000051f7be75 in Poco::PooledThread::run (this=0x616000006c80) at ../contrib/poco/Foundation/src/ThreadPool.cpp:199
#39 0x0000000051f741ee in Poco::(anonymous namespace)::RunnableHolder::run (this=0x602000001690) at ../contrib/poco/Foundation/src/Thread.cpp:55
#40 0x0000000051f71a58 in Poco::ThreadImpl::runnableEntry (pThread=0x616000006cb8) at ../contrib/poco/Foundation/src/Thread_POSIX.cpp:345
#41 0x00007ffff7f76609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#42 0x00007ffff7e9b163 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

bt full
https://pastila.nl/?00157c5a/ee8310dff57d555c302ebc8f44f5bdb3

**Comment by alexey-milovidov** [comment]
Duplicate of #50295.
