### ISSUE TITLE
Hung check failed: ParallelParsingInputFormat

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#38558]
https://s3.amazonaws.com/clickhouse-test-reports/0/4cda5491f639081428765181996cf1e118af5cfa/stress_test__address__actions_.html

https://pastila.nl/?002b351d/f0a88a6a03965f500fc559453fc2918d

It's weird that there's no segmentator thread, so it must be a bug.
May be also related to #37649 (but it's unlikely) 

cc: @nikitamikhaylov

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/0/db949553193a8393caed01728d24c6fa2f7b4217/stress_test__address__actions_.html

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/0/5cb3b25754c19fb695d37009fc45371c46e0af2a/stress_test__address__actions_.html

**Comment by alesapin** [comment]
One more https://s3.amazonaws.com/clickhouse-test-reports/40720/4f9faab924a15dec5281a530ca2d1921ec4a2a79/stress_test__address_.html?

**Comment by Algunenano** [comment]
The only report alive looks similar to https://github.com/ClickHouse/ClickHouse/pull/45498 and related to pipeline cancellation. There is one thread waiting for the condition and one thread cancelling the pipeline:

```
#0  0x00007fbf995d8376 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00000000370a80dd in Poco::EventImpl::waitImpl (this=0x60c002882e18) at ../contrib/poco/Foundation/src/Event_POSIX.cpp:106
#2  0x00000000301bc088 in Poco::Event::wait (this=0x60c002882e18) at ../contrib/poco/Foundation/include/Poco/Event.h:97
#3  ThreadFromGlobalPool::join (this=0x60f0016bb438) at ../src/Common/ThreadPool.h:217
#4  DB::PullingAsyncPipelineExecutor::cancel (this=0x7fbc7f80b770) at ../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:182
#5  0x00000000301bbb59 in DB::PullingAsyncPipelineExecutor::~PullingAsyncPipelineExecutor (this=0x7fbc7f80b770) at ../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:57
#6  0x00000000300bcb69 in DB::TCPHandler::processOrdinaryQueryWithProcessors (this=0x61a004ab9e80) at ../src/Server/TCPHandler.cpp:743
```

```
#0  0x00007fbf995d8376 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x000000003e8c0838 in std::__1::__libcpp_condvar_wait (__cv=0x61a0050e7d28, __m=0x80) at ../contrib/libcxx/include/__threading_support:334
#2  std::__1::condition_variable::wait (this=0x61a0050e7d28, lk=...) at ../contrib/libcxx/src/condition_variable.cpp:44
#3  0x0000000030437d5d in std::__1::condition_variable::wait<DB::ParallelParsingInputFormat::generate()::$_1>(std::__1::unique_lock<std::__1::mutex>&, DB::ParallelParsingInputFormat::generate()::$_1) (this=0x61a0050e7d00, __lk=..., __pred=...) at ../contrib/libcxx/include/__mutex_base:403
#4  DB::ParallelParsingInputFormat::generate (this=0x61a0050e7a98) at ../src/Processors/Formats/Impl/ParallelParsingInputFormat.cpp:181
#5  0x000000003016cacf in DB::ISource::tryGenerate (this=0x61a0050e7a98) at ../src/Processors/ISource.cpp:124
#6  0x000000003016bc5f in DB::ISource::work (this=0x61a0050e7a98) at ../src/Processors/ISource.cpp:94
#7  0x00000000301b5fcd in DB::executeJob (node=0x61100245e180, read_progress_callback=0x60d0014b8380) at 
```

It might be different, but since there hasn't been any more reports of this problem let's assume it's been solved.
