### ISSUE TITLE
Test `test_postgresql_database_engine` is flaky with analyzer

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#38677]
https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZEYXkoY2hlY2tfc3RhcnRfdGltZSkgYXMgZCwKY291bnQoKSwgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlciksIGFueShyZXBvcnRfdXJsKQpmcm9tIGNoZWNrcyB3aGVyZSAnMjAyMi0wNC0wMScgPD0gY2hlY2tfc3RhcnRfdGltZSBhbmQgdGVzdF9uYW1lIGxpa2UgJyV0ZXN0X3Bvc3RncmVzcWxfZGF0YWJhc2VfZW5naW5lJScgYW5kIHRlc3Rfc3RhdHVzIG5vdCBpbiAoJ09LJywgJ1NLSVBQRUQnKSBncm91cCBieSBkIG9yZGVyIGJ5IGQgZGVzYw==

May be related to #38369

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/0/0db9c798866951a5c5b4fee55e17c8b65afdeed2/integration_tests__asan__analyzer__[1_6].html

```
2023.07.21 23:48:12.511850 [ 8 ] {1f8db4b7-14c0-463f-b84e-7f868d62995a} <Debug> executeQuery: (from 172.16.15.1:37468) DROP DATABASE postgres_database (stage: Complete)
2023.07.21 23:48:12.512003 [ 8 ] {1f8db4b7-14c0-463f-b84e-7f868d62995a} <Trace> ContextAccess (default): Access granted: DROP DATABASE ON postgres_database.*
2023.07.21 23:48:12.512512 [ 8 ] {1f8db4b7-14c0-463f-b84e-7f868d62995a} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B.
2023.07.21 23:48:12.512548 [ 8 ] {1f8db4b7-14c0-463f-b84e-7f868d62995a} <Debug> TCPHandler: Processed in 0.001344149 sec.
2023.07.21 23:48:12.513122 [ 8 ] {} <Test> TCPHandler: Closing connection (open: true, cancelled: false, eof: true)
2023.07.21 23:48:12.513155 [ 8 ] {} <Debug> TCPHandler: Done processing connection.
2023.07.21 23:48:12.702632 [ 8 ] {} <Trace> TCPHandlerFactory: TCP Request. Address: 172.16.15.1:37474
2023.07.21 23:48:12.702979 [ 8 ] {} <Debug> TCPHandler: Connected ClickHouse client version 23.7.0, revision: 54464, user: default.
2023.07.21 23:48:12.703046 [ 8 ] {} <Debug> TCP-Session: 55c81a16-a853-4072-80ea-a60933269f07 Authenticating user 'default' from 172.16.15.1:37474
2023.07.21 23:48:12.703105 [ 8 ] {} <Debug> TCP-Session: 55c81a16-a853-4072-80ea-a60933269f07 Authenticated with global context as user 94309d50-4f52-5250-31bd-74fecac179db
2023.07.21 23:48:12.703227 [ 8 ] {} <Debug> TCP-Session: 55c81a16-a853-4072-80ea-a60933269f07 Creating session context with user_id: 94309d50-4f52-5250-31bd-74fecac179db
2023.07.21 23:48:12.728161 [ 8 ] {} <Debug> TCP-Session: 55c81a16-a853-4072-80ea-a60933269f07 Creating query context from session context, user_id: 94309d50-4f52-5250-31bd-74fecac179db, parent context user: default
2023.07.21 23:48:12.728505 [ 8 ] {94a3b74b-f3b4-4d3f-8536-8b324ba6d8f5} <Debug> executeQuery: (from 172.16.15.1:37474) SHOW DATABASES (stage: Complete)
2023.07.21 23:48:12.728930 [ 8 ] {94a3b74b-f3b4-4d3f-8536-8b324ba6d8f5} <Debug> executeQuery: (internal) SELECT name FROM system.databases ORDER BY name (stage: Complete)
2023.07.21 23:48:12.729871 [ 8 ] {94a3b74b-f3b4-4d3f-8536-8b324ba6d8f5} <Trace> Planner: Query SELECT system.databases.name AS name FROM system.databases ORDER BY system.databases.name ASC to stage Complete
2023.07.21 23:48:12.730009 [ 8 ] {94a3b74b-f3b4-4d3f-8536-8b324ba6d8f5} <Trace> ContextAccess (default): Access granted: SELECT(name) ON system.databases
2023.07.21 23:48:12.730091 [ 8 ] {94a3b74b-f3b4-4d3f-8536-8b324ba6d8f5} <Trace> ContextAccess (default): Access granted: SHOW DATABASES ON *.*
2023.07.21 23:48:12.730950 [ 8 ] {94a3b74b-f3b4-4d3f-8536-8b324ba6d8f5} <Trace> Planner: Query SELECT system.databases.name AS name FROM system.databases ORDER BY system.databases.name ASC from stage FetchColumns to stage Complete
2023.07.21 23:48:12.733605 [ 7 ] {} <Trace> BaseDaemon: Received signal 11
2023.07.21 23:48:12.734052 [ 7 ] {} <Trace> BaseDaemon: Received signal 11
2023.07.21 23:48:12.734323 [ 288 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2023.07.21 23:48:12.734401 [ 288 ] {} <Fatal> BaseDaemon: (version 23.7.1.1 (official build), build id: 777140AF592F6B5635A1A1CA322127D6B7E9EDC5, git hash: 0db9c798866951a5c5b4fee55e17c8b65afdeed2) (from thread 287) Received signal 11
2023.07.21 23:48:12.734506 [ 288 ] {} <Fatal> BaseDaemon: Signal description: Segmentation fault
2023.07.21 23:48:12.734555 [ 288 ] {} <Fatal> BaseDaemon: Address: 0x7f7daed26018. Access: write. Address not mapped to object.
2023.07.21 23:48:12.734612 [ 288 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000562d3ddf16ca 0x0000562d50d25cfd 0x0000562d50ccd598 0x0000562d50ccc9cb 0x00007f40608c0b43 0x00007f4060952a00
2023.07.21 23:48:12.734652 [ 288 ] {} <Fatal> BaseDaemon: ########################################
2023.07.21 23:48:12.734697 [ 288 ] {} <Fatal> BaseDaemon: (version 23.7.1.1 (official build), build id: 777140AF592F6B5635A1A1CA322127D6B7E9EDC5, git hash: 0db9c798866951a5c5b4fee55e17c8b65afdeed2) (from thread 287) (no query) Received signal Segmentation fault (11)
2023.07.21 23:48:12.734751 [ 288 ] {} <Fatal> BaseDaemon: Address: 0x7f7daed26018. Access: write. Address not mapped to object.
2023.07.21 23:48:12.734779 [ 288 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000562d3ddf16ca 0x0000562d50d25cfd 0x0000562d50ccd598 0x0000562d50ccc9cb 0x00007f40608c0b43 0x00007f4060952a00
2023.07.21 23:48:21.655831 [ 288 ] {} <Fatal> BaseDaemon: 3. __asan_stack_malloc_3 @ 0x00000000120c76ca in /usr/bin/clickhouse
2023.07.21 23:48:21.704893 [ 288 ] {} <Fatal> BaseDaemon: 4. ./build_docker/./src/Loggers/OwnSplitChannel.cpp:22: DB::OwnSplitChannel::log(Poco::Message const&) @ 0x0000000024ffbcfd in /usr/bin/clickhouse
2023.07.21 23:48:21.858180 [ 288 ] {} <Fatal> BaseDaemon: 5. ./build_docker/./src/Daemon/BaseDaemon.cpp:320: SignalListener::onFault(int, siginfo_t const&, ucontext_t*, StackTrace const&, std::vector<std::array<void*, 45ul>, std::allocator<std::array<void*, 45ul>>> const&, unsigned int, DB::ThreadStatus*) const @ 0x0000000024fa3598 in /usr/bin/clickhouse
2023.07.21 23:48:22.156911 [ 288 ] {} <Fatal> BaseDaemon: 6.1. inlined from ./build_docker/./src/Daemon/BaseDaemon.cpp:275: operator()
2023.07.21 23:48:22.157053 [ 288 ] {} <Fatal> BaseDaemon: 6.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<SignalListener::run()::'lambda'()>()()) std::__invoke[abi:v15000]<SignalListener::run()::'lambda'()>(SignalListener::run()::'lambda'()&&)
2023.07.21 23:48:22.157126 [ 288 ] {} <Fatal> BaseDaemon: 6.3. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/thread:284: void std::__thread_execute[abi:v15000]<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, SignalListener::run()::'lambda'()>(std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, SignalListener::run()::'lambda'()>&, std::__tuple_indices<>)
2023.07.21 23:48:22.157177 [ 288 ] {} <Fatal> BaseDaemon: 6. ./build_docker/./contrib/llvm-project/libcxx/include/thread:295: void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, SignalListener::run()::'lambda'()>>(void*) @ 0x0000000024fa29cb in /usr/bin/clickhouse
2023.07.21 23:48:22.157203 [ 288 ] {} <Fatal> BaseDaemon: 7. ? @ 0x00007f40608c0b43 in ?
2023.07.21 23:48:22.157220 [ 288 ] {} <Fatal> BaseDaemon: 8. ? @ 0x00007f4060952a00 in ?
2023.07.21 23:48:22.874792 [ 288 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 1D4816B552AB898621D5EC61710514F9)
2023.07.21 23:48:30.909241 [ 288 ] {} <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
2023.07.21 23:48:34.735756 [ 287 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2023.07.21 23:48:34.735866 [ 287 ] {} <Fatal> BaseDaemon: (version 23.7.1.1 (official build), build id: 777140AF592F6B5635A1A1CA322127D6B7E9EDC5, git hash: 0db9c798866951a5c5b4fee55e17c8b65afdeed2) (from thread 267) Received signal 11
2023.07.21 23:48:34.735908 [ 287 ] {} <Fatal> BaseDaemon: Signal description: Segmentation fault
2023.07.21 23:48:34.735954 [ 287 ] {} <Fatal> BaseDaemon: Address: 0x7f7dc9aa8018. Access: write. Address not mapped to object.
2023.07.21 23:48:34.736025 [ 287 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000562d3ddf1d2a 0x0000562d5055595b 0x0000562d505adec0 0x0000562d505adc3d 0x0000562d505a5a98 0x0000562d645c05ca 0x0000562d645be8d2 0x0000562d675b85c3 0x0000562d507a1ad2 0x0000562d507afdad 0x00007f40608c0b43 0x00007f4060952a00
```
```
=================================================================
==1==ERROR: AddressSanitizer: stack-use-after-return on address 0x7f3dc9a94ee7 at pc 0x562d50cd60b7 bp 0x7f3dafd1e650 sp 0x7f3dafd1e648
READ of size 1 at 0x7f3dc9a94ee7 thread T281
    #0 0x562d50cd60b6 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::operator=(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) build_docker/./contrib/llvm-project/libcxx/include/string
    #1 0x562d50cd60b6 in SignalListener::onFault(int, siginfo_t const&, ucontext_t*, StackTrace const&, std::__1::vector<std::__1::array<void*, 45ul>, std::__1::allocator<std::__1::array<void*, 45ul>>> const&, unsigned int, DB::ThreadStatus*) const build_docker/./src/Daemon/BaseDaemon.cpp:374:22
    #2 0x562d50ccc9ca in SignalListener::run()::'lambda'()::operator()() const build_docker/./src/Daemon/BaseDaemon.cpp:275:41
    #3 0x562d50ccc9ca in decltype(std::declval<SignalListener::run()::'lambda'()>()()) std::__1::__invoke[abi:v15000]<SignalListener::run()::'lambda'()>(SignalListener::run()::'lambda'()&&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #4 0x562d50ccc9ca in void std::__1::__thread_execute[abi:v15000]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, SignalListener::run()::'lambda'()>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, SignalListener::run()::'lambda'()>&, std::__1::__tuple_indices<>) build_docker/./contrib/llvm-project/libcxx/include/thread:284:5
    #5 0x562d50ccc9ca in void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, SignalListener::run()::'lambda'()>>(void*) build_docker/./contrib/llvm-project/libcxx/include/thread:295:5
    #6 0x7f40608c0b42  (/lib/x86_64-linux-gnu/libc.so.6+0x94b42) (BuildId: 69389d485a9793dbe873f0ea2c93e02efaa9aa3d)
    #7 0x7f40609529ff  (/lib/x86_64-linux-gnu/libc.so.6+0x1269ff) (BuildId: 69389d485a9793dbe873f0ea2c93e02efaa9aa3d)

Address 0x7f3dc9a94ee7 is located in stack of thread T261 (ThreadPool) at offset 743 in frame
    #0 0x562d675b828f in void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:712

  This frame has 5 object(s):
    [32, 56) 'ref.tmp.i.i.i32.i.i.i.i.i.i.i.i.i'
    [96, 120) 'ref.tmp.i.i.i.i.i.i.i.i.i.i.i.i'
    [160, 176) 'thread_group.i.i.i.i.i.i.i.i.i'
    [192, 200) 'ref.tmp7.i.i.i.i.i.i.i.i.i'
    [224, 872) 'thread_status.i.i.i.i' <== Memory access at offset 743 is inside this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
Thread T261 (ThreadPool) created by T0 here:
    #0 0x562d3de63f2a in pthread_create (/usr/bin/clickhouse+0x12139f2a) (BuildId: 777140af592f6b5635a1a1ca322127d6b7e9edc5)
    #1 0x562d507ae678 in std::__1::__libcpp_thread_create[abi:v15000](unsigned long*, void* (*)(void*), void*) build_docker/./contrib/llvm-project/libcxx/include/__threading_support:376:10
    #2 0x562d507ae678 in std::__1::thread::thread<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'(), void>(void&&) build_docker/./contrib/llvm-project/libcxx/include/thread:311:16
    #3 0x562d5079c2ab in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool) build_docker/./src/Common/ThreadPool.cpp:180:35
    #4 0x562d507b401d in ThreadPoolImpl<std::__1::thread>::scheduleOrThrow(std::__1::function<void ()>, Priority, unsigned long, bool) build_docker/./src/Common/ThreadPool.cpp:250:5
    #5 0x562d507b401d in ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&) build_docker/./src/Common/ThreadPool.h:222:38
    #6 0x562d507a4bb8 in void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool) build_docker/./src/Common/ThreadPool.cpp:180:35
    #7 0x562d507a428a in ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleOrThrowOnError(std::__1::function<void ()>, Priority) build_docker/./src/Common/ThreadPool.cpp:238:5
    #8 0x562d61b791b5 in DB::DatabaseOrdinary::startupTables(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>&, DB::LoadingStrictnessLevel) build_docker/./src/Databases/DatabaseOrdinary.cpp:280:25
    #9 0x562d61b61c8b in DB::DatabaseAtomic::startupTables(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>&, DB::LoadingStrictnessLevel) build_docker/./src/Databases/DatabaseAtomic.cpp:453:23
    #10 0x562d6489c175 in DB::startupSystemTables() build_docker/./src/Interpreters/loadMetadata.cpp:473:54
    #11 0x562d506e6373 in DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) build_docker/./programs/server/Server.cpp:1623:9
    #12 0x562d700a7be6 in Poco::Util::Application::run() build_docker/./base/poco/Util/src/Application.cpp:315:8
    #13 0x562d506c1a23 in DB::Server::run() build_docker/./programs/server/Server.cpp:391:25
    #14 0x562d700ec847 in Poco::Util::ServerApplication::run(int, char**) build_docker/./base/poco/Util/src/ServerApplication.cpp:131:9
    #15 0x562d506b9daa in mainEntryClickHouseServer(int, char**) build_docker/./programs/server/Server.cpp:196:20
    #16 0x562d3debae35 in main build_docker/./programs/main.cpp:487:12
    #17 0x7f4060855d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: 69389d485a9793dbe873f0ea2c93e02efaa9aa3d)

SUMMARY: AddressSanitizer: stack-use-after-return build_docker/./contrib/llvm-project/libcxx/include/string in std::__1::basic_string<char, std::__1::char_traits<char>, 
```

**Comment by tavplubix** [comment]
Looks like it crashed somewhere in analyzer, but then failed to print the stacktrace because something was wrong with the  thread status/query context in MaterializedPostgreSQL

**Comment by alexey-milovidov** [comment]
@novikd, the last time it failed is today.

**Comment by alexey-milovidov** [comment]
https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZEYXkoY2hlY2tfc3RhcnRfdGltZSkgYXMgZCwKY291bnQoKSwgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlciksIGFueShyZXBvcnRfdXJsKQpmcm9tIGNoZWNrcyB3aGVyZSAnMjAyNC0wMS0wMScgPD0gY2hlY2tfc3RhcnRfdGltZSBhbmQgdGVzdF9uYW1lIGxpa2UgJyV0ZXN0X3Bvc3RncmVzcWxfZGF0YWJhc2VfZW5naW5lJScgYW5kIHRlc3Rfc3RhdHVzIG5vdCBpbiAoJ09LJywgJ1NLSVBQRUQnKSBncm91cCBieSBkIG9yZGVyIGJ5IGQgZGVzYw==
