### ISSUE TITLE
Transaction has invalid state RUNNING

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#39028]
https://s3.amazonaws.com/clickhouse-test-reports/0/948b5b780470b7c5bafbbd6e07c11d6b94454d0f/stress_test__debug__actions_.html

```
/var/log/clickhouse-server/clickhouse-server.err.log:2022.06.17 16:25:35.370938 [ 50128 ] {a9783604-3bcb-47b1-a70c-b1d3381cbbd9} <Fatal> : Logical error: 'Transaction (42, 60, 785e258e-4131-42fd-a5fb-10361befca75) has invalid state RUNNING'.
/var/log/clickhouse-server/clickhouse-server.err.log:2022.06.17 16:36:14.977065 [ 53621 ] {} <Fatal> BaseDaemon: ########################################
/var/log/clickhouse-server/clickhouse-server.err.log:2022.06.17 16:36:17.026437 [ 53621 ] {} <Fatal> BaseDaemon: (version 22.7.1.1 (official build), build id: A7EFB6CBE1128073) (from thread 50128) (query_id: a9783604-3bcb-47b1-a70c-b1d3381cbbd9) (query: COMMIT) Received signal Aborted (6)
```

```
2022-06-17 16:25:36 Thread 1317 "TCPHandler" received signal SIGABRT, Aborted.
2022-06-17 16:25:36 [Switching to Thread 0x7fe2f654b700 (LWP 50128)]
2022-06-17 16:25:36 0x00007fe7d487c00b in raise () from /lib/x86_64-linux-gnu/libc.so.6
2022-06-17 16:26:43 Saved corefile core.670
2022-06-17 16:26:43 #0  0x00007fe7d487c00b in raise () from /lib/x86_64-linux-gnu/libc.so.6
2022-06-17 16:26:43 No symbol table info available.
2022-06-17 16:26:43 #1  0x00007fe7d485b859 in abort () from /lib/x86_64-linux-gnu/libc.so.6
2022-06-17 16:26:43 No symbol table info available.
2022-06-17 16:26:43 #2  0x0000000016d6a986 in DB::abortOnFailedAssertion (description=...) at ../src/Common/Exception.cpp:47
2022-06-17 16:26:43         always_false = false
2022-06-17 16:26:43 #3  0x0000000016d6aa15 in DB::handle_error_code (msg=..., code=49, remote=false, trace=...) at ../src/Common/Exception.cpp:59
2022-06-17 16:26:43 No locals.
2022-06-17 16:26:43 #4  0x0000000016d6aac5 in DB::Exception::Exception (this=0x7fe6e45c2600, msg=..., code=49, remote_=false) at ../src/Common/Exception.cpp:70
2022-06-17 16:26:43 No locals.
2022-06-17 16:26:43 #5  0x000000002630696a in DB::Exception::Exception<DB::TransactionID const&, DB::MergeTreeTransaction::State> (this=0x7fe6e45c2600, code=49, fmt=..., args=@0x7fe2f653965c: DB::MergeTreeTransaction::RUNNING, args=@0x7fe2f653965c: DB::MergeTreeTransaction::RUNNING) at ../src/Common/Exception.h:37
2022-06-17 16:26:43 No locals.
2022-06-17 16:26:43 #6  0x0000000026305d16 in DB::InterpreterTransactionControlQuery::executeCommit (this=0x7fe630a4fa40, session_context=...) at ../src/Interpreters/InterpreterTransactionControlQuery.cpp:86
2022-06-17 16:26:44         txn = {__ptr_ = 0x7fe5eb903518, __cntrl_ = 0x7fe5eb903500}
2022-06-17 16:26:44         mode = DB::TransactionsWaitCSNMode::WAIT_UNKNOWN
2022-06-17 16:26:44         csn = 2
2022-06-17 16:26:44         e = @0x7fe2f65396d0: {<Poco::Exception> = {<std::exception> = {_vptr$exception = 0x7fe2f65396f0, static capacity = 32, frames = {0x16d5f2d9 <std::__1::__shared_count::__add_shared()+25>, 0x500000024, 0x7fe671a329c0, 0x7fe2f6539710, 0x16d5f2b5 <std::__1::__shared_weak_count::__add_shared()+21>, 0x7fe2f6539720, 0x7fe671a329c0, 0x7fe5eb903518, 0x7fe5eb903500, 0x7fe630a4fa40, 0x7fe5a3d23800, 0x7fe671a329c0, 0x7fe2f653b338, 0x7fe2f6539830, 0x26305348 <DB::InterpreterTransactionControlQuery::execute()+520>, 0x7fe2f6539770, 0x1, 0x7fe70059b998, 0x7fe2f653b5e8, 0x7fe2f6539790, 0x100000004, 0x7fe2f653b338, 0x7fe2f653b338, 0x7fe630a4fa40, 0x16eb7f26 <wide::integer<128ul, unsigned int>::_impl::operator_eq<wide::integer<128ul, unsigned int> >(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)+102>, 0x7fe61ca83068, 0x1f6539818, 0x0, 0x7fe5a3d23800, 0x7fe671a329c0, 0x0, 0x2f653b4c8}, size = -162286408}, _msg = {static __short_mask = 128, static __long_mask = 9223372036854775808, __r_ = {<std::__1::__compressed_pair_elem<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__rep, 0, false>> = {__value_ = {{__l = {__data_ = 0x7fe70059b998 "\270\020\370/", __size_ = 140624272701440, __cap_ = 140627725724096}, __s = {__data_ = "\230\271Y\000\347\177\000\000\000\070\322\243\345\177\000\000\300)\243q\346\177", {<std::__1::__padding<char, 1ul>> = {<No data fields>}, __size_ = 0 '\000'}}, __r = {__words = {140630120053144, 140624272701440, 140627725724096}}}}}, <std::__1::__compressed_pair_elem<std::__1::allocator<char>, 1, true>> = {<std::__1::allocator<char>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<char> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, static npos = 18446744073709551615}, _pNested = 0x16feea95 <std::__1::__compressed_pair<DB::IInterpreter*, std::__1::default_delete<DB::IInterpreter> >::first() const+21>, _code = -162286408}, remote = 226}
2022-06-17 16:26:44 #7  0x0000000026305348 in DB::InterpreterTransactionControlQuery::execute (this=0x7fe630a4fa40) at ../src/Interpreters/InterpreterTransactionControlQuery.cpp:29
2022-06-17 16:26:44         session_context = {__ptr_ = 0x7fe5a3d23800, __cntrl_ = 0x7fe671a329c0}
2022-06-17 16:26:44         tcl = @0x7fe70059b998: {<DB::IAST> = {<std::__1::enable_shared_from_this<DB::IAST>> = {__weak_this_ = {__ptr_ = 0x7fe70059b998, __cntrl_ = 0x7fe70059b980}}, <DB::TypePromotion<DB::IAST>> = {<No data fields>}, _vptr$IAST = 0x2ff810b8 <vtable for DB::ASTTransactionControl+16>, children = {__begin_ = 0x0, __end_ = 0x0, __end_cap_ = {<std::__1::__compressed_pair_elem<std::__1::shared_ptr<DB::IAST>*, 0, false>> = {__value_ = 0x0}, <std::__1::__compressed_pair_elem<std::__1::allocator<std::__1::shared_ptr<DB::IAST> >, 1, true>> = {<std::__1::allocator<std::__1::shared_ptr<DB::IAST> >> = {<std::__1::__non_trivial_if<true, std::__1::allocator<std::__1::shared_ptr<DB::IAST> > >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}, static hilite_keyword = 0xd5b4014 "\033[1m", static hilite_identifier = 0xdfffdea "\033[0;36m", static hilite_function = 0xd6d11b1 "\033[0;33m", static hilite_operator = 0xd5b4ff7 "\033[1;33m", static hilite_alias = 0xdf71a50 "\033[0;32m", static hilite_substitution = 0xd7ef07e "\033[1;36m", static hilite_none = 0xd1432fd "\033[0m"}, action = DB::ASTTransactionControl::COMMIT, snapshot = 0}
...
```
https://pastila.nl/?000cb995/c182c6cd09ee1b409f1a45a43c519088

**Comment by tavplubix** [comment]
> 2022.06.17 16:25:35.370938

@qoega, this report is 3 weeks old. The issue is already fixed in #37822
