### ISSUE TITLE
The switch --print-media-type, is not support using unpatched qt, and will be ignored.QXcbConnection:

### ISSUE THREAD

**Issue by denisgolius** [ClickHouse/ClickHouse#3902]
```
 root@workbio /home/docs/www/ClickHouse/docs/tools # python build.py 
INFO:root:Building en docs
INFO:mkdocs.commands.build:Cleaning site directory
INFO:mkdocs.commands.build:Building documentation to directory: /home/docs/www/ClickHouse/docs/build/en
INFO:root:Building single page version for en
INFO:root:153 files will be concatenated into single md-file.
The switch --print-media-type, is not support using unpatched qt, and will be ignored.QXcbConnection: Could not connect to display 
Aborted (core dumped)
Traceback (most recent call last):
  File "build.py", line 246, in <module>
    build(args)
  File "/home/docs/www/ClickHouse/docs/tools/build.py", line 220, in build
    build_for_lang(lang, args)
  File "/home/docs/www/ClickHouse/docs/tools/build.py", line 136, in build_for_lang
    build_single_page_version(lang, args, cfg)
  File "/home/docs/www/ClickHouse/docs/tools/build.py", line 185, in build_single_page_version
    subprocess.check_call(' '.join(create_pdf_command), shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'wkhtmltopdf --print-media-type /home/docs/www/ClickHouse/docs/build/en/single/index.html /home/docs/www/ClickHouse/docs/build/en/single/clickhouse_en.pdf' returned non-zero exit status 134
```

It's ridiculous I think by building on server...or not?

Because building is corrupted and I'm not sure if the build is complete for EN language.

**Comment by blinkov** [comment]
Probably there's some requirement on `wkhtmltopdf` version or it's dependencies, but I haven't researched this in detail. The option it complains about is important to get the PDF version right. At the moment PDF version can be disabled only together with normal single-page version, but it can be improved.

**Comment by pradeshc** [comment]
the answers here

https://stackoverflow.com/questions/34479040/how-to-install-wkhtmltopdf-with-patched-qt
