### ISSUE TITLE
Reference binding to null pointer of type IDataType in KeyCondition

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#39099]
https://s3.amazonaws.com/clickhouse-test-reports/0/d222f238f02c79863cce7cc95ec19c68905e946a/fuzzer_astfuzzerubsan,actions//report.html

```
../contrib/libcxx/include/__memory/shared_ptr.h:808:16: runtime error: reference binding to null pointer of type 'std::shared_ptr<const DB::IDataType>::element_type' (aka 'const DB::IDataType')
#0 0x239d480e in std::__1::shared_ptr<DB::IDataType const>::operator*() const build_docker/../contrib/libcxx/include/__memory/shared_ptr.h:808:9
    #1 0x239d480e in DB::DataTypeTuple::equals(DB::IDataType const&) const build_docker/../src/DataTypes/DataTypeTuple.cpp:201:31
    #2 0x25711c47 in DB::KeyCondition::tryParseAtomFromAST(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, DB::Block&, DB::KeyCondition::RPNElement&) build_docker/../src/Storages/MergeTree/KeyCondition.cpp:1307:38
    #3 0x25710514 in DB::KeyCondition::traverseAST(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, DB::Block&) build_docker/../src/Storages/MergeTree/KeyCondition.cpp:644:10
    #4 0x2570fbfb in DB::KeyCondition::KeyCondition(DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::ExpressionActions> const&, bool, bool) build_docker/../src/Storages/MergeTree/KeyCondition.cpp:480:9
    #5 0x2635857b in DB::ReadFromMergeTree::selectRangesToRead(std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const> > >, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>, unsigned int, std::__1::shared_ptr<std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, long, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, long> > > >, DB::MergeTreeData const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, bool, Poco::Logger*) build_docker/../src/Processors/QueryPlan/ReadFromMergeTree.cpp:882:18
    #6 0x2635802c in DB::ReadFromMergeTree::selectRangesToRead(std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const> > >) const build_docker/../src/Processors/QueryPlan/ReadFromMergeTree.cpp:832:12
    #7 0x26359d76 in DB::ReadFromMergeTree::getAnalysisResult() const build_docker/../src/Processors/QueryPlan/ReadFromMergeTree.cpp:1014:67
    #8 0x26359fbf in DB::ReadFromMergeTree::initializePipeline(DB::QueryPipelineBuilder&, DB::BuildQueryPipelineSettings const&) build_docker/../src/Processors/QueryPlan/ReadFromMergeTree.cpp:1023:19
    #9 0x2631a40c in DB::ISourceStep::updatePipeline(std::__1::vector<std::__1::unique_ptr<DB::QueryPipelineBuilder, std::__1::default_delete<DB::QueryPipelineBuilder> >, std::__1::allocator<std::__1::unique_ptr<DB::QueryPipelineBuilder, std::__1::default_delete<DB::QueryPipelineBuilder> > > >, DB::BuildQueryPipelineSettings const&) build_docker/../src/Processors/QueryPlan/ISourceStep.cpp:16:5
    #10 0x26341b45 in DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&) build_docker/../src/Processors/QueryPlan/QueryPlan.cpp:187:47
    #11 0x24879b05 in DB::InterpreterSelectWithUnionQuery::execute() build_docker/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:370:31
    #12 0x24c8749a in DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) build_docker/../src/Interpreters/executeQuery.cpp:693:36
    #13 0x24c83d89 in DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) build_docker/../src/Interpreters/executeQuery.cpp:1081:30
    #14 0x25cc2c76 in DB::TCPHandler::runImpl() build_docker/../src/Server/TCPHandler.cpp:332:24
    #15 0x25ce0a15 in DB::TCPHandler::run() build_docker/../src/Server/TCPHandler.cpp:1804:9
    #16 0x26b5a5eb in Poco::Net::TCPServerConnection::start() build_docker/../contrib/poco/Net/src/TCPServerConnection.cpp:43:3
    #17 0x26b5aac4 in Poco::Net::TCPServerDispatcher::run() build_docker/../contrib/poco/Net/src/TCPServerDispatcher.cpp:115:20
    #18 0x26ccb106 in Poco::PooledThread::run() build_docker/../contrib/poco/Foundation/src/ThreadPool.cpp:199:14
    #19 0x26cc8c0b in Poco::ThreadImpl::runnableEntry(void*) build_docker/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345:27
    #20 0x7f252889e608 in start_thread /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477:8
    #21 0x7f25287c3132 in __clone /build/glibc-SzIz7B/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../contrib/libcxx/include/__memory/shared_ptr.h:808:16 in 

2022.07.09 16:02:29.123769 [ 106 ] {} <Trace> BaseDaemon: Received signal -3
2022.07.09 16:02:29.124247 [ 441 ] {} <Fatal> BaseDaemon: ########################################
2022.07.09 16:02:29.124306 [ 441 ] {} <Fatal> BaseDaemon: (version 22.7.1.1 (official build), build id: 94CFC54CC03E68F9) (from thread 163) (query_id: 8bddc229-c218-40ae-85a2-d9ac29d4f872) (query: SELECT * FROM tuple_01016 WHERE a < (toDateTime('2019-01-01 00:00:00'), 9223372036854775806) FORMAT `Null`) Received signal Unknown signal (-3)
2022.07.09 16:02:29.124320 [ 441 ] {} <Fatal> BaseDaemon: Sanitizer trap.
2022.07.09 16:02:29.124355 [ 441 ] {} <Fatal> BaseDaemon: Stack trace: 0xffdc6a3 0x1024e751 0xff93c86 0xffa3d73 0x239d480f 0x25711c48 0x25710515 0x2570fbfc 0x2635857c 0x2635802d 0x26359d77 0x26359fc0 0x2631a40d 0x26341b46 0x24879b06 0x24c8749b 0x24c83d8a 0x25cc2c77 0x25ce0a16 0x26b5a5ec 0x26b5aac5 0x26ccb107 0x26cc8c0c 0x7f252889e609 0x7f25287c3133
2022.07.09 16:02:29.145172 [ 441 ] {} <Fatal> BaseDaemon: 0.1. inlined from ./build_docker/../src/Common/StackTrace.cpp:305: StackTrace::tryCapture()
2022.07.09 16:02:29.145193 [ 441 ] {} <Fatal> BaseDaemon: 0. ../src/Common/StackTrace.cpp:266: StackTrace::StackTrace() @ 0xffdc6a3 in /workspace/clickhouse
2022.07.09 16:02:29.192069 [ 441 ] {} <Fatal> BaseDaemon: 1. ./build_docker/../src/Daemon/BaseDaemon.cpp:0: sanitizerDeathCallback() @ 0x1024e751 in /workspace/clickhouse

```

**Comment by Algunenano** [comment]
Probably fixed by https://github.com/ClickHouse/ClickHouse/pull/39101
