### ISSUE TITLE
Abort in `nuraft::raft_server::commit_in_bg`

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#39637]
https://s3.amazonaws.com/clickhouse-test-reports/0/288b73035f986779896d2bc819295f593a7501e4/stress_test__undefined_.html

```
2022-07-27 04:47:47 Thread 52 "clickhouse-serv" received signal SIGABRT, Aborted.
2022-07-27 04:47:47 [Switching to Thread 0x7f7314dd9700 (LWP 100949)]
2022-07-27 04:47:47 0x00007f735996f00b in raise () from /lib/x86_64-linux-gnu/libc.so.6
2022-07-27 04:53:24 Saved corefile core.100882
2022-07-27 04:53:24 #0  0x00007f735996f00b in raise () from /lib/x86_64-linux-gnu/libc.so.6
2022-07-27 04:53:24 No symbol table info available.
2022-07-27 04:53:24 #1  0x00007f735994e859 in abort () from /lib/x86_64-linux-gnu/libc.so.6
2022-07-27 04:53:24 No symbol table info available.
2022-07-27 04:53:24 #2  0x0000000017fd5626 in DB::KeeperStateManager::system_exit (this=<optimized out>) at ../src/Coordination/KeeperStateManager.cpp:251
2022-07-27 04:53:24 No locals.
2022-07-27 04:53:24 #3  0x000000001a80b14b in nuraft::raft_server::commit_in_bg (this=0x7f7331c52018) at ../contrib/NuRaft/src/handle_commit.cxx:157
2022-07-27 04:53:24         err = <optimized out>
2022-07-27 04:53:24         is_log_store_commit_exec = <optimized out>
2022-07-27 04:53:24         thread_name = {static __short_mask = 128, static __long_mask = 9223372036854775808, __r_ = {<std::__1::__compressed_pair_elem<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__rep, 0, false>> = {__value_ = {{__l = {__data_ = <optimized out>, __size_ = <optimized out>, __cap_ = 936748722493063168}, __s = {__data_ = {<optimized out> <repeats 13 times>, 0 '\000', <optimized out>, <optimized out>, 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000'}, {<std::__1::__padding<char, 1ul>> = {<No data fields>}, __size_ = 13 '\r'}}, __r = {__words = {<optimized out>, <optimized out>, 936748722493063168}}}}}, <std::__1::__compressed_pair_elem<std::__1::allocator<char>, 1, true>> = {<std::__1::allocator<char>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<char> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, static npos = 18446744073709551615}
2022-07-27 04:53:24 #4  0x000000001a8051ce in std::__1::__invoke<void (nuraft::raft_server::*&)(), nuraft::raft_server*&, , void>(void (nuraft::raft_server::*&)(), nuraft::raft_server*&) (__f=@0x7f7331d7e8c8: (void (nuraft::raft_server::*)(nuraft::raft_server * const)) 0x1a80ad60 <nuraft::raft_server::commit_in_bg()>, __a0=@0x7f7331d7e8d8: 0x7f7331c52018) at ../contrib/libcxx/include/type_traits:3565
2022-07-27 04:53:24 No locals.
2022-07-27 04:53:24 #5  std::__1::__apply_functor<void (nuraft::raft_server::*)(), std::__1::tuple<nuraft::raft_server*>, 0ul, std::__1::tuple<> > (__f=@0x7f7331d7e8c8: (void (nuraft::raft_server::*)(nuraft::raft_server * const)) 0x1a80ad60 <nuraft::raft_server::commit_in_bg()>, __bound_args=..., __args=...) at ../contrib/libcxx/include/__functional/bind.h:263
2022-07-27 04:53:24 No locals.
2022-07-27 04:53:24 #6  std::__1::__bind<void (nuraft::raft_server::*)(), nuraft::raft_server*>::operator()<> (this=0x7f7331d7e8c8) at ../contrib/libcxx/include/__functional/bind.h:298
2022-07-27 04:53:24 No locals.
2022-07-27 04:53:24 #7  std::__1::__invoke<std::__1::__bind<void (nuraft::raft_server::*)(), nuraft::raft_server*>>(std::__1::__bind<void (nuraft::raft_server::*)(), nuraft::raft_server*>&&) (__f=...) at ../contrib/libcxx/include/type_traits:3640
2022-07-27 04:53:24 No locals.
2022-07-27 04:53:24 #8  std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, std::__1::__bind<void (nuraft::raft_server::*)(), nuraft::raft_server*>>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, std::__1::__bind<void (nuraft::raft_server::*)(), nuraft::raft_server*>>&, std::__1::__tuple_indices<>) (__t=...) at ../contrib/libcxx/include/thread:282
2022-07-27 04:53:24 No locals.
2022-07-27 04:53:24 #9  std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, std::__1::__bind<void (nuraft::raft_server::*)(), nuraft::raft_server*> > > (__vp=0x7f7331d7e8c0) at ../contrib/libcxx/include/thread:293
2022-07-27 04:53:24         __p = {__ptr_ = {<std::__1::__compressed_pair_elem<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, std::__1::__bind<void (nuraft::raft_server::*)(), nuraft::raft_server*> >*, 0, false>> = {__value_ = 0x7f7331d7e8c0}, <std::__1::__compressed_pair_elem<std::__1::default_delete<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, std::__1::__bind<void (nuraft::raft_server::*)(), nuraft::raft_server*> > >, 1, true>> = {<std::__1::default_delete<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, std::__1::__bind<void (nuraft::raft_server::*)(), nuraft::raft_server*> > >> = {<No data fields>}, <No data fields>}, <No data fields>}}
2022-07-27 04:53:24 #10 0x00007f7359b26609 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
2022-07-27 04:53:24 No symbol table info available.
2022-07-27 04:53:24 #11 0x00007f7359a4b133 in clone () from /lib/x86_64-linux-gnu/libc.so.6
2022-07-27 04:53:24 No symbol table info available.
```

Maybe it's some issue with exception safety, there's MEMORY_LIMIT_EXCEEDED in logs just before crash:
```
2022.07.27 04:47:47.285868 [ 100909 ] {} <Error> void DB::KeeperDispatcher::requestThread(): Code: 241. DB::Exception: Memory limit (total) exceeded: would use 52.98 GiB (attempt to allocate chunk of 4946622 bytes), maximum: 51.44 GiB. OvercommitTracker decision: Memory overcommit isn't used. OvercommitTracker isn't set.. (MEMORY_LIMIT_EXCEEDED), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xba37dda in /usr/bin/clickhouse
1. DB::Exception::Exception<char const*, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, long&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string_view<char, std::__1::char_traits<char> > >(int, fmt::v8::basic_format_string<char, fmt::v8::type_identity<char const*>::type, fmt::v8::type_identity<char const*>::type, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::type, fmt::v8::type_identity<long&>::type, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::type, fmt::v8::type_identity<std::__1::basic_string_view<char, std::__1::char_traits<char> > >::type>, char const*&&, char const*&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, long&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, std::__1::basic_string_view<char, std::__1::char_traits<char> >&&) @ 0xba4fff7 in /usr/bin/clickhouse
2. MemoryTracker::allocImpl(long, bool, MemoryTracker*) @ 0xba4f9e7 in /usr/bin/clickhouse
3. MemoryTracker::allocImpl(long, bool, MemoryTracker*) @ 0xba4f471 in /usr/bin/clickhouse
4. DB::Memory<Allocator<false, false> >::alloc() @ 0xbaa2431 in /usr/bin/clickhouse
5. DB::ZstdDeflatingAppendableWriteBuffer::ZstdDeflatingAppendableWriteBuffer(std::__1::unique_ptr<DB::WriteBufferFromFile, std::__1::default_delete<DB::WriteBufferFromFile> >, int, bool, unsigned long, char*, unsigned long) @ 0x17fb0da4 in /usr/bin/clickhouse
6. DB::ChangelogWriter::ChangelogWriter(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::WriteMode, unsigned long) @ 0x17fb0241 in /usr/bin/clickhouse
7. DB::Changelog::rotate(unsigned long) @ 0x17fa59d9 in /usr/bin/clickhouse
8. DB::Changelog::appendEntry(unsigned long, std::__1::shared_ptr<nuraft::log_entry> const&) @ 0x17fa9636 in /usr/bin/clickhouse
9. DB::KeeperLogStore::append(std::__1::shared_ptr<nuraft::log_entry>&) @ 0x17fdd377 in /usr/bin/clickhouse
10. nuraft::raft_server::store_log_entry(std::__1::shared_ptr<nuraft::log_entry>&, unsigned long) @ 0x1a7fb763 in /usr/bin/clickhouse
11. nuraft::raft_server::handle_cli_req(nuraft::req_msg&) @ 0x1a8068cc in /usr/bin/clickhouse
12. nuraft::raft_server::handle_cli_req_prelock(nuraft::req_msg&) @ 0x1a806106 in /usr/bin/clickhouse
13. nuraft::raft_server::process_req(nuraft::req_msg&) @ 0x1a7f981c in /usr/bin/clickhouse
14. nuraft::raft_server::send_msg_to_leader(std::__1::shared_ptr<nuraft::req_msg>&) @ 0x1a81fa8a in /usr/bin/clickhouse
15. nuraft::raft_server::append_entries(std::__1::vector<std::__1::shared_ptr<nuraft::buffer>, std::__1::allocator<std::__1::shared_ptr<nuraft::buffer> > > const&) @ 0x1a8225e7 in /usr/bin/clickhouse
16. DB::KeeperServer::putRequestBatch(std::__1::vector<DB::KeeperStorage::RequestForSession, std::__1::allocator<DB::KeeperStorage::RequestForSession> > const&) @ 0x17f9a535 in /usr/bin/clickhouse
17. DB::KeeperDispatcher::requestThread() @ 0x17f81504 in /usr/bin/clickhouse
18. ? @ 0x17f8edee in /usr/bin/clickhouse
19. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xbb046a8 in /usr/bin/clickhouse
20. ? @ 0xbb07a3d in /usr/bin/clickhouse
21. ? @ 0x7f7359b26609 in ?
22. clone @ 0x7f7359a4b133 in ?
 (version 22.7.1.2484 (official build))
2022.07.27 04:47:47.286739 [ 100949 ] {} <Error> RaftInstance: background committing thread encounter err Trying to commit a ZXID 1099999 while the next ZXID to commit is 1099998, exiting to protect the system

```

cc: @antonio2368

**Comment by antonio2368** [comment]
This one is a bit tricky. The assert correctly triggered and aborted the Keeper.
What is problematic here is the uncommitted state which is completely kept in memory.

Applying a new log on leader consists of the following steps:
- preprocess the log so zxid and digest can be calculated
- store the log on disk and in memory index

If we fail storing the log itself, its changes will still be there because of the first step.
The fix would be to rollback the log if storing it fails, but what if the rollback itself fails (not hard to imagine for out of memory case). The best thing would be again to abort to avoid inconsistencies and rebuild in-memory structures from scratch. We ended up with the same result but with extra steps.
