### ISSUE TITLE
Use of uninitialized value in `ColumnSparse.Filter` (unit test)

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#39895]
https://s3.amazonaws.com/clickhouse-test-reports/0/fe95703a49d612547e9c5ac24d01734fc900f45b/unit_tests__msan_.html

```
[ RUN      ] ColumnSparse.Filter
==13==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0xb18a011 in checkEquals(DB::IColumn const&, DB::IColumn const&) build_docker/../src/Columns/tests/gtest_column_sparse.cpp:51:13
    #1 0xb18a011 in ColumnSparse_Filter_Test::TestBody()::$_2::operator()(unsigned long, unsigned long, unsigned long) const build_docker/../src/Columns/tests/gtest_column_sparse.cpp:159:14
    #2 0xb18a011 in ColumnSparse_Filter_Test::TestBody() build_docker/../src/Columns/tests/gtest_column_sparse.cpp:177:13
    #3 0x226870e1 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) build_docker/../contrib/googletest/googletest/src/gtest.cc:2589:10
    #4 0x226870e1 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) build_docker/../contrib/googletest/googletest/src/gtest.cc:2625:14
    #5 0x225dda58 in testing::Test::Run() build_docker/../contrib/googletest/googletest/src/gtest.cc:2664:5
    #6 0x225e5975 in testing::TestInfo::Run() build_docker/../contrib/googletest/googletest/src/gtest.cc:2842:11
    #7 0x225e8739 in testing::TestSuite::Run() build_docker/../contrib/googletest/googletest/src/gtest.cc:2996:28
    #8 0x22632112 in testing::internal::UnitTestImpl::RunAllTests() build_docker/../contrib/googletest/googletest/src/gtest.cc:5708:44
    #9 0x2268b7cb in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) build_docker/../contrib/googletest/googletest/src/gtest.cc:2589:10
    #10 0x2268b7cb in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) build_docker/../contrib/googletest/googletest/src/gtest.cc:2625:14
    #11 0x2262f8de in testing::UnitTest::Run() build_docker/../contrib/googletest/googletest/src/gtest.cc:5291:10
    #12 0xbafc59f in RUN_ALL_TESTS() build_docker/../contrib/googletest/googletest/include/gtest/gtest.h:2471:46
    #13 0xbafc59f in main build_docker/../src/Coordination/tests/gtest_coordination.cpp:2158:12
    #14 0x7fcd460dd082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)
    #15 0xb00ffad in _start (/unit_tests_dbms+0xb00ffad) (BuildId: dea0c07b2cbfa9a9)

  Uninitialized value was created by a heap allocation
    #0 0xb0448c0 in malloc (/unit_tests_dbms+0xb0448c0) (BuildId: dea0c07b2cbfa9a9)
    #1 0x577427fb in Allocator<false, false>::allocNoTrack(unsigned long, unsigned long) build_docker/../src/Common/Allocator.h:227:27
    #2 0xb195144 in Allocator<false, false>::alloc(unsigned long, unsigned long) build_docker/../src/Common/Allocator.h:96:16
    #3 0xb195144 in void DB::PODArrayBase<8ul, 4096ul, Allocator<false, false>, 15ul, 16ul>::alloc<>(unsigned long) build_docker/../src/Common/PODArray.h:128:65
    #4 0x1eed54ff in void DB::PODArrayBase<8ul, 4096ul, Allocator<false, false>, 15ul, 16ul>::realloc<>(unsigned long) build_docker/../src/Common/PODArray.h:153:13
    #5 0x1eed54ff in void DB::PODArrayBase<8ul, 4096ul, Allocator<false, false>, 15ul, 16ul>::reserve<>(unsigned long) build_docker/../src/Common/PODArray.h:234:13
    #6 0x1eed54ff in DB::ColumnVector<unsigned long>::filter(DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const&, long) const build_docker/../src/Columns/ColumnVector.cpp:600:18
    #7 0xb18942b in ColumnSparse_Filter_Test::TestBody()::$_2::operator()(unsigned long, unsigned long, unsigned long) const build_docker/../src/Columns/tests/gtest_column_sparse.cpp:157:35
    #8 0xb18942b in ColumnSparse_Filter_Test::TestBody() build_docker/../src/Columns/tests/gtest_column_sparse.cpp:177:13
    #9 0x226870e1 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) build_docker/../contrib/googletest/googletest/src/gtest.cc:2589:10
    #10 0x226870e1 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) build_docker/../contrib/googletest/googletest/src/gtest.cc:2625:14
    #11 0x225dda58 in testing::Test::Run() build_docker/../contrib/googletest/googletest/src/gtest.cc:2664:5
    #12 0x225e5975 in testing::TestInfo::Run() build_docker/../contrib/googletest/googletest/src/gtest.cc:2842:11
    #13 0x225e8739 in testing::TestSuite::Run() build_docker/../contrib/googletest/googletest/src/gtest.cc:2996:28
    #14 0x22632112 in testing::internal::UnitTestImpl::RunAllTests() build_docker/../contrib/googletest/googletest/src/gtest.cc:5708:44
    #15 0x2268b7cb in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) build_docker/../contrib/googletest/googletest/src/gtest.cc:2589:10
    #16 0x2268b7cb in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) build_docker/../contrib/googletest/googletest/src/gtest.cc:2625:14
    #17 0x2262f8de in testing::UnitTest::Run() build_docker/../contrib/googletest/googletest/src/gtest.cc:5291:10
    #18 0xbafc59f in RUN_ALL_TESTS() build_docker/../contrib/googletest/googletest/include/gtest/gtest.h:2471:46
    #19 0xbafc59f in main build_docker/../src/Coordination/tests/gtest_coordination.cpp:2158:12
    #20 0x7fcd460dd082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)

SUMMARY: MemorySanitizer: use-of-uninitialized-value build_docker/../src/Columns/tests/gtest_column_sparse.cpp:51:13 in checkEquals(DB::IColumn const&, DB::IColumn const&)
Exiting
```

cc: @CurtizJ

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/0/80104793948a82ceaefe710700096d2d31089dd2/unit_tests__msan_.html

**Comment by CurtizJ** [comment]
Probably [commit](https://github.com/ClickHouse/ClickHouse/commit/fe95703a49d612547e9c5ac24d01734fc900f45b) on which tests have been broken for the first time breaks them, because there are some changes near filtering.

**Comment by CurtizJ** [comment]
Or maybe this https://github.com/ClickHouse/ClickHouse/pull/39633

**Comment by alexey-milovidov** [comment]
I suspect #39633, because this unit test fails not on every run but only occasionally - most likely when it comes to AVX-512 machine.

**Comment by rschu1ze** [comment]
Could reproduce the problem on an EC2 box with AVX512 VBMI2 and can confirm that it was introduced by https://github.com/ClickHouse/ClickHouse/pull/39633.
