### ISSUE TITLE
Zookeeper Exception: Operation timeout

### ISSUE THREAD

**Issue by emoskvitin** [ClickHouse/ClickHouse#40585]
Hi Team,

We have an issue with zookeeper in our clickhouse setup. Usually it happens 4-5 times a day and starts with exception below and then the Session expired exception for the all tables. We don't see any issues/spikes in CPU/Memory/Disk neither on clickhouse or zookeeper side. 

### Clickhouse setup

clickhouse version: **21.12.5.1**
2 instances primary and dr
**170** Replicated tables. Active inserts performs in about ~30 tables with total rate ~ 60 inserts/sec to the all tables

```
clickhouse zookeeper config:
    <zookeeper>
        <session_timeout_ms>120000</session_timeout_ms>
        <operation_timeout_ms>60000</operation_timeout_ms>
    </zookeeper>

```
### Zookeeper

Zookeeper version: **3.6.2**
3 instances with following config:
-Djute.maxbuffer=8388608

```
tickTime=2000
initLimit=30000
syncLimit=50
minSessionTimeout=30000
maxSessionTimeout=60000000
autopurge.snapRetainCount=3
autopurge.purgeInterval=1
preAllocSize=131072
snapCount=3000000
maxClientCnxns=2000

```

Could you suggest what else can we check? Can we tune any configs parameters?
Thank you

**Clickhouse logs**

```
2022.08.01 06:36:52.652059 [ 76118 ] {9dc4e2d9-2bf8-44fc-bca4-22765dbe4d22} <Error> executeQuery: Code: 999. Coordination::Exception: Operation timeout, path: /clickhouse/tables/table.name/replicas/servername.com/is_active. (KEEPER_EXCEPTION) (version 21.12.5.1) (from 10.240.81.56:57023) (in query: OPTIMIZE TABLE rms.risk_result_rho partition '202207' DEDUPLICATE), Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x140a842c in /clickhouse-rhel/21.12.5.1/clickhouse/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x9b50bfa in /clickhouse-rhel/21.12.5.1/clickhouse/bin/clickhouse
2. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error, int) @ 0x1215ab96 in /clickhouse-rhel/21.12.5.1/clickhouse/bin/clickhouse
3. Coordination::Exception::Exception(Coordination::Error, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x1215b109 in /clickhouse-rhel/21.12.5.1/clickhouse/bin/clickhouse
4. zkutil::ZooKeeper::existsWatch(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Stat*, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x121619d3 in /clickhouse-rhel/21.12.5.1/clickhouse/bin/clickhouse
5. zkutil::ZooKeeper::exists(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Stat*, std::__1::shared_ptr<Poco::Event> const&) @ 0x121618b7 in /clickhouse-rhel/21.12.5.1/clickhouse/bin/clickhouse
6. DB::StorageReplicatedMergeTree::tryWaitForReplicaToProcessLogEntry(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ReplicatedMergeTreeLogEntryData const&, long)::$_29::operator()() const @ 0x119ad844 in /clickhouse-rhel/21.12.5.1/clickhouse/bin/clickhouse
7. zkutil::ZooKeeper::waitForDisappear(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<bool ()> const&) @ 0x12165cc8 in /clickhouse-rhel/21.12.5.1/clickhouse/bin/clickhouse
8. DB::StorageReplicatedMergeTree::tryWaitForReplicaToProcessLogEntry(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ReplicatedMergeTreeLogEntryData const&, long) @ 0x119ab812 in /clickhouse-rhel/21.12.5.1/clickhouse/bin/clickhouse
9. DB::StorageReplicatedMergeTree::waitForLogEntryToBeProcessedIfNecessary(DB::ReplicatedMergeTreeLogEntryData const&, std::__1::shared_ptr<DB::Context const>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x11995f53 in /clickhouse-rhel/21.12.5.1/clickhouse/bin/clickhouse
10. DB::StorageReplicatedMergeTree::optimize(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::IAST> const&, bool, bool, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::Context const>) @ 0x11993f4d in /clickhouse-rhel/21.12.5.1/clickhouse/bin/clickhouse
11. DB::InterpreterOptimizeQuery::execute() @ 0x112a45c9 in /clickhouse-rhel/21.12.5.1/clickhouse/bin/clickhouse
12. DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x11666255 in /clickhouse-rhel/21.12.5.1/clickhouse/bin/clickhouse
13. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, std::__1::optional<DB::FormatSettings> const&) @ 0x1166872d in /clickhouse-rhel/21.12.5.1/clickhouse/bin/clickhouse
14. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0x11dedca7 in /clickhouse-rhel/21.12.5.1/clickhouse/bin/clickhouse
15. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x11df158e in /clickhouse-rhel/21.12.5.1/clickhouse/bin/clickhouse
16. DB::HTTPServerConnection::run() @ 0x11e416d8 in /clickhouse-rhel/21.12.5.1/clickhouse/bin/clickhouse
17. Poco::Net::TCPServerConnection::start() @ 0x1401caa7 in /clickhouse-rhel/21.12.5.1/clickhouse/bin/clickhouse
18. Poco::Net::TCPServerDispatcher::run() @ 0x1401cf67 in /clickhouse-rhel/21.12.5.1/clickhouse/bin/clickhouse
19. Poco::PooledThread::run() @ 0x14109227 in /clickhouse-rhel/21.12.5.1/clickhouse/bin/clickhouse
20. Poco::ThreadImpl::runnableEntry(void*) @ 0x14106be6 in /clickhouse-rhel/21.12.5.1/clickhouse/bin/clickhouse
21. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
22. clone @ 0xfe96d in /usr/lib64/libc-2.17.so


2022.08.01 06:36:52.652782 [ 9448 ] {} <Error> table.name (ReplicatedMergeTreeCleanupThread): void DB::ReplicatedMergeTreeCleanupThread::run(): Code: 999. Coordination::Exception: Session expired (Session expired). (KEEPER_EXCEPTION), Stack trace (when copying this message, always include the lines below):
0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x140a842c in /clickhouse-rhel/21.12.5.1/clickhouse/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x9b50bfa in /clickhouse-rhel/21.12.5.1/clickhouse/bin/clickhouse
2. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error, int) @ 0x1215ab96 in /clickhouse-rhel/21.12.5.1/clickhouse/bin/clickhouse
3. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error) @ 0x1215ad2a in /clickhouse-rhel/21.12.5.1/clickhouse/bin/clickhouse
4. Coordination::ZooKeeper::pushRequest(Coordination::ZooKeeper::RequestInfo&&) @ 0x12190a62 in /clickhouse-rhel/21.12.5.1/clickhouse/bin/clickhouse

```

Zookeeper.log have only exception about the client closed the session
```
[ZOOKEEPER] 26-Jul 14:53:23,370 GMT  WARN - Unexpected exception [null] [server.NIOServerCnxn] [NIOWorkerThread-78]
EndOfStreamException: Unable to read additional data from client, it probably closed the socket: address = /XX.XX.XX.XX:port, session = 0x14021a6a374c0040
	at org.apache.zookeeper.server.NIOServerCnxn.handleFailedRead(NIOServerCnxn.java:163)
	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:326)
	at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:522)
	at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:154)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

```

**Comment by rkozlo** [comment]
Obsolete ch version. Start with update. Preferred 22.3 or 22.8

**Comment by emoskvitin** [comment]
Hi Team, update to 22.8 still see the issue. Do you need any more details?
Thanks

**Comment by 3442115** [comment]
Same text

**Comment by Algunenano** [comment]
If you get a timeout from keeper or ZK, it usually means that either:
* The keeper service is overloaded. Make sure you are not running it in an instance with other heavy services (like clickhouse sever)
* ClickHouse server itself is overloaded and it's too slow reading from the socket. Reduce load

Recent version of CH have gotten better dealing with keeper exceptions, retrying in some cases.
