### ISSUE TITLE
When I query in multiple threads, clickhosue-client says queryId already exists

### ISSUE THREAD

**Issue by zhengwenhao07** [ClickHouse/ClickHouse#40607]
I queried with clickhouse-client in  multiple threads and I've customized the queryId. But sometimes the client prompts " Query with id = xxxxxx is already running."
This is my code
```java
        String queryId = INSTANCE.createQueryId() + ":" + RandomUtils.nextInt(0, 100);
        try {
            clickHouseResponse = config.connect.query(sql, queryId).format(ClickHouseFormat.JSONEachRow).execute().get();
        } catch (Exception e) {
            e.printStackTrace();
        }
```
This is error log
```log
java.util.concurrent.ExecutionException: com.clickhouse.client.ClickHouseException: Code: 216. DB::Exception: Query with id = ca038ba5-bcdc-4b93-a857-79b066382917:68 is already running. (QUERY_WITH_SAME_ID_IS_ALREADY_RUNNING) (version 22.2.2.1)
, server ClickHouseNode [uri=http://192.168.0.247:8123/WG_CK_QUERY]@-540220962
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
        at com.sunsharing.zeus.clickhousestatistic.component.ClickHouseClientActuator.executeSql(ClickHouseClientActuator.java:68)
        at com.sunsharing.zeus.clickhousestatistic.component.ProdTaskActuator.lambda$executeTask$0(ProdTaskActuator.java:45)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.clickhouse.client.ClickHouseException: Code: 216. DB::Exception: Query with id = ca038ba5-bcdc-4b93-a857-79b066382917:68 is already running. (QUERY_WITH_SAME_ID_IS_ALREADY_RUNNING) (version 22.2.2.1)
, server ClickHouseNode [uri=http://192.168.0.247:8123/WG_CK_QUERY]@-540220962
        at com.clickhouse.client.ClickHouseException.of(ClickHouseException.java:168)
        at com.clickhouse.client.AbstractClient.lambda$execute$0(AbstractClient.java:291)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
        ... 3 more
Caused by: java.io.IOException: Code: 216. DB::Exception: Query with id = ca038ba5-bcdc-4b93-a857-79b066382917:68 is already running. (QUERY_WITH_SAME_ID_IS_ALREADY_RUNNING) (version 22.2.2.1)

```

**Comment by den-crane** [comment]
ask this in https://github.com/ClickHouse/clickhouse-jdbc

**Comment by zhengwenhao07** [comment]
> ask this in https://github.com/ClickHouse/clickhouse-jdbc
Thank you, I have resolved it!

**Comment by sokolov-alexey** [comment]
> > ask this in https://github.com/ClickHouse/clickhouse-jdbc
> > Thank you, I have resolved it!

Could you describe how you fixed it?
