### ISSUE TITLE
Create ReplicatedMergeTree table , but return KEEPER_EXCEPTION

### ISSUE THREAD

**Issue by ChaoHsupin** [ClickHouse/ClickHouse#40603]
Thans for your work!

### clickhouse version
22.2.3.1

I construct a cluster on k8s by zookeeper!
I create database on cluster successfuly , but i can't create ReplicatedMergeTree table by on cluster.

### execute sql：
````
CREATE TABLE IF NOT EXISTS monitor.rum_performance ON CLUSTER clicks_cluster
(
    `cop` String,
    `owt` String,
    `pdl` String,
    `service` String,
    `isLoadend` String,
    `isCache` String,
    `isLocalCache` String,
    `isValidateCache` String,
    `isLowEndDevice` String,
    `saveData` String,
    `isLowEndNetwork` String,
    `isRestore` String,
    `timestamp` DateTime64(3, 'Asia/Shanghai'),
    `load` Float32,
    `ttsr` Float32,
    `deviceMemory` Float32,
    `hardwareConcurrency` Float32,
    `timeOrigin` Float32,
    `networkRtt` Float32,
    `networkOnline` Float32
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/rum-performance', '{replica}')
PARTITION BY toYYYYMMDD(timestamp)
ORDER BY timestamp
````

### error return after execute sql:
````
Query id: fb6a2020-048c-4775-a85a-b3ccd7e69b1d

┌─host───────────────────────────────────────────────────────────┬─port─┬─status─┬─error────────────────────────────────────────────────────────────────────────────────────┬─num_hosts_remaining─┬─num_hosts_active─┐
│ clickhouse-prod-1.clickhouse-prod-hs.monitor.svc.cluster.local │ 9000 │    999 │ Code: 999. Coordination::Exception: Bad arguments. (KEEPER_EXCEPTION) (version 22.2.3.1) │                   1 │                0 │
│ clickhouse-prod-0.clickhouse-prod-hs.monitor.svc.cluster.local │ 9000 │    999 │ Code: 999. Coordination::Exception: Bad arguments. (KEEPER_EXCEPTION) (version 22.2.3.1) │                   0 │                0 │
└────────────────────────────────────────────────────────────────┴──────┴────────┴──────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────┴──────────────────┘
````
### clickhouse node logs:
````
2022.08.25 07:28:48.628010 [ 230 ] {791ab844-26da-47e0-b17b-1c1b7d5905c1} <Error> DDLWorker: Query CREATE TABLE IF NOT EXISTS monitor.rum_performan UUID '07c19bd8-704d-4a72-946a-1428b7e52463' (`cop` String, `owt` String, `pdl` String, `service` String, `cluster` String, `type` String, `subType` String, `initiatorType` String, `nextHopProtocol` String, `method` String, `statusCode` String, `statusText` String, `hunterId` String, `bizcode` String, `name` String, `nameHost` String, `feBu` String, `resourceId` String, `serviceWithStage` String, `_uniqueId` String, `url` String, `urlHost` String, `outerHTML` String, `path` String, `namePattern` String, `feVersion` String, `screenSize` String, `viewport` String, `ua` String, `pfeBu` String, `toolVersion` String, `refer` String, `visitId` String, `qhdi` String, `userId` String, `userLevel` String, `sessionId` String, `designId` String, `levelId` String, `obsRootAccountId` String, `connectionType` String, `downlink` String, `effectiveType` String, `browser` String, `os` String, `async` String, `isTimeout` String, `isAborted` String, `isCanceled` String, `isSuccess` String, `isLoadend` String, `isCache` String, `isLocalCache` String, `isValidateCache` String, `isLowEndDevice` String, `saveData` String, `isLowEndNetwork` String, `isRestore` String, `timestamp` DateTime64(3, 'Asia/Shanghai'), `connectEnd` Float32, `connectStart` Float32, `decodedBodySize` Float32, `domainLookupEnd` Float32, `domainLookupStart` Float32, `encodedBodySize` Float32, `fetchStart` Float32, `redirectCount` Float32, `redirectEnd` Float32, `redirectStart` Float32, `requestStart` Float32, `responseEnd` Float32, `responseStart` Float32, `secureConnectionStart` Float32, `transferSize` Float32, `workerStart` Float32, `redirectMs` Float32, `appCacheMs` Float32, `dnsMs` Float32, `tcpMs` Float32, `sslMs` Float32, `ttfb` Float32, `workerMs` Float32, `networkMs` Float32, `downloadMs` Float32, `fetchMs` Float32, `headerSize` Float32, `resBodySize` Float32, `resourceSize` Float32, `reqBodySize` Float32, `timeout` Float32, `startTime` Float32, `endTime` Float32, `duration` Float32, `domComplete` Float32, `domContentLoadedEventEnd` Float32, `domContentLoadedEventStart` Float32, `domInteractive` Float32, `loadEventEnd` Float32, `loadEventStart` Float32, `unloadEventEnd` Float32, `unloadEventStart` Float32, `parseMs` Float32, `loadMs` Float32, `unload` Float32, `tti` Float32, `ready` Float32, `load` Float32, `ttsr` Float32, `deviceMemory` Float32, `hardwareConcurrency` Float32, `timeOrigin` Float32, `networkRtt` Float32, `networkOnline` Float32) ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/rum-performan', '{replica}') PARTITION BY toYYYYMMDD(timestamp) ORDER BY timestamp wasn't finished successfully: Code: 999. Coordination::Exception: Bad arguments. (KEEPER_EXCEPTION), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xaebee1a in /usr/bin/clickhouse
1. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error, int) @ 0x15e2b9d5 in /usr/bin/clickhouse
2. Coordination::Exception::Exception(Coordination::Error) @ 0x15e2bffe in /usr/bin/clickhouse
3. zkutil::ZooKeeper::tryMulti(std::__1::vector<std::__1::shared_ptr<Coordination::Request>, std::__1::allocator<std::__1::shared_ptr<Coordination::Request> > > const&, std::__1::vector<std::__1::shared_ptr<Coordination::Response>, std::__1::allocator<std::__1::shared_ptr<Coordination::Response> > >&) @ 0x15e38002 in /usr/bin/clickhouse
4. DB::StorageReplicatedMergeTree::createTableIfNotExists(std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&) @ 0x1516bfd1 in /usr/bin/clickhouse
5. DB::StorageReplicatedMergeTree::StorageReplicatedMergeTree(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, DB::StorageID const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::StorageInMemoryMetadata const&, std::__1::shared_ptr<DB::Context>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::MergeTreeData::MergingParams const&, std::__1::unique_ptr<DB::MergeTreeSettings, std::__1::default_delete<DB::MergeTreeSettings> >, bool, bool) @ 0x1516584c in /usr/bin/clickhouse
6. ? @ 0x156ad036 in /usr/bin/clickhouse
7. DB::StorageFactory::get(DB::ASTCreateQuery const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, std::__1::shared_ptr<DB::Context>, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, bool) const @ 0x150d7afa in /usr/bin/clickhouse
8. DB::InterpreterCreateQuery::doCreateTable(DB::ASTCreateQuery&, DB::InterpreterCreateQuery::TableProperties const&) @ 0x14bc4671 in /usr/bin/clickhouse
9. DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0x14bbf4cd in /usr/bin/clickhouse
10. DB::InterpreterCreateQuery::execute() @ 0x14bc6f6b in /usr/bin/clickhouse
11. ? @ 0x14ee9bd9 in /usr/bin/clickhouse
12. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, std::__1::optional<DB::FormatSettings> const&) @ 0x14eecf8a in /usr/bin/clickhouse
13. DB::DDLWorker::tryExecuteQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::DDLTaskBase&, std::__1::shared_ptr<zkutil::ZooKeeper> const&) @ 0x146e578e in /usr/bin/clickhouse
14. DB::DDLWorker::processTask(DB::DDLTaskBase&, std::__1::shared_ptr<zkutil::ZooKeeper> const&) @ 0x146e41f2 in /usr/bin/clickhouse
15. DB::DDLWorker::scheduleTasks(bool) @ 0x146e1f63 in /usr/bin/clickhouse
16. DB::DDLWorker::runMainThread() @ 0x146dbce5 in /usr/bin/clickhouse
17. ThreadFromGlobalPool::ThreadFromGlobalPool<void (DB::DDLWorker::*)(), DB::DDLWorker*>(void (DB::DDLWorker::*&&)(), DB::DDLWorker*&&)::'lambda'()::operator()() @ 0x146efa37 in /usr/bin/clickhouse
18. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xaf62937 in /usr/bin/clickhouse
19. ? @ 0xaf663fd in /usr/bin/clickhouse
20. ? @ 0x7f089c1d1609 in ?
21. __clone @ 0x7f089c0f8293 in ?
 (version 22.2.3.1)
````

### check zookeeper logs：
````
2022-08-25 07:04:00,495 [myid:] - WARN  [NIOWorkerThread-2:o.a.z.s.NIOServerCnxn@371] - Unexpected exception
org.apache.zookeeper.server.ServerCnxn$EndOfStreamException: Unable to read additional data from client, it probably closed the socket: address = /172.18.30.38:54906, session = 0x20b8b4405e40000
	at org.apache.zookeeper.server.NIOServerCnxn.handleFailedRead(NIOServerCnxn.java:170)
	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:333)
	at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:508)
	at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:153)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
````

**Comment by ChaoHsupin** [comment]
I had solve it!
my macros.xml value have spacing，such as：
````
    <yandex>
      <macros>
        <shard>1</shard>
        <replica>
1
       </replica>
      </macros>
    </yandex>
````
