### ISSUE TITLE
CH version 22.5.1.2079: Select query fails with exception DB::Exception: Unknown codec family code: 19: (while reading column xxxx)

### ISSUE THREAD

**Issue by KarthikSRaj** [ClickHouse/ClickHouse#41329]
CH version 22.5.1.2079 is running in production for 3-4 months now, and no upgrades were done.

We have table with below schema:

```
CREATE TABLE UeMapping_local
(
    `imsi` Int64 CODEC(Delta(8), Default),
    `startdate` DateTime CODEC(Delta(4), Default),
    `enddate` DateTime CODEC(Delta(4), Default),
    `mappedue` String,
    `maptype` LowCardinality(String),
    `version` DateTime CODEC(Delta(4), Default),
    INDEX imsi_index1 imsi TYPE minmax GRANULARITY 1,
    INDEX startdate_index2 startdate TYPE minmax GRANULARITY 1,
    INDEX enddate_index3 enddate TYPE minmax GRANULARITY 1,
    INDEX maptype_index4 maptype TYPE set(0) GRANULARITY 1
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard1}/UeMapping/1639596378', '{replica1}', version)
PARTITION BY toYYYYMMDD(startdate)
PRIMARY KEY (imsi, startdate, maptype)
ORDER BY (imsi, startdate, maptype)
SETTINGS index_granularity = 8192 
```
When querying above table using JDBC jar, by passing msisdn in "where clause", we are getting below exception. 
`Query: select imsi from dbsbm.UeMapping final where mappedue = 'xxxxx' and maptype='x'`

**This does not happen for all queries and same query seem to work fine at later point of time.
We have not seen same behavior when tried from CH console or when we try locally.**

Below is the exception:
```
ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: 10.90.120.143, port: 8123; Code: 432. DB::Exception: Received from 10.90.120.144:9100. DB::Exception: Unknown codec family code: 19: (while reading column imsi): (while reading from part /mnt2/clickhouse-server/data/store/371/371b547c-262b-43d6-a8c2-3f05f83552b5/20220625_0_1311892_42131_1486032/ from mark 10 with max_rows_to_read = 8192): While executing MergeTreeInOrder. (UNKNOWN_CODEC) (version 22.5.1.2079 (official build))
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.getException(ClickHouseExceptionSpecifier.java:91) ~[clickhouse-jdbc-0.2.6.jar:0.2.6]
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:55) ~[clickhouse-jdbc-0.2.6.jar:0.2.6]
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:28) ~[clickhouse-jdbc-0.2.6.jar:0.2.6]
	at ru.yandex.clickhouse.ClickHouseStatementImpl.checkForErrorAndThrow(ClickHouseStatementImpl.java:1046) ~[clickhouse-jdbc-0.2.6.jar:0.2.6]
	at ru.yandex.clickhouse.ClickHouseStatementImpl.getInputStream(ClickHouseStatementImpl.java:737) ~[clickhouse-jdbc-0.2.6.jar:0.2.6]
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:196) ~[clickhouse-jdbc-0.2.6.jar:0.2.6]
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:166) ~[clickhouse-jdbc-0.2.6.jar:0.2.6]
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:161) ~[clickhouse-jdbc-0.2.6.jar:0.2.6]
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:156) ~[clickhouse-jdbc-0.2.6.jar:0.2.6]
```
It has become blocker for us, please let us know what's the reason for this issue and ways to fix it?
Inserts are not failing, hence not sure if this is only select query related flow issue or source data is corrupted?

**Comment by alexey-milovidov** [comment]
Install the new ClickHouse release.

**Comment by KarthikSRaj** [comment]
Please let me know if this issue is related to "Select query" or "Inserted data" or "index" or "something else"?
If, its the case of corrupted data, we need to plan accordingly in production.
Also, please share the github bug URL which captures same behavior in any of the builds and probable solution.

**Comment by den-crane** [comment]
@KarthikSRaj upgrade at least to 22.5.4.19 (bugfix release for 22.5.1.2079)

After upgrade use `check table` https://clickhouse.com/docs/en/sql-reference/statements/check-table/#checking-the-mergetree-family-tables

Most probably it's a bug related to select/read.

**Comment by KarthikSRaj** [comment]
Output of query `select value from system.settings where name = 'local_filesystem_read_method';` on all CH machines are as below:

┌─value─┐
│ pread │
└───────┘
