### ISSUE TITLE
stack-use-after-scope in CompressedReadBufferBase::readCompressedData

### ISSUE THREAD

**Issue by kssenii** [ClickHouse/ClickHouse#41748]
https://s3.amazonaws.com/clickhouse-test-reports/41733/307314e1bd8cc93bcfa52abdef6d605e9381ce4e/stress_test__asan_/stderr.log
```
==1649==WARNING: ASan doesn't fully support makecontext/swapcontext functions and may produce false positives in some cases!
=================================================================
==1649==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7f3815ce4980 at pc 0x00000dccfcb7 bp 0x7f388b54a3f0 sp 0x7f388b549bc0
READ of size 36180 at 0x7f3815ce4980 thread T354 (QueryPipelineEx)
    #0 0xdccfcb6 in __asan_memcpy (/usr/bin/clickhouse+0xdccfcb6) (BuildId: a64cd2d8b4b6a0e56e40dbfabcb50261b07b0f38)
    #1 0xdee51a8 in DB::ReadBuffer::read(char*, unsigned long) build_docker/../src/IO/ReadBuffer.h:178:13
    #2 0xdee51a8 in DB::ReadBuffer::readStrict(char*, unsigned long) build_docker/../src/IO/ReadBuffer.h:189:27
    #3 0x2ccc0662 in DB::CompressedReadBufferBase::readCompressedData(unsigned long&, unsigned long&, bool) build_docker/../src/Compression/CompressedReadBufferBase.cpp:192:24
    #4 0x31bee1a1 in DB::CachedCompressedReadBuffer::nextImpl()::$_0::operator()() const build_docker/../src/Compression/CachedCompressedReadBuffer.cpp:52:33
    #5 0x31bee1a1 in std::__1::pair<std::__1::shared_ptr<DB::UncompressedCacheCell>, bool> DB::CacheBase<wide::integer<128ul, unsigned int>, DB::UncompressedCacheCell, UInt128TrivialHash, DB::UncompressedSizeWeightFunction>::getOrSet<DB::CachedCompressedReadBuffer::nextImpl()::$_0>(wide::integer<128ul, unsigned int> const&, DB::CachedCompressedReadBuffer::nextImpl()::$_0&&) build_docker/../src/Common/CacheBase.h:125:24
    #6 0x31bee1a1 in std::__1::shared_ptr<DB::UncompressedCacheCell> DB::UncompressedCache::getOrSet<DB::CachedCompressedReadBuffer::nextImpl()::$_0>(wide::integer<128ul, unsigned int> const&, DB::CachedCompressedReadBuffer::nextImpl()::$_0&&) build_docker/../src/IO/UncompressedCache.h:64:29
    #7 0x31bee1a1 in DB::CachedCompressedReadBuffer::nextImpl() build_docker/../src/Compression/CachedCompressedReadBuffer.cpp:43:25
    #8 0xdde7e10 in DB::ReadBuffer::next() build_docker/../src/IO/ReadBuffer.h:64:20
    #9 0xdde7e10 in DB::ReadBuffer::eof() build_docker/../src/IO/ReadBuffer.h:98:38
    #10 0xdde7e10 in DB::ReadBuffer::read(char*, unsigned long) build_docker/../src/IO/ReadBuffer.h:175:37
    #11 0xdde7e10 in DB::ReadBuffer::readBig(char*, unsigned long) build_docker/../src/IO/ReadBuffer.h:202:16
    #12 0x2d25ae90 in DB::SerializationNumber<long>::deserializeBinaryBulk(DB::IColumn&, DB::ReadBuffer&, unsigned long, double) const build_docker/../src/DataTypes/Serializations/SerializationNumber.cpp:154:24
    #13 0x2d17b7dd in DB::ISerialization::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>>*) const build_docker/../src/DataTypes/Serializations/ISerialization.cpp:132:9
    #14 0x31bdc9b6 in DB::MergeTreeReaderCompact::readData(DB::NameAndTypePair const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, unsigned long, unsigned long, unsigned long, bool) build_docker/../src/Storages/MergeTree/MergeTreeReaderCompact.cpp:264:24
    #15 0x31bdb472 in DB::MergeTreeReaderCompact::readRows(unsigned long, unsigned long, bool, unsigned long, std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&) build_docker/../src/Storages/MergeTree/MergeTreeReaderCompact.cpp:183:17
    #16 0x32e7cc6a in DB::MergeTreeRangeReader::DelayedStream::readRows(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&, unsigned long) build_docker/../src/Storages/MergeTree/MergeTreeRangeReader.cpp:101:47
    #17 0x32e7cc6a in DB::MergeTreeRangeReader::DelayedStream::finalize(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&) build_docker/../src/Storages/MergeTree/MergeTreeRangeReader.cpp:175:12
    #18 0x32e8bedc in DB::MergeTreeRangeReader::Stream::finalize(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&) build_docker/../src/Storages/MergeTree/MergeTreeRangeReader.cpp:286:31
    #19 0x32e8bedc in DB::MergeTreeRangeReader::startReadingChain(unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange>>&) build_docker/../src/Storages/MergeTree/MergeTreeRangeReader.cpp:946:27
    #20 0x32e871a6 in DB::MergeTreeRangeReader::read(unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange>>&) build_docker/../src/Storages/MergeTree/MergeTreeRangeReader.cpp:854:23
    #21 0x32e67253 in DB::MergeTreeBaseSelectProcessor::readFromPartImpl() build_docker/../src/Storages/MergeTree/MergeTreeBaseSelectProcessor.cpp:385:43
    #22 0x32e683b6 in DB::MergeTreeBaseSelectProcessor::readFromPart() build_docker/../src/Storages/MergeTree/MergeTreeBaseSelectProcessor.cpp:425:12
    #23 0x32e5e0b7 in DB::MergeTreeBaseSelectProcessor::generate() build_docker/../src/Storages/MergeTree/MergeTreeBaseSelectProcessor.cpp:217:20
    #24 0x323b99f5 in DB::ISource::tryGenerate() build_docker/../src/Processors/ISource.cpp:124:18
    #25 0x323b8b7e in DB::ISource::work() build_docker/../src/Processors/ISource.cpp:94:26
    #26 0x3240602d in DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*) build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:47:26
    #27 0x3240602d in DB::ExecutionThreadContext::executeTask() build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:92:9
    #28 0x323e53c4 in DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:228:26
    #29 0x323e8e0b in DB::PipelineExecutor::executeSingleThread(unsigned long) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:194:5
    #30 0x323e8e0b in DB::PipelineExecutor::spawnThreads()::$_0::operator()() const build_docker/../src/Processors/Executors/PipelineExecutor.cpp:315:17
    #31 0x323e8e0b in decltype(static_cast<DB::PipelineExecutor::spawnThreads()::$_0&>(fp)()) std::__1::__invoke_constexpr<DB::PipelineExecutor::spawnThreads()::$_0&>(DB::PipelineExecutor::spawnThreads()::$_0&) build_docker/../contrib/libcxx/include/type_traits:3648:23
    #32 0x323e8e0b in decltype(auto) std::__1::__apply_tuple_impl<DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&>(DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/tuple:1595:1
    #33 0x323e8e0b in decltype(auto) std::__1::apply<DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&>(DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&) build_docker/../contrib/libcxx/include/tuple:1604:1
    #34 0x323e8e0b in ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()::operator()() build_docker/../src/Common/ThreadPool.h:193:13
    #35 0x323e8e0b in decltype(static_cast<DB::PipelineExecutor::spawnThreads()::$_0>(fp)()) std::__1::__invoke<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&>(DB::PipelineExecutor::spawnThreads()::$_0&&) build_docker/../contrib/libcxx/include/type_traits:3640:23
    #36 0x323e8e0b in void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&) build_docker/../contrib/libcxx/include/__functional/invoke.h:61:9
    #37 0x323e8e0b in std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'(), void ()>::operator()() build_docker/../contrib/libcxx/include/__functional/function.h:230:12
    #38 0x323e8e0b in void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) build_docker/../contrib/libcxx/include/__functional/function.h:711:16
    #39 0xdf30e5f in std::__1::__function::__policy_func<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:843:16
    #40 0xdf30e5f in std::__1::function<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:1184:12
    #41 0xdf30e5f in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) build_docker/../src/Common/ThreadPool.cpp:294:17
    #42 0xdf3a94c in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const build_docker/../src/Common/ThreadPool.cpp:144:73
    #43 0xdf3a94c in decltype(static_cast<void>(fp)()) std::__1::__invoke<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&) build_docker/../contrib/libcxx/include/type_traits:3640:23
    #44 0xdf3a94c in void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/thread:282:5
    #45 0xdf3a94c in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) build_docker/../contrib/libcxx/include/thread:293:5
    #46 0x7f3b38b28608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8608) (BuildId: 7b4536f41cdaa5888408e82d0836e33dcf436466)
    #47 0x7f3b38a4d132 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x11f132) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)

Address 0x7f3815ce4980 is a wild pointer inside of access range of size 0x000000008d54.
SUMMARY: AddressSanitizer: stack-use-after-scope (/usr/bin/clickhouse+0xdccfcb6) (BuildId: a64cd2d8b4b6a0e56e40dbfabcb50261b07b0f38) in __asan_memcpy
Shadow bytes around the buggy address:
  0x0fe782b948e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe782b948f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe782b94900: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe782b94910: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe782b94920: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0fe782b94930:[f8]00 00 00 f8 00 00 00 00 00 00 00 00 00 00 00
  0x0fe782b94940: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe782b94950: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe782b94960: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe782b94970: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe782b94980: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
Thread T354 (QueryPipelineEx) created by T332 (TCPHandler) here:
    #0 0xdcb985c in pthread_create (/usr/bin/clickhouse+0xdcb985c) (BuildId: a64cd2d8b4b6a0e56e40dbfabcb50261b07b0f38)
    #1 0xdf397d4 in std::__1::__libcpp_thread_create(unsigned long*, void* (*)(void*), void*) build_docker/../contrib/libcxx/include/__threading_support:375:10
    #2 0xdf397d4 in std::__1::thread::thread<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'(), void>(void&&) build_docker/../contrib/libcxx/include/thread:309:16
    #3 0xdf2da2b in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool) build_docker/../src/Common/ThreadPool.cpp:144:35
    #4 0xdf3fc47 in ThreadPoolImpl<std::__1::thread>::scheduleOrThrow(std::__1::function<void ()>, int, unsigned long, bool) build_docker/../src/Common/ThreadPool.cpp:180:5
    #5 0xdf3fc47 in ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&) build_docker/../src/Common/ThreadPool.h:176:38
    #6 0xdf334c2 in void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool) build_docker/../src/Common/ThreadPool.cpp:144:35
    #7 0xdf32bfb in ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleOrThrowOnError(std::__1::function<void ()>, int) build_docker/../src/Common/ThreadPool.cpp:168:5
    #8 0x326d3ff0 in DB::ParallelFormattingOutputFormat::scheduleFormatterThreadForUnitWithNumber(unsigned long, unsigned long) build_docker/../src/Processors/Formats/Impl/ParallelFormattingOutputFormat.h:251:14
    #9 0x326d0a52 in DB::ParallelFormattingOutputFormat::addChunk(DB::Chunk, DB::ParallelFormattingOutputFormat::ProcessingUnitType, bool) build_docker/../src/Processors/Formats/Impl/ParallelFormattingOutputFormat.cpp:66:9
    #10 0x326d57db in DB::ParallelFormattingOutputFormat::consume(DB::Chunk) build_docker/../src/Processors/Formats/Impl/ParallelFormattingOutputFormat.h:138:9
    #11 0x32424edf in DB::IOutputFormat::work() build_docker/../src/Processors/Formats/IOutputFormat.cpp:84:13
    #12 0x3240602d in DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*) build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:47:26
    #13 0x3240602d in DB::ExecutionThreadContext::executeTask() build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:92:9
    #14 0x323e53c4 in DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:228:26
    #15 0x323e3cb5 in DB::PipelineExecutor::executeSingleThread(unsigned long) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:194:5
    #16 0x323e3cb5 in DB::PipelineExecutor::executeImpl(unsigned long) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:367:9
    #17 0x323e3894 in DB::PipelineExecutor::execute(unsigned long) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:89:9
    #18 0x323e119f in DB::CompletedPipelineExecutor::execute() build_docker/../src/Processors/Executors/CompletedPipelineExecutor.cpp:100:18
    #19 0x2ffec3ef in DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)>, std::__1::optional<DB::FormatSettings> const&) build_docker/../src/Interpreters/executeQuery.cpp:1242:22
    #20 0x32208aa6 in DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) build_docker/../src/Server/HTTPHandler.cpp:818:5
    #21 0x322169ee in DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) build_docker/../src/Server/HTTPHandler.cpp:990:9
    #22 0x3232f68f in DB::HTTPServerConnection::run() build_docker/../src/Server/HTTP/HTTPServerConnection.cpp:65:34
    #23 0x3925b18e in Poco::Net::TCPServerConnection::start() build_docker/../contrib/poco/Net/src/TCPServerConnection.cpp:43:3
    #24 0x3925bf12 in Poco::Net::TCPServerDispatcher::run() build_docker/../contrib/poco/Net/src/TCPServerDispatcher.cpp:115:20
    #25 0x397308fb in Poco::PooledThread::run() build_docker/../contrib/poco/Foundation/src/ThreadPool.cpp:199:14
    #26 0x3972a1e7 in Poco::ThreadImpl::runnableEntry(void*) build_docker/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345:27
    #27 0x7f3b38b28608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8608) (BuildId: 7b4536f41cdaa5888408e82d0836e33dcf436466)

Thread T332 (TCPHandler) created by T316 here:
    #0 0xdcb985c in pthread_create (/usr/bin/clickhouse+0xdcb985c) (BuildId: a64cd2d8b4b6a0e56e40dbfabcb50261b07b0f38)
    #1 0x3972943e in Poco::ThreadImpl::startImpl(Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable>>) build_docker/../contrib/poco/Foundation/src/Thread_POSIX.cpp:202:6
    #2 0x3972c5fd in Poco::Thread::start(Poco::Runnable&) build_docker/../contrib/poco/Foundation/src/Thread.cpp:128:2
    #3 0x39734a07 in Poco::PooledThread::start() build_docker/../contrib/poco/Foundation/src/ThreadPool.cpp:85:10
    #4 0x39734a07 in Poco::ThreadPool::getThread() build_docker/../contrib/poco/Foundation/src/ThreadPool.cpp:461:14
    #5 0x397350f6 in Poco::ThreadPool::startWithPriority(Poco::Thread::Priority, Poco::Runnable&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) build_docker/../contrib/poco/Foundation/src/ThreadPool.cpp:365:2
    #6 0x3925cb4b in Poco::Net::TCPServerDispatcher::enqueue(Poco::Net::StreamSocket const&) build_docker/../contrib/poco/Net/src/TCPServerDispatcher.cpp:152:17
    #7 0x3925aa57 in Poco::Net::TCPServer::run() build_docker/../contrib/poco/Net/src/TCPServer.cpp:148:21
    #8 0x3972a1e7 in Poco::ThreadImpl::runnableEntry(void*) build_docker/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345:27
    #9 0x7f3b38b28608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8608) (BuildId: 7b4536f41cdaa5888408e82d0836e33dcf436466)

Thread T316 created by T0 here:
    #0 0xdcb985c in pthread_create (/usr/bin/clickhouse+0xdcb985c) (BuildId: a64cd2d8b4b6a0e56e40dbfabcb50261b07b0f38)
    #1 0x3972943e in Poco::ThreadImpl::startImpl(Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable>>) build_docker/../contrib/poco/Foundation/src/Thread_POSIX.cpp:202:6
    #2 0x3972c5fd in Poco::Thread::start(Poco::Runnable&) build_docker/../contrib/poco/Foundation/src/Thread.cpp:128:2
    #3 0xdd43c14 in DB::ProtocolServerAdapter::start() build_docker/../src/Server/ProtocolServerAdapter.h:29:26
    #4 0xdd43c14 in DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) build_docker/../programs/server/Server.cpp:1772:24
    #5 0x39293c26 in Poco::Util::Application::run() build_docker/../contrib/poco/Util/src/Application.cpp:334:8
    #6 0xdd1aedf in DB::Server::run() build_docker/../programs/server/Server.cpp:466:25
    #7 0x392d73d8 in Poco::Util::ServerApplication::run(int, char**) build_docker/../contrib/poco/Util/src/ServerApplication.cpp:611:9
    #8 0xdd13c8f in mainEntryClickHouseServer(int, char**) build_docker/../programs/server/Server.cpp:181:20
    #9 0xdd0e79a in main build_docker/../programs/main.cpp:480:12
    #10 0x7f3b38952082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)

==1649==ABORTING
```

**Comment by tavplubix** [comment]
Looks like https://github.com/ClickHouse/ClickHouse/issues/41500 (so it's not related to LowCardinality)
