### ISSUE TITLE
Flow into hdfs cause SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by ArsenyClean** [ClickHouse/ClickHouse#42119]
I flow 600 MB files into ClickHouse with  HDFS storage

Caused by: java.net.SocketTimeoutException: Read timed out
at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:283)
at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309)
at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
at ru.yandex.clickhouse.ClickHouseStatementImpl.sendStream(ClickHouseStatementImpl.java:1059)
... 26 common frames omitted

**Comment by ArsenyClean** [comment]
I flow 600 MB files into ClickHouse that storeage is HDFS

Caused by: java.net.SocketTimeoutException: Read timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:283)
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309)
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
        at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at ru.yandex.clickhouse.ClickHouseStatementImpl.sendStream(ClickHouseStatementImpl.java:1059)
        ... 26 common frames omitted

**Comment by DerekChia** [comment]
Which version of Hadoop and ClickHouse are you using? Were you able to stream smaller files before this?

**Comment by ArsenyClean** [comment]
[DerekChia](https://github.com/DerekChia)

ClickHouse  22.9.3.18

Hadoop 3.2.2


I cant understand, why clickhouse need smaller files? Cause Hdfs is not for small files

How to configure clickhouse to save into hdfs files with exact size?

Here the error.log

```
2022.10.12 13:20:55.962004 [ 237873 ] {} <Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 32, I/O error: Broken pipe, Stack trace (when copying this message, always include the lines below):

0. Poco::Net::SocketImpl::error(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x159abec1 in /usr/bic/1.0.0/clickhouse/bin/clickhouse
1. Poco::Net::SocketImpl::sendBytes(void const*, int, int) @ 0x159ad063 in /usr/bic/1.0.0/clickhouse/bin/clickhouse
2. Poco::Net::StreamSocketImpl::sendBytes(void const*, int, int) @ 0x159b1717 in /usr/bic/1.0.0/clickhouse/bin/clickhouse
3. Poco::Net::HTTPSession::write(char const*, long) @ 0x1598b573 in /usr/bic/1.0.0/clickhouse/bin/clickhouse
4. Poco::Net::HTTPChunkedIOS::~HTTPChunkedIOS() @ 0x1597171a in /usr/bic/1.0.0/clickhouse/bin/clickhouse
5. Poco::Net::HTTPChunkedOutputStream::~HTTPChunkedOutputStream() @ 0x159722a2 in /usr/bic/1.0.0/clickhouse/bin/clickhouse
6. DB::HTTPServerConnection::run() @ 0x12f2a138 in /usr/bic/1.0.0/clickhouse/bin/clickhouse
7. Poco::Net::TCPServerConnection::start() @ 0x159b27af in /usr/bic/1.0.0/clickhouse/bin/clickhouse
8. Poco::Net::TCPServerDispatcher::run() @ 0x159b4b3b in /usr/bic/1.0.0/clickhouse/bin/clickhouse
9. Poco::PooledThread::run() @ 0x15b700d2 in /usr/bic/1.0.0/clickhouse/bin/clickhouse
10. Poco::ThreadImpl::runnableEntry(void*) @ 0x15b6d85d in /usr/bic/1.0.0/clickhouse/bin/clickhouse
11. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
12. __clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
 (version 22.9.3.18 (official build))

```

**Comment by ArsenyClean** [comment]
@DerekChia  ?

**Comment by DerekChia** [comment]
@ArsenyClean let me try to replicate this issue on my end

**Comment by ArsenyClean** [comment]
@DerekChia we just make little file batch and this solve the problem

**Comment by DerekChia** [comment]
> @DerekChia we just make little file batch and this solve the problem

how small are these files?

**Comment by alexey-milovidov** [comment]
Hadoop and HDFS don't matter for us.
