### ISSUE TITLE
std::logic_error: Error in function boost::math::students_t_distribution<double> Degrees of freedom argument is -nan, but must be > 0 !

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#42162]
We exit in debug build on std:logic_error
```
2022.10.07 18:03:05.870264 [ 149 ] {b0d49df1-90d2-41aa-ba64-7bb6f85c6f01} <Debug> executeQuery: (from [::ffff:127.0.0.1]:54736) SELECT roundBankers(welchTTest(0., left).1, 257) AS t_stat, roundBankers(welchTTest(left, right).2, 255) AS p_value FROM welch_ttest__fuzz_18 (stage: Complete)
2022.10.07 18:03:05.870696 [ 149 ] {b0d49df1-90d2-41aa-ba64-7bb6f85c6f01} <Trace> ContextAccess (default): Access granted: SELECT(left, right) ON default.welch_ttest__fuzz_18
2022.10.07 18:03:05.870747 [ 149 ] {b0d49df1-90d2-41aa-ba64-7bb6f85c6f01} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2022.10.07 18:03:05.871369 [ 397 ] {b0d49df1-90d2-41aa-ba64-7bb6f85c6f01} <Trace> AggregatingTransform: Aggregating
2022.10.07 18:03:05.871390 [ 397 ] {b0d49df1-90d2-41aa-ba64-7bb6f85c6f01} <Trace> Aggregator: An entry for key=9746532784133328337 found in cache: sum_of_sizes=1, median_size=1
2022.10.07 18:03:05.871403 [ 397 ] {b0d49df1-90d2-41aa-ba64-7bb6f85c6f01} <Trace> Aggregator: Aggregation method: without_key
2022.10.07 18:03:05.871477 [ 397 ] {b0d49df1-90d2-41aa-ba64-7bb6f85c6f01} <Debug> AggregatingTransform: Aggregated. 1000 to 1 rows (from 9.78 KiB) in 0.000543136 sec. (1841159.489 rows/sec., 17.59 MiB/sec.)
2022.10.07 18:03:05.871490 [ 397 ] {b0d49df1-90d2-41aa-ba64-7bb6f85c6f01} <Trace> Aggregator: Merging aggregated data
2022.10.07 18:03:05.910520 [ 149 ] {b0d49df1-90d2-41aa-ba64-7bb6f85c6f01} <Error> executeQuery: std::exception. Code: 1001, type: boost::wrapexcept<std::domain_error>, e.what() = Error in function boost::math::students_t_distribution<double>::students_t_distribution: Degrees of freedom argument is -nan, but must be > 0 ! (version 22.10.1.1) (from [::ffff:127.0.0.1]:54736) (in query: SELECT roundBankers(welchTTest(0., left).1, 257) AS t_stat, roundBankers(welchTTest(left, right).2, 255) AS p_value FROM welch_ttest__fuzz_18), Stack trace (when copying this message, always include the lines below):

0. std::exception::capture() @ 0x15871a4c in /workspace/clickhouse
1. ./build_docker/../contrib/libcxx/src/support/runtime/stdexcept_default.ipp:26: std::logic_error::logic_error(std::logic_error const&) @ 0x2fb0c01f in /workspace/clickhouse
2. boost::wrapexcept<std::domain_error>::wrapexcept(std::domain_error const&) @ 0x1ba91d98 in /workspace/clickhouse
3. void boost::throw_exception<std::domain_error>(std::domain_error const&) @ 0x1ba91b37 in /workspace/clickhouse
4. void boost::math::policies::detail::raise_error<std::domain_error, double>(char const*, char const*, double const&) @ 0x1ba96dbc in /workspace/clickhouse
5. ./build_docker/../contrib/boost/boost/math/policies/error_handling.hpp:0: DB::AggregateFunctionTTest<DB::(anonymous namespace)::WelchTTestData>::insertResultInto(char*, DB::IColumn&, DB::Arena*) const @ 0x24ce050e in /workspace/clickhouse
6. ./build_docker/../src/Interpreters/Aggregator.cpp:1817: void DB::Aggregator::insertAggregatesIntoColumns<char*>(char*&, std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, DB::Arena*) const @ 0x2a3d9328 in /workspace/clickhouse
7. ./build_docker/../src/Interpreters/Aggregator.cpp:0: DB::Aggregator::prepareBlockAndFillWithoutKey(DB::AggregatedDataVariants&, bool, bool) const @ 0x2a375b38 in /workspace/clickhouse
8. ./build_docker/../src/Processors/Transforms/AggregatingTransform.cpp:336: DB::ConvertingAggregatedToChunksTransform::initialize() @ 0x2ca1d7bd in /workspace/clickhouse
9. ./build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:50: DB::ExecutionThreadContext::executeTask() @ 0x2c679854 in /workspace/clickhouse
10. ./build_docker/../src/Processors/Executors/PipelineExecutor.cpp:228: DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x2c6698db in /workspace/clickhouse
11. ./build_docker/../src/Processors/Executors/PipelineExecutor.cpp:0: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x2c66add1 in /workspace/clickhouse
12. ./build_docker/../base/base/strong_typedef.h:23: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x1f9b7b93 in /workspace/clickhouse
13. ./build_docker/../src/Common/ThreadPool.cpp:0: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()> >(void*) @ 0x1f9bb964 in /workspace/clickhouse
14. ? @ 0x7f7dd4143609 in ?
15. clone @ 0x7f7dd4068133 in ?
```

```
2022-10-07 18:03:05	 Thread 4 "TCPHandler" received signal SIGABRT, Aborted.
2022-10-07 18:03:05	 [Switching to Thread 0x7f7dd288b700 (LWP 149)]
2022-10-07 18:03:05	 __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
2022-10-07 18:03:05	 50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
2022-10-07 18:03:05	 #0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
2022-10-07 18:03:05	         set = {__val = {20484, 744926673, 530283411, 530299236, 1125917086711976, 140171961973264, 140171961973264, 11376068507788127593, 2, 140178379777376, 140178379777408, 140178405779439, 3177, 140172163302912, 3177, 1610630656}}
2022-10-07 18:03:05	         pid = <optimized out>
2022-10-07 18:03:05	         tid = <optimized out>
2022-10-07 18:03:05	         ret = <optimized out>
2022-10-07 18:03:05	 #1  0x00007f7dd3f6b859 in __GI_abort () at abort.c:79
2022-10-07 18:03:06	         save_stage = 1
2022-10-07 18:03:06	         act = {__sigaction_handler = {sa_handler = 0xc69, sa_sigaction = 0xc69}, sa_mask = {__val = {0, 140172173741344, 4294967298, 311, 660553662, 9223372036854778768, 140172163301568, 140172163301280, 11376068507788127593, 12145682903073170759, 140172164354504, 140172171894960, 140172163301280, 11376068507788127593, 4, 140178379777856}}, sa_flags = 361276496, sa_restorer = 0x7f7c609f8d20}
2022-10-07 18:03:06	         sigs = {__val = {32, 0 <repeats 15 times>}}
2022-10-07 18:03:06	 #2  0x000000002c5e7f42 in DB::TCPHandler::runImpl (this=this@entry=0x7f7c60003fa0) at ../src/Server/TCPHandler.cpp:477
2022-10-07 18:03:06	         query_scope = {<std::__1::__optional_move_assign_base<DB::CurrentThread::QueryScope, false>> = {<std::__1::__optional_copy_assign_base<DB::CurrentThread::QueryScope, false>> = {<std::__1::__optional_move_base<DB::CurrentThread::QueryScope, false>> = {<std::__1::__optional_copy_base<DB::CurrentThread::QueryScope, false>> = {<std::__1::__optional_storage_base<DB::CurrentThread::QueryScope, false>> = {<std::__1::__optional_destruct_base<DB::CurrentThread::QueryScope, false>> = {{__null_state_ = 1 '\001', __val_ = <incomplete type>}, __engaged_ = true}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <std::__1::__sfinae_ctor_base<true, true>> = {<No data fields>}, <std::__1::__sfinae_assign_base<true, true>> = {<No data fields>}, <No data fields>}
2022-10-07 18:03:06	         exception = {__ptr_ = {<std::__1::__compressed_pair_elem<DB::Exception*, 0, false>> = {__value_ = 0x7f7c609f8d20}, <std::__1::__compressed_pair_elem<std::__1::default_delete<DB::Exception>, 1, true>> = {<std::__1::default_delete<DB::Exception>> = {<No data fields>}, <No data fields>}, <No data fields>}}
2022-10-07 18:03:06	         thread_trace_context = {__ptr_ = {<std::__1::__compressed_pair_elem<DB::OpenTelemetry::TracingContextHolder*, 0, false>> = {__value_ = 0x7f7c623e1df0}, <std::__1::__compressed_pair_elem<std::__1::default_delete<DB::OpenTelemetry::TracingContextHolder>, 1, true>> = {<std::__1::default_delete<DB::OpenTelemetry::TracingContextHolder>> = {<No data fields>}, <No data fields>}, <No data fields>}}
2022-10-07 18:03:06	         network_error = false
2022-10-07 18:03:06	         query_duration_already_logged = false
2022-10-07 18:03:06	         e = <optimized out>
2022-10-07 18:03:06	         e = <optimized out>
2022-10-07 18:03:06	         e = <optimized out>
2022-10-07 18:03:06	         e = <optimized out>
2022-10-07 18:03:06	         e = <optimized out>
2022-10-07 18:03:06	         thread_status = <incomplete type>
2022-10-07 18:03:06	         e = <optimized out>
2022-10-07 18:03:06	 #3  0x000000002c6028da in DB::TCPHandler::run (this=0x7f7c60003fa0) at ../src/Server/TCPHandler.cpp:1879
2022-10-07 18:03:06	         e = <optimized out>
2022-10-07 18:03:06	 #4  0x000000002d589e4c in Poco::Net::TCPServerConnection::start (this=0x2) at ../contrib/poco/Net/src/TCPServerConnection.cpp:43
2022-10-07 18:03:06	         exc = <optimized out>
2022-10-07 18:03:06	         exc = <optimized out>
2022-10-07 18:03:06	 #5  0x000000002d58a33a in Poco::Net::TCPServerDispatcher::run (this=0x3a68a740) at ../contrib/poco/Net/src/TCPServerDispatcher.cpp:115
2022-10-07 18:03:06	         pConnection = <optimized out>
2022-10-07 18:03:06	         pCNf = <optimized out>
2022-10-07 18:03:06	         pNf = {_ptr = 0x7f7c54003a40}
2022-10-07 18:03:06	         lock = {_mutex = @0x3a68a810}
2022-10-07 18:03:06	         exc = <optimized out>
2022-10-07 18:03:06	         exc = <optimized out>
2022-10-07 18:03:06	         guard = {_ptr = 0x3a68a740}
2022-10-07 18:03:06	         idleTime = <optimized out>
2022-10-07 18:03:06	 #6  0x000000002d6ff5a7 in Poco::PooledThread::run (this=0x39ceea20) at ../contrib/poco/Foundation/src/ThreadPool.cpp:199
2022-10-07 18:03:06	         lock = {_mutex = @0x0}
2022-10-07 18:03:06	         pTarget = 0x3a68a740
2022-10-07 18:03:06	         exc = <optimized out>
2022-10-07 18:03:06	         exc = <optimized out>
2022-10-07 18:03:06	 #7  0x000000002d6fd14f in Poco::ThreadImpl::runnableEntry (pThread=0x39ceea58) at ../contrib/poco/Foundation/src/Thread_POSIX.cpp:345
2022-10-07 18:03:06	         sset = {__val = {20484, 0 <repeats 15 times>}}
2022-10-07 18:03:06	         pThreadImpl = 0x39ceea58
2022-10-07 18:03:06	         pData = {_ptr = 0x39ceec80}
2022-10-07 18:03:06	         exc = <optimized out>
2022-10-07 18:03:06	         exc = <optimized out>
2022-10-07 18:03:06	 #8  0x00007f7dd4143609 in start_thread (arg=<optimized out>) at pthread_create.c:477
2022-10-07 18:03:06	         ret = <optimized out>
2022-10-07 18:03:06	         pd = <optimized out>
2022-10-07 18:03:06	         unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140178379814656, -8206069753202503994, 140728813899774, 140728813899775, 140728813899904, 140178379782464, 8135060142149963462, 8135056878073515718}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
2022-10-07 18:03:06	         not_first_call = 0
2022-10-07 18:03:06	 #9  0x00007f7dd4068133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
2022-10-07 18:03:06	 No locals.
2022-10-07 18:03:06	 
```

```
2022.10.07 18:03:40.946589 [ 400 ] {} <Fatal> BaseDaemon: ########################################
2022.10.07 18:03:40.946842 [ 400 ] {} <Fatal> BaseDaemon: (version 22.10.1.1, build id: 51BCDF1AA351BAA4845958F020BB33A8F1C2DF3D) (from thread 149) (query_id: b0d49df1-90d2-41aa-ba64-7bb6f85c6f01) (query: SELECT roundBankers(welchTTest(0., left).1, 257) AS t_stat, roundBankers(welchTTest(left, right).2, 255) AS p_value FROM welch_ttest__fuzz_18) Received signal Aborted (6)
2022.10.07 18:03:40.946893 [ 400 ] {} <Fatal> BaseDaemon:
2022.10.07 18:03:40.946950 [ 400 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f7dd3f8c00b 0x7f7dd3f6b859 0x2c5e7f42 0x2c6028da 0x2d589e4c 0x2d58a33a 0x2d6ff5a7 0x2d6fd14f 0x7f7dd4143609 0x7f7dd4068133
2022.10.07 18:03:40.946992 [ 400 ] {} <Fatal> BaseDaemon: 3. gsignal @ 0x7f7dd3f8c00b in ?
2022.10.07 18:03:40.947020 [ 400 ] {} <Fatal> BaseDaemon: 4. abort @ 0x7f7dd3f6b859 in ?
2022.10.07 18:03:41.027076 [ 400 ] {} <Fatal> BaseDaemon: 5. ./build_docker/../src/Server/TCPHandler.cpp:477: DB::TCPHandler::runImpl() @ 0x2c5e7f42 in /workspace/clickhouse
2022.10.07 18:03:41.082677 [ 400 ] {} <Fatal> BaseDaemon: 6. ./build_docker/../src/Server/TCPHandler.cpp:1881: DB::TCPHandler::run() @ 0x2c6028da in /workspace/clickhouse
2022.10.07 18:03:41.086874 [ 400 ] {} <Fatal> BaseDaemon: 7. ./build_docker/../contrib/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x2d589e4c in /workspace/clickhouse
2022.10.07 18:03:41.093822 [ 400 ] {} <Fatal> BaseDaemon: 8.1. inlined from ./build_docker/../contrib/libcxx/include/__memory/unique_ptr.h:54: std::__1::default_delete<Poco::Net::TCPServerConnection>::operator()(Poco::Net::TCPServerConnection*) const
2022.10.07 18:03:41.093855 [ 400 ] {} <Fatal> BaseDaemon: 8.2. inlined from ./build_docker/../contrib/libcxx/include/__memory/unique_ptr.h:315: std::__1::unique_ptr<Poco::Net::TCPServerConnection, std::__1::default_delete<Poco::Net::TCPServerConnection> >::reset(Poco::Net::TCPServerConnection*)
2022.10.07 18:03:41.093872 [ 400 ] {} <Fatal> BaseDaemon: 8.3. inlined from ./build_docker/../contrib/libcxx/include/__memory/unique_ptr.h:269: ~unique_ptr
2022.10.07 18:03:41.093886 [ 400 ] {} <Fatal> BaseDaemon: 8. ./build_docker/../contrib/poco/Net/src/TCPServerDispatcher.cpp:116: Poco::Net::TCPServerDispatcher::run() @ 0x2d58a33a in /workspace/clickhouse
2022.10.07 18:03:41.100985 [ 400 ] {} <Fatal> BaseDaemon: 9. ./build_docker/../contrib/poco/Foundation/src/ThreadPool.cpp:213: Poco::PooledThread::run() @ 0x2d6ff5a7 in /workspace/clickhouse
2022.10.07 18:03:41.107893 [ 400 ] {} <Fatal> BaseDaemon: 10.1. inlined from ./build_docker/../contrib/poco/Foundation/include/Poco/SharedPtr.h:156: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable> >::assign(Poco::Runnable*)
2022.10.07 18:03:41.107923 [ 400 ] {} <Fatal> BaseDaemon: 10.2. inlined from ./build_docker/../contrib/poco/Foundation/include/Poco/SharedPtr.h:208: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable> >::operator=(Poco::Runnable*)
2022.10.07 18:03:41.107939 [ 400 ] {} <Fatal> BaseDaemon: 10. ./build_docker/../contrib/poco/Foundation/src/Thread_POSIX.cpp:360: Poco::ThreadImpl::runnableEntry(void*) @ 0x2d6fd14f in /workspace/clickhouse
2022.10.07 18:03:41.107955 [ 400 ] {} <Fatal> BaseDaemon: 11. ? @ 0x7f7dd4143609 in ?
2022.10.07 18:03:41.107972 [ 400 ] {} <Fatal> BaseDaemon: 12. clone @ 0x7f7dd4068133 in ?
2022.10.07 18:03:41.420415 [ 400 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read. (calculated checksum: 84A9FC7AEF11B6E0AF3D392C65D2475D)
```

**Comment by vdimir** [comment]
Adhoc fix https://github.com/ClickHouse/ClickHouse/pull/42823
