### ISSUE TITLE
Deadlock in `ReplicatedMergeTreeAttachThread`

### ISSUE THREAD

**Issue by vdimir** [ClickHouse/ClickHouse#42262]
<details>
<summary>Details</summary>

```
Found hung queries in processlist:
[
    {
        "is_initial_query": 1,
        "user": "default",
        "query_id": "afb2bbf0-3b7d-45a0-9298-3293fbbb92df",
        "address": "::1",
        "port": 39924,
        "initial_user": "default",
        "initial_query_id": "afb2bbf0-3b7d-45a0-9298-3293fbbb92df",
        "initial_address": "::1",
        "initial_port": 39924,
        "interface": 1,
        "os_user": "",
        "client_hostname": "4945c6280500",
        "client_name": "ClickHouse",
        "client_revision": "54460",
        "client_version_major": "22",
        "client_version_minor": "10",
        "client_version_patch": "1",
        "http_method": 0,
        "http_user_agent": "",
        "http_referer": "",
        "forwarded_for": "",
        "quota_key": "",
        "distributed_depth": "0",
        "elapsed": 1161.891683821,
        "is_cancelled": 0,
        "is_all_data_sent": 0,
        "read_rows": "0",
        "read_bytes": "0",
        "total_rows_approx": "0",
        "written_rows": "0",
        "written_bytes": "0",
        "memory_usage": "37048",
        "peak_memory_usage": "2135462",
        "query": "ATTACH TABLE adaptive_granularity_alter2;",
        "thread_ids": [
            "2323",
            "2089",
            "2094",
            "56154"
        ],
        "ProfileEvents": {
            "Query": "1",
            "FileOpen": "1",
            "ReadBufferFromFileDescriptorRead": "3",
            "ReadBufferFromFileDescriptorReadBytes": "430",
            "OpenedFileCacheMisses": "1",
            "IOBufferAllocs": "4",
            "IOBufferAllocBytes": "3178556",
            "CreatedReadBufferOrdinary": "1",
            "DiskReadElapsedMicroseconds": "24",
            "ZooKeeperTransactions": "3",
            "ZooKeeperExists": "2",
            "ZooKeeperGet": "1",
            "ContextLock": "40",
            "RWLockAcquiredReadLocks": "1",
            "RealTimeMicroseconds": "4078",
            "UserTimeMicroseconds": "802",
            "SystemTimeMicroseconds": "239",
            "OSCPUVirtualTimeMicroseconds": "1040",
            "OSReadChars": "1410",
            "OSWriteChars": "203",
            "CreatedHTTPConnections": "1",
            "S3ReadMicroseconds": "3141",
            "S3ReadRequestsCount": "1",
            "DiskS3ReadMicroseconds": "3141",
            "DiskS3ReadRequestsCount": "1",
            "S3GetObject": "1",
            "DiskS3GetObject": "1",
            "ReadBufferFromS3Microseconds": "3916",
            "ReadBufferFromS3Bytes": "1",
            "RemoteFSUnprefetchedReads": "3",
            "RemoteFSBuffers": "1",
            "ThreadpoolReaderTaskMicroseconds": "3979",
            "ThreadpoolReaderReadBytes": "1",
            "AsynchronousReadWaitMicroseconds": "4675"
        },
        "Settings": {
            "max_block_size": "32176",
            "max_threads": "44",
            "max_read_buffer_size": "1002158",
            "connect_timeout_with_failover_ms": "2000",
            "connect_timeout_with_failover_secure_ms": "3000",
            "idle_connection_timeout": "36000",
            "s3_check_objects_after_upload": "1",
            "use_uncompressed_cache": "1",
            "stream_like_engine_allow_direct_select": "1",
            "replication_wait_for_inactive_replica_timeout": "30",
            "compile_expressions": "0",
            "compile_aggregate_expressions": "0",
            "group_by_two_level_threshold": "1152921504606846976",
            "distributed_aggregation_memory_efficient": "0",
            "group_by_use_nulls": "1",
            "min_chunk_bytes_for_parallel_parsing": "18461723",
            "output_format_parallel_formatting": "0",
            "merge_tree_coarse_index_granularity": "16",
            "log_queries": "1",
            "insert_quorum_timeout": "60000",
            "fsync_metadata": "0",
            "http_send_timeout": "60",
            "http_receive_timeout": "60",
            "opentelemetry_start_trace_probability": "0.1",
            "max_rows_in_join": "1000",
            "join_algorithm": "auto",
            "max_memory_usage_for_user": "66945609728",
            "max_untracked_memory": "1048576",
            "memory_profiler_step": "1048576",
            "log_comment": "00926_zookeeper_adaptive_index_granularity_replicated_merge_tree_long.sql",
            "send_logs_level": "warning",
            "optimize_read_in_order": "0",
            "aggregation_in_order_max_block_bytes": "31887601",
            "read_in_order_two_level_merge_threshold": "18",
            "database_atomic_wait_for_drop_and_detach_synchronously": "1",
            "cast_ipv4_ipv6_default_on_conversion_error": "1",
            "local_filesystem_read_method": "read",
            "remote_filesystem_read_prefetch": "0",
            "async_insert_busy_timeout_ms": "5000",
            "enable_filesystem_cache": "1",
            "enable_filesystem_cache_on_write_operations": "1",
            "load_marks_asynchronously": "1",
            "allow_deprecated_database_ordinary": "1",
            "optimize_distinct_in_order": "0",
            "optimize_sorting_by_input_stream_properties": "0"
        },
        "current_database": "test_15"
    },
    {
        "is_initial_query": 1,
        "user": "default",
        "query_id": "9834b2e1-c067-4212-9a0c-b28fc1fc624c",
        "address": "::1",
        "port": 39976,
        "initial_user": "default",
        "initial_query_id": "9834b2e1-c067-4212-9a0c-b28fc1fc624c",
        "initial_address": "::1",
        "initial_port": 39976,
        "interface": 1,
        "os_user": "",
        "client_hostname": "4945c6280500",
        "client_name": "ClickHouse",
        "client_revision": "54460",
        "client_version_major": "22",
        "client_version_minor": "10",
        "client_version_patch": "1",
        "http_method": 0,
        "http_user_agent": "",
        "http_referer": "",
        "forwarded_for": "",
        "quota_key": "",
        "distributed_depth": "0",
        "elapsed": 360.056273916,
        "is_cancelled": 0,
        "is_all_data_sent": 0,
        "read_rows": "0",
        "read_bytes": "0",
        "total_rows_approx": "0",
        "written_rows": "0",
        "written_bytes": "0",
        "memory_usage": "0",
        "peak_memory_usage": "0",
        "query": "DETACH DATABASE test_15",
        "thread_ids": [
            "144291"
        ],
        "ProfileEvents": {
            "Query": "1",
            "ZooKeeperTransactions": "1",
            "ZooKeeperRemove": "1",
            "ReplicaPartialShutdown": "1",
            "ContextLock": "5",
            "RWLockAcquiredReadLocks": "9"
        },
        "Settings": {
            "connect_timeout_with_failover_ms": "2000",
            "connect_timeout_with_failover_secure_ms": "3000",
            "idle_connection_timeout": "36000",
            "s3_check_objects_after_upload": "1",
            "stream_like_engine_allow_direct_select": "1",
            "replication_wait_for_inactive_replica_timeout": "30",
            "log_queries": "1",
            "insert_quorum_timeout": "60000",
            "fsync_metadata": "0",
            "http_send_timeout": "60",
            "http_receive_timeout": "60",
            "opentelemetry_start_trace_probability": "0.1",
            "max_memory_usage_for_user": "0",
            "max_untracked_memory": "1073741824",
            "memory_profiler_step": "1073741824",
            "database_atomic_wait_for_drop_and_detach_synchronously": "1",
            "async_insert_busy_timeout_ms": "5000",
            "enable_filesystem_cache": "1",
            "enable_filesystem_cache_on_write_operations": "1",
            "load_marks_asynchronously": "1",
            "allow_deprecated_database_ordinary": "1"
        },
        "current_database": "default"
    }
]
None

```

</details>

Full report https://s3.amazonaws.com/clickhouse-test-reports/42103/81b948a46f72ae047accccf45f76f1cba33a0a28/stress_test__ubsan_.html

**Comment by tavplubix** [comment]
The root cause:
```
Thread 123 (Thread 0x7f5bb37fe700 (LWP 1607)):
#0  0x00007f5e030b2170 in __lll_lock_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f5e030aa0a3 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x000000001f90e67e in pthread_mutex_lock (arg=0x7f507defa958) at ../src/Common/ThreadFuzzer.cpp:317
#3  0x000000002faf8ae9 in std::__1::__libcpp_mutex_lock (__m=0x7f507defa958) at ../contrib/libcxx/include/__threading_support:303
#4  std::__1::mutex::lock (this=0x7f507defa958) at ../contrib/libcxx/src/mutex.cpp:33
#5  0x0000000029c3a842 in std::__1::lock_guard<std::__1::mutex>::lock_guard (this=0x7f5bb37f5e10, __m=...) at ../contrib/libcxx/include/__mutex_base:91
#6  DB::BackgroundSchedulePoolTaskInfo::deactivate (this=0x7f507defa908) at ../src/Core/BackgroundSchedulePool.cpp:45
#7  0x000000002c2fd4fc in DB::ReplicatedMergeTreeAttachThread::shutdown (this=0x7f5b8ccca168) at ../src/Storages/MergeTree/ReplicatedMergeTreeAttachThread.cpp:33
#8  0x000000002bc5505c in DB::StorageReplicatedMergeTree::shutdown (this=this@entry=0x7f5b8ccc90a0) at ../src/Storages/StorageReplicatedMergeTree.cpp:4242
#9  0x000000002bc54ae5 in DB::StorageReplicatedMergeTree::startupImpl (this=0x7f5b8ccc90a0) at ../src/Storages/StorageReplicatedMergeTree.cpp:4207
#10 0x000000002c3015b6 in DB::ReplicatedMergeTreeAttachThread::finalizeInitialization (this=this@entry=0x7f5b8ccca168) at ../src/Storages/MergeTree/ReplicatedMergeTreeAttachThread.cpp:190
#11 0x000000002c2fdab8 in DB::ReplicatedMergeTreeAttachThread::run (this=0x7f5b8ccca168) at ../src/Storages/MergeTree/ReplicatedMergeTreeAttachThread.cpp:51
#12 0x0000000029c3ac61 in std::__1::__function::__policy_func<void ()>::operator()() const (this=0x7f507defa938) at ../contrib/libcxx/include/__functional/function.h:843
#13 std::__1::function<void ()>::operator()() const (this=0x7f507defa938) at ../contrib/libcxx/include/__functional/function.h:1184
#14 DB::BackgroundSchedulePoolTaskInfo::execute (this=0x7f507defa908) at ../src/Core/BackgroundSchedulePool.cpp:98
#15 0x0000000029c3cf57 in DB::BackgroundSchedulePool::threadFunction (this=this@entry=0x397dda90) at ../src/Core/BackgroundSchedulePool.cpp:290
#16 0x0000000029c3d8ad in DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1::operator()() const (this=<optimized out>) at ../src/Core/BackgroundSchedulePool.cpp:152
#17 std::__1::__invoke_constexpr<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&) (__f=...) at ../contrib/libcxx/include/type_traits:3648
#18 std::__1::__apply_tuple_impl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&, std::__1::tuple<>&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&, std::__1::tuple<>&, std::__1::__tuple_indices<>) (__f=..., __t=...) at ../contrib/libcxx/include/tuple:1595
#19 std::__1::apply<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&, std::__1::tuple<>&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&, std::__1::tuple<>&) (__f=..., __t=...) at ../contrib/libcxx/include/tuple:1604
#20 ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&)::{lambda()#1}::operator()() (this=<optimized out>) at ../src/Common/ThreadPool.h:193
#21 std::__1::__invoke<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&)::{lambda()#1}&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&) (__f=...) at ../contrib/libcxx/include/type_traits:3640
#22 std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&)::{lambda()#1}&>(ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&)::{lambda()#1}&) (__args=...) at ../contrib/libcxx/include/__functional/invoke.h:61
#23 std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&)::{lambda()#1}, void ()>::operator()() (this=<optimized out>) at ../contrib/libcxx/include/__functional/function.h:230
#24 std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&)::{lambda()#1}, void ()> >(std::__1::__function::__policy_storage const*) (__buf=__buf@entry=0x7f5bb37f6800) at ../contrib/libcxx/include/__functional/function.h:711
#25 0x000000001f9b36b3 in std::__1::__function::__policy_func<void ()>::operator()() const (this=0x7f5bb37f6800) at ../contrib/libcxx/include/__functional/function.h:843
#26 std::__1::function<void ()>::operator()() const (this=0x7f5bb37f6800) at ../contrib/libcxx/include/__functional/function.h:1184
#27 ThreadPoolImpl<std::__1::thread>::worker (this=0x39cad680, thread_it=...) at ../src/Common/ThreadPool.cpp:294
#28 0x000000001f9b7484 in ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::{lambda()#2}::operator()() const (this=0x39e9c448) at ../src/Common/ThreadPool.cpp:144
#29 std::__1::__invoke<ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::{lambda()#2}>(ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::{lambda()#2}&&, (ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::{lambda()#2}&&)...) (__f=...) at ../contrib/libcxx/include/type_traits:3640
#30 std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::{lambda()#2}>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::{lambda()#2}>&, std::__1::__tuple_indices<>) (__t=...) at ../contrib/libcxx/include/thread:282
#31 std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::{lambda()#2}> >(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::{lambda()#2}>) (__vp=0x39e9c440) at ../contrib/libcxx/include/thread:293
#32 0x00007f5e030a7609 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#33 0x00007f5e02fcc133 in clone () from /lib/x86_64-linux-gnu/libc.so.6
```

**Comment by tavplubix** [comment]
Seems like `StorageReplicatedMergeTree::startupImpl` failed for some reason and called `shutdown` which tried to deactivate the AttachThread task. But task cannot deactivate itself.

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/42406/fffecbb9adc8d3de095352a0e2a4822343ede7e5/stress_test__asan_.html

**Comment by tavplubix** [comment]
Fixed in https://github.com/ClickHouse/ClickHouse/pull/44719
