### ISSUE TITLE
stack-use-after-scope in `ColumnArray::replicateString`

### ISSUE THREAD

**Issue by nikitamikhaylov** [ClickHouse/ClickHouse#42437]
**Describe the bug**
https://s3.amazonaws.com/clickhouse-test-reports/42143/82850eb56046c857be8df56a8c425304b2670425/stateful_tests__asan_/stderr.log

**Error message and/or stacktrace**
```
=================================================================
==646==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7f151225d980 at pc 0x00000dfc05aa bp 0x7f16fbf4f4f0 sp 0x7f16fbf4ecc0
WRITE of size 33554432 at 0x7f151225d980 thread T994 (QueryPipelineEx)
    #0 0xdfc05a9 in __asan_memcpy (/usr/bin/clickhouse+0xdfc05a9) (BuildId: e2f3e57c9d5750229244e6ee26377f571bcec5b8)
    #1 0x1ea29560 in Allocator<false, false>::realloc(void*, unsigned long, unsigned long, unsigned long) build_docker/../src/Common/Allocator.h:172:13
    #2 0xe05296b in void DB::PODArrayBase<8ul, 4096ul, Allocator<false, false>, 15ul, 16ul>::reserveForNextSize<>() (/usr/bin/clickhouse+0xe05296b) (BuildId: e2f3e57c9d5750229244e6ee26377f571bcec5b8)
    #3 0x30868146 in void DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul>::push_back<unsigned long&>(unsigned long&) build_docker/../src/Common/PODArray.h:437:19
    #4 0x30868146 in DB::ColumnArray::replicateString(DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul> const&) const build_docker/../src/Columns/ColumnArray.cpp:1058:36
    #5 0x30866d67 in DB::ColumnArray::replicate(DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul> const&) const build_docker/../src/Columns/ColumnArray.cpp:943:65
    #6 0x30af460e in DB::ColumnFunction::replicate(DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul> const&) const build_docker/../src/Columns/ColumnFunction.cpp:49:40
    #7 0x1cea3efb in DB::FunctionArrayMapped<DB::ArrayAllImpl, DB::NameArrayAll>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/usr/bin/clickhouse+0x1cea3efb) (BuildId: e2f3e57c9d5750229244e6ee26377f571bcec5b8)
    #8 0xe014f8b in DB::FunctionToExecutableFunctionAdaptor::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/usr/bin/clickhouse+0xe014f8b) (BuildId: e2f3e57c9d5750229244e6ee26377f571bcec5b8)
    #9 0x2ca10f9b in DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_docker/../src/Functions/IFunction.cpp:248:15
    #10 0x2ca12bb6 in DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_docker/../src/Functions/IFunction.cpp:302:22
    #11 0x2ca16fca in DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_docker/../src/Functions/IFunction.cpp:372:16
    #12 0x2eab02ac in DB::executeAction(DB::ExpressionActions::Action const&, DB::(anonymous namespace)::ExecutionContext&, bool) build_docker/../src/Interpreters/ExpressionActions.cpp:607:60
    #13 0x2eab02ac in DB::ExpressionActions::execute(DB::Block&, unsigned long&, bool) const build_docker/../src/Interpreters/ExpressionActions.cpp:724:13
    #14 0x3306c29f in DB::FilterTransform::doTransform(DB::Chunk&) build_docker/../src/Processors/Transforms/FilterTransform.cpp:122:25
    #15 0x3306be6d in DB::FilterTransform::transform(DB::Chunk&) build_docker/../src/Processors/Transforms/FilterTransform.cpp:107:5
    #16 0x25e430dd in DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) build_docker/../src/Processors/ISimpleTransform.h:32:9
    #17 0x32a6440c in DB::ISimpleTransform::work() build_docker/../src/Processors/ISimpleTransform.cpp:89:9
    #18 0x32ab966d in DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*) build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:47:26
    #19 0x32ab966d in DB::ExecutionThreadContext::executeTask() build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:92:9
    #20 0x32a98a04 in DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:228:26
    #21 0x32a9c44b in DB::PipelineExecutor::executeSingleThread(unsigned long) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:194:5
    #22 0x32a9c44b in DB::PipelineExecutor::spawnThreads()::$_0::operator()() const build_docker/../src/Processors/Executors/PipelineExecutor.cpp:315:17
    #23 0x32a9c44b in decltype(static_cast<DB::PipelineExecutor::spawnThreads()::$_0&>(fp)()) std::__1::__invoke_constexpr<DB::PipelineExecutor::spawnThreads()::$_0&>(DB::PipelineExecutor::spawnThreads()::$_0&) build_docker/../contrib/libcxx/include/type_traits:3648:23
    #24 0x32a9c44b in decltype(auto) std::__1::__apply_tuple_impl<DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&>(DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/tuple:1595:1
    #25 0x32a9c44b in decltype(auto) std::__1::apply<DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&>(DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&) build_docker/../contrib/libcxx/include/tuple:1604:1
    #26 0x32a9c44b in ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()::operator()() build_docker/../src/Common/ThreadPool.h:193:13
    #27 0x32a9c44b in decltype(static_cast<DB::PipelineExecutor::spawnThreads()::$_0>(fp)()) std::__1::__invoke<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&>(DB::PipelineExecutor::spawnThreads()::$_0&&) build_docker/../contrib/libcxx/include/type_traits:3640:23
    #28 0x32a9c44b in void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&) build_docker/../contrib/libcxx/include/__functional/invoke.h:61:9
    #29 0x32a9c44b in std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'(), void ()>::operator()() build_docker/../contrib/libcxx/include/__functional/function.h:230:12
    #30 0x32a9c44b in void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) build_docker/../contrib/libcxx/include/__functional/function.h:711:16
    #31 0x1ecc307f in std::__1::__function::__policy_func<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:843:16
    #32 0x1ecc307f in std::__1::function<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:1184:12
    #33 0x1ecc307f in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) build_docker/../src/Common/ThreadPool.cpp:294:17
    #34 0x1ecccb6c in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const build_docker/../src/Common/ThreadPool.cpp:144:73
    #35 0x1ecccb6c in decltype(static_cast<void>(fp)()) std::__1::__invoke<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&) build_docker/../contrib/libcxx/include/type_traits:3640:23
    #36 0x1ecccb6c in void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/thread:282:5
    #37 0x1ecccb6c in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) build_docker/../contrib/libcxx/include/thread:293:5
    #38 0x7f1d6d89f608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8608) (BuildId: 7b4536f41cdaa5888408e82d0836e33dcf436466)
    #39 0x7f1d6d7c4132 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x11f132) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)

Address 0x7f151225d980 is a wild pointer inside of access range of size 0x000002000000.
SUMMARY: AddressSanitizer: stack-use-after-scope (/usr/bin/clickhouse+0xdfc05a9) (BuildId: e2f3e57c9d5750229244e6ee26377f571bcec5b8) in __asan_memcpy
Shadow bytes around the buggy address:
  0x0fe322443ae0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe322443af0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe322443b00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe322443b10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe322443b20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0fe322443b30:[f8]00 00 00 f8 00 00 00 00 00 00 00 00 00 00 00
  0x0fe322443b40: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe322443b50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe322443b60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe322443b70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe322443b80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
Thread T994 (QueryPipelineEx) created by T982 (ThreadPool) here:
    #0 0xdfaa09c in pthread_create (/usr/bin/clickhouse+0xdfaa09c) (BuildId: e2f3e57c9d5750229244e6ee26377f571bcec5b8)
    #1 0x1eccb9f4 in std::__1::__libcpp_thread_create(unsigned long*, void* (*)(void*), void*) build_docker/../contrib/libcxx/include/__threading_support:375:10
    #2 0x1eccb9f4 in std::__1::thread::thread<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'(), void>(void&&) build_docker/../contrib/libcxx/include/thread:309:16
    #3 0x1ecbfc4b in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool) build_docker/../src/Common/ThreadPool.cpp:144:35
    #4 0x1ecc1827 in ThreadPoolImpl<std::__1::thread>::scheduleOrThrow(std::__1::function<void ()>, int, unsigned long, bool) build_docker/../src/Common/ThreadPool.cpp:180:5
    #5 0x32a9bd4e in ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&) build_docker/../src/Common/ThreadPool.h:176:38
    #6 0x32a9bd4e in ThreadFromGlobalPoolImpl<true>* std::__1::construct_at<ThreadFromGlobalPoolImpl<true>, DB::PipelineExecutor::spawnThreads()::$_0, ThreadFromGlobalPoolImpl<true>*>(ThreadFromGlobalPoolImpl<true>*, DB::PipelineExecutor::spawnThreads()::$_0&&) build_docker/../contrib/libcxx/include/__memory/construct_at.h:38:50
    #7 0x32a9bd4e in void std::__1::allocator_traits<std::__1::allocator<ThreadFromGlobalPoolImpl<true>>>::construct<ThreadFromGlobalPoolImpl<true>, DB::PipelineExecutor::spawnThreads()::$_0, void, void>(std::__1::allocator<ThreadFromGlobalPoolImpl<true>>&, ThreadFromGlobalPoolImpl<true>*, DB::PipelineExecutor::spawnThreads()::$_0&&) build_docker/../contrib/libcxx/include/__memory/allocator_traits.h:298:9
    #8 0x32a9a911 in void std::__1::vector<ThreadFromGlobalPoolImpl<true>, std::__1::allocator<ThreadFromGlobalPoolImpl<true>>>::__construct_one_at_end<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&) build_docker/../contrib/libcxx/include/vector:778:5
    #9 0x32a9a911 in ThreadFromGlobalPoolImpl<true>& std::__1::vector<ThreadFromGlobalPoolImpl<true>, std::__1::allocator<ThreadFromGlobalPoolImpl<true>>>::emplace_back<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&) build_docker/../contrib/libcxx/include/vector:1577:9
    #10 0x32a9a911 in DB::PipelineExecutor::spawnThreads() build_docker/../src/Processors/Executors/PipelineExecutor.cpp:304:17
    #11 0x32a97261 in DB::PipelineExecutor::executeImpl(unsigned long) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:360:9
    #12 0x32a96ed4 in DB::PipelineExecutor::execute(unsigned long) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:89:9
    #13 0x32ac33fb in DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long) build_docker/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:79:24
    #14 0x32ac33fb in DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0::operator()() const build_docker/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:107:13
    #15 0x32ac33fb in decltype(static_cast<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(fp)()) std::__1::__invoke_constexpr<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&) build_docker/../contrib/libcxx/include/type_traits:3648:23
    #16 0x32ac33fb in decltype(auto) std::__1::__apply_tuple_impl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/tuple:1595:1
    #17 0x32ac33fb in decltype(auto) std::__1::apply<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&) build_docker/../contrib/libcxx/include/tuple:1604:1
    #18 0x32ac33fb in ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()::operator()() build_docker/../src/Common/ThreadPool.h:193:13
    #19 0x32ac33fb in decltype(static_cast<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(fp)()) std::__1::__invoke<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&) build_docker/../contrib/libcxx/include/type_traits:3640:23
    #20 0x32ac33fb in void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&) build_docker/../contrib/libcxx/include/__functional/invoke.h:61:9
    #21 0x32ac33fb in std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>::operator()() build_docker/../contrib/libcxx/include/__functional/function.h:230:12
    #22 0x32ac33fb in void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) build_docker/../contrib/libcxx/include/__functional/function.h:711:16
    #23 0x1ecc307f in std::__1::__function::__policy_func<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:843:16
    #24 0x1ecc307f in std::__1::function<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:1184:12
    #25 0x1ecc307f in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) build_docker/../src/Common/ThreadPool.cpp:294:17
    #26 0x1ecccb6c in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const build_docker/../src/Common/ThreadPool.cpp:144:73
    #27 0x1ecccb6c in decltype(static_cast<void>(fp)()) std::__1::__invoke<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&) build_docker/../contrib/libcxx/include/type_traits:3640:23
    #28 0x1ecccb6c in void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/thread:282:5
    #29 0x1ecccb6c in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) build_docker/../contrib/libcxx/include/thread:293:5
    #30 0x7f1d6d89f608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8608) (BuildId: 7b4536f41cdaa5888408e82d0836e33dcf436466)

Thread T982 (ThreadPool) created by T972 (TCPHandler) here:
    #0 0xdfaa09c in pthread_create (/usr/bin/clickhouse+0xdfaa09c) (BuildId: e2f3e57c9d5750229244e6ee26377f571bcec5b8)
    #1 0x1eccb9f4 in std::__1::__libcpp_thread_create(unsigned long*, void* (*)(void*), void*) build_docker/../contrib/libcxx/include/__threading_support:375:10
    #2 0x1eccb9f4 in std::__1::thread::thread<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'(), void>(void&&) build_docker/../contrib/libcxx/include/thread:309:16
    #3 0x1ecbfc4b in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool) build_docker/../src/Common/ThreadPool.cpp:144:35
    #4 0x1ecc1827 in ThreadPoolImpl<std::__1::thread>::scheduleOrThrow(std::__1::function<void ()>, int, unsigned long, bool) build_docker/../src/Common/ThreadPool.cpp:180:5
    #5 0x32abfe5d in ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&) build_docker/../src/Common/ThreadPool.h:176:38
    #6 0x32abfe5d in DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long) build_docker/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:110:24
    #7 0x32ac0e77 in DB::PullingAsyncPipelineExecutor::pull(DB::Block&, unsigned long) build_docker/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:148:10
    #8 0x329ae550 in DB::TCPHandler::processOrdinaryQueryWithProcessors() build_docker/../src/Server/TCPHandler.cpp:739:25
    #9 0x3299a75b in DB::TCPHandler::runImpl() build_docker/../src/Server/TCPHandler.cpp:376:17
    #10 0x329cba22 in DB::TCPHandler::run() build_docker/../src/Server/TCPHandler.cpp:1884:9
    #11 0x3a2647ae in Poco::Net::TCPServerConnection::start() build_docker/../contrib/poco/Net/src/TCPServerConnection.cpp:43:3
    #12 0x3a265532 in Poco::Net::TCPServerDispatcher::run() build_docker/../contrib/poco/Net/src/TCPServerDispatcher.cpp:115:20
    #13 0x3a73a63b in Poco::PooledThread::run() build_docker/../contrib/poco/Foundation/src/ThreadPool.cpp:199:14
    #14 0x3a733f27 in Poco::ThreadImpl::runnableEntry(void*) build_docker/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345:27
    #15 0x7f1d6d89f608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8608) (BuildId: 7b4536f41cdaa5888408e82d0836e33dcf436466)

Thread T972 (TCPHandler) created by T260 here:
    #0 0xdfaa09c in pthread_create (/usr/bin/clickhouse+0xdfaa09c) (BuildId: e2f3e57c9d5750229244e6ee26377f571bcec5b8)
    #1 0x3a73317e in Poco::ThreadImpl::startImpl(Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable>>) build_docker/../contrib/poco/Foundation/src/Thread_POSIX.cpp:202:6
    #2 0x3a73633d in Poco::Thread::start(Poco::Runnable&) build_docker/../contrib/poco/Foundation/src/Thread.cpp:128:2
    #3 0x3a73e747 in Poco::PooledThread::start() build_docker/../contrib/poco/Foundation/src/ThreadPool.cpp:85:10
    #4 0x3a73e747 in Poco::ThreadPool::getThread() build_docker/../contrib/poco/Foundation/src/ThreadPool.cpp:461:14
    #5 0x3a73ee36 in Poco::ThreadPool::startWithPriority(Poco::Thread::Priority, Poco::Runnable&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) build_docker/../contrib/poco/Foundation/src/ThreadPool.cpp:365:2
    #6 0x3a26616b in Poco::Net::TCPServerDispatcher::enqueue(Poco::Net::StreamSocket const&) build_docker/../contrib/poco/Net/src/TCPServerDispatcher.cpp:152:17
    #7 0x3a264077 in Poco::Net::TCPServer::run() build_docker/../contrib/poco/Net/src/TCPServer.cpp:148:21
    #8 0x3a733f27 in Poco::ThreadImpl::runnableEntry(void*) build_docker/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345:27
    #9 0x7f1d6d89f608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8608) (BuildId: 7b4536f41cdaa5888408e82d0836e33dcf436466)

Thread T260 created by T0 here:
    #0 0xdfaa09c in pthread_create (/usr/bin/clickhouse+0xdfaa09c) (BuildId: e2f3e57c9d5750229244e6ee26377f571bcec5b8)
    #1 0x3a73317e in Poco::ThreadImpl::startImpl(Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable>>) build_docker/../contrib/poco/Foundation/src/Thread_POSIX.cpp:202:6
    #2 0x3a73633d in Poco::Thread::start(Poco::Runnable&) build_docker/../contrib/poco/Foundation/src/Thread.cpp:128:2
    #3 0x1ec6a8d4 in DB::ProtocolServerAdapter::start() build_docker/../src/Server/ProtocolServerAdapter.h:29:26
    #4 0x1ec6a8d4 in DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) build_docker/../programs/server/Server.cpp:1776:24
    #5 0x3a29d246 in Poco::Util::Application::run() build_docker/../contrib/poco/Util/src/Application.cpp:334:8
    #6 0x1ec41c3f in DB::Server::run() build_docker/../programs/server/Server.cpp:468:25
    #7 0x3a2e09f8 in Poco::Util::ServerApplication::run(int, char**) build_docker/../contrib/poco/Util/src/ServerApplication.cpp:611:9
    #8 0x1ec3a9e1 in mainEntryClickHouseServer(int, char**) build_docker/../programs/server/Server.cpp:183:20
    #9 0xdffefda in main build_docker/../programs/main.cpp:482:12
    #10 0x7f1d6d6c9082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)

```

**Comment by alexey-milovidov** [comment]
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/41500.
