### ISSUE TITLE
stack-use-after-scope in CompressedReadBufferBase

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#42621]
https://s3.amazonaws.com/clickhouse-test-reports/0/aee7bb0d91fe1a1f60c860b0916971e38aaf55db/stateless_tests__asan__[2/2].html

```
==648==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7f95a6337980 at pc 0x00000e031fb7 bp 0x7f92e66a1290 sp 0x7f92e66a0a60
READ of size 26671 at 0x7f95a6337980 thread T833 (QueryPipelineEx)
    #0 0xe031fb6 in __asan_memcpy (/usr/bin/clickhouse+0xe031fb6) (BuildId: 28e9f5c6707ecb42d8757872338308f394c0735c)
    #1 0x1ecfb508 in DB::ReadBuffer::read(char*, unsigned long) build_docker/../src/IO/ReadBuffer.h:178:13
    #2 0x1ecfb508 in DB::ReadBuffer::readStrict(char*, unsigned long) build_docker/../src/IO/ReadBuffer.h:189:27
    #3 0x2d4f8582 in DB::CompressedReadBufferBase::readCompressedData(unsigned long&, unsigned long&, bool) build_docker/../src/Compression/CompressedReadBufferBase.cpp:192:24
    #4 0x2d4fec21 in DB::CompressedReadBufferFromFile::nextImpl() build_docker/../src/Compression/CompressedReadBufferFromFile.cpp:22:23
    #5 0x2db00e0a in DB::ReadBuffer::next() build_docker/../src/IO/ReadBuffer.h:64:20
    #6 0x2db00e0a in DB::ReadBuffer::eof() build_docker/../src/IO/ReadBuffer.h:98:38
    #7 0x2db00e0a in void DB::deserializeBinarySSE2<2>(DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>&, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul>&, DB::ReadBuffer&, unsigned long) build_docker/../src/DataTypes/Serializations/SerializationString.cpp:123:18
    #8 0x2dafd848 in DB::SerializationString::deserializeBinaryBulk(DB::IColumn&, DB::ReadBuffer&, unsigned long, double) const build_docker/../src/DataTypes/Serializations/SerializationString.cpp:209:9
    #9 0x2d9c4a3d in DB::ISerialization::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>>*) const build_docker/../src/DataTypes/Serializations/ISerialization.cpp:132:9
    #10 0x32462fbd in DB::MergeTreeReaderWide::readData(DB::NameAndTypePair const&, std::__1::shared_ptr<DB::ISerialization const> const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, bool, unsigned long, unsigned long, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>>&, bool) build_docker/../src/Storages/MergeTree/MergeTreeReaderWide.cpp:306:20
    #11 0x32460200 in DB::MergeTreeReaderWide::readRows(unsigned long, unsigned long, bool, unsigned long, std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&) build_docker/../src/Storages/MergeTree/MergeTreeReaderWide.cpp:111:17
    #12 0x336ef9ea in DB::MergeTreeRangeReader::DelayedStream::readRows(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&, unsigned long) build_docker/../src/Storages/MergeTree/MergeTreeRangeReader.cpp:101:47
    #13 0x336ef9ea in DB::MergeTreeRangeReader::DelayedStream::finalize(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&) build_docker/../src/Storages/MergeTree/MergeTreeRangeReader.cpp:175:12
    #14 0x336fce71 in DB::MergeTreeRangeReader::Stream::finalize(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&) build_docker/../src/Storages/MergeTree/MergeTreeRangeReader.cpp:286:31
    #15 0x336fce71 in DB::MergeTreeRangeReader::continueReadingChain(DB::MergeTreeRangeReader::ReadResult const&, unsigned long&) build_docker/../src/Storages/MergeTree/MergeTreeRangeReader.cpp:1031:24
    #16 0x336f9dad in DB::MergeTreeRangeReader::read(unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange>>&) build_docker/../src/Storages/MergeTree/MergeTreeRangeReader.cpp:775:27
    #17 0x336d9fd3 in DB::MergeTreeBaseSelectProcessor::readFromPartImpl() build_docker/../src/Storages/MergeTree/MergeTreeBaseSelectProcessor.cpp:385:43
    #18 0x336db136 in DB::MergeTreeBaseSelectProcessor::readFromPart() build_docker/../src/Storages/MergeTree/MergeTreeBaseSelectProcessor.cpp:425:12
    #19 0x336d0e37 in DB::MergeTreeBaseSelectProcessor::generate() build_docker/../src/Storages/MergeTree/MergeTreeBaseSelectProcessor.cpp:217:20
    #20 0x32c26f35 in DB::ISource::tryGenerate() build_docker/../src/Processors/ISource.cpp:124:18
    #21 0x32c260be in DB::ISource::work() build_docker/../src/Processors/ISource.cpp:94:26
    #22 0x32c73bcd in DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*) build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:47:26
    #23 0x32c73bcd in DB::ExecutionThreadContext::executeTask() build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:92:9
    #24 0x32c52b44 in DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:229:26
    #25 0x32c5652b in DB::PipelineExecutor::executeSingleThread(unsigned long) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:195:5
    #26 0x32c5652b in DB::PipelineExecutor::spawnThreads()::$_0::operator()() const build_docker/../src/Processors/Executors/PipelineExecutor.cpp:316:17
    #27 0x32c5652b in decltype(static_cast<DB::PipelineExecutor::spawnThreads()::$_0&>(fp)()) std::__1::__invoke_constexpr<DB::PipelineExecutor::spawnThreads()::$_0&>(DB::PipelineExecutor::spawnThreads()::$_0&) build_docker/../contrib/libcxx/include/type_traits:3648:23
    #28 0x32c5652b in decltype(auto) std::__1::__apply_tuple_impl<DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&>(DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/tuple:1595:1
    #29 0x32c5652b in decltype(auto) std::__1::apply<DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&>(DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&) build_docker/../contrib/libcxx/include/tuple:1604:1
    #30 0x32c5652b in ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()::operator()() build_docker/../src/Common/ThreadPool.h:196:13
    #31 0x32c5652b in decltype(static_cast<DB::PipelineExecutor::spawnThreads()::$_0>(fp)()) std::__1::__invoke<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&>(DB::PipelineExecutor::spawnThreads()::$_0&&) build_docker/../contrib/libcxx/include/type_traits:3640:23
    #32 0x32c5652b in void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&) build_docker/../contrib/libcxx/include/__functional/invoke.h:61:9
    #33 0x32c5652b in std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'(), void ()>::operator()() build_docker/../contrib/libcxx/include/__functional/function.h:230:12
    #34 0x32c5652b in void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) build_docker/../contrib/libcxx/include/__functional/function.h:711:16
    #35 0x1edf367f in std::__1::__function::__policy_func<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:843:16
    #36 0x1edf367f in std::__1::function<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:1184:12
    #37 0x1edf367f in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) build_docker/../src/Common/ThreadPool.cpp:294:17
    #38 0x1edfd1cc in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const build_docker/../src/Common/ThreadPool.cpp:144:73
    #39 0x1edfd1cc in decltype(static_cast<void>(fp)()) std::__1::__invoke<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&) build_docker/../contrib/libcxx/include/type_traits:3640:23
    #40 0x1edfd1cc in void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/thread:282:5
    #41 0x1edfd1cc in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) build_docker/../contrib/libcxx/include/thread:293:5
    #42 0x7f97d3ab5608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8608) (BuildId: 7b4536f41cdaa5888408e82d0836e33dcf436466)
    #43 0x7f97d39da132 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x11f132) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)
```

**Comment by nikitamikhaylov** [comment]
Duplicate #41500
