### ISSUE TITLE
ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: 9.138.150.30, port: 8123; std::exception. Code: 1001, type: std::runtime_error, e.what() = failed alloc while reading (version 21.8.12.1)

### ISSUE THREAD

**Issue by learn2Pro** [ClickHouse/ClickHouse#43190]
I want to accumulate userid by bitmap in clickhouse
- step1:
create table like this
```sql
CREATE TABLE IF NOT EXISTS t_ck_test_xx_bits_final_local ON CLUSTER default_cluster (
  imp_date String,
  label String,
  value String,
  dummy String TTL now()+INTERVAL 3 HOUR,
  bits AggregateFunction(groupBitmap, UInt64) MATERIALIZED base64Decode(dummy)
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{table}/{shard}', '{replica}')  
PARTITION BY imp_date 
ORDER BY (label,value) 
SETTINGS index_granularity = 2;
```
- step2:
read hive by spark and insert to clickhouse like below
```sql
insert into t_ck_test_qimei36_labels_bits_final_local (imp_date,label,value,dummy) values (?,?,?,?)
```
the dummy column may be very large like (1.5GB)
- whats wrong i think:
then i met this problem **type: std::runtime_error, e.what() = failed alloc while reading (version 21.8.12.1)**
it looks like memory allocation problem, how to configure my clickhouse to solve this problem

**Comment by alexey-milovidov** [comment]
You are showing a message from some old version of the JDBC driver.
ClickHouse version 21.8 is unsupported, you must upgrade to 22.10 immediately by running
```
curl https://clickhouse.com/ | sh
```

**Comment by learn2Pro** [comment]
same problem met when i update jdbc->**0.3.2-patch11**,server->**22.3**
```java
java.sql.BatchUpdateException: std::exception. Code: 1001, type: std::runtime_error, e.what() = failed alloc while reading (version 22.3.10.22)
, server ClickHouseNode [uri=http://9.138.150.30:8123/tx, options={socket_timeout=12000000,client_name=spark-client}]@-882666552
	at com.clickhouse.jdbc.SqlExceptionUtils.batchUpdateError(SqlExceptionUtils.java:109)
	at com.clickhouse.jdbc.internal.InputBasedPreparedStatement.executeAny(InputBasedPreparedStatement.java:142)
	at com.clickhouse.jdbc.internal.AbstractPreparedStatement.executeLargeBatch(AbstractPreparedStatement.java:85)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeBatch(ClickHouseStatementImpl.java:568)
```

**Comment by learn2Pro** [comment]
i found solution here  https://github.com/ClickHouse/clickhouse-jdbc/pull/596
