### ISSUE TITLE
UndefinedBehaviorSanitizer: stack-overflow when formatting query

### ISSUE THREAD

**Issue by CheSema** [ClickHouse/ClickHouse#43251]
Original report 
https://oss-fuzz.com/testcase-detail/6348312009900032

**Describe the bug**
Clickhouse uses too much stack memory while formatting a parsed query.
Ch has a settings max_parser_depth which should have protect agains too deep queries.
Fuzzer has founded a query which could be parsed but could't be formatted du to stack-overflow.

The stack depth is more than 22000 calls.
#22775 0x0000000000ec345e in DB::ASTWithAlias::formatImpl (this=0x3062878, settings=..., state=..., frame=...) at ./src/Parsers/ASTWithAlias.cpp:32
#22776 0x0000000000f28248 in DB::ASTFunction::formatImplWithoutAlias (this=0x3062b48, settings=..., state=..., frame=...) at ./src/Parsers/ASTFunction.cpp:382

If increase the stack size (8176 -> 10000), test case passes.

**Comment by CheSema** [comment]
Clickhouse has 2 parameters, which can be confused
- max_ast_depth -- produce error message as "AST is too deep." error code: TOO_DEEP_AST
- max_parser_depth -- "Maximum parse depth exceeded" error code: TOO_DEEP_RECURSION

In that case the query parsed successfully, no error TOO_DEEP_RECURSION. As a result some too hight AST has been built. The height of AST should be checked after it is built.  
The select_parser_fuzzer.cpp hasn't checked the result AST depth. The original clickhouse server does this check. So  select_parser_fuzzer.cpp also has to do it.
