### ISSUE TITLE
Ast Fuzzer MemorySanitizer use-of-uninitialized-value Poco::Net::SocketImpl::sendBytes

### ISSUE THREAD

**Issue by CheSema** [ClickHouse/ClickHouse#43322]
**Describe the bug**
A link to the report https://s3.amazonaws.com/clickhouse-test-reports/43285/b13a8d478bb9c1d1e9f333c26acb6b33a22c6d9b/fuzzer_astfuzzermsan//report.html

query from the stack trace
```
SELECT sum(c0 = 0), min(c0 + 1048575), sum(c0 + 2) FROM t_having__fuzz_0 GROUP BY c0 HAVING c0 = 3 SETTINGS enable_optimize_predicate_expression = 0
```

<details>
<summary><b>StackTrace</b></summary>

```
2022.11.16 23:00:46.357562 [ 433 ] {} <Fatal> BaseDaemon: ########################################
2022.11.16 23:00:46.358304 [ 433 ] {} <Fatal> BaseDaemon: (version 22.11.1.1, build id: 75C90AF14FFCDB4C3309617ABA1DECECBBFC4A3B) (from thread 159) (query_id: adc87f95-5736-4af0-8351-f8051dcad641) (query: SELECT sum(c0 = 0), min(c0 + 1048575), sum(c0 + 2) FROM t_having__fuzz_0 GROUP BY c0 HAVING c0 = 3 SETTINGS enable_optimize_predicate_expression = 0) Received signal Unknown signal -3 (-3)
2022.11.16 23:00:46.358657 [ 433 ] {} <Fatal> BaseDaemon: Sanitizer trap.
2022.11.16 23:00:46.358968 [ 433 ] {} <Fatal> BaseDaemon: Stack trace: 0x282d5e19 0x28afc5fa 0xbf8cfd6 0xbfd46f1 0x54592932 0x545a8da8 0x43aa482f 0x4881f90c 0x48818319 0x487fbe91 0x4883cbde 0x545ac89e 0x545adc2f 0x54d0ec8c 0x54d0a222 0x54d05fe9 0x7f78d92d8609 0x7f78d91fd133
2022.11.16 23:00:46.491998 [ 433 ] {} <Fatal> BaseDaemon: 0.1. inlined from ./build_docker/../src/Common/StackTrace.cpp:332: StackTrace::tryCapture()
2022.11.16 23:00:46.492282 [ 433 ] {} <Fatal> BaseDaemon: 0. ./build_docker/../src/Common/StackTrace.cpp:293: StackTrace::StackTrace() @ 0x282d5e19 in /workspace/clickhouse
2022.11.16 23:00:46.752623 [ 433 ] {} <Fatal> BaseDaemon: 1. ./build_docker/../src/Daemon/BaseDaemon.cpp:421: sanitizerDeathCallback() @ 0x28afc5fa in /workspace/clickhouse
2022.11.16 23:00:52.334231 [ 433 ] {} <Fatal> BaseDaemon: 2. __sanitizer::Die() @ 0xbf8cfd6 in /workspace/clickhouse
2022.11.16 23:00:57.687293 [ 433 ] {} <Fatal> BaseDaemon: 3. ? @ 0xbfd46f1 in /workspace/clickhouse
2022.11.16 23:00:57.722644 [ 433 ] {} <Fatal> BaseDaemon: 4. ./build_docker/../contrib/poco/Net/src/SocketImpl.cpp:322: Poco::Net::SocketImpl::sendBytes(void const*, int, int) @ 0x54592932 in /workspace/clickhouse
2022.11.16 23:00:57.745163 [ 433 ] {} <Fatal> BaseDaemon: 5. ./build_docker/../contrib/poco/Net/src/StreamSocketImpl.cpp:0: Poco::Net::StreamSocketImpl::sendBytes(void const*, int, int) @ 0x545a8da8 in /workspace/clickhouse
2022.11.16 23:00:57.784840 [ 433 ] {} <Fatal> BaseDaemon: 6. ./build_docker/../src/IO/WriteBufferFromPocoSocket.cpp:0: DB::WriteBufferFromPocoSocket::nextImpl() @ 0x43aa482f in /workspace/clickhouse
2022.11.16 23:00:58.380033 [ 433 ] {} <Fatal> BaseDaemon: 7.1. inlined from ./build_docker/../src/IO/BufferBase.h:39: DB::BufferBase::Buffer::begin() const
2022.11.16 23:00:58.380177 [ 433 ] {} <Fatal> BaseDaemon: 7.2. inlined from ./build_docker/../src/IO/WriteBuffer.h:60: DB::WriteBuffer::next()
2022.11.16 23:00:58.380247 [ 433 ] {} <Fatal> BaseDaemon: 7. ./build_docker/../src/Server/TCPHandler.cpp:1779: DB::TCPHandler::sendData(DB::Block const&) @ 0x4881f90c in /workspace/clickhouse
2022.11.16 23:00:58.938016 [ 433 ] {} <Fatal> BaseDaemon: 8.1. inlined from ./build_docker/../contrib/libcxx/include/__mutex_base:143: ~unique_lock
2022.11.16 23:00:58.938150 [ 433 ] {} <Fatal> BaseDaemon: 8. ./build_docker/../src/Server/TCPHandler.cpp:783: DB::TCPHandler::processOrdinaryQueryWithProcessors() @ 0x48818319 in /workspace/clickhouse
2022.11.16 23:00:59.402252 [ 433 ] {} <Fatal> BaseDaemon: 9. ./build_docker/../src/Server/TCPHandler.cpp:0: DB::TCPHandler::runImpl() @ 0x487fbe91 in /workspace/clickhouse
2022.11.16 23:01:00.104241 [ 433 ] {} <Fatal> BaseDaemon: 10. ./build_docker/../src/Server/TCPHandler.cpp:1902: DB::TCPHandler::run() @ 0x4883cbde in /workspace/clickhouse
2022.11.16 23:01:00.124593 [ 433 ] {} <Fatal> BaseDaemon: 11. ./build_docker/../contrib/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x545ac89e in /workspace/clickhouse
2022.11.16 23:01:00.161616 [ 433 ] {} <Fatal> BaseDaemon: 12.1. inlined from ./build_docker/../contrib/libcxx/include/__memory/unique_ptr.h:302: std::__1::unique_ptr<Poco::Net::TCPServerConnection, std::__1::default_delete<Poco::Net::TCPServerConnection>>::reset[abi:v15003](Poco::Net::TCPServerConnection*)
2022.11.16 23:01:00.161766 [ 433 ] {} <Fatal> BaseDaemon: 12.2. inlined from ./build_docker/../contrib/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
2022.11.16 23:01:00.161833 [ 433 ] {} <Fatal> BaseDaemon: 12. ./build_docker/../contrib/poco/Net/src/TCPServerDispatcher.cpp:116: Poco::Net::TCPServerDispatcher::run() @ 0x545adc2f in /workspace/clickhouse
2022.11.16 23:01:00.205359 [ 433 ] {} <Fatal> BaseDaemon: 13. ./build_docker/../contrib/poco/Foundation/src/ThreadPool.cpp:0: Poco::PooledThread::run() @ 0x54d0ec8c in /workspace/clickhouse
2022.11.16 23:01:00.249232 [ 433 ] {} <Fatal> BaseDaemon: 14. ./build_docker/../contrib/poco/Foundation/src/Thread.cpp:56: Poco::(anonymous namespace)::RunnableHolder::run() @ 0x54d0a222 in /workspace/clickhouse
2022.11.16 23:01:00.285286 [ 433 ] {} <Fatal> BaseDaemon: 15. ./build_docker/../contrib/poco/Foundation/src/Thread_POSIX.cpp:360: Poco::ThreadImpl::runnableEntry(void*) @ 0x54d05fe9 in /workspace/clickhouse
2022.11.16 23:01:00.285436 [ 433 ] {} <Fatal> BaseDaemon: 16. ? @ 0x7f78d92d8609 in ?
2022.11.16 23:01:00.285527 [ 433 ] {} <Fatal> BaseDaemon: 17. clone @ 0x7f78d91fd133 in ?
2022.11.16 23:01:00.285634 [ 433 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
2022.11.16 23:01:06.357476 [ 434 ] {} <Fatal> BaseDaemon: ########################################
2022.11.16 23:01:06.357663 [ 434 ] {} <Fatal> BaseDaemon: (version 22.11.1.1, build id: 75C90AF14FFCDB4C3309617ABA1DECECBBFC4A3B) (from thread 159) (query_id: adc87f95-5736-4af0-8351-f8051dcad641) (query: SELECT sum(c0 = 0), min(c0 + 1048575), sum(c0 + 2) FROM t_having__fuzz_0 GROUP BY c0 HAVING c0 = 3 SETTINGS enable_optimize_predicate_expression = 0) Received signal Aborted (6)
2022.11.16 23:01:06.357821 [ 434 ] {} <Fatal> BaseDaemon: 
2022.11.16 23:01:06.357945 [ 434 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f78d912100b 0x7f78d9100859 0xbf8f207 0xbf8d031 0xbfd46f1 0x54592932 0x545a8da8 0x43aa482f 0x4881f90c 0x48818319 0x487fbe91 0x4883cbde 0x545ac89e 0x545adc2f 0x54d0ec8c 0x54d0a222 0x54d05fe9 0x7f78d92d8609 0x7f78d91fd133
2022.11.16 23:01:06.358069 [ 434 ] {} <Fatal> BaseDaemon: 4. raise @ 0x7f78d912100b in ?
2022.11.16 23:01:06.358164 [ 434 ] {} <Fatal> BaseDaemon: 5. abort @ 0x7f78d9100859 in ?
2022.11.16 23:01:11.741582 [ 434 ] {} <Fatal> BaseDaemon: 6. ? @ 0xbf8f207 in /workspace/clickhouse
    #13 0x283252a8 in DB::ThreadStatus::onFatalError() build_docker/../src/Common/ThreadStatus.cpp:243:9
2022.11.16 23:01:17.114311 [ 434 ] {} <Fatal> BaseDaemon: 7. ? @ 0xbf8d031 in /workspace/clickhouse
2022.11.16 23:01:22.472811 [ 434 ] {} <Fatal> BaseDaemon: 8. ? @ 0xbfd46f1 in /workspace/clickhouse
2022.11.16 23:01:22.507814 [ 434 ] {} <Fatal> BaseDaemon: 9. ./build_docker/../contrib/poco/Net/src/SocketImpl.cpp:322: Poco::Net::SocketImpl::sendBytes(void const*, int, int) @ 0x54592932 in /workspace/clickhouse
2022.11.16 23:01:22.530410 [ 434 ] {} <Fatal> BaseDaemon: 10. ./build_docker/../contrib/poco/Net/src/StreamSocketImpl.cpp:0: Poco::Net::StreamSocketImpl::sendBytes(void const*, int, int) @ 0x545a8da8 in /workspace/clickhouse
2022.11.16 23:01:22.569945 [ 434 ] {} <Fatal> BaseDaemon: 11. ./build_docker/../src/IO/WriteBufferFromPocoSocket.cpp:0: DB::WriteBufferFromPocoSocket::nextImpl() @ 0x43aa482f in /workspace/clickhouse
2022.11.16 23:01:23.161961 [ 434 ] {} <Fatal> BaseDaemon: 12.1. inlined from ./build_docker/../src/IO/BufferBase.h:39: DB::BufferBase::Buffer::begin() const
2022.11.16 23:01:23.162102 [ 434 ] {} <Fatal> BaseDaemon: 12.2. inlined from ./build_docker/../src/IO/WriteBuffer.h:60: DB::WriteBuffer::next()
2022.11.16 23:01:23.162169 [ 434 ] {} <Fatal> BaseDaemon: 12. ./build_docker/../src/Server/TCPHandler.cpp:1779: DB::TCPHandler::sendData(DB::Block const&) @ 0x4881f90c in /workspace/clickhouse
2022.11.16 23:01:23.267823 [ 435 ] {} <Fatal> BaseDaemon: ########################################
2022.11.16 23:01:23.267970 [ 435 ] {} <Fatal> BaseDaemon: (version 22.11.1.1, build id: 75C90AF14FFCDB4C3309617ABA1DECECBBFC4A3B) (from thread 433) (no query) Received signal Unknown signal -3 (-3)
2022.11.16 23:01:23.268178 [ 435 ] {} <Fatal> BaseDaemon: Sanitizer trap.
2022.11.16 23:01:23.268283 [ 435 ] {} <Fatal> BaseDaemon: Stack trace: 0x282d5e19 0x28afc5fa 0xbf8cfd6 0xbfd46f1 0x54592932 0x545a8da8 0x43aa482f 0x4883c012 0x4881ab98 0x4883f413 0x283252a9 0x28b13533 0x28b0c010 0x7f78d92d8609 0x7f78d91fd133
2022.11.16 23:01:23.399620 [ 435 ] {} <Fatal> BaseDaemon: 0.1. inlined from ./build_docker/../src/Common/StackTrace.cpp:332: StackTrace::tryCapture()
2022.11.16 23:01:23.399745 [ 435 ] {} <Fatal> BaseDaemon: 0. ./build_docker/../src/Common/StackTrace.cpp:293: StackTrace::StackTrace() @ 0x282d5e19 in /workspace/clickhouse
2022.11.16 23:01:23.660659 [ 435 ] {} <Fatal> BaseDaemon: 1. ./build_docker/../src/Daemon/BaseDaemon.cpp:421: sanitizerDeathCallback() @ 0x28afc5fa in /workspace/clickhouse
2022.11.16 23:01:23.723199 [ 434 ] {} <Fatal> BaseDaemon: 13.1. inlined from ./build_docker/../contrib/libcxx/include/__mutex_base:143: ~unique_lock
2022.11.16 23:01:23.723340 [ 434 ] {} <Fatal> BaseDaemon: 13. ./build_docker/../src/Server/TCPHandler.cpp:783: DB::TCPHandler::processOrdinaryQueryWithProcessors() @ 0x48818319 in /workspace/clickhouse
2022.11.16 23:01:24.187863 [ 434 ] {} <Fatal> BaseDaemon: 14. ./build_docker/../src/Server/TCPHandler.cpp:0: DB::TCPHandler::runImpl() @ 0x487fbe91 in /workspace/clickhouse
2022.11.16 23:01:24.889100 [ 434 ] {} <Fatal> BaseDaemon: 15. ./build_docker/../src/Server/TCPHandler.cpp:1902: DB::TCPHandler::run() @ 0x4883cbde in /workspace/clickhouse
2022.11.16 23:01:24.909385 [ 434 ] {} <Fatal> BaseDaemon: 16. ./build_docker/../contrib/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x545ac89e in /workspace/clickhouse
2022.11.16 23:01:24.946144 [ 434 ] {} <Fatal> BaseDaemon: 17.1. inlined from ./build_docker/../contrib/libcxx/include/__memory/unique_ptr.h:302: std::__1::unique_ptr<Poco::Net::TCPServerConnection, std::__1::default_delete<Poco::Net::TCPServerConnection>>::reset[abi:v15003](Poco::Net::TCPServerConnection*)
2022.11.16 23:01:24.946301 [ 434 ] {} <Fatal> BaseDaemon: 17.2. inlined from ./build_docker/../contrib/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
2022.11.16 23:01:24.946365 [ 434 ] {} <Fatal> BaseDaemon: 17. ./build_docker/../contrib/poco/Net/src/TCPServerDispatcher.cpp:116: Poco::Net::TCPServerDispatcher::run() @ 0x545adc2f in /workspace/clickhouse
2022.11.16 23:01:24.989860 [ 434 ] {} <Fatal> BaseDaemon: 18. ./build_docker/../contrib/poco/Foundation/src/ThreadPool.cpp:0: Poco::PooledThread::run() @ 0x54d0ec8c in /workspace/clickhouse
2022.11.16 23:01:25.033742 [ 434 ] {} <Fatal> BaseDaemon: 19. ./build_docker/../contrib/poco/Foundation/src/Thread.cpp:56: Poco::(anonymous namespace)::RunnableHolder::run() @ 0x54d0a222 in /workspace/clickhouse
2022.11.16 23:01:25.069877 [ 434 ] {} <Fatal> BaseDaemon: 20. ./build_docker/../contrib/poco/Foundation/src/Thread_POSIX.cpp:360: Poco::ThreadImpl::runnableEntry(void*) @ 0x54d05fe9 in /workspace/clickhouse
2022.11.16 23:01:25.070011 [ 434 ] {} <Fatal> BaseDaemon: 21. ? @ 0x7f78d92d8609 in ?
2022.11.16 23:01:25.070085 [ 434 ] {} <Fatal> BaseDaemon: 22. clone @ 0x7f78d91fd133 in ?
2022.11.16 23:01:25.070155 [ 434 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
```

</details>

<details>
<summary><b>MemorySanitizer</b></summary>

```
Uninitialized bytes in __interceptor_send at offset 83 inside [0x7f76ed533000, 121)

==147==WARNING: MemorySanitizer: use-of-uninitialized-value
#0 0x54592931 in Poco::Net::SocketImpl::sendBytes(void const*, int, int) build_docker/../contrib/poco/Net/src/SocketImpl.cpp:322:8
    #1 0x545a8da7 in Poco::Net::StreamSocketImpl::sendBytes(void const*, int, int) build_docker/../contrib/poco/Net/src/StreamSocketImpl.cpp:63:23
    #2 0x43aa482e in DB::WriteBufferFromPocoSocket::nextImpl() build_docker/../src/IO/WriteBufferFromPocoSocket.cpp:63:34
    #3 0x4881f90b in DB::WriteBuffer::next() build_docker/../src/IO/WriteBuffer.h:49:13
    #4 0x4881f90b in DB::TCPHandler::sendData(DB::Block const&) build_docker/../src/Server/TCPHandler.cpp:1779:37
    #5 0x48818318 in DB::TCPHandler::processOrdinaryQueryWithProcessors() build_docker/../src/Server/TCPHandler.cpp:781:21
    #6 0x487fbe90 in DB::TCPHandler::runImpl() build_docker/../src/Server/TCPHandler.cpp:388:17
    #7 0x4883cbdd in DB::TCPHandler::run() build_docker/../src/Server/TCPHandler.cpp:1902:9
    #8 0x545ac89d in Poco::Net::TCPServerConnection::start() build_docker/../contrib/poco/Net/src/TCPServerConnection.cpp:43:3
    #9 0x545adc2e in Poco::Net::TCPServerDispatcher::run() build_docker/../contrib/poco/Net/src/TCPServerDispatcher.cpp:115:20
    #10 0x54d0ec8b in Poco::PooledThread::run() build_docker/../contrib/poco/Foundation/src/ThreadPool.cpp:199:14
    #11 0x54d0a221 in Poco::(anonymous namespace)::RunnableHolder::run() build_docker/../contrib/poco/Foundation/src/Thread.cpp:55:11
    #12 0x54d05fe8 in Poco::ThreadImpl::runnableEntry(void*) build_docker/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345:27
    #13 0x7f78d92d8608 in start_thread /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477:8
    #14 0x7f78d91fd132 in __clone /build/glibc-SzIz7B/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95


  Uninitialized value was stored to memory at
    #0 0xbfa6999 in __msan_memcpy (/workspace/clickhouse+0xbfa6999) (BuildId: 75c90af14ffcdb4c3309617aba1dececbbfc4a3b)
    #1 0xc08ded6 in DB::WriteBuffer::write(char const*, unsigned long) (/workspace/clickhouse+0xc08ded6) (BuildId: 75c90af14ffcdb4c3309617aba1dececbbfc4a3b)
    #2 0x488d0897 in void DB::writePODBinary<char8_t>(char8_t const&, DB::WriteBuffer&) build_docker/../src/IO/WriteHelpers.h:84:9
    #3 0x488d0897 in void DB::writeBinary<char8_t>(char8_t const&, DB::WriteBuffer&) build_docker/../src/IO/WriteHelpers.h:849:59
    #4 0x488d0897 in DB::NativeWriter::write(DB::Block const&) build_docker/../src/Formats/NativeWriter.cpp:139:13
    #5 0x4881f802 in DB::TCPHandler::sendData(DB::Block const&) build_docker/../src/Server/TCPHandler.cpp:1778:26
    #6 0x48817879 in DB::TCPHandler::processOrdinaryQueryWithProcessors() build_docker/../src/Server/TCPHandler.cpp:746:13
    #7 0x487fbe90 in DB::TCPHandler::runImpl() build_docker/../src/Server/TCPHandler.cpp:388:17
    #8 0x4883cbdd in DB::TCPHandler::run() build_docker/../src/Server/TCPHandler.cpp:1902:9
    #9 0x545ac89d in Poco::Net::TCPServerConnection::start() build_docker/../contrib/poco/Net/src/TCPServerConnection.cpp:43:3
    #10 0x545adc2e in Poco::Net::TCPServerDispatcher::run() build_docker/../contrib/poco/Net/src/TCPServerDispatcher.cpp:115:20
    #11 0x54d0ec8b in Poco::PooledThread::run() build_docker/../contrib/poco/Foundation/src/ThreadPool.cpp:199:14
    #12 0x54d0a221 in Poco::(anonymous namespace)::RunnableHolder::run() build_docker/../contrib/poco/Foundation/src/Thread.cpp:55:11
    #13 0x54d05fe8 in Poco::ThreadImpl::runnableEntry(void*) build_docker/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345:27
    #14 0x7f78d92d8608 in start_thread /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477:8



  Uninitialized value was created by an allocation of 'ref.tmp100' in the stack frame of function '_ZN2DB12NativeWriter5writeERKNS_5BlockE'
    #0 0x488ce460 in DB::NativeWriter::write(DB::Block const&) build_docker/../src/Formats/NativeWriter.cpp:68

SUMMARY: MemorySanitizer: use-of-uninitialized-value build_docker/../contrib/poco/Net/src/SocketImpl.cpp:322:8 in Poco::Net::SocketImpl::sendBytes(void const*, int, int)
Exiting
```
</details>

**How to reproduce**
Try to reproduce the report and copy the tables and queries involved.

**Comment by CheSema** [comment]
This is the write-queries from the server log to the table t_having__fuzz_0
```
CREATE TABLE t_having__fuzz_0 (`c0` Float32, `c1` LowCardinality(UInt64)) ENGINE = Memory (stage: Complete)
INSERT INTO t_having__fuzz_0 SELECT number, number FROM numbers(1000)
```

**Comment by alexey-milovidov** [comment]
I cannot reproduce it, and it looks strange, as only one column, `c0`, is used in the query.
