### ISSUE TITLE
CI hitting Github limits

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#43515]
The "CheckLabels" check has been hitting Github API limits recently:

```
INFO:root:Getting URL with 5 tries and sleep 0 in between: https://api.github.com/repos/ClickHouse/ClickHouse/pulls/43455
INFO:root:Exception '403 Client Error: rate limit exceeded for url: https://api.github.com/repos/ClickHouse/ClickHouse/pulls/43455' while getting, retry 1
INFO:root:Exception '403 Client Error: rate limit exceeded for url: https://api.github.com/repos/ClickHouse/ClickHouse/pulls/43455' while getting, retry 2
INFO:root:Exception '403 Client Error: rate limit exceeded for url: https://api.github.com/repos/ClickHouse/ClickHouse/pulls/43455' while getting, retry 3
INFO:root:Exception '403 Client Error: rate limit exceeded for url: https://api.github.com/repos/ClickHouse/ClickHouse/pulls/43455' while getting, retry 4
WARNING:root:Unable to get pull request event 43455 from API, fallback to received event. Exception: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/ClickHouse/ClickHouse/pulls/43455
INFO:root:Getting URL with 5 tries and sleep 0 in between: https://api.github.com/users/Algunenano/orgs
INFO:root:Exception '403 Client Error: rate limit exceeded for url: https://api.github.com/users/Algunenano/orgs' while getting, retry 1
INFO:root:Exception '403 Client Error: rate limit exceeded for url: https://api.github.com/users/Algunenano/orgs' while getting, retry 2
INFO:root:Exception '403 Client Error: rate limit exceeded for url: https://api.github.com/users/Algunenano/orgs' while getting, retry 3
INFO:root:Exception '403 Client Error: rate limit exceeded for url: https://api.github.com/users/Algunenano/orgs' while getting, retry 4
Traceback (most recent call last):
  File "/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/ci/run_check.py", line 200, in <module>
    pr_info = PRInfo(need_orgs=True, pr_event_from_api=True, need_changed_files=True)
  File "/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/ci/pr_info.py", line 151, in __init__
    user_orgs_response = get_with_retries(
  File "/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/ci/build_download_helper.py", line 3[9](https://github.com/ClickHouse/ClickHouse/actions/runs/3523844456/jobs/5908494891#step:5:10), in get_with_retries
    raise Exception(exc)
Exception: 403 Client Error: rate limit exceeded for url: https://api.github.com/users/Algunenano/orgs
Error: Process completed with exit code 1.
```

Some runs:
* https://github.com/ClickHouse/ClickHouse/actions/runs/3514437197/jobs/5888710885
* https://github.com/ClickHouse/ClickHouse/actions/runs/3522479223/jobs/5905509925
* https://github.com/ClickHouse/ClickHouse/actions/runs/3523844456/jobs/5908494891

I'm not sure if something has changed in Clickhouse or Github side of things.

**Comment by tavplubix** [comment]
@Felixoid told that it's fixed in https://github.com/ClickHouse/ClickHouse/pull/43467 (merging fresh master or just this PR into you branch should fix the issue)
