### ISSUE TITLE
ClickHouse while inserting getting error cannot allocate memory: While executing Remote. (CANNOT_ALLOCATE_MEMORY) It looks like that the process is near the limit on number of virtual memory mappings.

### ISSUE THREAD

**Issue by KarthikSRaj** [ClickHouse/ClickHouse#43864]
CH version: 22.5.4.19 (official build)

Things were all fine for 4 months. All of a sudden got below error.

Increased vm.max_map_count to higher number and things came back to normalcy.

**Please clarify below questions:** 

**1. Why did this happen after 4 months? ingestion rate has not increased during this time.
2. Are there any configurations in config.xml using which this memory usage can be controlled?
3. Since memory is finite; this value can be increased to certain levels, any recommended value or recommended methodology to set certain value to this.
4. Does CH release and manage this acquired memory dynamically? or does it require a periodic CH restarts?** 

```
ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: 10.90.120.143, port: 8123; Code: 173. DB::ErrnoException: FiberStack: cannot protect guard page, errno: 12, strerror: Cannot allocate memory: While executing Remote. (CANNOT_ALLOCATE_MEMORY)
It looks like that the process is near the limit on number of virtual memory mappings.
Current number of mappings (/proc/self/maps): 65531.
Limit on number of mappings (/proc/sys/vm/max_map_count): 65530.
You should increase the limit for vm.max_map_count in /etc/sysctl.conf
 (version 22.5.4.19 (official build))

	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.getException(ClickHouseExceptionSpecifier.java:91)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:55)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:28)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.checkForErrorAndThrow(ClickHouseStatementImpl.java:1046)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.getInputStream(ClickHouseStatementImpl.java:737)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:196)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:166)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:161)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:156)
```

**Comment by KarthikSRaj** [comment]
Please share any comments or observations.

**Comment by ra1amx** [comment]
Hi. My problem is a little different. The server is running, but it stops running through the ports. `Error 210`. I decided - the problem is in config.xml But, things have become more complicated. The service starts - but, it is impossible to connect, record and delete data. 
Searching for the problem led me to change the parameter #vm.max_map_count     (_This file contains the maximum number of memory map areas a process may have. Memory map areas are used as a side-effect of calling malloc, directly by mmap and mprotect, and also when loading shared libraries.

While most applications need less than a thousand maps, certain programs, particularly malloc debuggers, may consume lots of them, e.g., up to one or two maps per allocation.

The default value is 65536._)


```
sysctl -a
sysctl -w vm.max_map_count=524288
 sysctl --system

```
The problem was not solved

I tried the command to run in manual mode 
sudo -u clickhouse clickhouse-server --config-file=/etc/clickhouse-server/config.xml 

and I saw the error 

`<Error> database.table (4c5b45a1-ac72-4a97-9c99-451e0de884d0): Detaching broken part /var/lib/clickhouse/store/4c5/4c5b45a1-ac72-4a97-9c99-451e0de884d0/202307_1694504275_1694504275_0 (size: 0.00 B)`. 

If it happened after update, it is likely because of backward incompability. You need to resolve this manually

After which I 

```
grep 'ClickHouse init process failed'  /var/log/clickhouse-server/clickhouse-server.log

 tail -F /var/log/clickhouse-server/clickhouse-server.err.log
```

and decided to do so
```
sudo -u clickhouse touch /var/lib/clickhouse/flags/force_restore_data

systemctl start clickhouse-server

 systemctl status clickhouse-server
```
the server started and the ports became available
` clickhouse-client --user default --password`

My problem is solved
