### ISSUE TITLE
Analyzer: use-of-uninitialized-value in SortNode/SipHash::update

### ISSUE THREAD

**Issue by kssenii** [ClickHouse/ClickHouse#44258]
https://s3.amazonaws.com/clickhouse-test-reports/41976/ea5b06023a79dceccae70ad5e3954129050af5a2/fuzzer_astfuzzermsan//report.html

```
2022.12.14 18:56:32.134997 [ 453 ] {} <Fatal> BaseDaemon: ########################################
2022.12.14 18:56:32.135719 [ 453 ] {} <Fatal> BaseDaemon: (version 22.12.1.1, build id: 149BE79908CE55572FF948EECD3EC781AA69F91A) (from thread 165) (query_id: 73895d08-bd51-4b0f-8a03-4af3a551cc0d) (query: SELECT * FROM (SELECT * FROM test_fetch ORDER BY a ASC, b ASC LIMIT 1, 3) ORDER BY a ASC, b ASC) Received signal sanitizer trap (-3)
2022.12.14 18:56:32.135994 [ 453 ] {} <Fatal> BaseDaemon: Sanitizer trap.
2022.12.14 18:56:32.136328 [ 453 ] {} <Fatal> BaseDaemon: Stack trace: 0x28c42259 0x294e3a9a 0xc272056 0xc286bf3 0x447aca9e 0x447a9bc3 0x447a909b 0x445e29ea 0x458016ce 0x447f2d4c 0x466262c4 0x4661d0de 0x49ee6bb6 0x49f2837e 0x55faef9e 0x55fb032f 0x5671088c 0x5670be22 0x56707be9 0x7f29ec00e609 0x7f29ebf33133
2022.12.14 18:56:32.268904 [ 453 ] {} <Fatal> BaseDaemon: 0.1. inlined from ./build_docker/../src/Common/StackTrace.cpp:334: StackTrace::tryCapture()
2022.12.14 18:56:32.269152 [ 453 ] {} <Fatal> BaseDaemon: 0. ./build_docker/../src/Common/StackTrace.cpp:295: StackTrace::StackTrace() @ 0x28c42259 in /workspace/clickhouse
2022.12.14 18:56:32.530003 [ 453 ] {} <Fatal> BaseDaemon: 1. ./build_docker/../src/Daemon/BaseDaemon.cpp:431: sanitizerDeathCallback() @ 0x294e3a9a in /workspace/clickhouse
2022.12.14 18:56:38.174160 [ 453 ] {} <Fatal> BaseDaemon: 2. __sanitizer::Die() @ 0xc272056 in /workspace/clickhouse
2022.12.14 18:56:43.596037 [ 453 ] {} <Fatal> BaseDaemon: 3. ? @ 0xc286bf3 in /workspace/clickhouse
2022.12.14 18:56:43.653110 [ 453 ] {} <Fatal> BaseDaemon: 4.1. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__hash_table:1822: std::__1::__hash_table<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>, std::__1::hash<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>>, std::__1::equal_to<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>>, std::__1::allocator<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>>>::__node_insert_unique_perform[abi:v15000](std::__1::__hash_node<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>, void*>*)
2022.12.14 18:56:43.653293 [ 453 ] {} <Fatal> BaseDaemon: 4.2. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__hash_table:1852: std::__1::__hash_table<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>, std::__1::hash<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>>, std::__1::equal_to<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>>, std::__1::allocator<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>>>::__node_insert_unique(std::__1::__hash_node<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>, void*>*)
2022.12.14 18:56:43.653360 [ 453 ] {} <Fatal> BaseDaemon: 4. ./build_docker/../contrib/llvm-project/libcxx/include/__hash_table:2054: std::__1::pair<std::__1::__hash_iterator<std::__1::__hash_node<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>, void*>*>, bool> std::__1::__hash_table<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>, std::__1::hash<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>>, std::__1::equal_to<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>>, std::__1::allocator<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>>>::__emplace_unique_impl<DB::IQueryTreeNode*>(DB::IQueryTreeNode*&&) @ 0x447aca9e in /workspace/clickhouse
2022.12.14 18:56:43.702494 [ 453 ] {} <Fatal> BaseDaemon: 5.1. inlined from ./build_docker/../src/Analyzer/Passes/OrderByLimitByDuplicateEliminationPass.cpp:0: DB::(anonymous namespace)::OrderByLimitByDuplicateEliminationVisitor::visitImpl(std::__1::shared_ptr<DB::IQueryTreeNode>&)
2022.12.14 18:56:43.702618 [ 453 ] {} <Fatal> BaseDaemon: 5. ./build_docker/../src/Analyzer/InDepthQueryTreeVisitor.h:52: DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::OrderByLimitByDuplicateEliminationVisitor, false>::visit(std::__1::shared_ptr<DB::IQueryTreeNode>&) @ 0x447a9bc3 in /workspace/clickhouse
2022.12.14 18:56:43.748406 [ 453 ] {} <Fatal> BaseDaemon: 6.1. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__hash_table:1473: ~__hash_table
2022.12.14 18:56:43.748522 [ 453 ] {} <Fatal> BaseDaemon: 6.2. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/unordered_set:615: ~unordered_set
2022.12.14 18:56:43.748593 [ 453 ] {} <Fatal> BaseDaemon: 6.3. inlined from ./build_docker/../src/Analyzer/Passes/OrderByLimitByDuplicateEliminationPass.cpp:14: ~OrderByLimitByDuplicateEliminationVisitor
2022.12.14 18:56:43.748656 [ 453 ] {} <Fatal> BaseDaemon: 6. ./build_docker/../src/Analyzer/Passes/OrderByLimitByDuplicateEliminationPass.cpp:77: DB::OrderByLimitByDuplicateEliminationPass::run(std::__1::shared_ptr<DB::IQueryTreeNode>, std::__1::shared_ptr<DB::Context const>) @ 0x447a909b in /workspace/clickhouse
2022.12.14 18:56:43.820936 [ 453 ] {} <Fatal> BaseDaemon: 7. ./build_docker/../src/Analyzer/QueryTreePassManager.cpp:97: DB::QueryTreePassManager::run(std::__1::shared_ptr<DB::IQueryTreeNode>) @ 0x445e29ea in /workspace/clickhouse
2022.12.14 18:56:43.939236 [ 453 ] {} <Fatal> BaseDaemon: 8.1. inlined from ./build_docker/../src/Analyzer/QueryTreePassManager.h:13: ~QueryTreePassManager
2022.12.14 18:56:43.939399 [ 453 ] {} <Fatal> BaseDaemon: 8.2. inlined from ./build_docker/../src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:57: DB::(anonymous namespace)::buildQueryTreeAndRunPasses(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const> const&)
2022.12.14 18:56:43.939482 [ 453 ] {} <Fatal> BaseDaemon: 8. ./build_docker/../src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:66: DB::InterpreterSelectQueryAnalyzer::InterpreterSelectQueryAnalyzer(std::__1::shared_ptr<DB::IAST> const&, DB::SelectQueryOptions const&, std::__1::shared_ptr<DB::Context const>) @ 0x458016ce in /workspace/clickhouse
2022.12.14 18:56:44.063399 [ 453 ] {} <Fatal> BaseDaemon: 9. ./build_docker/../src/Interpreters/InterpreterFactory.cpp:0: DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) @ 0x447f2d4c in /workspace/clickhouse
2022.12.14 18:56:44.722138 [ 453 ] {} <Fatal> BaseDaemon: 10. ./build_docker/../src/Interpreters/executeQuery.cpp:0: DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x466262c4 in /workspace/clickhouse
2022.12.14 18:56:45.438761 [ 453 ] {} <Fatal> BaseDaemon: 11. ./build_docker/../src/Interpreters/executeQuery.cpp:1083: DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x4661d0de in /workspace/clickhouse
```

**Comment by tavplubix** [comment]
@kssenii, full msan report is required, stacktrace is not enough (see https://github.com/ClickHouse/ClickHouse/issues/43736)

**Comment by kssenii** [comment]
```
==162==WARNING: MemorySanitizer: use-of-uninitialized-value
2022.12.14 18:56:27.000275 [ 387 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 2.31 GiB, peak 2.99 GiB, free memory in arenas 0.00 B, will set to 2.32 GiB (RSS), difference: 1.42 MiB
    #0 0x447aca9d in std::__1::__hash_table<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>, std::__1::hash<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>>, std::__1::equal_to<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>>, std::__1::allocator<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>>>::__node_insert_unique_perform[abi:v15000](std::__1::__hash_node<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>, void*>*) build_docker/../contrib/llvm-project/libcxx/include/__hash_table:1821:27
    #1 0x447aca9d in std::__1::__hash_table<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>, std::__1::hash<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>>, std::__1::equal_to<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>>, std::__1::allocator<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>>>::__node_insert_unique(std::__1::__hash_node<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>, void*>*) build_docker/../contrib/llvm-project/libcxx/include/__hash_table:1852:9
    #2 0x447aca9d in std::__1::pair<std::__1::__hash_iterator<std::__1::__hash_node<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>, void*>*>, bool> std::__1::__hash_table<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>, std::__1::hash<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>>, std::__1::equal_to<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>>, std::__1::allocator<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>>>::__emplace_unique_impl<DB::IQueryTreeNode*>(DB::IQueryTreeNode*&&) build_docker/../contrib/llvm-project/libcxx/include/__hash_table:2054:32
    #3 0x447a9bc2 in std::__1::pair<std::__1::__hash_iterator<std::__1::__hash_node<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>, void*>*>, bool> std::__1::__hash_table<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>, std::__1::hash<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>>, std::__1::equal_to<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>>, std::__1::allocator<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>>>::__emplace_unique_extract_key[abi:v15000]<DB::IQueryTreeNode*>(DB::IQueryTreeNode*&&, std::__1::__extract_key_fail_tag) build_docker/../contrib/llvm-project/libcxx/include/__hash_table:1067:14
    #4 0x447a9bc2 in std::__1::pair<std::__1::__hash_iterator<std::__1::__hash_node<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>, void*>*>, bool> std::__1::__hash_table<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>, std::__1::hash<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>>, std::__1::equal_to<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>>, std::__1::allocator<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>>>::__emplace_unique[abi:v15000]<DB::IQueryTreeNode*>(DB::IQueryTreeNode*&&) build_docker/../contrib/llvm-project/libcxx/include/__hash_table:1045:14
    #5 0x447a9bc2 in std::__1::pair<std::__1::__hash_const_iterator<std::__1::__hash_node<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>, void*>*>, bool> std::__1::unordered_set<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>, std::__1::hash<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>>, std::__1::equal_to<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>>, std::__1::allocator<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>>>::emplace[abi:v15000]<DB::IQueryTreeNode*>(DB::IQueryTreeNode*&&) build_docker/../contrib/llvm-project/libcxx/include/unordered_set:659:30
    #6 0x447a9bc2 in DB::(anonymous namespace)::OrderByLimitByDuplicateEliminationVisitor::visitImpl(std::__1::shared_ptr<DB::IQueryTreeNode>&) build_docker/../src/Analyzer/Passes/OrderByLimitByDuplicateEliminationPass.cpp:40:67
    #7 0x447a9bc2 in DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::OrderByLimitByDuplicateEliminationVisitor, false>::visit(std::__1::shared_ptr<DB::IQueryTreeNode>&) build_docker/../src/Analyzer/InDepthQueryTreeVisitor.h:52:22
    #8 0x447a909a in DB::OrderByLimitByDuplicateEliminationPass::run(std::__1::shared_ptr<DB::IQueryTreeNode>, std::__1::shared_ptr<DB::Context const>) build_docker/../src/Analyzer/Passes/OrderByLimitByDuplicateEliminationPass.cpp:76:13
    #9 0x445e29e9 in DB::QueryTreePassManager::run(std::__1::shared_ptr<DB::IQueryTreeNode>) build_docker/../src/Analyzer/QueryTreePassManager.cpp:99:20
    #10 0x458016cd in DB::(anonymous namespace)::buildQueryTreeAndRunPasses(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const> const&) build_docker/../src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:54:29
    #11 0x458016cd in DB::InterpreterSelectQueryAnalyzer::InterpreterSelectQueryAnalyzer(std::__1::shared_ptr<DB::IAST> const&, DB::SelectQueryOptions const&, std::__1::shared_ptr<DB::Context const>) build_docker/../src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:66:18
    #12 0x447f2d4b in std::__1::__unique_if<DB::InterpreterSelectQueryAnalyzer>::__unique_single std::__1::make_unique[abi:v15000]<DB::InterpreterSelectQueryAnalyzer, std::__1::shared_ptr<DB::IAST>&, DB::SelectQueryOptions const&, std::__1::shared_ptr<DB::Context>&>(std::__1::shared_ptr<DB::IAST>&, DB::SelectQueryOptions const&, std::__1::shared_ptr<DB::Context>&) build_docker/../contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:714:32
    #13 0x447f2d4b in DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) build_docker/../src/Interpreters/InterpreterFactory.cpp:140:20
    #14 0x466262c3 in DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) build_docker/../src/Interpreters/executeQuery.cpp:640:27
    #15 0x4661d0dd in DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) build_docker/../src/Interpreters/executeQuery.cpp:1083:30
    #16 0x49ee6bb5 in DB::TCPHandler::runImpl() build_docker/../src/Server/TCPHandler.cpp:375:24
    #17 0x49f2837d in DB::TCPHandler::run() build_docker/../src/Server/TCPHandler.cpp:1914:9
    #18 0x55faef9d in Poco::Net::TCPServerConnection::start() build_docker/../contrib/poco/Net/src/TCPServerConnection.cpp:43:3
--
    #12 0x44458c4f in DB::(anonymous namespace)::QueryTreeBuilder::buildSelectOrUnionExpression(std::__1::shared_ptr<DB::IAST> const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context const> const&) const build_docker/../src/Analyzer/QueryTreeBuilder.cpp:145:22
    #13 0x44463d10 in DB::(anonymous namespace)::QueryTreeBuilder::buildSelectWithUnionExpression(std::__1::shared_ptr<DB::IAST> const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context const> const&) const build_docker/../src/Analyzer/QueryTreeBuilder.cpp:161:16
    #14 0x44458d6a in DB::(anonymous namespace)::QueryTreeBuilder::buildSelectOrUnionExpression(std::__1::shared_ptr<DB::IAST> const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context const> const&) const build_docker/../src/Analyzer/QueryTreeBuilder.cpp:141:22
    #15 0x44457bd6 in DB::(anonymous namespace)::QueryTreeBuilder::QueryTreeBuilder(std::__1::shared_ptr<DB::IAST>, std::__1::shared_ptr<DB::Context const>) build_docker/../src/Analyzer/QueryTreeBuilder.cpp:126:27
    #16 0x44457bd6 in DB::buildQueryTree(std::__1::shared_ptr<DB::IAST>, std::__1::shared_ptr<DB::Context const>) build_docker/../src/Analyzer/QueryTreeBuilder.cpp:905:22
    #17 0x458014d3 in DB::(anonymous namespace)::buildQueryTreeAndRunPasses(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const> const&) build_docker/../src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:50:23
    #18 0x458014d3 in DB::InterpreterSelectQueryAnalyzer::InterpreterSelectQueryAnalyzer(std::__1::shared_ptr<DB::IAST> const&, DB::SelectQueryOptions const&, std::__1::shared_ptr<DB::Context const>) build_docker/../src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:66:18
    #19 0x447f2d4b in std::__1::__unique_if<DB::InterpreterSelectQueryAnalyzer>::__unique_single std::__1::make_unique[abi:v15000]<DB::InterpreterSelectQueryAnalyzer, std::__1::shared_ptr<DB::IAST>&, DB::SelectQueryOptions const&, std::__1::shared_ptr<DB::Context>&>(std::__1::shared_ptr<DB::IAST>&, DB::SelectQueryOptions const&, std::__1::shared_ptr<DB::Context>&) build_docker/../contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:714:32
    #20 0x447f2d4b in DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) build_docker/../src/Interpreters/InterpreterFactory.cpp:140:20
    #21 0x466262c3 in DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) build_docker/../src/Interpreters/executeQuery.cpp:640:27
    #22 0x4661d0dd in DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) build_docker/../src/Interpreters/executeQuery.cpp:1083:30
    #23 0x49ee6bb5 in DB::TCPHandler::runImpl() build_docker/../src/Server/TCPHandler.cpp:375:24
    #24 0x49f2837d in DB::TCPHandler::run() build_docker/../src/Server/TCPHandler.cpp:1914:9
    #25 0x55faef9d in Poco::Net::TCPServerConnection::start() build_docker/../contrib/poco/Net/src/TCPServerConnection.cpp:43:3
    #26 0x55fb032e in Poco::Net::TCPServerDispatcher::run() build_docker/../contrib/poco/Net/src/TCPServerDispatcher.cpp:115:20
    #27 0x5671088b in Poco::PooledThread::run() build_docker/../contrib/poco/Foundation/src/ThreadPool.cpp:199:14

  Uninitialized value was created by an allocation of 'nulls_sort_direction' in the stack frame of function '_ZNK2DB12_GLOBAL__N_116QueryTreeBuilder13buildSortListERKNSt3__110shared_ptrINS_4IASTEEERKNS3_IKNS_7ContextEEE'
    #0 0x444793e0 in DB::(anonymous namespace)::QueryTreeBuilder::buildSortList(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const> const&) const build_docker/../src/Analyzer/QueryTreeBuilder.cpp:335

SUMMARY: MemorySanitizer: use-of-uninitialized-value build_docker/../contrib/llvm-project/libcxx/include/__hash_table:1821:27 in std::__1::__hash_table<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>, std::__1::hash<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>>, std::__1::equal_to<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>>, std::__1::allocator<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>>>::__node_insert_unique_perform[abi:v15000](std::__1::__hash_node<DB::QueryTreeNodeWithHash<DB::IQueryTreeNode const*>, void*>*)
Exiting
```

**Comment by tavplubix** [comment]
Looks like some frames are sill missing

**Comment by tavplubix** [comment]
Here's the full report: https://pastila.nl/?0087be59/063b0e0124d093609c4c0722cd94fb6d
(I used `zgrep -Fav "2022.12.14 18:5" server.log.gz | tail -500` to obtain it)

**Comment by tavplubix** [comment]
The root cause is that `SortNode::updateTreeHashImpl` does not check if `nulls_sort_direction` has a value and the generic implementation of `SipHash::update` does not handle `std::optional` correctly

**Comment by alexey-milovidov** [comment]
@kitaisreal this is related to Analyzer.
