### ISSUE TITLE
stack-use-after-return in LimitReadBuffer

### ISSUE THREAD

**Issue by Avogar** [ClickHouse/ClickHouse#45199]
https://s3.amazonaws.com/clickhouse-test-reports/43927/035dc33707f5663f1612130c078434946932b9c7/stress_test__asan_.html

**Comment by Avogar** [comment]
Logs:
```
==1662==ERROR: AddressSanitizer: stack-use-after-return on address 0x7fce45c43828 at pc 0x0000203977c3 bp 0x7fce485afd00 sp
0x7fce485afcf8
WRITE of size 8 at 0x7fce45c43828 thread T1164 (HTTPHandler)
==1662==T352 TSDDtor
==1662==T352 exited
    #0 0x203977c2 in DB::LimitReadBuffer::~LimitReadBuffer() build_docker/../src/IO/LimitReadBuffer.cpp:80:24
    #1 0x203977c2 in DB::LimitReadBuffer::~LimitReadBuffer() build_docker/../src/IO/LimitReadBuffer.cpp:77:1
    #2 0x2f3673c9 in std::__1::default_delete<DB::ReadBuffer>::operator()[abi:v15000](DB::ReadBuffer*) const build_docker/../contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48:5
    #3 0x2f3673c9 in std::__1::unique_ptr<DB::ReadBuffer, std::__1::default_delete<DB::ReadBuffer>>::reset[abi:v15000](DB::ReadBuffer*) build_docker/../contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:305:7
    #4 0x2f3673c9 in std::__1::unique_ptr<DB::ReadBuffer, std::__1::default_delete<DB::ReadBuffer>>::~unique_ptr[abi:v15000]() build_docker/../contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259:19
    #5 0x2f3673c9 in DB::BaseExternalTable::~BaseExternalTable() build_docker/../src/Core/ExternalTable.h:45:42
    #6 0x35445531 in DB::DynamicQueryHandler::getQuery(DB::HTTPServerRequest&, DB::HTMLForm&, std::__1::shared_ptr<DB::Context>) build_docker/../src/Server/HTTPHandler.cpp:1083:1
    #7 0x35431eca in DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) build_docker/../src/Server/HTTPHandler.cpp:759:26
    #8 0x3543dc04 in DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) build_docker/../src/Server/HTTPHandler.cpp:988:9
    #9 0x3556cd2e in DB::HTTPServerConnection::run() build_docker/../src/Server/HTTP/HTTPServerConnection.cpp:68:34
    #10 0x3ccbb88e in Poco::Net::TCPServerConnection::start() build_docker/../contrib/poco/Net/src/TCPServerConnection.cpp:43:3
    #11 0x3ccbc5e4 in Poco::Net::TCPServerDispatcher::run() build_docker/../contrib/poco/Net/src/TCPServerDispatcher.cpp:115:20
    #12 0x3d18069b in Poco::PooledThread::run() build_docker/../contrib/poco/Foundation/src/ThreadPool.cpp:199:14
    #13 0x3d179c4c in Poco::ThreadImpl::runnableEntry(void*) build_docker/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345:27
    #14 0x7fd655be1608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8608) (BuildId: 7b4536f41cdaa5888408e82d0836e33dcf436466)
    #15 0x7fd655b06132 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x11f132) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)

Address 0x7fce45c43828 is located in stack of thread T1164 (HTTPHandler) at offset 40 in frame
    #0 0x355632af in DB::HTMLForm::readMultipart(DB::ReadBuffer&, DB::HTMLForm::PartHandler&) build_docker/../src/Server/HTT
P/HTMLForm.cpp:179

  This frame has 13 object(s):
    [32, 344) 'in' <== Memory access at offset 40 is inside this variable
    [416, 440) 'ref.tmp'
    [480, 504) 'ref.tmp12'
    [544, 584) 'header'
    [624, 656) 'params'
    [688, 712) 'ref.tmp39'
    [752, 776) 'unused'
    [816, 840) 'ref.tmp48'
    [880, 904) 'ref.tmp60'
    [944, 968) 'name'
    [1008, 1032) 'ref.tmp72'
    [1072, 1096) 'value'
    [1136, 1160) 'ref.tmp91'
```
