### ISSUE TITLE
insert data error

### ISSUE THREAD

**Issue by dchen202** [ClickHouse/ClickHouse#45348]
I used docker desktop to install clickhouse on Windows 10 system and a test table was successfully created:
`CREATE TABLE test  
(  
    `id` UInt8 default 0 comment 'id',  
    `name` Nullable(String) comment '名字',  
    `create_time` DateTime default toDateTime(now()) comment '创建时间'  
)  
ENGINE = MergeTree()  
PARTITION BY toYYYYMM(create_time)  
PRIMARY KEY id  
ORDER BY (id, create_time)`

But after preparing to insert a piece of data, an error is reported
SQL:
`insert into test(id, name, create_time) values(100, 'tank', toDateTime(now()));`

Error message:
org.jkiss.dbeaver.model.sql.DBSQLException: SQL 错误 [1002] [07000]: std::exception. Code: 1001, type: std::__1::__fs::filesystem::filesystem_error, e.what() = filesystem error: in rename: No such file or directory ["/var/lib/clickhouse/store/556/556181c8-f72b-4a69-bf20-75bf631b88c6/tmp_insert_202301_9_9_0/"] ["/var/lib/clickhouse/store/556/556181c8-f72b-4a69-bf20-75bf631b88c6/202301_9_9_0/"]
Cannot print extra info for Poco::Exception (version 22.12.3.5 (official build))
, server ClickHouseNode(addr=http:localhost:8123, db=onepaydb)@-984717543

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)

	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:577)

	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:486)

	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)

	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:493)

	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:894)

	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3642)

	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)

	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)

	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)

	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4891)

	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)

	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

Caused by: java.sql.SQLException: std::exception. Code: 1001, type: std::__1::__fs::filesystem::filesystem_error, e.what() = filesystem error: in rename: No such file or directory ["/var/lib/clickhouse/store/556/556181c8-f72b-4a69-bf20-75bf631b88c6/tmp_insert_202301_9_9_0/"] ["/var/lib/clickhouse/store/556/556181c8-f72b-4a69-bf20-75bf631b88c6/202301_9_9_0/"]
Cannot print extra info for Poco::Exception (version 22.12.3.5 (official build))
, server ClickHouseNode(addr=http:localhost:8123, db=onepaydb)@-984717543

	at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:54)

	at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:69)

	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.getLastResponse(ClickHouseStatementImpl.java:80)

	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:257)

	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.execute(ClickHouseStatementImpl.java:409)

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:329)

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.lambda$0(JDBCStatementImpl.java:131)

	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:94)

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)

	... 12 more

Caused by: java.io.IOException: std::exception. Code: 1001, type: std::__1::__fs::filesystem::filesystem_error, e.what() = filesystem error: in rename: No such file or directory ["/var/lib/clickhouse/store/556/556181c8-f72b-4a69-bf20-75bf631b88c6/tmp_insert_202301_9_9_0/"] ["/var/lib/clickhouse/store/556/556181c8-f72b-4a69-bf20-75bf631b88c6/202301_9_9_0/"]
Cannot print extra info for Poco::Exception (version 22.12.3.5 (official build))

	at com.clickhouse.client.http.HttpUrlConnectionImpl.checkResponse(HttpUrlConnectionImpl.java:130)

	at com.clickhouse.client.http.HttpUrlConnectionImpl.post(HttpUrlConnectionImpl.java:201)

	at com.clickhouse.client.http.ClickHouseHttpClient.postRequest(ClickHouseHttpClient.java:88)

	at com.clickhouse.client.http.ClickHouseHttpClient.execute(ClickHouseHttpClient.java:115)

	at com.clickhouse.client.ClickHouseRequest.execute(ClickHouseRequest.java:1375)

	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.getLastResponse(ClickHouseStatementImpl.java:75)

	... 18 more

What's wrong? Thanks.

**Comment by den-crane** [comment]
WSL / windows NTFS does not support some features. You need to use linux partitions with Ext4.
