### ISSUE TITLE
Flaky test_redirect_url_storage

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#45453]
https://s3.amazonaws.com/clickhouse-test-reports/0/fdea042991f2a020f6ed18d860a67dea8438403d/integration_tests__tsan__[4/4].html
```
2023-01-19 11:34:28,865 FATAL org.apache.hadoop.hdfs.server.datanode.DataNode: Exception in secureMain
java.net.BindException: Problem binding to [0.0.0.0:50010] java.net.BindException: Address already in use; For more details see:  http://wiki.apache.org/hadoop/BindException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:792)
        at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:721)
        at org.apache.hadoop.ipc.Server.bind(Server.java:425)
        at org.apache.hadoop.ipc.Server.bind(Server.java:397)
        at org.apache.hadoop.hdfs.net.TcpPeerServer.<init>(TcpPeerServer.java:111)
        at org.apache.hadoop.hdfs.server.datanode.DataNode.initDataXceiver(DataNode.java:920)
        at org.apache.hadoop.hdfs.server.datanode.DataNode.startDataNode(DataNode.java:1133)
        at org.apache.hadoop.hdfs.server.datanode.DataNode.<init>(DataNode.java:434)
        at org.apache.hadoop.hdfs.server.datanode.DataNode.makeInstance(DataNode.java:2404)
        at org.apache.hadoop.hdfs.server.datanode.DataNode.instantiateDataNode(DataNode.java:2291)
        at org.apache.hadoop.hdfs.server.datanode.DataNode.createDataNode(DataNode.java:2338)
        at org.apache.hadoop.hdfs.server.datanode.DataNode.secureMain(DataNode.java:2515)
        at org.apache.hadoop.hdfs.server.datanode.DataNode.main(DataNode.java:2539)
Caused by: java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:444)
        at sun.nio.ch.Net.bind(Net.java:436)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.apache.hadoop.ipc.Server.bind(Server.java:408)
        ... 10 more
```

`grep -Ri fatal` may be also useful as sanitisers check

**Comment by KochetovNicolai** [comment]
Last failure date is `2022-10-21`
