### ISSUE TITLE
Materialized View Stops Working Suddenly 

### ISSUE THREAD

**Issue by caueteixeira** [ClickHouse/ClickHouse#45452]
ClickHouse 22.8.4.7

All of the sudden Materialized View query stops working. 

It implements the last point data query with the following structure:

CREATE TABLE market_price(
timestamp UInt64,
price_id UInt64,
exchange_id Int32,
instrument_id Int32,
price_type Enum('bid' = 1, 'ask' = 2, 'last' = 3),
price Float64
)
ENGINE=MergeTree()
PARTITION BY tuple()
ORDER BY(exchange_id, instrument_id, price_type)
PRIMARY KEY(exchange_id, instrument_id, price_type)
TTL FROM_UNIXTIME(timestamp) + INTERVAL 1 HOUR

-------------------------------------------------------------

CREATE TABLE market_price_agg(
max_price_id AggregateFunction(max, UInt64),
exchange_id Int32,
instrument_id Int32,
price_type Float64,
price AggregateFunction(argMax, Float64, UInt64)
)
ENGINE=AggregatingMergeTree()
PARTITION BY tuple()
ORDER BY (exchange_id, instrument_id, price_type)

-------------------------------------------------------------

CREATE MATERIALIZED VIEW market_price_mv
TO market_price_agg
AS
SELECT
maxState(price_id) as max_price_id,
exchange_id,
instrument_id,
price_type,
argMaxState(price, price_id) as price
FROM
market_price
GROUP BY
exchange_id,
instrument_id,
price_type

-------------------------------------------------------------

SELECT
maxMerge(max_price_id) as price_id,
exchange_id,
instrument_id,
price_type,
argMaxMerge(price) as price
FROM
market_price_mv
GROUP BY
exchange_id,
instrument_id,
price_type

-------------------------------------------------------------

Query won't work (data is not aggregated and not refreshed). It seems like _agg and _mv also does not work (do not refresh) even thought records are still inserted at market_price.

Even after restarting clickhouse server, data is inserted properly at market_price table but the query will not work (never refreshed).

I have been experiencing this issue quite often. I thought It was a problem with clickhouse version but even when upgrading to 22.8.4.7 I still get the issue.

I can't see any related errors in clickhouse log file.

I believe It stops working after a connection timeout between the client and the server. These are connection errors on the client side:

1: 
java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 42720ms.
        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
        at dynamic.trading.basket.analytic.service.database.ConnectionHandler.executeQuery(ConnectionHandler.java:46)
        at dynamic.trading.basket.analytic.service.core.Analytic.refresh(Analytic.java:70)
        at dynamic.trading.basket.analytic.service.core.Analytic.process(Analytic.java:62)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

2:
ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 159, host: localhost, port: 8123; Read timed out
        at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.getException(ClickHouseExceptionSpecifier.java:86)
        at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:56)
        at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:25)
        at ru.yandex.clickhouse.ClickHouseStatementImpl.getInputStream(ClickHouseStatementImpl.java:797)
        at ru.yandex.clickhouse.ClickHouseStatementImpl.getLastInputStream(ClickHouseStatementImpl.java:691)
        at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:340)
        at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:324)
        at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:319)
        at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:314)
        at com.zaxxer.hikari.pool.ProxyStatement.executeQuery(ProxyStatement.java:110)
        at com.zaxxer.hikari.pool.HikariProxyStatement.executeQuery(HikariProxyStatement.java)
        at dynamic.trading.basket.analytic.service.database.ConnectionHandler.executeQuery(ConnectionHandler.java:48)
        at dynamic.trading.basket.analytic.service.core.Analytic.refresh(Analytic.java:70)
        at dynamic.trading.basket.analytic.service.core.Analytic.process(Analytic.java:62)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.base/java.net.SocketInputStream.socketRead0(Native Method)
        at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
        at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at ru.yandex.clickhouse.ClickHouseStatementImpl.getInputStream(ClickHouseStatementImpl.java:771)

The only way to get it back working is to stop clickhouse server, drop all tables/views, recreate them and restart the server.

Please let me know if you have any thoughts or need more details.

Thanks,

Caue

**Comment by den-crane** [comment]
I think you have an error `price_type Float64,`

Provide the full `/var/log/clickhouse-server/clickhouse-server.log` with TRACE level for a period of time related to the issue.

**Comment by caueteixeira** [comment]
[clickhouse-server-trace-on.log](https://github.com/ClickHouse/ClickHouse/files/10462207/clickhouse-server-trace-on.log)

@den-crane - please find attached. 

Let me know if you need anything else.

Thanks,

Caue

**Comment by den-crane** [comment]
How do you check that data is not coming any more? 
I see you query `analytic_view`, please provide `show create table analytic_view`
Also change  `price_type Float64,` to `price_type Enum('bid' = 1, 'ask' = 2, 'last' = 3),`

**Comment by caueteixeira** [comment]
@den-crane - I found the issue. The price_id inserted after restarting my process is reset to 0 at market_price while market_price_mv still holds the previous price_id. It works when price_id at market_price is greater than price_id at market_price_mv. That said, It's not a MV issue. 
Thanks,
Caue
