### ISSUE TITLE
heap-buffer-overflow in `MergeTreeConditionFullText` (possible type mismatch with `Field`)

### ISSUE THREAD

**Issue by kssenii** [ClickHouse/ClickHouse#45509]
https://s3.amazonaws.com/clickhouse-test-reports/45442/dfac0bb42d7214c7c4aaec35cf91a1c0c71a7e1d/fuzzer_astfuzzerasan/report.html
```sql
SELECT '2', (map['']) = NULL, '21474836.46', NULL FROM bf_ngrambf_map_keys_test PREWHERE (map_fixed['']) != '' WHERE (map_fixed[NULL]) != 'V0V0V0V0V0V0V0V0V0V0V0V0V0V0V0V0' SETTINGS force_data_skipping_indices = 'map_fixed_keys_ngrambf'
```

**Comment by tavplubix** [comment]
@kssenii, you forgot to attach the stacktrace:
```
=================================================================
==154==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x604000000000 at pc 0x000032e93ae3 bp 0x7fac53b19e10 sp 0x7fac53b19e08
READ of size 1 at 0x604000000000 thread T3 (TCPHandler)
    #0 0x32e93ae2 in DB::NgramTokenExtractor::nextInString(char const*, unsigned long, unsigned long*, unsigned long*, unsigned long*) const build_docker/../src/Interpreters/ITokenExtractor.cpp:29:56
    #1 0x32e93ae2 in DB::ITokenExtractorHelper<DB::NgramTokenExtractor>::stringToBloomFilter(char const*, unsigned long, DB::BloomFilter&) const build_docker/../src/Interpreters/ITokenExtractor.h:62:68
    #2 0x35b5acc0 in DB::MergeTreeConditionFullText::traverseTreeEquals(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, DB::RPNBuilderTreeNode const&, std::__1::shared_ptr<DB::IDataType const> const&, DB::Field const&, DB::MergeTreeConditionFullText::RPNElement&) build_docker/../src/Storages/MergeTree/MergeTreeIndexFullText.cpp:518:26
    #3 0x35b5685e in DB::MergeTreeConditionFullText::extractAtomFromTree(DB::RPNBuilderTreeNode const&, DB::MergeTreeConditionFullText::RPNElement&) build_docker/../src/Storages/MergeTree/MergeTreeIndexFullText.cpp:403:21
    #4 0x35b64e59 in std::__1::__function::__policy_func<bool (DB::RPNBuilderTreeNode const&, DB::MergeTreeConditionFullText::RPNElement&)>::operator()[abi:v15000](DB::RPNBuilderTreeNode const&, DB::MergeTreeConditionFullText::RPNElement&) const build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:848:16
    #5 0x35b64e59 in std::__1::function<bool (DB::RPNBuilderTreeNode const&, DB::MergeTreeConditionFullText::RPNElement&)>::operator()(DB::RPNBuilderTreeNode const&, DB::MergeTreeConditionFullText::RPNElement&) const build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:1187:12
    #6 0x35b64e59 in DB::RPNBuilder<DB::MergeTreeConditionFullText::RPNElement>::traverseTree(DB::RPNBuilderTreeNode const&) build_docker/../src/Storages/MergeTree/RPNBuilder.h:238:14
    #7 0x35b64bdd in DB::RPNBuilder<DB::MergeTreeConditionFullText::RPNElement>::traverseTree(DB::RPNBuilderTreeNode const&) build_docker/../src/Storages/MergeTree/RPNBuilder.h:225:21
    #8 0x35b64bdd in DB::RPNBuilder<DB::MergeTreeConditionFullText::RPNElement>::traverseTree(DB::RPNBuilderTreeNode const&) build_docker/../src/Storages/MergeTree/RPNBuilder.h:225:21
    #9 0x35b5f609 in DB::RPNBuilder<DB::MergeTreeConditionFullText::RPNElement>::RPNBuilder(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, DB::Block, std::__1::shared_ptr<DB::PreparedSets>, std::__1::function<bool (DB::RPNBuilderTreeNode const&, DB::MergeTreeConditionFullText::RPNElement&)> const&) build_docker/../src/Storages/MergeTree/RPNBuilder.h:204:9
    #10 0x35b51ae0 in DB::MergeTreeConditionFullText::MergeTreeConditionFullText(DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>, DB::Block const&, DB::BloomFilterParameters const&, DB::ITokenExtractor const*) build_docker/../src/Storages/MergeTree/MergeTreeIndexFullText.cpp:177:28
    #11 0x35b5c3e6 in DB::MergeTreeConditionFullText* std::__1::construct_at[abi:v15000]<DB::MergeTreeConditionFullText, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>&, DB::Block const&, DB::BloomFilterParameters const&, DB::ITokenExtractor*, DB::MergeTreeConditionFullText*>(DB::MergeTreeConditionFullText*, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>&, DB::Block const&, DB::BloomFilterParameters const&, DB::ITokenExtractor*&&) build_docker/../contrib/llvm-project/libcxx/include/__memory/construct_at.h:35:48
    #12 0x35b5c3e6 in void std::__1::allocator_traits<std::__1::allocator<DB::MergeTreeConditionFullText>>::construct[abi:v15000]<DB::MergeTreeConditionFullText, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>&, DB::Block const&, DB::BloomFilterParameters const&, DB::ITokenExtractor*, void, void>(std::__1::allocator<DB::MergeTreeConditionFullText>&, DB::MergeTreeConditionFullText*, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>&, DB::Block const&, DB::BloomFilterParameters const&, DB::ITokenExtractor*&&) build_docker/../contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:298:9
    #13 0x35b5c3e6 in std::__1::__shared_ptr_emplace<DB::MergeTreeConditionFullText, std::__1::allocator<DB::MergeTreeConditionFullText>>::__shared_ptr_emplace[abi:v15000]<DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>&, DB::Block const&, DB::BloomFilterParameters const&, DB::ITokenExtractor*>(std::__1::allocator<DB::MergeTreeConditionFullText>, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>&, DB::Block const&, DB::BloomFilterParameters const&, DB::ITokenExtractor*&&) build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:292:9
    #14 0x35b5c3e6 in std::__1::shared_ptr<DB::MergeTreeConditionFullText> std::__1::allocate_shared[abi:v15000]<DB::MergeTreeConditionFullText, std::__1::allocator<DB::MergeTreeConditionFullText>, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>&, DB::Block const&, DB::BloomFilterParameters const&, DB::ITokenExtractor*, void>(std::__1::allocator<DB::MergeTreeConditionFullText> const&, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>&, DB::Block const&, DB::BloomFilterParameters const&, DB::ITokenExtractor*&&) build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:953:55
    #15 0x35b5c3e6 in std::__1::shared_ptr<DB::MergeTreeConditionFullText> std::__1::make_shared[abi:v15000]<DB::MergeTreeConditionFullText, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>&, DB::Block const&, DB::BloomFilterParameters const&, DB::ITokenExtractor*, void>(DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>&, DB::Block const&, DB::BloomFilterParameters const&, DB::ITokenExtractor*&&) build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:962:12
    #16 0x35b5c3e6 in DB::MergeTreeIndexFullText::createIndexCondition(DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>) const build_docker/../src/Storages/MergeTree/MergeTreeIndexFullText.cpp:683:12
    #17 0x35a9ea79 in DB::MergeTreeDataSelectExecutor::filterPartsByPrimaryKeyAndSkipIndexes(std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const>>>&&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const>, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const> const&, DB::KeyCondition const&, DB::MergeTreeReaderSettings const&, Poco::Logger*, unsigned long, std::__1::vector<DB::ReadFromMergeTree::IndexStat, std::__1::allocator<DB::ReadFromMergeTree::IndexStat>>&, bool) build_docker/../src/Storages/MergeTree/MergeTreeDataSelectExecutor.cpp:937:48
    #18 0x37232d54 in DB::ReadFromMergeTree::selectRangesToReadImpl(std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const>>>, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>, unsigned long, std::__1::shared_ptr<std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, long, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, long>>>>, DB::MergeTreeData const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, bool, Poco::Logger*) build_docker/../src/Processors/QueryPlan/ReadFromMergeTree.cpp:1112:36
    #19 0x3722e73e in DB::ReadFromMergeTree::selectRangesToRead(std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const>>>, std::__1::shared_ptr<DB::PrewhereInfo> const&, DB::ActionDAGNodes const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>, unsigned long, std::__1::shared_ptr<std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, long, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, long>>>>, DB::MergeTreeData const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, bool, Poco::Logger*) build_docker/../src/Processors/QueryPlan/ReadFromMergeTree.cpp:968:16
    #20 0x3722d93a in DB::ReadFromMergeTree::selectRangesToRead(std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const>>>) const build_docker/../src/Processors/QueryPlan/ReadFromMergeTree.cpp:900:12
    #21 0x37237273 in DB::ReadFromMergeTree::getAnalysisResult() const build_docker/../src/Processors/QueryPlan/ReadFromMergeTree.cpp:1205:67
    #22 0x372377b4 in DB::ReadFromMergeTree::initializePipeline(DB::QueryPipelineBuilder&, DB::BuildQueryPipelineSettings const&) build_docker/../src/Processors/QueryPlan/ReadFromMergeTree.cpp:1214:19
    #23 0x371b04b5 in DB::ISourceStep::updatePipeline(std::__1::vector<std::__1::unique_ptr<DB::QueryPipelineBuilder, std::__1::default_delete<DB::QueryPipelineBuilder>>, std::__1::allocator<std::__1::unique_ptr<DB::QueryPipelineBuilder, std::__1::default_delete<DB::QueryPipelineBuilder>>>>, DB::BuildQueryPipelineSettings const&) build_docker/../src/Processors/QueryPlan/ISourceStep.cpp:16:5
    #24 0x371fb592 in DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&) build_docker/../src/Processors/QueryPlan/QueryPlan.cpp:187:47
    #25 0x3349f592 in DB::InterpreterSelectWithUnionQuery::execute() build_docker/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:388:31
    #26 0x33d4b55e in DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) build_docker/../src/Interpreters/executeQuery.cpp:713:36
    #27 0x33d4424b in DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) build_docker/../src/Interpreters/executeQuery.cpp:1114:30
    #28 0x36665afd in DB::TCPHandler::runImpl() build_docker/../src/Server/TCPHandler.cpp:378:24
    #29 0x366979c6 in DB::TCPHandler::run() build_docker/../src/Server/TCPHandler.cpp:1945:9
    #30 0x3de3816e in Poco::Net::TCPServerConnection::start() build_docker/../contrib/poco/Net/src/TCPServerConnection.cpp:43:3
    #31 0x3de38ec4 in Poco::Net::TCPServerDispatcher::run() build_docker/../contrib/poco/Net/src/TCPServerDispatcher.cpp:115:20
    #32 0x3e2fd3db in Poco::PooledThread::run() build_docker/../contrib/poco/Foundation/src/ThreadPool.cpp:199:14
    #33 0x3e2f698c in Poco::ThreadImpl::runnableEntry(void*) build_docker/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345:27
    #34 0x7fad885de608 in start_thread /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477:8
    #35 0x7fad88503132 in __clone /build/glibc-SzIz7B/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95

0x604000000000 is located 16 bytes to the left of 40-byte region [0x604000000010,0x604000000038)
allocated by thread T0 here:
    #0 0xea3c58d in operator new(unsigned long) (/workspace/clickhouse+0xea3c58d) (BuildId: 339c7c48af43a50c479b78c564fb283cba16d8e0)
    #1 0x459334d5 in google::protobuf::(anonymous namespace)::GeneratedDatabase() build_docker/../contrib/protobuf/src/google/protobuf/descriptor.cc:1303:34
    #2 0x4593389d in google::protobuf::DescriptorPool::InternalAddGeneratedFile(void const*, int) build_docker/../contrib/protobuf/src/google/protobuf/descriptor.cc:1357:3
    #3 0x45adbb94 in google::protobuf::(anonymous namespace)::AddDescriptorsImpl(google::protobuf::internal::DescriptorTable const*) build_docker/../contrib/protobuf/src/google/protobuf/generated_message_reflection.cc:2767:3
    #4 0x45adbb94 in google::protobuf::(anonymous namespace)::AddDescriptors(google::protobuf::internal::DescriptorTable const*) build_docker/../contrib/protobuf/src/google/protobuf/generated_message_reflection.cc:2778:3
    #5 0x3f5b327c in __cxx_global_var_init build_docker/src/Server/grpc_protos/clickhouse_grpc.pb.cc:464:97
    #6 0x3f5b327c in _GLOBAL__I_000102 build_docker/src/Server/grpc_protos/clickhouse_grpc.pb.cc
    #7 0x45df29cc in __libc_csu_init (/workspace/clickhouse+0x45df29cc) (BuildId: 339c7c48af43a50c479b78c564fb283cba16d8e0)

Thread T3 (TCPHandler) created by T0 here:
    #0 0xe9eb1dc in pthread_create (/workspace/clickhouse+0xe9eb1dc) (BuildId: 339c7c48af43a50c479b78c564fb283cba16d8e0)
    #1 0x3e2f5d7e in Poco::ThreadImpl::startImpl(Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable>>) build_docker/../contrib/poco/Foundation/src/Thread_POSIX.cpp:202:6
    #2 0x3e2f8d5d in Poco::Thread::start(Poco::Runnable&) build_docker/../contrib/poco/Foundation/src/Thread.cpp:128:2
    #3 0x3e2fdd69 in Poco::PooledThread::start() build_docker/../contrib/poco/Foundation/src/ThreadPool.cpp:85:10
    #4 0x3e2fdd69 in Poco::ThreadPool::ThreadPool(int, int, int, int) build_docker/../contrib/poco/Foundation/src/ThreadPool.cpp:252:12
    #5 0x20ade437 in DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) build_docker/../programs/server/Server.cpp:774:22
    #6 0x3de6ef1e in Poco::Util::Application::run() build_docker/../contrib/poco/Util/src/Application.cpp:334:8
    #7 0x20ad2cda in DB::Server::run() build_docker/../programs/server/Server.cpp:474:25
    #8 0x3deb273f in Poco::Util::ServerApplication::run(int, char**) build_docker/../contrib/poco/Util/src/ServerApplication.cpp:611:9
    #9 0x20acafc1 in mainEntryClickHouseServer(int, char**) build_docker/../programs/server/Server.cpp:195:20
    #10 0xea409ad in main build_docker/../programs/main.cpp:482:12
    #11 0x7fad88408082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16

SUMMARY: AddressSanitizer: heap-buffer-overflow build_docker/../src/Interpreters/ITokenExtractor.cpp:29:56 in DB::NgramTokenExtractor::nextInString(char const*, unsigned long, unsigned long*, unsigned long*, unsigned long*) const
Shadow bytes around the buggy address:
  0x0c087fff7fb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c087fff7fc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c087fff7fd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c087fff7fe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c087fff7ff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c087fff8000:[fa]fa 00 00 00 00 00 fa fa fa fd fd fd fd fd fa
  0x0c087fff8010: fa fa fd fd fd fd fd fd fa fa 00 00 00 00 00 00
  0x0c087fff8020: fa fa fd fd fd fd fd fd fa fa fd fd fd fd fd fd
  0x0c087fff8030: fa fa fa fa fa fa fa fa fa fa 00 00 00 00 00 00
  0x0c087fff8040: fa fa 00 00 00 00 00 00 fa fa 00 00 00 00 00 00
  0x0c087fff8050: fa fa 00 00 00 00 00 00 fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==154==ABORTING
```

From the stack trace we can see that the root cause of the issue is likely to be in `MergeTreeConditionFullText`, not in `NgramTokenExtractor`. I'm pretty sure that it's a kind of type mismatch and `const_value` is not a string, so `const_value.get<String>()` returns an invalid reference.

cc: @kitaisreal
