### ISSUE TITLE
Segmentation fault DB::DatabaseOnDisk::renameTable

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#45554]
https://s3.amazonaws.com/clickhouse-test-reports/0/cb1e8afda634c3bb997944c89ab4ba3aff035fa0/stress_test__debug_/fatal_messages.txt

```
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.24 13:56:02.691720 [ 42972 ] {} <Fatal> BaseDaemon: (version 22.13.1.1 (official build), build id: 5B74AA3F1FF49B536C46AA851FC64A12E41DE5BF) (from thread 2183) (query_id: 24b65bb8-0392-492b-8a3d-41ab5e2e6125) (query: RENAME TABLE x TO y;) Received signal Segmentation fault (11)
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.24 13:56:02.692012 [ 42972 ] {} <Fatal> BaseDaemon: Address: 0x128 Access: read. Address not mapped to object.
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.24 13:56:02.692268 [ 42972 ] {} <Fatal> BaseDaemon: Stack trace: 0x2a65f18c 0x2a65c296 0x2a65cb52 0x289e6da2 0x29957cae 0x29ad3d06 0x29ad2bd9 0x2a06b36a 0x2a067304 0x2ba2c566 0x2ba3c8a5 0x305f9ad9 0x305fa31c 0x30849534 0x308462da 0x308450be 0x7f30d506d609 0x7f30d4f92133
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.24 13:56:04.399123 [ 42972 ] {} <Fatal> BaseDaemon: 4. /build/build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:815: std::__1::shared_ptr<DB::RWLockImpl>::operator->[abi:v15000]() const @ 0x2a65f18c in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.24 13:56:04.750793 [ 42972 ] {} <Fatal> BaseDaemon: 5. /build/build_docker/../src/Storages/IStorage.cpp:38: DB::IStorage::tryLockTimed(std::__1::shared_ptr<DB::RWLockImpl> const&, DB::RWLockImpl::Type, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l>> const&) const @ 0x2a65c296 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.24 13:56:05.055856 [ 42972 ] {} <Fatal> BaseDaemon: 6. /build/build_docker/../src/Storages/IStorage.cpp:94: DB::IStorage::lockExclusively(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l>> const&) @ 0x2a65cb52 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.24 13:56:05.617061 [ 42972 ] {} <Fatal> BaseDaemon: 7. /build/build_docker/../src/Databases/DatabaseOnDisk.cpp:382: DB::DatabaseOnDisk::renameTable(std::__1::shared_ptr<DB::Context const>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, DB::IDatabase&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool, bool) @ 0x289e6da2 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.24 13:56:05.816000 [ 42972 ] {} <Fatal> BaseDaemon: 8. /build/build_docker/../src/Databases/DatabaseLazy.cpp:95: DB::DatabaseLazy::renameTable(std::__1::shared_ptr<DB::Context const>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, DB::IDatabase&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool, bool) @ 0x29957cae in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.24 13:56:06.127707 [ 42972 ] {} <Fatal> BaseDaemon: 9. /build/build_docker/../src/Interpreters/InterpreterRenameQuery.cpp:132: DB::InterpreterRenameQuery::executeToTables(DB::ASTRenameQuery const&, std::__1::vector<DB::RenameDescription, std::__1::allocator<DB::RenameDescription>> const&, std::__1::map<DB::UniqueTableName, std::__1::unique_ptr<DB::DDLGuard, std::__1::default_delete<DB::DDLGuard>>, std::__1::less<DB::UniqueTableName>, std::__1::allocator<std::__1::pair<DB::UniqueTableName const, std::__1::unique_ptr<DB::DDLGuard, std::__1::default_delete<DB::DDLGuard>>>>>&) @ 0x29ad3d06 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.24 13:56:06.221543 [ 42972 ] {} <Fatal> BaseDaemon: 10. /build/build_docker/../src/Interpreters/InterpreterRenameQuery.cpp:75: DB::InterpreterRenameQuery::execute() @ 0x29ad2bd9 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.24 13:56:06.936129 [ 42972 ] {} <Fatal> BaseDaemon: 11. /build/build_docker/../src/Interpreters/executeQuery.cpp:715: DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x2a06b36a in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.24 13:56:07.255362 [ 42972 ] {} <Fatal> BaseDaemon: 12. /build/build_docker/../src/Interpreters/executeQuery.cpp:1169: DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x2a067304 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.24 13:56:07.936411 [ 42972 ] {} <Fatal> BaseDaemon: 13. /build/build_docker/../src/Server/TCPHandler.cpp:378: DB::TCPHandler::runImpl() @ 0x2ba2c566 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.24 13:56:08.305030 [ 42972 ] {} <Fatal> BaseDaemon: 14. /build/build_docker/../src/Server/TCPHandler.cpp:1945: DB::TCPHandler::run() @ 0x2ba3c8a5 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.24 13:56:08.347543 [ 42972 ] {} <Fatal> BaseDaemon: 15. /build/build_docker/../contrib/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x305f9ad9 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.24 13:56:08.436507 [ 42972 ] {} <Fatal> BaseDaemon: 16. /build/build_docker/../contrib/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x305fa31c in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.24 13:56:08.587554 [ 42972 ] {} <Fatal> BaseDaemon: 17. /build/build_docker/../contrib/poco/Foundation/src/ThreadPool.cpp:199: Poco::PooledThread::run() @ 0x30849534 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.24 13:56:08.658776 [ 42972 ] {} <Fatal> BaseDaemon: 18. /build/build_docker/../contrib/poco/Foundation/src/Thread.cpp:56: Poco::(anonymous namespace)::RunnableHolder::run() @ 0x308462da in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.24 13:56:08.700066 [ 42972 ] {} <Fatal> BaseDaemon: 19. /build/build_docker/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345: Poco::ThreadImpl::runnableEntry(void*) @ 0x308450be in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.24 13:56:08.700429 [ 42972 ] {} <Fatal> BaseDaemon: 20. ? @ 0x7f30d506d609 in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.24 13:56:08.700686 [ 42972 ] {} <Fatal> BaseDaemon: 21. __clone @ 0x7f30d4f92133 in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.24 13:56:10.150862 [ 42972 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 0C2340F331E012C7DD863C6621B0DAE2)
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.24 13:57:03.247225 [ 1546 ] {} <Fatal> Application: Child process was terminated by signal 11.
```

**Comment by qoega** [comment]
Similar to 
https://s3.amazonaws.com/clickhouse-test-reports/0/ee31da9e1e4eaec79f5967249f424ce9105110bc/stress_test__ubsan_.html
```
../src/Databases/DatabaseOnDisk.cpp:380:25: runtime error: member call on null pointer of type 'DB::IStorage'
    #0 0x2db08f5a in DB::DatabaseOnDisk::renameTable(std::__1::shared_ptr<DB::Context const>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, DB::IDatabase&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool, bool) build_docker/../src/Databases/DatabaseOnDisk.cpp:380:25
    #1 0x2eb5bec0 in DB::InterpreterRenameQuery::executeToTables(DB::ASTRenameQuery const&, std::__1::vector<DB::RenameDescription, std::__1::allocator<DB::RenameDescription>> const&, std::__1::map<DB::UniqueTableName, std::__1::unique_ptr<DB::DDLGuard, std::__1::default_delete<DB::DDLGuard>>, std::__1::less<DB::UniqueTableName>, std::__1::allocator<std::__1::pair<DB::UniqueTableName const, std::__1::unique_ptr<DB::DDLGuard, std::__1::default_delete<DB::DDLGuard>>>>>&) build_docker/../src/Interpreters/InterpreterRenameQuery.cpp:132:23
    #2 0x2eb5ad81 in DB::InterpreterRenameQuery::execute() build_docker/../src/Interpreters/InterpreterRenameQuery.cpp:75:16
    #3 0x2f0b8a19 in DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) build_docker/../src/Interpreters/executeQuery.cpp:715:36
    #4 0x2f0b450b in DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) build_docker/../src/Interpreters/executeQuery.cpp:1169:30
    #5 0x305d4c6f in DB::TCPHandler::runImpl() build_docker/../src/Server/TCPHandler.cpp:378:24
    #6 0x305f65f5 in DB::TCPHandler::run() build_docker/../src/Server/TCPHandler.cpp:1945:9
    #7 0x3166e7cb in Poco::Net::TCPServerConnection::start() build_docker/../contrib/poco/Net/src/TCPServerConnection.cpp:43:3
    #8 0x3166ecb9 in Poco::Net::TCPServerDispatcher::run() build_docker/../contrib/poco/Net/src/TCPServerDispatcher.cpp:115:20
    #9 0x317e6746 in Poco::PooledThread::run() build_docker/../contrib/poco/Foundation/src/ThreadPool.cpp:199:14
    #10 0x317e422e in Poco::ThreadImpl::runnableEntry(void*) build_docker/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345:27
    #11 0x7f929277e608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8608) (BuildId: 7b4536f41cdaa5888408e82d0836e33dcf436466)
    #12 0x7f92926a3132 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x11f132) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../src/Databases/DatabaseOnDisk.cpp:380:25 in 
```
