### ISSUE TITLE
msan assert: use-of-uninitialized-value in joinBlockImpl()

### ISSUE THREAD

**Issue by rschu1ze** [ClickHouse/ClickHouse#46965]
```
==1561==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x4606e0e9 in void DB::HashJoin::joinBlockImpl<(DB::JoinKind)1, (DB::JoinStrictness)5, DB::HashJoin::MapsTemplate<DB::RowRef>>(DB::Block&, DB::Block const&, std::__1::vector<DB::HashJoin::MapsTemplate<DB::RowRef> const*, std::__1::allocator<DB::HashJoin::MapsTemplate<DB::RowRef> const*>> const&, bool) const build_docker/../src/Interpreters/HashJoin.cpp:1496:9
    #1 0x45092ed2 in auto DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4::operator()<std::__1::integral_constant<DB::JoinKind, (DB::JoinKind)1>, std::__1::integral_constant<DB::JoinStrictness, (DB::JoinStrictness)5>, std::__1::vector<DB::HashJoin::MapsTemplate<DB::RowRef> const*, std::__1::allocator<DB::HashJoin::MapsTemplate<DB::RowRef> const*>>>(std::__1::integral_constant<DB::JoinKind, (DB::JoinKind)1>, std::__1::integral_constant<DB::JoinStrictness, (DB::JoinStrictness)5>, std::__1::vector<DB::HashJoin::MapsTemplate<DB::RowRef> const*, std::__1::allocator<DB::HashJoin::MapsTemplate<DB::RowRef> const*>>&) const build_docker/../src/Interpreters/HashJoin.cpp:1745:13
    #2 0x45092ed2 in auto bool DB::joinDispatch<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4>(DB::JoinKind, DB::JoinStrictness, std::__1::vector<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*, std::__1::allocator<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*>>&, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4&&)::'lambda'(std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>)::operator()<std::__1::integral_constant<int, 4>>(std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>) const build_docker/../src/Interpreters/joinDispatch.h:121:13
    #3 0x45092ed2 in bool func_wrapper<bool DB::joinDispatch<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4>(DB::JoinKind, DB::JoinStrictness, std::__1::vector<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*, std::__1::allocator<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*>>&, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4&&)::'lambda'(std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>), std::__1::integral_constant<int, 4>>(std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>&&, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4&&) build_docker/../base/base/constexpr_helpers.h:18:16
    #4 0x45092ed2 in bool static_for_impl<int, 0, bool DB::joinDispatch<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4>(DB::JoinKind, DB::JoinStrictness, std::__1::vector<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*, std::__1::allocator<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*>>&, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4&&)::'lambda'(std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>), 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23>(bool DB::joinDispatch<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4>(DB::JoinKind, DB::JoinStrictness, std::__1::vector<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*, std::__1::allocator<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*>>&, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4&&)::'lambda'(std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>)&&, std::__1::integer_sequence<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23>) build_docker/../base/base/constexpr_helpers.h:24:13
    #5 0x45092ed2 in bool static_for<0, 24, bool DB::joinDispatch<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4>(DB::JoinKind, DB::JoinStrictness, std::__1::vector<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*, std::__1::allocator<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*>>&, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4&&)::'lambda'(std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>)>(bool DB::joinDispatch<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4>(DB::JoinKind, DB::JoinStrictness, std::__1::vector<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*, std::__1::allocator<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*>>&, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4&&)::'lambda'(std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>)&&) build_docker/../base/base/constexpr_helpers.h:31:12
    #6 0x45092ed2 in bool DB::joinDispatch<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4>(DB::JoinKind, DB::JoinStrictness, std::__1::vector<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*, std::__1::allocator<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*>>&, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4&&) build_docker/../src/Interpreters/joinDispatch.h:106:12
    #7 0x45092ed2 in DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&) build_docker/../src/Interpreters/HashJoin.cpp:1743:13
    #8 0x45052573 in DB::GraceHashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&) build_docker/../src/Interpreters/GraceHashJoin.cpp:428:16
    #9 0x4c47d5d7 in DB::JoiningTransform::readExecute(DB::Chunk&) build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h
    #10 0x4c47a706 in DB::JoiningTransform::transform(DB::Chunk&) build_docker/../src/Processors/Transforms/JoiningTransform.cpp:191:17
    #11 0x4c478cac in DB::JoiningTransform::work() build_docker/../src/Processors/Transforms/JoiningTransform.cpp:125:9
    #12 0x4bb39b7d in DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*) build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:47:26
    #13 0x4bb39b7d in DB::ExecutionThreadContext::executeTask() build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:92:9
    #14 0x4baffdbc in DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:229:26
    #15 0x4bb05bed in DB::PipelineExecutor::executeSingleThread(unsigned long) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:195:5
    #16 0x4bb05bed in DB::PipelineExecutor::spawnThreads()::$_0::operator()() const build_docker/../src/Processors/Executors/PipelineExecutor.cpp:320:17
    #17 0x4bb05bed in decltype(std::declval<DB::PipelineExecutor::spawnThreads()::$_0&>()()) std::__1::__invoke[abi:v15000]<DB::PipelineExecutor::spawnThreads()::$_0&>(DB::PipelineExecutor::spawnThreads()::$_0&) build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #18 0x4bb05bed in decltype(auto) std::__1::__apply_tuple_impl[abi:v15000]<DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&>(DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>) build_docker/../contrib/llvm-project/libcxx/include/tuple:1789:1
    #19 0x4bb05bed in decltype(auto) std::__1::apply[abi:v15000]<DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&>(DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&) build_docker/../contrib/llvm-project/libcxx/include/tuple:1798:1
    #20 0x4bb05bed in ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()::operator()() build_docker/../src/Common/ThreadPool.h:210:13
    #21 0x4bb05bed in decltype(std::declval<DB::PipelineExecutor::spawnThreads()::$_0>()()) std::__1::__invoke[abi:v15000]<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&>(DB::PipelineExecutor::spawnThreads()::$_0&&) build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #22 0x4bb05bed in void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&) build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:479:9
    #23 0x4bb05bed in std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'(), void ()>::operator()[abi:v15000]() build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:235:12
    #24 0x4bb05bed in void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:716:16
    #25 0x29784c2c in std::__1::__function::__policy_func<void ()>::operator()[abi:v15000]() const build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:848:16
    #26 0x29784c2c in std::__1::function<void ()>::operator()() const build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:1187:12
    #27 0x29784c2c in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) build_docker/../src/Common/ThreadPool.cpp:315:17
    #28 0x29793b42 in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const build_docker/../src/Common/ThreadPool.cpp:145:73
    #29 0x29793b42 in decltype(std::declval<void>()()) std::__1::__invoke[abi:v15000]<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&) build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #30 0x29793b42 in void std::__1::__thread_execute[abi:v15000]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>&, std::__1::__tuple_indices<>) build_docker/../contrib/llvm-project/libcxx/include/thread:284:5
    #31 0x29793b42 in void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) build_docker/../contrib/llvm-project/libcxx/include/thread:295:5
    #32 0x7f894f19c608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8608) (BuildId: 7b4536f41cdaa5888408e82d0836e33dcf436466)
    #33 0x7f894f0c1132 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x11f132) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)

  Uninitialized value was created by a heap deallocation
```

**Describe the bug**
[Here](https://s3.amazonaws.com/clickhouse-test-reports/46940/22d09caea2fadce928094aac6ce902dc7f1c6933/stress_test__msan_/stderr.log) / [here](https://s3.amazonaws.com/clickhouse-test-reports/46940/22d09caea2fadce928094aac6ce902dc7f1c6933/stress_test__msan_.html) / [here](https://github.com/ClickHouse/ClickHouse/pull/46940)

**How to reproduce**
?

**Comment by tavplubix** [comment]
cc: @vdimir

**Comment by vdimir** [comment]
Repro for issue from the original comment

```sql
SELECT number FROM system.numbers SEMI LEFT JOIN (SELECT number, ['test'] FROM system.numbers LIMIT 1) js2 USING (number) LIMIT 1 SETTINGS join_algorithm = 'grace_hash';
```


Fixed in https://github.com/ClickHouse/ClickHouse/pull/47153 (compared commits https://github.com/ClickHouse/ClickHouse/commit/4f048ce535e80c9999a7e05f6e08d5fbe4b3c50c - crashes, https://github.com/ClickHouse/ClickHouse/commit/b298fbeecc74263f2e90b9901f3859b31098c05d - ok)

**Comment by vdimir** [comment]
There's same query in logs here

> [s3.amazonaws.com/clickhouse-test-reports/47456/2fbb3660de4682e29c4501a25bb250f463c5f04c/upgrade_check__asan_/gdb.log](https://s3.amazonaws.com/clickhouse-test-reports/47456/2fbb3660de4682e29c4501a25bb250f463c5f04c/upgrade_check__asan_/gdb.log)

```
 ~ % curl 'https://s3.amazonaws.com/clickhouse-test-reports/47456/2fbb3660de4682e29c4501a25bb250f463c5f04c/upgrade_check__asan_/clickhouse-server.stress.log.zst' | zstd -d | grep -i 'execute.*JOIN' | tail -5


2023.03.11 06:24:54.258530 [ 82727 ] {c8e1b8a3-af2d-42aa-b34b-ef6c45ed8aff} <Debug> executeQuery: (from [::1]:45202) (comment: 01783_merge_engine_join_key_condition.sql) DROP DATABASE IF EXISTS test_2gvtu1ow  (stage: Complete)
2023.03.11 06:24:55.167556 [ 175897 ] {50cc5a43-9145-43d5-a42e-0ca414732384} <Debug> executeQuery: (from [::1]:45564) (comment: 01410_nullable_key_more_tests.sh) select * from table_with_nullable_keys where nullable_misc = (select (randomPrintableASCII(30), rand())) or nullable_misc in (select arrayJoin([(randomPrintableASCII(30), null), (null, rand())])) (stage: Complete)
2023.03.11 06:24:55.686059 [ 175897 ] {e9f640c2-f636-4cf8-9bf8-6845b6924d48} <Debug> executeQuery: (from [::1]:54102) (comment: 00956_join_use_nulls_with_array_column.sql) SET join_use_nulls = 1; (stage: Complete)
2023.03.11 06:24:55.687131 [ 175897 ] {556fb5ce-936f-443c-9bd7-100e47e89e20} <Debug> executeQuery: (from [::1]:54102) (comment: 00956_join_use_nulls_with_array_column.sql) SELECT number FROM system.numbers SEMI LEFT JOIN (SELECT number, ['test'] FROM system.numbers LIMIT 1) js2 USING (number) LIMIT 1; (stage: Complete)
2023.03.11 06:24:55.694721 [ 175897 ] {135e84c7-5241-470a-85be-db120dd86ddd} <Debug> executeQuery: (from [::1]:54102) (comment: 00956_join_use_nulls_with_array_column.sql) SELECT number FROM system.numbers ANY LEFT JOIN (SELECT number, ['test'] FROM system.numbers LIMIT 1) js2 USING (number) LIMIT 1; (stage: Complete)
```

But actually mentioned patch is applied on failed commit 
```
$ git show 2fbb3660de4682e29c4501a25bb250f463c5f04c:src/Processors/Transforms/JoiningTransform.cpp | grep -A 5 'DelayedJoinedBlocksTransform::work'
void DelayedJoinedBlocksTransform::work()
{
    if (finished)
        return;

    delayed_blocks = join->getDelayedBlocks();
```

And it's unclear which query caused segfault because there are no `Fatal`s in logs, only in gdb.log without mentioning query. Needs further investigation.
