### ISSUE TITLE
com.clickhouse.client.ClickHouseException: 拒绝连接 (Connection refused), server ClickHouseNode [uri=http://localhost:0/default]@281105551(failover=2, retry=0)

### ISSUE THREAD

**Issue by zhyan099** [ClickHouse/ClickHouse#47969]
I use clickhouse-http-client-0.3.2-patch11.jar connect to clickhouse cluster，But the connection reported an error. 
Here is my code：
`ClickHouseNodes servers = ClickHouseNodes.of(
                "jdbc:ch:http://192.168.139.61:8123,192.168.139.62:8123,192.168.139.63:8123/harbintaxi"
                        + "?load_balancing_policy=random&health_check_interval=5000&failover=2");`
`try (ClickHouseClient client = ClickHouseClient.newInstance(ClickHouseProtocol.HTTP); ClickHouseResponse response = client.connect(servers).set("send_progress_in_http_headers", 1).query(insertSql).execute().get();
                ) {
            ClickHouseResponseSummary summary = response.getSummary();
            logger.info("success:" + summary.getWrittenRows());
        }`
-----------------------------------------------------------------------------------------------------------------------------------------------
`[2023-03-24 17:49:44.530][D][uler1][ClickHouseNode.34][][]Failed to probe localhost:0
java.net.ConnectException: 拒绝连接 (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[2023-03-24 17:49:44.531][D][xec-1][ClickHouseNodeSelector.36][cf4ff3dfff180a94][8mMz2Gy30S]Checking [com.clickhouse.client.cli.ClickHouseCommandLineClient@78030418] against [HTTP]...
[2023-03-24 17:49:44.532][D][uler1][ClickHouseNodeSelector.36][][]Checking [com.clickhouse.client.cli.ClickHouseCommandLineClient@11400d29] against [HTTP]...
[2023-03-24 17:49:44.533][D][xec-1][ClickHouseNodeSelector.36][cf4ff3dfff180a94][8mMz2Gy30S]Checking [com.clickhouse.client.grpc.ClickHouseGrpcClient@740a853b] against [HTTP]...
[2023-03-24 17:49:44.533][D][uler1][ClickHouseNodeSelector.36][][]Checking [com.clickhouse.client.grpc.ClickHouseGrpcClient@755e186f] against [HTTP]...
[2023-03-24 17:49:44.534][D][uler1][ClickHouseNodeSelector.36][][]Checking [com.clickhouse.client.http.ClickHouseHttpClient@2a201a48] against [HTTP]...
[2023-03-24 17:49:44.534][D][xec-1][ClickHouseNodeSelector.36][cf4ff3dfff180a94][8mMz2Gy30S]Checking [com.clickhouse.client.http.ClickHouseHttpClient@19c15007] against [HTTP]...
[2023-03-24 17:49:44.538][D][uler1][AbstractClient.36][][]Connecting to: ClickHouseNode [uri=http://localhost:0/default]@281105551
[2023-03-24 17:49:44.538][D][xec-1][ClickHouseNode.34][cf4ff3dfff180a94][8mMz2Gy30S]Failed to probe localhost:0
java.net.ConnectException: 拒绝连接 (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[2023-03-24 17:49:44.546][D][rker1][AbstractClient.36][][]Connecting to: ClickHouseNode [uri=http://localhost:0/default]@281105551
[2023-03-24 17:49:44.559][D][uler1][AbstractClient.36][][]Connection established: com.clickhouse.client.http.HttpUrlConnectionImpl@6e86be21
[2023-03-24 17:49:44.559][D][rker1][AbstractClient.36][][]Connection established: com.clickhouse.client.http.HttpUrlConnectionImpl@30ba7b5a`

**Comment by Alex-Cheng** [comment]
It seems that your configuration for JDBC is not correct, because the error message "Connecting to: ClickHouseNode [uri=http://localhost:0/default]@281105551". The error message shows that the code tries to connect localhost on port 0, which is impossible(we cannot use port 0, better use port number greater than 1000).

**Comment by mua-haha** [comment]
既然你指定了http协议，url用http开头就行。
ClickHouseNodes servers = ClickHouseNodes.of( "http://192.168.139.61:8123,192.168.139.62:8123,192.168.139.63:8123/harbintaxi" + "?load_balancing_policy=random&health_check_interval=5000&failover=2");

官网给的例子 有那么一点confusing
