### ISSUE TITLE
coredump at `DataTypeString::serializeBinaryBulk`

### ISSUE THREAD

**Issue by MrSsunlight** [ClickHouse/ClickHouse#48270]
clickhouse version: 20.3.11.97

gdb info:
```bash
(gdb) 
.......
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd6bf5700 (LWP 103631)]
0x000000000ba97830 in memcpy ()
(gdb) bt
#0  0x000000000ba97830 in memcpy ()
#1  0x0000000008a07548 in DB::DataTypeString::serializeBinaryBulk(DB::IColumn const&, DB::WriteBuffer&, unsigned long, unsigned long) const ()
#2  0x0000000008f63c95 in DB::MergeTreeDataPartWriterWide::writeColumn(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::IDataType const&, DB::IColumn const&, std::__1::set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&) ()
#3  0x0000000008f646eb in DB::MergeTreeDataPartWriterWide::write(DB::Block const&, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul> const*, DB::Block const&, DB::Block const&) ()
#4  0x0000000008fdee72 in DB::MergedBlockOutputStream::writeImpl(DB::Block const&, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul> const*) ()
#5  0x0000000008f2fd45 in DB::MergeTreeDataMergerMutator::mergePartsToTemporaryPart(DB::FutureMergedMutatedPart const&, DB::MergeListEntry&, DB::TableStructureReadLockHolder&, long, std::__1::unique_ptr<DB::IReservation, std::__1::default_delete<DB::IReservation> > const&,bool, bool) ()
#6  0x0000000008e24b53 in DB::StorageReplicatedMergeTree::tryExecuteMerge(DB::ReplicatedMergeTreeLogEntry const&) ()
#7  0x0000000008e51b5b in DB::StorageReplicatedMergeTree::executeLogEntry(DB::ReplicatedMergeTreeLogEntry&) ()
#8  0x0000000008e51f9c in DB::StorageReplicatedMergeTree::queueTask()::{lambda(std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)#2}::operator()(std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&) const [clone .isra.0] ()
#9  0x000000000901a1de in DB::ReplicatedMergeTreeQueue::processEntry(std::__1::function<std::__1::shared_ptr<zkutil::ZooKeeper> ()>, std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&, std::__1::function<bool (std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>)
    ()
#10 0x0000000008e08e37 in DB::StorageReplicatedMergeTree::queueTask() ()
#11 0x0000000008ec1481 in DB::BackgroundProcessingPool::threadFunction() ()
#12 0x0000000008ec1e2d in _ZZN20ThreadFromGlobalPoolC4IZN2DB24BackgroundProcessingPoolC4EiRKNS2_12PoolSettingsEPKcS7_EUlvE_JEEEOT_DpOT0_ENKUlvE_clEv ()
#13 0x0000000005013ead in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) ()
#14 0x000000000501251f in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::{lambda()#3}> >(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::{lambda()#3}>) ()
#15 0x00007ffff72eeea5 in start_thread (arg=0x7fffd6bf5700) at pthread_create.c:307
#16 0x00007ffff7b0b8dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

```bash
(gdb) f 1
#1  0x0000000008a07548 in DB::DataTypeString::serializeBinaryBulk(DB::IColumn const&, DB::WriteBuffer&, unsigned long, unsigned long) const ()

(gdb) info frame
Stack level 1, frame at 0x7fffd6bee8c0:
rip = 0x8a07548 in DB::DataTypeString::serializeBinaryBulk(DB::IColumn const&, DB::WriteBuffer&, unsigned long, unsigned long) const; saved rip 0x8f63c95
called by frame at 0x7fffd6beea70, caller of frame at 0x7fffd6bee840
Arglist at 0x7fffd6bee838, args:
Locals at 0x7fffd6bee838, Previous frame's sp is 0x7fffd6bee8c0
Saved registers:
  rbx at 0x7fffd6bee888, rbp at 0x7fffd6bee890, r12 at 0x7fffd6bee898, r13 at 0x7fffd6bee8a0, r14 at 0x7fffd6bee8a8, r15 at 0x7fffd6bee8b0, rip at 0x7fffd6bee8b8
```

**Comment by tavplubix** [comment]
> clickhouse version: 20.3.11.97

This version is 3 years old, it's not been supported for 2 years already, you must upgrade.
