### ISSUE TITLE
Partition intersects next part exception

### ISSUE THREAD

**Issue by baldurgaldur** [ClickHouse/ClickHouse#4833]
During a call to docker container with the clickhouse server running version 1.1.54394.3 the following command:
`OPTIMIZE table transactions PARTITION 201712"`

Results in this exception being logged:
```java
nested exception is ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 49, host: clickhouse, port: 8123; Code: 49, e.displayText() = DB::Exception: Part 20181201_20181231_1950_4223_11 intersects next part 20181201_20181231_1950_5084_8 (state Committed). It is a bug., e.what() = DB::Exception
myproject.2019-03-28-12.log-
myproject.2019-03-28-12.log-       at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:89)
myproject.2019-03-28-12.log-       at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
myproject.2019-03-28-12.log-       at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
myproject.2019-03-28-12.log-       at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1402)
```

The container is still up, I can query it for data. 

system.tables contains the **20181201_20181231_1950_5084_8** partition but not **20181201_20181231_1950_4223_11**. 

I know this because the following query:
`select * from system.parts where name = '20181201_20181231_1950_5084_8'` returns a result
The partition is even active.

Should I be worried?

**Comment by yuzhichang** [comment]
I noticed similar problem on system.query_log table.

```
2019.11.18 13:09:31.397505 [ 13 ] {} <Debug> system.query_log (MergerMutator): Selected 5 parts from 20191118_34225_34295_18 to 20191118_34299_34299_0_34299
2019.11.18 13:09:31.397624 [ 13 ] {} <Debug> DiskSpaceMonitor: Reserving 1.00 MiB on disk `default`, having unreserved 3.04 TiB.
2019.11.18 13:09:31.397669 [ 13 ] {} <Debug> system.query_log (MergerMutator): Merging 5 parts: from 20191118_34225_34295_18 to 20191118_34299_34299_0_34299 into tmp_merge_20191118_34225_342
99_19
2019.11.18 13:09:31.403590 [ 13 ] {} <Debug> system.query_log (MergerMutator): Selected MergeAlgorithm: Horizontal
2019.11.18 13:09:31.403735 [ 13 ] {} <Trace> MergeTreeSequentialBlockInputStream: Reading 2 marks from part 20191118_34225_34295_18, total 298 rows starting from the beginning of the part
2019.11.18 13:09:31.406493 [ 13 ] {} <Trace> MergeTreeSequentialBlockInputStream: Reading 2 marks from part 20191118_34296_34296_0_34296, total 1 rows starting from the beginning of the part
2019.11.18 13:09:31.408176 [ 13 ] {} <Trace> MergeTreeSequentialBlockInputStream: Reading 2 marks from part 20191118_34297_34297_0_34297, total 1 rows starting from the beginning of the part2019.11.18 13:09:31.409870 [ 13 ] {} <Trace> MergeTreeSequentialBlockInputStream: Reading 2 marks from part 20191118_34298_34298_0_34298, total 1 rows starting from the beginning of the part
2019.11.18 13:09:31.411707 [ 13 ] {} <Trace> MergeTreeSequentialBlockInputStream: Reading 2 marks from part 20191118_34299_34299_0_34299, total 1 rows starting from the beginning of the part2019.11.18 13:09:31.503430 [ 13 ] {} <Debug> system.query_log (MergerMutator): Merge sorted 302 rows, containing 42 columns (42 merged, 0 gathered) in 0.11 sec., 2856.04 rows/sec., 3.20 MB/s
ec.
2019.11.18 13:09:31.507158 [ 13 ] {} <Trace> system.query_log: Renaming temporary part tmp_merge_20191118_34225_34299_19 to 20191118_34225_34299_19.
2019.11.18 13:09:38.868395 [ 13 ] {} <Error> void DB::BackgroundProcessingPool::threadFunction(): Code: 49, e.displayText() = DB::Exception: Part 20191118_34225_34299_19 intersects next part 20191118_34296_34296_0_34296 (state Committed). It is a bug., Stack trace:

0. 0x5597602204c0 StackTrace::StackTrace() /bigdata/zhichyu/1/ClickHouse/obj-x86_64-linux-gnu/../dbms/src/Common/StackTrace.cpp:228
1. 0x559760220295 DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) /bigdata/zhichyu/1/ClickHouse/obj-x86_64-linux-gnu/../dbms/src/Common/Exception.h:27
2. 0x5597600627e6 DB::MergeTreeData::getActivePartsToReplace(DB::MergeTreePartInfo const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<DB::MergeTreeDataPart const>&, std::unique_lock<std::mutex>&) const [clone .cold] /usr/include/c++/9/bits/basic_string.h:222
3. 0x55976376eeac DB::MergeTreeData::renameTempPartAndReplace(std::shared_ptr<DB::MergeTreeDataPart>&, SimpleIncrement*, DB::MergeTreeData::Transaction*, std::unique_lock<std::mutex>&, std::vector<std::shared_ptr<DB::MergeTreeDataPart const>, std::allocator<std::shared_ptr<DB::MergeTreeDataPart const> > >*) /bigdata/zhichyu/1/ClickHouse/obj-x86_64-linux-gnu/../dbms/src/Storages/MergeTree/MergeTreeData.cpp:2065
4. 0x55976376f6ed DB::MergeTreeData::renameTempPartAndReplace(std::shared_ptr<DB::MergeTreeDataPart>&, SimpleIncrement*, DB::MergeTreeData::Transaction*) /usr/include/c++/9/bits/unique_lock.h:105
5. 0x55976379029f DB::MergeTreeDataMergerMutator::renameMergedTemporaryPart(std::shared_ptr<DB::MergeTreeDataPart>&, std::vector<std::shared_ptr<DB::MergeTreeDataPart const>, std::allocator<std::shared_ptr<DB::MergeTreeDataPart const> > > const&, DB::MergeTreeData::Transaction*) /bigdata/zhichyu/1/ClickHouse/obj-x86_64-linux-gnu/../dbms/src/Storages/MergeTree/MergeTreeDataMergerMutator.cpp:1196
6. 0x5597636b163b DB::StorageMergeTree::merge(bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) /usr/include/c++/9/bits/shared_ptr_base.h:729
7. 0x5597636b65b4 DB::StorageMergeTree::mergeMutateTask() /usr/include/c++/9/bits/basic_string.h:222
8. 0x559763743f84 DB::BackgroundProcessingPool::threadFunction() /usr/include/c++/9/bits/std_function.h:688
9. 0x5597637448fa ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::{lambda()#1}>(DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::{lambda()#1}&&)::{lambda()#1}::operator()() const /bigdata/zhichyu/1/ClickHouse/obj-x86_64-linux-gnu/../dbms/src/Common/ThreadPool.h:150
10. 0x55976026942c ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>) /usr/include/c++/9/bits/atomic_base.h:551
11. 0x559764d6d430 execute_native_thread_routine /usr/lib/debug/usr/bin/clickhouse
12. 0x7f790073ddd5 start_thread /usr/lib64/libpthread-2.17.so
13. 0x7f790005aead clone /usr/lib64/libc-2.17.so
 (version 19.15.3.6)

```

**Comment by blinkov** [comment]
@baldurgaldur, do you have any further questions?

**Comment by alexey-milovidov** [comment]
@baldurgaldur The old version 1.1.54394 had some bugs that may relate to this behaviour.

@yuzhichang You should not worry about this issue if it happens only on system tables.
It may happen due to incorrect set of parts in filesystem that may appear after server restart.
The system will continue to work and system tables will continue to be queryable.
