### ISSUE TITLE
use-of-uninitialized-value in QueryCache::Writer

### ISSUE THREAD

**Issue by Avogar** [ClickHouse/ClickHouse#48385]
https://s3.amazonaws.com/clickhouse-test-reports/48122/e1e508f8ec200a0e5acd7e33726c36303032972d/stress_test__msan_.html

```
==1656==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x64215a7b in LZ4_count build_docker/./contrib/lz4/lib/lz4.c:625:13
    #1 0x64215a7b in LZ4_compress_generic_validated build_docker/./contrib/lz4/lib/lz4.c:1103:29
    #2 0x64215a7b in LZ4_compress_generic build_docker/./contrib/lz4/lib/lz4.c:1289:12
    #3 0x64215a7b in LZ4_compress_fast_extState build_docker/./contrib/lz4/lib/lz4.c:1304:20
    #4 0x64222aeb in LZ4_compress_fast build_docker/./contrib/lz4/lib/lz4.c:1376:14
    #5 0x64222aeb in LZ4_compress_default build_docker/./contrib/lz4/lib/lz4.c:1387:12
    #6 0x48becc17 in DB::ColumnCompressed::compressBuffer(void const*, unsigned long, bool) build_docker/./src/Columns/ColumnCompressed.cpp:27:27
    #7 0x48f1c63a in DB::ColumnVector<unsigned long>::compress() const build_docker/./src/Columns/ColumnVector.cpp:926:23
    #8 0x487121ac in DB::ColumnArray::compress() const build_docker/./src/Columns/ColumnArray.cpp:939:39
    #9 0x4853228e in DB::QueryCache::Writer::finalizeWrite() build_docker/./src/Interpreters/Cache/QueryCache.cpp:285:63
    #10 0x4cf73f1b in DB::StreamInQueryCacheTransform::finalizeWriteInQueryCache() build_docker/./src/Processors/Transforms/StreamInQueryCacheTransform.cpp:26:22
    #11 0x430cd175 in DB::QueryPipeline::finalizeWriteInQueryCache() build_docker/./src/QueryPipeline/QueryPipeline.cpp:597:59
    #12 0x483e8c98 in DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3::operator()(DB::QueryPipeline&) build_docker/./src/Interpreters/executeQuery.cpp:939:36
    #13 0x483e8c98 in decltype(std::declval<DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3&>()(std::declval<DB::QueryPipeline&>())) std::__1::__invoke[abi:v15000]<DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3&, DB::QueryPipeline&>(DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3&, DB::QueryPipeline&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #14 0x483e8c98 in void std::__1::__invoke_void_return_wrapper<void, true>::__call<DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3&, DB::QueryPipeline&>(DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3&, DB::QueryPipeline&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:479:9
    #15 0x483e8c98 in std::__1::__function::__default_alloc_func<DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3, void (DB::QueryPipeline&)>::operator()[abi:v15000](DB::QueryPipeline&) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:235:12
    #16 0x483e8c98 in void std::__1::__function::__policy_invoker<void (DB::QueryPipeline&)>::__call_impl<std::__1::__function::__default_alloc_func<DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3, void (DB::QueryPipeline&)>>(std::__1::__function::__policy_storage const*, DB::QueryPipeline&) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716:16
    #17 0x43073df3 in std::__1::__function::__policy_func<void (DB::QueryPipeline&)>::operator()[abi:v15000](DB::QueryPipeline&) const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:848:16
    #18 0x43073df3 in std::__1::function<void (DB::QueryPipeline&)>::operator()(DB::QueryPipeline&) const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:1187:12
    #19 0x43073df3 in DB::BlockIO::onFinish() build_docker/./src/QueryPipeline/BlockIO.cpp:57:9
    #20 0x4c26063e in DB::TCPHandler::runImpl() build_docker/./src/Server/TCPHandler.cpp
    #21 0x4c2a62d9 in DB::TCPHandler::run() build_docker/./src/Server/TCPHandler.cpp:2038:9
    #22 0x58a5fddd in Poco::Net::TCPServerConnection::start() build_docker/./base/poco/Net/src/TCPServerConnection.cpp:43:3
    #23 0x58a6116e in Poco::Net::TCPServerDispatcher::run() build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:115:20
    #24 0x591c206b in Poco::PooledThread::run() build_docker/./base/poco/Foundation/src/ThreadPool.cpp:188:14
    #25 0x591bd601 in Poco::(anonymous namespace)::RunnableHolder::run() build_docker/./base/poco/Foundation/src/Thread.cpp:45:11
    #26 0x591b9328 in Poco::ThreadImpl::runnableEntry(void*) build_docker/./base/poco/Foundation/src/Thread_POSIX.cpp:335:27
    #27 0x7f5d65f67608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8608) (BuildId: 7b4536f41cdaa5888408e82d0836e33dcf436466)
    #28 0x7f5d65e8c132 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x11f132) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)

  Uninitialized value was created by a heap allocation
    #0 0xc988420 in malloc (/usr/bin/clickhouse+0xc988420) (BuildId: f8a908ed51f5d37f9c371bbf43ef3de50516c9b3)
    #1 0x29717d07 in Allocator<false, false>::allocNoTrack(unsigned long, unsigned long) build_docker/./src/Common/Allocator.h:237:27
    #2 0x2971775b in Allocator<false, false>::alloc(unsigned long, unsigned long) build_docker/./src/Common/Allocator.h:103:16
    #3 0xca0525e in void DB::PODArrayBase<8ul, 4096ul, Allocator<false, false>, 63ul, 64ul>::resize<>(unsigned long) (/usr/bin/clickhouse+0xca0525e) (BuildId: f8a908ed51f5d37f9c371bbf43ef3de50516c9b3)
    #4 0x48f0e7cd in DB::ColumnVector<unsigned long>::insertRangeFrom(DB::IColumn const&, unsigned long, unsigned long) build_docker/./src/Columns/ColumnVector.cpp:475:10
    #5 0x48705bcc in DB::ColumnArray::insertRangeFrom(DB::IColumn const&, unsigned long, unsigned long) build_docker/./src/Columns/ColumnArray.cpp:532:15
    #6 0x4c363944 in DB::Chunk::append(DB::Chunk const&, unsigned long, unsigned long) build_docker/./src/Processors/Chunk.cpp:183:36
    #7 0x48530bee in DB::QueryCache::Writer::finalizeWrite() build_docker/./src/Interpreters/Cache/QueryCache.cpp:263:40
    #8 0x4cf73f1b in DB::StreamInQueryCacheTransform::finalizeWriteInQueryCache() build_docker/./src/Processors/Transforms/StreamInQueryCacheTransform.cpp:26:22
    #9 0x430cd175 in DB::QueryPipeline::finalizeWriteInQueryCache() build_docker/./src/QueryPipeline/QueryPipeline.cpp:597:59
    #10 0x483e8c98 in DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3::operator()(DB::QueryPipeline&) build_docker/./src/Interpreters/executeQuery.cpp:939:36
    #11 0x483e8c98 in decltype(std::declval<DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3&>()(std::declval<DB::QueryPipeline&>())) std::__1::__invoke[abi:v15000]<DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3&, DB::QueryPipeline&>(DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3&, DB::QueryPipeline&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #12 0x483e8c98 in void std::__1::__invoke_void_return_wrapper<void, true>::__call<DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3&, DB::QueryPipeline&>(DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3&, DB::QueryPipeline&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:479:9
    #13 0x483e8c98 in std::__1::__function::__default_alloc_func<DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3, void (DB::QueryPipeline&)>::operator()[abi:v15000](DB::QueryPipeline&) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:235:12
    #14 0x483e8c98 in void std::__1::__function::__policy_invoker<void (DB::QueryPipeline&)>::__call_impl<std::__1::__function::__default_alloc_func<DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3, void (DB::QueryPipeline&)>>(std::__1::__function::__policy_storage const*, DB::QueryPipeline&) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716:16
    #15 0x43073df3 in std::__1::__function::__policy_func<void (DB::QueryPipeline&)>::operator()[abi:v15000](DB::QueryPipeline&) const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:848:16
    #16 0x43073df3 in std::__1::function<void (DB::QueryPipeline&)>::operator()(DB::QueryPipeline&) const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:1187:12
    #17 0x43073df3 in DB::BlockIO::onFinish() build_docker/./src/QueryPipeline/BlockIO.cpp:57:9
    #18 0x4c26063e in DB::TCPHandler::runImpl() build_docker/./src/Server/TCPHandler.cpp
    #19 0x4c2a62d9 in DB::TCPHandler::run() build_docker/./src/Server/TCPHandler.cpp:2038:9
    #20 0x58a5fddd in Poco::Net::TCPServerConnection::start() build_docker/./base/poco/Net/src/TCPServerConnection.cpp:43:3
    #21 0x58a6116e in Poco::Net::TCPServerDispatcher::run() build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:115:20
    #22 0x591c206b in Poco::PooledThread::run() build_docker/./base/poco/Foundation/src/ThreadPool.cpp:188:14
    #23 0x591bd601 in Poco::(anonymous namespace)::RunnableHolder::run() build_docker/./base/poco/Foundation/src/Thread.cpp:45:11
    #24 0x591b9328 in Poco::ThreadImpl::runnableEntry(void*) build_docker/./base/poco/Foundation/src/Thread_POSIX.cpp:335:27
    #25 0x7f5d65f67608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8608) (BuildId: 7b4536f41cdaa5888408e82d0836e33dcf436466)

SUMMARY: MemorySanitizer: use-of-uninitialized-value build_docker/./contrib/lz4/lib/lz4.c:625:13 in LZ4_count
Exiting
Uninitialized bytes in __interceptor_write at offset 0 inside [0x7f57da815c50, 392)
==1656==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x299de4b6 in DB::WriteBufferFromFileDescriptorDiscardOnFailure::nextImpl() build_docker/./src/IO/WriteBufferFromFileDescriptorDiscardOnFailure.cpp:16:23
    #1 0x29cfa3b9 in DB::WriteBuffer::next() build_docker/./src/IO/WriteBuffer.h:49:13
    #2 0x2a16a8a3 in sanitizerDeathCallback() build_docker/./src/Daemon/BaseDaemon.cpp:447:9
    #3 0xc968215 in __sanitizer::Die() crtstuff.c
    #4 0xc97cdb2 in __msan_warning_with_origin_noreturn (/usr/bin/clickhouse+0xc97cdb2) (BuildId: f8a908ed51f5d37f9c371bbf43ef3de50516c9b3)
    #5 0x64215a7b in LZ4_count build_docker/./contrib/lz4/lib/lz4.c:625:13
    #6 0x64215a7b in LZ4_compress_generic_validated build_docker/./contrib/lz4/lib/lz4.c:1103:29
    #7 0x64215a7b in LZ4_compress_generic build_docker/./contrib/lz4/lib/lz4.c:1289:12
    #8 0x64215a7b in LZ4_compress_fast_extState build_docker/./contrib/lz4/lib/lz4.c:1304:20
    #9 0x64222aeb in LZ4_compress_fast build_docker/./contrib/lz4/lib/lz4.c:1376:14
    #10 0x64222aeb in LZ4_compress_default build_docker/./contrib/lz4/lib/lz4.c:1387:12
    #11 0x48becc17 in DB::ColumnCompressed::compressBuffer(void const*, unsigned long, bool) build_docker/./src/Columns/ColumnCompressed.cpp:27:27
    #12 0x48f1c63a in DB::ColumnVector<unsigned long>::compress() const build_docker/./src/Columns/ColumnVector.cpp:926:23
    #13 0x487121ac in DB::ColumnArray::compress() const build_docker/./src/Columns/ColumnArray.cpp:939:39
    #14 0x4853228e in DB::QueryCache::Writer::finalizeWrite() build_docker/./src/Interpreters/Cache/QueryCache.cpp:285:63
    #15 0x4cf73f1b in DB::StreamInQueryCacheTransform::finalizeWriteInQueryCache() build_docker/./src/Processors/Transforms/StreamInQueryCacheTransform.cpp:26:22
    #16 0x430cd175 in DB::QueryPipeline::finalizeWriteInQueryCache() build_docker/./src/QueryPipeline/QueryPipeline.cpp:597:59
    #17 0x483e8c98 in DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3::operator()(DB::QueryPipeline&) build_docker/./src/Interpreters/executeQuery.cpp:939:36
    #18 0x483e8c98 in decltype(std::declval<DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3&>()(std::declval<DB::QueryPipeline&>())) std::__1::__invoke[abi:v15000]<DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3&, DB::QueryPipeline&>(DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3&, DB::QueryPipeline&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #19 0x483e8c98 in void std::__1::__invoke_void_return_wrapper<void, true>::__call<DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3&, DB::QueryPipeline&>(DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3&, DB::QueryPipeline&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:479:9
    #20 0x483e8c98 in std::__1::__function::__default_alloc_func<DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3, void (DB::QueryPipeline&)>::operator()[abi:v15000](DB::QueryPipeline&) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:235:12
    #21 0x483e8c98 in void std::__1::__function::__policy_invoker<void (DB::QueryPipeline&)>::__call_impl<std::__1::__function::__default_alloc_func<DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3, void (DB::QueryPipeline&)>>(std::__1::__function::__policy_storage const*, DB::QueryPipeline&) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716:16
    #22 0x43073df3 in std::__1::__function::__policy_func<void (DB::QueryPipeline&)>::operator()[abi:v15000](DB::QueryPipeline&) const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:848:16
    #23 0x43073df3 in std::__1::function<void (DB::QueryPipeline&)>::operator()(DB::QueryPipeline&) const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:1187:12
    #24 0x43073df3 in DB::BlockIO::onFinish() build_docker/./src/QueryPipeline/BlockIO.cpp:57:9
    #25 0x4c26063e in DB::TCPHandler::runImpl() build_docker/./src/Server/TCPHandler.cpp
    #26 0x4c2a62d9 in DB::TCPHandler::run() build_docker/./src/Server/TCPHandler.cpp:2038:9
    #27 0x58a5fddd in Poco::Net::TCPServerConnection::start() build_docker/./base/poco/Net/src/TCPServerConnection.cpp:43:3
    #28 0x58a6116e in Poco::Net::TCPServerDispatcher::run() build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:115:20
    #29 0x591c206b in Poco::PooledThread::run() build_docker/./base/poco/Foundation/src/ThreadPool.cpp:188:14
    #30 0x591bd601 in Poco::(anonymous namespace)::RunnableHolder::run() build_docker/./base/poco/Foundation/src/Thread.cpp:45:11
    #31 0x591b9328 in Poco::ThreadImpl::runnableEntry(void*) build_docker/./base/poco/Foundation/src/Thread_POSIX.cpp:335:27
    #32 0x7f5d65f67608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8608) (BuildId: 7b4536f41cdaa5888408e82d0836e33dcf436466)
    #33 0x7f5d65e8c132 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x11f132) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)

  Uninitialized value was stored to memory at
    #0 0xc981bd9 in __msan_memcpy (/usr/bin/clickhouse+0xc981bd9) (BuildId: f8a908ed51f5d37f9c371bbf43ef3de50516c9b3)
    #1 0xca8395d in DB::WriteBuffer::write(char const*, unsigned long) (/usr/bin/clickhouse+0xca8395d) (BuildId: f8a908ed51f5d37f9c371bbf43ef3de50516c9b3)
    #2 0x2a1720b0 in void DB::writePODBinary<int>(int const&, DB::WriteBuffer&) build_docker/./src/IO/WriteHelpers.h:85:9
    #3 0x2a1720b0 in void DB::writeBinary<int>(int const&, DB::WriteBuffer&) build_docker/./src/IO/WriteHelpers.h:853:59
    #4 0x2a16a850 in sanitizerDeathCallback() build_docker/./src/Daemon/BaseDaemon.cpp:442:5
    #5 0xc968215 in __sanitizer::Die() crtstuff.c
    #6 0x64215a7b in LZ4_count build_docker/./contrib/lz4/lib/lz4.c:625:13
    #7 0x64215a7b in LZ4_compress_generic_validated build_docker/./contrib/lz4/lib/lz4.c:1103:29
    #8 0x64215a7b in LZ4_compress_generic build_docker/./contrib/lz4/lib/lz4.c:1289:12
    #9 0x64215a7b in LZ4_compress_fast_extState build_docker/./contrib/lz4/lib/lz4.c:1304:20
    #10 0x64222aeb in LZ4_compress_fast build_docker/./contrib/lz4/lib/lz4.c:1376:14
    #11 0x64222aeb in LZ4_compress_default build_docker/./contrib/lz4/lib/lz4.c:1387:12
    #12 0x48becc17 in DB::ColumnCompressed::compressBuffer(void const*, unsigned long, bool) build_docker/./src/Columns/ColumnCompressed.cpp:27:27
    #13 0x48f1c63a in DB::ColumnVector<unsigned long>::compress() const build_docker/./src/Columns/ColumnVector.cpp:926:23
    #14 0x487121ac in DB::ColumnArray::compress() const build_docker/./src/Columns/ColumnArray.cpp:939:39
    #15 0x4853228e in DB::QueryCache::Writer::finalizeWrite() build_docker/./src/Interpreters/Cache/QueryCache.cpp:285:63
    #16 0x4cf73f1b in DB::StreamInQueryCacheTransform::finalizeWriteInQueryCache() build_docker/./src/Processors/Transforms/StreamInQueryCacheTransform.cpp:26:22
    #17 0x430cd175 in DB::QueryPipeline::finalizeWriteInQueryCache() build_docker/./src/QueryPipeline/QueryPipeline.cpp:597:59
    #18 0x483e8c98 in DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3::operator()(DB::QueryPipeline&) build_docker/./src/Interpreters/executeQuery.cpp:939:36
    #19 0x483e8c98 in decltype(std::declval<DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3&>()(std::declval<DB::QueryPipeline&>())) std::__1::__invoke[abi:v15000]<DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3&, DB::QueryPipeline&>(DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3&, DB::QueryPipeline&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #20 0x483e8c98 in void std::__1::__invoke_void_return_wrapper<void, true>::__call<DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3&, DB::QueryPipeline&>(DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3&, DB::QueryPipeline&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:479:9
    #21 0x483e8c98 in std::__1::__function::__default_alloc_func<DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3, void (DB::QueryPipeline&)>::operator()[abi:v15000](DB::QueryPipeline&) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:235:12
    #22 0x483e8c98 in void std::__1::__function::__policy_invoker<void (DB::QueryPipeline&)>::__call_impl<std::__1::__function::__default_alloc_func<DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3, void (DB::QueryPipeline&)>>(std::__1::__function::__policy_storage const*, DB::QueryPipeline&) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716:16
    #23 0x43073df3 in std::__1::__function::__policy_func<void (DB::QueryPipeline&)>::operator()[abi:v15000](DB::QueryPipeline&) const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:848:16
    #24 0x43073df3 in std::__1::function<void (DB::QueryPipeline&)>::operator()(DB::QueryPipeline&) const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:1187:12
    #25 0x43073df3 in DB::BlockIO::onFinish() build_docker/./src/QueryPipeline/BlockIO.cpp:57:9
    #26 0x4c26063e in DB::TCPHandler::runImpl() build_docker/./src/Server/TCPHandler.cpp
    #27 0x4c2a62d9 in DB::TCPHandler::run() build_docker/./src/Server/TCPHandler.cpp:2038:9
    #28 0x58a5fddd in Poco::Net::TCPServerConnection::start() build_docker/./base/poco/Net/src/TCPServerConnection.cpp:43:3
    #29 0x58a6116e in Poco::Net::TCPServerDispatcher::run() build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:115:20
    #30 0x591c206b in Poco::PooledThread::run() build_docker/./base/poco/Foundation/src/ThreadPool.cpp:188:14

  Memory was marked as uninitialized
    #0 0xc98874d in __sanitizer_dtor_callback (/usr/bin/clickhouse+0xc98874d) (BuildId: f8a908ed51f5d37f9c371bbf43ef3de50516c9b3)
    #1 0x29bfc86d in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::~basic_string() build_docker/./contrib/llvm-project/libcxx/include/string:2335:1
    #2 0x29bfc86d in DB::QueryLogElement::~QueryLogElement() build_docker/./src/Interpreters/QueryLog.h:30:8
    #3 0x483e4000 in DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_4::~$_4() build_docker/./src/Interpreters/executeQuery.cpp:1060:39
    #4 0x483c2b77 in DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) build_docker/./src/Interpreters/executeQuery.cpp:1139:9
    #5 0x483a94bd in DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) build_docker/./src/Interpreters/executeQuery.cpp:1166:30
    #6 0x4c260249 in DB::TCPHandler::runImpl() build_docker/./src/Server/TCPHandler.cpp:420:24
    #7 0x4c2a62d9 in DB::TCPHandler::run() build_docker/./src/Server/TCPHandler.cpp:2038:9
    #8 0x58a5fddd in Poco::Net::TCPServerConnection::start() build_docker/./base/poco/Net/src/TCPServerConnection.cpp:43:3
    #9 0x58a6116e in Poco::Net::TCPServerDispatcher::run() build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:115:20
    #10 0x591c206b in Poco::PooledThread::run() build_docker/./base/poco/Foundation/src/ThreadPool.cpp:188:14
    #11 0x591bd601 in Poco::(anonymous namespace)::RunnableHolder::run() build_docker/./base/poco/Foundation/src/Thread.cpp:45:11
    #12 0x591b9328 in Poco::ThreadImpl::runnableEntry(void*) build_docker/./base/poco/Foundation/src/Thread_POSIX.cpp:335:27
    #13 0x7f5d65f67608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8608) (BuildId: 7b4536f41cdaa5888408e82d0836e33dcf436466)

SUMMARY: MemorySanitizer: use-of-uninitialized-value build_docker/./src/IO/WriteBufferFromFileDescriptorDiscardOnFailure.cpp:16:23 in DB::WriteBufferFromFileDescriptorDiscardOnFailure::nextImpl()
```

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/0/dd64eaed668a35f083d6690023d1bf46a988a68d/stress_test__msan_.html

**Comment by tavplubix** [comment]
> None of the linked three PRs included fix https://github.com/ClickHouse/ClickHouse/pull/48500.

[This one](https://s3.amazonaws.com/clickhouse-test-reports/0/dd64eaed668a35f083d6690023d1bf46a988a68d/stress_test__msan_.html) does include https://github.com/ClickHouse/ClickHouse/pull/48500 (if I'm not mistaken)

**Comment by rschu1ze** [comment]
> [This one](https://s3.amazonaws.com/clickhouse-test-reports/0/dd64eaed668a35f083d6690023d1bf46a988a68d/stress_test__msan_.html) does include #48500 (if I'm not mistaken)

You are right. I checked further, the crashes are triggered (in the stress test) from 01161_all_system_tables, query `SELECT * FROM system.errors LIMIT 10000 FORMAT Null`. But I still had no luck with reproduction when running this test in a loop with query cache on, I think it needs to be filled in a specific way by previous test failures.

Anyways, the squashing code which created the uninitialized value contained another bug, fix: #48763. Let's see if this helps.

**Comment by vdimir** [comment]
Another case: https://s3.amazonaws.com/clickhouse-test-reports/48795/4fcd435f853dc47eacfcdb32342f0dae54e4e050/stress_test__msan_.html (from [`4fcd435` (#48795)](https://github.com/ClickHouse/ClickHouse/pull/48795/commits/4fcd435f853dc47eacfcdb32342f0dae54e4e050) ), and it happened after https://github.com/ClickHouse/ClickHouse/pull/48763 was merged

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/0/108afc4d907606702429541416b668aacc43e974/stress_test__msan_.html

**Comment by rschu1ze** [comment]
Running a stress tests on msan locally, trying to reproduce it.

**Comment by rschu1ze** [comment]
The crash reproduced after 10 min stress testing, trying to narrow it down.

**Comment by rschu1ze** [comment]
I still cannot really explain what exactly goes wrong but I am quite sure the crash is unrelated to the query cache. The crash happens sporadically but only for query `SELECT last_error_trace FROM system.errors` which returns the addresses of the functions in the stack trace of the last error as `Array(UInt32)`. I can crash the server when
- I run the stress test on an msan build for a while, e.g. `PATH=$PATH:~/repo/ch/build/programs/ python3 stress.py --output-folder ~/out/ --global-time-limit 60 --num-parallel 32 --test-cmd ~/repo/ch/tests/clickhouse-test` (1 minute), this produces a ton of errors (I guess because I did not go through the many preparation steps which happen in CI, e.g. minio/S3) and
- run `SELECT last_error_trace FROM system.errors` in a parallel clickhouse-client (with or without enabled query cache - doesn't matter).

-->
```
0. ./build/./src/Common/StackTrace.cpp:287: StackTrace::tryCapture() @ 0x2b1b0f14
1. ./build/./src/Common/StackTrace.h:49: StackTrace::StackTrace() @ 0x2bab9065
2. ./build/./src/Daemon/BaseDaemon.cpp:441: sanitizerDeathCallback() @ 0x2bab038f
3. __sanitizer::Die() @ 0xdcfbdd
4. ? @ 0xdd437b1
5. ./build/./base/poco/Net/src/SocketImpl.cpp:290: Poco::Net::SocketImpl::sendBytes(void const*, int, int) @ 0x5aab7a72
6. ./build/./base/poco/Net/src/StreamSocketImpl.cpp:0: Poco::Net::StreamSocketImpl::sendBytes(void const*, int, int) @ 0x5aac9448
7. ./build/./src/IO/WriteBufferFromPocoSocket.cpp:0: DB::WriteBufferFromPocoSocket::nextImpl() @ 0x48cbfe37
8.1. inlined from ./build/./src/IO/BufferBase.h:39: DB::BufferBase::Buffer::begin() const 
8.2. inlined from ./build/./src/IO/WriteBuffer.h:60: DB::WriteBuffer::next() 
8. ./build/./src/Server/TCPHandler.cpp:1920: DB::TCPHandler::sendData(DB::Block const&) @ 0x4e3c580d
9. ./build/./src/Server/TCPHandler.cpp:0: DB::TCPHandler::processOrdinaryQueryWithProcessors() @ 0x4e3bdcd2
10. [...]
```

and sometimes in the QueryCache as [here](https://s3.amazonaws.com/clickhouse-test-reports/0/108afc4d907606702429541416b668aacc43e974/stress_test__msan_/fatal_messages.txt). I checked if the data coming from libunwind StackTrace.cpp is properly unpoisened but the code looks good. Since always the same query is affected and the query cache is not necessarily involved (but when it is it tries to squash and compress chunks containing poisened stacktrace data), I tend to disable "01161_all_system_tables" in msan (or maybe just this one query in it). But I'll check again tomorrow morning, maybe a night of sleep will help :-)
