### ISSUE TITLE
Bus error in clickhouse-local due to the usage of mmap for reading files

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#49016]
I have 11 GB log file and I run clickhouse-local as follows:

```
milovidov@milovidov-desktop:~/Downloads$ gdb clickhouse-local
rGNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from clickhouse-local...

(gdb) r
Starting program: /usr/bin/clickhouse-local 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff580b640 (LWP 3357198)]
ClickHouse local version 23.4.1.1.

[New Thread 0x7ffff4bff640 (LWP 3357199)]
milovidov-desktop :) [New Thread 0x7ffff2cff640 (LWP 3357200)]
[New Thread 0x7ffff1fff640 (LWP 3357201)]
[New Thread 0x7ffff17fe640 (LWP 3357202)]
[New Thread 0x7ffff0ffd640 (LWP 3357203)]
[New Thread 0x7ffff07fc640 (LWP 3357204)]
[New Thread 0x7fffefffb640 (LWP 3357205)]
[New Thread 0x7fffef7fa640 (LWP 3357206)]
[New Thread 0x7fffeeff9640 (LWP 3357207)]
[New Thread 0x7fffee7f8640 (LWP 3357208)]
[New Thread 0x7fffedff7640 (LWP 3357209)]
[New Thread 0x7fffed7f6640 (LWP 3357210)]
[New Thread 0x7fffecff5640 (LWP 3357211)]
[Thread 0x7ffff4bff640 (LWP 3357199) exited]
                     
milovidov-desktop :) SELECT count() FROM file('clickhouse-server.stress.log_', LineAsString)

SELECT count()
FROM file('clickhouse-server.stress.log_', LineAsString)

Query id: 840ab534-1df3-4216-bdf8-3032d8c8c406

[New Thread 0x7fffe88ff640 (LWP 3358471)]
[New Thread 0x7ffd2f3f4640 (LWP 3358472)]
[New Thread 0x7ffd2ebf3640 (LWP 3358473)]
[New Thread 0x7ffd2e3f2640 (LWP 3358474)]
[New Thread 0x7ffd2dbf1640 (LWP 3358475)]
[New Thread 0x7ffd2d3f0640 (LWP 3358476)]
[New Thread 0x7ffd2cbef640 (LWP 3358477)]
[New Thread 0x7ffd2c3ee640 (LWP 3358478)]
[New Thread 0x7ffd2bbed640 (LWP 3358479)]
[New Thread 0x7ffd2a7ff640 (LWP 3358480)]
[New Thread 0x7ffd299ff640 (LWP 3358481)]
[New Thread 0x7ffd291fe640 (LWP 3358482)]
[New Thread 0x7ffd285ff640 (LWP 3358483)]
[New Thread 0x7ffd265ff640 (LWP 3358484)]
[New Thread 0x7ffd257ff640 (LWP 3358485)]
[New Thread 0x7ffd24ffe640 (LWP 3358486)]
[New Thread 0x7ffd241ff640 (LWP 3358487)]
[New Thread 0x7ffd239fe640 (LWP 3358488)]
[New Thread 0x7ffd231fd640 (LWP 3358489)]
[New Thread 0x7ffd229fc640 (LWP 3358490)]
[New Thread 0x7ffd221fb640 (LWP 3358491)]
[New Thread 0x7ffd219fa640 (LWP 3358492)]
[New Thread 0x7ffd211f9640 (LWP 3358493)]
[New Thread 0x7ffd209f8640 (LWP 3358494)]
[New Thread 0x7ffd201f7640 (LWP 3358495)]
[New Thread 0x7ffd1f9f6640 (LWP 3358496)]
[New Thread 0x7ffd1f1f5640 (LWP 3358497)]
[New Thread 0x7ffd1e9f4640 (LWP 3358498)]
[New Thread 0x7ffd1e1f3640 (LWP 3358499)]
[New Thread 0x7ffd1d9f2640 (LWP 3358500)]
[New Thread 0x7ffd1cbff640 (LWP 3358501)]
[New Thread 0x7ffd1c3fe640 (LWP 3358502)]
[New Thread 0x7ffd1bbfd640 (LWP 3358503)]
[New Thread 0x7ffd1b3fc640 (LWP 3358504)]
[New Thread 0x7ffd1abfb640 (LWP 3358505)]
[New Thread 0x7ffd1a3fa640 (LWP 3358506)]
[New Thread 0x7ffd19bf9640 (LWP 3358507)]
[New Thread 0x7ffd193f8640 (LWP 3358508)]
[New Thread 0x7ffd18bf7640 (LWP 3358509)]
[New Thread 0x7ffd183f6640 (LWP 3358510)]
[New Thread 0x7ffd17bf5640 (LWP 3358511)]
[New Thread 0x7ffd173f4640 (LWP 3358512)]
[New Thread 0x7ffd16bf3640 (LWP 3358513)]
[New Thread 0x7ffd15dff640 (LWP 3358514)]
[New Thread 0x7ffd155fe640 (LWP 3358515)]
[New Thread 0x7ffd14dfd640 (LWP 3358516)]
[New Thread 0x7ffd145fc640 (LWP 3358517)]
[New Thread 0x7ffd13dfb640 (LWP 3358518)]
[New Thread 0x7ffd135fa640 (LWP 3358519)]
[New Thread 0x7ffd12df9640 (LWP 3358520)]
[New Thread 0x7ffd125f8640 (LWP 3358521)]
[New Thread 0x7ffd11df7640 (LWP 3358522)]
[New Thread 0x7ffd115f6640 (LWP 3358523)]
[New Thread 0x7ffd10df5640 (LWP 3358524)]
[New Thread 0x7ffd0cbff640 (LWP 3358525)]
→ Progress: 11.26 million rows, 3.03 GB (5.34 million rows/s., 1.44 GB/s.) █████████████████████████████████████▍                                                                                                           (1.3 CPU, 692.61 MB RAM) 21%[New Thread 0x7ffccb7ff640 (LWP 3358552)]
↘ Progress: 38.82 million rows, 9.44 GB (4.30 million rows/s., 1.05 GB/s.) (0.7 CPU, 692.60 MB RAM)█████████████████████████████████████████████████████████████████████████████████████████████████████████                                         75%
Thread 26 "Segmentator" received signal SIGBUS, Bus error.
[Switching to Thread 0x7ffd299ff640 (LWP 3358481)]
detail::find_first_symbols_sse2<true, (detail::ReturnMode)0, (char)13, (char)10> (begin=<optimized out>, end=0x7fffe80fef67 "") at ./base/base/../base/find_symbols.h:85
85 ./base/base/../base/find_symbols.h: No such file or directory.
(gdb) bt
#0  detail::find_first_symbols_sse2<true, (detail::ReturnMode)0, (char)13, (char)10> (begin=<optimized out>, end=0x7fffe80fef67 "") at ./base/base/../base/find_symbols.h:85
#1  detail::find_first_symbols_dispatch<true, (detail::ReturnMode)0, (char)13, (char)10> (begin=<optimized out>, end=0x7fffe80fef67 "") at ./base/base/../base/find_symbols.h:194
#2  find_first_symbols<(char)13, (char)10> (begin=<optimized out>, end=0x7fffe80fef67 "") at ./base/base/../base/find_symbols.h:211
#3  DB::newLineFileSegmentationEngine (in=..., memory=..., min_bytes=10485760, max_rows=65409) at ./src/Formats/newLineSegmentationEngine.cpp:21
#4  0x0000000017df4238 in std::__1::__function::__policy_func<std::__1::pair<bool, unsigned long> (DB::ReadBuffer&, DB::Memory<Allocator<false, false> >&, unsigned long, unsigned long)>::operator()[abi:v15000](DB::ReadBuffer&, DB::Memory<Allocator<false, false> >&, unsigned long&&, unsigned long&&) const (this=0x7fffe9e051b0, __args=<optimized out>, __args=<optimized out>, __args=<optimized out>, __args=<optimized out>) at ./contrib/llvm-project/libcxx/include/__functional/function.h:848
#5  std::__1::function<std::__1::pair<bool, unsigned long> (DB::ReadBuffer&, DB::Memory<Allocator<false, false> >&, unsigned long, unsigned long)>::operator()(DB::ReadBuffer&, DB::Memory<Allocator<false, false> >&, unsigned long, unsigned long) const (this=0x7fffe9e051b0, __arg=65409, __arg=65409, __arg=65409, __arg=65409) at ./contrib/llvm-project/libcxx/include/__functional/function.h:1187
#6  DB::ParallelParsingInputFormat::segmentatorThreadFunction (this=this@entry=0x7fffe9e05018, thread_group=...) at ./src/Processors/Formats/Impl/ParallelParsingInputFormat.cpp:42
#7  0x0000000017df7a45 in std::__1::__invoke[abi:v15000]<void (DB::ParallelParsingInputFormat::*&)(std::__1::shared_ptr<DB::ThreadGroup>), DB::ParallelParsingInputFormat*&, std::__1::shared_ptr<DB::ThreadGroup>&, void>(void (DB::ParallelParsingInputFormat::*&)(std::__1::shared_ptr<DB::ThreadGroup>), DB::ParallelParsingInputFormat*&, std::__1::shared_ptr<DB::ThreadGroup>&) (__a0=@0x7ffd299f66e0: 0x7fffe9e05018, __args=..., __f=<optimized out>)
    at ./contrib/llvm-project/libcxx/include/__functional/invoke.h:359
#8  std::__1::__apply_tuple_impl[abi:v15000]<void (DB::ParallelParsingInputFormat::*&)(std::__1::shared_ptr<DB::ThreadGroup>), std::__1::tuple<DB::ParallelParsingInputFormat*, std::__1::shared_ptr<DB::ThreadGroup> >&, 0ul, 1ul>(void (DB::ParallelParsingInputFormat::*&)(std::__1::shared_ptr<DB::ThreadGroup>), std::__1::tuple<DB::ParallelParsingInputFormat*, std::__1::shared_ptr<DB::ThreadGroup> >&, std::__1::__tuple_indices<0ul, 1ul>) (__t=..., __f=<optimized out>)
    at ./contrib/llvm-project/libcxx/include/tuple:1789
#9  std::__1::apply[abi:v15000]<void (DB::ParallelParsingInputFormat::*&)(std::__1::shared_ptr<DB::ThreadGroup>), std::__1::tuple<DB::ParallelParsingInputFormat*, std::__1::shared_ptr<DB::ThreadGroup> >&>(void (DB::ParallelParsingInputFormat::*&)(std::__1::shared_ptr<DB::ThreadGroup>), std::__1::tuple<DB::ParallelParsingInputFormat*, std::__1::shared_ptr<DB::ThreadGroup> >&) (__t=..., __f=<optimized out>) at ./contrib/llvm-project/libcxx/include/tuple:1798
#10 ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<void (DB::ParallelParsingInputFormat::*)(std::__1::shared_ptr<DB::ThreadGroup>), DB::ParallelParsingInputFormat*, std::__1::shared_ptr<DB::ThreadGroup> >(void (DB::ParallelParsingInputFormat::*&&)(std::__1::shared_ptr<DB::ThreadGroup>), DB::ParallelParsingInputFormat*&&, std::__1::shared_ptr<DB::ThreadGroup>&&)::{lambda()#1}::operator()() (this=0x7fffe9dac0c0) at ./src/Common/ThreadPool.h:228
#11 0x00000000117a7d7e in std::__1::__function::__policy_func<void ()>::operator()[abi:v15000]() const (this=0x7ffd299f69d0) at ./contrib/llvm-project/libcxx/include/__functional/function.h:848
#12 std::__1::function<void ()>::operator()() const (this=0x7ffd299f69d0) at ./contrib/llvm-project/libcxx/include/__functional/function.h:1187
#13 ThreadPoolImpl<std::__1::thread>::worker (this=0x7ffff701ff40, thread_it=...) at ./src/Common/ThreadPool.cpp:413
#14 0x00000000117ab76e in ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::{lambda()#2}::operator()() const (this=0x7ffff2000ce8) at ./src/Common/ThreadPool.cpp:180
#15 std::__1::__invoke[abi:v15000]<ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::{lambda()#2}>(ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::{lambda()#2}&&) (__f=...) at ./contrib/llvm-project/libcxx/include/__functional/invoke.h:394
#16 std::__1::__thread_execute[abi:v15000]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::{lambda()#2}>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::{lambda()#2}>&, std::__1::__tuple_indices<>) (__t=...) at ./contrib/llvm-project/libcxx/include/thread:284
#17 std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::{lambda()#2}> >(void*) (__vp=0x7ffff2000ce0) at ./contrib/llvm-project/libcxx/include/thread:295
#18 0x00007ffff7dffb43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#19 0x00007ffff7e91a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

The file is not changing in background.

**Comment by alexey-milovidov** [comment]
```
milovidov@milovidov-desktop:~/Downloads$ stat clickhouse-server.stress.log_ 
  File: clickhouse-server.stress.log_
  Size: 11690614631    Blocks: 22833240   IO Block: 4096   regular file
Device: 10302h/66306d  Inode: 27269118    Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1000/milovidov)   Gid: ( 1000/milovidov)
Access: 2023-04-21 16:09:59.194448599 +0200
Modify: 2023-01-02 00:44:11.402596960 +0100
Change: 2023-01-02 02:36:47.208098146 +0100
 Birth: 2023-01-02 00:51:33.336562338 +0100

milovidov@milovidov-desktop:~/Downloads$ wc -c clickhouse-server.stress.log_
11690614631 clickhouse-server.stress.log_
milovidov@milovidov-desktop:~/Downloads$ cat clickhouse-server.stress.log_ | wc -c
cat: clickhouse-server.stress.log_: Input/output error
9142263808
```
