### ISSUE TITLE
Very strange error ": java.lang.UnsupportedOperationException: LZ4 is not supported." when creating JDBC prepareStatement

### ISSUE THREAD

**Issue by GangLiCN** [ClickHouse/ClickHouse#49493]
**Describe the unexpected behaviour**
I executed a very simple  Java application to test the batch Insert functionality of
CLickHouse, but unfortunately  I  hit below error:

> Caused by: java.lang.UnsupportedOperationException: LZ4 is not supported. Please disable compression(compress=0), modify the algorithm(e.g. compress_algorithm=gzip), or add the missing libraries to the classpath.
        at com.clickhouse.data.ClickHouseCompressionAlgorithm.createInputStream(ClickHouseCompressionAlgorithm.java:61)
        at com.clickhouse.data.ClickHouseInputStream.wrap(ClickHouseInputStream.java:98)
        at com.clickhouse.data.ClickHouseInputStream.of(ClickHouseInputStream.java:294)
        at com.clickhouse.client.ClickHouseClient.getResponseInputStream(ClickHouseClient.java:166)
        at com.clickhouse.client.ClickHouseClient.getAsyncResponseInputStream(ClickHouseClient.java:189)
        at com.clickhouse.client.http.HttpUrlConnectionImpl.buildResponse(HttpUrlConnectionImpl.java:99)
        at com.clickhouse.client.http.HttpUrlConnectionImpl.post(HttpUrlConnectionImpl.java:229)
        at com.clickhouse.client.http.ClickHouseHttpClient.send(ClickHouseHttpClient.java:124)
        at com.clickhouse.client.AbstractClient.execute(AbstractClient.java:280)
        at com.clickhouse.client.ClickHouseClientBuilder$Agent.sendOnce(ClickHouseClientBuilder.java:282)
        at com.clickhouse.client.ClickHouseClientBuilder$Agent.send(ClickHouseClientBuilder.java:294)
        at com.clickhouse.client.ClickHouseClientBuilder$Agent.execute(ClickHouseClientBuilder.java:349)
        at com.clickhouse.client.ClickHouseClient.executeAndWait(ClickHouseClient.java:1056)
        at com.clickhouse.client.ClickHouseRequest.executeAndWait(ClickHouseRequest.java:2154)
        at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.getTableColumns(ClickHouseConnectionImpl.java:263)
        ... 4 more

**How to reproduce**
1) Create a table via below SQL:
CREATE TABLE users ( \
 id UInt32 , \
 name String , \
 age UInt8  \ 
) ENGINE = MergeTree() \
PARTITION BY id ORDER BY (id, name);

2) Write a JAVA application to test  batchInsert functionality:
Sample code:

//   Public function to get database connection
`public Connection getConnect(String url, String driver, String user, String password) {
        Connection conn = null;
        try {
            // System.out.println(String.format("JDBC connection url:%s",url));
            Class.forName(driver);
            conn =  DriverManager.getConnection(url, user, password);
            conn.setAutoCommit(false);
        } catch (ClassNotFoundException e1) {
            e1.printStackTrace();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return conn;
    }

In  Main func,  create database connection first, then create a PreparedStatement:
 `.....
        Connection conn = getConnect(url,driver,user,password);

        PreparedStatement pst = null;
                                        
         try {
                   pst = conn.prepareStatement("insert into users(id,name,age) values(?,?,?)");
                   pst.setInt(1, unique_id);
                    pst.setString(2, usr_final);
                    pst.setInt(3, random_age);
                    pst.addBatch();
                    ......
        
       } catch (Exception e) {
                    e.printStackTrace();
        } finally {
          ......
         }
`

* Which ClickHouse server version to use
22.8.16.32
* Which interface to use, if matters
ClickHouse JDBC driver:  0.4.2(also tried 0.4.5), the same effect.

* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
CREATE TABLE users ( \
 id UInt32 , \
 name  String, \
 age UInt8  \ 
) ENGINE = MergeTree() \
PARTITION BY id ORDER BY (id, name);

* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**
1) The simple  batchInsert action should be finished without any error.
2) LZ4 is default compress method that CK is used,  and the OS -level package does exit:
lz4-devel-1.8.3-1.el7.x86_64
lz4-1.8.3-1.el7.x86_64

**Error message and/or stacktrace**
> java.sql.SQLException: LZ4 is not supported. Please disable compression(compress=0), modify the algorithm(e.g. compress_algorithm=gzip), or add the missing libraries to the classpath., server ClickHouseNode [uri=http://xx.xx.xx.xx::8123/default]@217686826
	at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:85)
	at com.clickhouse.jdbc.SqlExceptionUtils.create(SqlExceptionUtils.java:31)
	at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:90)
	at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.getTableColumns(ClickHouseConnectionImpl.java:267)
	at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.prepareStatement(ClickHouseConnectionImpl.java:843)
	at com.clickhouse.jdbc.ClickHouseConnection.prepareStatement(ClickHouseConnection.java:121)
	at ThreadInsert_ck$1.run(ThreadInsert_ck.java:219)
	at java.lang.Thread.run(Thread.java:750)

> Caused by: java.lang.UnsupportedOperationException: LZ4 is not supported. Please disable compression(compress=0), modify the algorithm(e.g. compress_algorithm=gzip), or add the missing libraries to the classpath.
        at com.clickhouse.data.ClickHouseCompressionAlgorithm.createInputStream(ClickHouseCompressionAlgorithm.java:61)
        at com.clickhouse.data.ClickHouseInputStream.wrap(ClickHouseInputStream.java:98)
        at com.clickhouse.data.ClickHouseInputStream.of(ClickHouseInputStream.java:294)
        at com.clickhouse.client.ClickHouseClient.getResponseInputStream(ClickHouseClient.java:166)
        at com.clickhouse.client.ClickHouseClient.getAsyncResponseInputStream(ClickHouseClient.java:189)
        at com.clickhouse.client.http.HttpUrlConnectionImpl.buildResponse(HttpUrlConnectionImpl.java:99)
        at com.clickhouse.client.http.HttpUrlConnectionImpl.post(HttpUrlConnectionImpl.java:229)
        at com.clickhouse.client.http.ClickHouseHttpClient.send(ClickHouseHttpClient.java:124)
        at com.clickhouse.client.AbstractClient.execute(AbstractClient.java:280)
        at com.clickhouse.client.ClickHouseClientBuilder$Agent.sendOnce(ClickHouseClientBuilder.java:282)
        at com.clickhouse.client.ClickHouseClientBuilder$Agent.send(ClickHouseClientBuilder.java:294)
        at com.clickhouse.client.ClickHouseClientBuilder$Agent.execute(ClickHouseClientBuilder.java:349)
        at com.clickhouse.client.ClickHouseClient.executeAndWait(ClickHouseClient.java:1056)
        at com.clickhouse.client.ClickHouseRequest.executeAndWait(ClickHouseRequest.java:2154)
        at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.getTableColumns(ClickHouseConnectionImpl.java:263)
        ... 4 more

**Additional context**
I also wrote a simple ClickHouseSink application using  Flink connector, it also executes insert action using same JDBC driver
and similar java code, no problem, everything goes fine.

**Comment by tavplubix** [comment]
See https://github.com/ClickHouse/clickhouse-java/issues/1317

**Comment by GangLiCN** [comment]
Thanks,   LZ4 issue is fixed after  added "lz4-java.jar" into CLASSPATH.  but another error throws:

> java.sql.BatchUpdateException: Code: 252. DB::Exception: Too many partitions for single INSERT block (more than 100). The limit is controlled by 'max_partitions_per_insert_block' setting. Large number of partitions is a common misconception. It will lead to severe negative performance impact, including slow server startup, slow INSERT queries and slow SELECT queries. Recommended total number of partitions for a table is under 1000..10000. Please note, that partitioning is not intended to speed up SELECT queries (ORDER BY key is sufficient to make range queries fast). Partitions are intended for data manipulation (DROP PARTITION, etc). (TOO_MANY_PARTS) (version 22.8.16.32 (official build))

**Comment by tavplubix** [comment]
This error is intended. You are probably using a bad partitioning key, it's highly not recommended to have a lot of partitions. The exception message is quite self-explanatory, please read the error message carefully.

**Comment by GangLiCN** [comment]
Thanks, the partition issue also has been fixed by adding below line into  "user.xml"
<max_partitions_per_insert_block>5000</max_partitions_per_insert_block>

**Comment by tavplubix** [comment]
> <max_partitions_per_insert_block>5000</max_partitions_per_insert_block>

**It's highly not recommended, and it's not going to work well. You should change `partition by` key.**
