### ISSUE TITLE
Assertion `symbol == '\0'' failed.

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#49567]
https://s3.amazonaws.com/clickhouse-test-reports/0/38b2f94bfa225b21749d0ffab0185b03f9fec417/fuzzer_astfuzzerdebug/report.html

```
WITH NULL AS a
SELECT
    [1023, -2147483648],
    quantilesState(0.0001)(1024),
    countArrayIfState([NULL], NULL),
    [1048577, 100000000000000000000., -2147483647],
    countArrayState([NULL]),
    identity(1048575),
    a
FROM numbers(257)
    WITH TOTALS

**clickhouse-client**: /build/src/AggregateFunctions/AggregateFunctionNothing.h:72: virtual void DB::AggregateFunctionNothing::deserialize(__restrict DB::AggregateDataPtr, DB::ReadBuffer &, std::optional<size_t>, DB::Arena *) const: Assertion `symbol == '\0'' failed.
```

**Comment by qoega** [comment]
core is strange
```
(gdb) bt
#0  0x00007f1c5d3a700b in __GI_raise (sig=0, sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:44
#1  0x00007f1c5d386859 in __GI_abort () at abort.c:79
#2  0x00007f1c5d386729 in __assert_fail_base (fmt=0x7f1c5d51c588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0xfd65910 "symbol == '\\0'", file=0xfd6591f "/build/src/AggregateFunctions/AggregateFunctionNothing.h", line=72, function=<optimized out>) at assert.c:92
#3  0x00007f1c5d397fd6 in __GI___assert_fail (assertion=0x2 <error: Cannot access memory at address 0x2>, file=0x7fffe79e8dd0 "", line=72, function=0x7f1c5d3a700b <__GI_raise+155> "\017\005\211\306D\211", <incomplete sequence \352>) at assert.c:101
#4  0x00007fffe79e90e0 in ?? ()
#5  0x000000001a2a9d00 in ?? ()
#6  0x00007fffe79f2c80 in ?? ()
#7  0x00000000267e12e4 in DB::AggregateFunctionNothing::deserialize (this=0x2c736e6f69746172, buf=...) at /build/src/AggregateFunctions/AggregateFunctionNothing.h:72
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

**Comment by alexey-milovidov** [comment]
Good finding:

```
milovidov-desktop :) SELECT countArrayIfState([NULL], NULL), 'Hello'

Exception on client:
Code: 62. DB::Exception: Syntax error (data type): failed at position 1 (''Hello''): 'Hello'. Expected one of: data type, nested table, identifier: while receiving packet from localhost:9000. (SYNTAX_ERROR)
```

```
SELECT CAST('\x01\x00' AS AggregateFunction(nothingArrayIf, Array(Nullable(Nothing)), Nullable(Nothing)))
```

Assertion failed.

> core is strange

It is not strange for `gdb`. We build code with the latest clang and LLVM; older gdb can be confused with the debug info.
You can use LLDB-16 instead.
