### ISSUE TITLE
flaky unit test `AsyncLoader.ScheduleJobWithCanceledDependencies`

### ISSUE THREAD

**Issue by kssenii** [ClickHouse/ClickHouse#51201]
https://s3.amazonaws.com/clickhouse-test-reports/51187/fcb793dc02731d1b164f5cb71e754e5033beddcf/unit_tests__msan_/run.log
```
[ RUN      ] AsyncLoader.ScheduleJobWithCanceledDependencies
==14==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x5581cdc57058 in DB::AsyncLoader::worker(DB::AsyncLoader::Pool&) build_docker/./src/Common/AsyncLoader.cpp:688:21
    #1 0x5581cdc5725f in DB::AsyncLoader::spawn(DB::AsyncLoader::Pool&, std::__1::unique_lock<std::__1::mutex>&)::$_0::operator()() const build_docker/./src/Common/AsyncLoader.cpp:659:5
    #2 0x5581cdc5725f in decltype(std::declval<DB::AsyncLoader::spawn(DB::AsyncLoader::Pool&, std::__1::unique_lock<std::__1::mutex>&)::$_0&>()()) std::__1::__invoke[abi:v15000]<DB::AsyncLoader::spawn(DB::AsyncLoader::Pool&, std::__1::unique_lock<std::__1::mutex>&)::$_0&>(DB::AsyncLoader::spawn(DB::AsyncLoader::Pool&, std::__1::unique_lock<std::__1::mutex>&)::$_0&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #3 0x5581cdc5725f in void std::__1::__invoke_void_return_wrapper<void, true>::__call<DB::AsyncLoader::spawn(DB::AsyncLoader::Pool&, std::__1::unique_lock<std::__1::mutex>&)::$_0&>(DB::AsyncLoader::spawn(DB::AsyncLoader::Pool&, std::__1::unique_lock<std::__1::mutex>&)::$_0&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:479:9
    #4 0x5581cdc5725f in std::__1::__function::__default_alloc_func<DB::AsyncLoader::spawn(DB::AsyncLoader::Pool&, std::__1::unique_lock<std::__1::mutex>&)::$_0, void ()>::operator()[abi:v15000]() build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:235:12
    #5 0x5581cdc5725f in void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::AsyncLoader::spawn(DB::AsyncLoader::Pool&, std::__1::unique_lock<std::__1::mutex>&)::$_0, void ()>>(std::__1::__function::__policy_storage const*) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716:16
    #6 0x5581cded67f0 in std::__1::__function::__policy_func<void ()>::operator()[abi:v15000]() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:848:16
    #7 0x5581cded67f0 in std::__1::function<void ()>::operator()() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:1187:12
    #8 0x5581cded67f0 in ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__1::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) build_docker/./src/Common/ThreadPool.cpp:416:13
    #9 0x5581cdee0e0a in void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const build_docker/./src/Common/ThreadPool.cpp:180:73
    #10 0x5581cdee0e0a in decltype(std::declval<void>()()) std::__1::__invoke[abi:v15000]<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()&>(void&&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #11 0x5581cdee0e0a in decltype(auto) std::__1::__apply_tuple_impl[abi:v15000]<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()&, std::__1::tuple<>&>(void&&, std::__1::tuple<>&, std::__1::__tuple_indices<>) build_docker/./contrib/llvm-project/libcxx/include/tuple:1789:1
    #12 0x5581cdee0e0a in decltype(auto) std::__1::apply[abi:v15000]<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()&, std::__1::tuple<>&>(void&&, std::__1::tuple<>&) build_docker/./contrib/llvm-project/libcxx/include/tuple:1798:1
    #13 0x5581cdee0e0a in ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'()::operator()() build_docker/./src/Common/ThreadPool.h:229:13
    #14 0x5581cdee0cbe in decltype(std::declval<void>()()) std::__1::__invoke[abi:v15000]<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'()&>(void&&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #15 0x5581cdee0cbe in void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'()&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:479:9
    #16 0x5581cdee0cbe in std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>::operator()[abi:v15000]() build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:235:12
    #17 0x5581cdee0cbe in void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716:16
    #18 0x5581cdecd8de in std::__1::__function::__policy_func<void ()>::operator()[abi:v15000]() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:848:16
    #19 0x5581cdecd8de in std::__1::function<void ()>::operator()() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:1187:12
    #20 0x5581cdecd8de in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) build_docker/./src/Common/ThreadPool.cpp:416:13
    #21 0x5581cdeda68a in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const build_docker/./src/Common/ThreadPool.cpp:180:73
    #22 0x5581cdeda68a in decltype(std::declval<void>()()) std::__1::__invoke[abi:v15000]<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #23 0x5581cdeda68a in void std::__1::__thread_execute[abi:v15000]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>&, std::__1::__tuple_indices<>) build_docker/./contrib/llvm-project/libcxx/include/thread:284:5
    #24 0x5581cdeda68a in void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) build_docker/./contrib/llvm-project/libcxx/include/thread:295:5
    #25 0x7fe6028a3608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8608) (BuildId: 7b4536f41cdaa5888408e82d0836e33dcf436466)
    #26 0x7fe6027c8132 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x11f132) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)

  Member fields were destroyed
    #0 0x55818ace417d in __sanitizer_dtor_callback_fields (/unit_tests_dbms+0xecec17d) (BuildId: 76f8eb7153679e84a5c9dc16e8d5f20adb2a0cdf)
    #1 0x5581cdc57948 in DB::AsyncLoader::Pool::~Pool() build_docker/./src/Common/AsyncLoader.h:343:16
    #2 0x5581cdc57948 in DB::AsyncLoader::Pool::~Pool() build_docker/./src/Common/AsyncLoader.h:337:12
    #3 0x5581cdc4bebd in void std::__1::__destroy_at[abi:v15000]<DB::AsyncLoader::Pool, 0>(DB::AsyncLoader::Pool*) build_docker/./contrib/llvm-project/libcxx/include/__memory/construct_at.h:63:13
    #4 0x5581cdc4bebd in void std::__1::destroy_at[abi:v15000]<DB::AsyncLoader::Pool, 0>(DB::AsyncLoader::Pool*) build_docker/./contrib/llvm-project/libcxx/include/__memory/construct_at.h:88:5
    #5 0x5581cdc4bebd in void std::__1::allocator_traits<std::__1::allocator<DB::AsyncLoader::Pool>>::destroy[abi:v15000]<DB::AsyncLoader::Pool, void, void>(std::__1::allocator<DB::AsyncLoader::Pool>&, DB::AsyncLoader::Pool*) build_docker/./contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:317:9
    #6 0x5581cdc4bebd in std::__1::vector<DB::AsyncLoader::Pool, std::__1::allocator<DB::AsyncLoader::Pool>>::__base_destruct_at_end[abi:v15000](DB::AsyncLoader::Pool*) build_docker/./contrib/llvm-project/libcxx/include/vector:833:9
    #7 0x5581cdc4bebd in std::__1::vector<DB::AsyncLoader::Pool, std::__1::allocator<DB::AsyncLoader::Pool>>::__clear[abi:v15000]() build_docker/./contrib/llvm-project/libcxx/include/vector:827:29
    #8 0x5581cdc4bebd in std::__1::vector<DB::AsyncLoader::Pool, std::__1::allocator<DB::AsyncLoader::Pool>>::~vector[abi:v15000]() build_docker/./contrib/llvm-project/libcxx/include/vector:436:9
    #9 0x5581cdc4bebd in DB::AsyncLoader::~AsyncLoader() build_docker/./src/Common/AsyncLoader.cpp:192:1
    #10 0x55818b1269ba in AsyncLoaderTest::~AsyncLoaderTest() build_docker/./src/Common/tests/gtest_async_loader.cpp:38:8
    #11 0x55818b1269ba in AsyncLoader_ScheduleJobWithCanceledDependencies_Test::TestBody() build_docker/./src/Common/tests/gtest_async_loader.cpp:539:1
    #12 0x5581b8bd8a76 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) build_docker/./contrib/googletest/googletest/src/gtest.cc:2621:10
    #13 0x5581b8bd8a76 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) build_docker/./contrib/googletest/googletest/src/gtest.cc:2657:14
    #14 0x5581b8b79284 in testing::Test::Run() build_docker/./contrib/googletest/googletest/src/gtest.cc:2696:5
    #15 0x5581b8b7d162 in testing::TestInfo::Run() build_docker/./contrib/googletest/googletest/src/gtest.cc:2845:11
    #16 0x5581b8b7f259 in testing::TestSuite::Run() build_docker/./contrib/googletest/googletest/src/gtest.cc:3004:30
    #17 0x5581b8bbd7c6 in testing::internal::UnitTestImpl::RunAllTests() build_docker/./contrib/googletest/googletest/src/gtest.cc:5889:44
    #18 0x5581b8bdb656 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) build_docker/./contrib/googletest/googletest/src/gtest.cc:2621:10
    #19 0x5581b8bdb656 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) build_docker/./contrib/googletest/googletest/src/gtest.cc:2657:14
    #20 0x5581b8bbc68d in testing::UnitTest::Run() build_docker/./contrib/googletest/googletest/src/gtest.cc:5454:10
    #21 0x55818b78ca0f in RUN_ALL_TESTS() build_docker/./contrib/googletest/googletest/include/gtest/gtest.h:2310:73
    #22 0x55818b78ca0f in main build_docker/./src/Coordination/tests/gtest_coordination.cpp:2618:12
    #23 0x7fe6026cd082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)

SUMMARY: MemorySanitizer: use-of-uninitialized-value build_docker/./src/Common/AsyncLoader.cpp:688:21 in DB::AsyncLoader::worker(DB::AsyncLoader::Pool&)
Exiting

Thread 11 "Pool0" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fe5fcd2c700 (LWP 27)]
0x00007fe6026ec00b in raise () from /lib/x86_64-linux-gnu/libc.so.6
#0  0x00007fe6026ec00b in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fe6026cb859 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x000055818acc5d87 in __sanitizer::Abort() ()
#3  0x000055818acc3b91 in __sanitizer::Die() ()
#4  0x000055818acd8623 in __msan_warning_with_origin_noreturn ()
#5  0x00005581cdc57059 in DB::AsyncLoader::worker (this=0x7ffca370b210, 
    pool=...) at ./src/Common/AsyncLoader.cpp:688
#6  0x00005581cdc57260 in DB::AsyncLoader::spawn(DB::AsyncLoader::Pool&, std::__1::unique_lock<std::__1::mutex>&)::$_0::operator()() const (
    this=<optimized out>) at ./src/Common/AsyncLoader.cpp:659
#7  std::__1::__invoke[abi:v15000]<DB::AsyncLoader::spawn(DB::AsyncLoader::Pool&, std::__1::unique_lock<std::__1::mutex>&)::$_0&> (__f=...)
    at ./contrib/llvm-project/libcxx/include/__functional/invoke.h:394
#8  std::__1::__invoke_void_return_wrapper<void, true>::__call<DB::AsyncLoader::spawn(DB::AsyncLoader::Pool&, std::__1::unique_lock<std::__1::mutex>&)::$_0&>(DB::AsyncLoader::spawn(DB::AsyncLoader::Pool&, std::__1::unique_lock<std::__1::mutex>&)::$_0&) (__args=...)
    at ./contrib/llvm-project/libcxx/include/__functional/invoke.h:479
#9  std::__1::__function::__default_alloc_func<DB::AsyncLoader::spawn(DB::AsyncLoader::Pool&, std::__1::unique_lock<std::__1::mutex>&)::$_0, void ()>::operator()[abi:v15000]() (this=<optimized out>)
    at ./contrib/llvm-project/libcxx/include/__functional/function.h:235
#10 std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::AsyncLoader::spawn(DB::AsyncLoader::Pool&, std::__1::unique_lock<std::__1::mutex>&)::$_0, void ()> >(std::__1::__function::__policy_storage const*) (__buf=<optimized out>)
    at ./contrib/llvm-project/libcxx/include/__functional/function.h:716
#11 0x00005581cded67f1 in std::__1::__function::__policy_func<void ()>::operator()[abi:v15000]() const (this=0x7fe5fcd26f28)
    at ./contrib/llvm-project/libcxx/include/__functional/function.h:848
#12 std::__1::function<void ()>::operator()() const (this=0x7fe5fcd26f28)
    at ./contrib/llvm-project/libcxx/include/__functional/function.h:1187
#13 ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::worker (
    this=this@entry=0x711000001f40, thread_it=thread_it@entry=...)
    at ./src/Common/ThreadPool.cpp:416
#14 0x00005581cdee0e0b in ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}::operator()() const (this=<optimized out>)
    at ./src/Common/ThreadPool.cpp:180
#15 std::__1::__invoke[abi:v15000]<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}&> (__f=...)
    at ./contrib/llvm-project/libcxx/include/__functional/invoke.h:394
#16 std::__1::__apply_tuple_impl[abi:v15000]<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}&, std::__1::tuple<>&>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}&, std::__1::tuple<>&, std::__1::__tuple_indices<>) (__f=..., __t=...)
    at ./contrib/llvm-project/libcxx/include/tuple:1789
#17 std::__1::apply[abi:v15000]<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}&, std::__1::tuple<>&>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}&, std::__1::tuple<>&) (__f=..., __t=...) at ./contrib/llvm-project/libcxx/include/tuple:1798
#18 ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}&&)::{lambda()#1}::operator()() (this=<optimized out>)
    at ./src/Common/ThreadPool.h:229
#19 0x00005581cdee0cbf in std::__1::__invoke[abi:v15000]<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}&&)::{lambda()#1}&> (__f=...)
    at ./contrib/llvm-project/libcxx/include/__functional/invoke.h:394
#20 std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}&&)::{lambda()#1}&>(ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}&&)::{lambda()#1}&) (__args=...)
    at ./contrib/llvm-project/libcxx/include/__functional/invoke.h:479
#21 std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}&&)::{lambda()#1}, void ()>::operator()[abi:v15000]() (this=0x2)
    at ./contrib/llvm-project/libcxx/include/__functional/function.h:235
#22 std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}&&)::{lambda()#1}, void ()> >(std::__1::__function::__policy_storage const*) (__buf=<optimized out>)
    at ./contrib/llvm-project/libcxx/include/__functional/function.h:716
#23 0x00005581cdecd8df in std::__1::__function::__policy_func<void ()>::operator()[abi:v15000]() const (this=0x7fe5fcd274f8)
    at ./contrib/llvm-project/libcxx/include/__functional/function.h:848
#24 std::__1::function<void ()>::operator()() const (this=0x7fe5fcd274f8)
    at ./contrib/llvm-project/libcxx/include/__functional/function.h:1187
#25 ThreadPoolImpl<std::__1::thread>::worker (this=0x711000012480, 
    thread_it=...) at ./src/Common/ThreadPool.cpp:416
#26 0x00005581cdeda68b in ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}::operator()() const (this=<optimized out>)
    at ./src/Common/ThreadPool.cpp:180
#27 std::__1::__invoke[abi:v15000]<ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}> (__f=...)
    at ./contrib/llvm-project/libcxx/include/__functional/invoke.h:394
#28 std::__1::__thread_execute[abi:v15000]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}>&, std::__1::__tuple_indices<>) (__t=...)
    at ./contrib/llvm-project/libcxx/include/thread:284
#29 std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}> >(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}>) (__vp=0x702000485060)
    at ./contrib/llvm-project/libcxx/include/thread:295
#30 0x00007fe6028a3609 in start_thread ()
```

**Comment by kssenii** [comment]
cc @serxa
