### ISSUE TITLE
Test `test_storage_azure_blob_storage`: `heap-buffer-overflow` in `StorageAzureBlobSource`

### ISSUE THREAD

**Issue by CurtizJ** [ClickHouse/ClickHouse#51244]
**Describe the bug**
[A link to the report
](https://s3.amazonaws.com/clickhouse-test-reports/51164/5e500cc799ced3b183bb1aefdf56aa7cb2e83646/integration_tests__asan__[3_6].html)

**Error message and/or stacktrace**
```
E           Exception: Sanitizer assert found for instance =================================================================
E           ==1==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6320002b4097 at pc 0x5598ec392ed8 bp 0x7ff75805feb0 sp 0x7ff75805fea8
E           READ of size 1 at 0x6320002b4097 thread T348 (AzureReader)
E               #0 0x5598ec392ed7 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::__is_long[abi:v15000]() const build_docker/./contrib/llvm-project/libcxx/include/string:1499:33
E               #1 0x5598ec392ed7 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) build_docker/./contrib/llvm-project/libcxx/include/string:2012:16
E               #2 0x5598ec392ed7 in DB::RelativePathWithMetadata::RelativePathWithMetadata(DB::RelativePathWithMetadata const&) build_docker/./src/Disks/ObjectStorages/IObjectStorage.h:43:8
E               #3 0x5598ec392ed7 in DB::StorageAzureBlobSource::Iterator::next() build_docker/./src/Storages/StorageAzureBlob.cpp:974:16
E               #4 0x5598ec39b238 in DB::StorageAzureBlobSource::createReader() build_docker/./src/Storages/StorageAzureBlob.cpp:1126:47
E               #5 0x5598ec3a8400 in DB::StorageAzureBlobSource::createReaderAsync()::$_0::operator()() const build_docker/./src/Storages/StorageAzureBlob.cpp:1157:52
E               #6 0x5598ec3a8400 in decltype(std::declval<DB::StorageAzureBlobSource::createReaderAsync()::$_0&>()()) std::__1::__invoke[abi:v15000]<DB::StorageAzureBlobSource::createReaderAsync()::$_0&>(DB::StorageAzureBlobSource::createReaderAsync()::$_0&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
E               #7 0x5598ec3a8400 in DB::StorageAzureBlobSource::ReaderHolder std::__1::__invoke_void_return_wrapper<DB::StorageAzureBlobSource::ReaderHolder, false>::__call<DB::StorageAzureBlobSource::createReaderAsync()::$_0&>(DB::StorageAzureBlobSource::createReaderAsync()::$_0&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:470:16
E               #8 0x5598ec3a8400 in std::__1::__function::__default_alloc_func<DB::StorageAzureBlobSource::createReaderAsync()::$_0, DB::StorageAzureBlobSource::ReaderHolder ()>::operator()[abi:v15000]() build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:235:12
E               #9 0x5598ec3a8400 in DB::StorageAzureBlobSource::ReaderHolder std::__1::__function::__policy_invoker<DB::StorageAzureBlobSource::ReaderHolder ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::StorageAzureBlobSource::createReaderAsync()::$_0, DB::StorageAzureBlobSource::ReaderHolder ()>>(std::__1::__function::__policy_storage const*) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716:16
E               #10 0x5598ec3c4398 in std::__1::__function::__policy_func<DB::StorageAzureBlobSource::ReaderHolder ()>::operator()[abi:v15000]() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:848:16
E               #11 0x5598ec3c4398 in std::__1::function<DB::StorageAzureBlobSource::ReaderHolder ()>::operator()() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:1187:12
E               #12 0x5598ec3c4398 in std::__1::function<std::__1::future<DB::StorageAzureBlobSource::ReaderHolder> (std::__1::function<DB::StorageAzureBlobSource::ReaderHolder ()>&&, Priority)> DB::threadPoolCallbackRunner<DB::StorageAzureBlobSource::ReaderHolder, std::__1::function<DB::StorageAzureBlobSource::ReaderHolder ()>>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)::'lambda'(std::__1::function<DB::StorageAzureBlobSource::ReaderHolder ()>&&, Priority)::operator()(std::__1::function<DB::StorageAzureBlobSource::ReaderHolder ()>&&, Priority)::'lambda'()::operator()() build_docker/./src/Interpreters/threadPoolCallbackRunner.h:42:20
E               #13 0x5598ec3c4398 in decltype(std::declval<DB::StorageAzureBlobSource::ReaderHolder>()()) std::__1::__invoke[abi:v15000]<std::__1::function<std::__1::future<DB::StorageAzureBlobSource::ReaderHolder> (std::__1::function<DB::StorageAzureBlobSource::ReaderHolder ()>&&, Priority)> DB::threadPoolCallbackRunner<DB::StorageAzureBlobSource::ReaderHolder, std::__1::function<DB::StorageAzureBlobSource::ReaderHolder ()>>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)::'lambda'(std::__1::function<DB::StorageAzureBlobSource::ReaderHolder ()>&&, Priority)::operator()(std::__1::function<DB::StorageAzureBlobSource::ReaderHolder ()>&&, Priority)::'lambda'()&>(DB::StorageAzureBlobSource::ReaderHolder&&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
E               #14 0x5598ec3c4398 in std::__1::__packaged_task_func<std::__1::function<std::__1::future<DB::StorageAzureBlobSource::ReaderHolder> (std::__1::function<DB::StorageAzureBlobSource::ReaderHolder ()>&&, Priority)> DB::threadPoolCallbackRunner<DB::StorageAzureBlobSource::ReaderHolder, std::__1::function<DB::StorageAzureBlobSource::ReaderHolder ()>>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)::'lambda'(std::__1::function<DB::StorageAzureBlobSource::ReaderHolder ()>&&, Priority)::operator()(std::__1::function<DB::StorageAzureBlobSource::ReaderHolder ()>&&, Priority)::'lambda'(), std::__1::allocator<std::__1::function<std::__1::future<DB::StorageAzureBlobSource::ReaderHolder> (std::__1::function<DB::StorageAzureBlobSource::ReaderHolder ()>&&, Priority)> DB::threadPoolCallbackRunner<DB::StorageAzureBlobSource::ReaderHolder, std::__1::function<DB::StorageAzureBlobSource::ReaderHolder ()>>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)::'lambda'(std::__1::function<DB::StorageAzureBlobSource::ReaderHolder ()>&&, Priority)::operator()(std::__1::function<DB::StorageAzureBlobSource::ReaderHolder ()>&&, Priority)::'lambda'()>, DB::StorageAzureBlobSource::ReaderHolder ()>::operator()() build_docker/./contrib/llvm-project/libcxx/include/future:1694:12
E               #15 0x5598ec3c553d in std::__1::__packaged_task_function<DB::StorageAzureBlobSource::ReaderHolder ()>::operator()() const build_docker/./contrib/llvm-project/libcxx/include/future:1876:12
E               #16 0x5598ec3c553d in std::__1::packaged_task<DB::StorageAzureBlobSource::ReaderHolder ()>::operator()() build_docker/./contrib/llvm-project/libcxx/include/future:1953:24
E               #17 0x5598d72042ef in std::__1::__function::__policy_func<void ()>::operator()[abi:v15000]() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:848:16
E               #18 0x5598d72042ef in std::__1::function<void ()>::operator()() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:1187:12
E               #19 0x5598d72042ef in ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__1::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) build_docker/./src/Common/ThreadPool.cpp:416:13
E               #20 0x5598d720e9cd in void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const build_docker/./src/Common/ThreadPool.cpp:180:73
E               #21 0x5598d720e9cd in decltype(std::declval<void>()()) std::__1::__invoke[abi:v15000]<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()&>(void&&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
E               #22 0x5598d720e9cd in decltype(auto) std::__1::__apply_tuple_impl[abi:v15000]<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()&, std::__1::tuple<>&>(void&&, std::__1::tuple<>&, std::__1::__tuple_indices<>) build_docker/./contrib/llvm-project/libcxx/include/tuple:1789:1
E               #23 0x5598d720e9cd in decltype(auto) std::__1::apply[abi:v15000]<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()&, std::__1::tuple<>&>(void&&, std::__1::tuple<>&) build_docker/./contrib/llvm-project/libcxx/include/tuple:1798:1
E               #24 0x5598d720e9cd in ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'()::operator()() build_docker/./src/Common/ThreadPool.h:229:13
E               #25 0x5598d71fb950 in std::__1::__function::__policy_func<void ()>::operator()[abi:v15000]() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:848:16
E               #26 0x5598d71fb950 in std::__1::function<void ()>::operator()() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:1187:12
E               #27 0x5598d71fb950 in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) build_docker/./src/Common/ThreadPool.cpp:416:13
E               #28 0x5598d72086ec in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const build_docker/./src/Common/ThreadPool.cpp:180:73
E               #29 0x5598d72086ec in decltype(std::declval<void>()()) std::__1::__invoke[abi:v15000]<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
E               #30 0x5598d72086ec in void std::__1::__thread_execute[abi:v15000]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>&, std::__1::__tuple_indices<>) build_docker/./contrib/llvm-project/libcxx/include/thread:284:5
E               #31 0x5598d72086ec in void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) build_docker/./contrib/llvm-project/libcxx/include/thread:295:5
E               #32 0x7ffa1f5d9608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8608) (BuildId: 7b4536f41cdaa5888408e82d0836e33dcf436466)
E               #33 0x7ffa1f4fe132 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x11f132) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)
```

**Comment by SmitaRKulkarni** [comment]
Fixed in PR #50936
