### ISSUE TITLE
UndefinedBehaviorSanitizer: reference binding to null pointer of type 'const DB::ActionsDAG::Node *'

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#51278]
https://s3.amazonaws.com/clickhouse-test-reports/0/9d9c9ccaff12af27beca43d5f7f937f54df83377/fuzzer_astfuzzerubsan/report.html
```
/build/contrib/llvm-project/libcxx/include/vector:556:16: runtime error: reference binding to null pointer of type 'const DB::ActionsDAG::Node *'
    #0 0x5579edc6306d in DB::ActionsDAG::cloneActionsForFilterPushDown(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&) build_docker/./src/Interpreters/ActionsDAG.cpp
    #1 0x5579f16707b2 in DB::QueryPlanOptimizations::tryPushDownFilter(DB::QueryPlan::Node*, std::__1::list<DB::QueryPlan::Node, std::__1::allocator<DB::QueryPlan::Node>>&)::$_1::operator()(DB::JoinKind) const build_docker/./src/Processors/QueryPlan/Optimizations/filterPushDown.cpp:352:42
    #2 0x5579f166ebd9 in DB::QueryPlanOptimizations::tryPushDownFilter(DB::QueryPlan::Node*, std::__1::list<DB::QueryPlan::Node, std::__1::allocator<DB::QueryPlan::Node>>&) build_docker/./src/Processors/QueryPlan/Optimizations/filterPushDown.cpp:374:36
    #3 0x5579f163fe5e in DB::QueryPlanOptimizations::optimizeTreeFirstPass(DB::QueryPlanOptimizationSettings const&, DB::QueryPlan::Node&, std::__1::list<DB::QueryPlan::Node, std::__1::allocator<DB::QueryPlan::Node>>&) build_docker/./src/Processors/QueryPlan/Optimizations/optimizeTree.cpp:87:33
    #4 0x5579f15880a2 in DB::QueryPlan::optimize(DB::QueryPlanOptimizationSettings const&) build_docker/./src/Processors/QueryPlan/QueryPlan.cpp:483:5
    #5 0x5579f15875ad in DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&) build_docker/./src/Processors/QueryPlan/QueryPlan.cpp:161:5
    #6 0x5579eef0082a in DB::InterpreterSelectWithUnionQuery::execute() build_docker/./src/Interpreters/InterpreterSelectWithUnionQuery.cpp:379:31
    #7 0x5579ef4547f5 in DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) build_docker/./src/Interpreters/executeQuery.cpp:723:36
    #8 0x5579ef44e73b in DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) build_docker/./src/Interpreters/executeQuery.cpp:1182:30
    #9 0x5579f0c24972 in DB::TCPHandler::runImpl() build_docker/./src/Server/TCPHandler.cpp:420:24
    #10 0x5579f0c4f551 in DB::TCPHandler::run() build_docker/./src/Server/TCPHandler.cpp:2043:9
    #11 0x5579f23fa0fd in Poco::Net::TCPServerConnection::start() build_docker/./base/poco/Net/src/TCPServerConnection.cpp:43:3
    #12 0x5579f23fb239 in Poco::Net::TCPServerDispatcher::run() build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:115:20
    #13 0x5579f268ff8f in Poco::PooledThread::run() build_docker/./base/poco/Foundation/src/ThreadPool.cpp:188:14
    #14 0x5579f268b0b0 in Poco::ThreadImpl::runnableEntry(void*) build_docker/./base/poco/Foundation/src/Thread_POSIX.cpp:335:27
    #15 0x7f3c580e4608 in start_thread /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477:8
    #16 0x7f3c58009132 in __clone /build/glibc-SzIz7B/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /build/contrib/llvm-project/libcxx/include/vector:556:16 in
```

```
2023.06.22 14:29:36.173190 [ 485 ] {} <Fatal> BaseDaemon: ########################################
2023.06.22 14:29:36.173285 [ 485 ] {} <Fatal> BaseDaemon: (version 23.6.1.1 (official build), build id: C6C5CF89AE7A842D7C3AB5068A762565F0DFEB51, git hash: 9d9c9ccaff12af27beca43d5f7f937f54df83377) (from thread 480) (query_id: 33f0373d-d18a-40b5-8c85-e584efa0db7b) (query: SELECT * FROM m__fuzz_11 INNER JOIN b__fuzz_0 USING (key) WHERE ID = 1 HAVING ID = 1 ORDER BY ID ASC NULLS LAST) Received signal sanitizer trap (-3)
2023.06.22 14:29:36.173319 [ 485 ] {} <Fatal> BaseDaemon: Sanitizer trap.
2023.06.22 14:29:36.173372 [ 485 ] {} <Fatal> BaseDaemon: Stack trace: 0x00005579e10548d7 0x00005579e141b025 0x00005579d49560d6 0x00005579d49661a3 0x00005579edc6306e 0x00005579f16707b3 0x00005579f166ebda 0x00005579f163fe5f 0x00005579f15880a3 0x00005579f15875ae 0x00005579eef0082b 0x00005579ef4547f6 0x00005579ef44e73c 0x00005579f0c24973 0x00005579f0c4f552 0x00005579f23fa0fe 0x00005579f23fb23a 0x00005579f268ff90 0x00005579f268b0b1 0x00007f3c580e4609 0x00007f3c58009133
2023.06.22 14:29:36.188032 [ 485 ] {} <Fatal> BaseDaemon: 0. ./build_docker/./src/Common/StackTrace.cpp:291: StackTrace::tryCapture() @ 0x00000000378868d7 in /workspace/clickhouse
2023.06.22 14:29:36.223739 [ 485 ] {} <Fatal> BaseDaemon: 1. ./build_docker/./src/Common/StackTrace.h:0: sanitizerDeathCallback() @ 0x0000000037c4d025 in /workspace/clickhouse
2023.06.22 14:29:37.559270 [ 485 ] {} <Fatal> BaseDaemon: 2. __sanitizer::Die() @ 0x000000002b1880d6 in /workspace/clickhouse
2023.06.22 14:29:38.874574 [ 485 ] {} <Fatal> BaseDaemon: 3. ? @ 0x000000002b1981a3 in /workspace/clickhouse
2023.06.22 14:29:39.120203 [ 485 ] {} <Fatal> BaseDaemon: 4.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__iterator/wrap_iter.h:100: std::__wrap_iter<DB::ActionsDAG::Node const**>::operator++[abi:v15000]()
2023.06.22 14:29:39.120260 [ 485 ] {} <Fatal> BaseDaemon: 4. ./build_docker/./src/Interpreters/ActionsDAG.cpp:2191: DB::ActionsDAG::cloneActionsForFilterPushDown(String const&, bool, std::vector<String, std::allocator<String>> const&, std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&) @ 0x000000004449506e in /workspace/clickhouse
2023.06.22 14:29:39.153908 [ 485 ] {} <Fatal> BaseDaemon: 5. ./build_docker/./src/Processors/QueryPlan/Optimizations/filterPushDown.cpp:0: DB::QueryPlanOptimizations::tryPushDownFilter(DB::QueryPlan::Node*, std::list<DB::QueryPlan::Node, std::allocator<DB::QueryPlan::Node>>&)::$_1::operator()(DB::JoinKind) const @ 0x0000000047ea27b3 in /workspace/clickhouse
2023.06.22 14:29:39.192698 [ 485 ] {} <Fatal> BaseDaemon: 6. ./build_docker/./src/Processors/QueryPlan/Optimizations/filterPushDown.cpp:374: DB::QueryPlanOptimizations::tryPushDownFilter(DB::QueryPlan::Node*, std::list<DB::QueryPlan::Node, std::allocator<DB::QueryPlan::Node>>&) @ 0x0000000047ea0bda in /workspace/clickhouse
2023.06.22 14:29:39.208353 [ 485 ] {} <Fatal> BaseDaemon: 7. ./build_docker/./src/Processors/QueryPlan/Optimizations/optimizeTree.cpp:88: DB::QueryPlanOptimizations::optimizeTreeFirstPass(DB::QueryPlanOptimizationSettings const&, DB::QueryPlan::Node&, std::list<DB::QueryPlan::Node, std::allocator<DB::QueryPlan::Node>>&) @ 0x0000000047e71e5f in /workspace/clickhouse
2023.06.22 14:29:39.253274 [ 485 ] {} <Fatal> BaseDaemon: 8. ./build_docker/./src/Processors/QueryPlan/QueryPlan.cpp:484: DB::QueryPlan::optimize(DB::QueryPlanOptimizationSettings const&) @ 0x0000000047dba0a3 in /workspace/clickhouse
2023.06.22 14:29:39.291790 [ 485 ] {} <Fatal> BaseDaemon: 9.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/compressed_pair.h:36: __compressed_pair_elem
2023.06.22 14:29:39.291853 [ 485 ] {} <Fatal> BaseDaemon: 9.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/compressed_pair.h:108: __compressed_pair<std::__value_init_tag, std::__value_init_tag>
2023.06.22 14:29:39.291894 [ 485 ] {} <Fatal> BaseDaemon: 9.3. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:168: unique_ptr<true, void>
2023.06.22 14:29:39.291932 [ 485 ] {} <Fatal> BaseDaemon: 9. ./build_docker/./src/Processors/QueryPlan/QueryPlan.cpp:169: DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&) @ 0x0000000047db95ae in /workspace/clickhouse
2023.06.22 14:29:39.336801 [ 485 ] {} <Fatal> BaseDaemon: 10. ./build_docker/./src/Interpreters/InterpreterSelectWithUnionQuery.cpp:379: DB::InterpreterSelectWithUnionQuery::execute() @ 0x000000004573282b in /workspace/clickhouse
2023.06.22 14:29:39.407637 [ 485 ] {} <Fatal> BaseDaemon: 11. ./build_docker/./src/Interpreters/executeQuery.cpp:0: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x0000000045c867f6 in /workspace/clickhouse
2023.06.22 14:29:39.483736 [ 485 ] {} <Fatal> BaseDaemon: 12. ./build_docker/./src/Interpreters/executeQuery.cpp:1182: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x0000000045c8073c in /workspace/clickhouse
2023.06.22 14:29:39.547569 [ 485 ] {} <Fatal> BaseDaemon: 13. ./build_docker/./src/Server/TCPHandler.cpp:0: DB::TCPHandler::runImpl() @ 0x0000000047456973 in /workspace/clickhouse
2023.06.22 14:29:39.638918 [ 485 ] {} <Fatal> BaseDaemon: 14. ./build_docker/./src/Server/TCPHandler.cpp:2045: DB::TCPHandler::run() @ 0x0000000047481552 in /workspace/clickhouse
2023.06.22 14:29:39.644492 [ 485 ] {} <Fatal> BaseDaemon: 15. ./build_docker/./base/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x0000000048c2c0fe in /workspace/clickhouse
2023.06.22 14:29:39.651934 [ 485 ] {} <Fatal> BaseDaemon: 16.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:302: std::unique_ptr<Poco::Net::TCPServerConnection, std::default_delete<Poco::Net::TCPServerConnection>>::reset[abi:v15000](Poco::Net::TCPServerConnection*)
2023.06.22 14:29:39.651969 [ 485 ] {} <Fatal> BaseDaemon: 16.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
2023.06.22 14:29:39.652008 [ 485 ] {} <Fatal> BaseDaemon: 16. ./build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:116: Poco::Net::TCPServerDispatcher::run() @ 0x0000000048c2d23a in /workspace/clickhouse
2023.06.22 14:29:39.659795 [ 485 ] {} <Fatal> BaseDaemon: 17. ./build_docker/./base/poco/Foundation/src/ThreadPool.cpp:202: Poco::PooledThread::run() @ 0x0000000048ec1f90 in /workspace/clickhouse
2023.06.22 14:29:39.667222 [ 485 ] {} <Fatal> BaseDaemon: 18.1. inlined from ./build_docker/./base/poco/Foundation/include/Poco/AutoPtr.h:205: Poco::AutoPtr<Poco::ThreadImpl::ThreadData>::operator->()
2023.06.22 14:29:39.667255 [ 485 ] {} <Fatal> BaseDaemon: 18. ./build_docker/./base/poco/Foundation/src/Thread_POSIX.cpp:350: Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000048ebd0b1 in /workspace/clickhouse
2023.06.22 14:29:39.667294 [ 485 ] {} <Fatal> BaseDaemon: 19. ? @ 0x00007f3c580e4609 in ?
2023.06.22 14:29:39.667332 [ 485 ] {} <Fatal> BaseDaemon: 20. __clone @ 0x00007f3c58009133 in ?
2023.06.22 14:29:39.958414 [ 485 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: AC8400584E278726232B354C6EB4702A)
2023.06.22 14:29:43.438055 [ 485 ] {} <Fatal> BaseDaemon: Changed settings: receive_timeout = 10., receive_data_timeout_ms = 10000, allow_suspicious_low_cardinality_types = true, log_queries = true, insert_quorum = 'auto', insert_quorum_timeout = 5000, insert_quorum_parallel = false, select_sequential_consistency = 1, table_function_remote_max_addresses = 200, join_use_nulls = false, max_execution_time = 10., max_memory_usage = 10000000000, send_logs_level = 'fatal', allow_introspection_functions = true, mutations_sync = 1
```

```
CREATE TABLE m__fuzz_11 (`key` Int8) ENGINE = Merge(currentDatabase(), 'a');
CREATE TABLE b__fuzz_0 (`key` UInt32, `ID` LowCardinality(UInt32)) ENGINE = MergeTree ORDER BY key;
SELECT * FROM m__fuzz_11 INNER JOIN b__fuzz_0 USING (key) WHERE ID = 1 HAVING ID = 1 ORDER BY ID ASC NULLS LAST;
```

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/issues/50451
