### ISSUE TITLE
Block structure mismatch in RIGHT JOIN

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#51963]
![Untitled15](https://github.com/ClickHouse/ClickHouse/assets/18581488/a43144ed-5a02-40c3-afb1-22045ac5903c)

**Describe the bug**
https://s3.amazonaws.com/clickhouse-test-reports/51914/253953b5acb32cbc1d1045f309e49616ffa88d8c/fuzzer_astfuzzerasan/report.html

**How to reproduce**
`build_debug$ programs/clickhouse local --query "SELECT bar.a FROM (SELECT 1 AS a) AS foo RIGHT JOIN (SELECT 1 AS a) AS bar ON 0`

**Comment by alexey-milovidov** [comment]
```
milovidov@milovidov-desktop:~/work/ClickHouse/build_debug$ gdb --args programs/clickhouse local --query "SELECT bar.a FROM (SELECT 1 AS a) AS foo RIGHT JOIN (SELECT 1 AS a) AS bar ON 0"
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from programs/clickhouse...
r
(gdb) r
Starting program: /home/milovidov/work/ClickHouse/build_debug/programs/clickhouse local --query SELECT\ bar.a\ FROM\ \(SELECT\ 1\ AS\ a\)\ AS\ foo\ RIGHT\ JOIN\ \(SELECT\ 1\ AS\ a\)\ AS\ bar\ ON\ 0
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff5b0b640 (LWP 53565)]
[New Thread 0x7ffff4dff640 (LWP 53566)]
[New Thread 0x7ffff41ff640 (LWP 53567)]

Thread 4 "QueryPullPipeEx" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff41ff640 (LWP 53567)]
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737289123392) at ./nptl/pthread_kill.c:44
44      ./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737289123392) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737289123392) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737289123392, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7dad476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff7d937f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00000000241652fe in DB::abortOnFailedAssertion (description=...) at /home/milovidov/work/ClickHouse/src/Common/Exception.cpp:50
#6  0x0000000024165375 in DB::handle_error_code (msg=..., code=49, remote=false, trace=...) at /home/milovidov/work/ClickHouse/src/Common/Exception.cpp:62
#7  0x00000000241657c9 in DB::Exception::Exception (this=0x7ffff323a080, msg_masked=..., code=49, remote_=false) at /home/milovidov/work/ClickHouse/src/Common/Exception.cpp:96
#8  0x000000001abac9ca in DB::Exception::Exception (this=0x7ffff323a080, msg=..., code=49, remote_=false) at /home/milovidov/work/ClickHouse/src/Common/Exception.h:63
#9  0x000000002b5f1288 in DB::Exception::Exception<std::__1::basic_string_view<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > (this=0x7ffff323a080, code=49, fmt=..., args=..., args=..., args=...)
    at /home/milovidov/work/ClickHouse/src/Common/Exception.h:91
#10 0x000000002b5e8b6f in DB::onError<void, std::__1::basic_string_view<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > (code=49, fmt_string=..., fmt_args=..., fmt_args=..., fmt_args=...) at /home/milovidov/work/ClickHouse/src/Core/Block.cpp:38
#11 0x000000002b5e3646 in DB::checkColumnStructure<void> (actual=..., expected=..., context_description=..., allow_materialize=false, code=49) at /home/milovidov/work/ClickHouse/src/Core/Block.cpp:86
#12 0x000000002b5e7590 in DB::checkBlockStructure<void> (lhs=..., rhs=..., context_description=..., allow_materialize=false) at /home/milovidov/work/ClickHouse/src/Core/Block.cpp:130
#13 0x000000002b5e73c0 in DB::assertBlocksHaveEqualStructure (lhs=..., rhs=..., context_description=...) at /home/milovidov/work/ClickHouse/src/Core/Block.cpp:682
#14 0x000000002cd37f4d in DB::NotJoinedBlocks::nextImpl (this=0x7ffff3235000) at /home/milovidov/work/ClickHouse/src/Interpreters/JoinUtils.cpp:869
#15 0x000000002eb9626c in DB::IBlocksStream::next (this=0x7ffff3235000) at /home/milovidov/work/ClickHouse/src/Interpreters/IJoin.h:111
#16 0x000000002eb8d34b in DB::JoiningTransform::work (this=0x7ffff6869cd8) at /home/milovidov/work/ClickHouse/src/Processors/Transforms/JoiningTransform.cpp:149
#17 0x000000002e704663 in DB::executeJob (node=0x7ffff71d9d00, read_progress_callback=0x7ffff68d7d60) at /home/milovidov/work/ClickHouse/src/Processors/Executors/ExecutionThreadContext.cpp:47
#18 0x000000002e7043a0 in DB::ExecutionThreadContext::executeTask (this=0x7ffff3223000) at /home/milovidov/work/ClickHouse/src/Processors/Executors/ExecutionThreadContext.cpp:92
#19 0x000000002e6e9221 in DB::PipelineExecutor::executeStepImpl (this=0x7ffff68c1518, thread_num=0, yield_flag=0x0) at /home/milovidov/work/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:255
#20 0x000000002e6e9537 in DB::PipelineExecutor::executeSingleThread (this=0x7ffff68c1518, thread_num=0) at /home/milovidov/work/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:221
#21 0x000000002e6e8547 in DB::PipelineExecutor::executeImpl (this=0x7ffff68c1518, num_threads=1) at /home/milovidov/work/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:379
#22 0x000000002e6e7b20 in DB::PipelineExecutor::execute (this=0x7ffff68c1518, num_threads=1) at /home/milovidov/work/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:113
#23 0x000000002e70b3da in DB::threadFunction (data=..., thread_group=..., num_threads=1) at /home/milovidov/work/ClickHouse/src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:83
#24 0x000000002e70b280 in DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0::operator()() const (this=0x7ffff41f2250)
    at /home/milovidov/work/ClickHouse/src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:111
#25 0x000000002e70b215 in std::__1::__invoke[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&) (
    __f=...) at /home/milovidov/work/ClickHouse/contrib/llvm-project/libcxx/include/__functional/invoke.h:394
#26 0x000000002e70b1f9 in std::__1::__apply_tuple_impl[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>) (__f=..., __t=...) at /home/milovidov/work/ClickHouse/contrib/llvm-project/libcxx/include/tuple:1789
#27 0x000000002e70b15d in std::__1::apply[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&) (__f=..., __t=...) at /home/milovidov/work/ClickHouse/contrib/llvm-project/libcxx/include/tuple:1798
#28 0x000000002e70b067 in ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::{lambda()#1}::operator()() (this=0x7ffff686b2a0) at /home/milovidov/work/ClickHouse/src/Common/ThreadPool.h:242
#29 0x000000002e70afd5 in std::__1::__invoke[abi:v15000]<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::{lambda()#1}&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&) (__f=...)
    at /home/milovidov/work/ClickHouse/contrib/llvm-project/libcxx/include/__functional/invoke.h:394
#30 0x000000002e70afb5 in std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::{lambda()#1}&>(ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::{lambda()#1}&) (__args=...)
    at /home/milovidov/work/ClickHouse/contrib/llvm-project/libcxx/include/__functional/invoke.h:479
#31 0x000000002e70af95 in std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::{lambda()#1}, void ()>::operator()[abi:v15000]() (this=0x7ffff686b2a0)
    at /home/milovidov/work/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:235
#32 0x000000002e70af60 in std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::{lambda()#1}, void ()> >(std::__1::__function::__policy_storage const*) (
    __buf=0x7ffff41f2518) at /home/milovidov/work/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:716
#33 0x00000000241bed76 in std::__1::__function::__policy_func<void ()>::operator()[abi:v15000]() const (this=0x7ffff41f2518)
    at /home/milovidov/work/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:848
#34 0x00000000241be275 in std::__1::function<void ()>::operator()() const (this=0x7ffff41f2518) at /home/milovidov/work/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:1187
#35 0x00000000242c5b43 in ThreadPoolImpl<std::__1::thread>::worker (this=0x7ffff7020080, thread_it=...) at /home/milovidov/work/ClickHouse/src/Common/ThreadPool.cpp:427
#36 0x00000000242cde24 in ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}::operator()() const (
    this=0x7ffff71cfca8) at /home/milovidov/work/ClickHouse/src/Common/ThreadPool.cpp:180
#37 0x00000000242cddd5 in std::__1::__invoke[abi:v15000]<ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}>(ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}&&) (__f=...)
    at /home/milovidov/work/ClickHouse/contrib/llvm-project/libcxx/include/__functional/invoke.h:394
#38 0x00000000242cdcfd in std::__1::__thread_execute[abi:v15000]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}>&, std::__1::__tuple_indices<>) (__t=...)
    at /home/milovidov/work/ClickHouse/contrib/llvm-project/libcxx/include/thread:284
#39 0x00000000242cd7e2 in std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}> >(void*) (__vp=0x7ffff71cfca0)
    at /home/milovidov/work/ClickHouse/contrib/llvm-project/libcxx/include/thread:295
#40 0x00007ffff7dffb43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
--Type <RET> for more, q to quit, c to continue without paging--
#41 0x00007ffff7e91a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
(gdb)
```

**Comment by Algunenano** [comment]
Not sure if @vdimir fixed it at some point, but it looks like it only happened in debug mode and it doesn't happen anymore

**Comment by alexey-milovidov** [comment]
Ok then.
