### ISSUE TITLE
Ambiguous MSAN issue in AST fuzzer test

### ISSUE THREAD

**Issue by antaljanosbenjamin** [ClickHouse/ClickHouse#52019]
(you don't have to strictly follow this form)

**Describe the bug**
AST fuzzing found two errors in the MSAN build:
- one in `DB::MergeTreeConditionInverted::traverseASTEquals`
- one in `DB::WriteBufferFromFileDescriptorDiscardOnFailure::nextImpl()` which is probably called from `sanitizerDeathCallback`, but we can afford issues in this handler as long as the original error is properly reported (which is the case right now).

https://s3.amazonaws.com/clickhouse-test-reports/50686/ab2b02be11a9db98824da7b7b88dfea0752368f6/fuzzer_astfuzzermsan/report.html

**How to reproduce**
It is unclear how to reproduce, which query triggered the error. The last query was run at `15:51`:
```
2023.07.06 15:51:12.538394 [ 185 ] {5aea9db4-cedf-4be7-b04f-62cfaf4c2f94} <Debug> executeQuery: (from [::ffff:127.0.0.1]:54148) SELECT toString(toDateTime('-922337203.6854775808', 1, 'Asia/IstanbulAsia/IstanbulAsia/IstanbulAsia/Istanbul')) (stage: Complete)
```

However the server was only terminated at `16:08`:
```
2023.07.06 16:08:21.350031 [ 160 ] {} <Fatal> Application: Child process was terminated by signal 6.
```

**Error message and/or stacktrace**
```
SUMMARY: MemorySanitizer: use-of-uninitialized-value build_docker/./src/Storages/MergeTree/MergeTreeIndexInverted.cpp:551:26 in DB::MergeTreeConditionInverted::traverseASTEquals(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, DB::RPNBuilderTreeNode const&, std::__1::shared_ptr<DB::IDataType const> const&, DB::Field const&, DB::MergeTreeConditionInverted::RPNElement&) Received signal -3 SUMMARY: MemorySanitizer: use-of-uninitialized-value build_docker/./src/IO/WriteBufferFromFileDescriptorDiscardOnFailure.cpp:16:23 in DB::WriteBufferFromFileDescriptorDiscardOnFailure::nextImpl()
--
```

**Comment by azat** [comment]
>SUMMARY: MemorySanitizer: use-of-uninitialized-value build_docker/./src/Storages/MergeTree/MergeTreeIndexInverted.cpp:551:26 in DB::MergeTreeConditionInverted::traverseASTEquals(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, DB::RPNBuilderTreeNode const&, std::__1::shared_ptr<DB::IDataType const> const&, DB::Field const&, DB::MergeTreeConditionInverted::RPNElement&) Received signal -3 SUMMARY: MemorySanitizer: use-of-uninitialized-value build_docker/./src/IO/WriteBufferFromFileDescriptorDiscardOnFailure.cpp:16:23 in DB::WriteBufferFromFileDescriptorDiscardOnFailure::nextImpl()

This is likely due to previous MSan error

**Comment by azat** [comment]
```
==172==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x55cf82aedd6c in DB::ASTFunction* typeid_cast<DB::ASTFunction*, DB::IAST>(DB::IAST*) build_docker/./src/Common/typeid_cast.h:42:73
    #1 0x55cf82aedd6c in DB::TypePromotion<DB::IAST>::CastHelper<DB::ASTFunction, false, false>::value(DB::IAST*) build_docker/./src/Common/TypePromotion.h:38:43
    #2 0x55cf82aedd6c in std::__1::invoke_result<decltype(&CastHelper<DB::ASTFunction, false>::value), DB::TypePromotion<DB::IAST>::CastHelper<DB::ASTFunction, false, std::is_reference_v<DB::ASTFunction>>, DB::IAST*>::type DB::TypePromotion<DB::IAST>::as<DB::ASTFunction>() build_docker/./src/>
    #3 0x55cf82aedd6c in DB::MergeTreeIndexConditionSet::operatorFromAST(std::__1::shared_ptr<DB::IAST>&) build_docker/./src/Storages/MergeTree/MergeTreeIndexSet.cpp:602:25
    #4 0x55cf82ae5bc1 in DB::MergeTreeIndexConditionSet::traverseAST(std::__1::shared_ptr<DB::IAST>&) const build_docker/./src/Storages/MergeTree/MergeTreeIndexSet.cpp:547:9
    #5 0x55cf82ae5de6 in DB::MergeTreeIndexConditionSet::traverseAST(std::__1::shared_ptr<DB::IAST>&) const build_docker/./src/Storages/MergeTree/MergeTreeIndexSet.cpp:552:13
    #6 0x55cf82ae06db in DB::MergeTreeIndexConditionSet::MergeTreeIndexConditionSet(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, DB::Block const&, unsigned long, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>) build_docker/.>
    #7 0x55cf82b0a0c3 in DB::MergeTreeIndexConditionSet* std::__1::construct_at[abi:v15000]<DB::MergeTreeIndexConditionSet, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, DB::Block const&, unsigned long const&, DB::SelectQueryInfo const&, std::__1>
    #8 0x55cf82b0a0c3 in void std::__1::allocator_traits<std::__1::allocator<DB::MergeTreeIndexConditionSet>>::construct[abi:v15000]<DB::MergeTreeIndexConditionSet, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, DB::Block const&, unsigned long con>
    #9 0x55cf82b0a0c3 in std::__1::__shared_ptr_emplace<DB::MergeTreeIndexConditionSet, std::__1::allocator<DB::MergeTreeIndexConditionSet>>::__shared_ptr_emplace[abi:v15000]<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, DB::Block const&, unsigne>
    #10 0x55cf82b0a0c3 in std::__1::shared_ptr<DB::MergeTreeIndexConditionSet> std::__1::allocate_shared[abi:v15000]<DB::MergeTreeIndexConditionSet, std::__1::allocator<DB::MergeTreeIndexConditionSet>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&>
    #11 0x55cf82aef09c in std::__1::shared_ptr<DB::MergeTreeIndexConditionSet> std::__1::make_shared[abi:v15000]<DB::MergeTreeIndexConditionSet, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, DB::Block const&, unsigned long const&, DB::SelectQuery>
    #12 0x55cf82aef09c in DB::MergeTreeIndexSet::createIndexCondition(DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>) const build_docker/./src/Storages/MergeTree/MergeTreeIndexSet.cpp:703:12
    #13 0x55cf84951cd4 in DB::buildIndexes(std::__1::optional<DB::ReadFromMergeTree::Indexes>&, std::__1::shared_ptr<DB::ActionsDAG>, DB::MergeTreeData const&, std::__1::shared_ptr<DB::Context const> const&, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> c>
    #14 0x55cf84955ed3 in DB::ReadFromMergeTree::selectRangesToReadImpl(std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const>>>, std::__1::vector<std::__1::shared_ptr<DB::AlterConversions const>, std::__1::a>
    #15 0x55cf8494caef in DB::ReadFromMergeTree::selectRangesToRead(std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const>>>, std::__1::vector<std::__1::shared_ptr<DB::AlterConversions const>, std::__1::alloc>
    #16 0x55cf82a409a9 in DB::MergeTreeDataSelectExecutor::estimateNumMarksToRead(std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const>>>, std::__1::shared_ptr<DB::PrewhereInfo> const&, std::__1::vector<std:>
    #17 0x55cf827f728d in DB::MergeTreeData::canUseParallelReplicasBasedOnPKAnalysis(std::__1::shared_ptr<DB::Context const>, std::__1::shared_ptr<DB::StorageSnapshot> const&, DB::SelectQueryInfo&) const build_docker/./src/Storages/MergeTree/MergeTreeData.cpp:7295:30
    #18 0x55cf827f627e in DB::MergeTreeData::getQueryProcessingStage(std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, std::__1::shared_ptr<DB::StorageSnapshot> const&, DB::SelectQueryInfo&) const build_docker/./src/Storages/MergeTree/MergeTreeData.cpp:7255:14
    #19 0x55cf7f2f4969 in DB::InterpreterSelectQuery::getSampleBlockImpl() build_docker/./src/Interpreters/InterpreterSelectQuery.cpp:937:31
    #20 0x55cf7f2daa00 in DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basi>
    #21 0x55cf7f2c6691 in DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basi>
    #22 0x55cf7f2b98c6 in DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, s>
    #23 0x55cf7f520b98 in std::__1::__unique_if<DB::InterpreterSelectQuery>::__unique_single std::__1::make_unique[abi:v15000]<DB::InterpreterSelectQuery, std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>&, DB::SelectQueryOptions&, std::__1::vector<std::__1::basic_strin>
    #24 0x55cf7f520b98 in DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter(std::__1::shared_ptr<DB::IAST> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::>
    #25 0x55cf7f51b6cd in DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocato>
    #26 0x55cf7f1d8334 in std::__1::__unique_if<DB::InterpreterSelectWithUnionQuery>::__unique_single std::__1::make_unique[abi:v15000]<DB::InterpreterSelectWithUnionQuery, std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>&, DB::SelectQueryOptions const&>(std::__1::shared_ptr>
    #27 0x55cf7f1d4ea9 in DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) build_docker/./src/Interpreters/InterpreterFactory.cpp:162:16
    #28 0x55cf8012e485 in DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) build_docker/./src/Interpreters/executeQuery.cpp:1032:31
    #29 0x55cf80121bc1 in DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) build_docker/./src/Interpreters/executeQuery.cpp:1229:30
    #30 0x55cf8389295f in DB::TCPHandler::runImpl() build_docker/./src/Server/TCPHandler.cpp:424:24
    #31 0x55cf838d7dfb in DB::TCPHandler::run() build_docker/./src/Server/TCPHandler.cpp:2050:9
    #32 0x55cf8f50f75f in Poco::Net::TCPServerConnection::start() build_docker/./base/poco/Net/src/TCPServerConnection.cpp:43:3
    #33 0x55cf8f5105c1 in Poco::Net::TCPServerDispatcher::run() build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:115:20
    #34 0x55cf8fa969a5 in Poco::PooledThread::run() build_docker/./base/poco/Foundation/src/ThreadPool.cpp:188:14
    #35 0x55cf8fa937cd in Poco::(anonymous namespace)::RunnableHolder::run() build_docker/./base/poco/Foundation/src/Thread.cpp:45:11
    #36 0x55cf8fa90731 in Poco::ThreadImpl::runnableEntry(void*) build_docker/./base/poco/Foundation/src/Thread_POSIX.cpp:335:27
    #37 0x7f45059b1b42 in start_thread nptl/pthread_create.c:442:8
    #38 0x7f4505a439ff  misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

  Uninitialized value was created by a heap deallocation

```

**Comment by azat** [comment]
The problem is index analysis:

```
    #0 0x55658547c59e in DB::MergeTreeConditionInverted::traverseASTEquals(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, DB::RPNBuilderTreeNode const&, std::__1::shared_ptr<DB::IDataType const> const&, DB::Field const&, DB::MergeTreeConditionInve>
    #1 0x556585475566 in DB::MergeTreeConditionInverted::traverseAtomAST(DB::RPNBuilderTreeNode const&, DB::MergeTreeConditionInverted::RPNElement&) build_docker/./src/Storages/MergeTree/MergeTreeIndexInverted.cpp:438:21
    #2 0x55658547e73e in DB::MergeTreeConditionInverted::MergeTreeConditionInverted(DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>, DB::Block const&, DB::GinFilterParameters const&, DB::ITokenExtractor const*)::$_1::operator()(DB::RPNBuilderTreeNode const&, DB::MergeTreeC>
    #3 0x55658547e73e in decltype(std::declval<DB::MergeTreeConditionInverted::MergeTreeConditionInverted(DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>, DB::Block const&, DB::GinFilterParameters const&, DB::ITokenExtractor const*)::$_1&>()(std::declval<DB::RPNBuilderTree>
    #4 0x55658547e73e in bool std::__1::__invoke_void_return_wrapper<bool, false>::__call<DB::MergeTreeConditionInverted::MergeTreeConditionInverted(DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>, DB::Block const&, DB::GinFilterParameters const&, DB::ITokenExtractor const>
    #5 0x55658547e73e in std::__1::__function::__default_alloc_func<DB::MergeTreeConditionInverted::MergeTreeConditionInverted(DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>, DB::Block const&, DB::GinFilterParameters const&, DB::ITokenExtractor const*)::$_1, bool (DB::RPN>
    #6 0x55658547e73e in bool std::__1::__function::__policy_invoker<bool (DB::RPNBuilderTreeNode const&, DB::MergeTreeConditionInverted::RPNElement&)>::__call_impl<std::__1::__function::__default_alloc_func<DB::MergeTreeConditionInverted::MergeTreeConditionInverted(DB::SelectQueryInfo const&>
    #7 0x556585489e35 in std::__1::__function::__policy_func<bool (DB::RPNBuilderTreeNode const&, DB::MergeTreeConditionInverted::RPNElement&)>::operator()[abi:v15000](DB::RPNBuilderTreeNode const&, DB::MergeTreeConditionInverted::RPNElement&) const build_docker/./contrib/llvm-project/libcxx/>
    #8 0x556585489e35 in std::__1::function<bool (DB::RPNBuilderTreeNode const&, DB::MergeTreeConditionInverted::RPNElement&)>::operator()(DB::RPNBuilderTreeNode const&, DB::MergeTreeConditionInverted::RPNElement&) const build_docker/./contrib/llvm-project/libcxx/include/__functional/function>
    #9 0x556585489e35 in DB::RPNBuilder<DB::MergeTreeConditionInverted::RPNElement>::traverseTree(DB::RPNBuilderTreeNode const&) build_docker/./src/Storages/MergeTree/RPNBuilder.h:252:14
    #10 0x556585489921 in DB::RPNBuilder<DB::MergeTreeConditionInverted::RPNElement>::traverseTree(DB::RPNBuilderTreeNode const&) build_docker/./src/Storages/MergeTree/RPNBuilder.h:239:21
    #11 0x556585489921 in DB::RPNBuilder<DB::MergeTreeConditionInverted::RPNElement>::traverseTree(DB::RPNBuilderTreeNode const&) build_docker/./src/Storages/MergeTree/RPNBuilder.h:239:21
    #12 0x5565854804e6 in DB::RPNBuilder<DB::MergeTreeConditionInverted::RPNElement>::RPNBuilder(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, DB::Block, std::__1::shared_ptr<DB::PreparedSets>, std::__1::function<bool (DB::RPNBuilderTreeNode const&, DB::Merge>
    #13 0x55658546fb87 in DB::MergeTreeConditionInverted::MergeTreeConditionInverted(DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>, DB::Block const&, DB::GinFilterParameters const&, DB::ITokenExtractor const*) build_docker/./src/Storages/MergeTree/MergeTreeIndexInverted.>
    #14 0x55658548bd5c in DB::MergeTreeConditionInverted* std::__1::construct_at[abi:v15000]<DB::MergeTreeConditionInverted, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>&, DB::Block const&, DB::GinFilterParameters const&, DB::ITokenExtractor*, DB::MergeTreeConditionInve>
    #15 0x55658548bd5c in void std::__1::allocator_traits<std::__1::allocator<DB::MergeTreeConditionInverted>>::construct[abi:v15000]<DB::MergeTreeConditionInverted, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>&, DB::Block const&, DB::GinFilterParameters const&, DB::ITo>
    #16 0x55658548bd5c in std::__1::__shared_ptr_emplace<DB::MergeTreeConditionInverted, std::__1::allocator<DB::MergeTreeConditionInverted>>::__shared_ptr_emplace[abi:v15000]<DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>&, DB::Block const&, DB::GinFilterParameters const>
    #17 0x55658548bd5c in std::__1::shared_ptr<DB::MergeTreeConditionInverted> std::__1::allocate_shared[abi:v15000]<DB::MergeTreeConditionInverted, std::__1::allocator<DB::MergeTreeConditionInverted>, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>&, DB::Block const&, DB:>
    #18 0x55658547ceda in std::__1::shared_ptr<DB::MergeTreeConditionInverted> std::__1::make_shared[abi:v15000]<DB::MergeTreeConditionInverted, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>&, DB::Block const&, DB::GinFilterParameters const&, DB::ITokenExtractor*, void>(>
    #19 0x55658547ceda in DB::MergeTreeIndexInverted::createIndexCondition(DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>) const build_docker/./src/Storages/MergeTree/MergeTreeIndexInverted.cpp:716:12
    #20 0x556587125734 in DB::buildIndexes(std::__1::optional<DB::ReadFromMergeTree::Indexes>&, std::__1::shared_ptr<DB::ActionsDAG>, DB::MergeTreeData const&, std::__1::shared_ptr<DB::Context const> const&, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> c>
    #21 0x556587121aaa in DB::ReadFromMergeTree::applyFilters() build_docker/./src/Processors/QueryPlan/ReadFromMergeTree.cpp:1305:5
    #22 0x55658726cf4f in DB::QueryPlanOptimizations::optimizeTreeThirdPass(DB::QueryPlan::Node&, std::__1::list<DB::QueryPlan::Node, std::__1::allocator<DB::QueryPlan::Node>>&) build_docker/./src/Processors/QueryPlan/Optimizations/optimizeTree.cpp:201:38
    #23 0x5565870bc489 in DB::QueryPlan::optimize(DB::QueryPlanOptimizationSettings const&) build_docker/./src/Processors/QueryPlan/QueryPlan.cpp:485:5
    #24 0x5565870b919a in DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&) build_docker/./src/Processors/QueryPlan/QueryPlan.cpp:161:5
    #25 0x55658206385a in DB::InterpreterSelectWithUnionQuery::execute() build_docker/./src/Interpreters/InterpreterSelectWithUnionQuery.cpp:379:31
    #26 0x556582c15c50 in DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) build_docker/./src/Interpreters/executeQuery.cpp:751:40
    #27 0x556582c09681 in DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) build_docker/./src/Interpreters/executeQuery.cpp:1173:30
    #28 0x5565860e7bd7 in DB::TCPHandler::runImpl() build_docker/./src/Server/TCPHandler.cpp:421:24
    #29 0x556586126e9e in DB::TCPHandler::run() build_docker/./src/Server/TCPHandler.cpp:2057:9
    #30 0x5565919f4ebf in Poco::Net::TCPServerConnection::start() build_docker/./base/poco/Net/src/TCPServerConnection.cpp:43:3
    #31 0x5565919f5d21 in Poco::Net::TCPServerDispatcher::run() build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:115:20
    #32 0x556591f69fc5 in Poco::PooledThread::run() build_docker/./base/poco/Foundation/src/ThreadPool.cpp:188:14
    #33 0x556591f66ded in Poco::(anonymous namespace)::RunnableHolder::run() build_docker/./base/poco/Foundation/src/Thread.cpp:45:11
    #34 0x556591f63d51 in Poco::ThreadImpl::runnableEntry(void*) build_docker/./base/poco/Foundation/src/Thread_POSIX.cpp:335:27
    #35 0x7fb918645b42 in start_thread nptl/pthread_create.c:442:8
    #36 0x7fb9186d79ff  misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```
