### ISSUE TITLE
runtime error: member call on null pointer of type 'DB::TypePromotion<DB::IAST>'

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#52214]
https://s3.amazonaws.com/clickhouse-test-reports/0/67e9de14de6f1e75981a58327e2ef0380fe758ba/fuzzer_astfuzzerubsan/report.html

```
/build/src/Client/QueryFuzzer.cpp:863:36: runtime error: member call on null pointer of type 'DB::TypePromotion<DB::IAST>'
    #0 0x55b30482a541 in DB::QueryFuzzer::notifyQueryFailed(std::__1::shared_ptr<DB::IAST>) build_docker/./src/Client/QueryFuzzer.cpp:863:36
    #1 0x55b2f50ab4ce in DB::Client::processWithFuzzing(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) build_docker/./programs/client/Client.cpp:909:20
    #2 0x55b304770894 in DB::ClientBase::executeMultiQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) build_docker/./src/Client/ClientBase.cpp:2024:26
    #3 0x55b30477335f in DB::ClientBase::processMultiQueryFromFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) build_docker/./src/Client/ClientBase.cpp:2432:12
    #4 0x55b30477891e in DB::ClientBase::runNonInteractive() build_docker/./src/Client/ClientBase.cpp:2449:18
    #5 0x55b2f50a0d71 in DB::Client::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) build_docker/./programs/client/Client.cpp:372:9
    #6 0x55b3061b8f52 in Poco::Util::Application::run() build_docker/./base/poco/Util/src/Application.cpp:315:8
    #7 0x55b2f50bb866 in mainEntryClickHouseClient(int, char**) build_docker/./programs/client/Client.cpp:1433:23
    #8 0x55b2e87d861f in main build_docker/./programs/main.cpp:487:12
    #9 0x7fb3e9587d8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #10 0x7fb3e9587e3f in __libc_start_main csu/../csu/libc-start.c:392:3
    #11 0x55b2e87af66d in _start (/workspace/clickhouse+0x2b8b066d) (BuildId: bc26fc7beb175df9c56f936c10a522979eb2fc43)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /build/src/Client/QueryFuzzer.cpp:863:36 in 
```

**Comment by alexey-milovidov** [comment]
@akuzm, this is an error in AST Fuzzer.
