### ISSUE TITLE
SIGILL in fuzzer with TSAN

### ISSUE THREAD

**Issue by antonio2368** [ClickHouse/ClickHouse#52311]
Fuzzer with TSAN sometimes gets `SIGILL` because of a failed check:
```
CHECK failed: sanitizer_stack_store.cpp:80 "((block_idx)) < (((sizeof(blocks_)/sizeof((blocks_)[0]))))" (0x1000, 0x1000) (tid=184)
```
https://s3.amazonaws.com/clickhouse-test-reports/0/8d10dd71f7e86c431bb9eeb76a1dee182dff8f1e/fuzzer_astfuzzertsan/report.html

Complete stacktrace:
```
#0  0x00005583f3a1b7f6 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) ()
#1  0x00005583f3a20de0 in __sanitizer::StackStore::Alloc(unsigned long, unsigned long*, unsigned long*) ()
#2  0x00005583f3a20c54 in __sanitizer::StackStore::Store(__sanitizer::StackTrace const&, unsigned long*) ()
#3  0x00005583f3a22d4b in __sanitizer::StackDepotNode::store(unsigned int, __sanitizer::StackTrace const&, unsigned long long) ()
#4  0x00005583f3a231d1 in __sanitizer::StackDepotBase<__sanitizer::StackDepotNode, 1, 20>::Put(__sanitizer::StackTrace, bool*) ()
#5  0x00005583f3aa2c6c in __tsan::CurrentStackId(__tsan::ThreadState*, unsigned long) ()
#6  0x00005583f3a0b5e3 in __sanitizer::DD::MutexInit(__sanitizer::DDCallback*, __sanitizer::DDMutex*) ()
#7  0x00005583f3aae1bd in __tsan::DDMutexInit(__tsan::ThreadState*, unsigned long, __tsan::SyncVar*) ()
#8  0x00005583f3ab9313 in __tsan::MetaMap::GetSync(__tsan::ThreadState*, unsigned long, unsigned long, bool, bool) ()
#9  0x00005583f3ab15c9 in __tsan::Release(__tsan::ThreadState*, unsigned long, unsigned long) ()
#10 0x00005583f3a3105d in __tsan::FdRelease(__tsan::ThreadState*, unsigned long, int) ()
#11 0x00005583f3a436a4 in write ()
#12 0x00005583fbeb4a4d in DB::WriteBufferFromFileDescriptorDiscardOnFailure::nextImpl (this=<optimized out>) at ./src/IO/WriteBufferFromFileDescriptorDiscardOnFailure.cpp:16
#13 0x00005583f3aee11f in DB::WriteBuffer::write(char const*, unsigned long) ()
#14 0x00005583fc14d04b in DB::writePODBinary<DB::ThreadStatus*> (x=<error reading variable>, buf=...) at ./src/IO/WriteHelpers.h:88
#15 signalHandler (sig=<optimized out>, info=<optimized out>, context=<optimized out>) at ./src/Daemon/BaseDaemon.cpp:159
#16 0x00005583f3a3da00 in __tsan::CallUserSignalHandler(__tsan::ThreadState*, bool, bool, int, __sanitizer::__sanitizer_siginfo*, void*) ()
#17 0x00005583f3a3df26 in sighandler(int, __sanitizer::__sanitizer_siginfo*, void*) ()
#18 0x00007f98d8b3d520 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#19 0x0000000000000007 in ?? ()
#20 0x0000000000000000 in ?? ()
```

AFAIU, the stack frames are stored in fixed amount of blocks:
```
  static constexpr uptr kBlockSizeFrames = 0x100000;
  static constexpr uptr kBlockCount = 0x1000;
  static constexpr uptr kBlockSizeBytes = kBlockSizeFrames * sizeof(uptr);
```

Seems like we fill all the blocks causing the check to fail (total number of frames is `kBlockSizeFrames * kBlockCount`)

I didn't find any other place that seems wrong but I'm also not sure what we can do in a case like this. Maybe limit how long we run tests in TSAN fuzzer?

**Comment by alexey-milovidov** [comment]
The report from the signal handler is secondary to some other report - could you please send a link to it?

**Comment by antonio2368** [comment]
Forgot to paste report, added to the issue description.

**Comment by Algunenano** [comment]
The report is now gone, so it's not possible to investigate
