### ISSUE TITLE
use-of-uninitialized-value in CRC32 from zlib

### ISSUE THREAD

**Issue by azat** [ClickHouse/ClickHouse#52462]
**How to reproduce**

```sql
SELECT CRC32(murmurHash3_128())
```

**Error message and/or stacktrace**

```
==695==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x55794244de2d in crc32_little build_docker/./contrib/zlib-ng/crc32.c:117:9
    #1 0x55794244d632 in crc32_z build_docker/./contrib/zlib-ng/crc32.c:30:27
    #2 0x5578f7c05bfe in DB::FunctionStringOrArrayToT<DB::(anonymous namespace)::CRCFunctionWrapper<(anonymous namespace)::CRC32ZLIBImpl>, (anonymous namespace)::CRC32ZLIBImpl, unsigned int, true>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const CRC.cpp
    #3 0x5578f7c19ae1 in DB::IFunction::executeImplDryRun(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/usr/bin/clickhouse+0xfb3dae1) (BuildId: bdc944d42ec637925902788011ce430bb1e71924)
    #4 0x5578f7c19417 in DB::FunctionToExecutableFunctionAdaptor::executeDryRunImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/usr/bin/clickhouse+0xfb3d417) (BuildId: bdc944d42ec637925902788011ce430bb1e71924)
    #5 0x557924a74159 in DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_docker/./src/Functions/IFunction.cpp:245:15
    #6 0x557924a76244 in DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_docker/./src/Functions/IFunction.cpp:302:22
    #7 0x557924a7bfb7 in DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_docker/./src/Functions/IFunction.cpp:374:16
    #8 0x5579265ec804 in DB::executeActionForHeader(DB::ActionsDAG::Node const*, std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>>) build_docker/./src/Interpreters/ActionsDAG.cpp:541:49
    #9 0x5579265ec804 in DB::ActionsDAG::updateHeader(DB::Block) const build_docker/./src/Interpreters/ActionsDAG.cpp:660:44
    #10 0x55792d8ea122 in DB::ExpressionTransform::transformHeader(DB::Block, DB::ActionsDAG const&) build_docker/./src/Processors/Transforms/ExpressionTransform.cpp:8:23
    #11 0x55792ddff8cf in DB::ExpressionStep::ExpressionStep(DB::DataStream const&, std::__1::shared_ptr<DB::ActionsDAG> const&) build_docker/./src/Processors/QueryPlan/ExpressionStep.cpp:31:9
    #12 0x557928ba2b79 in std::__1::__unique_if<DB::ExpressionStep>::__unique_single std::__1::make_unique[abi:v15000]<DB::ExpressionStep, DB::DataStream const&, std::__1::shared_ptr<DB::ActionsDAG> const&>(DB::DataStream const&, std::__1::shared_ptr<DB::ActionsDAG> const&) build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:714:32
    #13 0x557928ba2b79 in DB::InterpreterSelectQuery::executeExpression(DB::QueryPlan&, std::__1::shared_ptr<DB::ActionsDAG> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) build_docker/./src/Interpreters/InterpreterSelectQuery.cpp:2795:28
    #14 0x557928b808a3 in DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::__1::optional<DB::Pipe>) build_docker/./src/Interpreters/InterpreterSelectQuery.cpp:1751:21
    #15 0x557928b79d0c in DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) build_docker/./src/Interpreters/InterpreterSelectQuery.cpp:899:5
    #16 0x557928db35da in DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) build_docker/./src/Interpreters/InterpreterSelectWithUnionQuery.cpp:303:38
    #17 0x557928db5edc in DB::InterpreterSelectWithUnionQuery::execute() build_docker/./src/Interpreters/InterpreterSelectWithUnionQuery.cpp:377:5
    #18 0x55792998b7f1 in DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) build_docker/./src/Interpreters/executeQuery.cpp:1074:40
    #19 0x55792997f141 in DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) build_docker/./src/Interpreters/executeQuery.cpp:1212:30
    #20 0x55792cea95b7 in DB::TCPHandler::runImpl() build_docker/./src/Server/TCPHandler.cpp:421:24
    #21 0x55792ceef63e in DB::TCPHandler::run() build_docker/./src/Server/TCPHandler.cpp:2049:9
    #22 0x5579388b3abf in Poco::Net::TCPServerConnection::start() build_docker/./base/poco/Net/src/TCPServerConnection.cpp:43:3
    #23 0x5579388b4921 in Poco::Net::TCPServerDispatcher::run() build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:115:20
    #24 0x557938e279c5 in Poco::PooledThread::run() build_docker/./base/poco/Foundation/src/ThreadPool.cpp:188:14
    #25 0x557938e247ed in Poco::(anonymous namespace)::RunnableHolder::run() build_docker/./base/poco/Foundation/src/Thread.cpp:45:11
    #26 0x557938e21751 in Poco::ThreadImpl::runnableEntry(void*) build_docker/./base/poco/Foundation/src/Thread_POSIX.cpp:335:27
    #27 0x7f9e18c93b42  (/lib/x86_64-linux-gnu/libc.so.6+0x94b42) (BuildId: 69389d485a9793dbe873f0ea2c93e02efaa9aa3d)
    #28 0x7f9e18d24bb3 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x125bb3) (BuildId: 69389d485a9793dbe873f0ea2c93e02efaa9aa3d)

  Uninitialized value was created by a heap allocation
    #0 0x5578f7ba9582 in malloc (/usr/bin/clickhouse+0xfacd582) (BuildId: bdc944d42ec637925902788011ce430bb1e71924)
    #1 0x557910125a46 in Allocator<false>::allocNoTrack(unsigned long, unsigned long) build_docker/./src/Common/Allocator.h:154:23
    #2 0x557910125629 in Allocator<false>::alloc(unsigned long, unsigned long) build_docker/./src/Common/Allocator.h:76:16
    #3 0x5578f7ebe95d in DB::PODArray<wide::integer<128ul, unsigned int>, 4096ul, Allocator<false>, 63ul, 64ul>::PODArray(unsigned long) (/usr/bin/clickhouse+0xfde295d) (BuildId: bdc944d42ec637925902788011ce430bb1e71924)
    #4 0x5578fa64ee91 in DB::TargetSpecific::Default::FunctionAnyHash<DB::MurmurHash3Impl128, false, char, char>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/usr/bin/clickhouse+0x12572e91) (BuildId: bdc944d42ec637925902788011ce430bb1e71924)
    #5 0x5578f9755879 in DB::ImplementationSelector<DB::IFunction>::selectAndExecute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/usr/bin/clickhouse+0x11679879) (BuildId: bdc944d42ec637925902788011ce430bb1e71924)
    #6 0x5578fa64ebb1 in DB::FunctionAnyHash<DB::MurmurHash3Impl128, false, char, char>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/usr/bin/clickhouse+0x12572bb1) (BuildId: bdc944d42ec637925902788011ce430bb1e71924)
    #7 0x5578f7c19ae1 in DB::IFunction::executeImplDryRun(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/usr/bin/clickhouse+0xfb3dae1) (BuildId: bdc944d42ec637925902788011ce430bb1e71924)
    #8 0x5578f7c19417 in DB::FunctionToExecutableFunctionAdaptor::executeDryRunImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/usr/bin/clickhouse+0xfb3d417) (BuildId: bdc944d42ec637925902788011ce430bb1e71924)
    #9 0x557924a74159 in DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_docker/./src/Functions/IFunction.cpp:245:15
    #10 0x557924a76244 in DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_docker/./src/Functions/IFunction.cpp:302:22
    #11 0x557924a7bfb7 in DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_docker/./src/Functions/IFunction.cpp:374:16
    #12 0x5579265ec804 in DB::executeActionForHeader(DB::ActionsDAG::Node const*, std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>>) build_docker/./src/Interpreters/ActionsDAG.cpp:541:49
    #13 0x5579265ec804 in DB::ActionsDAG::updateHeader(DB::Block) const build_docker/./src/Interpreters/ActionsDAG.cpp:660:44
    #14 0x55792d8ea122 in DB::ExpressionTransform::transformHeader(DB::Block, DB::ActionsDAG const&) build_docker/./src/Processors/Transforms/ExpressionTransform.cpp:8:23
    #15 0x55792ddff8cf in DB::ExpressionStep::ExpressionStep(DB::DataStream const&, std::__1::shared_ptr<DB::ActionsDAG> const&) build_docker/./src/Processors/QueryPlan/ExpressionStep.cpp:31:9
    #16 0x557928ba2b79 in std::__1::__unique_if<DB::ExpressionStep>::__unique_single std::__1::make_unique[abi:v15000]<DB::ExpressionStep, DB::DataStream const&, std::__1::shared_ptr<DB::ActionsDAG> const&>(DB::DataStream const&, std::__1::shared_ptr<DB::ActionsDAG> const&) build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:714:32
    #17 0x557928ba2b79 in DB::InterpreterSelectQuery::executeExpression(DB::QueryPlan&, std::__1::shared_ptr<DB::ActionsDAG> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) build_docker/./src/Interpreters/InterpreterSelectQuery.cpp:2795:28
    #18 0x557928b808a3 in DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::__1::optional<DB::Pipe>) build_docker/./src/Interpreters/InterpreterSelectQuery.cpp:1751:21
    #19 0x557928b79d0c in DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) build_docker/./src/Interpreters/InterpreterSelectQuery.cpp:899:5
    #20 0x557928db35da in DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) build_docker/./src/Interpreters/InterpreterSelectWithUnionQuery.cpp:303:38
    #21 0x557928db5edc in DB::InterpreterSelectWithUnionQuery::execute() build_docker/./src/Interpreters/InterpreterSelectWithUnionQuery.cpp:377:5
```

CI: https://s3.amazonaws.com/clickhouse-test-reports/52148/0f969923229375d72faac15257fc70bd7ece9095/stateless_tests__msan__[5_6].html

**Comment by azat** [comment]
Fixed in https://github.com/ClickHouse/ClickHouse/pull/52448
