### ISSUE TITLE
How to structure db in task management when high load?

### ISSUE THREAD

**Issue by fridary** [ClickHouse/ClickHouse#54488]
**OS**: Ubuntu 20.04.6 LTS
**ClickHouse**: 23.7.2.25 (official build)
**Server**: Intel(R) Xeon(R) CPU E5-2695 v4 @ 2.10GHz

I am creating a project where users send tasks to server and server executes it in queues. Amount of requests is around 100 tasks per second. In a loop script takes 1000 tasks from Clickhouse, do math operations and save results back. I need to make architecture where it takes less time to grab data and save.

The problem is how to structure database, when there are `ALTER TABLE` mutations and I get this errors:
```
2023-09-10 23:03:49,488 ERROR <class 'clickhouse_connect.driver.exceptions.DatabaseError'>: :HTTPDriver for http://127.0.0.1:8123 returned response code 500)
 Code: 692. DB::Exception: Too many unfinished mutations (1007) in table mydb.task (57439eaa-de08-403a-aa5e-5de99eb253d7). (TOO_MANY_MUTATIONS) (version 23.7.2.25 (official build))

2023-09-10 23:03:54,416 ERROR Traceback (most recent call last):
  File "/var/www/site.com/task.py", line 359, in <module>
    cl_client.query(f"ALTER TABLE task UPDATE executed=1 WHERE datetime >= '{tasks.result_rows[-1][7].replace(tzinfo=None)}' AND datetime <= '{tasks.result_rows[0][7].replace(tzinfo=None)}'")
  File "/home/fridary/miniconda3/envs/yolo/lib/python3.9/site-packages/clickhouse_connect/driver/client.py", line 186, in query
    response = self.command(query,
  File "/home/fridary/miniconda3/envs/yolo/lib/python3.9/site-packages/clickhouse_connect/driver/httpclient.py", line 331, in command
    response = self._raw_request(payload, params, headers, method, fields=fields)
  File "/home/fridary/miniconda3/envs/yolo/lib/python3.9/site-packages/clickhouse_connect/driver/httpclient.py", line 432, in _raw_request
    self._error_handler(response)
  File "/home/fridary/miniconda3/envs/yolo/lib/python3.9/site-packages/clickhouse_connect/driver/httpclient.py", line 357, in _error_handler
    raise OperationalError(err_str) if retried else DatabaseError(err_str) from None
clickhouse_connect.driver.exceptions.DatabaseError: :HTTPDriver for http://127.0.0.1:8123 returned response code 500)
 Code: 692. DB::Exception: Too many unfinished mutations (1007) in table mydb.task (57439eaa-de08-403a-aa5e-5de99eb253d7). (TOO_MANY_MUTATIONS) (version 23.7.2.25 (official build))
```

I guess there is one way is to set `<mutations_sync>1</mutations_sync>`, but I'd like to make more correct.

task table:
```
CREATE TABLE db.task
(
    uuid UUID,
    body  String NOT NULL,
    executed  UInt8 NOT NULL DEFAULT 0,
    datetime  DateTime64(5) NOT NULL DEFAULT now()
)
ENGINE = MergeTree()
PRIMARY KEY (uuid, datetime)
ORDER BY (uuid, datetime);
```

result table:
```
CREATE TABLE smart_captcha.task_result
(
    task_uuid UUID,
    result Nullable(String),
    datetime  DateTime64(5) NOT NULL DEFAULT now()
)
ENGINE = MergeTree()
PRIMARY KEY (task_uuid, datetime)
ORDER BY (task_uuid, datetime);
```

Simple code on python to show what happens:
```python
def execute_task(uuid, body, datetime):
    # .. math operations ..

    # save results
    cl_client.insert('task_result', [[uuid, 'any result']], column_names=['task_uuid', 'result'])

if __name__ == "__main__":
    while 1:
        # take last 1000 tasks executed=0
        tasks = cl_client.query(f"SELECT uuid, body, datetime FROM task WHERE executed=0 ORDER BY datetime DESC LIMIT 1000")

        # mark them as executed=1 in order not to execute again
        # I use first and last datetime values to select range 
        cl_client.query(f"ALTER TABLE task UPDATE executed=1 WHERE datetime >= '{tasks.result_rows[-1][2]}' AND datetime <= '{tasks.result_rows[0][2]}'")

        args = []
        for i, row in enumerate(tasks.result_rows):
            # uuid, body, datetime
            args.append((row[0], row[1], row[2]))
        
        # execute tasks asynchronously
        pool.starmap_async(execute_task, args)
```

Did I choose correct `ENGINE` for such kind of job?
How can I get around this query with `ALTER TABLE`?

**Comment by den-crane** [comment]
Clickhouse is not Redis and is not Postgresql. You should not use Clickhouse for this. Use another database.
At least use ReplacingMergeTree, not mutations.

**Comment by fridary** [comment]
@den-crane thank you for reply.
I supposed 1000 operations with mutations per 1-2 seconds not much for Clickhouse, doesn't it?
For better performance I tried to turn off async mutation, but get this error, where is mistake?

`<mutations_sync>1</mutations_sync>` in config.xml and `sudo systemctl restart clickhouse-server`, clickhouse-server show errors:
```

$ journalctl -xe
сен 11 06:03:12 sirjay-pc rsyslogd[1479]: action 'action-0-builtin:omfile' suspended (module 'builtin:omfile'), retry 0. There should be messages before this>
сен 11 06:03:12 sirjay-pc rsyslogd[1479]: action 'action-0-builtin:omfile' resumed (module 'builtin:omfile') [v8.2001.0 try https://www.rsyslog.com/e/2359 ]
сен 11 06:03:12 sirjay-pc rsyslogd[1479]: action 'action-0-builtin:omfile' suspended (module 'builtin:omfile'), retry 0. There should be messages before this>
сен 11 06:03:12 sirjay-pc rsyslogd[1479]: action 'action-0-builtin:omfile' resumed (module 'builtin:omfile') [v8.2001.0 try https://www.rsyslog.com/e/2359 ]
сен 11 06:03:12 sirjay-pc rsyslogd[1479]: action 'action-0-builtin:omfile' suspended (module 'builtin:omfile'), retry 0. There should be messages before this>
сен 11 06:03:12 sirjay-pc rsyslogd[1479]: action 'action-0-builtin:omfile' resumed (module 'builtin:omfile') [v8.2001.0 try https://www.rsyslog.com/e/2359 ]
сен 11 06:03:12 sirjay-pc rsyslogd[1479]: action 'action-0-builtin:omfile' suspended (module 'builtin:omfile'), retry 0. There should be messages before this>
сен 11 06:03:12 sirjay-pc rsyslogd[1479]: action 'action-0-builtin:omfile' resumed (module 'builtin:omfile') [v8.2001.0 try https://www.rsyslog.com/e/2359 ]
сен 11 06:03:12 sirjay-pc rsyslogd[1479]: action 'action-0-builtin:omfile' suspended (module 'builtin:omfile'), retry 0. There should be messages before this>
сен 11 06:03:12 sirjay-pc rsyslogd[1479]: action 'action-0-builtin:omfile' resumed (module 'builtin:omfile') [v8.2001.0 try https://www.rsyslog.com/e/2359 ]
сен 11 06:03:12 sirjay-pc rsyslogd[1479]: action 'action-0-builtin:omfile' suspended (module 'builtin:omfile'), retry 0. There should be messages before this>
сен 11 06:03:12 sirjay-pc rsyslogd[1479]: action 'action-0-builtin:omfile' resumed (module 'builtin:omfile') [v8.2001.0 try https://www.rsyslog.com/e/2359 ]
сен 11 06:03:12 sirjay-pc rsyslogd[1479]: action 'action-0-builtin:omfile' suspended (module 'builtin:omfile'), retry 0. There should be messages before this>
сен 11 06:03:12 sirjay-pc rsyslogd[1479]: action 'action-0-builtin:omfile' resumed (module 'builtin:omfile') [v8.2001.0 try https://www.rsyslog.com/e/2359 ]
сен 11 06:03:12 sirjay-pc rsyslogd[1479]: action 'action-0-builtin:omfile' suspended (module 'builtin:omfile'), retry 0. There should be messages before this>
сен 11 06:03:12 sirjay-pc rsyslogd[1479]: action 'action-0-builtin:omfile' suspended (module 'builtin:omfile'), next retry is Mon Sep 11 06:03:42 2023, retry>
сен 11 06:03:18 sirjay-pc clickhouse-server[14967]: Processing configuration file '/etc/clickhouse-server/config.xml'.
сен 11 06:03:18 sirjay-pc clickhouse-server[14967]: Saved preprocessed configuration to '/var/lib/clickhouse/preprocessed_configs/config.xml'.
сен 11 06:03:23 sirjay-pc sudo[15361]:   sirjay : TTY=pts/4 ; PWD=/home/sirjay ; USER=root ; COMMAND=/usr/bin/systemctl restart clickhouse-server
сен 11 06:03:23 sirjay-pc sudo[15361]: pam_unix(sudo:session): session opened for user root by sirjay(uid=0)
сен 11 06:03:23 sirjay-pc systemd[1]: Stopping ClickHouse Server (analytic DBMS for big data)...
-- Subject: A stop job for unit clickhouse-server.service has begun execution
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A stop job for unit clickhouse-server.service has begun execution.
-- 
-- The job identifier is 6533.
сен 11 06:03:23 sirjay-pc systemd[1]: clickhouse-server.service: Killing process 14967 (n/a) with signal SIGKILL.
сен 11 06:03:23 sirjay-pc systemd[1]: clickhouse-server.service: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The unit clickhouse-server.service has successfully entered the 'dead' state.
сен 11 06:03:23 sirjay-pc systemd[1]: Stopped ClickHouse Server (analytic DBMS for big data).
-- Subject: A stop job for unit clickhouse-server.service has finished
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A stop job for unit clickhouse-server.service has finished.
-- 
-- The job identifier is 6533 and the job result is done.
сен 11 06:03:23 sirjay-pc systemd[1]: Starting ClickHouse Server (analytic DBMS for big data)...
-- Subject: A start job for unit clickhouse-server.service has begun execution
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A start job for unit clickhouse-server.service has begun execution.
-- 
-- The job identifier is 6533.
сен 11 06:03:23 sirjay-pc clickhouse-server[15364]: Processing configuration file '/etc/clickhouse-server/config.xml'.
сен 11 06:03:23 sirjay-pc clickhouse-server[15364]: Logging trace to /var/log/clickhouse-server/clickhouse-server.log
сен 11 06:03:23 sirjay-pc clickhouse-server[15364]: Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
сен 11 06:03:23 sirjay-pc systemd[1]: clickhouse-server.service: Supervising process 15365 which is not our child. We'll most likely not notice when it exits.
сен 11 06:03:24 sirjay-pc systemd[1]: clickhouse-server.service: Killing process 15365 (n/a) with signal SIGKILL.
сен 11 06:03:24 sirjay-pc systemd[1]: clickhouse-server.service: Failed with result 'protocol'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The unit clickhouse-server.service has entered the 'failed' state with result 'protocol'.
сен 11 06:03:24 sirjay-pc systemd[1]: Failed to start ClickHouse Server (analytic DBMS for big data).
-- Subject: A start job for unit clickhouse-server.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A start job for unit clickhouse-server.service has finished with a failure.
-- 
-- The job identifier is 6533 and the job result is failed.
сен 11 06:03:24 sirjay-pc sudo[15361]: pam_unix(sudo:session): session closed for user root
сен 11 06:03:31 sirjay-pc kernel: [UFW BLOCK] IN=eno1 OUT= MAC=94:18:82:89:54:9c:00:f2:8b:50:3c:c0:08:00 SRC=89.248.165.159 DST=91.242.32.44 LEN=40 TOS=0x00 >

$ sudo systemctl status clickhouse-server.service
● clickhouse-server.service - ClickHouse Server (analytic DBMS for big data)
     Loaded: loaded (/lib/systemd/system/clickhouse-server.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: protocol) since
```

**Comment by den-crane** [comment]
>I supposed 1000 operations with mutations per 1-2 seconds not much for Clickhouse, doesn't it?

You are kidding? Mutations are admin operations.
Clickhouse expects that 1000 mutations will be executed within 1 year, not 1 second.

**Comment by fridary** [comment]
@den-crane what if `ALTER TABLE task UPDATE ...` replace to `DELETE FROM task WHERE ...` and then after making task math operations  create the same columns and values in new table `task_results` as was in `task` and with result column? That is good solution? So in loop take 1000 tasks from `task`, delete them and save results in `task_results`
