### ISSUE TITLE
"OSError: [Errno 24] Too many open files" even with high limits

### ISSUE THREAD

**Issue by fridary** [ClickHouse/ClickHouse#54652]
**OS:** Ubuntu 20.04.6 LTS
**ClickHouse:** 23.7.2.25 (official build)
**Server:** Intel(R) Xeon(R) CPU E5-2695 v4 @ 2.10GHz 72 cores

I read these topics about "Too many files open":
https://github.com/ClickHouse/ClickHouse/issues/8121
https://github.com/ClickHouse/ClickHouse/issues/14574

Error:
```
Traceback (most recent call last):
  File "/home/sirjay/miniconda3/envs/yolo/lib/python3.9/site-packages/clickhouse_connect/driver/httpclient.py", line 408, in _raw_request
  File "/home/sirjay/miniconda3/envs/yolo/lib/python3.9/site-packages/urllib3/request.py", line 78, in request
  File "/home/sirjay/miniconda3/envs/yolo/lib/python3.9/site-packages/urllib3/request.py", line 170, in request_encode_body
  File "/home/sirjay/miniconda3/envs/yolo/lib/python3.9/site-packages/urllib3/poolmanager.py", line 376, in urlopen
  File "/home/sirjay/miniconda3/envs/yolo/lib/python3.9/site-packages/urllib3/connectionpool.py", line 826, in urlopen
  File "/home/sirjay/miniconda3/envs/yolo/lib/python3.9/site-packages/urllib3/connectionpool.py", line 798, in urlopen
  File "/home/sirjay/miniconda3/envs/yolo/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8123): Max retries exceeded with url: /?wait_end_of_query=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f39b1acca00>: Failed to establish a new connection: [Errno 24] Too many open files'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/www/mysite/task.py", line 93, in _return_task
    cl_client = clickhouse_connect.get_client(**db_config_clickhouse)
  File "/home/sirjay/miniconda3/envs/yolo/lib/python3.9/site-packages/clickhouse_connect/__init__.py", line 8, in get_client
  File "/home/sirjay/miniconda3/envs/yolo/lib/python3.9/site-packages/clickhouse_connect/driver/__init__.py", line 110, in create_client
  File "/home/sirjay/miniconda3/envs/yolo/lib/python3.9/site-packages/clickhouse_connect/driver/httpclient.py", line 140, in __init__
  File "/home/sirjay/miniconda3/envs/yolo/lib/python3.9/site-packages/clickhouse_connect/driver/client.py", line 60, in __init__
  File "/home/sirjay/miniconda3/envs/yolo/lib/python3.9/site-packages/clickhouse_connect/driver/httpclient.py", line 331, in command
  File "/home/sirjay/miniconda3/envs/yolo/lib/python3.9/site-packages/clickhouse_connect/driver/httpclient.py", line 419, in _raw_request
clickhouse_connect.driver.exceptions.OperationalError: Error HTTPConnectionPool(host='127.0.0.1', port=8123): Max retries exceeded with url: /?wait_end_of_query=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f39b1acca00>: Failed to establish a new connection: [Errno 24] Too many open files')) executing HTTP request attempt 0 http://127.0.0.1:8123

2023-09-14 20:04:11,712 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc611cb9b80>: Failed to establish a new connection: [Errno 24] Too many open files')': /?wait_end_of_query=1
2023-09-14 20:04:11,713 WARNING Unexpected Http Driver Exception
2023-09-14 20:04:11,714 ERROR Traceback (most recent call last):
  File "/home/sirjay/miniconda3/envs/yolo/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
  File "/home/sirjay/miniconda3/envs/yolo/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
  File "/home/sirjay/miniconda3/envs/yolo/lib/python3.9/site-packages/urllib3/util/connection.py", line 76, in create_connection
  File "/home/sirjay/miniconda3/envs/yolo/lib/python3.9/socket.py", line 232, in __init__
OSError: [Errno 24] Too many open files
```

I use clickhouse only for `insert` command with load ~10 operations/second. After 1 hour of work server sends the error above.

Info:
```
$ sysctl fs.file-max
fs.file-max = 300000
$ ulimit -Hn
100000
$ ulimit -Sn
100000
$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 772764
max locked memory       (kbytes, -l) 65536
max memory size         (kbytes, -m) unlimited
open files                      (-n) 100000
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 772764
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
$ ps -ef|grep click
sirjay      7754       1  0 16:51 ?        00:00:00 clickhouse-watchdog        --config=/etc/clickhouse-server/config.xml --pid-file=/run/clickhouse-server/clickhouse-server.pid
sirjay      9047    7754 15 16:51 ?        00:30:05 /usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml --pid-file=/run/clickhouse-server/clickhouse-server.pid
sirjay     42586   15650  0 20:08 pts/1    00:00:00 grep --color=auto click
$ more /proc/9047/limits
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        1073741824           unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             772764               772764               processes 
Max open files            500000               500000               files     
Max locked memory         65536                65536                bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       772764               772764               signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us 
```

When I reboot server I get this:
```
$ cat /proc/sys/fs/file-nr
33872	0	300000
```

After 1 hour of work and getting errors:
```
$ cat /proc/sys/fs/file-nr
57488	0	300000
--^-------------------
this must be total opened files
```

What is mistake?
And the most important, why number of files in the system increases so fast? In 1 day there can be 24*57488=1.3 million of files?

database has 1 table:
```
CREATE TABLE test_table
(
    datetime  DateTime64(3) NOT NULL DEFAULT now(),
    user_id  UInt32 NOT NULL,
    var1  String NOT NULL,
    var2  String NOT NULL,
    num1  Float32 NOT NULL,
    num2  Int8 NOT NULL,
    num3  UInt32 NOT NULL DEFAULT 0,
    num4  Decimal64(3) NOT NULL
)
ENGINE = MergeTree()
PRIMARY KEY (user_id, (user_id, var1), (num3, var1), num3);
```
Maybe I set wrong indexes/primary key? 

Also I don't understand why clickhouse storage is 26 Gb:
```
$ sudo du -sh /var/lib/clickhouse
26G	/var/lib/clickhouse
```
I queried disk space and pointed that database and table on screenshot, where I get loads 10 operations/second. In 1 hour there is only `1.00 MiB`. No more other processes I use clickhouse, only this database and 1 table.
<img width="900" alt="Снимок экрана 2023-09-14 в 12 46 32" src="https://github.com/ClickHouse/ClickHouse/assets/3791864/64ca83ea-6378-489f-9516-c954c0efcf5f">

**Comment by den-crane** [comment]
>Also I don't understand why clickhouse storage is 26 Gb:

https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-system-tables-eat-my-disk/

**Comment by den-crane** [comment]
check
```
cat security/limits.d/clickhouse.conf
clickhouse	soft	nofile	1048576
clickhouse	hard	nofile	1048576
```

**Comment by den-crane** [comment]
>Too many open files

It's python error. Not Clickhouse.

**Comment by den-crane** [comment]
Clickhouse errors always have `DB::Exception`

using this pattern:
```
DB::Exception: Cannot open file .... errno: 24, strerror: Too many open files.
```

**Comment by fridary** [comment]
@den-crane do I understand correct, that if this is ClickHouse errors, that they will be stored here `/var/log/clickhouse-server/clickhouse-server.err.log`? I checked indeed this files and there were no `[Errno 24] Too many open files`
