### ISSUE TITLE
The associated promise has been destructed prior to the associated state becoming ready

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#55155]
https://s3.amazonaws.com/clickhouse-test-reports/0/ec7e0bcce95d0ccc2e4dc7ce46ea55a2e9f137f2/stress_test__asan_.html

```
[ 6210 ] {d125c7a4-c5fb-486b-955e-2dcb143f8412::all_2_2_0_10} <Fatal> : Logical error: \'std::exception. Code: 1001, type: std::__1::future_error, e.what() = The associated promise has been destructed prior to the associated state becoming ready. (version 23.9.1.1 (official build)), Stack trace:
 [ 16060 ] {d125c7a4-c5fb-486b-955e-2dcb143f8412::all_4_4_0_10} <Fatal> : Logical error: \'std::exception. Code: 1001, type: std::__1::future_error, e.what() = The associated promise has been destructed prior to the associated state becoming ready. (version 23.9.1.1 (official build)), Stack trace:
 [ 3489 ] {d125c7a4-c5fb-486b-955e-2dcb143f8412::all_3_3_0_10} <Fatal> : Logical error: \'std::exception. Code: 1001, type: std::__1::future_error, e.what() = The associated promise has been destructed prior to the associated state becoming ready. (version 23.9.1.1 (official build)), Stack trace:
 [ 2291 ] {} <Fatal> Application: Child process was terminated by signal 6.
 [ 6210 ] {d125c7a4-c5fb-486b-955e-2dcb143f8412::all_2_2_0_10} <Fatal> : Logical error: \'std::exception. Code: 1001, type: std::__1::future_error, e.what() = The associated promise has been destructed prior to the associated state becoming ready. (version 23.9.1.1 (official build)), Stack trace:
 [ 16060 ] {d125c7a4-c5fb-486b-955e-2dcb143f8412::all_4_4_0_10} <Fatal> : Logical error: \'std::exception. Code: 1001, type: std::__1::future_error, e.what() = The associated promise has been destructed prior to the associated state becoming ready. (version 23.9.1.1 (official build)), Stack trace:
 [ 3489 ] {d125c7a4-c5fb-486b-955e-2dcb143f8412::all_3_3_0_10} <Fatal> : Logical error: \'std::exception. Code: 1001, type: std::__1::future_error, e.what() = The associated promise has been destructed prior to the associated state becoming ready. (version 23.9.1.1 (official build)), Stack trace:
 [ 2291 ] {} <Fatal> Application: Child process was terminated by signal 6.

2023-09-22 16:15:45 Thread 1558 "QueryPullPipeEx" received signal SIGABRT, Aborted.
2023-09-22 16:15:45 [Switching to Thread 0x7f02d5136640 (LWP 6210)]
2023-09-22 16:15:45 0x00007f0bdd488a7c in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
2023-09-22 16:15:45 #0  0x00007f0bdd488a7c in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
2023-09-22 16:15:45 No symbol table info available.
2023-09-22 16:15:45 #1  0x00007f0bdd434476 in raise () from /lib/x86_64-linux-gnu/libc.so.6
2023-09-22 16:15:45 No symbol table info available.
2023-09-22 16:15:45 #2  0x00007f0bdd41a7f3 in abort () from /lib/x86_64-linux-gnu/libc.so.6
2023-09-22 16:15:45 No symbol table info available.
2023-09-22 16:15:45 #3  0x000055760d5cb428 in DB::abortOnFailedAssertion (description=...) at ./src/Common/Exception.cpp:50
2023-09-22 16:15:45         always_false = false
2023-09-22 16:15:45 #4  0x000055760d5d8095 in DB::getCurrentExceptionMessageAndPattern (with_stacktrace=<optimized out>, check_embedded_stacktrace=<optimized out>, with_extra_info=<optimized out>) at ./src/Common/Exception.cpp:442
2023-09-22 16:15:46         stream = {<DB::detail::StringHolder> = {value = {static __endian_factor = 1, __r_ = {<std::__1::__compressed_pair_elem<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__rep, 0, false>> = {__value_ = {{__l = {__data_ = 0x623005010100 
2023-09-22 16:15:46         message_format_string = {static npos = 18446744073709551615, __data = 0x0, __size = 0}
2023-09-22 16:15:46         e = <optimized out>
2023-09-22 16:15:46         e = <optimized out>
2023-09-22 16:15:46         e = <optimized out>
2023-09-22 16:15:46 #5  0x000055760d5db8f1 in DB::getCurrentExceptionMessage (with_stacktrace=false, check_embedded_stacktrace=true, with_extra_info=true) at ./src/Common/Exception.cpp:384
2023-09-22 16:15:47 No locals.
2023-09-22 16:15:47 #6  DB::ExecutionStatus::fromCurrentException (start_of_message=..., with_stacktrace=<optimized out>) at ./src/Common/Exception.cpp:621
2023-09-22 16:15:47         msg = <optimized out>
2023-09-22 16:15:47 #7  0x0000557625162f23 in DB::PipelineExecutor::execute (this=<optimized out>, num_threads=<optimized out>, concurrency_control=<optimized out>) at ./src/Processors/Executors/PipelineExecutor.cpp:123
2023-09-22 16:15:47         span = {<DB::OpenTelemetry::Span> = {trace_id = {t = {items = {0, 0}}}, span_id = 0, parent_span_id = 0, operation_name = {static __endian_factor = 1, __r_ = {<std::__1::__compressed_pair_elem<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<c
2023-09-22 16:15:47 #8  0x000055762518dd27 in DB::threadFunction (data=..., thread_group=..., num_threads=18, concurrency_control=<optimized out>) at ./src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:85
2023-09-22 16:15:47         scope_exit77 = {static is_nullable = false, function = {<No data fields>}}
2023-09-22 16:15:47 #9  DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0::operator()() const (this=<optimized out>) at ./src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:113
2023-09-22 16:15:47 No locals.
2023-09-22 16:15:47 #10 std::__1::__invoke[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&) (__f=...) at ./contrib/llvm-project/libcxx/include/__functional/invoke.h:394
2023-09-22 16:15:47 No locals.
2023-09-22 16:15:47 #11 std::__1::__apply_tuple_impl[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>) (__f=..., __t=...) a
2023-09-22 16:15:47 No locals.
2023-09-22 16:15:47 #12 std::__1::apply[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&) (__f=..., __t=...) at ./contrib/llvm-project/libcxx/include/tu
2023-09-22 16:15:47 No locals.
2023-09-22 16:15:47 #13 ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::{lambda()#1}::operator()() (this=0x604003ff2bd0) at ./src/Common/ThreadP
2023-09-22 16:16:03         thread_status = {<boost::noncopyable_::noncopyable> = {<boost::noncopyable_::base_token> = {<No data fields>}, <No data fields>}, thread_id = 6210, os_thread_priority = 0, performance_counters = {counters = 0x620007ab3080, counters_holder = {__ptr_ = {<std::__1::__compres
2023-09-22 16:16:03         scope_exit230 = {static is_nullable = false, function = {<No data fields>}}
2023-09-22 16:16:03         function = <optimized out>
2023-09-22 16:16:03         arguments = <optimized out>
2023-09-22 16:16:03 #14 std::__1::__invoke[abi:v15000]<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::{lambda()#1}&>(DB::PullingAsyncPipelineEx
2023-09-22 16:16:03 No locals.
2023-09-22 16:16:03 #15 std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::{lambda()#1}&
2023-09-22 16:16:03 No locals.
2023-09-22 16:16:03 #16 std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::{lambda()#1}, void ()>::opera
2023-09-22 16:16:03 No locals.
2023-09-22 16:16:03 #17 std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::
2023-09-22 16:16:03         __f = 0x604003ff2bd0
2023-09-22 16:16:03 #18 0x000055760d8aa9b2 in std::__1::__function::__policy_func<void ()>::operator()[abi:v15000]() const (this=0x7f02d4236110) at ./contrib/llvm-project/libcxx/include/__functional/function.h:848
2023-09-22 16:16:03 No locals.
2023-09-22 16:16:03 #19 std::__1::function<void ()>::operator()() const (this=0x7f02d4236110) at ./contrib/llvm-project/libcxx/include/__functional/function.h:1187
2023-09-22 16:16:03 No locals.
2023-09-22 16:16:03 #20 ThreadPoolImpl<std::__1::thread>::worker (this=0x61200001aec0, thread_it=...) at ./src/Common/ThreadPool.cpp:426
```

**Comment by alexey-milovidov** [comment]
No cases since November in our CI: https://pastila.nl/?000030ad/134fd7e20385cf706b068d6743fa93b4#6+LWmiuF7EnRjCJN0Ehv+A==

**Comment by alexey-milovidov** [comment]
Also checked Fatal.

**Comment by CheSema** [comment]
It is still with us.

**Comment by CheSema** [comment]
```
2025.07.30 18:10:01.050236 [ 2592496 ] {00408-wait-1-/home/sema/work/ClickHouse/tests/queries/0_stateless/00408_test_tydt9xxc_file_3.tmp.LvtvG1} <Fatal> : Logical error: 'std::exception. Code: 1001, type: std::__1::future_error, e.what() = The associated promise has been destructed prior to the associated state becoming ready. (version 25.8.1.1), Stack trace:

0. /home/sema/work/ClickHouse/contrib/llvm-project/libcxx/include/__exception/exception.h:113: std::logic_error::logic_error(std::logic_error const&) @ 0x0000000024d560f0
1. /home/sema/work/ClickHouse/contrib/llvm-project/libcxx/include/future:491: std::promise<void>::~promise() @ 0x0000000024d10e2e
2. /home/sema/work/ClickHouse/src/Interpreters/AsynchronousInsertQueue.h:135: DB::AsynchronousInsertQueue::InsertData::Entry::~Entry() @ 0x0000000018b0cedd
3. /home/sema/work/ClickHouse/contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:156: DB::AsynchronousInsertQueue::InsertData::~InsertData() @ 0x0000000018b0b6af
4. /home/sema/work/ClickHouse/contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:80: DB::AsynchronousInsertQueue::processData(DB::AsynchronousInsertQueue::InsertQuery, std::unique_ptr<DB::AsynchronousInsertQueue::InsertData, std::default_delete<DB::AsynchronousInsertQueue::InsertData>>, std::shared_ptr<DB::Context const>, DB::AsynchronousInsertQueue::QueueShardFlushTimeHistory&) @ 0x0000000018b050e4
5. /home/sema/work/ClickHouse/src/Interpreters/AsynchronousInsertQueue.cpp:333: void std::__function::__policy_invoker<void ()>::__call_impl[abi:se190107]<std::__function::__default_alloc_func<DB::AsynchronousInsertQueue::scheduleDataProcessingJob(DB::AsynchronousInsertQueue::InsertQuery const&, std::unique_ptr<DB::AsynchronousInsertQueue::InsertData, std::default_delete<DB::AsynchronousInsertQueue::InsertData>>, std::shared_ptr<DB::Context const>, unsigned long)::$_0, void ()>>(std::__function::__policy_storage const*) @ 0x0000000018b07d84
6. /home/sema/work/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x0000000012227873
7. /home/sema/work/ClickHouse/contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()::operator()() @ 0x000000001222dd66
8. /home/sema/work/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x0000000012224d46
9. /home/sema/work/ClickHouse/contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: void* std::__thread_proxy[abi:se190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x000000001222b5c0
10. start_thread @ 0x000000000009caa4
11. clone3 @ 0x0000000000129c3c
'.
```
But it is different case. It is not related to this issue. 

And it actualy was my mistake in my PR.
