### ISSUE TITLE
zookeeper learner handler error , socket closed which leads to detachment on clickhouse

### ISSUE THREAD

**Issue by AsjadLFC** [ClickHouse/ClickHouse#55465]
I am getting this error in zookeeper logs. zookeeper is connected to clickhouse in the setup.

Unexpected exception in LearnerHandler: 
java.net.SocketException: Socket closed
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:183)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:271)
	at java.base/java.io.DataInputStream.readInt(DataInputStream.java:392)
	at org.apache.jute.BinaryInputArchive.readInt(BinaryInputArchive.java:96)
	at org.apache.zookeeper.server.quorum.QuorumPacket.deserialize(QuorumPacket.java:86)
	at org.apache.jute.BinaryInputArchive.readRecord(BinaryInputArchive.java:134)
	at org.apache.zookeeper.server.quorum.LearnerHandler.run(LearnerHandler.java:656)

**Comment by tavplubix** [comment]
The error is not related to ClickHouse, we don't have any java code.
