### ISSUE TITLE
SystemLog: [WriteBufferFromS3] WriteBuffer is not finalized in destructor

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#57087]
[WriteBufferFromS3] WriteBuffer is not finalized in destructor

Report: https://s3.amazonaws.com/clickhouse-test-reports/57029/844125b5de5eb8b4210a89bb63e9b8a3ded085c1/stress_test__ubsan_.html

Trace:
```
 [ 27901 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
 [ 27901 ] {} <Fatal> BaseDaemon: (version 23.11.1.1, build id: 88262A5F2CEBEEC65170953213B086A62AA873D8, git hash: 6f007a4e50bce8cad5ddb1231321daf22694ded0) (from thread 27747) Received signal 6
 [ 27901 ] {} <Fatal> BaseDaemon: Signal description: Aborted
 [ 27901 ] {} <Fatal> BaseDaemon: 
 [ 27901 ] {} <Fatal> BaseDaemon: Stack trace: 0x00007fb0044519fc 0x00007fb0043fd476 0x00007fb0043e37f3 0x00005595bcb56968 0x00005595bcbfdf10 0x00005595c84da7ef 0x00005595c84daf0e 0x00005595c8cab01c 0x00005595c8caa6ae 0x00005595cb4d6b52 0x00005595cb4d6dae 0x00005595cb231190 0x00005595cb72f16e 0x0000
 [ 27901 ] {} <Fatal> BaseDaemon: ########################################
 [ 27901 ] {} <Fatal> BaseDaemon: (version 23.11.1.1, build id: 88262A5F2CEBEEC65170953213B086A62AA873D8, git hash: 6f007a4e50bce8cad5ddb1231321daf22694ded0) (from thread 27747) (no query) Received signal Aborted (6)
 [ 27901 ] {} <Fatal> BaseDaemon: 
 [ 27901 ] {} <Fatal> BaseDaemon: Stack trace: 0x00007fb0044519fc 0x00007fb0043fd476 0x00007fb0043e37f3 0x00005595bcb56968 0x00005595bcbfdf10 0x00005595c84da7ef 0x00005595c84daf0e 0x00005595c8cab01c 0x00005595c8caa6ae 0x00005595cb4d6b52 0x00005595cb4d6dae 0x00005595cb231190 0x00005595cb72f16e 0x0000
 [ 27901 ] {} <Fatal> BaseDaemon: 3. ? @ 0x00007fb0044519fc in ?
 [ 27901 ] {} <Fatal> BaseDaemon: 4. ? @ 0x00007fb0043fd476 in ?
 [ 27901 ] {} <Fatal> BaseDaemon: 5. ? @ 0x00007fb0043e37f3 in ?
 [ 27901 ] {} <Fatal> BaseDaemon: 6. ./build_docker/./src/Common/Exception.cpp:44: DB::abortOnFailedAssertion(String const&) @ 0x000000002358b968 in /usr/bin/clickhouse
 [ 27901 ] {} <Fatal> BaseDaemon: 7. ./build_docker/./src/IO/WriteBuffer.cpp:28: DB::WriteBuffer::~WriteBuffer() @ 0x0000000023632f10 in /usr/bin/clickhouse
 [ 27901 ] {} <Fatal> BaseDaemon: 8. ./build_docker/./src/IO/WriteBufferFromS3.cpp:266: DB::WriteBufferFromS3::~WriteBufferFromS3() @ 0x000000002ef0f7ef in /usr/bin/clickhouse
 [ 27901 ] {} <Fatal> BaseDaemon: 9. ./build_docker/./src/IO/WriteBufferFromS3.cpp:245: DB::WriteBufferFromS3::~WriteBufferFromS3() @ 0x000000002ef0ff0e in /usr/bin/clickhouse
 [ 27901 ] {} <Fatal> BaseDaemon: 10.1. inlined from ./src/IO/BufferWithOwnMemory.h:150: ~BufferWithOwnMemory
 [ 27901 ] {} <Fatal> BaseDaemon: 10. ./build_docker/./src/IO/WriteBufferFromFileDecorator.cpp:37: DB::WriteBufferFromFileDecorator::~WriteBufferFromFileDecorator() @ 0x000000002f6e001c in /usr/bin/clickhouse
 [ 27901 ] {} <Fatal> BaseDaemon: 11. ./src/Disks/IO/WriteBufferWithFinalizeCallback.h:14: DB::WriteBufferWithFinalizeCallback::~WriteBufferWithFinalizeCallback() @ 0x000000002f6df6ae in /usr/bin/clickhouse
 [ 27901 ] {} <Fatal> BaseDaemon: 12. ./src/Storages/MergeTree/MergeTreeDataPartWriterCompact.h:10: DB::MergeTreeDataPartWriterCompact::~MergeTreeDataPartWriterCompact() @ 0x0000000031f0bb52 in /usr/bin/clickhouse
 [ 27901 ] {} <Fatal> BaseDaemon: 13. ./src/Storages/MergeTree/MergeTreeDataPartWriterCompact.h:10: DB::MergeTreeDataPartWriterCompact::~MergeTreeDataPartWriterCompact() @ 0x0000000031f0bdae in /usr/bin/clickhouse
 [ 27901 ] {} <Fatal> BaseDaemon: 14. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:0: DB::IMergedBlockOutputStream::~IMergedBlockOutputStream() @ 0x0000000031c66190 in /usr/bin/clickhouse
 [ 27901 ] {} <Fatal> BaseDaemon: 15.1. inlined from ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48: std::default_delete<DB::MergedBlockOutputStream>::operator()[abi:v15000](DB::MergedBlockOutputStream*) const
 [ 27901 ] {} <Fatal> BaseDaemon: 15.2. inlined from ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:305: std::unique_ptr<DB::MergedBlockOutputStream, std::default_delete<DB::MergedBlockOutputStream>>::reset[abi:v15000](DB::MergedBlockOutputStream*)
 [ 27901 ] {} <Fatal> BaseDaemon: 15.3. inlined from ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
 [ 27901 ] {} <Fatal> BaseDaemon: 15.4. inlined from ./src/Storages/MergeTree/MergeTreeDataWriter.h:65: ~Stream
 [ 27901 ] {} <Fatal> BaseDaemon: 15. ./contrib/llvm-project/libcxx/include/__memory/construct_at.h:63: void std::__destroy_at[abi:v15000]<DB::MergeTreeDataWriter::TemporaryPart::Stream, 0>(DB::MergeTreeDataWriter::TemporaryPart::Stream*) @ 0x000000003216416e in /usr/bin/clickhouse
 [ 27901 ] {} <Fatal> BaseDaemon: 16.1. inlined from ./contrib/llvm-project/libcxx/include/vector:832: std::vector<DB::MergeTreeDataWriter::TemporaryPart::Stream, std::allocator<DB::MergeTreeDataWriter::TemporaryPart::Stream>>::__base_destruct_at_end[abi:v15000](DB::MergeTreeDataWriter::TemporaryPar
 [ 27901 ] {} <Fatal> BaseDaemon: 16.2. inlined from ./contrib/llvm-project/libcxx/include/vector:827: std::vector<DB::MergeTreeDataWriter::TemporaryPart::Stream, std::allocator<DB::MergeTreeDataWriter::TemporaryPart::Stream>>::__clear[abi:v15000]()
 [ 27901 ] {} <Fatal> BaseDaemon: 16. ./contrib/llvm-project/libcxx/include/vector:436: std::vector<DB::MergeTreeDataWriter::TemporaryPart::Stream, std::allocator<DB::MergeTreeDataWriter::TemporaryPart::Stream>>::~vector[abi:v15000]() @ 0x0000000032164077 in /usr/bin/clickhouse
 [ 27901 ] {} <Fatal> BaseDaemon: 17.1. inlined from ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:701: ~shared_ptr
 [ 27901 ] {} <Fatal> BaseDaemon: 17.2. inlined from ./src/Storages/MergeTree/MergeTreeDataWriter.h:61: ~TemporaryPart
 [ 27901 ] {} <Fatal> BaseDaemon: 17. ./build_docker/./src/Storages/MergeTree/MergeTreeSink.cpp:18: DB::MergeTreeSink::DelayedChunk::Partition::~Partition() @ 0x0000000032344a6e in /usr/bin/clickhouse
 [ 27901 ] {} <Fatal> BaseDaemon: 18.1. inlined from ./contrib/llvm-project/libcxx/include/vector:832: std::vector<DB::MergeTreeSink::DelayedChunk::Partition, std::allocator<DB::MergeTreeSink::DelayedChunk::Partition>>::__base_destruct_at_end[abi:v15000](DB::MergeTreeSink::DelayedChunk::Partition*)
 [ 27901 ] {} <Fatal> BaseDaemon: 18.2. inlined from ./contrib/llvm-project/libcxx/include/vector:827: std::vector<DB::MergeTreeSink::DelayedChunk::Partition, std::allocator<DB::MergeTreeSink::DelayedChunk::Partition>>::__clear[abi:v15000]()
 [ 27901 ] {} <Fatal> BaseDaemon: 18. ./contrib/llvm-project/libcxx/include/vector:436: std::vector<DB::MergeTreeSink::DelayedChunk::Partition, std::allocator<DB::MergeTreeSink::DelayedChunk::Partition>>::~vector[abi:v15000]() @ 0x000000003234497d in /usr/bin/clickhouse
 [ 27901 ] {} <Fatal> BaseDaemon: 19.1. inlined from ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48: std::default_delete<DB::MergeTreeSink::DelayedChunk>::operator()[abi:v15000](DB::MergeTreeSink::DelayedChunk*) const
 [ 27901 ] {} <Fatal> BaseDaemon: 19.2. inlined from ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:305: std::unique_ptr<DB::MergeTreeSink::DelayedChunk, std::default_delete<DB::MergeTreeSink::DelayedChunk>>::reset[abi:v15000](DB::MergeTreeSink::DelayedChunk*)
 [ 27901 ] {} <Fatal> BaseDaemon: 19.3. inlined from ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
 [ 27901 ] {} <Fatal> BaseDaemon: 19. ./build_docker/./src/Storages/MergeTree/MergeTreeSink.cpp:30: DB::MergeTreeSink::~MergeTreeSink() @ 0x0000000032340201 in /usr/bin/clickhouse
 [ 27901 ] {} <Fatal> BaseDaemon: 20. std::__shared_count::__release_shared[abi:v15000]() @ 0x00000000173e5380 in /usr/bin/clickhouse
 [ 27901 ] {} <Fatal> BaseDaemon: 21. std::__shared_weak_count::__release_shared[abi:v15000]() @ 0x00000000173e528f in /usr/bin/clickhouse
 [ 27901 ] {} <Fatal> BaseDaemon: 22. ./contrib/llvm-project/libcxx/include/vector:832: std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>::__base_destruct_at_end[abi:v15000](std::shared_ptr<DB::IProcessor>*) @ 0x000000002e1248c8 in /usr/bin/clickhouse
 [ 27901 ] {} <Fatal> BaseDaemon: 23.1. inlined from ./contrib/llvm-project/libcxx/include/vector:437: ~vector
 [ 27901 ] {} <Fatal> BaseDaemon: 23. ./contrib/llvm-project/libcxx/include/__memory/construct_at.h:63: void std::__destroy_at[abi:v15000]<std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>, 0>(std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std
 [ 27404 ] {} <Fatal> Application: Child process was terminated by signal 9 (KILL). If it is not done by \'forcestop\' command or manually, the possible cause is OOM Killer (see \'dmesg\' and look at the \'/var/log/kern.log\' for the details).
 [ 27747 ] {} <Fatal> : Logical error: \'false && "WriteBuffer is not finalized in destructor."\'.
```

2023-11-21 19:07:05 #62 0x00005595ca0fc4a3 in DB::SystemLog<DB::TraceLogElement>::flushImpl (this=this@entry=0x7fadd001aa48, to_flush=..., to_flush_end=to_flush_end@entry=454) at ./build_docker/./src/Interpreters/SystemLog.cpp:517
2023-11-21 19:07:05 No locals.
2023-11-21 19:07:05 #63 0x00005595ca0fa791 in DB::SystemLog<DB::TraceLogElement>::savingThreadFunction (this=0x7fadd001aa48) at ./build_docker/./src/Interpreters/SystemLog.cpp:456
2023-11-21 19:07:05         should_prepare_tables_anyway = false
2023-11-21 19:07:05         to_flush_end = 454
2023-11-21 19:07:05         exit_this_thread = true
2023-11-21 19:07:05         to_flush = {__begin_ = 0x7fad381fd1d0, __end_ = 0x7fad382062a8, __end_cap_ = {<std::__1::__compressed_pair_elem<DB::TraceLogElement*, 0, false>> = {__value_ = 0x7fad3820c1d0}, <std::__1::__compressed_pair_elem<std::__1::allocator<DB::TraceLogElement>, 1, true>> = {<std::__1::allocator<DB::TraceLogElement>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<DB::TraceLogElement> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}
2023-11-21 19:07:05 #64 0x00005595bcd1c76c in DB::SystemLogBase<DB::TraceLogElement>::startup()::{lambda()#1}::operator()() const (this=<optimized out>) at ./build_docker/./src/Common/SystemLogBase.cpp:248
2023-11-21 19:07:05 No locals.
2023-11-21 19:07:05 #65 std::__1::__invoke[abi:v15000]<DB::SystemLogBase<DB::TraceLogElement>::startup()::{lambda()#1}&>(DB::SystemLogBase<DB::TraceLogElement>::startup()::{lambda()#1}&) (__f=...) at ./contrib/llvm-project/libcxx/include/__functional/invoke.h:394
2023-11-21 19:07:05 No locals.
2023-11-21 19:07:05 #66 std::__1::__apply_tuple_impl[abi:v15000]<DB::SystemLogBase<DB::TraceLogElement>::startup()::{lambda()#1}&, std::__1::tuple<>&>(DB::SystemLogBase<DB::TraceLogElement>::startup()::{lambda()#1}&, std::__1::tuple<>&, std::__1::__tuple_indices<>) (__f=..., __t=...) at ./contrib/llvm-project/libcxx/include/tuple:1789
2023-11-21 19:07:05 No locals.
2023-11-21 19:07:05 #67 std::__1::apply[abi:v15000]<DB::SystemLogBase<DB::TraceLogElement>::startup()::{lambda()#1}&, std::__1::tuple<>&>(DB::SystemLogBase<DB::TraceLogElement>::startup()::{lambda()#1}&, std::__1::tuple<>&) (__f=..., __t=...) at ./contrib/llvm-project/libcxx/include/tuple:1798
2023-11-21 19:07:05 No locals.
2023-11-21 19:07:05 #68 ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::SystemLogBase<DB::TraceLogElement>::startup()::{lambda()#1}>(DB::SystemLogBase<DB::TraceLogElement>::startup()::{lambda()#1}&&)::{lambda()#1}::operator()() (this=0x5595dd0f72f0) at ./src/Common/ThreadPool.h:250

**Comment by alexey-milovidov** [comment]
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/43303
