### ISSUE TITLE
Hive Metastore expired  Which Hive version that Clickhouse support?

### ISSUE THREAD

**Issue by windylcx** [ClickHouse/ClickHouse#57340]
when query a hive engine table:
Received exception from server (version 22.11.1):
Code: 640. DB::Exception: Received from  xxx:9000. DB::Exception: Hive Metastore expired because No more data to read.. (NO_HIVEMETASTORE)

and the hiveserve query log:

2023-11-29T10:36:00,394 DEBUG [org.eclipse.jetty.server.session.HashSessionManager@50f4b83dTimer] server.session: Scavenging sessions at 1701225360394
2023-11-29T10:36:04,640 DEBUG [HiveServer2-Handler-Pool: Thread-98] transport.TSaslServerTransport: transport map does not contain key
2023-11-29T10:36:04,640 DEBUG [HiveServer2-Handler-Pool: Thread-98] transport.TSaslTransport: opening transport org.apache.thrift.transport.TSaslServerTransport@6106f218
2023-11-29T10:36:04,640 DEBUG [HiveServer2-Handler-Pool: Thread-98] transport.TSaslTransport: SERVER: Writing message with status ERROR and payload length 19
2023-11-29T10:36:04,640 DEBUG [HiveServer2-Handler-Pool: Thread-98] transport.TSaslServerTransport: failed to open server transport
org.apache.thrift.transport.TTransportException: Invalid status -128
	at org.apache.thrift.transport.TSaslTransport.sendAndThrowMessage(TSaslTransport.java:232) ~[hive-exec-3.1.2.jar:3.1.2]
	at org.apache.thrift.transport.TSaslTransport.receiveSaslMessage(TSaslTransport.java:184) ~[hive-exec-3.1.2.jar:3.1.2]
	at org.apache.thrift.transport.TSaslServerTransport.handleSaslStartMessage(TSaslServerTransport.java:125) ~[hive-exec-3.1.2.jar:3.1.2]
	at org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:271) ~[hive-exec-3.1.2.jar:3.1.2]
	at org.apache.thrift.transport.TSaslServerTransport.open(TSaslServerTransport.java:41) ~[hive-exec-3.1.2.jar:3.1.2]
	at org.apache.thrift.transport.TSaslServerTransport$Factory.getTransport(TSaslServerTransport.java:216) ~[hive-exec-3.1.2.jar:3.1.2]
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:269) ~[hive-exec-3.1.2.jar:3.1.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
2023-11-29T10:36:04,640 ERROR [HiveServer2-Handler-Pool: Thread-98] server.TThreadPoolServer: Error occurred during processing of message.
java.lang.RuntimeException: org.apache.thrift.transport.TTransportException: Invalid status -128
	at org.apache.thrift.transport.TSaslServerTransport$Factory.getTransport(TSaslServerTransport.java:219) ~[hive-exec-3.1.2.jar:3.1.2]
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:269) ~[hive-exec-3.1.2.jar:3.1.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: org.apache.thrift.transport.TTransportException: Invalid status -128
	at org.apache.thrift.transport.TSaslTransport.sendAndThrowMessage(TSaslTransport.java:232) ~[hive-exec-3.1.2.jar:3.1.2]
	at org.apache.thrift.transport.TSaslTransport.receiveSaslMessage(TSaslTransport.java:184) ~[hive-exec-3.1.2.jar:3.1.2]
	at org.apache.thrift.transport.TSaslServerTransport.handleSaslStartMessage(TSaslServerTransport.java:125) ~[hive-exec-3.1.2.jar:3.1.2]
	at org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:271) ~[hive-exec-3.1.2.jar:3.1.2]
	at org.apache.thrift.transport.TSaslServerTransport.open(TSaslServerTransport.java:41) ~[hive-exec-3.1.2.jar:3.1.2]
	at org.apache.thrift.transport.TSaslServerTransport$Factory.getTransport(TSaslServerTransport.java:216) ~[hive-exec-3.1.2.jar:3.1.2]
	... 4 more

may be is the hive version problem ?

**Comment by fxx-real** [comment]
Hi @windylcx , I'm also experiencing the same issue. Have you found a solution?
