### ISSUE TITLE
ColumnObject (experimental feature that is going to be removed): Crash with optimize_functions_to_subcolumns

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#57384]
Report: https://s3.amazonaws.com/clickhouse-test-reports/57315/025fcd3aa4ca3867c1c3510adb4804d7b85076c6/stateless_tests__aarch64_.html

Simplest reproducer:
```
$ git diff
diff --git a/tests/queries/0_stateless/01825_type_json_in_other_types.sh b/tests/queries/0_stateless/01825_type_json_in_other_types.sh
index e9cf0bcaca1..128ff3549bf 100755
--- a/tests/queries/0_stateless/01825_type_json_in_other_types.sh
+++ b/tests/queries/0_stateless/01825_type_json_in_other_types.sh
@@ -73,7 +73,7 @@ echo "============="
 
 $CLICKHOUSE_CLIENT -q "
     SELECT (data.2)['aa'] AS aa, (data.2)['bb'] AS bb
-    FROM t_json_nested ORDER BY id FORMAT JSONEachRow" --output_format_json_named_tuples_as_objects 1
+    FROM t_json_nested ORDER BY id FORMAT JSONEachRow" --output_format_json_named_tuples_as_objects 1 --optimize_functions_to_subcolumns 1
 
 echo "============="
```

```
#0  DB::ColumnObject::Subcolumn::isFinalized (this=0x338) at ./build/./src/Columns/ColumnObject.cpp:431
#1  DB::ColumnObject::isFinalized() const::$_0::operator()<std::__1::shared_ptr<DB::SubcolumnsTree<DB::ColumnObject::Subcolumn>::Node> >(std::__1::shared_ptr<DB::SubcolumnsTree<DB::ColumnObject::Subcolumn>::Node> const&) const (this=<optimized out>, 
    entry=...) at ./build/./src/Columns/ColumnObject.cpp:1065
#2  std::__1::all_of[abi:v15000]<std::__1::__wrap_iter<std::__1::shared_ptr<DB::SubcolumnsTree<DB::ColumnObject::Subcolumn>::Node> const*>, DB::ColumnObject::isFinalized() const::$_0>(std::__1::__wrap_iter<std::__1::shared_ptr<DB::SubcolumnsTree<DB::ColumnObject::Subcolumn>::Node> const*>, std::__1::__wrap_iter<std::__1::shared_ptr<DB::SubcolumnsTree<DB::ColumnObject::Subcolumn>::Node> const*>, DB::ColumnObject::isFinalized() const::$_0) (__first=..., __last=..., __pred=...)
    at ./contrib/llvm-project/libcxx/include/__algorithm/all_of.h:25
#3  DB::ColumnObject::isFinalized (this=<optimized out>) at ./build/./src/Columns/ColumnObject.cpp:1064
#4  0x000000001019b509 in DB::SerializationObject<DB::JSONDataParser<DB::SimdJSONParser> >::serializeBinaryBulkStatePrefix (this=0x7fe674e15c38, column=..., settings=..., state=...) at ./build/./src/DataTypes/Serializations/SerializationObject.cpp:169
#5  0x000000001019b657 in DB::SerializationObject<DB::JSONDataParser<DB::SimdJSONParser> >::serializeBinaryBulkStatePrefix (this=0x7fe674e15c38, column=..., settings=..., state=...) at ./build/./src/DataTypes/Serializations/SerializationObject.cpp:172
#6  0x000000001019b657 in DB::SerializationObject<DB::JSONDataParser<DB::SimdJSONParser> >::serializeBinaryBulkStatePrefix (this=0x7fe674e15c38, column=..., settings=..., state=...) at ./build/./src/DataTypes/Serializations/SerializationObject.cpp:172
#7  0x000000001015ed45 in DB::SerializationArray::serializeBinaryBulkStatePrefix (this=0x7fe6414e8fd8, column=..., settings=..., state=...) at ./build/./src/DataTypes/Serializations/SerializationArray.cpp:270
#8  0x0000000011f10350 in DB::writeData (serialization=..., ostr=..., offset=0, limit=0, column=...) at ./build/./src/Formats/NativeWriter.cpp:61
#9  DB::NativeWriter::write (this=0x7fe64144e400, block=...) at ./build/./src/Formats/NativeWriter.cpp:163
#10 0x0000000011ee2f17 in DB::TCPHandler::sendData (this=this@entry=0x7fe641730200, block=...) at ./build/./src/Server/TCPHandler.cpp:2168
#11 0x0000000011ee0ae7 in DB::TCPHandler::processOrdinaryQueryWithProcessors (this=this@entry=0x7fe641730200) at ./build/./src/Server/TCPHandler.cpp:1019
#12 0x0000000011ed73cd in DB::TCPHandler::runImpl (this=0x7fe641730200) at ./build/./src/Server/TCPHandler.cpp:520
#13 0x0000000011eed80a in DB::TCPHandler::run (this=0x7fe7121f0ae0) at ./build/./src/Server/TCPHandler.cpp:2292
#14 0x000000001486c6c7 in Poco::Net::TCPServerConnection::start (this=0x7fe7121f0ae0) at ./build/./base/poco/Net/src/TCPServerConnection.cpp:43
#15 0x000000001486cbba in Poco::Net::TCPServerDispatcher::run (this=0x7fe6708b3c00) at ./build/./base/poco/Net/src/TCPServerDispatcher.cpp:115
#16 0x00000000149bab1b in Poco::PooledThread::run (this=0x7fe85f7cab00) at ./build/./base/poco/Foundation/src/ThreadPool.cpp:188
#17 0x00000000149b81d1 in Poco::ThreadImpl::runnableEntry (pThread=<optimized out>) at ./base/poco/Foundation/src/Thread_POSIX.cpp:335
#18 0x00007fe8604659eb in start_thread (arg=<optimized out>) at pthread_create.c:444
#19 0x00007fe8604e97cc in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```

**Comment by Algunenano** [comment]
Closing. It should not appear again since we disable Object('json') from fuzzer and stress tests
