### ISSUE TITLE
[Analyzer] Crash with optimize_syntax_fuse_functions

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#57402]
Report: https://s3.amazonaws.com/clickhouse-test-reports/57315/64bd77fe9c0131ba9d9699c421e231e92242023a/stateless_tests__release__analyzer_.html

Reproducer via stateless tests:
```
clickhouse-client --queries-file 00506_union_distributed.sql --allow_experimental_analyzer=1 --optimize_syntax_fuse_functions 
```

The stacktrace of the thread that failed has ~7000 steps, so it looks like infinite recursion:

```
(gdb) bt
#0  0x0000000010ce9b34 in DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectSetsVisitor, true>::visit (this=this@entry=0x7f506e6009a8, query_tree_node=...) at ./src/Analyzer/InDepthQueryTreeVisitor.h:59
#1  0x0000000010ceb370 in DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectSetsVisitor, true>::visitChildren (this=0x7f506e6009a8, expression=...) at ./src/Analyzer/InDepthQueryTreeVisitor.h:91
#2  DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectSetsVisitor, true>::visit (this=this@entry=0x7f506e6009a8, query_tree_node=...) at ./src/Analyzer/InDepthQueryTreeVisitor.h:67
#3  0x0000000010ceb370 in DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectSetsVisitor, true>::visitChildren (this=0x7f506e6009a8, expression=...) at ./src/Analyzer/InDepthQueryTreeVisitor.h:91
#4  DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectSetsVisitor, true>::visit (this=this@entry=0x7f506e6009a8, query_tree_node=...) at ./src/Analyzer/InDepthQueryTreeVisitor.h:67
#5  0x0000000010ceb370 in DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectSetsVisitor, true>::visitChildren (this=0x7f506e6009a8, expression=...) at ./src/Analyzer/InDepthQueryTreeVisitor.h:91
#6  DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectSetsVisitor, true>::visit (this=this@entry=0x7f506e6009a8, query_tree_node=...) at ./src/Analyzer/InDepthQueryTreeVisitor.h:67
#7  0x0000000010ceb370 in DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectSetsVisitor, true>::visitChildren (this=0x7f506e6009a8, expression=...) at ./src/Analyzer/InDepthQueryTreeVisitor.h:91
#8  DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectSetsVisitor, true>::visit (this=this@entry=0x7f506e6009a8, query_tree_node=...) at ./src/Analyzer/InDepthQueryTreeVisitor.h:67
#9  0x0000000010ceb370 in DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectSetsVisitor, true>::visitChildren (this=0x7f506e6009a8, expression=...) at ./src/Analyzer/InDepthQueryTreeVisitor.h:91
#10 DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectSetsVisitor, true>::visit (this=this@entry=0x7f506e6009a8, query_tree_node=...) at ./src/Analyzer/InDepthQueryTreeVisitor.h:67
#11 0x0000000010ce9ae7 in DB::collectSets (node=..., planner_context=...) at ./build/./src/Planner/CollectSets.cpp:147
#12 0x0000000010ccdb44 in DB::Planner::buildPlanForQueryNode (this=0x7f506e601c90) at ./build/./src/Planner/Planner.cpp:1335
#13 0x0000000010ccb6e7 in DB::Planner::buildQueryPlanIfNeeded (this=this@entry=0x7f506e601c90) at ./build/./src/Planner/Planner.cpp:1196
#14 0x0000000010cce404 in DB::(anonymous namespace)::collectFiltersForAnalysis (query_tree=..., planner_context=...) at ./build/./src/Planner/Planner.cpp:198
#15 DB::Planner::buildPlanForQueryNode (this=0x7f506e602a10) at ./build/./src/Planner/Planner.cpp:1340
#16 0x0000000010ccb6e7 in DB::Planner::buildQueryPlanIfNeeded (this=this@entry=0x7f506e602a10) at ./build/./src/Planner/Planner.cpp:1196
#17 0x0000000010cce404 in DB::(anonymous namespace)::collectFiltersForAnalysis (query_tree=..., planner_context=...) at ./build/./src/Planner/Planner.cpp:198
#18 DB::Planner::buildPlanForQueryNode (this=0x7f506e603790) at ./build/./src/Planner/Planner.cpp:1340
#19 0x0000000010ccb6e7 in DB::Planner::buildQueryPlanIfNeeded (this=this@entry=0x7f506e603790) at ./build/./src/Planner/Planner.cpp:1196
#20 0x0000000010cce404 in DB::(anonymous namespace)::collectFiltersForAnalysis (query_tree=..., planner_context=...) at ./build/./src/Planner/Planner.cpp:198
#21 DB::Planner::buildPlanForQueryNode (this=0x7f506e604510) at ./build/./src/Planner/Planner.cpp:1340
#22 0x0000000010ccb6e7 in DB::Planner::buildQueryPlanIfNeeded (this=this@entry=0x7f506e604510) at ./build/./src/Planner/Planner.cpp:1196
#23 0x0000000010cce404 in DB::(anonymous namespace)::collectFiltersForAnalysis (query_tree=..., planner_context=...) at ./build/./src/Planner/Planner.cpp:198
#24 DB::Planner::buildPlanForQueryNode (this=0x7f506e605290) at ./build/./src/Planner/Planner.cpp:1340
#25 0x0000000010ccb6e7 in DB::Planner::buildQueryPlanIfNeeded (this=this@entry=0x7f506e605290) at ./build/./src/Planner/Planner.cpp:1196

...


#7237 0x0000000010ccb6e7 in DB::Planner::buildQueryPlanIfNeeded (this=this@entry=0x7f506edf1890) at ./build/./src/Planner/Planner.cpp:1196
#7238 0x0000000010cce404 in DB::(anonymous namespace)::collectFiltersForAnalysis (query_tree=..., planner_context=...) at ./build/./src/Planner/Planner.cpp:198
#7239 DB::Planner::buildPlanForQueryNode (this=0x7f506edf2610) at ./build/./src/Planner/Planner.cpp:1340
#7240 0x0000000010ccb6e7 in DB::Planner::buildQueryPlanIfNeeded (this=this@entry=0x7f506edf2610) at ./build/./src/Planner/Planner.cpp:1196
#7241 0x0000000010cce404 in DB::(anonymous namespace)::collectFiltersForAnalysis (query_tree=..., planner_context=...) at ./build/./src/Planner/Planner.cpp:198
#7242 DB::Planner::buildPlanForQueryNode (this=0x7f506edf2f48) at ./build/./src/Planner/Planner.cpp:1340
#7243 0x0000000010ccb6e7 in DB::Planner::buildQueryPlanIfNeeded (this=this@entry=0x7f506edf2f48) at ./build/./src/Planner/Planner.cpp:1196



#7244 0x0000000010ccc245 in DB::Planner::buildPlanForUnionNode (this=0x7f506edf3680) at ./build/./src/Planner/Planner.cpp:1221
#7245 0x0000000010ccb6e0 in DB::Planner::buildQueryPlanIfNeeded (this=0x7f506edf3680) at ./build/./src/Planner/Planner.cpp:1194
#7246 0x0000000010cf1779 in DB::(anonymous namespace)::buildQueryPlanForTableExpression (table_expression=..., select_query_info=..., select_query_options=..., planner_context=..., is_single_table_expression=<optimized out>, 
    wrap_read_columns_in_subquery=<optimized out>) at ./build/./src/Planner/PlannerJoinTree.cpp:895
#7247 0x0000000010ced631 in DB::buildJoinTreeQueryPlan (query_node=..., select_query_info=..., select_query_options=..., outer_scope_columns=..., planner_context=...) at ./build/./src/Planner/PlannerJoinTree.cpp:1562
#7248 0x0000000010ccef44 in DB::Planner::buildPlanForQueryNode (this=0x7f4f2387f068) at ./build/./src/Planner/Planner.cpp:1366
#7249 0x0000000010ccb6e7 in DB::Planner::buildQueryPlanIfNeeded (this=0x7f4f2387f068) at ./build/./src/Planner/Planner.cpp:1196
#7250 0x0000000010cca98d in DB::InterpreterSelectQueryAnalyzer::getQueryPlan (this=0x7f4f2387f000) at ./build/./src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:238
#7251 0x000000001107c983 in DB::executeQueryImpl (
    begin=begin@entry=0x7f4f25ae0c80 "select b, sum(c) from ( select a, b, sum(c) as c from union2 where a>1 group by a,b UNION ALL select a, b, sum(c) as c from union2 where b>1 group by a, b  order by a, b) as a group by b order by b;", 
    end=<optimized out>, context=..., flags=..., stage=DB::QueryProcessingStage::Complete, istr=0x0) at ./build/./src/Interpreters/executeQuery.cpp:1060
#7252 0x0000000011079769 in DB::executeQuery (query=..., context=..., flags=flags@entry=..., stage=DB::QueryProcessingStage::Complete) at ./build/./src/Interpreters/executeQuery.cpp:1287
#7253 0x0000000011f2e524 in DB::TCPHandler::runImpl (this=0x7f4ef1099400) at ./build/./src/Server/TCPHandler.cpp:498
#7254 0x0000000011f44b2a in DB::TCPHandler::run (this=0x7f506e6009a8) at ./build/./src/Server/TCPHandler.cpp:2292
#7255 0x00000000148c7f87 in Poco::Net::TCPServerConnection::start (this=0x7f506e6009a8) at ./build/./base/poco/Net/src/TCPServerConnection.cpp:43
#7256 0x00000000148c847a in Poco::Net::TCPServerDispatcher::run (this=0x7f4f35e13900) at ./build/./base/poco/Net/src/TCPServerDispatcher.cpp:115
#7257 0x0000000014a163db in Poco::PooledThread::run (this=0x7f5116dca600) at ./build/./base/poco/Foundation/src/ThreadPool.cpp:188
#7258 0x0000000014a13a91 in Poco::ThreadImpl::runnableEntry (pThread=<optimized out>) at ./base/poco/Foundation/src/Thread_POSIX.cpp:335
#7259 0x00007f51179bf9eb in start_thread (arg=<optimized out>) at pthread_create.c:444
#7260 0x00007f5117a437cc in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```

**Comment by antonio2368** [comment]
Fails in the older builds, but does not reproduce in the newest master.
