### ISSUE TITLE
(Analyzer, not ready for production) MemorySanitizer: use-of-uninitialized-value in ColumnNullable

### ISSUE THREAD

**Issue by amosbird** [ClickHouse/ClickHouse#57465]
**Describe the bug**
https://s3.amazonaws.com/clickhouse-test-reports/56944/e8561574ec7ca2c0ad941c07f4398780a61a1e2d/fuzzer_astfuzzermsan/report.html

**How to reproduce**

Only happens when analyzer is enabled.

```
SELECT count(NULL) IGNORE NULLS > avg(toDecimal32(NULL)) IGNORE NULLS, count() FROM numbers(1000) WITH TOTALS SETTINGS allow_experimental_analyzer = 1;
```

```
240036:SUMMARY: MemorySanitizer: use-of-uninitialized-value build_docker/./src/Columns/ColumnNullable.cpp:825:19 in DB::ColumnNullable::checkConsistency() const
Exiting
Uninitialized bytes in write at offset 0 inside [0x7fd577af1e00, 392)
==260==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x56115811c825 in DB::WriteBufferFromFileDescriptorDiscardOnFailure::nextImpl() build_docker/./src/IO/WriteBufferFromFileDescriptorDiscardOnFailure.cpp:16:23
    #1 0x5611588cafa9 in DB::WriteBuffer::next() build_docker/./src/IO/WriteBuffer.h:53:13
    #2 0x5611588c4c38 in sanitizerDeathCallback() build_docker/./src/Daemon/BaseDaemon.cpp:560:9
    #3 0x56114081b1d5 in __sanitizer::Die() crtstuff.c
    #4 0x56114082c732 in __msan_warning_with_origin_noreturn (/workspace/clickhouse+0x7c6c732) (BuildId: a41fe96a7ddc5ce6e883b6c4801c0e5db2748038)
    #5 0x5611706c3641 in DB::ColumnNullable::checkConsistency() const build_docker/./src/Columns/ColumnNullable.cpp:825:19
    #6 0x56116c7c1495 in DB::SerializationNullable::serializeBinaryBulkWithMultipleStreams(DB::IColumn const&, unsigned long, unsigned long, DB::ISerialization::SerializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::SerializeBinaryBulkState>&) const build_docker/./src/DataTypes/Serializations/SerializationNullable.cpp:112:9
    #7 0x5611737f74e6 in DB::writeData(DB::ISerialization const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&, DB::WriteBuffer&, unsigned long, unsigned long) build_docker/./src/Formats/NativeWriter.cpp:62:19
    #8 0x5611737f74e6 in DB::NativeWriter::write(DB::Block const&) build_docker/./src/Formats/NativeWriter.cpp:163:13
    #9 0x561173744912 in DB::TCPHandler::sendData(DB::Block const&) build_docker/./src/Server/TCPHandler.cpp:2168:26
    #10 0x56117373d1e5 in DB::TCPHandler::processOrdinaryQueryWithProcessors() build_docker/./src/Server/TCPHandler.cpp:1019:21
    #11 0x56117371adfe in DB::TCPHandler::runImpl() build_docker/./src/Server/TCPHandler.cpp:520:17
    #12 0x56117376b45b in DB::TCPHandler::run() build_docker/./src/Server/TCPHandler.cpp:2292:9
    #13 0x56117786ab3f in Poco::Net::TCPServerConnection::start() build_docker/./base/poco/Net/src/TCPServerConnection.cpp:43:3
    #14 0x56117786b9a1 in Poco::Net::TCPServerDispatcher::run() build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:115:20
    #15 0x561177cedde5 in Poco::PooledThread::run() build_docker/./base/poco/Foundation/src/ThreadPool.cpp:188:14
    #16 0x561177ceabad in Poco::(anonymous namespace)::RunnableHolder::run() build_docker/./base/poco/Foundation/src/Thread.cpp:45:11
    #17 0x561177ce7a91 in Poco::ThreadImpl::runnableEntry(void*) build_docker/./base/poco/Foundation/src/Thread_POSIX.cpp:335:27
    #18 0x7fd6805cbac2 in start_thread nptl/pthread_create.c:442:8
    #19 0x7fd68065da3f  misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

  Uninitialized value was stored to memory at
    #0 0x56114083280a in __msan_memcpy (/workspace/clickhouse+0x7c7280a) (BuildId: a41fe96a7ddc5ce6e883b6c4801c0e5db2748038)
    #1 0x5611408ec573 in DB::WriteBuffer::write(char const*, unsigned long) (/workspace/clickhouse+0x7d2c573) (BuildId: a41fe96a7ddc5ce6e883b6c4801c0e5db2748038)
    #2 0x5611588caef6 in void DB::writePODBinary<int>(int const&, DB::WriteBuffer&) build_docker/./src/IO/WriteHelpers.h:88:9
    #3 0x5611588caef6 in void DB::writeBinary<int>(int const&, DB::WriteBuffer&) build_docker/./src/IO/WriteHelpers.h:1031:59
    #4 0x5611588c4be5 in sanitizerDeathCallback() build_docker/./src/Daemon/BaseDaemon.cpp:555:5
    #5 0x56114081b1d5 in __sanitizer::Die() crtstuff.c
    #6 0x5611706c3641 in DB::ColumnNullable::checkConsistency() const build_docker/./src/Columns/ColumnNullable.cpp:825:19
    #7 0x56116c7c1495 in DB::SerializationNullable::serializeBinaryBulkWithMultipleStreams(DB::IColumn const&, unsigned long, unsigned long, DB::ISerialization::SerializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::SerializeBinaryBulkState>&) const build_docker/./src/DataTypes/Serializations/SerializationNullable.cpp:112:9
    #8 0x5611737f74e6 in DB::writeData(DB::ISerialization const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&, DB::WriteBuffer&, unsigned long, unsigned long) build_docker/./src/Formats/NativeWriter.cpp:62:19
    #9 0x5611737f74e6 in DB::NativeWriter::write(DB::Block const&) build_docker/./src/Formats/NativeWriter.cpp:163:13
    #10 0x561173744912 in DB::TCPHandler::sendData(DB::Block const&) build_docker/./src/Server/TCPHandler.cpp:2168:26
    #11 0x56117373d1e5 in DB::TCPHandler::processOrdinaryQueryWithProcessors() build_docker/./src/Server/TCPHandler.cpp:1019:21
    #12 0x56117371adfe in DB::TCPHandler::runImpl() build_docker/./src/Server/TCPHandler.cpp:520:17
    #13 0x56117376b45b in DB::TCPHandler::run() build_docker/./src/Server/TCPHandler.cpp:2292:9
    #14 0x56117786ab3f in Poco::Net::TCPServerConnection::start() build_docker/./base/poco/Net/src/TCPServerConnection.cpp:43:3
    #15 0x56117786b9a1 in Poco::Net::TCPServerDispatcher::run() build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:115:20
    #16 0x561177cedde5 in Poco::PooledThread::run() build_docker/./base/poco/Foundation/src/ThreadPool.cpp:188:14
    #17 0x561177ceabad in Poco::(anonymous namespace)::RunnableHolder::run() build_docker/./base/poco/Foundation/src/Thread.cpp:45:11
    #18 0x561177ce7a91 in Poco::ThreadImpl::runnableEntry(void*) build_docker/./base/poco/Foundation/src/Thread_POSIX.cpp:335:27
    #19 0x7fd6805cbac2 in start_thread nptl/pthread_create.c:442:8

  Member fields were destroyed
    #0 0x56114083c15d in __sanitizer_dtor_callback_fields (/workspace/clickhouse+0x7c7c15d) (BuildId: a41fe96a7ddc5ce6e883b6c4801c0e5db2748038)
    #1 0x56116c6f3b2f in std::__1::__function::__policy_func<void (std::__1::vector<std::__1::shared_ptr<DB::IDataType const>, std::__1::allocator<std::__1::shared_ptr<DB::IDataType const>>>&, std::__1::unordered_set<DB::TypeIndex, std::__1::hash<DB::TypeIndex>, std::__1::equal_to<DB::TypeIndex>, std::__1::allocator<DB::TypeIndex>>&)>::~__policy_func[abi:v15000]() build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:728:22
    #2 0x56116c6f3b2f in std::__1::__function::__policy_func<void (std::__1::vector<std::__1::shared_ptr<DB::IDataType const>, std::__1::allocator<std::__1::shared_ptr<DB::IDataType const>>>&, std::__1::unordered_set<DB::TypeIndex, std::__1::hash<DB::TypeIndex>, std::__1::equal_to<DB::TypeIndex>, std::__1::allocator<DB::TypeIndex>>&)>::~__policy_func[abi:v15000]() build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:820:5
    #3 0x56116c6f3b2f in std::__1::function<void (std::__1::vector<std::__1::shared_ptr<DB::IDataType const>, std::__1::allocator<std::__1::shared_ptr<DB::IDataType const>>>&, std::__1::unordered_set<DB::TypeIndex, std::__1::hash<DB::TypeIndex>, std::__1::equal_to<DB::TypeIndex>, std::__1::allocator<DB::TypeIndex>>&)>::~function() build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:1174:43
    #4 0x56116c6f3b2f in DB::callOnNestedSimpleTypes(std::__1::shared_ptr<DB::IDataType const>&, std::__1::function<void (std::__1::shared_ptr<DB::IDataType const>&)>) build_docker/./src/DataTypes/transformTypesRecursively.cpp:184:5
    #5 0x56116c329103 in DB::setVersionToAggregateFunctions(std::__1::shared_ptr<DB::IDataType const>&, bool, std::__1::optional<unsigned long>) build_docker/./src/DataTypes/DataTypeAggregateFunction.cpp:263:5
    #6 0x5611737f5efb in DB::NativeWriter::write(DB::Block const&) build_docker/./src/Formats/NativeWriter.cpp:120:9
    #7 0x561173744912 in DB::TCPHandler::sendData(DB::Block const&) build_docker/./src/Server/TCPHandler.cpp:2168:26
    #8 0x56117373d1e5 in DB::TCPHandler::processOrdinaryQueryWithProcessors() build_docker/./src/Server/TCPHandler.cpp:1019:21
    #9 0x56117371adfe in DB::TCPHandler::runImpl() build_docker/./src/Server/TCPHandler.cpp:520:17
    #10 0x56117376b45b in DB::TCPHandler::run() build_docker/./src/Server/TCPHandler.cpp:2292:9
    #11 0x56117786ab3f in Poco::Net::TCPServerConnection::start() build_docker/./base/poco/Net/src/TCPServerConnection.cpp:43:3
    #12 0x56117786b9a1 in Poco::Net::TCPServerDispatcher::run() build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:115:20
    #13 0x561177cedde5 in Poco::PooledThread::run() build_docker/./base/poco/Foundation/src/ThreadPool.cpp:188:14
    #14 0x561177ceabad in Poco::(anonymous namespace)::RunnableHolder::run() build_docker/./base/poco/Foundation/src/Thread.cpp:45:11
    #15 0x561177ce7a91 in Poco::ThreadImpl::runnableEntry(void*) build_docker/./base/poco/Foundation/src/Thread_POSIX.cpp:335:27
    #16 0x7fd6805cbac2 in start_thread nptl/pthread_create.c:442:8
```

**Comment by antonio2368** [comment]
Managed to reproduce on the older MSAN build but it does not reproduce in the newest build.
