### ISSUE TITLE
arrayFold of arrayIntersect segfault

### ISSUE THREAD

**Issue by nikandfor** [ClickHouse/ClickHouse#57816]
This little query breaks clickhouse. It works on arm64 macos local, it works on amd64 linux server, it works on fresh installed version.

```
$ clickhouse local
ClickHouse local version 23.12.1.457 (official build).

air.local :) SELECT arrayFold(acc, x -> arrayIntersect(acc, x), [['qwe', 'asd'], ['qwe','asde']], [])

SELECT arrayFold((acc, x) -> arrayIntersect(acc, x), [['qwe', 'asd'], ['qwe', 'asde']], [])

Query id: 660a9bd1-2975-49b8-ba29-35bcfce5901c

Abort trap: 6
```

**Comment by Algunenano** [comment]
Via gdb:

```
#0  DB::ColumnArray::insertRangeFrom (this=0x70200002f840, src=..., start=0, length=1) at ./build_msan/./src/Columns/ColumnArray.cpp:521
#1  0x000055557469539b in DB::ArrayFold::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const ()
#2  0x000055555d23e598 in DB::FunctionToExecutableFunctionAdaptor::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const
    ()
#3  0x000055558790b598 in DB::IExecutableFunction::executeWithoutLowCardinalityColumns (this=this@entry=0x70200006d800, args=..., result_type=..., input_rows_count=input_rows_count@entry=1, dry_run=false)
    at ./build_msan/./src/Functions/IFunction.cpp:248
#4  0x000055558790d6b1 in DB::IExecutableFunction::executeWithoutSparseColumns (this=this@entry=0x70200006d800, arguments=..., result_type=..., input_rows_count=input_rows_count@entry=1, dry_run=false) at ./build_msan/./src/Functions/IFunction.cpp:303
#5  0x0000555587913d17 in DB::IExecutableFunction::execute (this=0x70200006d800, arguments=..., result_type=..., input_rows_count=1, dry_run=false) at ./build_msan/./src/Functions/IFunction.cpp:378
#6  0x000055558b8c67d8 in DB::executeAction (action=..., execution_context=..., dry_run=false) at ./build_msan/./src/Interpreters/ExpressionActions.cpp:613
#7  DB::ExpressionActions::execute (this=0x7110000ea398, block=..., num_rows=@0x7ffee8772100: 1, dry_run=false) at ./build_msan/./src/Interpreters/ExpressionActions.cpp:730
#8  0x0000555592af616e in DB::ExpressionTransform::transform (this=0x71200021e898, chunk=...) at ./build_msan/./src/Processors/Transforms/ExpressionTransform.cpp:23
#9  0x000055557d4813e1 in DB::ISimpleTransform::transform (this=0x0, input_chunk=..., output_chunk=...) at ./src/Processors/ISimpleTransform.h:32
#10 0x0000555592038f26 in DB::ISimpleTransform::work (this=0x71200021e898) at ./build_msan/./src/Processors/ISimpleTransform.cpp:89
#11 0x00005555920a156e in DB::executeJob (node=0x710000017500, read_progress_callback=0x70a0000370a0) at ./build_msan/./src/Processors/Executors/ExecutionThreadContext.cpp:47
#12 DB::ExecutionThreadContext::executeTask (this=<optimized out>) at ./build_msan/./src/Processors/Executors/ExecutionThreadContext.cpp:95
```

```
(gdb) p typeid(src)
$9 = {_vptr$type_info = 0x55559d7f3a50 <vtable for __cxxabiv1::__si_class_type_info+16>, __type_name = 0x55555825e064 <typeinfo name for DB::ColumnConst> "N2DB11ColumnConstE"}
```

The column is `const` not `array`, so the assert fails. If asserts are disabled, it will crash if you are lucky (or corrupt things if not)

cc @rschu1ze @Lirikl

**Comment by nikandfor** [comment]
The longer version also works.
```
$ clickhouse local
ClickHouse local version 23.12.1.116 (official build).

air.local :) CREATE TABLE q (id UInt32, arr Array(String)) ENGINE GenerateRandom(0, 10, 20)

CREATE TABLE q
(
    `id` UInt32,
    `arr` Array(String)
)
ENGINE = GenerateRandom(0, 10, 20)

Query id: 0bbc04b0-9d87-48f3-9264-7d8926db5dc4

Ok.

0 rows in set. Elapsed: 0.000 sec.

air.local :) SELECT id, arrayFold(acc, x -> arrayIntersect(acc, x), groupArray(arr), []) AS u FROM (SELECT * FROM q LIMIT 5) GROUP BY id

SELECT
    id,
    arrayFold((acc, x) -> arrayIntersect(acc, x), groupArray(arr), []) AS u
FROM
(
    SELECT *
    FROM q
    LIMIT 5
)
GROUP BY id

Query id: 84246678-9c81-4078-991d-fc785dac5f07

Abort trap: 6
```
