### ISSUE TITLE
[Analyzer] StorageDistributed: runtime error: member call on null pointer of type 'DB::TypePromotion<DB::IQueryTreeNode>'

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#57898]
Report: https://s3.amazonaws.com/clickhouse-test-reports/57876/3343d59f8025edb75e58a710d2147694979ea978/fuzzer_astfuzzerubsan/report.html

```
/build/src/Storages/StorageDistributed.cpp:534:54: runtime error: member call on null pointer of type 'DB::TypePromotion<DB::IQueryTreeNode>'
    #0 0x55648d88e281 in DB::StorageDistributed::getOptimizedQueryProcessingStageAnalyzer(DB::SelectQueryInfo const&, DB::Settings const&) const build_docker/./src/Storages/StorageDistributed.cpp:534:54
    #1 0x55648d8883d2 in DB::StorageDistributed::getQueryProcessingStage(std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, std::__1::shared_ptr<DB::StorageSnapshot> const&, DB::SelectQueryInfo&) const build_docker/./src/Storages/StorageDistributed.cpp:509:27
    #2 0x55648c9a580f in DB::InterpreterSelectQuery::getSampleBlockImpl() build_docker/./src/Interpreters/InterpreterSelectQuery.cpp:991:31
    #3 0x55648c9912bc in DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::PreparedSets>)::$_0::operator()(bool) const build_docker/./src/Interpreters/InterpreterSelectQuery.cpp:780:25
    #4 0x55648c9857d3 in DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::PreparedSets>) build_docker/./src/Interpreters/InterpreterSelectQuery.cpp:783:5
    #5 0x55648c97cff5 in DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::PreparedSets>) build_docker/./src/Interpreters/InterpreterSelectQuery.cpp:359:7
    #6 0x55648c97cd92 in DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) build_docker/./src/Interpreters/InterpreterSelectQuery.cpp:201:7
    #7 0x55648c7124ef in DB::(anonymous namespace)::ExplainAnalyzedSyntaxMatcher::visit(DB::ASTSelectQuery&, std::__1::shared_ptr<DB::IAST>&, DB::(anonymous namespace)::ExplainAnalyzedSyntaxMatcher::Data&) build_docker/./src/Interpreters/InterpreterExplainQuery.cpp:71:36
    #8 0x55648c7124ef in DB::(anonymous namespace)::ExplainAnalyzedSyntaxMatcher::visit(std::__1::shared_ptr<DB::IAST>&, DB::(anonymous namespace)::ExplainAnalyzedSyntaxMatcher::Data&) build_docker/./src/Interpreters/InterpreterExplainQuery.cpp:64:17
    #9 0x55648c7124ef in DB::InDepthNodeVisitor<DB::(anonymous namespace)::ExplainAnalyzedSyntaxMatcher, true, false, std::__1::shared_ptr<DB::IAST>>::doVisit(std::__1::shared_ptr<DB::IAST>&) build_docker/./src/Interpreters/InDepthNodeVisitor.h:71:13
    #10 0x55648c712c73 in void DB::InDepthNodeVisitor<DB::(anonymous namespace)::ExplainAnalyzedSyntaxMatcher, true, false, std::__1::shared_ptr<DB::IAST>>::visitImplMain<false>(std::__1::shared_ptr<DB::IAST>&) build_docker/./src/Interpreters/InDepthNodeVisitor.h:61:9
    #11 0x55648c712c73 in void DB::InDepthNodeVisitor<DB::(anonymous namespace)::ExplainAnalyzedSyntaxMatcher, true, false, std::__1::shared_ptr<DB::IAST>>::visitImpl<false>(std::__1::shared_ptr<DB::IAST>&) build_docker/./src/Interpreters/InDepthNodeVisitor.h:51:13
    #12 0x55648c712c73 in void DB::InDepthNodeVisitor<DB::(anonymous namespace)::ExplainAnalyzedSyntaxMatcher, true, false, std::__1::shared_ptr<DB::IAST>>::visitChildren<false>(std::__1::shared_ptr<DB::IAST>&) build_docker/./src/Interpreters/InDepthNodeVisitor.h:92:17
    #13 0x55648c712c7e in void DB::InDepthNodeVisitor<DB::(anonymous namespace)::ExplainAnalyzedSyntaxMatcher, true, false, std::__1::shared_ptr<DB::IAST>>::visitImplMain<false>(std::__1::shared_ptr<DB::IAST>&) build_docker/./src/Interpreters/InDepthNodeVisitor.h:64:13
    #14 0x55648c712c7e in void DB::InDepthNodeVisitor<DB::(anonymous namespace)::ExplainAnalyzedSyntaxMatcher, true, false, std::__1::shared_ptr<DB::IAST>>::visitImpl<false>(std::__1::shared_ptr<DB::IAST>&) build_docker/./src/Interpreters/InDepthNodeVisitor.h:51:13
    #15 0x55648c712c7e in void DB::InDepthNodeVisitor<DB::(anonymous namespace)::ExplainAnalyzedSyntaxMatcher, true, false, std::__1::shared_ptr<DB::IAST>>::visitChildren<false>(std::__1::shared_ptr<DB::IAST>&) build_docker/./src/Interpreters/InDepthNodeVisitor.h:92:17
    #16 0x55648c712c7e in void DB::InDepthNodeVisitor<DB::(anonymous namespace)::ExplainAnalyzedSyntaxMatcher, true, false, std::__1::shared_ptr<DB::IAST>>::visitImplMain<false>(std::__1::shared_ptr<DB::IAST>&) build_docker/./src/Interpreters/InDepthNodeVisitor.h:64:13
    #17 0x55648c712c7e in void DB::InDepthNodeVisitor<DB::(anonymous namespace)::ExplainAnalyzedSyntaxMatcher, true, false, std::__1::shared_ptr<DB::IAST>>::visitImpl<false>(std::__1::shared_ptr<DB::IAST>&) build_docker/./src/Interpreters/InDepthNodeVisitor.h:51:13
    #18 0x55648c712c7e in void DB::InDepthNodeVisitor<DB::(anonymous namespace)::ExplainAnalyzedSyntaxMatcher, true, false, std::__1::shared_ptr<DB::IAST>>::visitChildren<false>(std::__1::shared_ptr<DB::IAST>&) build_docker/./src/Interpreters/InDepthNodeVisitor.h:92:17
    #19 0x55648c709084 in void DB::InDepthNodeVisitor<DB::(anonymous namespace)::ExplainAnalyzedSyntaxMatcher, true, false, std::__1::shared_ptr<DB::IAST>>::visitImplMain<false>(std::__1::shared_ptr<DB::IAST>&) build_docker/./src/Interpreters/InDepthNodeVisitor.h:64:13
    #20 0x55648c709084 in void DB::InDepthNodeVisitor<DB::(anonymous namespace)::ExplainAnalyzedSyntaxMatcher, true, false, std::__1::shared_ptr<DB::IAST>>::visitImpl<false>(std::__1::shared_ptr<DB::IAST>&) build_docker/./src/Interpreters/InDepthNodeVisitor.h:51:13
    #21 0x55648c709084 in DB::InDepthNodeVisitor<DB::(anonymous namespace)::ExplainAnalyzedSyntaxMatcher, true, false, std::__1::shared_ptr<DB::IAST>>::visit(std::__1::shared_ptr<DB::IAST>&) build_docker/./src/Interpreters/InDepthNodeVisitor.h:32:13
    #22 0x55648c709084 in DB::InterpreterExplainQuery::executeImpl() build_docker/./src/Interpreters/InterpreterExplainQuery.cpp:385:48
    #23 0x55648c706203 in DB::InterpreterExplainQuery::execute() build_docker/./src/Interpreters/InterpreterExplainQuery.cpp:90:20
    #24 0x55648d09fe28 in DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) build_docker/./src/Interpreters/executeQuery.cpp:1109:40
    #25 0x55648d098bc6 in DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) build_docker/./src/Interpreters/executeQuery.cpp:1287:26
    #26 0x55648e9f7fa5 in DB::TCPHandler::runImpl() build_docker/./src/Server/TCPHandler.cpp:498:54
    #27 0x55648ea282f1 in DB::TCPHandler::run() build_docker/./src/Server/TCPHandler.cpp:2292:9
    #28 0x55649062c09d in Poco::Net::TCPServerConnection::start() build_docker/./base/poco/Net/src/TCPServerConnection.cpp:43:3
    #29 0x55649062d1d9 in Poco::Net::TCPServerDispatcher::run() build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:115:20
    #30 0x55649089402f in Poco::PooledThread::run() build_docker/./base/poco/Foundation/src/ThreadPool.cpp:188:14
    #31 0x55649088f130 in Poco::ThreadImpl::runnableEntry(void*) build_docker/./base/poco/Foundation/src/Thread_POSIX.cpp:335:27
    #32 0x7fd836d51ac2 in start_thread nptl/pthread_create.c:442:8
    #33 0x7fd836de365f  misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /build/src/Storages/StorageDistributed.cpp:534:54 in

```

Seems related to `EXPLAIN` and distributed tables but I couldn't reproduce it.

This is what I tried with different settings:
```
set optimize_skip_unused_shards=1;
set allow_experimental_analyzer=1;

drop table if exists data_01071;
create table data_01071 (key Int) Engine=Null();

DROP TABLE IF EXISTS dist_01071;
CREATE TABLE dist_01071 AS data_01071 ENGINE = Distributed(test_cluster_two_shards, currentDatabase(), data_01071);

SELECT * FROM dist_01071;
EXPLAIN AST SELECT * FROM dist_01071;
EXPLAIN ESTIMATE SELECT * FROM dist_01071;
EXPLAIN CURRENT TRANSACTION SELECT * FROM dist_01071;
EXPLAIN SYNTAX SELECT * FROM dist_01071;
```

I ran `01071_force_optimize_skip_unused_shards.sql` with extra queries for 10k iterations and didn't reproduce it either.

**Comment by devcrafter** [comment]
Should be fixed by https://github.com/ClickHouse/ClickHouse/pull/61059 . Currently, we disable the analyzer in `EXPLAIN AST/SYNTAX`.
