### ISSUE TITLE
Deadlock on shutdown in `rocksdb` 

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#58294]
https://s3.amazonaws.com/clickhouse-test-reports/56946/524d53199d2f2f7b8ca0eb4fd6b2aaa9c2c36ae6/upgrade_check__debug_.html

```
2023-12-28 06:56:58 [Thread debugging using libthread_db enabled]
2023-12-28 06:56:58 Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
2023-12-28 06:56:58 0x00007fd8887ecc6b in munmap () from /lib/x86_64-linux-gnu/libc.so.6
2023-12-28 06:56:59 
2023-12-28 06:56:59 Thread 8 (Thread 0x7fd48a3fe640 (LWP 190712) "FgLoad"):
2023-12-28 06:56:59 #0  0x00007fd88875f117 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
2023-12-28 06:56:59 #1  0x00007fd888761a41 in pthread_cond_wait () from /lib/x86_64-linux-gnu/libc.so.6
2023-12-28 06:56:59 #2  0x00000000261ba61d in std::__1::__libcpp_condvar_wait[abi:v15000](pthread_cond_t*, pthread_mutex_t*) (__cv=0x7fd8878b5be0, __m=0x7fd8878b5bb8) at /build/contrib/llvm-project/libcxx/include/__threading_support:335
2023-12-28 06:56:59 #3  0x00000000261ba232 in std::__1::condition_variable::wait (this=0x7fd8878b5be0, lk=...) at /build/contrib/llvm-project/libcxx/src/condition_variable.cpp:46
2023-12-28 06:56:59 #4  0x000000002465b0b2 in rocksdb::ThreadPoolImpl::Impl::BGThread (this=0x7fd8878b5b60, thread_id=0) at /build/contrib/rocksdb/util/threadpool_imp.cc:194
2023-12-28 06:56:59 #5  0x000000002465b905 in rocksdb::ThreadPoolImpl::Impl::BGThreadWrapper (arg=0x7fd59d119630) at /build/contrib/rocksdb/util/threadpool_imp.cc:307
2023-12-28 06:56:59 #6  0x000000002465e280 in std::__1::__invoke[abi:v15000]<void (*)(void*), rocksdb::BGThreadMetadata*>(void (*&&)(void*), rocksdb::BGThreadMetadata*&&) (__f=@0x7fd4f9735768: 0x2465b7e0 <rocksdb::ThreadPoolImpl::Impl::BGThreadWrapper(void*)>, __args=@0x7fd4f9735770: 0x7fd59d119630) at /build/contrib/llvm-project/libcxx/include/__functional/invoke.h:394
2023-12-28 06:56:59 #7  0x000000002465e24e in std::__1::__thread_execute[abi:v15000]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(void*), rocksdb::BGThreadMetadata*, 2ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(void*), rocksdb::BGThreadMetadata*>&, std::__1::__tuple_indices<2ul>) (__t=...) at /build/contrib/llvm-project/libcxx/include/thread:284
2023-12-28 06:56:59 #8  0x000000002465e022 in std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(void*), rocksdb::BGThreadMetadata*> >(void*) (__vp=0x7fd4f9735760) at /build/contrib/llvm-project/libcxx/include/thread:295
2023-12-28 06:56:59 #9  0x00007fd888762ac3 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
2023-12-28 06:56:59 #10 0x00007fd8887f4a40 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
2023-12-28 06:56:59 
2023-12-28 06:56:59 Thread 7 (Thread 0x7fd48abff640 (LWP 190711) "FgLoad"):
2023-12-28 06:56:59 #0  0x00007fd88875f117 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
2023-12-28 06:56:59 #1  0x00007fd888761a41 in pthread_cond_wait () from /lib/x86_64-linux-gnu/libc.so.6
2023-12-28 06:56:59 #2  0x00000000261ba61d in std::__1::__libcpp_condvar_wait[abi:v15000](pthread_cond_t*, pthread_mutex_t*) (__cv=0x7fd8878b5b00, __m=0x7fd8878b5ad8) at /build/contrib/llvm-project/libcxx/include/__threading_support:335
2023-12-28 06:56:59 #3  0x00000000261ba232 in std::__1::condition_variable::wait (this=0x7fd8878b5b00, lk=...) at /build/contrib/llvm-project/libcxx/src/condition_variable.cpp:46
2023-12-28 06:56:59 #4  0x000000002465b0b2 in rocksdb::ThreadPoolImpl::Impl::BGThread (this=0x7fd8878b5a80, thread_id=0) at /build/contrib/rocksdb/util/threadpool_imp.cc:194
2023-12-28 06:56:59 #5  0x000000002465b905 in rocksdb::ThreadPoolImpl::Impl::BGThreadWrapper (arg=0x7fd5abc2d790) at /build/contrib/rocksdb/util/threadpool_imp.cc:307
2023-12-28 06:56:59 #6  0x000000002465e280 in std::__1::__invoke[abi:v15000]<void (*)(void*), rocksdb::BGThreadMetadata*>(void (*&&)(void*), rocksdb::BGThreadMetadata*&&) (__f=@0x7fd4f9735708: 0x2465b7e0 <rocksdb::ThreadPoolImpl::Impl::BGThreadWrapper(void*)>, __args=@0x7fd4f9735710: 0x7fd5abc2d790) at /build/contrib/llvm-project/libcxx/include/__functional/invoke.h:394
2023-12-28 06:56:59 #7  0x000000002465e24e in std::__1::__thread_execute[abi:v15000]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(void*), rocksdb::BGThreadMetadata*, 2ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(void*), rocksdb::BGThreadMetadata*>&, std::__1::__tuple_indices<2ul>) (__t=...) at /build/contrib/llvm-project/libcxx/include/thread:284
2023-12-28 06:57:01 #8  0x000000002465e022 in std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(void*), rocksdb::BGThreadMetadata*> >(void*) (__vp=0x7fd4f9735700) at /build/contrib/llvm-project/libcxx/include/thread:295
2023-12-28 06:57:01 #9  0x00007fd888762ac3 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
2023-12-28 06:57:01 #10 0x00007fd8887f4a40 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
2023-12-28 06:57:01 
2023-12-28 06:57:01 Thread 6 (Thread 0x7fd75c1ff640 (LWP 189597) "clickhouse-serv"):
2023-12-28 06:57:01 #0  __syscall () at /build/base/glibc-compatibility/musl/x86_64/syscall.s:14
2023-12-28 06:57:01 #1  0x0000000026271284 in epoll_pwait (fd=31, ev=0x7fd75c1ef8d0, cnt=100, to=100000, sigs=0x0) at /build/base/glibc-compatibility/musl/epoll.c:27
2023-12-28 06:57:01 #2  0x000000002627130e in epoll_wait (fd=31, ev=0x7fd75c1ef8d0, cnt=100, to=100000) at /build/base/glibc-compatibility/musl/epoll.c:36
2023-12-28 06:57:01 #3  0x000000002339dca6 in aws_event_loop_listen_for_io_events (epoll_fd=31, events=0x7fd75c1ef8d0, timeout=100000) at /build/contrib/aws-c-io/source/linux/epoll_event_loop.c:568
2023-12-28 06:57:01 #4  0x000000002339d54d in aws_event_loop_thread (args=0x7fd88744d0a0) at /build/contrib/aws-c-io/source/linux/epoll_event_loop.c:615
2023-12-28 06:57:01 #5  0x000000002338cf39 in thread_fn (arg=0x7fd887824950) at /build/contrib/aws-c-common/source/posix/thread.c:173
2023-12-28 06:57:01 #6  0x00007fd888762ac3 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
2023-12-28 06:57:01 #7  0x00007fd8887f4a40 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
2023-12-28 06:57:01 
2023-12-28 06:57:01 Thread 5 (Thread 0x7fd761ffd640 (LWP 189588) "IntersrvHandler"):
2023-12-28 06:57:01 #0  0x00007fd88875f117 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
2023-12-28 06:57:01 #1  0x00007fd888761a41 in pthread_cond_wait () from /lib/x86_64-linux-gnu/libc.so.6
2023-12-28 06:57:01 #2  0x0000000023110b59 in Poco::EventImpl::waitImpl (this=0x7fd887935a08) at /build/base/poco/Foundation/src/Event_POSIX.cpp:94
2023-12-28 06:57:01 #3  0x000000001385eff5 in Poco::Event::wait (this=0x7fd887935a08) at /build/base/poco/Foundation/include/Poco/Event.h:92
2023-12-28 06:57:01 #4  0x000000002318e890 in Poco::PooledThread::run (this=0x7fd887935900) at /build/base/poco/Foundation/src/ThreadPool.cpp:180
2023-12-28 06:57:01 #5  0x000000002318b67a in Poco::(anonymous namespace)::RunnableHolder::run (this=0x7fd8878018d0) at /build/base/poco/Foundation/src/Thread.cpp:45
2023-12-28 06:57:01 #6  0x000000002318a3be in Poco::ThreadImpl::runnableEntry (pThread=0x7fd887935938) at /build/base/poco/Foundation/src/Thread_POSIX.cpp:335
2023-12-28 06:57:01 #7  0x00007fd888762ac3 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
2023-12-28 06:57:01 #8  0x00007fd8887f4a40 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
2023-12-28 06:57:01 
2023-12-28 06:57:01 Thread 4 (Thread 0x7fd7627fe640 (LWP 189587) "TCPHandler"):
2023-12-28 06:57:01 #0  0x00007fd88875f117 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
2023-12-28 06:57:01 #1  0x00007fd888761a41 in pthread_cond_wait () from /lib/x86_64-linux-gnu/libc.so.6
2023-12-28 06:57:01 #2  0x0000000023110b59 in Poco::EventImpl::waitImpl (this=0x7fd887935788) at /build/base/poco/Foundation/src/Event_POSIX.cpp:94
2023-12-28 06:57:01 #3  0x000000001385eff5 in Poco::Event::wait (this=0x7fd887935788) at /build/base/poco/Foundation/include/Poco/Event.h:92
2023-12-28 06:57:01 #4  0x000000002318e890 in Poco::PooledThread::run (this=0x7fd887935680) at /build/base/poco/Foundation/src/ThreadPool.cpp:180
2023-12-28 06:57:01 #5  0x000000002318b67a in Poco::(anonymous namespace)::RunnableHolder::run (this=0x7fd8878018e0) at /build/base/poco/Foundation/src/Thread.cpp:45
2023-12-28 06:57:01 #6  0x000000002318a3be in Poco::ThreadImpl::runnableEntry (pThread=0x7fd8879356b8) at /build/base/poco/Foundation/src/Thread_POSIX.cpp:335
2023-12-28 06:57:01 #7  0x00007fd888762ac3 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
2023-12-28 06:57:01 #8  0x00007fd8887f4a40 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
2023-12-28 06:57:01 
2023-12-28 06:57:01 Thread 3 (Thread 0x7fd762fff640 (LWP 189586) "KeeperHandler"):
2023-12-28 06:57:01 #0  0x00007fd88875f117 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
2023-12-28 06:57:01 #1  0x00007fd888761a41 in pthread_cond_wait () from /lib/x86_64-linux-gnu/libc.so.6
2023-12-28 06:57:01 #2  0x0000000023110b59 in Poco::EventImpl::waitImpl (this=0x7fd887935288) at /build/base/poco/Foundation/src/Event_POSIX.cpp:94
2023-12-28 06:57:01 #3  0x000000001385eff5 in Poco::Event::wait (this=0x7fd887935288) at /build/base/poco/Foundation/include/Poco/Event.h:92
2023-12-28 06:57:01 #4  0x000000002318e890 in Poco::PooledThread::run (this=0x7fd887935180) at /build/base/poco/Foundation/src/ThreadPool.cpp:180
2023-12-28 06:57:01 #5  0x000000002318b67a in Poco::(anonymous namespace)::RunnableHolder::run (this=0x7fd8878018c0) at /build/base/poco/Foundation/src/Thread.cpp:45
2023-12-28 06:57:03 #6  0x000000002318a3be in Poco::ThreadImpl::runnableEntry (pThread=0x7fd8879351b8) at /build/base/poco/Foundation/src/Thread_POSIX.cpp:335
2023-12-28 06:57:03 #7  0x00007fd888762ac3 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
2023-12-28 06:57:03 #8  0x00007fd8887f4a40 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
2023-12-28 06:57:03 
2023-12-28 06:57:03 Thread 2 (Thread 0x7fd886816640 (LWP 189583) "clickhouse-serv"):
2023-12-28 06:57:03 #0  0x00007fd8887e2a0c in read () from /lib/x86_64-linux-gnu/libc.so.6
2023-12-28 06:57:03 #1  0x0000000013787309 in DB::ReadBufferFromFileDescriptor::readImpl (this=0x7fd8868067e0, to=0x7fd8868068c0 "\017", min_bytes=1, max_bytes=536, offset=4) at /build/src/IO/ReadBufferFromFileDescriptor.cpp:75
2023-12-28 06:57:03 #2  0x00000000137876d6 in DB::ReadBufferFromFileDescriptor::nextImpl (this=0x7fd8868067e0) at /build/src/IO/ReadBufferFromFileDescriptor.cpp:124
2023-12-28 06:57:03 #3  0x000000000aa757bc in DB::ReadBuffer::next (this=0x7fd8868067e0) at /build/src/IO/ReadBuffer.h:70
2023-12-28 06:57:03 #4  0x0000000013b9ce1c in DB::ReadBuffer::eof (this=0x7fd8868067e0) at /build/src/IO/ReadBuffer.h:104
2023-12-28 06:57:03 #5  SignalListener::run (this=0x7fd887885060) at /build/src/Daemon/BaseDaemon.cpp:225
2023-12-28 06:57:03 #6  0x000000002318b67a in Poco::(anonymous namespace)::RunnableHolder::run (this=0x7fd887801850) at /build/base/poco/Foundation/src/Thread.cpp:45
2023-12-28 06:57:03 #7  0x000000002318a3be in Poco::ThreadImpl::runnableEntry (pThread=0x7ffff6d6de50) at /build/base/poco/Foundation/src/Thread_POSIX.cpp:335
2023-12-28 06:57:03 #8  0x00007fd888762ac3 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
2023-12-28 06:57:03 #9  0x00007fd8887f4a40 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
2023-12-28 06:57:03 
2023-12-28 06:57:03 Thread 1 (Thread 0x7fd8885dd700 (LWP 189582) "clickhouse-serv"):
2023-12-28 06:57:03 #0  0x00007fd8887ecc6b in munmap () from /lib/x86_64-linux-gnu/libc.so.6
2023-12-28 06:57:03 #1  0x00007fd88875f458 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
2023-12-28 06:57:03 #2  0x00007fd88875f5a5 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
2023-12-28 06:57:03 #3  0x00007fd88876459c in ?? () from /lib/x86_64-linux-gnu/libc.so.6
2023-12-28 06:57:03 #4  0x00000000262324fc in std::__1::__libcpp_thread_join[abi:v15000](unsigned long*) (__t=0x7fd7428a3410) at /build/contrib/llvm-project/libcxx/include/__threading_support:396
2023-12-28 06:57:03 #5  0x0000000026231f91 in std::__1::thread::join (this=0x7fd7428a3410) at /build/contrib/llvm-project/libcxx/src/thread.cpp:49
2023-12-28 06:57:03 #6  0x00000000138700a3 in ThreadPoolImpl<std::__1::thread>::finalize (this=0x7fd887832880) at /build/src/Common/ThreadPool.cpp:335
2023-12-28 06:57:03 #7  0x000000001386f331 in GlobalThreadPool::shutdown () at /build/src/Common/ThreadPool.cpp:541
2023-12-28 06:57:03 #8  0x00000000137f82d0 in DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)::$_0::operator()() const (this=0x7ffff6d6b578) at /build/programs/server/Server.cpp:708
2023-12-28 06:57:03 #9  0x00000000137f7d75 in BasicScopeGuard<DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)::$_0>::invoke() (this=0x7ffff6d6b578) at /build/base/base/../base/scope_guard.h:99
2023-12-28 06:57:03 #10 0x00000000137f27d5 in BasicScopeGuard<DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)::$_0>::~BasicScopeGuard() (this=0x7ffff6d6b578) at /build/base/base/../base/scope_guard.h:48
2023-12-28 06:57:03 #11 0x00000000137ed5f7 in DB::Server::main (this=0x7ffff6d6dcf0) at /build/programs/server/Server.cpp:2029
2023-12-28 06:57:03 #12 0x0000000022fd40e5 in Poco::Util::Application::run (this=0x7ffff6d6dcf0) at /build/base/poco/Util/src/Application.cpp:315
2023-12-28 06:57:03 #13 0x00000000137d59fb in DB::Server::run (this=0x7ffff6d6dcf0) at /build/programs/server/Server.cpp:399
2023-12-28 06:57:03 #14 0x0000000022ff2ff9 in Poco::Util::ServerApplication::run (this=0x7ffff6d6dcf0, argc=6, argv=0x7fd88795a520) at /build/base/poco/Util/src/ServerApplication.cpp:131
2023-12-28 06:57:03 #15 0x00000000137d31a3 in mainEntryClickHouseServer (argc=6, argv=0x7fd88795a520) at /build/programs/server/Server.cpp:205
2023-12-28 06:57:03 #16 0x000000000a916e25 in main (argc_=6, argv_=0x7ffff6d6e2e8) at /build/programs/main.cpp:505
2023-12-28 06:57:03 [Inferior 1 (process 189582) detached]
```

**Comment by azat** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=76039&sha=f364900f29dda34fcb06e9cc2f5164ef9dc5388a&name_0=PR&name_1=Stress%20test%20%28ubsan%29

**Comment by alexey-milovidov** [comment]
The report does not load.
