### ISSUE TITLE
Segfault in JIT

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#58508]
https://s3.amazonaws.com/clickhouse-test-reports/58350/b1688b19538a8bd389e12575bb09a3b628a1a2fe/stateless_tests__aarch64_.html

```
2024.01.04 02:49:08.598043 [ 3397 ] {ec016aec-8dcf-4575-b39b-a55ecff29b10} <Debug> executeQuery: (from [::1]:32906) (comment: 01115_join_with_dictionary.sql) SELECT * FROM (SELECT if(number % 2 = 0, number, number * 1000) AS k FROM numbers(100)) s1 JOIN dict_flat d ON k = key OR k == 1000 * key ORDER BY key; (stage: Complete)
2024.01.04 02:49:08.598527 [ 3397 ] {ec016aec-8dcf-4575-b39b-a55ecff29b10} <Trace> ContextAccess (default): Access granted: dictGet ON test_3i8jcdn0.dict_flat
2024.01.04 02:49:08.598795 [ 3397 ] {ec016aec-8dcf-4575-b39b-a55ecff29b10} <Trace> ContextAccess (default): Access granted: SELECT(key, a, b, c) ON test_3i8jcdn0.dict_flat
2024.01.04 02:49:08.598960 [ 3397 ] {ec016aec-8dcf-4575-b39b-a55ecff29b10} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2024.01.04 02:49:08.599018 [ 3397 ] {ec016aec-8dcf-4575-b39b-a55ecff29b10} <Trace> ExpressionAnalyzer: Can't use direct join: only one key is supported
2024.01.04 02:49:08.599040 [ 3397 ] {ec016aec-8dcf-4575-b39b-a55ecff29b10} <Trace> HashJoin: Keys: [(k) = (key)]; [(k) = (multiply(1000, key))], datatype: EMPTY, kind: Inner, strictness: All, right header: key UInt64 UInt64(size = 0), multiply(1000, key) UInt64 UInt64(size = 0), b String String(size = 0), a UInt8 UInt8(size = 0), c Float64 Float64(size = 0)
2024.01.04 02:49:08.599329 [ 3397 ] {ec016aec-8dcf-4575-b39b-a55ecff29b10} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2024.01.04 02:49:08.599368 [ 3397 ] {ec016aec-8dcf-4575-b39b-a55ecff29b10} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2024.01.04 02:49:08.599382 [ 3397 ] {ec016aec-8dcf-4575-b39b-a55ecff29b10} <Debug> JoiningTransform: Before join block: 'k UInt64 UInt64(size = 0)'
2024.01.04 02:49:08.599730 [ 3397 ] {ec016aec-8dcf-4575-b39b-a55ecff29b10} <Debug> JoiningTransform: After join block: 'k UInt64 UInt64(size = 0), key UInt64 UInt64(size = 0), multiply(1000, key) UInt64 UInt64(size = 0), b String String(size = 0), a UInt8 UInt8(size = 0), c Float64 Float64(size = 0)'
2024.01.04 02:49:08.599860 [ 3397 ] {ec016aec-8dcf-4575-b39b-a55ecff29b10} <Debug> JoiningTransform: Before join block: 'k UInt64 UInt64(size = 0)'
2024.01.04 02:49:08.600147 [ 3397 ] {ec016aec-8dcf-4575-b39b-a55ecff29b10} <Debug> JoiningTransform: After join block: 'k UInt64 UInt64(size = 0), key UInt64 UInt64(size = 0), multiply(1000, key) UInt64 UInt64(size = 0), b String String(size = 0), a UInt8 UInt8(size = 0), c Float64 Float64(size = 0)'
2024.01.04 02:49:08.600236 [ 3397 ] {ec016aec-8dcf-4575-b39b-a55ecff29b10} <Trace> ExpressionJIT: Compile expression if(UInt8, UInt64, multiply(UInt64, 1000 : UInt16))

```

```
2024-01-04 02:49:08 Thread 991 "TCPHandler" received signal SIGSEGV, Segmentation fault.
2024-01-04 02:49:08 [Switching to Thread 0xfff94fa586c0 (LWP 3397)]
2024-01-04 02:49:08 0x0000aaaabd60afc0 in isSelect01(llvm::APInt const&, llvm::APInt const&) ()
2024-01-04 02:49:08 #0  0x0000aaaabd60afc0 in isSelect01(llvm::APInt const&, llvm::APInt const&) ()
2024-01-04 02:49:09 No symbol table info available.
2024-01-04 02:49:09 #1  0x0000aaaabd5fe120 in llvm::InstCombinerImpl::foldSelectIntoOp(llvm::SelectInst&, llvm::Value*, llvm::Value*)::$_0::operator()(llvm::SelectInst&, llvm::Value*, llvm::Value*, bool) const ()
2024-01-04 02:49:09 No symbol table info available.
2024-01-04 02:49:09 #2  0x0000aaaabd5fdf08 in llvm::InstCombinerImpl::foldSelectIntoOp(llvm::SelectInst&, llvm::Value*, llvm::Value*) ()
2024-01-04 02:49:09 No symbol table info available.
2024-01-04 02:49:09 #3  0x0000aaaabd605f70 in llvm::InstCombinerImpl::visitSelectInst(llvm::SelectInst&) ()
2024-01-04 02:49:09 No symbol table info available.
2024-01-04 02:49:09 #4  0x0000aaaabd53d548 in llvm::InstCombinerImpl::run() ()
2024-01-04 02:49:09 No symbol table info available.
2024-01-04 02:49:09 #5  0x0000aaaabd544fa8 in llvm::InstructionCombiningPass::runOnFunction(llvm::Function&) ()
2024-01-04 02:49:09 No symbol table info available.
2024-01-04 02:49:09 #6  0x0000aaaabdcd4dd4 in llvm::FPPassManager::runOnFunction(llvm::Function&) ()
2024-01-04 02:49:09 No symbol table info available.
2024-01-04 02:49:09 #7  0x0000aaaabdcdff9c in llvm::FPPassManager::runOnModule(llvm::Module&) ()
2024-01-04 02:49:09 No symbol table info available.
2024-01-04 02:49:09 #8  0x0000aaaabdcd6270 in llvm::legacy::PassManagerImpl::run(llvm::Module&) ()
2024-01-04 02:49:11 No symbol table info available.
2024-01-04 02:49:11 #9  0x0000aaaabafd34dc in DB::CHJIT::runOptimizationPassesOnModule (module=..., this=<optimized out>) at ./build_docker/./src/Interpreters/JIT/CHJIT.cpp:511
2024-01-04 02:50:06         pass_manager_builder = <incomplete type>
2024-01-04 02:50:06         mpm = <incomplete type>
2024-01-04 02:50:06         fpm = <incomplete type>
2024-01-04 02:50:06         __begin1 = <optimized out>
2024-01-04 02:50:06         __end1 = <optimized out>
2024-01-04 02:50:06         __range1 = <optimized out>
2024-01-04 02:50:06         function = <optimized out>
2024-01-04 02:50:06 #10 DB::CHJIT::compileModule (this=0xaaaac0282fe0 <DB::getJITInstance()::jit>, module=...) at ./build_docker/./src/Interpreters/JIT/CHJIT.cpp:403
2024-01-04 02:50:40         object = <incomplete type>
2024-01-04 02:50:40         dynamic_linker = <incomplete type>
2024-01-04 02:50:40         buffer = <optimized out>
2024-01-04 02:50:40         module_memory_manager = <optimized out>
2024-01-04 02:50:40         linked_object = <optimized out>
2024-01-04 02:50:40         compiled_module = <optimized out>
2024-01-04 02:50:40 #11 0x0000aaaabafd2fb0 in DB::CHJIT::compileModule(std::__1::function<void (llvm::Module&)>) (this=0xaaaac0282fe0 <DB::getJITInstance()::jit>, compile_function=...) at ./build_docker/./src/Interpreters/JIT/CHJIT.cpp:386
2024-01-04 02:50:44         module = {__ptr_ = {<std::__1::__compressed_pair_elem<llvm::Module*, 0, false>> = {__value_ = 0x0}, <std::__1::__compressed_pair_elem<std::__1::default_delete<llvm::Module>, 1, true>> = {<std::__1::default_delete<llvm::Module>> = {<No data fields>}, <No data fields>}, <No data fields>}}
2024-01-04 02:50:44         lock = {__m_ = @0xaaaac02831e8}
2024-01-04 02:50:44         module_info = <optimized out>
2024-01-04 02:50:44 #12 0x0000aaaabafde244 in DB::compileFunction (jit=..., function=...) at ./build_docker/./src/Interpreters/JIT/compileFunction.cpp:172
2024-01-04 02:50:44         compiled_module = {size = 0, identifier = 0, function_name_to_symbol = {__table_ = {__bucket_list_ = {__ptr_ = {<std::__1::__compressed_pair_elem<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void*>, void*>*>**, 0, false>> = {__value_ = 0x0}, <std::__1::__compressed_pair_elem<std::__1::__bucket_list_deallocator<std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void*>, void*>*>*> >, 1, false>> = {__value_ = {__data_ = {<std::__1::__compressed_pair_elem<unsigned long, 0, false>> = {__value_ = 0}, <std::__1::__compressed_pair_elem<std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void*>, void*>*>*>, 1, true>> = {<std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void*>, void*>*>*>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void*>, void*>*>*> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}}, <No data fields>}}, __p1_ = {<std::__1::__compressed_pair_elem<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void*>, void*>*>, 0, false>> = {__value_ = {__next_ = 0x0}}, <std::__1::__compressed_pair_elem<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void*>, void*> >, 1, true>> = {<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void*>, void*> >> = {<std::__1::__non_trivial_if<true, std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void*>, void*> > >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, __p2_ = {<std::__1::__compressed_pair_elem<unsigned long, 0, false>> = {__value_ = 0}, <std::__1::__compressed_pair_elem<std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void*>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, 1, true>> = {<std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void*>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>> = {<std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >> = {<std::__1::__unary_function_keep_layout_base<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long>> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, __p3_ = {<std::__1::__compressed_pair_elem<float, 0, false>> = {__value_ = 4.23192136e-43}, <std::__1::__compressed_pair_elem<std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void*>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, 1, true>> = {<std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void*>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>> = {<std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >> = {<std::__1::__binary_function_keep_layout_base<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool>> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}}}
2024-01-04 02:50:44         watch = {start_ns = 18446743147840585571, stop_ns = 0, clock_type = 4, is_running = true}
2024-01-04 02:50:44         compiled_function_ptr = <optimized out>
2024-01-04 02:50:44         result_compiled_function = <optimized out>
```

https://pastila.nl/?0002e155/458845d4869f875308f515b7889bd250#y45YgZtXO8XgRHltrqdn+g==

**Comment by alexey-milovidov** [comment]
Reverted.
