### ISSUE TITLE
Peformace test `insert_values_with_expressions` runs timeout

### ISSUE THREAD

**Issue by lgbo-ustc** [ClickHouse/ClickHouse#58974]
(you don't have to strictly follow this form)

**Describe the situation**
What exactly works slower than expected?

It seems there is some problem with `insert_values_with_expressions`

https://s3.amazonaws.com/clickhouse-test-reports/55656/d1202a31526b87ed150a7313c3370b69ee493208/performance_comparison_aarch64_[2_4]/report.html
https://s3.amazonaws.com/clickhouse-test-reports/53406/bc0cdce596091a33600242d37c3f4140a273335d/performance_comparison_aarch64_[2_4]/report.html

Both got 
```
Traceback (most recent call last):
  File "/workspace/right/scripts/perf.py", line 430, in <module>
    res = c.execute(
  File "/usr/local/lib/python3.10/dist-packages/clickhouse_driver/client.py", line 267, in execute
    rv = self.process_ordinary_query(
  File "/usr/local/lib/python3.10/dist-packages/clickhouse_driver/client.py", line 453, in process_ordinary_query
    return self.receive_result(with_column_types=with_column_types,
  File "/usr/local/lib/python3.10/dist-packages/clickhouse_driver/client.py", line 117, in receive_result
    return result.get_result()
  File "/usr/local/lib/python3.10/dist-packages/clickhouse_driver/result.py", line 50, in get_result
    for packet in self.packet_generator:
  File "/usr/local/lib/python3.10/dist-packages/clickhouse_driver/client.py", line 133, in packet_generator
    packet = self.receive_packet()
  File "/usr/local/lib/python3.10/dist-packages/clickhouse_driver/client.py", line 150, in receive_packet
    raise packet.exception
clickhouse_driver.errors.ServerException: Code: 159.
insert_values_with_expressions.query0.run0: DB::Exception: Timeout exceeded: elapsed 23.093577582 seconds, maximum: 15. Stack trace:

0. ./build_docker/./src/Common/Exception.cpp:96: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000bbf4288 in /workspace/left/clickhouse
1. ./contrib/llvm-project/libcxx/include/string:1499: DB::Exception::Exception<double, double>(int, FormatStringHelperImpl<std::type_identity<double>::type, std::type_identity<double>::type>, double&&, double&&) @ 0x000000000f4b61d8 in /workspace/left/clickhouse
2. ./build_docker/./src/QueryPipeline/ExecutionSpeedLimits.cpp:0: DB::ExecutionSpeedLimits::checkTimeLimit(Stopwatch const&, DB::OverflowMode) const @ 0x000000000f4b60f8 in /workspace/left/clickhouse
3. ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:198: DB::PipelineExecutor::finalizeExecution() @ 0x00000000110bc900 in /workspace/left/clickhouse
4. ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:132: DB::PipelineExecutor::execute(unsigned long, bool) @ 0x00000000110bc680 in /workspace/left/clickhouse
5. ./build_docker/./src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:96: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x00000000110c84a8 in /workspace/left/clickhouse
6. ./base/base/../base/wide_integer_impl.h:809: void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000bcbee88 in /workspace/left/clickhouse
7. ? @ 0x000000000007d5c8 in /usr/lib/aarch64-linux-gnu/libc.so.6
8. ? @ 0x00000000000e5d5c in /usr/lib/aarch64-linux-gnu/libc.so.6

Test insert_values_with_expressions failed with error code 1
```

**How to reproduce**
* Which ClickHouse server version to use
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to slow performance

**Expected performance**
What are your performance expectation, why do you think they are realistic? Has it been working faster in older ClickHouse releases? Is it working faster in some specific other system?

**Additional context**

**Comment by tavplubix** [comment]
The template-based evaluation is broken:
```
localhost.localdomain :) set input_format_values_interpret_expressions=0

SET input_format_values_interpret_expressions = 0

Query id: 503ed32b-6b3b-4d9b-95ca-a0630ee4b0c3

Ok.

0 rows in set. Elapsed: 0.003 sec. 

localhost.localdomain :) select * from file('test_all_expr_matches.values', Values, 'd DateTime, i UInt32, s String, ni Nullable(UInt64), ns Nullable(String), ars Array(String)') format Null

SELECT *
FROM file('test_all_expr_matches.values', Values, 'd DateTime, i UInt32, s String, ni Nullable(UInt64), ns Nullable(String), ars Array(String)')
FORMAT `Null`

Query id: db696ac6-e946-4039-a22e-cf1845595e15


Elapsed: 0.141 sec. 

Received exception from server (version 24.1.1):
Code: 62. DB::Exception: Received from localhost:9000. DB::Exception: Cannot deduce template of expression: if(0 == 0, NULL,  format('{0}.{1}.{2}', toString(0), toString(0), '')), : (in file/uri /home/tavplubix/ch/test/repl/user_files/test_all_expr_matches.values): While executing ValuesBlockInputFormat: While executing File. Stack trace:

0. /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/exception:134: std::exception::capture() @ 0x000000000a97d022 in /home/tavplubix/ch/ClickHouse/cmake-build-debug/programs/clickhouse
1. /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/exception:112: std::exception::exception[abi:v15000]() @ 0x000000000a97cfed in /home/tavplubix/ch/ClickHouse/cmake-build-debug/programs/clickhouse
2. /home/tavplubix/ch/ClickHouse/base/poco/Foundation/src/Exception.cpp:27: Poco::Exception::Exception(String const&, int) @ 0x0000000024f9de20 in /home/tavplubix/ch/ClickHouse/cmake-build-debug/programs/clickhouse
3. /home/tavplubix/ch/ClickHouse/src/Common/Exception.cpp:94: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000001490bfbb in /home/tavplubix/ch/ClickHouse/cmake-build-debug/programs/clickhouse
4. /home/tavplubix/ch/ClickHouse/src/Common/Exception.h:86: DB::Exception::Exception(String&&, int, bool) @ 0x000000000a96dbf7 in /home/tavplubix/ch/ClickHouse/cmake-build-debug/programs/clickhouse
5. /home/tavplubix/ch/ClickHouse/src/Common/Exception.h:105: DB::Exception::Exception<String>(int, FormatStringHelperImpl<std::type_identity<String>::type>, String&&) @ 0x000000000a96da64 in /home/tavplubix/ch/ClickHouse/cmake-build-debug/programs/clickhouse
6. /home/tavplubix/ch/ClickHouse/src/Processors/Formats/Impl/ValuesBlockInputFormat.cpp:524: DB::ValuesBlockInputFormat::parseExpression(DB::IColumn&, unsigned long) @ 0x000000002058e93e in /home/tavplubix/ch/ClickHouse/cmake-build-debug/programs/clickhouse
7. /home/tavplubix/ch/ClickHouse/src/Processors/Formats/Impl/ValuesBlockInputFormat.cpp:319: DB::ValuesBlockInputFormat::readRow(std::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn>>>&, unsigned long) @ 0x000000002058b360 in /home/tavplubix/ch/ClickHouse/cmake-build-debug/programs/clickhouse
8. /home/tavplubix/ch/ClickHouse/src/Processors/Formats/Impl/ValuesBlockInputFormat.cpp:122: DB::ValuesBlockInputFormat::read() @ 0x000000002058a54b in /home/tavplubix/ch/ClickHouse/cmake-build-debug/programs/clickhouse
9. /home/tavplubix/ch/ClickHouse/src/Processors/Formats/IInputFormat.cpp:19: DB::IInputFormat::generate() @ 0x000000002003a90a in /home/tavplubix/ch/ClickHouse/cmake-build-debug/programs/clickhouse
10. /home/tavplubix/ch/ClickHouse/src/Processors/ISource.cpp:139: DB::ISource::tryGenerate() @ 0x000000001ffe6b20 in /home/tavplubix/ch/ClickHouse/cmake-build-debug/programs/clickhouse
11. /home/tavplubix/ch/ClickHouse/src/Processors/ISource.cpp:108: DB::ISource::work() @ 0x000000001ffe6763 in /home/tavplubix/ch/ClickHouse/cmake-build-debug/programs/clickhouse
12. /home/tavplubix/ch/ClickHouse/src/Processors/Executors/ExecutionThreadContext.cpp:47: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*) @ 0x0000000020026490 in /home/tavplubix/ch/ClickHouse/cmake-build-debug/programs/clickhouse
13. /home/tavplubix/ch/ClickHouse/src/Processors/Executors/ExecutionThreadContext.cpp:95: DB::ExecutionThreadContext::executeTask() @ 0x0000000020026161 in /home/tavplubix/ch/ClickHouse/cmake-build-debug/programs/clickhouse
14. /home/tavplubix/ch/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:273: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x0000000020007a1e in /home/tavplubix/ch/ClickHouse/cmake-build-debug/programs/clickhouse
15. /home/tavplubix/ch/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:148: DB::PipelineExecutor::executeStep(std::atomic<bool>*) @ 0x000000002000743e in /home/tavplubix/ch/ClickHouse/cmake-build-debug/programs/clickhouse
16. /home/tavplubix/ch/ClickHouse/src/Processors/Executors/PullingPipelineExecutor.cpp:54: DB::PullingPipelineExecutor::pull(DB::Chunk&) @ 0x0000000020031a4b in /home/tavplubix/ch/ClickHouse/cmake-build-debug/programs/clickhouse
17. /home/tavplubix/ch/ClickHouse/src/Storages/StorageFile.cpp:1248: DB::StorageFileSource::generate() @ 0x000000001ed44ee6 in /home/tavplubix/ch/ClickHouse/cmake-build-debug/programs/clickhouse
18. /home/tavplubix/ch/ClickHouse/src/Processors/ISource.cpp:139: DB::ISource::tryGenerate() @ 0x000000001ffe6b20 in /home/tavplubix/ch/ClickHouse/cmake-build-debug/programs/clickhouse
19. /home/tavplubix/ch/ClickHouse/src/Processors/ISource.cpp:108: DB::ISource::work() @ 0x000000001ffe6763 in /home/tavplubix/ch/ClickHouse/cmake-build-debug/programs/clickhouse
20. /home/tavplubix/ch/ClickHouse/src/Processors/Executors/ExecutionThreadContext.cpp:47: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*) @ 0x0000000020026490 in /home/tavplubix/ch/ClickHouse/cmake-build-debug/programs/clickhouse
21. /home/tavplubix/ch/ClickHouse/src/Processors/Executors/ExecutionThreadContext.cpp:95: DB::ExecutionThreadContext::executeTask() @ 0x0000000020026161 in /home/tavplubix/ch/ClickHouse/cmake-build-debug/programs/clickhouse
22. /home/tavplubix/ch/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:273: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x0000000020007a1e in /home/tavplubix/ch/ClickHouse/cmake-build-debug/programs/clickhouse
23. /home/tavplubix/ch/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:239: DB::PipelineExecutor::executeSingleThread(unsigned long) @ 0x0000000020007e44 in /home/tavplubix/ch/ClickHouse/cmake-build-debug/programs/clickhouse
24. /home/tavplubix/ch/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:373: DB::PipelineExecutor::spawnThreads()::$_0::operator()() const @ 0x0000000020008ca7 in /home/tavplubix/ch/ClickHouse/cmake-build-debug/programs/clickhouse
25. /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/invoke.h:394: ? @ 0x0000000020008bf5 in /home/tavplubix/ch/ClickHouse/cmake-build-debug/programs/clickhouse
26. /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/invoke.h:480: ? @ 0x0000000020008bd5 in /home/tavplubix/ch/ClickHouse/cmake-build-debug/programs/clickhouse
27. /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:235: ? @ 0x0000000020008bb5 in /home/tavplubix/ch/ClickHouse/cmake-build-debug/programs/clickhouse
28. /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x0000000020008b80 in /home/tavplubix/ch/ClickHouse/cmake-build-debug/programs/clickhouse
29. /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:848: ? @ 0x0000000012ffdd16 in /home/tavplubix/ch/ClickHouse/cmake-build-debug/programs/clickhouse
30. /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:1187: ? @ 0x0000000012ffd8b5 in /home/tavplubix/ch/ClickHouse/cmake-build-debug/programs/clickhouse
31. /home/tavplubix/ch/ClickHouse/src/Common/ThreadPool.cpp:455: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x0000000014ab393e in /home/tavplubix/ch/ClickHouse/cmake-build-debug/programs/clickhouse
. (SYNTAX_ERROR)

```

**Comment by tavplubix** [comment]
Fixed by https://github.com/ClickHouse/ClickHouse/pull/59070
