### ISSUE TITLE
`Logical error: 'status == LoadStatus::CANCELED'.`

### ISSUE THREAD

**Issue by kssenii** [ClickHouse/ClickHouse#59026]
https://s3.amazonaws.com/clickhouse-test-reports/56864/7c66141e08ec203dbff908d69d929ea3bfc0995f/stress_test__tsan_.html

cc @serxa 

```
2024-01-19 20:19:26 #0  0x00007f0c78af79fc in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
2024-01-19 20:19:26 No symbol table info available.
2024-01-19 20:19:26 #1  0x00007f0c78aa3476 in raise () from /lib/x86_64-linux-gnu/libc.so.6
2024-01-19 20:19:26 No symbol table info available.
2024-01-19 20:19:26 #2  0x00007f0c78a897f3 in abort () from /lib/x86_64-linux-gnu/libc.so.6
2024-01-19 20:19:26 No symbol table info available.
2024-01-19 20:19:26 #3  0x00005611e37bc3b3 in __interceptor_abort ()
2024-01-19 20:19:26 No symbol table info available.
2024-01-19 20:19:26 #4  0x00005611ebb158ab in DB::abortOnFailedAssertion (description=...) at ./build_docker/./src/Common/Exception.cpp:43
2024-01-19 20:19:26 No locals.
2024-01-19 20:19:26 #5  0x00005611ebce22e0 in DB::AsyncLoader::finish (this=this@entry=0x7b3c0000cd50, job=..., status=status@entry=DB::LoadStatus::FAILED, reason=..., lock=...) at ./build_docker/./src/Common/AsyncLoader.cpp:601
2024-01-19 20:19:26         dpt_info = {__i_ = {__node_ = 0x0}}
2024-01-19 20:19:26         dpt = @0x7b0800974410: {__ptr_ = 0x7b44036f3f98, __cntrl_ = 0x7b44036f3f80}
2024-01-19 20:19:26         __range1 = @0x7f083b025a38: {__table_ = {__bucket_list_ = {__ptr_ = {<std::__1::__compressed_pair_elem<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::shared_ptr<DB::LoadJob>, void*>*>**, 0, false>> = {__value_ = 0x7b0c00e68800}, <std::__1::__compressed_pair_elem<std::__1::__bucket_list_deallocator<std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::shared_ptr<DB::LoadJob>, void*>*>*> >, 1, false>> = {__value_ = {__data_ = {<std::__1::__compressed_pair_elem<unsigned long, 0, false>> = {__value_ = 5}, <std::__1::__compressed_pair_elem<std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::shared_ptr<DB::LoadJob>, void*>*>*>, 1, true>> = {<std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::shared_ptr<DB::LoadJob>, void*>*>*>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::shared_ptr<DB::LoadJob>, void*>*>*> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}}, <No data fields>}}, __p1_ = {<std::__1::__compressed_pair_elem<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::shared_ptr<DB::LoadJob>, void*>*>, 0, false>> = {__value_ = {__next_ = 0x7b0800bb4120}}, <std::__1::__compressed_pair_elem<std::__1::allocator<std::__1::__hash_node<std::__1::shared_ptr<DB::LoadJob>, void*> >, 1, true>> = {<std::__1::allocator<std::__1::__hash_node<std::__1::shared_ptr<DB::LoadJob>, void*> >> = {<std::__1::__non_trivial_if<true, std::__1::allocator<std::__1::__hash_node<std::__1::shared_ptr<DB::LoadJob>, void*> > >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, __p2_ = {<std::__1::__compressed_pair_elem<unsigned long, 0, false>> = {__value_ = 4}, <std::__1::__compressed_pair_elem<std::__1::hash<std::__1::shared_ptr<DB::LoadJob> >, 1, true>> = {<std::__1::hash<std::__1::shared_ptr<DB::LoadJob> >> = {<No data fields>}, <No data fields>}, <No data fields>}, __p3_ = {<std::__1::__compressed_pair_elem<float, 0, false>> = {__value_ = 1}, <std::__1::__compressed_pair_elem<std::__1::equal_to<std::__1::shared_ptr<DB::LoadJob> >, 1, true>> = {<std::__1::equal_to<std::__1::shared_ptr<DB::LoadJob> >> = {<std::__1::__binary_function_keep_layout_base<std::__1::shared_ptr<DB::LoadJob>, std::__1::shared_ptr<DB::LoadJob>, bool>> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}}
2024-01-19 20:19:26         __begin1 = {__node_ = 0x7b0800974400}
2024-01-19 20:19:26         __end1 = {__node_ = 0x0}
2024-01-19 20:19:26         dependent = {__table_ = {__bucket_list_ = {__ptr_ = {<std::__1::__compressed_pair_elem<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::shared_ptr<DB::LoadJob>, void*>*>**, 0, false>> = {__value_ = 0x0}, <std::__1::__compressed_pair_elem<std::__1::__bucket_list_deallocator<std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::shared_ptr<DB::LoadJob>, void*>*>*> >, 1, false>> = {__value_ = {__data_ = {<std::__1::__compressed_pair_elem<unsigned long, 0, false>> = {__value_ = 0}, <std::__1::__compressed_pair_elem<std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::shared_ptr<DB::LoadJob>, void*>*>*>, 1, true>> = {<std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::shared_ptr<DB::LoadJob>, void*>*>*>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::shared_ptr<DB::LoadJob>, void*>*>*> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}}, <No data fields>}}, __p1_ = {<std::__1::__compressed_pair_elem<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::shared_ptr<DB::LoadJob>, void*>*>, 0, false>> = {__value_ = {__next_ = 0x0}}, <std::__1::__compressed_pair_elem<std::__1::allocator<std::__1::__hash_node<std::__1::shared_ptr<DB::LoadJob>, void*> >, 1, true>> = {<std::__1::allocator<std::__1::__hash_node<std::__1::shared_ptr<DB::LoadJob>, void*> >> = {<std::__1::__non_trivial_if<true, std::__1::allocator<std::__1::__hash_node<std::__1::shared_ptr<DB::LoadJob>, void*> > >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, __p2_ = {<std::__1::__compressed_pair_elem<unsigned long, 0, false>> = {__value_ = 0}, <std::__1::__compressed_pair_elem<std::__1::hash<std::__1::shared_ptr<DB::LoadJob> >, 1, true>> = {<std::__1::hash<std::__1::shared_ptr<DB::LoadJob> >> = {<No data fields>}, <No data fields>}, <No data fields>}, __p3_ = {<std::__1::__compressed_pair_elem<float, 0, false>> = {__value_ = 1}, <std::__1::__compressed_pair_elem<std::__1::equal_to<std::__1::shared_ptr<DB::LoadJob> >, 1, true>> = {<std::__1::equal_to<std::__1::shared_ptr<DB::LoadJob> >> = {<std::__1::__binary_function_keep_layout_base<std::__1::shared_ptr<DB::LoadJob>, std::__1::shared_ptr<DB::LoadJob>, bool>> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}}
2024-01-19 20:19:26         info = <optimized out>
2024-01-19 20:19:26 #6  0x00005611ebce443c in DB::AsyncLoader::worker (this=this@entry=0x7b3c0000cd50, pool=...) at ./build_docker/./src/Common/AsyncLoader.cpp:823
2024-01-19 20:19:26         lock = {__m_ = 0x7b3c0000cd60, __owns_ = true}
2024-01-19 20:19:26         it = <optimized out>
2024-01-19 20:19:26         exception_from_job = {__ptr_ = 0x7b50041ae480}
2024-01-19 20:19:26         job = <optimized out>
2024-01-19 20:19:26         pool_id = 0
2024-01-19 20:19:26 #7  0x00005611ebce4c73 in DB::AsyncLoader::spawn(DB::AsyncLoader::Pool&, std::__1::unique_lock<std::__1::mutex>&)::$_0::operator()() const (this=<optimized out>) at ./build_docker/./src/Common/AsyncLoader.cpp:800
2024-01-19 20:19:26 No locals.
2024-01-19 20:19:26 #8  std::__1::__invoke[abi:v15000]<DB::AsyncLoader::spawn(DB::AsyncLoader::Pool&, std::__1::unique_lock<std::__1::mutex>&)::$_0&>(DB::AsyncLoader::spawn(DB::AsyncLoader::Pool&, std::__1::unique_lock<std::__1::mutex>&)::$_0&) (__f=...) at ./contrib/llvm-project/libcxx/include/__functional/invoke.h:394
2024-01-19 20:19:26 No locals.
2024-01-19 20:19:26 #9  std::__1::__invoke_void_return_wrapper<void, true>::__call<DB::AsyncLoader::spawn(DB::AsyncLoader::Pool&, std::__1::unique_lock<std::__1::mutex>&)::$_0&>(DB::AsyncLoader::spawn(DB::AsyncLoader::Pool&, std::__1::unique_lock<std::__1::mutex>&)::$_0&) (__args=...) at ./contrib/llvm-project/libcxx/include/__functional/invoke.h:479
2024-01-19 20:19:26 No locals.
2024-01-19 20:19:26 #10 std::__1::__function::__default_alloc_func<DB::AsyncLoader::spawn(DB::AsyncLoader::Pool&, std::__1::unique_lock<std::__1::mutex>&)::$_0, void ()>::operator()[abi:v15000]() (this=<optimized out>) at ./contrib/llvm-project/libcxx/include/__functional/function.h:235
2024-01-19 20:19:26 No locals.
2024-01-19 20:19:26 #11 std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::AsyncLoader::spawn(DB::AsyncLoader::Pool&, std::__1::unique_lock<std::__1::mutex>&)::$_0, void ()> >(std::__1::__function::__policy_storage const*) (__buf=0x7f083b025ed8) at ./contrib/llvm-project/libcxx/include/__functional/function.h:716
2024-01-19 20:19:26         __f = 0x7f083b025ed8
2024-01-19 20:19:26 #12 0x00005611ebc4666f in std::__1::__function::__policy_func<void ()>::operator()[abi:v15000]() const (this=0x7f083b025ed8) at ./contrib/llvm-project/libcxx/include/__functional/function.h:848
2024-01-19 20:19:26 No locals.
2024-01-19 20:19:26 #13 std::__1::function<void ()>::operator()() const (this=0x7f083b025ed8) at ./contrib/llvm-project/libcxx/include/__functional/function.h:1187
2024-01-19 20:19:26 No locals.
2024-01-19 20:19:26 #14 ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::worker (this=this@entry=0x7b4400057d00, thread_it=thread_it@entry=...) at ./build_docker/./src/Common/ThreadPool.cpp:455
2024-01-19 20:19:26         metric_active_pool_threads = {what = <optimized out>, amount = 1}
2024-01-19 20:19:26         job_data = <optimized out>
2024-01-19 20:19:26         thread_trace_context = <optimized out>
2024-01-19 20:19:26         exception_from_job = {__ptr_ = 0x0}
2024-01-19 20:19:26         metric_pool_threads = {what = 0x5611fe7596a0 <CurrentMetrics::values+880>, amount = 1}
2024-01-19 20:19:26         job_is_done = <optimized out>
```

**Comment by serxa** [comment]
Fix is here https://github.com/ClickHouse/ClickHouse/pull/59011
