### ISSUE TITLE
Segfault in `AggregateFunctionTopK`

### ISSUE THREAD

**Issue by kssenii** [ClickHouse/ClickHouse#59107]
https://s3.amazonaws.com/clickhouse-test-reports/59049/4b4eac7c0604b1d5eac9a8a821f96d32474d1e5d/ast_fuzzer__tsan_/report.html

```
2024.01.22 15:22:39.822096 [ 1226 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2024.01.22 15:22:39.822159 [ 1226 ] {} <Fatal> BaseDaemon: (version 24.1.1.1, build id: 33D0E98755324BB79B08F5623A4BFC88C9C649E8, git hash: acce2743b450d28b45be77a8c85db255bd05e0ac) (from thread 967) Received signal 11
2024.01.22 15:22:39.822191 [ 1226 ] {} <Fatal> BaseDaemon: Signal description: Segmentation fault
2024.01.22 15:22:39.822224 [ 1226 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2024.01.22 15:22:39.822267 [ 1226 ] {} <Fatal> BaseDaemon: Stack trace: 0x000055de5ad3d422 0x000055de65f51863 0x000055de65ec2d1f 0x000055de6b5fffa8 0x000055de6b6104eb 0x000055de6b618052 0x000055de6e14f1ba 0x000055de6668c194 0x000055de6dd3f645 0x000055de6dd68435 0x000055de6dd5b5f1 0x000055de6dd5c0d1 0x000055de63157f2f 0x000055de6315c2fd 0x000055de6315c262 0x000055de6315420f 0x000055de6315a0d2 0x000055de5accb5cf 0x00007f5c6d9afac3 0x00007f5c6da41660
2024.01.22 15:22:39.822305 [ 1226 ] {} <Fatal> BaseDaemon: ########################################
2024.01.22 15:22:39.822502 [ 1226 ] {} <Fatal> BaseDaemon: (version 24.1.1.1, build id: 33D0E98755324BB79B08F5623A4BFC88C9C649E8, git hash: acce2743b450d28b45be77a8c85db255bd05e0ac) (from thread 967) (query_id: 26f45bf7-2fd0-4cf9-9d32-f85b703a309b) (query: SELECT NULL, NULL AND (toDate(topK('102.4') IGNORE NULLS, toDate(NULL) AND NULL, toDate(NULL, 1025 AND (toDate(9223372036854775807, NULL, 9223372036854775807, NULL) AND NULL) AND NULL, NULL)) AND toDate(2147483646, NULL) AND NULL) FROM remote('127.0.0.{1,2}', view(SELECT NULL FROM system.one WHERE toDate(toDate(toDate(NULL, 1025 AND (toDate(-1, NULL, 9223372036854775807, NULL) AND NULL) AND NULL, NULL), NULL, NULL, NULL), NULL) GROUP BY GROUPING SETS ((''))))) Received signal Segmentation fault (11)
2024.01.22 15:22:39.822608 [ 1226 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2024.01.22 15:22:39.822680 [ 1226 ] {} <Fatal> BaseDaemon: Stack trace: 0x000055de5ad3d422 0x000055de65f51863 0x000055de65ec2d1f 0x000055de6b5fffa8 0x000055de6b6104eb 0x000055de6b618052 0x000055de6e14f1ba 0x000055de6668c194 0x000055de6dd3f645 0x000055de6dd68435 0x000055de6dd5b5f1 0x000055de6dd5c0d1 0x000055de63157f2f 0x000055de6315c2fd 0x000055de6315c262 0x000055de6315420f 0x000055de6315a0d2 0x000055de5accb5cf 0x00007f5c6d9afac3 0x00007f5c6da41660
2024.01.22 15:22:44.534373 [ 1226 ] {} <Fatal> BaseDaemon: 5. ? @ 0x00000000073a3422 in /workspace/clickhouse
2024.01.22 15:22:45.137107 [ 1226 ] {} <Fatal> BaseDaemon: 6.0. inlined from ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:274: std::unique_ptr<DB::SpaceSaving<StringRef, StringRefHash>::Counter, std::default_delete<DB::SpaceSaving<StringRef, StringRefHash>::Counter>>::operator->[abi:v15000]() const
2024.01.22 15:22:45.137260 [ 1226 ] {} <Fatal> BaseDaemon: 6. ./src/Common/SpaceSaving.h:219: DB::SpaceSaving<StringRef, StringRefHash>::merge(DB::SpaceSaving<StringRef, StringRefHash> const&) @ 0x00000000125b7863 in /workspace/clickhouse
2024.01.22 15:22:45.715477 [ 1226 ] {} <Fatal> BaseDaemon: 7. ./build_docker/./src/AggregateFunctions/AggregateFunctionTopK.cpp:242: DB::(anonymous namespace)::AggregateFunctionTopKGeneric<true, false>::merge(char*, char const*, DB::Arena*) const @ 0x0000000012528d1f in /workspace/clickhouse
2024.01.22 15:22:48.409504 [ 1226 ] {} <Fatal> BaseDaemon: 8. ./build_docker/./src/Interpreters/Aggregator.cpp:3068: DB::Aggregator::mergeWithoutKeyStreamsImpl(DB::AggregatedDataVariants&, unsigned long, unsigned long, std::vector<DB::PODArray<char*, 4096ul, Allocator<false, false>, 63ul, 64ul> const*, std::allocator<DB::PODArray<char*, 4096ul, Allocator<false, false>, 63ul, 64ul> const*>> const&) const @ 0x0000000017c65fa8 in /workspace/clickhouse
2024.01.22 15:22:51.323716 [ 1226 ] {} <Fatal> BaseDaemon: 9. ./build_docker/./src/Interpreters/Aggregator.cpp:0: DB::Aggregator::mergeBlockWithoutKeyStreamsImpl(DB::Block, DB::AggregatedDataVariants&) const @ 0x0000000017c764eb in /workspace/clickhouse
2024.01.22 15:22:54.296452 [ 1226 ] {} <Fatal> BaseDaemon: 10.0. inlined from ./contrib/llvm-project/libcxx/include/__hash_table:1473: ~__hash_table
2024.01.22 15:22:54.296558 [ 1226 ] {} <Fatal> BaseDaemon: 10.1. inlined from ./contrib/llvm-project/libcxx/include/unordered_map:1153: ~unordered_map
2024.01.22 15:22:54.296616 [ 1226 ] {} <Fatal> BaseDaemon: 10.2. inlined from ./src/Core/Block.h:25: ~Block
2024.01.22 15:22:54.296685 [ 1226 ] {} <Fatal> BaseDaemon: 10. ./build_docker/./src/Interpreters/Aggregator.cpp:3335: DB::Aggregator::mergeBlocks(std::list<DB::Block, std::allocator<DB::Block>>&, bool) @ 0x0000000017c7e052 in /workspace/clickhouse
2024.01.22 15:22:54.444181 [ 1226 ] {} <Fatal> BaseDaemon: 11. ./build_docker/./src/Processors/Transforms/MergingAggregatedMemoryEfficientTransform.cpp:0: DB::MergingAggregatedBucketTransform::transform(DB::Chunk&) @ 0x000000001a7b51ba in /workspace/clickhouse
2024.01.22 15:22:54.543917 [ 1226 ] {} <Fatal> BaseDaemon: 12.0. inlined from ./contrib/llvm-project/libcxx/include/__utility/swap.h:35: std::enable_if<is_move_constructible<COW<DB::IColumn>::immutable_ptr<DB::IColumn>*>::value && is_move_assignable<COW<DB::IColumn>::immutable_ptr<DB::IColumn>*>::value, void>::type std::swap[abi:v15000]<COW<DB::IColumn>::immutable_ptr<DB::IColumn>*>(COW<DB::IColumn>::immutable_ptr<DB::IColumn>*&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>*&)
2024.01.22 15:22:54.544074 [ 1226 ] {} <Fatal> BaseDaemon: 12.1. inlined from ./contrib/llvm-project/libcxx/include/vector:1950: std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>::swap(std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&)
2024.01.22 15:22:54.544152 [ 1226 ] {} <Fatal> BaseDaemon: 12.2. inlined from ./src/Processors/Chunk.h:64: DB::Chunk::swap(DB::Chunk&)
2024.01.22 15:22:54.544220 [ 1226 ] {} <Fatal> BaseDaemon: 12. ./src/Processors/ISimpleTransform.h:33: DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) @ 0x0000000012cf2194 in /workspace/clickhouse
2024.01.22 15:22:54.602138 [ 1226 ] {} <Fatal> BaseDaemon: 13. ./build_docker/./src/Processors/ISimpleTransform.cpp:99: DB::ISimpleTransform::work() @ 0x000000001a3a5645 in /workspace/clickhouse
2024.01.22 15:22:54.622244 [ 1226 ] {} <Fatal> BaseDaemon: 14.0. inlined from ./contrib/llvm-project/libcxx/include/list:588: std::__list_imp<DB::ExecutingGraph::Edge, std::allocator<DB::ExecutingGraph::Edge>>::__sz[abi:v15000]() const
2024.01.22 15:22:54.622360 [ 1226 ] {} <Fatal> BaseDaemon: 14.1. inlined from ./contrib/llvm-project/libcxx/include/list:616: std::__list_imp<DB::ExecutingGraph::Edge, std::allocator<DB::ExecutingGraph::Edge>>::empty[abi:v15000]() const
2024.01.22 15:22:54.622452 [ 1226 ] {} <Fatal> BaseDaemon: 14.2. inlined from ./contrib/llvm-project/libcxx/include/list:918: std::list<DB::ExecutingGraph::Edge, std::allocator<DB::ExecutingGraph::Edge>>::empty[abi:v15000]() const
2024.01.22 15:22:54.622530 [ 1226 ] {} <Fatal> BaseDaemon: 14.3. inlined from ./build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:50: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
2024.01.22 15:22:54.622614 [ 1226 ] {} <Fatal> BaseDaemon: 14. ./build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:95: DB::ExecutionThreadContext::executeTask() @ 0x000000001a3ce435 in /workspace/clickhouse
2024.01.22 15:22:54.701619 [ 1226 ] {} <Fatal> BaseDaemon: 15.0. inlined from ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:273: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*)
2024.01.22 15:22:54.701735 [ 1226 ] {} <Fatal> BaseDaemon: 15. ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:239: DB::PipelineExecutor::executeSingleThread(unsigned long) @ 0x000000001a3c15f1 in /workspace/clickhouse
2024.01.22 15:22:54.793494 [ 1226 ] {} <Fatal> BaseDaemon: 16.0. inlined from ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:381: operator()
2024.01.22 15:22:54.793581 [ 1226 ] {} <Fatal> BaseDaemon: 16.1. inlined from ./contrib/llvm-project/libcxx/include/__functional/invoke.h:394: ?
2024.01.22 15:22:54.793619 [ 1226 ] {} <Fatal> BaseDaemon: 16.2. inlined from ./contrib/llvm-project/libcxx/include/__functional/invoke.h:479: ?
2024.01.22 15:22:54.793657 [ 1226 ] {} <Fatal> BaseDaemon: 16.3. inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:235: ?
2024.01.22 15:22:54.793695 [ 1226 ] {} <Fatal> BaseDaemon: 16. ./contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x000000001a3c20d1 in /workspace/clickhouse
2024.01.22 15:22:54.865340 [ 1226 ] {} <Fatal> BaseDaemon: 17.0. inlined from ./base/base/../base/wide_integer_impl.h:809: bool wide::integer<128ul, unsigned int>::_impl::operator_eq<wide::integer<128ul, unsigned int>>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
2024.01.22 15:22:54.865446 [ 1226 ] {} <Fatal> BaseDaemon: 17.1. inlined from ./base/base/../base/wide_integer_impl.h:1482: bool wide::operator==<128ul, unsigned int, 128ul, unsigned int>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
2024.01.22 15:22:54.865507 [ 1226 ] {} <Fatal> BaseDaemon: 17.2. inlined from ./base/base/../base/strong_typedef.h:42: StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>::operator==(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&) const
2024.01.22 15:22:54.865548 [ 1226 ] {} <Fatal> BaseDaemon: 17.3. inlined from ./src/Common/OpenTelemetryTraceContext.h:65: DB::OpenTelemetry::Span::isTraceEnabled() const
2024.01.22 15:22:54.865597 [ 1226 ] {} <Fatal> BaseDaemon: 17. ./build_docker/./src/Common/ThreadPool.cpp:457: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x000000000f7bdf2f in /workspace/clickhouse
2024.01.22 15:22:54.919472 [ 1226 ] {} <Fatal> BaseDaemon: 18. ./build_docker/./src/Common/ThreadPool.cpp:0: ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'()::operator()() @ 0x000000000f7c22fd in /workspace/clickhouse
2024.01.22 15:22:55.000516 [ 1226 ] {} <Fatal> BaseDaemon: 19. ./contrib/llvm-project/libcxx/include/__functional/function.h:717: ? @ 0x000000000f7c2262 in /workspace/clickhouse
2024.01.22 15:22:55.061326 [ 1226 ] {} <Fatal> BaseDaemon: 20.0. inlined from ./base/base/../base/wide_integer_impl.h:809: bool wide::integer<128ul, unsigned int>::_impl::operator_eq<wide::integer<128ul, unsigned int>>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
2024.01.22 15:22:55.061438 [ 1226 ] {} <Fatal> BaseDaemon: 20.1. inlined from ./base/base/../base/wide_integer_impl.h:1482: bool wide::operator==<128ul, unsigned int, 128ul, unsigned int>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
2024.01.22 15:22:55.061492 [ 1226 ] {} <Fatal> BaseDaemon: 20.2. inlined from ./base/base/../base/strong_typedef.h:42: StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>::operator==(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&) const
2024.01.22 15:22:55.061550 [ 1226 ] {} <Fatal> BaseDaemon: 20.3. inlined from ./src/Common/OpenTelemetryTraceContext.h:65: DB::OpenTelemetry::Span::isTraceEnabled() const
2024.01.22 15:22:55.061592 [ 1226 ] {} <Fatal> BaseDaemon: 20. ./build_docker/./src/Common/ThreadPool.cpp:457: ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0x000000000f7ba20f in /workspace/clickhouse
2024.01.22 15:22:55.144187 [ 1226 ] {} <Fatal> BaseDaemon: 21.0. inlined from ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:302: std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>::reset[abi:v15000](std::__thread_struct*)
2024.01.22 15:22:55.144290 [ 1226 ] {} <Fatal> BaseDaemon: 21.1. inlined from ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
2024.01.22 15:22:55.144350 [ 1226 ] {} <Fatal> BaseDaemon: 21.2. inlined from ./contrib/llvm-project/libcxx/include/tuple:265: ~__tuple_leaf
2024.01.22 15:22:55.144402 [ 1226 ] {} <Fatal> BaseDaemon: 21.3. inlined from ./contrib/llvm-project/libcxx/include/tuple:538: ~tuple
2024.01.22 15:22:55.144481 [ 1226 ] {} <Fatal> BaseDaemon: 21.4. inlined from ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48: std::default_delete<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>::operator()[abi:v15000](std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>*) const
2024.01.22 15:22:55.144574 [ 1226 ] {} <Fatal> BaseDaemon: 21.5. inlined from ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:305: std::unique_ptr<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>, std::default_delete<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>>::reset[abi:v15000](std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>*)
2024.01.22 15:22:55.144633 [ 1226 ] {} <Fatal> BaseDaemon: 21.6. inlined from ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
2024.01.22 15:22:55.144680 [ 1226 ] {} <Fatal> BaseDaemon: 21. ./contrib/llvm-project/libcxx/include/thread:297: void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000f7c00d2 in /workspace/clickhouse
2024.01.22 15:22:59.523119 [ 1226 ] {} <Fatal> BaseDaemon: 22. ? @ 0x00000000073315cf in /workspace/clickhouse
2024.01.22 15:22:59.523282 [ 1226 ] {} <Fatal> BaseDaemon: 23. ? @ 0x00007f5c6d9afac3
2024.01.22 15:22:59.523343 [ 1226 ] {} <Fatal> BaseDaemon: 24. ? @ 0x00007f5c6da41660
2024.01.22 15:22:59.523394 [ 1226 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
2024.01.22 15:23:18.906118 [ 1226 ] {} <Fatal> BaseDaemon: This ClickHouse version is not official and should be upgraded to the official build.
2024.01.22 15:23:18.906598 [ 1226 ] {} <Fatal> BaseDaemon: Changed settings: receive_timeout = 10., receive_data_timeout_ms = 10000, allow_suspicious_low_cardinality_types = true, log_queries = true, table_function_remote_max_addresses = 200, max_execution_time = 10., max_memory_usage = 10000000000, log_comment = '/workspace/ch/tests/queries/0_stateless/02962_analyzer_resolve_group_by_on_shards.sql', allow_introspection_functions = true, allow_deprecated_syntax_for_merge_tree = true
2024.01.22 15:23:29.213773 [ 171 ] {} <Fatal> Application: Child process was terminated by signal 11.
```

**Comment by Algunenano** [comment]
Reproducer in master:

```
SELECT toDate(topK('102.4'), NULL, NULL)
FROM remote('127.0.0.{1,2}', view(
    SELECT NULL
    FROM system.one
    WHERE toDate(NULL, 1025)
))
```


```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x000077f06bdd18a3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x000077f06bd81668 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x000077f06bd694b8 in __GI_abort () at abort.c:79
#4  0x0000000029781d12 in std::__1::__libcpp_verbose_abort (format=warning: (Error: pc 0x1b7553e in address map, but not in symtab.)
0x1b7553e "%s:%d: assertion %s failed: %s") at /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/src/verbose_abort.cpp:74
#5  0x0000000017e84cba in std::__1::vector<std::__1::unique_ptr<DB::SpaceSaving<StringRef, StringRefHash>::Counter, std::__1::default_delete<DB::SpaceSaving<StringRef, StringRefHash>::Counter> >, AllocatorWithMemoryTracking<std::__1::unique_ptr<DB::SpaceSaving<StringRef, StringRefHash>::Counter, std::__1::default_delete<DB::SpaceSaving<StringRef, StringRefHash>::Counter> > > >::back[abi:v15000]() const (this=0x77ed73c72240) at /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/vector:570
#6  0x0000000017e84700 in DB::SpaceSaving<StringRef, StringRefHash>::merge (this=0x77ed95b51000, rhs=...) at /mnt/ch/ClickHouse/src/Common/SpaceSaving.h:219
#7  0x0000000017d83cb8 in DB::(anonymous namespace)::AggregateFunctionTopKGeneric<true, false>::merge (this=0x77ed6c6f5910, place=0x77ed95b51000 "", rhs=0x77ed73c72000 "") at /mnt/ch/ClickHouse/src/AggregateFunctions/AggregateFunctionTopK.cpp:241
#8  0x000000001d5fab54 in DB::Aggregator::mergeWithoutKeyStreamsImpl (this=0x77eef1943a90, result=..., row_begin=0, row_end=1, aggregate_columns_data=...) at /mnt/ch/ClickHouse/src/Interpreters/Aggregator.cpp:3084
#9  0x000000001d604b6f in DB::Aggregator::mergeBlockWithoutKeyStreamsImpl (this=0x77eef1943a90, block=..., result=...) at /mnt/ch/ClickHouse/src/Interpreters/Aggregator.cpp:3048
#10 0x000000001d60ec67 in DB::Aggregator::mergeBlocks (this=0x77eef1943a90, blocks=..., final=true) at /mnt/ch/ClickHouse/src/Interpreters/Aggregator.cpp:3352
#11 0x00000000209f3eae in DB::MergingAggregatedBucketTransform::transform (this=0x77eef19f9318, chunk=...) at /mnt/ch/ClickHouse/src/Processors/Transforms/MergingAggregatedMemoryEfficientTransform.cpp:366
#12 0x000000001854dee2 in DB::ISimpleTransform::transform (this=0x77eef19f9318, input_chunk=..., output_chunk=...) at /mnt/ch/ClickHouse/src/Processors/ISimpleTransform.h:32
#13 0x00000000203b35a9 in DB::ISimpleTransform::work (this=0x77eef19f9318) at /mnt/ch/ClickHouse/src/Processors/ISimpleTransform.cpp:89
#14 0x00000000203f6970 in DB::executeJob (node=0x77ed80cfbc00, read_progress_callback=0x77ed6c712580) at /mnt/ch/ClickHouse/src/Processors/Executors/ExecutionThreadContext.cpp:47
#15 0x00000000203f6641 in DB::ExecutionThreadContext::executeTask (this=0x77ee73b1f100) at /mnt/ch/ClickHouse/src/Processors/Executors/ExecutionThreadContext.cpp:95
#16 0x00000000203d7efe in DB::PipelineExecutor::executeStepImpl (this=0x77eef19f94d8, thread_num=3, yield_flag=0x0) at /mnt/ch/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:273
#17 0x00000000203d8324 in DB::PipelineExecutor::executeSingleThread (this=0x77eef19f94d8, thread_num=3) at /mnt/ch/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:239
```

Reproduces:
* 23.12: Yes
* 23.11: Yes
* 23.10.1.1976: Yes
* 23.9.1.1854: No
* 23.8.3.48: No
