### ISSUE TITLE
Segfault getProfileEvents

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#59719]
https://s3.amazonaws.com/clickhouse-test-reports/51243/258af12b822d102dabe98fbe55477193ef38f8f1/stateless_tests__debug__[5_5].html
```
2024.02.07 08:09:42.775396 [ 6976 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2024.02.07 08:09:42.775634 [ 6976 ] {} <Fatal> BaseDaemon: (version 24.2.1.1, build id: E90F52B2D3B8823F48C75FB3CDAF817EAC3D981E, git hash: 3d51c4ba923fa179adf2d7a25421941300247631) (from thread 5821) Received signal 11
2024.02.07 08:09:42.775748 [ 6976 ] {} <Fatal> BaseDaemon: Signal description: Segmentation fault
2024.02.07 08:09:42.775846 [ 6976 ] {} <Fatal> BaseDaemon: Address: 0x68. Access: read. Address not mapped to object.
2024.02.07 08:09:42.775998 [ 6976 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000000013a1e703 0x0000000013a1d1fb 0x0000000013a1df17 0x000000001c66e13c 0x000000001e1af54e 0x000000001e1aadd4 0x000000001e1aa902 0x000000001e1a0f99 0x000000001e1b5c05 0x000000002361c2b9 0x000000002361cb1c 0x00000000237f3a34 0x00000000237f07da 0x00000000237ef51e 0x00007f9e82efdac3 0x00007f9e82f8ea04
2024.02.07 08:09:42.776112 [ 6976 ] {} <Fatal> BaseDaemon: ########################################
2024.02.07 08:09:42.776202 [ 6976 ] {} <Fatal> BaseDaemon: (version 24.2.1.1, build id: E90F52B2D3B8823F48C75FB3CDAF817EAC3D981E, git hash: 3d51c4ba923fa179adf2d7a25421941300247631) (from thread 5821) (no query) Received signal Segmentation fault (11)
2024.02.07 08:09:42.776305 [ 6976 ] {} <Fatal> BaseDaemon: Address: 0x68. Access: read. Address not mapped to object.
2024.02.07 08:09:42.776390 [ 6976 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000000013a1e703 0x0000000013a1d1fb 0x0000000013a1df17 0x000000001c66e13c 0x000000001e1af54e 0x000000001e1aadd4 0x000000001e1aa902 0x000000001e1a0f99 0x000000001e1b5c05 0x000000002361c2b9 0x000000002361cb1c 0x00000000237f3a34 0x00000000237f07da 0x00000000237ef51e 0x00007f9e82efdac3 0x00007f9e82f8ea04
2024.02.07 08:15:10.274204 [ 6976 ] {} <Fatal> BaseDaemon: 4. /build/contrib/llvm-project/libcxx/include/atomic:958: long std::__cxx_atomic_load[abi:v15000]<long>(std::__cxx_atomic_base_impl<long> const*, std::memory_order) @ 0x0000000013a1e703 in /usr/bin/clickhouse
2024.02.07 08:15:10.369284 [ 6976 ] {} <Fatal> BaseDaemon: 5. /build/contrib/llvm-project/libcxx/include/atomic:1588: std::__atomic_base<long, false>::load[abi:v15000](std::memory_order) const @ 0x0000000013a1d1fb in /usr/bin/clickhouse
2024.02.07 08:15:10.427692 [ 6976 ] {} <Fatal> BaseDaemon: 6. /build/src/Common/MemoryTracker.h:122: MemoryTracker::get() const @ 0x0000000013a1df17 in /usr/bin/clickhouse
2024.02.07 08:15:10.529548 [ 6976 ] {} <Fatal> BaseDaemon: 7. /build/src/Interpreters/ProfileEventsExt.cpp:130: ProfileEvents::getProfileEvents(String const&, std::shared_ptr<ConcurrentBoundedQueue<DB::Block>>, DB::Block&, std::unordered_map<unsigned long, ProfileEvents::Counters::Snapshot, std::hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<std::pair<unsigned long const, ProfileEvents::Counters::Snapshot>>>&) @ 0x000000001c66e13c in /usr/bin/clickhouse
2024.02.07 08:15:10.806986 [ 6976 ] {} <Fatal> BaseDaemon: 8. /build/src/Server/TCPHandler.cpp:1222: DB::TCPHandler::sendProfileEvents() @ 0x000000001e1af54e in /usr/bin/clickhouse
2024.02.07 08:15:11.078017 [ 6976 ] {} <Fatal> BaseDaemon: 9. /build/src/Server/TCPHandler.cpp:1241: DB::TCPHandler::sendSelectProfileEvents() @ 0x000000001e1aadd4 in /usr/bin/clickhouse
2024.02.07 08:15:11.362704 [ 6976 ] {} <Fatal> BaseDaemon: 10. /build/src/Server/TCPHandler.cpp:1033: DB::TCPHandler::processOrdinaryQueryWithProcessors() @ 0x000000001e1aa902 in /usr/bin/clickhouse
2024.02.07 08:15:11.615015 [ 6976 ] {} <Fatal> BaseDaemon: 11. /build/src/Server/TCPHandler.cpp:542: DB::TCPHandler::runImpl() @ 0x000000001e1a0f99 in /usr/bin/clickhouse
2024.02.07 08:15:11.888492 [ 6976 ] {} <Fatal> BaseDaemon: 12. /build/src/Server/TCPHandler.cpp:2314: DB::TCPHandler::run() @ 0x000000001e1b5c05 in /usr/bin/clickhouse
2024.02.07 08:15:11.904938 [ 6976 ] {} <Fatal> BaseDaemon: 13. /build/base/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x000000002361c2b9 in /usr/bin/clickhouse
2024.02.07 08:15:11.927665 [ 6976 ] {} <Fatal> BaseDaemon: 14. /build/base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x000000002361cb1c in /usr/bin/clickhouse
2024.02.07 08:15:11.951578 [ 6976 ] {} <Fatal> BaseDaemon: 15. /build/base/poco/Foundation/src/ThreadPool.cpp:188: Poco::PooledThread::run() @ 0x00000000237f3a34 in /usr/bin/clickhouse
2024.02.07 08:15:11.974904 [ 6976 ] {} <Fatal> BaseDaemon: 16. /build/base/poco/Foundation/src/Thread.cpp:46: Poco::(anonymous namespace)::RunnableHolder::run() @ 0x00000000237f07da in /usr/bin/clickhouse
2024.02.07 08:15:11.996497 [ 6976 ] {} <Fatal> BaseDaemon: 17. /build/base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x00000000237ef51e in /usr/bin/clickhouse
2024.02.07 08:15:11.996612 [ 6976 ] {} <Fatal> BaseDaemon: 18. ? @ 0x00007f9e82efdac3
2024.02.07 08:15:11.996675 [ 6976 ] {} <Fatal> BaseDaemon: 19. ? @ 0x00007f9e82f8ea04
2024.02.07 08:15:11.996745 [ 6976 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
2024.02.07 08:15:13.675522 [ 6976 ] {} <Fatal> BaseDaemon: This ClickHouse version is not official and should be upgraded to the official build.
2024.02.07 08:15:17.328322 [ 748 ] {} <Fatal> Application: Child process was terminated by signal 11.
```

```
2024-02-07 07:58:42 Thread 1061 "TCPHandler" received signal SIGSEGV, Segmentation fault.
2024-02-07 07:58:42 [Switching to Thread 0x7f9ac515f640 (LWP 5821)]
2024-02-07 07:58:42 0x0000000013a1e703 in std::__1::__cxx_atomic_load[abi:v15000]<long>(std::__1::__cxx_atomic_base_impl<long> const*, std::__1::memory_order) (__a=0x68, __order=std::__1::memory_order::relaxed) at /build/contrib/llvm-project/libcxx/include/atomic:958
2024-02-07 07:58:42 #0  0x0000000013a1e703 in std::__1::__cxx_atomic_load[abi:v15000]<long>(std::__1::__cxx_atomic_base_impl<long> const*, std::__1::memory_order) (__a=0x68, __order=std::__1::memory_order::relaxed) at /build/contrib/llvm-project/libcxx/include/atomic:958
2024-02-07 07:58:42 No locals.
2024-02-07 07:58:42 #1  0x0000000013a1d1fb in std::__1::__atomic_base<long, false>::load[abi:v15000](std::__1::memory_order) const (this=0x68, __m=std::__1::memory_order::relaxed) at /build/contrib/llvm-project/libcxx/include/atomic:1588
2024-02-07 07:58:43 No locals.
2024-02-07 07:58:43 #2  0x0000000013a1df17 in MemoryTracker::get (this=0x68) at /build/src/Common/MemoryTracker.h:122
2024-02-07 07:58:43 No locals.
2024-02-07 07:58:43 #3  0x000000001c66e13c in ProfileEvents::getProfileEvents (host_name=..., profile_queue=..., block=..., last_sent_snapshots=...) at /build/src/Interpreters/ProfileEventsExt.cpp:130
2024-02-07 07:58:44         group_counters = {counters_holder = {__ptr_ = {<std::__1::__compressed_pair_elem<unsigned long*, 0, false>> = {__value_ = 0x7fff36dedc90 <clock_gettime>}, <std::__1::__compressed_pair_elem<std::__1::default_delete<unsigned long []>, 1, true>> = {<std::__1::default_delete<unsigned long []>> = {<No data fields>}, <No data fields>}, <No data fields>}}}
2024-02-07 07:58:44         prev_group_snapshot = {__i_ = {__node_ = 0x7f9bf25a4cf0}}
2024-02-07 07:58:44         column_names_and_types = {<std::__1::list<DB::NameAndTypePair, std::__1::allocator<DB::NameAndTypePair> >> = {<std::__1::__list_imp<DB::NameAndTypePair, std::__1::allocator<DB::NameAndTypePair> >> = {__end_ = {__prev_ = 0x7f9d49fb56c0, __next_ = 0x7f9d49fb5660}, __size_alloc_ = {<std::__1::__compressed_pair_elem<unsigned long, 0, false>> = {__value_ = 6}, <std::__1::__compressed_pair_elem<std::__1::allocator<std::__1::__list_node<DB::NameAndTypePair, void*> >, 1, true>> = {<std::__1::allocator<std::__1::__list_node<DB::NameAndTypePair, void*> >> = {<std::__1::__non_trivial_if<true, std::__1::allocator<std::__1::__list_node<DB::NameAndTypePair, void*> > >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}, <No data fields>}, <No data fields>}
2024-02-07 07:58:44         temp_columns = {__begin_ = 0x0, __end_ = 0x0, __end_cap_ = {<std::__1::__compressed_pair_elem<DB::ColumnWithTypeAndName*, 0, false>> = {__value_ = 0x0}, <std::__1::__compressed_pair_elem<std::__1::allocator<DB::ColumnWithTypeAndName>, 1, true>> = {<std::__1::allocator<DB::ColumnWithTypeAndName>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<DB::ColumnWithTypeAndName> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}
2024-02-07 07:58:44         columns = {__begin_ = 0x7f9bcb083ac0, __end_ = 0x7f9bcb083af0, __end_cap_ = {<std::__1::__compressed_pair_elem<COW<DB::IColumn>::mutable_ptr<DB::IColumn>*, 0, false>> = {__value_ = 0x7f9bcb083af0}, <std::__1::__compressed_pair_elem<std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> >, 1, true>> = {<std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> >> = {<std::__1::__non_trivial_if<true, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}
2024-02-07 07:58:44         thread_group = {__ptr_ = 0x0, __cntrl_ = 0x0}
2024-02-07 07:58:44         new_snapshots = {__table_ = {__bucket_list_ = {__ptr_ = {<std::__1::__compressed_pair_elem<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long, ProfileEvents::Counters::Snapshot>, void*>*>**, 0, false>> = {__value_ = 0x0}, <std::__1::__compressed_pair_elem<std::__1::__bucket_list_deallocator<std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long, ProfileEvents::Counters::Snapshot>, void*>*>*> >, 1, false>> = {__value_ = {__data_ = {<std::__1::__compressed_pair_elem<unsigned long, 0, false>> = {__value_ = 0}, <std::__1::__compressed_pair_elem<std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long, ProfileEvents::Counters::Snapshot>, void*>*>*>, 1, true>> = {<std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long, ProfileEvents::Counters::Snapshot>, void*>*>*>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long, ProfileEvents::Counters::Snapshot>, void*>*>*> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}}, <No data fields>}}, __p1_ = {<std::__1::__compressed_pair_elem<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long, ProfileEvents::Counters::Snapshot>, void*>*>, 0, false>> = {__value_ = {__next_ = 0x0}}, <std::__1::__compressed_pair_elem<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long, ProfileEvents::Counters::Snapshot>, void*> >, 1, true>> = {<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long, ProfileEvents::Counters::Snapshot>, void*> >> = {<std::__1::__non_trivial_if<true, std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long, ProfileEvents::Counters::Snapshot>, void*> > >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, __p2_ = {<std::__1::__compressed_pair_elem<unsigned long, 0, false>> = {__value_ = 0}, <std::__1::__compressed_pair_elem<std::__1::__unordered_map_hasher<unsigned long, std::__1::__hash_value_type<unsigned long, ProfileEvents::Counters::Snapshot>, std::__1::hash<unsigned long>, std::__1::equal_to<unsigned long>, true>, 1, true>> = {<std::__1::__unordered_map_hasher<unsigned long, std::__1::__hash_value_type<unsigned long, ProfileEvents::Counters::Snapshot>, std::__1::hash<unsigned long>, std::__1::equal_to<unsigned long>, true>> = {<std::__1::hash<unsigned long>> = {<std::__1::__unary_function_keep_layout_base<unsigned long, unsigned long>> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, __p3_ = {<std::__1::__compressed_pair_elem<float, 0, false>> = {__value_ = 1}, <std::__1::__compressed_pair_elem<std::__1::__unordered_map_equal<unsigned long, std::__1::__hash_value_type<unsigned long, ProfileEvents::Counters::Snapshot>, std::__1::equal_to<unsigned long>, std::__1::hash<unsigned long>, true>, 1, true>> = {<std::__1::__unordered_map_equal<unsigned long, std::__1::__hash_value_type<unsigned long, ProfileEvents::Counters::Snapshot>, std::__1::equal_to<unsigned long>, std::__1::hash<unsigned long>, true>> = {<std::__1::equal_to<unsigned long>> = {<std::__1::__binary_function_keep_layout_base<unsigned long, unsigned long, bool>> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}}
2024-02-07 07:58:44         group_snapshot = {thread_id = 0, counters = {increment_holder = {__ptr_ = {<std::__1::__compressed_pair_elem<long*, 0, false>> = {__value_ = 0x0}, <std::__1::__compressed_pair_elem<std::__1::default_delete<long []>, 1, true>> = {<std::__1::default_delete<long []>> = {<No data fields>}, <No data fields>}, <No data fields>}}}, memory_usage = 4, peak_memory_usage = 190847735, current_time = 1707274722}
2024-02-07 07:58:44         curr_block = {data = {__begin_ = 0x7f9ac514c0a0, __end_ = 0x7f9e01efd7d0, __end_cap_ = {<std::__1::__compressed_pair_elem<DB::ColumnWithTypeAndName*, 0, false>> = {__value_ = 0x7f9e82f90912 <send+130>}, <std::__1::__compressed_pair_elem<std::__1::allocator<DB::ColumnWithTypeAndName>, 1, true>> = {<std::__1::allocator<DB::ColumnWithTypeAndName>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<DB::ColumnWithTypeAndName> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}, index_by_name = {__table_ = {__bucket_list_ = {__ptr_ = {<std::__1::__compressed_pair_elem<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long>, void*>*>**, 0, false>> = {__value_ = 0xd}, <std::__1::__compressed_pair_elem<std::__1::__bucket_list_deallocator<std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long>, void*>*>*> >, 1, false>> = {__value_ = {__data_ = {<std::__1::__compressed_pair_elem<unsigned long, 0, false>> = {__value_ = 140307787845440}, <std::__1::__compressed_pair_elem<std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long>, void*>*>*>, 1, true>> = {<std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long>, void*>*>*>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long>, void*>*>*> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}}, <No data fields>}}, __p1_ = {<std::__1::__compressed_pair_elem<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long>, void*>*>, 0, false>> = {__value_ = {__next_ = 0x7fff36ded84a}}, <std::__1::__compressed_pair_elem<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long>, void*> >, 1, true>> = {<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long>, void*> >> = {<std::__1::__non_trivial_if<true, std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long>, void*> > >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, __p2_ = {<std::__1::__compressed_pair_elem<unsigned long, 0, false>> = {__value_ = 140302708241984}, <std::__1::__compressed_pair_elem<std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, 1, true>> = {<std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>> = {<std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >> = {<std::__1::__unary_function_keep_layout_base<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long>> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, __p3_ = {<std::__1::__compressed_pair_elem<float, 0, false>> = {__value_ = -2399.39062}, <std::__1::__compressed_pair_elem<std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, 1, true>> = {<std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>> = {<std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >> = {<std::__1::__binary_function_keep_layout_base<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool>> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}}, info = {is_overflows = false, bucket_num = 0}}
2024-02-07 07:58:44         empty = false
2024-02-07 07:58:44 #4  0x000000001e1af54e in DB::TCPHandler::sendProfileEvents (this=0x7f9bb4073200) at /build/src/Server/TCPHandler.cpp:1222
2024-02-07 07:58:44         block = {data = {__begin_ = 0x7f9bb5d60d00, __end_ = 0x7f9bb5d60e20, __end_cap_ = {<std::__1::__compressed_pair_elem<DB::ColumnWithTypeAndName*, 0, false>> = {__value_ = 0x7f9bb5d60e80}, <std::__1::__compressed_pair_elem<std::__1::allocator<DB::ColumnWithTypeAndName>, 1, true>> = {<std::__1::allocator<DB::ColumnWithTypeAndName>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<DB::ColumnWithTypeAndName> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}, index_by_name = {__table_ = {__bucket_list_ = {__ptr_ = {<std::__1::__compressed_pair_elem<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long>, void*>*>**, 0, false>> = {__value_ = 0x7f9bb4e17ac0}, <std::__1::__compressed_pair_elem<std::__1::__bucket_list_deallocator<std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long>, void*>*>*> >, 1, false>> = {__value_ = {__data_ = {<std::__1::__compressed_pair_elem<unsigned long, 0, false>> = {__value_ = 11}, <std::__1::__compressed_pair_elem<std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long>, void*>*>*>, 1, true>> = {<std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long>, void*>*>*>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long>, void*>*>*> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}}, <No data fields>}}, __p1_ = {<std::__1::__compressed_pair_elem<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long>, void*>*>, 0, false>> = {__value_ = {__next_ = 0x7f9bcde8b3c0}}, <std::__1::__compressed_pair_elem<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long>, void*> >, 1, true>> = {<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long>, void*> >> = {<std::__1::__non_trivial_if<true, std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long>, void*> > >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, __p2_ = {<std::__1::__compressed_pair_elem<unsigned long, 0, false>> = {__value_ = 6}, <std::__1::__compressed_pair_elem<std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, 1, true>> = {<std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>> = {<std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >> = {<std::__1::__unary_function_keep_layout_base<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long>> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, __p3_ = {<std::__1::__compressed_pair_elem<float, 0, false>> = {__value_ = 1}, <std::__1::__compressed_pair_elem<std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, 1, true>> = {<std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>> = {<std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >> = {<std::__1::__binary_function_keep_layout_base<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool>> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}}, info = {is_overflows = false, bucket_num = -1}}
2024-02-07 07:58:44 #5  0x000000001e1aadd4 in DB::TCPHandler::sendSelectProfileEvents (this=0x7f9bb4073200) at /build/src/Server/TCPHandler.cpp:1240
2024-02-07 07:58:44 No locals.
2024-02-07 07:58:44 #6  0x000000001e1aa902 in DB::TCPHandler::processOrdinaryQueryWithProcessors (this=0x7f9bb4073200) at /build/src/Server/TCPHandler.cpp:1033
2024-02-07 07:58:45         lock = {__m_ = 0x7f9bb40733e8, __owns_ = true}
2024-02-07 07:58:45         cancellation_status = DB::QueryState::CancellationStatus::NOT_CANCELLED
2024-02-07 07:58:45         executor = {pipeline = @0x7f9bb4073538, lazy_format = {__ptr_ = 0x7f9bbe41a818, __cntrl_ = 0x7f9bbe41a800}, data = {__ptr_ = {<std::__1::__compressed_pair_elem<DB::PullingAsyncPipelineExecutor::Data*, 0, false>> = {__value_ = 0x7f9bb545dc00}, <std::__1::__compressed_pair_elem<std::__1::default_delete<DB::PullingAsyncPipelineExecutor::Data>, 1, true>> = {<std::__1::default_delete<DB::PullingAsyncPipelineExecutor::Data>> = {<No data fields>}, <No data fields>}, <No data fields>}}}
2024-02-07 07:58:45         query_thread_metric_increment = {what = 0x275ce638 <CurrentMetrics::values+376>, amount = 1}

```

**Comment by qoega** [comment]
I failed to find open one for some reason
