### ISSUE TITLE
server crash on excessive ) at the end of insert query

### ISSUE THREAD

**Issue by bvt123** [ClickHouse/ClickHouse#60035]
when I run the query by clickhouse-client or clickhouse-local the server is crashed:
```
create table test (a Int8) engine = MergeTree order by tuple();
INSERT INTO test
SELECT * FROM (
 SELECT number
 FROM system.numbers
 LIMIT 10
) AS x
INNER JOIN input('a Int64') AS y ON x.number = y.a
Format CSV)
```

2024.02.15 17:20:09.029175 [ 6399849 ] {} <Trace> BaseDaemon: Received signal 11
2024.02.15 17:20:09.029478 [ 6401482 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2024.02.15 17:20:09.029567 [ 6401482 ] {} <Fatal> BaseDaemon: (version 23.12.1.1339 (official build), build id: , git hash: 643dddb61986286e537360c48a4fc3ee72bcee0a) (from thread 6399850) Received signal 11
2024.02.15 17:20:09.029624 [ 6401482 ] {} <Fatal> BaseDaemon: Signal description: Segmentation fault: 11
2024.02.15 17:20:09.029668 [ 6401482 ] {} <Fatal> BaseDaemon: Address: 0xc0. Access: . Address not mapped to object.
2024.02.15 17:20:09.029688 [ 6401482 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000000107e4e2eb 0x000000010811444f 0x00007ff80581d5ed 0x0000000107ff9581 0x000000010c5d3c50 0x000000010c2ec36f 0x000000010c265c52 0x000000010c26a70f 0x000000010c2a511b 0x000000010c2a2d9f 0x000000010c2a4863 0x000000010c249747 0x000000010c5c31f6 0x000000010c5bfa93 0x000000010d2cad6a 0x000000010d2e0b5c 0x000000010edfd80c 0x000000010edfdd5e 0x000000010ee71e67 0x000000010ee6f6a0 0x00007ff8057f01d3
2

**Comment by Algunenano** [comment]
```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ffff7e35393 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007ffff7de46c8 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff7dcc4b8 in __GI_abort () at abort.c:79
#4  0x00000000263a9c61 in Poco::SignalHandler::handleSignal (sig=11) at /mnt/ch/ClickHouse/base/poco/Foundation/src/SignalHandler.cpp:94
#5  <signal handler called>
#6  0x0000000015084635 in std::__1::__bucket_list_deallocator<std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<DB::ASTSelectQuery::Expression, unsigned long>, void*>*>*> >::size[abi:v15000]() const (
    this=0xc0) at /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/__hash_table:768
#7  0x00000000150843bd in std::__1::__hash_table<std::__1::__hash_value_type<DB::ASTSelectQuery::Expression, unsigned long>, std::__1::__unordered_map_hasher<DB::ASTSelectQuery::Expression, std::__1::__hash_value_type<DB::ASTSelectQuery::Expression, unsigned long>, std::__1::hash<DB::ASTSelectQuery::Expression>, std::__1::equal_to<DB::ASTSelectQuery::Expression>, true>, std::__1::__unordered_map_equal<DB::ASTSelectQuery::Expression, std::__1::__hash_value_type<DB::ASTSelectQuery::Expression, unsigned long>, std::__1::equal_to<DB::ASTSelectQuery::Expression>, std::__1::hash<DB::ASTSelectQuery::Expression>, true>, std::__1::allocator<std::__1::__hash_value_type<DB::ASTSelectQuery::Expression, unsigned long> > >::bucket_count[abi:v15000]() const (
    this=0xb8) at /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/__hash_table:1164
#8  0x0000000015084163 in std::__1::__hash_table<std::__1::__hash_value_type<DB::ASTSelectQuery::Expression, unsigned long>, std::__1::__unordered_map_hasher<DB::ASTSelectQuery::Expression, std::__1::__hash_value_type<DB::ASTSelectQuery::Expression, unsigned long>, std::__1::hash<DB::ASTSelectQuery::Expression>, std::__1::equal_to<DB::ASTSelectQuery::Expression>, true>, std::__1::__unordered_map_equal<DB::ASTSelectQuery::Expression, std::__1::__hash_value_type<DB::ASTSelectQuery::Expression, unsigned long>, std::__1::equal_to<DB::ASTSelectQuery::Expression>, std::__1::hash<DB::ASTSelectQuery::Expression>, true>, std::__1::allocator<std::__1::__hash_value_type<DB::ASTSelectQuery::Expression, unsigned long> > >::find<DB::ASTSelectQuery::Expression> (
    this=0xb8, __k=@0x7ffffffe8d67: DB::ASTSelectQuery::Expression::SELECT) at /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/__hash_table:2334
#9  0x0000000015083f4a in std::__1::unordered_map<DB::ASTSelectQuery::Expression, unsigned long, std::__1::hash<DB::ASTSelectQuery::Expression>, std::__1::equal_to<DB::ASTSelectQuery::Expression>, std::__1::allocator<std::__1::pair<DB::ASTSelectQuery::Expression const, unsigned long> > >::find[abi:v15000](DB::ASTSelectQuery::Expression const&) const (this=0xb8, __k=@0x7ffffffe8d67: DB::ASTSelectQuery::Expression::SELECT) at /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/unordered_map:1445
#10 0x0000000015083e1e in DB::ASTSelectQuery::getExpression (this=0x0, expr=DB::ASTSelectQuery::Expression::SELECT, clone=false) at /mnt/ch/ClickHouse/src/Parsers/ASTSelectQuery.h:123
#11 0x000000001d67321c in DB::ASTSelectQuery::select (this=0x0) at /mnt/ch/ClickHouse/src/Parsers/ASTSelectQuery.h:100
#12 0x000000001d647f4b in DB::Context::executeTableFunction (this=0x7ffebe2c5000, table_expression=..., select_query_hint=0x0) at /mnt/ch/ClickHouse/src/Interpreters/Context.cpp:1788
#13 0x000000001ed00e69 in DB::getColumnsFromTableExpression (table_expression=..., context=..., materialized=..., aliases=..., virtuals=..., is_create_parameterized_view=false) at /mnt/ch/ClickHouse/src/Interpreters/getTableExpressions.cpp:96
#14 0x000000001ed00956 in DB::getDatabaseAndTablesWithColumns (table_expressions=..., context=..., include_alias_cols=false, include_materialized_cols=false, is_create_parameterized_view=false)
    at /mnt/ch/ClickHouse/src/Interpreters/getTableExpressions.cpp:135
#15 0x000000001e6c89d2 in DB::JoinedTables::resolveTables (this=0x7ffffffec498) at /mnt/ch/ClickHouse/src/Interpreters/JoinedTables.cpp:243
#16 0x000000001e4d43f2 in DB::InterpreterSelectQuery::InterpreterSelectQuery (this=0x7ffd55825800, query_ptr_=..., context_=..., input_pipe_=..., storage_=..., options_=..., required_result_column_names=..., metadata_snapshot_=..., prepared_sets_=...)
    at /mnt/ch/ClickHouse/src/Interpreters/InterpreterSelectQuery.cpp:455
#17 0x000000001e4d3251 in DB::InterpreterSelectQuery::InterpreterSelectQuery (this=0x7ffd55825800, query_ptr_=..., context_=..., options_=..., required_result_column_names_=...) at /mnt/ch/ClickHouse/src/Interpreters/InterpreterSelectQuery.cpp:210
#18 0x000000001e6915ee in std::__1::make_unique[abi:v15000]<DB::InterpreterSelectQuery, std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>&, DB::SelectQueryOptions&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&>(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>&, DB::SelectQueryOptions&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) (__args=..., __args=..., 
    __args=..., __args=...) at /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:714
#19 0x000000001e68e346 in DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter (this=0x7ffffffee158, ast_ptr_=..., current_required_result_column_names=...) at /mnt/ch/ClickHouse/src/Interpreters/InterpreterSelectWithUnionQuery.cpp:255
#20 0x000000001e68d6b2 in DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery (this=0x7ffffffee158, query_ptr_=..., context_=..., options_=..., required_result_column_names=...)
    at /mnt/ch/ClickHouse/src/Interpreters/InterpreterSelectWithUnionQuery.cpp:153
#21 0x000000001e68c1e3 in DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery (this=0x7ffffffee158, query_ptr_=..., context_=..., options_=..., required_result_column_names=...)
    at /mnt/ch/ClickHouse/src/Interpreters/InterpreterSelectWithUnionQuery.cpp:42
#22 0x000000001e4be163 in DB::InterpreterInsertQuery::execute (this=0x7ffff57dd650) at /mnt/ch/ClickHouse/src/Interpreters/InterpreterInsertQuery.cpp:493
#23 0x000000001ecda4e3 in DB::executeQueryImpl (begin=0x7ffff2e2f5e0 "INSERT INTO test\nSELECT * FROM (\n SELECT number\n FROM system.numbers\n LIMIT 10\n) AS x\nINNER JOIN input('a Int64') AS y ON x.number = y.a\nFormat CSV", end=0x7ffff2e2f673 "", 
    context=..., flags=..., stage=DB::QueryProcessingStage::Complete, istr=0x0) at /mnt/ch/ClickHouse/src/Interpreters/executeQuery.cpp:1100
#24 0x000000001ecd50fe in DB::executeQuery (query=..., context=..., flags=..., stage=DB::QueryProcessingStage::Complete) at /mnt/ch/ClickHouse/src/Interpreters/executeQuery.cpp:1279
#25 0x00000000205ba7fd in DB::LocalConnection::sendQuery(DB::ConnectionTimeouts const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, DB::Settings const*, DB::ClientInfo const*, bool, std::__1::function<void (DB::Progress const&)>) (this=0x7ffff604ae00, query=..., query_parameters=..., query_id=..., stage=2, client_info=0x7ffff5f78008, process_progress_callback=...) at /mnt/ch/ClickHouse/src/Client/LocalConnection.cpp:134
#26 0x00000000205167a9 in DB::ClientBase::processInsertQuery (this=0x7fffffffa2a0, query_to_execute=..., parsed_query=...) at /mnt/ch/ClickHouse/src/Client/ClientBase.cpp:1436
#27 0x0000000020510d95 in DB::ClientBase::processParsedSingleQuery (this=0x7fffffffa2a0, full_query=..., query_to_execute=..., parsed_query=..., echo_query_=..., report_error=false) at /mnt/ch/ClickHouse/src/Client/ClientBase.cpp:1891
#28 0x000000002050f8c3 in DB::ClientBase::processTextAsSingleQuery (this=0x7fffffffa2a0, full_query=...) at /mnt/ch/ClickHouse/src/Client/ClientBase.cpp:858
#29 0x000000002051c024 in DB::ClientBase::processQueryText (this=0x7fffffffa2a0, text=...) at /mnt/ch/ClickHouse/src/Client/ClientBase.cpp:2293
#30 0x000000002051e74c in DB::ClientBase::runInteractive (this=0x7fffffffa2a0) at /mnt/ch/ClickHouse/src/Client/ClientBase.cpp:2530
#31 0x00000000150a7472 in DB::LocalServer::main (this=0x7fffffffa2a0) at /mnt/ch/ClickHouse/programs/local/LocalServer.cpp:543
#32 0x00000000261d46d2 in Poco::Util::Application::run (this=0x7fffffffa2a0) at /mnt/ch/ClickHouse/base/poco/Util/src/Application.cpp:315
#33 0x00000000150b1420 in mainEntryClickHouseLocal (argc=1, argv=0x7ffff68011a0) at /mnt/ch/ClickHouse/programs/local/LocalServer.cpp:955
#34 0x000000000ad9e318 in main (argc_=2, argv_=0x7fffffffe238) at /mnt/ch/ClickHouse/programs/main.cpp:508
(gdb) f 12
#12 0x000000001d647f4b in DB::Context::executeTableFunction (this=0x7ffebe2c5000, table_expression=..., select_query_hint=0x0) at /mnt/ch/ClickHouse/src/Interpreters/Context.cpp:1788
1788                const auto & expression_list = select_query_hint->select()->as<ASTExpressionList>()->children;
(gdb) p select_query_hint
$1 = (const DB::ASTSelectQuery *) 0x0
```

cc @Avogar

**Comment by ilejn** [comment]
Hm ... cannot reproduce against (a week old) master

```
:) create table test (a Int8) engine = MergeTree order by tuple();
INSERT INTO test
SELECT * FROM (
 SELECT number
 FROM system.numbers
 LIMIT 10
) AS x
INNER JOIN input('a Int64') AS y ON x.number = y.a
Format Parquet);

Syntax error: failed at position 216 (')') (line 9, col 15):

create table test (a Int8) engine = MergeTree order by tuple();
INSERT INTO test
SELECT * FROM (
 SELECT number
 FROM system.numbers
 LIMIT 10
) AS x
INNER JOIN input('a Int64') AS y ON x.number = y.a
Format Parquet);

Unmatched parentheses: )
```

**Comment by Avogar** [comment]
I could reproduce, and already know what the bug is, will fix it
