### ISSUE TITLE
cross-compile for risc-v error

### ISSUE THREAD

**Issue by hurwan** [ClickHouse/ClickHouse#60381]
> Make sure that `git diff` result is empty and you've just pulled fresh master. Try cleaning up cmake cache. Just in case, official build instructions are published here: https://clickhouse.com/docs/en/development/build/

**Operating system**
```
Linux VM-16-7-ubuntu 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal
```

**Cmake version**
`cmake version 3.24.0`

**Ninja version**
`ninja --version
1.10.0`

**Compiler name and version**
```
-- Cross-compiling for target: 
-- Using compiler:
Ubuntu clang version 17.0.6 (++20231208085846+6009708b4367-1~exp1~20231208085949.74)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
-- Using linker: riscv64-linux-gnu-ld.bfd
-- Using archiver: /usr/bin/llvm-ar-17
-- Using ranlib: /usr/bin/llvm-ranlib-17
-- Using install-name-tool: /usr/bin/llvm-install-name-tool-17
-- Using objcopy: /usr/bin/llvm-objcopy-17
-- Using strip: /usr/bin/llvm-strip-17
-- Using ccache: /usr/bin/ccache (version 3.7.7)
```
cross-compile for risc-v

**Full cmake and/or ninja output**
```
git checkout master
git pull
git submodule sync
git submodule update --init --recursive
CC=clang-17 CXX=clang++-17 cmake . -Bbuild-riscv64 -G Ninja -DCMAKE_TOOLCHAIN_FILE=cmake/linux/toolchain-riscv64.cmake -DGLIBC_COMPATIBILITY=OFF -DENABLE_LDAP=OFF  -DOPENSSL_NO_ASM=ON -DENABLE_JEMALLOC=ON -DENABLE_PARQUET=OFF -DENABLE_GRPC=OFF -DENABLE_HDFS=OFF -DENABLE_MYSQL=OFF
ninja -C build-riscv64
[10096/10141] Linking CXX executable programs/odbc-bridge/tests/validate-odbc-connection-string
FAILED: programs/odbc-bridge/tests/validate-odbc-connection-string 
: && /usr/bin/clang++-17 --target=riscv64-linux-gnu --sysroot=/data/ClickHouse/cmake/linux/../../contrib/sysroot/linux-riscv64 --gcc-toolchain=/data/ClickHouse/cmake/linux/../../contrib/sysroot/linux-riscv64 -fdiagnostics-color=always -Xclang -fuse-ctor-homing -Wno-enum-constexpr-conversion -fsized-deallocation  -gdwarf-aranges -pipe -fasynchronous-unwind-tables -ffile-prefix-map=/data/ClickHouse=. -falign-functions=32  -fdiagnostics-absolute-paths -fstrict-vtable-pointers -Wall -Wextra -Wframe-larger-than=65536 -Weverything -Wpedantic -Wno-zero-length-array -Wno-c++98-compat-pedantic -Wno-c++98-compat -Wno-c++20-compat -Wno-sign-conversion -Wno-implicit-int-conversion -Wno-implicit-int-float-conversion -Wno-ctad-maybe-unsupported -Wno-disabled-macro-expansion -Wno-documentation-unknown-command -Wno-double-promotion -Wno-exit-time-destructors -Wno-float-equal -Wno-global-constructors -Wno-missing-prototypes -Wno-missing-variable-declarations -Wno-padded -Wno-switch-enum -Wno-undefined-func-template -Wno-unused-template -Wno-vla -Wno-weak-template-vtables -Wno-weak-vtables -Wno-thread-safety-negative -Wno-enum-constexpr-conversion -Wno-unsafe-buffer-usage -O2 -g -DNDEBUG -O3 -g  -fno-pie -fuse-ld=bfd --ld-path=/usr/bin/riscv64-linux-gnu-ld.bfd -Wl,--no-export-dynamic -Wl,--gc-sections -no-pie -Wl,-no-pie    -Xlinker --no-undefined src/CMakeFiles/clickhouse_malloc.dir/Common/malloc.cpp.o programs/odbc-bridge/tests/CMakeFiles/validate-odbc-connection-string.dir/validate-odbc-connection-string.cpp.o programs/odbc-bridge/tests/CMakeFiles/validate-odbc-connection-string.dir/__/validateODBCConnectionString.cpp.o -o programs/odbc-bridge/tests/validate-odbc-connection-string  src/libclickhouse_new_delete.a  src/libclickhouse_common_io.a  src/Common/StringUtils/libstring_utils.a  base/widechar_width/libwidechar_width.a  base/base/libcommon.a  base/poco/NetSSL_OpenSSL/lib_poco_net_ssl.a  base/poco/Net/lib_poco_net.a  base/poco/Crypto/lib_poco_crypto.a  base/poco/Util/lib_poco_util.a  base/poco/JSON/lib_poco_json.a  base/poco/JSON/lib_poco_json_pdjson.a  base/poco/XML/lib_poco_xml.a  base/poco/XML/lib_poco_xml_expat.a  contrib/replxx-cmake/lib_replxx.a  contrib/cctz-cmake/lib_cctz.a  contrib/cctz-cmake/libtzdata.a  contrib/fmtlib-cmake/lib_fmt.a  contrib/dragonbox-cmake/lib_dragonbox_to_chars.a  contrib/boost-cmake/lib_boost_program_options.a  contrib/boost-cmake/lib_boost_system.a  contrib/boost-cmake/lib_boost_context.a  contrib/cityhash102/lib_cityhash.a  contrib/re2-cmake/lib_re2.a  contrib/abseil-cpp-cmake/libabsl_cord.a  contrib/abseil-cpp-cmake/libabsl_cordz_info.a  contrib/abseil-cpp-cmake/libabsl_cord_internal.a  contrib/abseil-cpp-cmake/libabsl_cordz_functions.a  contrib/abseil-cpp-cmake/libabsl_cordz_handle.a  contrib/abseil-cpp-cmake/libabsl_crc_cord_state.a  contrib/abseil-cpp-cmake/libabsl_crc32c.a  contrib/abseil-cpp-cmake/libabsl_crc_internal.a  contrib/abseil-cpp-cmake/libabsl_crc_cpu_detect.a  contrib/abseil-cpp-cmake/libabsl_raw_hash_set.a  contrib/abseil-cpp-cmake/libabsl_hash.a  contrib/abseil-cpp-cmake/libabsl_city.a  contrib/abseil-cpp-cmake/libabsl_bad_variant_access.a  contrib/abseil-cpp-cmake/libabsl_low_level_hash.a  contrib/abseil-cpp-cmake/libabsl_hashtablez_sampler.a  contrib/abseil-cpp-cmake/libabsl_exponential_biased.a  contrib/abseil-cpp-cmake/libabsl_str_format_internal.a  contrib/abseil-cpp-cmake/libabsl_synchronization.a  contrib/abseil-cpp-cmake/libabsl_graphcycles_internal.a  contrib/abseil-cpp-cmake/libabsl_kernel_timeout_internal.a  contrib/abseil-cpp-cmake/libabsl_stacktrace.a  contrib/abseil-cpp-cmake/libabsl_symbolize.a  contrib/abseil-cpp-cmake/libabsl_malloc_internal.a  contrib/abseil-cpp-cmake/libabsl_debugging_internal.a  contrib/abseil-cpp-cmake/libabsl_demangle_internal.a  contrib/abseil-cpp-cmake/libabsl_time.a  contrib/abseil-cpp-cmake/libabsl_strings.a  contrib/abseil-cpp-cmake/libabsl_strings_internal.a  contrib/abseil-cpp-cmake/libabsl_string_view.a  contrib/abseil-cpp-cmake/libabsl_base.a  contrib/abseil-cpp-cmake/libabsl_spinlock_wait.a  contrib/abseil-cpp-cmake/libabsl_int128.a  contrib/abseil-cpp-cmake/libabsl_civil_time.a  contrib/abseil-cpp-cmake/libabsl_time_zone.a  contrib/abseil-cpp-cmake/libabsl_bad_optional_access.a  contrib/abseil-cpp-cmake/libabsl_throw_delegate.a  contrib/abseil-cpp-cmake/libabsl_raw_logging_internal.a  contrib/abseil-cpp-cmake/libabsl_log_severity.a  base/poco/Foundation/lib_poco_foundation.a  contrib/double-conversion-cmake/lib_double-conversion.a  base/poco/Foundation/lib_poco_foundation_pcre.a  contrib/libfiu-cmake/lib_fiu.a  contrib/libssh-cmake/lib_ssh.a  contrib/aws-cmake/lib_aws.a  contrib/azure-cmake/lib_azure_sdk.a  contrib/curl-cmake/lib_curl.a  contrib/c-ares-cmake/lib_c-ares.a  contrib/libxml2-cmake/lib_libxml2.a  contrib/brotli-cmake/lib_brotli.a  contrib/snappy-cmake/lib_snappy.a  contrib/libbcrypt-cmake/lib_bcrypt.a  contrib/liburing-cmake/lib_liburing.a  contrib/lz4-cmake/lib_lz4.a  contrib/libarchive-cmake/lib_libarchive.a  contrib/minizip-ng-cmake/lib_minizip.a  contrib/zlib-ng-cmake/lib_zlib.a  contrib/zstd-cmake/lib_zstd.a  contrib/xz-cmake/lib_liblzma.a  contrib/bzip2-cmake/lib_bzip2.a  contrib/boringssl-cmake/lib_ssl.a  contrib/boringssl-cmake/lib_crypto.a  -lpthread  contrib/jemalloc-cmake/lib_jemalloc.a  contrib/gwpasan-cmake/lib_gwp_asan.a  -Wl,--start-group  contrib/libcxx-cmake/libcxx.a  contrib/libcxxabi-cmake/libcxxabi.a  contrib/libunwind-cmake/libunwind.a  -Wl,--end-group  -nodefaultlibs -lgcc  -lc -lm -lrt -lpthread -ldl && :
/usr/bin/riscv64-linux-gnu-ld.bfd: /data/ClickHouse/cmake/linux/../../contrib/sysroot/linux-riscv64/lib/riscv64-linux-gnu/librt.a(timer_create.o): undefined reference to symbol '__stack_chk_guard@@GLIBC_2.27'
/usr/bin/riscv64-linux-gnu-ld.bfd: /data/ClickHouse/cmake/linux/../../contrib/sysroot/linux-riscv64/lib/riscv64-linux-gnu/./ld-linux-riscv64-lp64d.so.1: error adding symbols: DSO missing from command line
clang++-17: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by alexey-milovidov** [comment]
Compile exactly as in the build logs: https://s3.amazonaws.com/clickhouse-test-reports/0/30d31d4d9bfd740f4a7935702f2761ad8134207b/clickhouse_special_build_check/report.html

Or download a pre-built binary.

**Comment by alexey-milovidov** [comment]
Here is the build log for RISC-V: https://s3.amazonaws.com/clickhouse-builds/24.2/30d31d4d9bfd740f4a7935702f2761ad8134207b/binary_riscv64/build_log.log

**Comment by hurwan** [comment]
tried with
`./docker/packager/packager --package-type=binary --output-dir "/data/build_riscv" --compiler "clang-17-riscv64"`

get error
```
Feb 26 17:19:34 [7109/9822] Building CXX object src/CMakeFiles/clickhouse_compression.dir/Core/Settings.cpp.o
Feb 26 17:19:34 FAILED: src/CMakeFiles/clickhouse_compression.dir/Core/Settings.cpp.o
Feb 26 17:19:34 prlimit --as=10000000000 --data=5000000000 --cpu=1000 /usr/bin/clang++-17 --target=riscv64-linux-gnu --sysroot=/build/cmake/linux/../../contrib/sysroot/linux-riscv64 -DBOOST_ASIO_HAS_STD_INVOKE_RESULT=1 -DBOOST_ASIO_STANDALONE=1 -DBOOST_TIMER_ENABLE_DEPRECATED=1 -DDUMMY_BACKTRACE -DENABLE_MULTITARGET_CODE=1 -DHAVE_BZLIB_H=1 -DHAVE_CONFIG_H -DHAVE_FUTIMESAT=1 -DHAVE_ICONV=1 -DHAVE_LIBLZMA=1 -DHAVE_LIBZSTD=1 -DHAVE_LINUX_FS_H=1 -DHAVE_LINUX_TYPES_H=1 -DHAVE_LZMA_H=1 -DHAVE_STRUCT_STAT_ST_MTIM_TV_NSEC=1 -DHAVE_SYS_STATFS_H=1 -DHAVE_ZLIB_H=1 -DHAVE_ZSTD_H=1 -DINCBIN_SILENCE_BITCODE_WARNING -DLZ4_DISABLE_DEPRECATE_WARNINGS=1 -DLZ4_FAST_DEC_LOOP=1 -DMAJOR_IN_SYSMACROS=1 -DPOCO_ENABLE_CPP11 -DPOCO_HAVE_FD_EPOLL -DPOCO_OS_FAMILY_UNIX -DSTD_EXCEPTION_HAS_STACK_TRACE=1 -DWITH_COVERAGE=0 -DWITH_GZFILEOP -DZLIB_COMPAT -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -I/build/build_docker/includes/configs -I/build/base/pcg-random/. -I/build/src -I/build/build_docker/src -I/build/build_docker/src/Core/include -I/build/base/base/.. -I/build/build_docker/base/base/.. -I/build/contrib/cctz/include -I/build/contrib/re2 -I/build/contrib/libfiu/libfiu -I/build/contrib/libssh/include -I/build/build_docker/contrib/libssh/include -I/build/contrib/miniselect/include -I/build/contrib/zstd/lib -I/build/contrib/pocketfft -I/build/contrib/libarchive-cmake -I/build/contrib/libarchive/libarchive -I/build/contrib/lz4/lib -isystem /build/contrib/llvm-project/libcxx/include -isystem /build/contrib/llvm-project/libcxxabi/include -isystem /build/contrib/libunwind/include -isystem /build/contrib/llvm-project/llvm/include -isystem /build/build_docker/contrib/llvm-project/llvm/include -isystem /build/contrib/sparsehash-c11 -isystem /build/contrib/incbin -isystem /build/contrib/cityhash102/include -isystem /build/contrib/boost -isystem /build/base/poco/Net/include -isystem /build/base/poco/Foundation/include -isystem /build/base/poco/NetSSL_OpenSSL/include -isystem /build/base/poco/Crypto/include -isystem /build/contrib/boringssl/include -isystem /build/base/poco/Util/include -isystem /build/base/poco/JSON/include -isystem /build/base/poco/XML/include -isystem /build/contrib/replxx/include -isystem /build/contrib/fmtlib-cmake/../fmtlib/include -isystem /build/contrib/magic_enum/include -isystem /build/contrib/double-conversion -isystem /build/contrib/dragonbox/include -isystem /build/contrib/libdivide-cmake/. -isystem /build/contrib/libdivide -isystem /build/contrib/zlib-ng -isystem /build/build_docker/contrib/zlib-ng-cmake -isystem /build/contrib/abseil-cpp -isystem /build/contrib/pdqsort -isystem /build/contrib/xz/src/liblzma/api -isystem /build/contrib/aws/src/aws-cpp-sdk-core/include -isystem /build/build_docker/contrib/aws-cmake/include -isystem /build/contrib/aws/generated/src/aws-cpp-sdk-s3/include -isystem /build/contrib/aws-c-auth/include -isystem /build/contrib/aws-c-common/include -isystem /build/contrib/aws-c-io/include -isystem /build/contrib/aws-crt-cpp/include -isystem /build/contrib/aws-c-mqtt/include -isystem /build/contrib/aws-c-sdkutils/include -isystem /build/contrib/azure/sdk/core/azure-core/inc -isystem /build/contrib/azure/sdk/identity/azure-identity/inc -isystem /build/contrib/azure/sdk/storage/azure-storage-common/inc -isystem /build/contrib/azure/sdk/storage/azure-storage-blobs/inc -isystem /build/contrib/snappy -isystem /build/build_docker/contrib/snappy-cmake -isystem /build/contrib/libbcrypt -isystem /build/contrib/msgpack-c/include -isystem /build/build_docker/contrib/liburing/src/include-compat -isystem /build/build_docker/contrib/liburing/src/include -isystem /build/contrib/liburing/src/include -isystem /build/contrib/fast_float/include -isystem /build/contrib/croaring/cpp -isystem /build/contrib/croaring/include -isystem /build/contrib/krb5/src/include -isystem /build/build_docker/contrib/krb5-cmake/include -isystem /build/contrib/NuRaft/include --gcc-toolchain=/build/cmake/linux/../../contrib/sysroot/linux-riscv64 -fdiagnostics-color=always -Xclang -fuse-ctor-homing -Wno-enum-constexpr-conversion -fsized-deallocation  -gdwarf-aranges -pipe -fasynchronous-unwind-tables -ffile-prefix-map=/build=. -falign-functions=32  -fdiagnostics-absolute-paths -fstrict-vtable-pointers -Wall -Wextra -Wframe-larger-than=65536 -Weverything -Wpedantic -Wno-zero-length-array -Wno-c++98-compat-pedantic -Wno-c++98-compat -Wno-c++20-compat -Wno-sign-conversion -Wno-implicit-int-conversion -Wno-implicit-int-float-conversion -Wno-ctad-maybe-unsupported -Wno-disabled-macro-expansion -Wno-documentation-unknown-command -Wno-double-promotion -Wno-exit-time-destructors -Wno-float-equal -Wno-global-constructors -Wno-missing-prototypes -Wno-missing-variable-declarations -Wno-padded -Wno-switch-enum -Wno-undefined-func-template -Wno-unused-template -Wno-vla -Wno-weak-template-vtables -Wno-weak-vtables -Wno-thread-safety-negative -Wno-enum-constexpr-conversion -Wno-unsafe-buffer-usage -O2 -g -DNDEBUG -O3 -g  -fno-pie -std=c++23   -D OS_LINUX -Werror -nostdinc++ -MD -MT src/CMakeFiles/clickhouse_compression.dir/Core/Settings.cpp.o -MF src/CMakeFiles/clickhouse_compression.dir/Core/Settings.cpp.o.d -o src/CMakeFiles/clickhouse_compression.dir/Core/Settings.cpp.o -c /build/src/Core/Settings.cpp
Feb 26 17:19:34 Killed
```

error message
```
Feb 26 17:19:47 ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "./docker/packager/packager", line 554, in <module>
    main()
  File "./docker/packager/packager", line 541, in main
    run_docker_image_with_env(
  File "./docker/packager/packager", line 115, in run_docker_image_with_env
    subprocess.check_call(cmd, shell=True)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'docker run --network=host --user=0:0 --rm  --volume=/data/build_riscv:/output --volume=/data/ClickHouse:/build  -e OUTPUT_DIR=/output -e CC=clang-17 -e CXX=clang++-17 -e BUILD_TYPE=None -e CMAKE_FLAGS="$CMAKE_FLAGS -DCMAKE_TOOLCHAIN_FILE=/build/cmake/linux/toolchain-riscv64.cmake -DCMAKE_C_COMPILER=clang-17 -DCMAKE_CXX_COMPILER=clang++-17 -DCOMPILER_CACHE=disabled" -e BUILD_TARGET='clickhouse-bundle' --volume=/root/.cargo/registry:/rust/cargo/registry  clickhouse/binary-builder:latest' returned non-zero exit status 1.
```

can get a correct command?

**Comment by alexey-milovidov** [comment]
You might want to remove `prlimit --as=10000000000 --data=5000000000 --cpu=1000` from compiler invocation.

**Comment by alexey-milovidov** [comment]
But we already built ClickHouse, so you don't have to compile on your own. Just download a pre-build binary.

**Comment by hurwan** [comment]
But the release not include package for risc-v64.
`https://github.com/ClickHouse/ClickHouse/releases`
