### ISSUE TITLE
Strange deadlock in `sanitizerDeathCallback`

### ISSUE THREAD

**Issue by antaljanosbenjamin** [ClickHouse/ClickHouse#60405]
[CI DB link](https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHB1bGxfcmVxdWVzdF9udW1iZXIsIGdyb3VwQXJyYXkodGVzdF9uYW1lKSBhcyBmYWlsZWRfdGVzdF9uYW1lcywgY2hlY2tfc3RhdHVzLCByZXBvcnRfdXJsCkZST00gY2hlY2tzCldIRVJFIDEKICAgIC0tIEFORCBjaGVja19zdGFydF90aW1lID4gdG9kYXkoKSAtIElOVEVSVkFMIDEwIERBWVMKICAgIC0tIEFORCBwdWxsX3JlcXVlc3RfbnVtYmVyICE9IDAKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnU0tJUFBFRCcKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnT0snCiAgICBBTkQgY2hlY2tfc3RhdHVzICE9ICdzdWNjZXNzJwogICAgQU5EIChjaGVja19uYW1lIExJS0UgJyVVcGdyYWRlIGNoZWNrJScgT1IgY2hlY2tfbmFtZSBMSUtFICclU3RyZXNzIHRlc3QlJykKICAgIC0tIEFORCB0ZXN0X25hbWUgaWxpa2UgJyVQb3NzaWJsZSBkZWFkbG9jayBvbiBzaHV0ZG93biAoc2VlIGdkYi5sb2cpJScKR1JPVVAgQlkgY2hlY2tfc3RhcnRfdGltZSwgY2hlY2tfbmFtZSwgcHVsbF9yZXF1ZXN0X251bWJlciwgY2hlY2tfc3RhdHVzLCByZXBvcnRfdXJsCkhBVklORyBmYWlsZWRfdGVzdF9uYW1lcyA9IFsnJywnUG9zc2libGUgZGVhZGxvY2sgb24gc2h1dGRvd24gKHNlZSBnZGIubG9nKSddIE9SIGZhaWxlZF90ZXN0X25hbWVzID0gWydQb3NzaWJsZSBkZWFkbG9jayBvbiBzaHV0ZG93biAoc2VlIGdkYi5sb2cpJywnJ10KT1JERVIgQlkgY2hlY2tfc3RhcnRfdGltZSBkZXNjLCBjaGVja19uYW1l).

**Describe the bug**
Sometimes upgrade checks/stress tests fails with "possible deadlock on stop". The backtrace dump in gdb only shows a single thread in `sanitizerDeathCallback` in a sleep:
```
thread apply all backtrace (on stop)
2024-02-21 16:17:36 [Thread debugging using libthread_db enabled]
2024-02-21 16:17:36 Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
2024-02-21 16:17:36 __syscall () at ./build_docker/./base/glibc-compatibility/musl/x86_64/syscall.s:14
2024-02-21 16:17:36 
2024-02-21 16:17:36 Thread 1 (Thread 0x7f4e268ec300 (LWP 740674) "clickhouse-serv"):
2024-02-21 16:17:36 #0  __syscall () at ./build_docker/./base/glibc-compatibility/musl/x86_64/syscall.s:14
2024-02-21 16:17:36 #1  0x000055b348887a48 in clock_nanosleep (clk=<optimized out>, flags=<optimized out>, req=<optimized out>, rem=<optimized out>) at ./build_docker/./base/glibc-compatibility/musl/clock_nanosleep.c:21
2024-02-21 16:17:36 #2  0x000055b341fadf44 in sleepForNanoseconds (nanoseconds=<optimized out>) at ./build_docker/./base/base/sleep.cpp:48
2024-02-21 16:17:36 #3  sleepForMicroseconds (microseconds=<optimized out>) at ./build_docker/./base/base/sleep.cpp:54
2024-02-21 16:17:36 #4  sleepForMilliseconds (milliseconds=<optimized out>) at ./build_docker/./base/base/sleep.cpp:59
2024-02-21 16:17:36 #5  sleepForSeconds (seconds=20) at ./build_docker/./base/base/sleep.cpp:64
2024-02-21 16:17:36 #6  0x000055b323f93f63 in sanitizerDeathCallback () at ./build_docker/./src/Daemon/BaseDaemon.cpp:571
2024-02-21 16:17:36 #7  0x000055b31077d506 in __sanitizer::Die() ()
2024-02-21 16:17:36 #8  0x000055b31078a1a8 in __lsan::CheckForLeaks() ()
2024-02-21 16:17:36 #9  0x000055b310789d2b in __lsan::DoLeakCheck() ()
2024-02-21 16:17:36 #10 0x00007f4e26a21a56 in __cxa_finalize () from /lib/x86_64-linux-gnu/libc.so.6
2024-02-21 16:17:36 #11 0x000055b3106c4f47 in __do_global_dtors_aux ()
2024-02-21 16:17:36 #12 0x00007ffee4113600 in ?? ()
2024-02-21 16:17:36 Backtrace stopped: previous frame identical to this frame (corrupt stack?)
2024-02-21 16:17:36 [Inferior 1 (process 740674) detached]
```

**Comment by alexey-milovidov** [comment]
That's weird, but there are no longer cases.
