### ISSUE TITLE
AddressSanitizer: heap-buffer-overflow FunctionStringHashFixedString

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#60484]
https://s3.amazonaws.com/clickhouse-test-reports/60469/ee772aaf0f7a05fafb3fa286419148211362b0d6/ast_fuzzer__asan_.html

```
    #0 0x55776b477a11 in __asan_memcpy (/workspace/clickhouse+0xa5dba11) (BuildId: 79acd9ef374d1d94b4cbab90e159a1749cc61365)
    #1 0x55779af6f1e6 in OPENSSL_memcpy build_docker/./contrib/boringssl/crypto/fipsmodule/../internal.h:824:10
    #2 0x55779af6f1e6 in crypto_md32_update build_docker/./contrib/boringssl/crypto/fipsmodule/md4/../digest/md32_common.h:143:5
    #3 0x55779af6f1e6 in MD4_Update build_docker/./contrib/boringssl/crypto/fipsmodule/md4/md4.c:93:3
    #4 0x55776d672cb2 in DB::FunctionStringHashFixedString<DB::MD4Impl>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/workspace/clickhouse+0xc7d6cb2) (BuildId: 79acd9ef374d1d94b4cbab90e159a1749cc61365)
    #5 0x55776b4c486b in DB::FunctionToExecutableFunctionAdaptor::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/workspace/clickhouse+0xa62886b) (BuildId: 79acd9ef374d1d94b4cbab90e159a1749cc61365)
    #6 0x55778823515a in DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_docker/./src/Functions/IFunction.cpp:248:15
    #7 0x557788237a70 in DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_docker/./src/Functions/IFunction.cpp:281:24
    #8 0x55778823a72a in DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_docker/./src/Functions/IFunction.cpp:378:16
    #9 0x55778acb2f51 in DB::executeAction(DB::ExpressionActions::Action const&, DB::(anonymous namespace)::ExecutionContext&, bool) build_docker/./src/Interpreters/ExpressionActions.cpp:616:60
    #10 0x55778acb2f51 in DB::ExpressionActions::execute(DB::Block&, unsigned long&, bool) const build_docker/./src/Interpreters/ExpressionActions.cpp:740:13
    #11 0x55778fd529a9 in DB::ExpressionTransform::transform(DB::Chunk&) build_docker/./src/Processors/Transforms/ExpressionTransform.cpp:23:17
    #12 0x557781411bdd in DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) build_docker/./src/Processors/ISimpleTransform.h:32:9
    #13 0x55778f6c2d98 in DB::ISimpleTransform::work() build_docker/./src/Processors/ISimpleTransform.cpp:89:9
    #14 0x55778f700290 in DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*) build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:47:26
    #15 0x55778f700290 in DB::ExecutionThreadContext::executeTask() build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:95:9
    #16 0x55778f6e96fc in DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) build_docker/./src/Processors/Executors/PipelineExecutor.cpp:273:26
    #17 0x55778f6e7f9b in DB::PipelineExecutor::executeSingleThread(unsigned long) build_docker/./src/Processors/Executors/PipelineExecutor.cpp:239:5
    #18 0x55778f6e7f9b in DB::PipelineExecutor::executeImpl(unsigned long, bool) build_docker/./src/Processors/Executors/PipelineExecutor.cpp:409:9
    #19 0x55778f6e7a9a in DB::PipelineExecutor::execute(unsigned long, bool) build_docker/./src/Processors/Executors/PipelineExecutor.cpp:111:9
    #20 0x55778f70916e in DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::__1::shared_ptr<DB::ThreadGroup>, unsigned long, bool) build_docker/./src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:84:24
    #21 0x55778f70916e in DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0::operator()() const build_docker/./src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:112:13
    #22 0x55778f70916e in decltype(std::declval<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>()()) std::__1::__invoke[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #23 0x55778f70916e in decltype(auto) std::__1::__apply_tuple_impl[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<...>) build_docker/./contrib/llvm-project/libcxx/include/tuple:1789:1
    #24 0x55778f70916e in decltype(auto) std::__1::apply[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&) build_docker/./contrib/llvm-project/libcxx/include/tuple:1798:1
    #25 0x55778f70916e in ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()::operator()() build_docker/./src/Common/ThreadPool.h:223:13
    #26 0x55778f70916e in decltype(std::declval<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>()()) std::__1::__invoke[abi:v15000]<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #27 0x55778f70916e in void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:479:9
    #28 0x55778f70916e in std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>::operator()[abi:v15000]() build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:235:12
    #29 0x55778f70916e in void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716:16
    #30 0x55777b5ee47b in std::__1::__function::__policy_func<void ()>::operator()[abi:v15000]() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:848:16
    #31 0x55777b5ee47b in std::__1::function<void ()>::operator()() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:1187:12
    #32 0x55777b5ee47b in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) build_docker/./src/Common/ThreadPool.cpp:455:13
    #33 0x55777b5f795e in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const build_docker/./src/Common/ThreadPool.cpp:217:73
    #34 0x55777b5f795e in decltype(std::declval<void>()()) std::__1::__invoke[abi:v15000]<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #35 0x55777b5f795e in void std::__1::__thread_execute[abi:v15000]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>&, std::__1::__tuple_indices<...>) build_docker/./contrib/llvm-project/libcxx/include/thread:284:5
    #36 0x55777b5f795e in void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) build_docker/./contrib/llvm-project/libcxx/include/thread:295:5
    #37 0x55776b477658 in asan_thread_start(void*) crtstuff.c
    #38 0x7f80afaafac2 in start_thread nptl/pthread_create.c:442:8
    #39 0x7f80afb4184f  misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

Triggered [with clang-18](https://github.com/ClickHouse/ClickHouse/pull/60469)

**Comment by Algunenano** [comment]
Please include the queries that cause issues:

```
SELECT toIPv6(materialize(_CAST('fe80::62:5aff:fed1:daf0', 'LowCardinality(String)'))) AS ipv6, halfMD5(toIPv6(materialize(_CAST('fe80::62:5aff:fed1:daf0', 'LowCardinality(String)')))) AS `halfMD5(ipv6)`, hex(MD4(toIPv6(materialize(_CAST('fe80::62:5aff:fed1:daf0', 'LowCardinality(String)'))))) AS `hex(MD4(ipv6))`, hex(MD5(toIPv6(materialize(_CAST('fe80::62:5aff:fed1:daf0', 'LowCardinality(String)'))))) AS `hex(MD5(ipv6))`, hex(SHA1(toIPv6(materialize(_CAST('fe80::62:5aff:fed1:daf0', 'LowCardinality(String)'))))) AS `hex(SHA1(ipv6))`, hex(SHA224(toIPv6(materialize(_CAST('fe80::62:5aff:fed1:daf0', 'LowCardinality(String)'))))) AS `hex(SHA224(ipv6))`, hex(SHA256(toIPv6(materialize(_CAST('fe80::62:5aff:fed1:daf0', 'LowCardinality(String)'))))) AS `hex(SHA256(ipv6))`, hex(SHA512(toIPv6(materialize(_CAST('fe80::62:5aff:fed1:daf0', 'LowCardinality(String)'))))) AS `hex(SHA512(ipv6))`, hex(SHA512_256(toIPv6(materialize(_CAST('fe80::62:5aff:fed1:daf0', 'LowCardinality(String)'))))) AS `hex(SHA512_256(ipv6))`, farmFingerprint64(toIPv6(materialize(_CAST('fe80::62:5aff:fed1:daf0', 'LowCardinality(String)')))) AS `farmFingerprint64(ipv6)`, javaHash(toIPv6(materialize(_CAST('fe80::62:5aff:fed1:daf0', 'LowCardinality(String)')))) AS `javaHash(ipv6)`, xxh3(toIPv6(materialize(_CAST('fe80::62:5aff:fed1:daf0', 'LowCardinality(String)')))) AS `xxh3(ipv6)`, wyHash64(toIPv6(materialize(_CAST('fe80::62:5aff:fed1:daf0', 'LowCardinality(String)')))) AS `wyHash64(ipv6)`, xxHash32(toIPv6(materialize(_CAST('fe80::62:5aff:fed1:daf0', 'LowCardinality(String)')))) AS `xxHash32(ipv6)`, gccMurmurHash(toIPv6(materialize(_CAST('fe80::62:5aff:fed1:daf0', 'LowCardinality(String)')))) AS `gccMurmurHash(ipv6)`, murmurHash2_32(toIPv6(materialize(_CAST('fe80::62:5aff:fed1:daf0', 'LowCardinality(String)')))) AS `murmurHash2_32(ipv6)`, javaHashUTF16LE(toIPv6(materialize(_CAST('fe80::62:5aff:fed1:daf0', 'LowCardinality(String)')))) AS `javaHashUTF16LE(ipv6)`, metroHash64(toIPv6(materialize(_CAST('fe80::62:5aff:fed1:daf0', 'LowCardinality(String)')))) AS `metroHash64(ipv6)`, hex(sipHash128(toIPv6(materialize(_CAST('fe80::62:5aff:fed1:daf0', 'LowCardinality(String)'))))) AS `hex(sipHash128(ipv6))`, hex(murmurHash3_128(toIPv6(materialize(_CAST('fe80::62:5aff:fed1:daf0', 'LowCardinality(String)'))))) AS `hex(murmurHash3_128(ipv6))`, sipHash64(toIPv6(materialize(_CAST('fe80::62:5aff:fed1:daf0', 'LowCardinality(String)')))) AS `sipHash64(ipv6)`, xxHash64(toIPv6(materialize(_CAST('fe80::62:5aff:fed1:daf0', 'LowCardinality(String)')))) AS `xxHash64(ipv6)`, murmurHash2_64(toIPv6(materialize(_CAST('fe80::62:5aff:fed1:daf0', 'LowCardinality(String)')))) AS `murmurHash2_64(ipv6)`, cityHash64(toIPv6(materialize(_CAST('fe80::62:5aff:fed1:daf0', 'LowCardinality(String)')))) AS `cityHash64(ipv6)`, hiveHash(toIPv6(materialize(_CAST('fe80::62:5aff:fed1:daf0', 'LowCardinality(String)')))) AS `hiveHash(ipv6)`, murmurHash3_64(toIPv6(materialize(_CAST('fe80::62:5aff:fed1:daf0', 'LowCardinality(String)')))) AS `murmurHash3_64(ipv6)`, murmurHash3_32(toIPv6(materialize(_CAST('fe80::62:5aff:fed1:daf0', 'LowCardinality(String)')))) AS `murmurHash3_32(ipv6)` FROM system.one AS __table1
```

Doesn't have anything to do with clang-18.


Probably related/fixed by https://github.com/ClickHouse/ClickHouse/pull/60359 (needs to be checked)

**Comment by Algunenano** [comment]
It was indeed fixed by https://github.com/ClickHouse/ClickHouse/pull/60359
