### ISSUE TITLE
Multiple predicates on a column with an index causes an exception

### ISSUE THREAD

**Issue by aaron276h** [ClickHouse/ClickHouse#60660]
Clickhouse version `24.1.1`

**Describe what's wrong**

Querying a MergeTree table with multiple predicates on a single column that has an index causes an exception.

[reproduder](https://fiddle.clickhouse.com/320052e6-82a5-467c-a3ee-1aa602ddaa37)

**Does it reproduce on the most recent release?**

Yes

**How to reproduce**

```
CREATE TABLE IF NOT EXISTS example(
     "id" Int64,
    "labels" Map(String, String),
    INDEX labels mapKeys(labels) TYPE SET(0) GRANULARITY 1,
 ) ENGINE = MergeTree()
ORDER BY ("id")

INSERT into example (*) Values (toInt64(10), {'key1': 'val1', 'key2':'val2'});

SELECT * FROM example WHERE has(mapKeys(labels), 'key1') AND has(mapKeys(labels), 'key2') 
```
```
Received exception from server (version 24.2.1):
Code: 10. DB::Exception: Received from localhost:9000. DB::Exception: Not found column mapKeys(labels) in block: while executing 'INPUT : 1 -> mapKeys(labels) Array(String) : 3'. (NOT_FOUND_COLUMN_IN_BLOCK)
(query: SELECT * FROM example WHERE has(mapKeys(labels), 'key1') AND has(mapKeys(labels), 'key2') )
```

**Expected behavior**

Query to run correctly.

**Comment by CyberKexx** [comment]
Possibly related to https://github.com/ClickHouse/ClickHouse/issues/60671

**Comment by Kirannaik78** [comment]
The problem lies in the fact that 'mapkeys(labels)' is not a direct column in the table. Instead, it's part of the index definition. you can't directly reference it in the WHERE clause. To filter results based on keys in the 'labels' map. 

```
select * from example where has(labels, 'key1') and has(labels, 'key2');
```

**Comment by aaron276h** [comment]
@Kirannaik78 if we use `has(labels, 'key1')` instead of `has(mapKeys(labels), 'key1')` then the data skipping index on the keys of the labels column is no longer being used. Can see this on a table with multiple parts and running `EXPLAIN indexes=1 SELECT ...`

Worth pointing that the query `SELECT * FROM example WHERE has(mapKeys(labels), 'key1') AND has(mapKeys(labels), 'key2')` works when the index `INDEX labels mapKeys(labels) TYPE SET(0) GRANULARITY 1` does not exist, which makes this seem like an indexing problem.

**Comment by aaron276h** [comment]
> problem lies in the fact that 'mapkeys(labels)' is not a direct column in the table. Instead, it's part of the index definition. you can't directly reference it in the WHERE clause

Also wanted to point out that having one predicate on `mapkeys(labels)` works as expected, for example:

```
SELECT * FROM example WHERE has(mapKeys(labels), 'key1')
```
does not cause an exception.

**Comment by filimonov** [comment]
It's the regression between 23.12 and 24.1
https://fiddle.clickhouse.com/7372ba5d-b258-4ea5-8080-18ea2be45e3e 
https://fiddle.clickhouse.com/9b42053f-ebba-42ce-8e8f-ef104190714f

**Comment by cw9** [comment]
any update on this?

**Comment by cw9** [comment]
can confirm this is still broken in version 24.10.2

**Comment by UnamedRus** [comment]
Two suspects https://github.com/ClickHouse/ClickHouse/commit/7a271f09ed134d339a3f87397cc8e2306d536242
https://github.com/ClickHouse/ClickHouse/commit/ddbdd89904e9396def354a8c748f738aac956f8c
 
Main is https://github.com/ClickHouse/ClickHouse/pull/58480

@KochetovNicolai

```
#0  __cxa_throw (thrown_object=0x55556b4bec00, tinfo=0x555566fc9580 <typeinfo for DB::Exception>, dest=0x555559a5f1c0 <DB::Exception::~Exception()>) at /home/projects/gh/ClickHouse/contrib/llvm-project/libcxxabi/src/cxa_exception.cpp:279
#1  0x00005555641bb3b2 in DB::executeAction (action=..., execution_context=..., dry_run=false, allow_duplicates_in_input=false) at /home/projects/gh/ClickHouse/src/Interpreters/ExpressionActions.cpp:725
#2  DB::ExpressionActions::execute (this=this@entry=0x55556d0b60c8, block=..., num_rows=@0x7fffffff6d88: 1, dry_run=false, allow_duplicates_in_input=false) at /home/projects/gh/ClickHouse/src/Interpreters/ExpressionActions.cpp:781
#3  0x00005555641bbb5b in DB::ExpressionActions::execute (this=0x55556d0b60c8, block=..., dry_run=false, allow_duplicates_in_input=false) at /home/projects/gh/ClickHouse/src/Interpreters/ExpressionActions.cpp:827
#4  0x0000555565c6fd6c in DB::MergeTreeIndexConditionSet::getPossibleGranules (this=0x55556a468b98, idx_granules=...) at /home/projects/gh/ClickHouse/src/Storages/MergeTree/MergeTreeIndexSet.cpp:445
#5  0x0000555565c36196 in DB::MergeTreeDataSelectExecutor::filterMarksUsingIndex (index_helper=..., condition=..., part=..., ranges=..., settings=..., reader_settings=..., mark_cache=<optimized out>, uncompressed_cache=<optimized out>,

```

https://github.com/ClickHouse/ClickHouse/blob/d4dae3066ebc0a805f6d34539b9b6053fc420932/src/Storages/MergeTree/MergeTreeIndexSet.cpp#L445

**Comment by alexey-milovidov** [comment]
Still reproduces in master 25.10.

**Comment by alexey-milovidov** [comment]
Still reproduces in master 26.1.
