### ISSUE TITLE
Not found column _sample_factor when WHERE is present

### ISSUE THREAD

**Issue by ruslandoga** [ClickHouse/ClickHouse#60685]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**

I'm getting `NOT_FOUND_COLUMN_IN_BLOCK` error for `_sample_factor` on queries containing a WHERE clause: 

```console
$ docker run -d --rm --ulimit nofile=262144:262144 clickhouse/clickhouse-server:24.2
$ docker exec -ti 4e clickhouse client
```
```sql
4ed07fc7aea4 :) create table demo(a UInt64, b UInt64) engine MergeTree order by (a, b) sample by b;
4ed07fc7aea4 :) insert into demo(a, b) values (1, 2), (3, 4);

4ed07fc7aea4 :) select uniq(b) * any(_sample_factor) from demo sample 200000;
-- ┌─multiply(uniq(b), any(_sample_factor))─┐
-- │                                      2 │
-- └────────────────────────────────────────┘

4ed07fc7aea4 :) select uniq(b) * any(_sample_factor) from demo sample 200000 where a < -1;
-- Received exception from server (version 24.2.1):
-- Code: 10. DB::Exception: Received from localhost:9000. DB::Exception: Not found column _sample_factor:  in block a UInt64 UInt64(size = 0), b UInt64 UInt64(size = 0). (NOT_FOUND_COLUMN_IN_BLOCK)

4ed07fc7aea4 :) select version();
-- ┌─version()───┐
-- │ 24.2.1.2248 │
-- └─────────────┘
```

**Comment by deltamualpha** [comment]
also getting something that looks related to this error, also when using plausible:

```
2024.03.04 03:07:15.885032 [ 718 ] {4945bbac-e61f-488b-a728-ebe8fd57b7ad} <Error> DynamicQueryHandler: Code: 10. DB::Exception: Not found column _sample_factor:  in block timestamp DateTime UInt32(size = 0), site_id UInt64 UInt64(size = 0), user_id UInt64 UInt64(size = 0). (NOT_FOUND_COLUMN_IN_BLOCK), Stack trace (when copying this message, always include the lines below): |  
-- | --
  |   | 22. ? @ 0x00007fce3f045353 |  
  |   | 21. ? @ 0x00007fce3f120609 |  
  |   | 20. Poco::ThreadImpl::runnableEntry(void*) @ 0x00000000159a6c1d |  
  |   | 19. Poco::PooledThread::run() @ 0x00000000159a85e7 |  
  |   | 18. Poco::Net::TCPServerDispatcher::run() @ 0x00000000158aff51 |  
  |   | 17. Poco::Net::TCPServerConnection::start() @ 0x00000000158af152 |  
  |   | 16. DB::HTTPServerConnection::run() @ 0x0000000012fdb73a |  
  |   | 15. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x0000000012f61350 |  
  |   | 14. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional<DB::CurrentThread::QueryScope>&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x0000000012f5ca15 |  
  |   | 13. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::shared_ptr<DB::Context>, std::function<void (DB::QueryResultDetails const&)>, DB::QueryFlags, std::optional<DB::FormatSettings> const&, std::function<void (DB::IOutputFormat&)>) @ 0x0000000011f6b9a9 |  
  |   | 12. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x0000000011f68134 |  
  |   | 11. DB::InterpreterSelectWithUnionQuery::execute() @ 0x0000000011bd33d7 |  
  |   | 10. DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&) @ 0x000000001344fc8e |  
  |   | 9. DB::QueryPlan::optimize(DB::QueryPlanOptimizationSettings const&) @ 0x0000000013450dd6 |  
  |   | 8. DB::QueryPlanOptimizations::optimizeTreeSecondPass(DB::QueryPlanOptimizationSettings const&, DB::QueryPlan::Node&, std::list<DB::QueryPlan::Node, std::allocator<DB::QueryPlan::Node>>&) @ 0x00000000134e12ac |  
  |   | 7. DB::QueryPlanOptimizations::optimizePrewhere(std::vector<DB::QueryPlanOptimizations::Frame, std::allocator<DB::QueryPlanOptimizations::Frame>>&, std::list<DB::QueryPlan::Node, std::allocator<DB::QueryPlan::Node>>&) @ 0x00000000134e3ac8 |  
  |   | 6. std::__unique_if<DB::ExpressionStep>::__unique_single std::make_unique[abi:v15000]<DB::ExpressionStep, DB::DataStream const&, std::shared_ptr<DB::ActionsDAG>>(DB::DataStream const&, std::shared_ptr<DB::ActionsDAG>&&) @ 0x00000000134e45e6 |  
  |   | 5. DB::ExpressionStep::ExpressionStep(DB::DataStream const&, std::shared_ptr<DB::ActionsDAG> const&) @ 0x000000001342286e |  
  |   | 4. DB::ExpressionTransform::transformHeader(DB::Block, DB::ActionsDAG const&) @ 0x000000001329e164 |  
  |   | 3. DB::ActionsDAG::updateHeader(DB::Block) const @ 0x00000000110b5490 |  
  |   | 2. DB::ActionsDAG::evaluatePartialResult(std::unordered_map<DB::ActionsDAG::Node const*, DB::ColumnWithTypeAndName, std::hash<DB::ActionsDAG::Node const*>, std::equal_to<DB::ActionsDAG::Node const*>, std::allocator<std::pair<DB::ActionsDAG::Node const* const, DB::ColumnWithTypeAndName>>>&, std::vector<DB::ActionsDAG::Node const*, std::allocator<DB::ActionsDAG::Node const*>> const&, unsigned long, bool) @ 0x00000000110b7403 |  
  |   | 1. DB::Exception::Exception<String const&>(int, FormatStringHelperImpl<std::type_identity<String const&>::type>, String const&) @ 0x00000000078e0983 |  
  |   | 0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000cf5565b
```

Reverting to the previous version immediately fixed the issue.

**Comment by nodecook-dev** [comment]
Same here

**Comment by CurtizJ** [comment]
It will be fixes in #60205. As a workaround in version 24.2 you can set `query_plan_optimize_prewhere = 0` to return the previous behaviour.

**Comment by luizkowalski** [comment]
👋🏻 

This is my current config:

```xml
<clickhouse>
    <prometheus>
        <endpoint>/metrics</endpoint>
        <port>8122</port>
        <metrics>true</metrics>
        <events>true</events>
        <asynchronous_metrics>true</asynchronous_metrics>
        <errors>true</errors>
    </prometheus>
    <profiles>
        <default>
            <log_queries>0</log_queries>
            <log_query_threads>0</log_query_threads>
           <query_plan_optimize_prewhere>0</query_plan_optimize_prewhere>
        </default>
    </profiles>
</clickhouse>
```

I'm running Plausible on CH 24.2.1.2248 and still seeing the same error:


```
    Args: [#Function<0.120383873/1 in Plausible.ClickhouseRepo.parallel_tasks/1>, [#Function<1.31364236/0 in Plausible.Stats.Aggregate.aggregate/3>]]
10:42:39.672 request_id=F7rECufU1eQJ6WgAABDh [info] Sent 500 in 14ms
10:42:39.674 [error] #PID<0.3730.0> running PlausibleWeb.Endpoint (connection #PID<0.3729.0>, stream id 1) terminated
Server: plausible.sumiu.link:80 (http)
Request: GET /api/stats/luizkowalski.net/browsers?period=day&date=2024-03-08&filters=%7B%7D&with_imported=true
** (exit) an exception was raised:
    ** (Ch.Error) Code: 10. DB::Exception: Not found column _sample_factor:  in block start DateTime UInt32(size = 0), site_id UInt64 UInt64(size = 0), user_id UInt64 UInt64(size = 0), browser LowCardinality(String) ColumnLowCardinality(size = 0, UInt8(size = 0), ColumnUnique(size = 1, String(size = 1))). (NOT_FOUND_COLUMN_IN_BLOCK) (version 24.2.1.2248 (official build))

        (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
        (ecto_ch 0.1.9) lib/ecto/adapters/clickhouse.ex:269: Ecto.Adapters.ClickHouse.execute/5
        (ecto 3.9.5) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
        (ecto 3.9.5) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
        (plausible 0.0.1) lib/plausible/stats/breakdown.ex:195: Plausible.Stats.Breakdown.breakdown_sessions/5
        (plausible 0.0.1) lib/plausible_web/controllers/api/stats_controller.ex:933: PlausibleWeb.Api.StatsController.browsers/2
        (plausible 0.0.1) lib/plausible_web/controllers/api/stats_controller.ex:1: PlausibleWeb.Api.StatsController.action/2
        (plausible 0.0.1) lib/plausible_web/controllers/api/stats_controller.ex:1: PlausibleWeb.Api.StatsController.phoenix_controller_pipeline/2
10:42:39.676 [error] Ranch protocol #PID<0.3727.0> of listener PlausibleWeb.Endpoint.HTTP (connection #PID<0.3726.0>, stream id 1) terminated
an exception was raised:
    ** (Ch.Error) Code: 10. DB::Exception: Not found column _sample_factor:  in block site_id UInt64 UInt64(size = 0), start DateTime UInt32(size = 0), sign Int8 Int8(size = 0), is_bounce UInt8 UInt8(size = 0), pageviews Int32 Int32(size = 0), duration UInt32 UInt32(size = 0). (NOT_FOUND_COLUMN_IN_BLOCK) (version 24.2.1.2248 (official build))
```

Not sure if this Plausible or CH anymore...any ideas?

**Comment by ruslandoga** [comment]
@luizkowalski 

Please check that the setting is set correctly from one of the Plausible ClickHouse connections.

```console
$ docker compose exec plausible bin/plausible remote
```
```elixir
iex> Plausible.ClickhouseRepo.query("show setting query_plan_optimize_prewhere")
#=> %Ch.Result{rows: [["0"]]}
```

**Comment by luizkowalski** [comment]
Nevermind, got it. `query_plan_optimize_prewhere` XML config option is only available on `24.2`, apparently? anyway, all good now; thanks a lot, @ruslandoga and @CurtizJ

**Comment by PedroTadim** [comment]
Hello! I still hit this error inside a mutation: https://fiddle.clickhouse.com/5bb32d65-adb6-4efb-b0a9-faa95e43d5e8 Is this an issue?
