### ISSUE TITLE
Assertion `n < size()' failed for `JSONExtract` function

### ISSUE THREAD

**Issue by jkartseva** [ClickHouse/ClickHouse#61562]
**Describe the bug**
```
clickhouse-server: /build/src/Columns/ColumnString.h:109: virtual StringRef DB::ColumnString::getDataAt(size_t) const: Assertion `n < size()' failed.
2024.03.18 20:31:33.490711 [ 306 ] {} <Trace> BaseDaemon: Received signal 6
2024.03.18 20:31:33.491483 [ 1328 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2024.03.18 20:31:33.491575 [ 1328 ] {} <Fatal> BaseDaemon: (version 24.3.1.1 (official build), build id: EEAA401996E448EDF4AED282E057F13371DD96F6, git hash: 0bd60dac5109845ddd7ec532d7aaf3eafdd3b6fc) (from thread 308) Received signal 6
2024.03.18 20:31:33.491623 [ 1328 ] {} <Fatal> BaseDaemon: Signal description: Aborted
2024.03.18 20:31:33.491650 [ 1328 ] {} <Fatal> BaseDaemon:
2024.03.18 20:31:33.491719 [ 1328 ] {} <Fatal> BaseDaemon: Stack trace: 0x00007effad6729fc 0x00007effad61e476 0x00007effad6047f3 0x00007effad60471b 0x00007effad615e96 0x000000000a9bf379 0x000000000bb78953 0x000000000bbb4b71 0x000000000bbb41ea 0x000000000bbb40a1 0x000000000a9dc0f9 0x00000000195c9f26 0x00000000195caa2c 0x00000000195cbf95 0x000000001a949867 0x000000001a94949e 0x000000001a948980 0x000000001deba911 0x000000001e157106 0x000000001b98b711 0x000000001b97d7e2 0x000000001b9758a5 0x000000001b97285d 0x000000001bb08434 0x000000001bb08f80 0x000000001c0bebd7 0x000000001c0b912a 0x000000001d8e4b72 0x000000001d8f9aa5 0x0000000022cbceb9 0x0000000022cbd708 0x0000000022e94a74 0x0000000022e9181a 0x0000000022e9055e 0x00007effad670ac3 0x00007effad702850
2024.03.18 20:31:33.491767 [ 1328 ] {} <Fatal> BaseDaemon: ########################################
2024.03.18 20:31:33.492058 [ 1328 ] {} <Fatal> BaseDaemon: (version 24.3.1.1 (official build), build id: EEAA401996E448EDF4AED282E057F13371DD96F6, git hash: 0bd60dac5109845ddd7ec532d7aaf3eafdd3b6fc) (from thread 308) (query_id: f335ab9c-9165-4f3e-8236-c1bca923d9f6) (query: SELECT JSONExtract(materialize(toLowCardinality('{"string_value":null}')), materialize('string_value'), 'LowCardinality(Nullable(String))') AS x WHERE coalesce(coalesce(NULL, 1, 100, NULL))) Received signal Aborted (6)
```
[A link to the report
](https://s3.amazonaws.com/clickhouse-test-reports/0/0bd60dac5109845ddd7ec532d7aaf3eafdd3b6fc/ast_fuzzer__debug_.html)

**How to reproduce**
```
SELECT JSONExtract(materialize(toLowCardinality('{"string_value":null}')), materialize('string_value'), 'LowCardinality(Nullable(String))') AS x WHERE coalesce(coalesce(NULL, 1, 100, NULL))
```
The issue is seemingly related to the `toLowCardinality` conversion.

**Comment by jkartseva** [comment]
Another issue includes `LowCardinality` types. Maybe related:
```
2024.03.18 18:03:35.851041 [ 239 ] {03db7d12-96f3-4ed0-a262-993271951293} <Trace> Planner: Query SELECT _CAST(2, 'Nullable(UInt8)') AS `toNullable(toNullable(2))`, 19 AND greatest(materialize(_CAST(1, 'LowCardinality(UInt8)')) % 2, _CAST(1, 'UInt8')) AND _CAST(1, 'UInt8') AND 2 AS `and(19, greatest(modulo(materialize(toLowCardinality(1)), 2), greatest(greatest(1, 1))), greatest(modulo(1, 2), modulo(1, 2)), 2)` FROM system.one AS __table1 GROUP BY _CAST(1, 'UInt8') from stage FetchColumns to stage Complete
==237==WARNING: MemorySanitizer: use-of-uninitialized-value
2024.03.18 18:03:36.000307 [ 915 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 2.89 GiB, peak 3.56 GiB, free memory in arenas 0.00 B, will set to 2.90 GiB (RSS), difference: 8.28 MiB
    #0 0x555faf5a3f63 in DB::ColumnVector<char8_t>::compareAt(unsigned long, unsigned long, DB::IColumn const&, int) const build_docker/./src/Columns/ColumnVector.h:147:9
    #1 0x555f8a59433e in DB::FunctionLeastGreatestGeneric<(DB::LeastGreatest)1>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/workspace/clickhouse+0x1291433e) (BuildId: 2e0c45d7903fdf3c6de4c5dc872f8048627bf35a)
    #2 0x555f7f9861a1 in DB::IFunction::executeImplDryRun(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/workspace/clickhouse+0x7d061a1) (BuildId: 2e0c45d7903fdf3c6de4c5dc872f8048627bf35a)
    #3 0x555f81a1ebb7 in DB::FunctionToExecutableFunctionAdaptor::executeDryRunImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/workspace/clickhouse+0x9d9ebb7) (BuildId: 2e0c45d7903fdf3c6de4c5dc872f8048627bf35a)
    #4 0x555fa82ea639 in DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_docker/./src/Functions/IFunction.cpp:246:15
    #5 0x555fa82ee9de in DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_docker/./src/Functions/IFunction.cpp:281:24
    #6 0x555fa82f2be5 in DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_docker/./src/Functions/IFunction.cpp:378:16
    #7 0x555faaba2711 in DB::executeActionForPartialResult(DB::ActionsDAG::Node const*, std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>>, unsigned long) build_docker/./src/Interpreters/ActionsDAG.cpp:662:49
    #8 0x555faaba2711 in DB::ActionsDAG::evaluatePartialResult(std::__1::unordered_map<DB::ActionsDAG::Node const*, DB::ColumnWithTypeAndName, std::__1::hash<DB::ActionsDAG::Node const*>, std::__1::equal_to<DB::ActionsDAG::Node const*>, std::__1::allocator<std::__1::pair<DB::ActionsDAG::Node const* const, DB::ColumnWithTypeAndName>>>&, std::__1::vector<DB::ActionsDAG::Node const*, std::__1::allocator<DB::ActionsDAG::Node const*>> const&, unsigned long, bool) build_docker/./src/Interpre
 ```
 
 https://s3.amazonaws.com/clickhouse-test-reports/0/d4895c2e52912d63a64aef87c64768d42f8f7fc5/ast_fuzzer__msan_.html
