### ISSUE TITLE
get Coordination::Exception: XID overflow (Session expired), bug zookeeper do not zxid overflow.

### ISSUE THREAD

**Issue by cosen-wu** [ClickHouse/ClickHouse#61978]
1.we have cluster of 4s2r and two zookeeper cluster.

2.clickhouse version: 22.8.21.38 (official build)

3.get error log, and table in readonly mode.
2024.03.27 19:37:42.108924 [ 54729 ] {}> test.part_only (1569e912-5bc4-4eea-9bf6-67f060c3d9af): void DB::StorageReplicatedMergeTree::mutationsUpdatingTask(): Code: 999. Coordination::Exception: XID overflow (Session expired). (KEEPER_EXCEPTION), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa40325a in /usr/bin/clickhouse
1. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error, int) @ 0x161c8836 in /usr/bin/clickhouse
2. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error) @ 0x161c8abc in /usr/bin/clickhouse
3. Coordination::ZooKeeper::pushRequest(Coordination::ZooKeeper::RequestInfo&&) @ 0x162177a2 in /usr/bin/clickhouse
4. Coordination::ZooKeeper::list(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::ListRequestType, std::__1::function<void (Coordination::ListResponse const&)>, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x16219844 in /usr/bin/clickhouse
5. zkutil::ZooKeeper::asyncTryGetChildrenNoThrow(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (Coordination::WatchResponse const&)>, Coordination::ListRequestType) @ 0x161d1a3b in /usr/bin/clickhouse
6. zkutil::ZooKeeper::getChildrenImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&, Coordination::Stat*, std::__1::function<void (Coordination::WatchResponse const&)>, Coordination::ListRequestType) @ 0x161d1528 in /usr/bin/clickhouse
7. zkutil::ZooKeeper::tryGetChildrenWatch(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&, Coordination::Stat*, std::__1::function<void (Coordination::WatchResponse const&)>, Coordination::ListRequestType) @ 0x161d1fc0 in /usr/bin/clickhouse
8. zkutil::ZooKeeper::getChildrenWatch(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Stat*, std::__1::function<void (Coordination::WatchResponse const&)>, Coordination::ListRequestType) @ 0x161d1eaf in /usr/bin/clickhouse
9. DB::ReplicatedMergeTreeQueue::updateMutations(std::__1::shared_ptr<zkutil::ZooKeeper>, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x15aa743b in /usr/bin/clickhouse
10. DB::StorageReplicatedMergeTree::mutationsUpdatingTask() @ 0x1557f286 in /usr/bin/clickhouse
11. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x13f35ab8 in /usr/bin/clickhouse
12. DB::BackgroundSchedulePool::threadFunction() @ 0x13f38396 in /usr/bin/clickhouse
13. ? @ 0x13f390cc in /usr/bin/clickhouse
14. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa4c4828 in /usr/bin/clickhouse
15. ? @ 0xa4c7a3d in /usr/bin/clickhouse
16. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
17. __clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
 (version 22.8.21.38 (official build))

4.zookeeper error log
2024-03-27 19:37:40,795 [myid:] - WARN  [NIOWorkerThread-33:o.a.z.s.NIOServerCnxn@388] - Close of session 0x301062ec9db0013
java.io.IOException: Broken pipe
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
        at sun.nio.ch.IOUtil.write(IOUtil.java:51)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
        at org.apache.zookeeper.server.NIOServerCnxn.handleWrite(NIOServerCnxn.java:286)
        at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:363)
        at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:508)
        at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:153)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2024-03-27 19:37:40,915 [myid:] - WARN  [NIOWorkerThread-25:o.a.z.s.ZooKeeperServer@1422] - Connection request from old client /10.14.203.21:51146; will be dropped if server is in r-o mode
2024-03-27 19:37:40,916 [myid:] - INFO  [CommitProcessor:3:o.a.z.s.q.LeaderSessionTracker@104] - Committing global session 0x301062ec9db001b

5.The setting of zookeeper session time out
<session_timeout_ms>180000</session_timeout_ms>

6.My questions:
- Why did this problem occur？
- Is there a way to solve this problem？ 

Thanks.

**Comment by den-crane** [comment]
Expected behaviour. 

XID overflow is well-known Zookeeper flaw. https://dev.zookeeper.apache.narkive.com/FtSQMeuz/jira-updated-zookeeper-2789-reassign-zxid-for-solving-32bit-overflow-problem 

Yes. Clickhouse tables became readonly. Also expected. Also well-known.

>22.8.21.38

Obsolete. You should upgrade to a supported version, 24.3, 23.8 ... In the recent Clickhouse versions readonly state is much shorter, several milliseconds instead of 10 seconds. 

v22.10.1.1877-stable.md:* - Improve the time to recover lost keeper connections. [#42541](https://github.com/ClickHouse/ClickHouse/pull/42541) ([Raúl Marín](https://github.com/Algunenano)).

---

Also you may try clickhouse-keeper https://clickhouse.com/clickhouse/keeper  https://clickhouse.com/blog/clickhouse-keeper-a-zookeeper-alternative-written-in-cpp 

https://github.com/ClickHouse/ClickHouse/issues/44415#issuecomment-1564435871

**Comment by cosen-wu** [comment]
@den-crane 
It's strange that I didn't execute the mutation query, but the stack shows that the mutationsUpdatingTask method has been called. Why is this?
9.DB::ReplicatedMergeTreeQueue::updateMutations(std::__1::shared_ptrzkutil::ZooKeeper, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x15aa743b in /usr/bin/clickhouse
10.DB::StorageReplicatedMergeTree::mutationsUpdatingTask() @ 0x1557f286 in /usr/bin/clickhouse

**Comment by cosen-wu** [comment]
thanks for your reply.
The `session_timeout_ms `has been set for three minutes, but the problem still occurs. Is there a way for me to troubleshoot this issue? Because I can't see any issues with zookeeper from the metrics, or do you need me to provide some information to troubleshoot the problem?

**Comment by Algunenano** [comment]
@cosen-wu As @den-crane has said: this is a known limitation of Zookeeper. Recent versions of CH have introduced multiple improvements so that it has less impact, including the replacement of Zookeeper by clickhouse-keeper. You should upgrade.
