### ISSUE TITLE
Can't truncate partitioned S3 engine table

### ISSUE THREAD

**Issue by Beetelbrox** [ClickHouse/ClickHouse#62379]
### **Describe the unexpected behaviour**
When trying to truncate a S3 engine table with a `PARTITION BY` clause, the corresponding `{_partition_id}` wildcard and no additional globs you get the following error:
```
S3 key 'partition-overwrite/{_partition_id}.parquet' contains globs, so the table is in readonly mode. (DATABASE_ACCESS_DENIED)
```

### **How to reproduce**
Tested on `24.4.1.444`

Create partitioned s3 table:
```
CREATE TABLE s3_engine_table
(
    `name` String,
    `value` UInt32
)
ENGINE = S3('http://localhost:6000/my-bucket/partition-overwrite/{_partition_id}.parquet', 'admin', 'password', 'Parquet') PARTITION BY name
```

Try to truncate it:
```
TRUNCATE TABLE s3_engine_table SYNC

Query id: 90640428-b316-4fc3-a44d-fad70ba1d756


Elapsed: 0.023 sec.

Received exception:
Code: 291. DB::Exception: S3 key 'partition-overwrite/{_partition_id}.parquet' contains globs, so the table is in readonly mode. (DATABASE_ACCESS_DENIED)
```

### **Expected behavior**
I can truncate partitioned s3 tables as I can truncate non-partitioned ones without globs.

### **Error message and/or stacktrace**
```
TRUNCATE TABLE s3_engine_table SYNC

Query id: d80557c6-9737-4dcb-9ae8-935b49a2f4fe

2024.04.07 14:19:23.317293 [ 1638322 ] {} <Trace> LOCAL-Session: 0d10e09a-681f-4a75-a061-170f7c70656e Creating query context from session context, user_id: 94309d50-4f52-5250-31bd-74fecac179db, parent context user: default
2024.04.07 14:19:23.317391 [ 1638322 ] {d80557c6-9737-4dcb-9ae8-935b49a2f4fe} <Debug> executeQuery: (from 0.0.0.0:0, user: ) TRUNCATE TABLE s3_engine_table SYNC (stage: Complete)
2024.04.07 14:19:23.317488 [ 1638322 ] {d80557c6-9737-4dcb-9ae8-935b49a2f4fe} <Trace> ContextAccess (default): Access granted: TRUNCATE ON default.s3_engine_table
2024.04.07 14:19:23.317656 [ 1638322 ] {d80557c6-9737-4dcb-9ae8-935b49a2f4fe} <Error> executeQuery: Code: 291. DB::Exception: S3 key 'partition-overwrite/{_partition_id}.parquet' contains globs, so the table is in readonly mode. (DATABASE_ACCESS_DENIED) (version 24.4.1.444 (official build)) (from 0.0.0.0:0) (in query: TRUNCATE TABLE s3_engine_table SYNC), Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(String const&, int) @ 0x000000010d25ba80
1. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x00000001074991a4
2. DB::Exception::Exception<String&>(int, FormatStringHelperImpl<std::type_identity<String&>::type>, String&) @ 0x0000000102c56bb0
3. DB::StorageS3::truncate(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::Context const>, DB::TableExclusiveLockHolder&) @ 0x000000010b8be9e0
4. DB::InterpreterDropQuery::executeToTableImpl(std::shared_ptr<DB::Context const>, DB::ASTDropQuery&, std::shared_ptr<DB::IDatabase>&, StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>&) @ 0x000000010ae6aa3c
5. DB::InterpreterDropQuery::executeToTable(DB::ASTDropQuery&) @ 0x000000010ae69be8
6. DB::InterpreterDropQuery::execute() @ 0x000000010ae69030
7. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x000000010b1c436c
8. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x000000010b1c1338
9. DB::LocalConnection::sendQuery(DB::ConnectionTimeouts const&, String const&, std::unordered_map<String, String, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, String>>> const&, String const&, unsigned long long, DB::Settings const*, DB::ClientInfo const*, bool, std::function<void (DB::Progress const&)>) @ 0x000000010bddbd20
10. DB::ClientBase::processOrdinaryQuery(String const&, std::shared_ptr<DB::IAST>) @ 0x000000010bd992e4
11. DB::ClientBase::processParsedSingleQuery(String const&, String const&, std::shared_ptr<DB::IAST>, std::optional<bool>, bool) @ 0x000000010bd981b0
12. DB::ClientBase::processTextAsSingleQuery(String const&) @ 0x000000010bd975b0
13. DB::ClientBase::processQueryText(String const&) @ 0x000000010bda0f00
14. DB::ClientBase::runInteractive() @ 0x000000010bda2b90
15. DB::LocalServer::main(std::vector<String, std::allocator<String>> const&) @ 0x00000001076f2924
16. Poco::Util::Application::run() @ 0x000000010d14797c
17. mainEntryClickHouseLocal(int, char**) @ 0x00000001076fa5a0
18. main @ 0x0000000102c3fb9c
19. start @ 0x0000000180ce7f28


Elapsed: 0.001 sec.

Received exception:
Code: 291. DB::Exception: S3 key 'partition-overwrite/{_partition_id}.parquet' contains globs, so the table is in readonly mode. (DATABASE_ACCESS_DENIED)
```

### **Additional context**
The `{_partition_id}` template is interpreted as a glob instead of expanded, causing the truncate to fail. Found this out while trying to truncate a table I had just inserted data into.

**Comment by Aigul9** [comment]
I have a similar issue
When trying to execute query via Airflow:
```
    query = f"""
        INSERT INTO FUNCTION
           s3(
               '{S3_ENDPOINT}/{S3_BUCKET}/{S3_FOLDER}/{view_name}/{filename}__{{_partition_id}}.csv.gz',
               {S3_ACCESS_KEY_ID},
               {S3_SECRET_ACCESS_KEY},
               'CSV'
            )
        SELECT *
        FROM {schema}.{view_name}
        LIMIT 10;
    """
    ```
    
    I get the error:
    ```
    [2024-10-31, 16:25:32 MSK] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/home/dags/etea/sibgatullinaai/dags/clickhouse_to_s3.py", line 74, in export_to_csv
    client.query(query)
  File "/home/airflow/.local/lib/python3.11/site-packages/clickhouse_connect/driver/client.py", line 193, in query
    return self._query_with_context(query_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/clickhouse_connect/driver/httpclient.py", line 209, in _query_with_context
    response = self._raw_request(body,
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/clickhouse_connect/driver/httpclient.py", line 432, in _raw_request
    self._error_handler(response)
  File "/home/airflow/.local/lib/python3.11/site-packages/clickhouse_connect/driver/httpclient.py", line 357, in _error_handler
    raise OperationalError(err_str) if retried else DatabaseError(err_str) from None
clickhouse_connect.driver.exceptions.DatabaseError: :HTTPDriver for http://clickhouse-chproxy-prod-01.platina:9080 returned response code 500)
 Code: 291. DB::Exception: S3 key 'etea/md_econometric_sm/md_econometric_sm__20241031__162532__9999__{_partition_id}.csv.gz' contains globs, so the table is in readonly mode. (DATABASE_ACCESS_DENIED) (version 24.2.2.71 (official build))
```

Have you found the solution?
