### ISSUE TITLE
Segfault while running query with formatRow

### ISSUE THREAD

**Issue by sebver** [ClickHouse/ClickHouse#62794]
**Describe what's wrong**

Running the following query against the HTTP endpoint will cause clickhouse to segfault:
```
SELECT formatRow('JSONEachRow', number) as test FROM (SELECT number FROM numbers(1000000))
```
When you run with less numbers it will not crash but give weird results:
```
❯ curl http://localhost:8123 -d "SELECT formatRow('JSONEachRow', number) as test FROM (SELECT number FROM numbers(15))"
{"number":"0"}\n
{"number":"1"}\n
{"number":"2"}\n
{"number":"3"}\n
{"number":"4"}\n
{"number":"5"}\n
{"number":"6"}\n
{"number":"7"}\n
{"number":"8"}\n
{"number":"9"}\n
{"number":"10"}\n
{"number":"11"}\0
\0\0\0\0\0\0\0\0\0\0\0\0\0\0��
���\0\0��|���\0\0\0\0\0
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0
```

Running the query with clickhouse-client seems to work fine.

Using `FORMAT` also works fine:
```
❯ curl http://localhost:8123 -d "SELECT number FROM numbers(100000) FORMAT JSONEachRow"
...
{"number":"99998"}
{"number":"99999"}
```

**Does it reproduce on the most recent release?**

Yes.

**How to reproduce**

Run the latest image
```
docker run -p 8123:8123 clickhouse/clickhouse-server:latest
```
Then run the query using the HTTP endpoint:
```
curl http://localhost:8123 -d "SELECT formatRow('JSONEachRow', number) as test FROM (SELECT number FROM numbers(1000000))"
```

As soon as you run it, the container will exit with exit code 139.

**Comment by Algunenano** [comment]
```
==31891==WARNING: MemorySanitizer: use-of-uninitialized-value
2024.04.19 13:39:51.000296 [ 32526 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 611.06 MiB, peak 611.06 MiB, free memory in arenas 0.00 B, will set to 637.82 MiB (RSS), difference: 26.76 MiB
    #0 0x5d68b652a22e in void DB::writeAnyEscapedString<(char)39, false, true>(char const*, char const*, DB::WriteBuffer&) (/mnt/ch/ClickHouse/build_msan_public/programs/clickhouse+0x8b5222e) (BuildId: d4f4e861ed3df660a192b3c3f8b27ff8e4865fb8)
    #1 0x5d68ded3b367 in DB::writeEscapedString(char const*, unsigned long, DB::WriteBuffer&) build_msan_public/./src/IO/WriteHelpers.h:574:5
    #2 0x5d68ded3b367 in DB::writeEscapedString(std::__1::basic_string_view<char, std::__1::char_traits<char>>, DB::WriteBuffer&) build_msan_public/./src/IO/WriteHelpers.h:579:5
    #3 0x5d68ded3b367 in DB::SerializationString::serializeTextEscaped(DB::IColumn const&, unsigned long, DB::WriteBuffer&, DB::FormatSettings const&) const build_msan_public/./src/DataTypes/Serializations/SerializationString.cpp:271:5
    #4 0x5d68e7dfc163 in DB::TabSeparatedRowOutputFormat::writeField(DB::IColumn const&, DB::ISerialization const&, unsigned long) build_msan_public/./src/Processors/Formats/Impl/TabSeparatedRowOutputFormat.cpp
    #5 0x5d68e75c4566 in DB::IRowOutputFormat::write(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>> const&, unsigned long) build_msan_public/./src/Processors/Formats/IRowOutputFormat.cpp:78:9
    #6 0x5d68e75c3d8d in DB::IRowOutputFormat::consume(DB::Chunk) build_msan_public/./src/Processors/Formats/IRowOutputFormat.cpp:31:9
    #7 0x5d68e7b00099 in DB::ParallelFormattingOutputFormat::formatterThreadFunction(unsigned long, unsigned long, std::__1::shared_ptr<DB::ThreadGroup> const&) build_msan_public/./src/Processors/Formats/Impl/ParallelFormattingOutputFormat.cpp:235:32
    #8 0x5d68e7b02f42 in DB::ParallelFormattingOutputFormat::scheduleFormatterThreadForUnitWithNumber(unsigned long, unsigned long)::'lambda'()::operator()() const build_msan_public/./src/Processors/Formats/Impl/ParallelFormattingOutputFormat.h:300:13
    #9 0x5d68e7b02f42 in decltype(std::declval<DB::ParallelFormattingOutputFormat::scheduleFormatterThreadForUnitWithNumber(unsigned long, unsigned long)::'lambda'()&>()()) std::__1::__invoke[abi:v15000]<DB::ParallelFormattingOutputFormat::scheduleFormatterThreadForUnitWithNumber(unsigned long, unsigned long)::'lambda'()&>(DB::ParallelFormattingOutputFormat::scheduleFormatterThreadForUnitWithNumber(unsigned long, unsigned long)::'lambda'()&) build_msan_public/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #10 0x5d68e7b02f42 in void std::__1::__invoke_void_return_wrapper<void, true>::__call<DB::ParallelFormattingOutputFormat::scheduleFormatterThreadForUnitWithNumber(unsigned long, unsigned long)::'lambda'()&>(DB::ParallelFormattingOutputFormat::scheduleFormatterThreadForUnitWithNumber(unsigned long, unsigned long)::'lambda'()&) build_msan_public/./contrib/llvm-project/libcxx/include/__functional/invoke.h:479:9
    #11 0x5d68e7b02f42 in std::__1::__function::__default_alloc_func<DB::ParallelFormattingOutputFormat::scheduleFormatterThreadForUnitWithNumber(unsigned long, unsigned long)::'lambda'(), void ()>::operator()[abi:v15000]() build_msan_public/./contrib/llvm-project/libcxx/include/__functional/function.h:235:12
    #12 0x5d68e7b02f42 in void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::ParallelFormattingOutputFormat::scheduleFormatterThreadForUnitWithNumber(unsigned long, unsigned long)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) build_msan_public/./contrib/llvm-project/libcxx/include/__functional/function.h:716:16
    #13 0x5d68cc42358e in std::__1::__function::__policy_func<void ()>::operator()[abi:v15000]() const build_msan_public/./contrib/llvm-project/libcxx/include/__functional/function.h:848:16
    #14 0x5d68cc42358e in std::__1::function<void ()>::operator()() const build_msan_public/./contrib/llvm-project/libcxx/include/__functional/function.h:1187:12
    #15 0x5d68cc42358e in ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::worker(std::__1::__list_iterator<ThreadFromGlobalPoolImpl<false, true>, void*>) build_msan_public/./src/Common/ThreadPool.cpp:458:13
    #16 0x5d68cc42e252 in void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const build_msan_public/./src/Common/ThreadPool.cpp:220:73
    #17 0x5d68cc42e252 in decltype(std::declval<void>()()) std::__1::__invoke[abi:v15000]<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()&>(void&&) build_msan_public/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #18 0x5d68cc42e252 in decltype(auto) std::__1::__apply_tuple_impl[abi:v15000]<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()&, std::__1::tuple<>&>(void&&, std::__1::tuple<>&, std::__1::__tuple_indices<>) build_msan_public/./contrib/llvm-project/libcxx/include/tuple:1789:1
    #19 0x5d68cc42e252 in decltype(auto) std::__1::apply[abi:v15000]<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()&, std::__1::tuple<>&>(void&&, std::__1::tuple<>&) build_msan_public/./contrib/llvm-project/libcxx/include/tuple:1798:1
    #20 0x5d68cc42e252 in ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'()::operator()() build_msan_public/./src/Common/ThreadPool.h:246:13
    #21 0x5d68cc42e05e in decltype(std::declval<void>()()) std::__1::__invoke[abi:v15000]<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'()&>(void&&) build_msan_public/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #22 0x5d68cc42e05e in void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'()&) build_msan_public/./contrib/llvm-project/libcxx/include/__functional/invoke.h:479:9
    #23 0x5d68cc42e05e in std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>::operator()[abi:v15000]() build_msan_public/./contrib/llvm-project/libcxx/include/__functional/function.h:235:12
    #24 0x5d68cc42e05e in void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) build_msan_public/./contrib/llvm-project/libcxx/include/__functional/function.h:716:16
    #25 0x5d68cc41abca in std::__1::__function::__policy_func<void ()>::operator()[abi:v15000]() const build_msan_public/./contrib/llvm-project/libcxx/include/__functional/function.h:848:16
    #26 0x5d68cc41abca in std::__1::function<void ()>::operator()() const build_msan_public/./contrib/llvm-project/libcxx/include/__functional/function.h:1187:12
    #27 0x5d68cc41abca in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) build_msan_public/./src/Common/ThreadPool.cpp:458:13
    #28 0x5d68cc42824a in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const build_msan_public/./src/Common/ThreadPool.cpp:220:73
    #29 0x5d68cc42824a in decltype(std::declval<void>()()) std::__1::__invoke[abi:v15000]<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&) build_msan_public/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #30 0x5d68cc42824a in void std::__1::__thread_execute[abi:v15000]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>&, std::__1::__tuple_indices<>) build_msan_public/./contrib/llvm-project/libcxx/include/thread:284:5
    #31 0x5d68cc42824a in void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) build_msan_public/./contrib/llvm-project/libcxx/include/thread:295:5
    #32 0x785156e94ac2 in start_thread nptl/pthread_create.c:442:8
    #33 0x785156f2684f  misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

  Uninitialized value was created by a heap allocation
2024.04.19 13:39:55.000208 [ 32526 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 638.19 MiB, peak 638.19 MiB, free memory in arenas 0.00 B, will set to 639.44 MiB (RSS), difference: 1.25 MiB
    #0 0x5d68b527ed8a in realloc (/mnt/ch/ClickHouse/build_msan_public/programs/clickhouse+0x78a6d8a) (BuildId: d4f4e861ed3df660a192b3c3f8b27ff8e4865fb8)
    #1 0x5d68cc11c2ed in Allocator<false, false>::realloc(void*, unsigned long, unsigned long, unsigned long) build_msan_public/./src/Common/Allocator.cpp:155:26
    #2 0x5d68b52f7c6e in void DB::PODArrayBase<1ul, 4096ul, Allocator<false, false>, 63ul, 64ul>::resize<>(unsigned long) (/mnt/ch/ClickHouse/build_msan_public/programs/clickhouse+0x791fc6e) (BuildId: d4f4e861ed3df660a192b3c3f8b27ff8e4865fb8)
    #3 0x5d68b5319e25 in DB::WriteBufferFromVector<DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>>::finalizeImpl() (/mnt/ch/ClickHouse/build_msan_public/programs/clickhouse+0x7941e25) (BuildId: d4f4e861ed3df660a192b3c3f8b27ff8e4865fb8)
    #4 0x5d68b5310e4d in DB::WriteBuffer::finalize() (/mnt/ch/ClickHouse/build_msan_public/programs/clickhouse+0x7938e4d) (BuildId: d4f4e861ed3df660a192b3c3f8b27ff8e4865fb8)
    #5 0x5d68bc3c5bca in DB::(anonymous namespace)::FunctionFormatRow<false>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const formatRow.cpp
    #6 0x5d68b6545d17 in DB::FunctionToExecutableFunctionAdaptor::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/mnt/ch/ClickHouse/build_msan_public/programs/clickhouse+0x8b6dd17) (BuildId: d4f4e861ed3df660a192b3c3f8b27ff8e4865fb8)
    #7 0x5d68dcdeaa7c in DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_msan_public/./src/Functions/IFunction.cpp:248:15
    #8 0x5d68dcdec9a7 in DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_msan_public/./src/Functions/IFunction.cpp:303:22
    #9 0x5d68dcdf2e45 in DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_msan_public/./src/Functions/IFunction.cpp:378:16
    #10 0x5d68dfbf8c31 in DB::executeAction(DB::ExpressionActions::Action const&, DB::(anonymous namespace)::ExecutionContext&, bool, bool) build_msan_public/./src/Interpreters/ExpressionActions.cpp:616:60
    #11 0x5d68dfbf8c31 in DB::ExpressionActions::execute(DB::Block&, unsigned long&, bool, bool) const build_msan_public/./src/Interpreters/ExpressionActions.cpp:746:13
    #12 0x5d68e7ef973d in DB::ExpressionTransform::transform(DB::Chunk&) build_msan_public/./src/Processors/Transforms/ExpressionTransform.cpp:23:17
    #13 0x5d68d241f0a0 in DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) build_msan_public/./src/Processors/ISimpleTransform.h:32:9
    #14 0x5d68e752c39d in DB::ISimpleTransform::work() build_msan_public/./src/Processors/ISimpleTransform.cpp:89:9
    #15 0x5d68e759be76 in DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*) build_msan_public/./src/Processors/Executors/ExecutionThreadContext.cpp:47:26
    #16 0x5d68e759be76 in DB::ExecutionThreadContext::executeTask() build_msan_public/./src/Processors/Executors/ExecutionThreadContext.cpp:95:9
    #17 0x5d68e756b546 in DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) build_msan_public/./src/Processors/Executors/PipelineExecutor.cpp:273:26
    #18 0x5d68e756b546 in DB::PipelineExecutor::executeSingleThread(unsigned long) build_msan_public/./src/Processors/Executors/PipelineExecutor.cpp:239:5
    #19 0x5d68e75677e3 in DB::PipelineExecutor::executeImpl(unsigned long, bool) build_msan_public/./src/Processors/Executors/PipelineExecutor.cpp:411:9
    #20 0x5d68e7567247 in DB::PipelineExecutor::execute(unsigned long, bool) build_msan_public/./src/Processors/Executors/PipelineExecutor.cpp:111:9
    #21 0x5d68e756349e in DB::CompletedPipelineExecutor::execute() build_msan_public/./src/Processors/Executors/CompletedPipelineExecutor.cpp:110:18
    #22 0x5d68e354ad95 in DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (DB::QueryResultDetails const&)>, DB::QueryFlags, std::__1::optional<DB::FormatSettings> const&, std::__1::function<void (DB::IOutputFormat&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context const> const&, std::__1::optional<DB::FormatSettings> const&)>) build_msan_public/./src/Interpreters/executeQuery.cpp:1596:22

SUMMARY: MemorySanitizer: use-of-uninitialized-value (/mnt/ch/ClickHouse/build_msan_public/programs/clickhouse+0x8b5222e) (BuildId: d4f4e861ed3df660a192b3c3f8b27ff8e4865fb8) in void DB::writeAnyEscapedString<(char)39, false, true>(char const*, char const*, DB::WriteBuffer&)
Exiting
2024.04.19 13:39:55.022309 [ 31893 ] {} <Trace> BaseDaemon: Received signal -3
2024.04.19 13:39:55.023071 [ 32570 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2024.04.19 13:39:55.023425 [ 32570 ] {} <Fatal> BaseDaemon: (version 24.4.1.1, build id: D4F4E861ED3DF660A192B3C3F8B27FF8E4865FB8, git hash: c83fc0b2805767cf08885e1730bae19432f5d25f) (from thread 32557) Received signal -3
2024.04.19 13:39:55.023631 [ 32570 ] {} <Fatal> BaseDaemon: Signal description: sanitizer trap
2024.04.19 13:39:55.023806 [ 32570 ] {} <Fatal> BaseDaemon: Sanitizer trap.
2024.04.19 13:39:55.023989 [ 32570 ] {} <Fatal> BaseDaemon: Stack trace: 0x00005d68cc27a45b 0x00005d68cca54e9d 0x00005d68cca4c24f 0x00005d68b525e4d6 0x00005d68b526fa33 0x00005d68b652a22f 0x00005d68ded3b368 0x00005d68e7dfc164 0x00005d68e75c4567 0x00005d68e75c3d8e 0x00005d68e7b0009a 0x00005d68e7b02f43 0x00005d68cc42358f 0x00005d68cc42e253 0x00005d68cc42e05f 0x00005d68cc41abcb 0x00005d68cc42824b 0x0000785156e94ac3 0x0000785156f26850
2024.04.19 13:39:55.024167 [ 32570 ] {} <Fatal> BaseDaemon: ########################################
2024.04.19 13:39:55.024326 [ 32570 ] {} <Fatal> BaseDaemon: (version 24.4.1.1, build id: D4F4E861ED3DF660A192B3C3F8B27FF8E4865FB8, git hash: c83fc0b2805767cf08885e1730bae19432f5d25f) (from thread 32557) (query_id: ba360351-0a5d-4957-947c-98b8fd92833f) (query: SELECT formatRow('JSONEachRow', number) as test FROM (SELECT number FROM numbers(15))) Received signal sanitizer trap (-3)
2024.04.19 13:39:55.024468 [ 32570 ] {} <Fatal> BaseDaemon: Sanitizer trap.
2024.04.19 13:39:55.024592 [ 32570 ] {} <Fatal> BaseDaemon: Stack trace: 0x00005d68cc27a45b 0x00005d68cca54e9d 0x00005d68cca4c24f 0x00005d68b525e4d6 0x00005d68b526fa33 0x00005d68b652a22f 0x00005d68ded3b368 0x00005d68e7dfc164 0x00005d68e75c4567 0x00005d68e75c3d8e 0x00005d68e7b0009a 0x00005d68e7b02f43 0x00005d68cc42358f 0x00005d68cc42e253 0x00005d68cc42e05f 0x00005d68cc41abcb 0x00005d68cc42824b 0x0000785156e94ac3 0x0000785156f26850
2024.04.19 13:39:55.296821 [ 32570 ] {} <Fatal> BaseDaemon: 0. ./build_msan_public/./src/Common/StackTrace.cpp:347: StackTrace::tryCapture() @ 0x000000001e8a245b
2024.04.19 13:39:56.000217 [ 32526 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 639.44 MiB, peak 639.44 MiB, free memory in arenas 0.00 B, will set to 658.94 MiB (RSS), difference: 19.50 MiB
2024.04.19 13:39:56.049736 [ 32570 ] {} <Fatal> BaseDaemon: 1. ./src/Common/StackTrace.h:47: StackTrace::StackTrace() @ 0x000000001f07ce9d
2024.04.19 13:39:56.707582 [ 32570 ] {} <Fatal> BaseDaemon: 2. ./build_msan_public/./src/Daemon/BaseDaemon.cpp:586: sanitizerDeathCallback() @ 0x000000001f07424f
```
