### ISSUE TITLE
clickhouse python client insert big arrow table  error

### ISSUE THREAD

**Issue by a819721810** [ClickHouse/ClickHouse#63009]
> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).
24.4.1.173 official build

insert arrow use python client , show error:
show TimeOutError:
```
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\python311\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Anaconda3\envs\python311\Lib\site-packages\urllib3\connectionpool.py", line 496, in _make_request
    conn.request(
  File "D:\ProgramData\Anaconda3\envs\python311\Lib\site-packages\urllib3\connection.py", line 409, in request
    self.send(chunk)
  File "D:\ProgramData\Anaconda3\envs\python311\Lib\http\client.py", line 1002, in send
    self.sock.sendall(data)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\python311\Lib\site-packages\clickhouse_connect\driver\httpclient.py", line 413, in _raw_request
    response = self.http.request(method, url, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Anaconda3\envs\python311\Lib\site-packages\urllib3\_request_methods.py", line 118, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Anaconda3\envs\python311\Lib\site-packages\urllib3\_request_methods.py", line 217, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Anaconda3\envs\python311\Lib\site-packages\urllib3\poolmanager.py", line 443, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Anaconda3\envs\python311\Lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Anaconda3\envs\python311\Lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Anaconda3\envs\python311\Lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "D:\ProgramData\Anaconda3\envs\python311\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Anaconda3\envs\python311\Lib\site-packages\urllib3\connectionpool.py", line 496, in _make_request
    conn.request(
  File "D:\ProgramData\Anaconda3\envs\python311\Lib\site-packages\urllib3\connection.py", line 409, in request
    self.send(chunk)
  File "D:\ProgramData\Anaconda3\envs\python311\Lib\http\client.py", line 1002, in send
    self.sock.sendall(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', TimeoutError('timed out'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\共享资料\CATOCB\Multi_ZB_SZ_WT.py", line 252, in <module>
    main()
  File "D:\共享资料\CATOCB\Multi_ZB_SZ_WT.py", line 246, in main
    process(date_str)
  File "D:\共享资料\CATOCB\Multi_ZB_SZ_WT.py", line 213, in process
    cb_client.upload_arrow(table, "zb_mm_local", "stock_base")
  File "D:\ProgramData\Anaconda3\envs\python311\Lib\site-packages\ruogu\date_base\chdb_cluster.py", line 127, in upload_arrow
    res = client.insert_arrow(table_name, arrow, database)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Anaconda3\envs\python311\Lib\site-packages\clickhouse_connect\driver\client.py", line 606, in insert_arrow
    return self.raw_insert(full_table, column_names, insert_block, settings, 'Arrow')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Anaconda3\envs\python311\Lib\site-packages\clickhouse_connect\driver\httpclient.py", line 284, in raw_insert
    response = self._raw_request(insert_block, params, headers, server_wait=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Anaconda3\envs\python311\Lib\site-packages\clickhouse_connect\driver\httpclient.py", line 424, in _raw_request
    raise OperationalError(f'Error {ex} executing HTTP request attempt {attempts} {self.url}') from ex
clickhouse_connect.driver.exceptions.OperationalError: Error ('Connection aborted.', TimeoutError('timed out')) executing HTTP request attempt 1 http://chdb.ruogu.work:8123
```

**Enable crash reporting**

2024.04.26 10:23:22.096088 [ 145006 ] {81f9124f-8ddc-48eb-bb7b-b51b0a22e22b} <Error> DynamicQueryHandler: Code: 33. DB::Exception: Unexpected EOF, got 4294967294 of 7474276266 bytes: While executing ArrowBlockInputFormat. (CANNOT_READ_ALL_DATA), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c8acb9b
1. DB::Exception::Exception<unsigned long&, unsigned long const&>(int, FormatStringHelperImpl<std::type_identity<unsigned long&>::type, std::type_identity<unsigned long const&>::type>, unsigned long&, unsigned long const&) @ 0x00000000081d8a98
2. DB::LimitReadBuffer::nextImpl() @ 0x000000000ca8f946
3. DB::(anonymous namespace)::ReadBufferWrapper<std::nullptr_t>::nextImpl() (.3a27af6be19a0553989b6b5ce4ae753b) @ 0x000000000fa5becc
4. DB::(anonymous namespace)::ReadBufferWrapper<std::nullptr_t>::nextImpl() (.3a27af6be19a0553989b6b5ce4ae753b) @ 0x000000000fa5becc
5. DB::ConcatReadBuffer::nextImpl() @ 0x000000001014ec06
6. DB::(anonymous namespace)::ReadBufferWrapper<std::nullptr_t>::nextImpl() (.3a27af6be19a0553989b6b5ce4ae753b) @ 0x000000000fa5becc
7. DB::ConcatReadBuffer::nextImpl() @ 0x000000001014ec06
8. DB::(anonymous namespace)::copyDataImpl(DB::ReadBuffer&, DB::WriteBuffer&, bool, unsigned long, std::atomic<int> const*, std::shared_ptr<DB::Throttler>) (.llvm.11379089755201849936) @ 0x000000000c930d06
9. DB::asArrowFileLoadIntoMemory(DB::ReadBuffer&, std::atomic<int>&, String const&, String const&) @ 0x0000000012414967
10. DB::createFileReader(DB::ReadBuffer&, DB::FormatSettings const&, std::atomic<int>&) @ 0x00000000123f6b57
11. DB::ArrowBlockInputFormat::prepareReader() @ 0x00000000123f5bca
12. DB::ArrowBlockInputFormat::read() @ 0x00000000123f5339
13. DB::IInputFormat::generate() @ 0x00000000123ec636
14. DB::ISource::tryGenerate() @ 0x00000000123c8015
15. DB::ISource::work() @ 0x00000000123c7aa2
16. DB::ExecutionThreadContext::executeTask() @ 0x00000000123e2cda
17. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x00000000123d7230
18. DB::PipelineExecutor::execute(unsigned long, bool) @ 0x00000000123d66a1
19. DB::CompletedPipelineExecutor::execute() @ 0x00000000123d4e32
20. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::shared_ptr<DB::Context>, std::function<void (DB::QueryResultDetails const&)>, DB::QueryFlags, std::optional<DB::FormatSettings> const&, std::function<void (DB::IOutputFormat&)>) @ 0x000000001127fcfb
21. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional<DB::CurrentThread::QueryScope>&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x0000000012305a55
22. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x000000001230a514
23. DB::HTTPServerConnection::run() @ 0x0000000012389aba
24. Poco::Net::TCPServerConnection::start() @ 0x0000000014caedb2
25. Poco::Net::TCPServerDispatcher::run() @ 0x0000000014cafbf9
26. Poco::PooledThread::run() @ 0x0000000014da8361
27. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000014da68fd
28. ? @ 0x00007ff7b784aac3
29. ? @ 0x00007ff7b78dc850
 (version 24.4.1.173 (official build))
2024.04.26 10:23:22.096158 [ 145006 ] {81f9124f-8ddc-48eb-bb7b-b51b0a22e22b} <Error> DynamicQueryHandler: Cannot send exception to client: Code: 33. DB::Exception: Unexpected EOF, got 4294969368 of 7474276266 bytes. (CANNOT_READ_ALL_DATA), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c8acb9b
1. DB::Exception::Exception<unsigned long&, unsigned long const&>(int, FormatStringHelperImpl<std::type_identity<unsigned long&>::type, std::type_identity<unsigned long const&>::type>, unsigned long&, unsigned long const&) @ 0x00000000081d8a98
2. DB::LimitReadBuffer::nextImpl() @ 0x000000000ca8f946
3. DB::HTTPHandler::formatExceptionForClient(int, DB::HTTPServerRequest&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x0000000012308a67
4. DB::HTTPHandler::trySendExceptionToClient(String const&, int, DB::HTTPServerRequest&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x00000000123084ef
5. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x000000001230badb
6. DB::HTTPServerConnection::run() @ 0x0000000012389aba
7. Poco::Net::TCPServerConnection::start() @ 0x0000000014caedb2
8. Poco::Net::TCPServerDispatcher::run() @ 0x0000000014cafbf9
9. Poco::PooledThread::run() @ 0x0000000014da8361
10. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000014da68fd
11. ? @ 0x00007ff7b784aac3
12. ? @ 0x00007ff7b78dc850
 (version 24.4.1.173 (official build))

**How to reproduce**
i use clickhouse-connect (python client) insert arrow( 72488478 rows) to clickhouse local table
```
client = clickhouse_connect.get_client(**self.connection_config)
res = client.insert_arrow("zb_mm_local", arrow, "stock_base")
```
when len(arrow) is 72488478 , then timeout, use old version clickhouse  23.12.1.553 is ok

i splite arrow to 5 piece, also ok:
```
total_rows = len(table)
chunk_size = total_rows // 5
chunks = [table.slice(i * chunk_size, (i + 1) * chunk_size) if i < 4 else table.slice(i * chunk_size, total_rows)
              for i in range(5)]
for i, chunk in enumerate(chunks):
cb_client.insert_arrow("zb_mm_local",chunk, "stock_base")
```

* `CREATE TABLE` statements for all tables involved
```
CREATE TABLE stock_base.zb_mm_local
(

    `code` String ,

    `date` Date ,

    `date_time` DateTime64(3,
 'Asia/Shanghai'),

    `exg` UInt8 ,

    `time_int` Int32 ,

    `price` Nullable(Float64) ,

    `volume` Nullable(Int64) ,

    `side` FixedString(1),

    `type` FixedString(1),

    `trade_flag` FixedString(1) ,

    `chno` UInt64 ,

    `bidno` Nullable(Int64) ,

    `askno` Nullable(Int64) ,

    `ordno` Nullable(Int64) ,

    `seqno` UInt64
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{uuid}/{shard}',
 '{replica}')
PARTITION BY toYYYYMM(date)
PRIMARY KEY (date,
 code,
 exg)
ORDER BY (date,
 code,
 exg,
 date_time,
 chno,
 seqno)
SETTINGS index_granularity = 8192

```
* Sample data for all these tables, use [clickhouse-obfuscator]
INSERT INTO zb_mm_local (`code`, `date`, `date_time`, `exg`, `time_int`, `price`, `volume`, `side`, `type`, `trade_flag`, `chno`, `bidno`, `askno`, `ordno`, `seqno`) VALUES ('002725', '2024-04-25', '2024-04-25 13:02:06.820', 1, 46926820, 0, 10000, '\0', '\0', '4', 2011, 0, 22748150, 22792748, 22792748), ('002725', '2024-04-25', '2024-04-25 13:02:09.660', 1, 46929660, 8.8, 500, 'S', '2', '\0', 2011, 0, 0, 22802220, 22802220), ('002725', '2024-04-25', '2024-04-25 13:02:09.660', 1, 46929660, 8.8, 100, '\0', '\0', 'F', 2011, 20489457, 22802220, 22802221, 22802221)
;

**Expected behavior**
insert success

**Comment by a819721810** [comment]
> Is this the same as #62952?
yes，all me,  i think is bug, i use old clickhouse version, is ok

**Comment by a819721810** [comment]
@Algunenano  hi,  can you be reproducible ?

**Comment by a819721810** [comment]
@Algunenano  hi， i find this problem.  clickhouse python client timeout  default is 10 second . thx
