### ISSUE TITLE
Crash in FunctionArrayElement

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#63468]
Report: https://s3.amazonaws.com/clickhouse-test-reports/59940/34a9ec3bb1d3f6d54b6f2737a28dc75dc7849e99/ast_fuzzer__tsan_.html

```
CREATE TABLE t_break_line
(
    `id` UInt64,
    `value` String,
    `value1` String
)
ENGINE = MergeTree
ORDER BY id
```

```
SELECT
    [[65536, [[[9][1], 1][1]][1]][1]],
    [[[[materialize(9)][toLowCardinality(1)]][1]][1]],
    [[9][1], [[[[65536][materialize(toNullable(toLowCardinality(1)))]][1], 1][1]][1]][toNullable(1)],
    [[[1, [[[toInt128(65536)][1]][1]][materialize(1)], [9, 9, toLowCardinality(65536)][1], toNullable(1)][toNullable(1)]][1], 1, materialize(1)],
    [[[[1][toNullable(toLowCardinality(1))]][materialize(toLowCardinality(1))]][1], 9]
FROM t_break_line
ORDER BY [1][materialize(toLowCardinality(1))] DESC NULLS FIRST
FORMAT PrettyMonoBlock
```

Under MSAN (1 week old):
```
==165379==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x55558d9adc91 in DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>::t_start() const build_msan/./src/Common/PODArray.h:315:83
    #1 0x55558d9adc91 in DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>::operator[](long) const build_msan/./src/Common/PODArray.h:383:16
    #2 0x55558d9adc91 in DB::ColumnNullable::insertFrom(DB::IColumn const&, unsigned long) build_msan/./src/Columns/ColumnNullable.cpp:231:32
    #3 0x555573a5770b in COW<DB::IColumn>::immutable_ptr<DB::IColumn> DB::(anonymous namespace)::FunctionArrayElement::executeConst<char8_t>(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul> const&, DB::(anonymous namespace)::ArrayImpl::NullMapBuilder&, unsigned long) arrayElement.cpp
    #4 0x555573899aa5 in DB::(anonymous namespace)::FunctionArrayElement::perform(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, DB::(anonymous namespace)::ArrayImpl::NullMapBuilder&, unsigned long) const arrayElement.cpp
    #5 0x555573861634 in DB::(anonymous namespace)::FunctionArrayElement::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const arrayElement.cpp
    #6 0x55555d39dae1 in DB::IFunction::executeImplDryRun(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0x7e49ae1) (BuildId: ff1307260fdef0e7e7c09edb4904954e7582b16f)
    #7 0x55555e6ea9f7 in DB::FunctionToExecutableFunctionAdaptor::executeDryRunImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0x91969f7) (BuildId: ff1307260fdef0e7e7c09edb4904954e7582b16f)
    #8 0x5555862e2817 in DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_msan/./src/Functions/IFunction.cpp:246:15
    #9 0x5555862e6ef5 in DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_msan/./src/Functions/IFunction.cpp:281:24
    #10 0x5555862eb25c in DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_msan/./src/Functions/IFunction.cpp:378:16
    #11 0x555588ef22c5 in DB::executeActionForPartialResult(DB::ActionsDAG::Node const*, std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>>, unsigned long) build_msan/./src/Interpreters/ActionsDAG.cpp:662:49
    #12 0x555588ef22c5 in DB::ActionsDAG::evaluatePartialResult(std::__1::unordered_map<DB::ActionsDAG::Node const*, DB::ColumnWithTypeAndName, std::__1::hash<DB::ActionsDAG::Node const*>, std::__1::equal_to<DB::ActionsDAG::Node const*>, std::__1::allocator<std::__1::pair<DB::ActionsDAG::Node const* const, DB::ColumnWithTypeAndName>>>&, std::__1::vector<DB::ActionsDAG::Node const*, std::__1::allocator<DB::ActionsDAG::Node const*>> const&, unsigned long, bool) build_msan/./src/Interpreters/ActionsDAG.cpp:829:48
    #13 0x555588eed4f9 in DB::ActionsDAG::updateHeader(DB::Block) const build_msan/./src/Interpreters/ActionsDAG.cpp:739:26
```

**Comment by Algunenano** [comment]
Still reproduces. Seems related to const parameters `FunctionArrayElement::executeConst<char8_t>` during the analysis phase (`executeImplDryRun`)

**Comment by rschu1ze** [comment]
Dups #61659
