### ISSUE TITLE
`test_move_partition_throttling` santizier assert

### ISSUE THREAD

**Issue by alesapin** [ClickHouse/ClickHouse#63597]
Repro: https://s3.amazonaws.com/clickhouse-test-reports/63353/ff810ceb39a5a5942617bc453854dfc49c9cbb19/stress_test__asan_.html

```
=================================================================
==3336==ERROR: AddressSanitizer: stack-use-after-return on address 0x7f8c3b1dd020 at pc 0x55ac4a9cad0f bp 0x7f8e0e1c5a10 sp 0x7f8e0e1c5a08
READ of size 16 at 0x7f8c3b1dd020 thread T799 (ThreadPool)
    #0 0x55ac4a9cad0e in std::__1::shared_ptr<DB::Throttler>::shared_ptr[abi:v15000](std::__1::shared_ptr<DB::Throttler> const&) build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:593:22
    #1 0x55ac4a9cad0e in DB::WriteSettings::WriteSettings(DB::WriteSettings const&) build_docker/./src/IO/WriteSettings.h:10:8
    #2 0x55ac4a9cad0e in DB::WriteSettings DB::updateResourceLink<DB::WriteSettings>(DB::WriteSettings const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) build_docker/./src/Disks/ObjectStorages/DiskObjectStorage.cpp:459:16
    #3 0x55ac4a9cad0e in DB::DiskObjectStorage::writeFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, unsigned long, DB::WriteMode, DB::WriteSettings const&) build_docker/./src/Disks/ObjectStorages/DiskObjectStorage.cpp:508:36
    #4 0x55ac4a955d79 in DB::IDisk::copyFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, DB::IDisk&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, DB::ReadSettings const&, DB::WriteSettings const&, std::__1::function<void ()> const&) build_docker/./src/Disks/IDisk.cpp:40:24
    #5 0x55ac4a961371 in DB::asyncCopy(DB::IDisk&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, DB::IDisk&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>&, std::__1::vector<std::__1::future<void>, std::__1::allocator<std::__1::future<void>>>&, bool, DB::ReadSettings const&, DB::WriteSettings const&, std::__1::function<void ()> const&)::$_0::operator()() const build_docker/./src/Disks/IDisk.cpp:117:31
    #6 0x55ac4a961371 in decltype(std::declval<DB::asyncCopy(DB::IDisk&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, DB::IDisk&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>&, std::__1::vector<std::__1::future<void>, std::__1::allocator<std::__1::future<void>>>&, bool, DB::ReadSettings const&, DB::WriteSettings const&, std::__1::function<void ()> const&)::$_0&>()()) std::__1::__invoke[abi:v15000]<DB::asyncCopy(DB::IDisk&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, DB::IDisk&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>&, std::__1::vector<std::__1::future<void>, std::__1::allocator<std::__1::future<void>>>&, bool, DB::ReadSettings const&, DB::WriteSettings const&, std::__1::function<void ()> const&)::$_0&>(DB::asyncCopy(DB::IDisk&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, DB::IDisk&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>&, std::__1::vector<std::__1::future<void>, std::__1::allocator<std::__1::future<void>>>&, bool, DB::ReadSettings const&, DB::WriteSettings const&, std::__1::function<void ()> const&)::$_0&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #7 0x55ac4a961371 in void std::__1::__invoke_void_return_wrapper<void, true>::__call<DB::asyncCopy(DB::IDisk&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, DB::IDisk&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>&, std::__1::vector<std::__1::future<void>, std::__1::allocator<std::__1::future<void>>>&, bool, DB::ReadSettings const&, DB::WriteSettings const&, std::__1::function<void ()> const&)::$_0&>(DB::asyncCopy(DB::IDisk&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, DB::IDisk&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>&, std::__1::vector<std::__1::future<void>, std::__1::allocator<std::__1::future<void>>>&, bool, DB::ReadSettings const&, DB::WriteSettings const&, std::__1::function<void ()> const&)::$_0&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:479:9
    #8 0x55ac4a961371 in std::__1::__function::__default_alloc_func<DB::asyncCopy(DB::IDisk&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, DB::IDisk&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>&, std::__1::vector<std::__1::future<void>, std::__1::allocator<std::__1::future<void>>>&, bool, DB::ReadSettings const&, DB::WriteSettings const&, std::__1::function<void ()> const&)::$_0, void ()>::operator()[abi:v15000]() build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:235:12
    #9 0x55ac4a961371 in void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::asyncCopy(DB::IDisk&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, DB::IDisk&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>&, std::__1::vector<std::__1::future<void>, std::__1::allocator<std::__1::future<void>>>&, bool, DB::ReadSettings const&, DB::WriteSettings const&, std::__1::function<void ()> const&)::$_0, void ()>>(std::__1::__function::__policy_storage const*) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716:16
    #10 0x55ac3b82ad3a in std::__1::__function::__policy_func<void ()>::operator()[abi:v15000]() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:848:16
    #11 0x55ac3b82ad3a in std::__1::function<void ()>::operator()() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:1187:12
    #12 0x55ac3b82ad3a in ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::worker(std::__1::__list_iterator<ThreadFromGlobalPoolImpl<false, true>, void*>) build_docker/./src/Common/ThreadPool.cpp:458:13
    #13 0x55ac3b83481c in void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const build_docker/./src/Common/ThreadPool.cpp:220:73
    #14 0x55ac3b83481c in decltype(std::declval<void>()()) std::__1::__invoke[abi:v15000]<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()&>(void&&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #15 0x55ac3b83481c in decltype(auto) std::__1::__apply_tuple_impl[abi:v15000]<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()&, std::__1::tuple<>&>(void&&, std::__1::tuple<>&, std::__1::__tuple_indices<>) build_docker/./contrib/llvm-project/libcxx/include/tuple:1789:1
    #16 0x55ac3b83481c in decltype(auto) std::__1::apply[abi:v15000]<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()&, std::__1::tuple<>&>(void&&, std::__1::tuple<>&) build_docker/./contrib/llvm-project/libcxx/include/tuple:1798:1
    #17 0x55ac3b83481c in ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'()::operator()() build_docker/./src/Common/ThreadPool.h:246:13
    #18 0x55ac3b8229cc in std::__1::__function::__policy_func<void ()>::operator()[abi:v15000]() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:848:16
    #19 0x55ac3b8229cc in std::__1::function<void ()>::operator()() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:1187:12
    #20 0x55ac3b8229cc in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) build_docker/./src/Common/ThreadPool.cpp:458:13
    #21 0x55ac3b82fe4c in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const build_docker/./src/Common/ThreadPool.cpp:220:73
    #22 0x55ac3b82fe4c in decltype(std::declval<void>()()) std::__1::__invoke[abi:v15000]<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #23 0x55ac3b82fe4c in void std::__1::__thread_execute[abi:v15000]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>&, std::__1::__tuple_indices<>) build_docker/./contrib/llvm-project/libcxx/include/thread:284:5
    #24 0x55ac3b82fe4c in void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) build_docker/./contrib/llvm-project/libcxx/include/thread:295:5
    #25 0x55ac295f465a in asan_thread_start(void*) crtstuff.c
    #26 0x7f92d2d45ac2  (/lib/x86_64-linux-gnu/libc.so.6+0x94ac2) (BuildId: c289da5071a3399de893d2af81d6a30c62646e1e)
    #27 0x7f92d2dd784f  (/lib/x86_64-linux-gnu/libc.so.6+0x12684f) (BuildId: c289da5071a3399de893d2af81d6a30c62646e1e)

Address 0x7f8c3b1dd020 is located in stack of thread T1096 (TCPHandler) at offset 32 in frame
    #0 0x55ac4a95af4f in DB::IDisk::copyThroughBuffers(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::IDisk> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool, DB::ReadSettings const&, DB::WriteSettings, std::__1::function<void ()> const&) build_docker/./src/Disks/IDisk.cpp:151

  This frame has 4 object(s):
    [32, 96) 'write_settings.byval' <== Memory access at offset 32 is inside this variable
    [128, 152) 'results' (line 152)
    [192, 216) 'agg.tmp'
    [256, 280) 'agg.tmp2'
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
Thread T1096 (TCPHandler) created by T773 here:
    #0 0x55ac295dc3ed in pthread_create (/usr/bin/clickhouse+0xaa073ed) (BuildId: 826640a5be3fcb0d63de48d1aace23233911a4ab)
    #1 0x55ac59560d52 in Poco::ThreadImpl::startImpl(Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable>>) build_docker/./base/poco/Foundation/src/Thread_POSIX.cpp:198:6
    #2 0x55ac59564261 in Poco::Thread::start(Poco::Runnable&) build_docker/./base/poco/Foundation/src/Thread.cpp:118:2
    #3 0x55ac5956cee7 in Poco::PooledThread::start() build_docker/./base/poco/Foundation/src/ThreadPool.cpp:78:10
    #4 0x55ac5956cee7 in Poco::ThreadPool::getThread() build_docker/./base/poco/Foundation/src/ThreadPool.cpp:446:14
    #5 0x55ac5956d617 in Poco::ThreadPool::startWithPriority(Poco::Thread::Priority, Poco::Runnable&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) build_docker/./base/poco/Foundation/src/ThreadPool.cpp:350:2
    #6 0x55ac5915b8a1 in Poco::Net::TCPServerDispatcher::enqueue(Poco::Net::StreamSocket const&) build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:153:17
    #7 0x55ac59159856 in Poco::Net::TCPServer::run() build_docker/./base/poco/Net/src/TCPServer.cpp:148:21
    #8 0x55ac59561b47 in Poco::ThreadImpl::runnableEntry(void*) build_docker/./base/poco/Foundation/src/Thread_POSIX.cpp:335:27
    #9 0x55ac295f465a in asan_thread_start(void*) crtstuff.c

Thread T773 created by T0 here:
    #0 0x55ac295dc3ed in pthread_create (/usr/bin/clickhouse+0xaa073ed) (BuildId: 826640a5be3fcb0d63de48d1aace23233911a4ab)
    #1 0x55ac59560d52 in Poco::ThreadImpl::startImpl(Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable>>) build_docker/./base/poco/Foundation/src/Thread_POSIX.cpp:198:6
    #2 0x55ac59564261 in Poco::Thread::start(Poco::Runnable&) build_docker/./base/poco/Foundation/src/Thread.cpp:118:2
    #3 0x55ac3badc659 in DB::ProtocolServerAdapter::start() build_docker/./src/Server/ProtocolServerAdapter.h:31:26
    #4 0x55ac3badc659 in DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) build_docker/./programs/server/Server.cpp:2100:24
    #5 0x55ac591945be in Poco::Util::Application::run() build_docker/./base/poco/Util/src/Application.cpp:315:8
    #6 0x55ac3baa8aa3 in DB::Server::run() build_docker/./programs/server/Server.cpp:419:25
    #7 0x55ac591d8e68 in Poco::Util::ServerApplication::run(int, char**) build_docker/./base/poco/Util/src/ServerApplication.cpp:131:9
    #8 0x55ac3baa0b6a in mainEntryClickHouseServer(int, char**) build_docker/./programs/server/Server.cpp:225:20
    #9 0x55ac2962e61e in main build_docker/./programs/main.cpp:502:21
    #10 0x7f92d2cdad8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: c289da5071a3399de893d2af81d6a30c62646e1e)

SUMMARY: AddressSanitizer: stack-use-after-return build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:593:22 in std::__1::shared_ptr<DB::Throttler>::shared_ptr[abi:v15000](std::__1::shared_ptr<DB::Throttler> const&)
Shadow bytes around the buggy address:
  0x7f8c3b1dcd80: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f8c3b1dce00: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f8c3b1dce80: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f8c3b1dcf00: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f8c3b1dcf80: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
=>0x7f8c3b1dd000: f5 f5 f5 f5[f5]f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f8c3b1dd080: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f8c3b1dd100: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f8c3b1dd180: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f8c3b1dd200: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f8c3b1dd280: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
Thread T799 (ThreadPool) created by T4 (TCPHandler) here:
    #0 0x55ac295dc3ed in pthread_create (/usr/bin/clickhouse+0xaa073ed) (BuildId: 826640a5be3fcb0d63de48d1aace23233911a4ab)
    #1 0x55ac3b82da58 in std::__1::__libcpp_thread_create[abi:v15000](unsigned long*, void* (*)(void*), void*) build_docker/./contrib/llvm-project/libcxx/include/__threading_support:376:10
    #2 0x55ac3b82da58 in std::__1::thread::thread<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'(), void>(void&&) build_docker/./contrib/llvm-project/libcxx/include/thread:311:16
    #3 0x55ac3b81f80b in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool) build_docker/./src/Common/ThreadPool.cpp:220:35
    #4 0x55ac3b833eb7 in ThreadPoolImpl<std::__1::thread>::scheduleOrThrow(std::__1::function<void ()>, Priority, unsigned long, bool) build_docker/./src/Common/ThreadPool.cpp:291:5
    #5 0x55ac3b833eb7 in ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&) build_docker/./src/Common/ThreadPool.h:218:38
    #6 0x55ac3b825523 in void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool) build_docker/./src/Common/ThreadPool.cpp:220:35
    #7 0x55ac3b824bea in ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleOrThrowOnError(std::__1::function<void ()>, Priority) build_docker/./src/Common/ThreadPool.cpp:279:5
    #8 0x55ac516fd093 in DB::PipelineExecutor::spawnThreads() build_docker/./src/Processors/Executors/PipelineExecutor.cpp:360:15
    #9 0x55ac516f8eb2 in DB::PipelineExecutor::executeImpl(unsigned long, bool) build_docker/./src/Processors/Executors/PipelineExecutor.cpp:404:9
    #10 0x55ac516f889e in DB::PipelineExecutor::execute(unsigned long, bool) build_docker/./src/Processors/Executors/PipelineExecutor.cpp:111:9
    #11 0x55ac516f52b4 in DB::CompletedPipelineExecutor::execute() build_docker/./src/Processors/Executors/CompletedPipelineExecutor.cpp:110:18
    #12 0x55ac4df54f01 in DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (DB::QueryResultDetails const&)>, DB::QueryFlags, std::__1::optional<DB::FormatSettings> const&, std::__1::function<void (DB::IOutputFormat&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context const> const&, std::__1::optional<DB::FormatSettings> const&)>) build_docker/./src/Interpreters/executeQuery.cpp:1621:22
    #13 0x55ac5146cfb5 in DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) build_docker/./src/Server/HTTPHandler.cpp:937:5
    #14 0x55ac5147b3d0 in DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) build_docker/./src/Server/HTTPHandler.cpp:1144:9
    #15 0x55ac51601c73 in DB::HTTPServerConnection::run() build_docker/./src/Server/HTTP/HTTPServerConnection.cpp:70:34
    #16 0x55ac59159fae in Poco::Net::TCPServerConnection::start() build_docker/./base/poco/Net/src/TCPServerConnection.cpp:43:3
    #17 0x55ac5915ac56 in Poco::Net::TCPServerDispatcher::run() build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:115:20
    #18 0x55ac59568b5b in Poco::PooledThread::run() build_docker/./base/poco/Foundation/src/ThreadPool.cpp:188:14
    #19 0x55ac59561b47 in Poco::ThreadImpl::runnableEntry(void*) build_docker/./base/poco/Foundation/src/Thread_POSIX.cpp:335:27
    #20 0x55ac295f465a in asan_thread_start(void*) crtstuff.c

Thread T4 (TCPHandler) created by T0 here:
    #0 0x55ac295dc3ed in pthread_create (/usr/bin/clickhouse+0xaa073ed) (BuildId: 826640a5be3fcb0d63de48d1aace23233911a4ab)
    #1 0x55ac59560d52 in Poco::ThreadImpl::startImpl(Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable>>) build_docker/./base/poco/Foundation/src/Thread_POSIX.cpp:198:6
    #2 0x55ac59564261 in Poco::Thread::start(Poco::Runnable&) build_docker/./base/poco/Foundation/src/Thread.cpp:118:2
    #3 0x55ac595695c9 in Poco::PooledThread::start() build_docker/./base/poco/Foundation/src/ThreadPool.cpp:78:10
    #4 0x55ac595695c9 in Poco::ThreadPool::ThreadPool(int, int, int, int) build_docker/./base/poco/Foundation/src/ThreadPool.cpp:237:12
    #5 0x55ac3bab1f89 in DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) build_docker/./programs/server/Server.cpp:724:22
    #6 0x55ac591945be in Poco::Util::Application::run() build_docker/./base/poco/Util/src/Application.cpp:315:8
    #7 0x55ac3baa8aa3 in DB::Server::run() build_docker/./programs/server/Server.cpp:419:25
    #8 0x55ac591d8e68 in Poco::Util::ServerApplication::run(int, char**) build_docker/./base/poco/Util/src/ServerApplication.cpp:131:9
    #9 0x55ac3baa0b6a in mainEntryClickHouseServer(int, char**) build_docker/./programs/server/Server.cpp:225:20
    #10 0x55ac2962e61e in main build_docker/./programs/main.cpp:502:21
    #11 0x7f92d2cdad8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: c289da5071a3399de893d2af81d6a30c62646e1e)

==3336==ABORTING
```

**Comment by alexey-milovidov** [comment]
@azat, please fix it, otherwise we will have to remove the "throttling of move partition" feature.

**Comment by azat** [comment]
This should be fixed by the https://github.com/ClickHouse/ClickHouse/pull/63523 already

P.S. This is not only throttling of move partition, but copying in general.
