### ISSUE TITLE
Not a bug: libunwind: aarch64: SIGSEGV signal handler leads to another seg fault

### ISSUE THREAD

**Issue by maxknv** [ClickHouse/ClickHouse#63855]
Problem can be 100% reproduced in integration tests on ARM in TCs:

1. test_crash_log/test.py::test_pkill
2. test_send_crash_reports/test.py::test_send_segfault

Stack trace:
```
#0  libunwind::CFI_Parser<libunwind::LocalAddressSpace>::parseFDEInstructions (addressSpace=..., fdeInfo=..., cieInfo=..., upToPC=<optimized out>, arch=<optimized out>, results=<optimized out>)
    at /tmp/ClickHouse/contrib/libunwind/src/DwarfParser.hpp:561
561     /tmp/ClickHouse/contrib/libunwind/src/DwarfParser.hpp: No such file or directory.
[Current thread is 1 (Thread 0xffffa8bae020 (LWP 13297))]
(gdb) bt
#0  libunwind::CFI_Parser<libunwind::LocalAddressSpace>::parseFDEInstructions (addressSpace=..., fdeInfo=..., cieInfo=..., upToPC=<optimized out>, arch=<optimized out>, results=<optimized out>)
    at /tmp/ClickHouse/contrib/libunwind/src/DwarfParser.hpp:561
#1  0x0000aaaae80afa60 in libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_arm64>::getInfoFromFdeCie (this=0xffff20832370, fdeInfo=..., cieInfo=..., pc=187651014192840, 
    dso_base=187650590556160) at /tmp/ClickHouse/contrib/libunwind/src/UnwindCursor.hpp:1614
#2  libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_arm64>::getInfoFromDwarfSection (this=0xffff20832370, pc=187651014192840, sects=..., fdeSectionOffsetHint=0)
    at /tmp/ClickHouse/contrib/libunwind/src/UnwindCursor.hpp:1689
#3  libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_arm64>::setInfoBasedOnIPRegister (this=this@entry=0xffff20832370, isReturnAddress=<optimized out>)
    at /tmp/ClickHouse/contrib/libunwind/src/UnwindCursor.hpp:2592
#4  0x0000aaaae80ae01c in __unw_init_local (cursor=0xffff20832370, context=0xffff208325e0) at /tmp/ClickHouse/contrib/libunwind/src/libunwind.cpp:91
#5  0x0000aaaae80aeed8 in unw_backtrace (buffer=0xffff208328f8, size=45) at /tmp/ClickHouse/contrib/libunwind/src/libunwind.cpp:346
#6  0x0000aaaad654cde8 in StackTrace::tryCapture (this=0xffff208328e8) at /tmp/ClickHouse/src/Common/StackTrace.cpp:347
#7  0x0000aaaad654ccbc in StackTrace::StackTrace (this=0xffff208328e8, signal_context=...) at /tmp/ClickHouse/src/Common/StackTrace.cpp:316
#8  0x0000aaaad6959244 in signalHandler (sig=11, info=0xffff20832da0, context=0xffff20832e20) at /tmp/ClickHouse/src/Daemon/BaseDaemon.cpp:154
#9  <signal handler called>
```
libunwind fork commit: 40d8eadf96b127d9b22d53ce7a4fc52aaedea965

To reproduce manually (not in tests):
1. run CH server on Aarch64 linux
2. kill -SEGV pid
3. Server crashes with segfault, No crash report will be generated `SELECT COUNT(*) FROM system.crash_log ==> 0`

**Comment by azat** [comment]
>SIGSEGV signal handler leads to another seg fault

This is normal right now, because the SIGSEGV likely happened in unwind, and later on, it tries to unwind from almost the same stack, and it crashes on the same frame

It is likely will be fixed by https://github.com/ClickHouse/ClickHouse/pull/60468

**Comment by alesapin** [comment]
@azat No, tried yesterday, didn't help.

**Comment by alesapin** [comment]
Also https://github.com/ClickHouse/ClickHouse/pull/60468 didn't help as well

**Comment by Algunenano** [comment]
Crash in libunwind - ARM64 (with today's master): https://s3.amazonaws.com/clickhouse-test-reports/64180/7123d08a692e98b71e87c3b24dde62d427ce410b/stateless_tests__aarch64_.html


https://s3.amazonaws.com/clickhouse-test-reports/64180/7123d08a692e98b71e87c3b24dde62d427ce410b/stateless_tests__aarch64_/gdb.log
```
2024-05-22 21:15:56 [Switching to Thread 0xff193f017b80 (LWP 1356)]
2024-05-22 21:15:56 0x0000aad18fb1d734 in libunwind::DwarfInstructions<libunwind::LocalAddressSpace, libunwind::Registers_arm64>::getSavedRegister (addressSpace=..., registers=..., cfa=82, savedReg=...) at ./contrib/libunwind/src/DwarfInstructions.hpp:97
2024-05-22 21:15:56 #0  0x0000aad18fb1d734 in libunwind::DwarfInstructions<libunwind::LocalAddressSpace, libunwind::Registers_arm64>::getSavedRegister (addressSpace=..., registers=..., cfa=82, savedReg=...) at ./contrib/libunwind/src/DwarfInstructions.hpp:97
2024-05-22 21:15:56 No locals.
2024-05-22 21:15:56 #1  0x0000aad18fb1c7a4 in libunwind::DwarfInstructions<libunwind::LocalAddressSpace, libunwind::Registers_arm64>::stepWithDwarf (addressSpace=..., pc=<optimized out>, fdeStart=<optimized out>, registers=..., isSignalFrame=@0xff193f013749: false) at ./contrib/libunwind/src/DwarfInstructions.hpp:245
2024-05-22 21:15:56         i = 19
2024-05-22 21:15:56         newRegisters = {_registers = {__x = {280490899732176, 280483896319936, 26, 4189926356, 280488233195648, 187816950379296, 0, 0, 280488333168348, 280488333168577, 280488333168348, 18446744073709551586, 8244231025856375905, 280488398207559, 280488263621134, 18446744073709551615, 280488398200896, 280499299515840, 280477810608968, 2135, 0, 1604, 2, 280488290875672, 5, 280488317450624, 280488317450824, 280489448082072, 1}, __fp = 2, __lr = 187816950154512, __sp = 82, __pc = 187816966201556, __ra_sign_state = 0}, _vectorHalfRegisters = {0, 1.3857745738341003e-309, 1.3857964171226594e-309, 2.4703282292062327e-323, 1.385774573833547e-309, 9.8813129168249309e-324, 1.3833838083554903e-322, 0, 0.29999999999999999, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2.6438934905902626e-319, -2.750926028454933e-277, 8.8931816251424378e-323, 1.6798231958602383e-322, 9.3872472709836843e-323, 9.3872472709836843e-323, 8.8931816251424378e-323, 4.9406564584124654e-324, 4.9406564584124654e-324, 4.9406564584124654e-324, 4.9406564584124654e-324, 4.9406564584124654e-324, 4.9406564584124654e-324, 4.9406564584124654e-324}}
2024-05-22 21:15:56         cfa = 82
2024-05-22 21:15:56         lastReg = 95
2024-05-22 21:15:56         returnAddress = 0
2024-05-22 21:15:56         prolog = {cfaRegister = 29, cfaRegisterOffset = 80, cfaExpression = 0, spExtraArgSize = 0, savedRegisters = {{location = libunwind::CFI_Parser<libunwind::LocalAddressSpace>::kRegisterUnused, initialStateSaved = false, value = 0} <repeats 19 times>, {location = libunwind::CFI_Parser<libunwind::LocalAddressSpace>::kRegisterInCFA, initialStateSaved = true, value = -8}, {location = libunwind::CFI_Parser<libunwind::LocalAddressSpace>::kRegisterInCFA, initialStateSaved = true, value = -16}, {location = libunwind::CFI_Parser<libunwind::LocalAddressSpace>::kRegisterInCFA, initialStateSaved = true, value = -24}, {location = libunwind::CFI_Parser<libunwind::LocalAddressSpace>::kRegisterInCFA, initialStateSaved = true, value = -32}, {location = libunwind::CFI_Parser<libunwind::LocalAddressSpace>::kRegisterInCFA, initialStateSaved = true, value = -40}, {location = libunwind::CFI_Parser<libunwind::LocalAddressSpace>::kRegisterInCFA, initialStateSaved = true, value = -48}, {location = libunwind::CFI_Parser<libunwind::LocalAddressSpace>::kRegisterInCFA, initialStateSaved = true, value = -64}, {location = libunwind::CFI_Parser<libunwind::LocalAddressSpace>::kRegisterUnused, initialStateSaved = false, value = 0}, {location = libunwind::CFI_Parser<libunwind::LocalAddressSpace>::kRegisterUnused, initialStateSaved = false, value = 0}, {location = libunwind::CFI_Parser<libunwind::LocalAddressSpace>::kRegisterUnused, initialStateSaved = false, value = 0}, {location = libunwind::CFI_Parser<libunwind::LocalAddressSpace>::kRegisterInCFA, initialStateSaved = true, value = -80}, {location = libunwind::CFI_Parser<libunwind::LocalAddressSpace>::kRegisterInCFA, initialStateSaved = true, value = -72}, {location = libunwind::CFI_Parser<libunwind::LocalAddressSpace>::kRegisterUnused, initialStateSaved = false, value = 0} <repeats 65 times>}}
2024-05-22 21:15:56         fdeInfo = {fdeStart = 187816778789664, fdeLength = 120, fdeInstructions = 187816778789681, pcStart = 187816966201312, pcEnd = 187816966201704, lsda = 0}
2024-05-22 21:15:56         cieInfo = {cieStart = 187816768947836, cieLength = 20, cieInstructions = 187816768947853, pointerEncoding = 27 '\033', lsdaEncoding = 255 '\377', personalityEncoding = 0 '\000', personalityOffsetInCIE = 0 '\000', personality = 0, codeAlignFactor = 1, dataAlignFactor = -4, isSignalFrame = false, fdesHaveAugmentationData = true, returnAddressRegister = 30 '\036', addressesSignedWithBKey = false}
2024-05-22 21:15:56 #2  0x0000aad18fb1b780 in libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_arm64>::stepWithDwarfFDE (this=0xff193f0134e0) at ./contrib/libunwind/src/UnwindCursor.hpp:1002
2024-05-22 21:15:56 No locals.
2024-05-22 21:15:56 #3  libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_arm64>::step (this=0xff193f0134e0) at ./contrib/libunwind/src/UnwindCursor.hpp:2849
2024-05-22 21:15:56         result = <optimized out>
2024-05-22 21:15:56 #4  __unw_step (cursor=0xff193f0134e0) at ./build_docker/./contrib/libunwind/src/libunwind.cpp:182
2024-05-22 21:15:56         co = 0xff193f0134e0
2024-05-22 21:15:56 #5  0x0000aad1868b5094 in unw_backtrace (buffer=<optimized out>, size=45) at ./contrib/libunwind/src/libunwind.cpp:352
2024-05-22 21:15:56         context = {data = {280483896309584, 280483896310592, 0, 0, 280499301161816, 17882710577277595806, 0, 0, 135, 0, 280483896337624, 0, 8244231025856375905, 280488398207559, 0, 18446744073709551615, 187817044773792, 280499299132352, 280477810608968, 280483896310208, 280483896310592, 280483896310224, 280483896336576, 187817045769200, 2, 280483896329024, 280488317450824, 280489448082072, 1, 280483896310112, 187816882163720, 280483896308944, 187816882163720, 0, 0, 280483896320000, 280488317450824, 5, 280483896319888, 2, 28, 0, 4599075939470750515, 0, 0, 0, 0, 0, 0, 0, 0, 0, 53513, 9692733207530075507, 18, 34, 19, 19, 18, 1, 1, 1, 1, 1, 1, 1}}
2024-05-22 21:15:56         cursor = {data = {187817040435032, 187817047494608, 280490899732176, 280483896319936, 26, 4189926356, 280488233195648, 187816950379296, 0, 0, 280488333168348, 280488333168577, 280488333168348, 18446744073709551586, 8244231025856375905, 280488398207559, 280488263621134, 18446744073709551615, 280488398200896, 280499299515840, 280477810608968, 2135, 0, 1604, 2, 280488290875672, 5, 280488317450624, 280488317450824, 280489448082072, 1, 2, 187816950154512, 280483896319968, 187816966201556, 0, 0, 280483896320000, 280488317450824, 5, 280483896319888, 2, 28, 0, 4599075939470750515, 0, 0, 0, 0, 0, 0, 0, 0, 0, 53513, 9692733207530075507, 18, 34, 19, 19, 18, 1, 1, 1, 1, 1, 1, 1, 187816966201312, 187816966201704, 0, 0, 0, 0, 515446407168, 187816778789664, 187816791437312, 77124143618719744}}
2024-05-22 21:15:56         current = 4
2024-05-22 21:15:56         ip = 82
2024-05-22 21:15:56 #6  StackTrace::tryCapture (this=0xff193f0139c0) at ./build_docker/./src/Common/StackTrace.cpp:349
2024-05-22 21:15:56 No locals.
2024-05-22 21:15:56 #7  StackTrace::StackTrace (this=0xff193f0139c0, signal_context=...) at ./build_docker/./src/Common/StackTrace.cpp:318
2024-05-22 21:15:56         caller_address = <optimized out>
2024-05-22 21:15:56 #8  0x0000aad1868d2d44 in std::__1::construct_at[abi:v15000]<StackTrace, ucontext_t const&, StackTrace*>(StackTrace*, ucontext_t const&) (__location=0xff193f0139c0, __args=...) at ./contrib/llvm-project/libcxx/include/__memory/construct_at.h:35
2024-05-22 21:15:56 No locals.
2024-05-22 21:15:56 #9  std::__1::__optional_storage_base<StackTrace, false>::__construct[abi:v15000]<ucontext_t const&>(ucontext_t const&) (this=0xff193f0139c0, __args=...) at ./contrib/llvm-project/libcxx/include/optional:374
2024-05-22 21:15:56 No locals.
2024-05-22 21:15:56 #10 std::__1::optional<StackTrace>::emplace[abi:v15000]<ucontext_t const&, void>(ucontext_t const&) (this=0xff193f0139c0, __args=...) at ./contrib/llvm-project/libcxx/include/optional:898
2024-05-22 21:15:56 No locals.
2024-05-22 21:15:56 #11 DB::(anonymous namespace)::writeTraceInfo (trace_type=DB::TraceType::Real, info=<optimized out>, context=<optimized out>) at ./build_docker/./src/Common/QueryProfiler.cpp:98
2024-05-22 21:15:59         signal_context = {uc_flags = 0, uc_link = 0x0, uc_stack = {ss_sp = 0xff1c477c0000, ss_flags = 0, ss_size = 32768}, uc_sigmask = {__val = {4096, 280492503020224, 280483896329176, 393216, 280483896329176, 280483896315488, 187816999473908, 280483896317088, 187816999497864, 280483896329672, 187817046722496, 280492502942848, 327680, 280483896329176, 393216, 280492504951808}}, uc_mcontext = {fault_address = 0, regs = {280490899732176, 280483896319936, 26, 4189926356, 280488233195648, 187816950379296, 0, 0, 280488333168348, 280488333168577, 280488333168348, 18446744073709551586, 8244231025856375905, 280488398207559, 280488263621134, 18446744073709551615, 280488398200896, 280499299515840, 280477810608968, 280488208482224, 2, 1604, 2, 280488290875672, 5, 280488317450624, 280488317450824, 280489448082072, 1, 280483896320000, 187816950154512}, sp = 280483896319936, pc = 187816950622000, pstate = 2147487744, __reserved = "\001\200PF\020\002\000\000\020\000\000\000\000\000\000\000\377\377\377\377\377\377\377\377\000\000\000\000\000\000\000\000renas.all.pdirty\000\000\000\000\000\000\000\000\000\240\022\004\000\000\000\000\000\300\071\"", '\000' <repeats 44 times>, "\034\000\000\000\000\000\000\000\346", '\000' <repeats 23 times>, "\063\063\063\063\063\063\323?", '\000' <repeats 152 times>...}}
2024-05-22 21:15:59         stack_trace = {<std::__1::__optional_move_assign_base<StackTrace, true>> = {<std::__1::__optional_copy_assign_base<StackTrace, true>> = {<std::__1::__optional_move_base<StackTrace, true>> = {<std::__1::__optional_copy_base<StackTrace, true>> = {<std::__1::__optional_storage_base<StackTrace, false>> = {<std::__1::__optional_destruct_base<StackTrace, true>> = {{__null_state_ = 0 '\000', __val_ = {static capacity = 45, size = 0, offset = 0, frame_pointers = {__elems_ = {0xaad1868d2d44 <DB::(anonymous namespace)::writeTraceInfo(DB::TraceType, int, siginfo_t*, void*)+484>, 0xff1cd53479d0 <__kernel_rt_sigreturn>, 0xaad18a9fe730 <DB::ColumnVector<char8_t>::insert(DB::Field const&)+48>, 0xaad18b8da0d4 <std::__1::__less<DB::SortCursor, DB::SortCursor>::operator()[abi:v15000](DB::SortCursor const&, DB::SortCursor const&) const+244>, 0x0 <repeats 41 times>}}}}, __engaged_ = false}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <std::__1::__sfinae_ctor_base<true, true>> = {<No data fields>}, <std::__1::__sfinae_assign_base<true, true>> = {<No data fields>}, <No data fields>}
2024-05-22 21:15:59         saved_errno = 2
2024-05-22 21:15:59         sanitizer = false
2024-05-22 21:15:59         scope_exit51 = <optimized out>
2024-05-22 21:15:59 #12 <signal handler called>
2024-05-22 21:15:59 No symbol table info available.
2024-05-22 21:15:59 #13 0x0000aad18a9fe730 in DB::ColumnVector<char8_t>::insert (this=0xff1ae070f6d0, x=...) at ./src/Columns/ColumnVector.h:225
2024-05-22 21:15:59 No locals.
2024-05-22 21:15:59 #14 0x0000aad18a98c510 in DB::ColumnLowCardinality::Index::insertPosition (this=0xff1a4007bfb0, position=<optimized out>) at ./build_docker/./src/Columns/ColumnLowCardinality.cpp:714
2024-05-22 21:15:59 No locals.
2024-05-22 21:15:59 #15 0x0000aad18b976064 in DB::MergedData::insertRow (raw_columns=..., row=1604, block_size=8192, this=<optimized out>) at ./src/Processors/Merges/Algorithms/MergedData.h:34
2024-05-22 21:15:59         i = 2
2024-05-22 21:15:59         num_columns = <optimized out>
2024-05-22 21:15:59         i = <optimized out>
2024-05-22 21:15:59 #16 DB::MergingSortedAlgorithm::mergeImpl<DB::SortingQueueImpl<DB::SortCursor, (DB::SortingQueueStrategy)0> > (this=0xff1a44f0f918, queue=...) at ./build_docker/./src/Processors/Merges/Algorithms/MergingSortedAlgorithm.cpp:193
2024-05-22 21:15:59         current = {<DB::SortCursorHelper<DB::SortCursor>> = {impl = 0xff1a46867980}, <No data fields>}
2024-05-22 21:15:59         current = <optimized out>
2024-05-22 21:15:59         source_num = <optimized out>
2024-05-22 21:15:59         total_merged_rows_after_insertion = <optimized out>
2024-05-22 21:15:59         chunk_num_rows = <optimized out>
2024-05-22 21:15:59         limit_reached = <optimized out>
2024-05-22 21:15:59         status = <optimized out>
2024-05-22 21:15:59         row_source = <optimized out>
2024-05-22 21:15:59         i = <optimized out>
2024-05-22 21:15:59         row_source = <optimized out>
2024-05-22 21:15:59 #17 DB::MergingSortedAlgorithm::merge()::$_0::operator()<DB::SortingQueueImpl<DB::SortCursor, (DB::SortingQueueStrategy)0> >(DB::SortingQueueImpl<DB::SortCursor, (DB::SortingQueueStrategy)0>&) const (queue=..., this=<optimized out>) at ./build_docker/./src/Processors/Merges/Algorithms/MergingSortedAlgorithm.cpp:111
2024-05-22 21:15:59 No locals.
2024-05-22 21:15:59 #18 std::__1::__invoke[abi:v15000]<DB::MergingSortedAlgorithm::merge()::$_0&, DB::SortingQueueImpl<DB::SortCursor, (DB::SortingQueueStrategy)0>&>(DB::MergingSortedAlgorithm::merge()::$_0&, DB::SortingQueueImpl<DB::SortCursor, (DB::SortingQueueStrategy)0>&) (__args=..., __f=...) at ./contrib/llvm-project/libcxx/include/__functional/invoke.h:394
2024-05-22 21:15:59 No locals.
2024-05-22 21:15:59 #19 std::__1::__variant_detail::__visitation::__variant::__value_visitor<DB::MergingSortedAlgorithm::merge()::$_0&>::operator()[abi:v15000]<std::__1::__variant_detail::__alt<25ul, DB::SortingQueueImpl<DB::SortCursor, (DB::SortingQueueStrategy)0> >&>(std::__1::__variant_detail::__alt<25ul, DB::SortingQueueImpl<DB::SortCursor, (DB::SortingQueueStrategy)0> >&) const (__alts=..., this=<optimized out>) at ./contrib/llvm-project/libcxx/include/variant:668
2024-05-22 21:15:59 No locals.
2024-05-22 21:15:59 #20 std::__1::__invoke[abi:v15000]<std::__1::__variant_detail::__visitation::__variant::__value_visitor<DB::MergingSortedAlgorithm::merge()::$_0&>, std::__1::__variant_detail::__alt<25ul, DB::SortingQueueImpl<DB::SortCursor, (DB::SortingQueueStrategy)0> >&>(std::__1::__variant_detail::__visitation::__variant::__value_visitor<DB::MergingSortedAlgorithm::merge()::$_0&>&&, std::__1::__variant_detail::__alt<25ul, DB::SortingQueueImpl<DB::SortCursor, (DB::SortingQueueStrategy)0> >&) (__args=..., __f=...) at ./contrib/llvm-project/libcxx/include/__functional/invoke.h:394
2024-05-22 21:15:59 No locals.
2024-05-22 21:15:59 #21 _ZNSt3__116__variant_detail12__visitation6__base12__dispatcherIJLm25EEE10__dispatchB6v15000IONS1_9__variant15__value_visitorIRZN2DB22MergingSortedAlgorithm5mergeEvE3$_0EEJRNS0_6__baseILNS0_6_TraitE1EJNS8_16SortingQueueImplINS8_33SpecializedSingleColumnSortCursorINS8_12ColumnVectorIDuEEEELNS8_20SortingQueueStrategyE0EEENSG_INSH_INSI_ItEEEELSL_0EEENSG_INSH_INSI_IjEEEELSL_0EEENSG_INSH_INSI_ImEEEELSL_0EEENSG_INSH_INSI_IN4wide7integerILm128EjEEEEEELSL_0EEENSG_INSH_INSI_INSX_ILm256EjEEEEEELSL_0EEENSG_INSH_INSI_IDB8_EEEELSL_0EEENSG_INSH_INSI_IsEEEELSL_0EEENSG_INSH_INSI_IiEEEELSL_0EEENSG_INSH_INSI_IlEEEELSL_0EEENSG_INSH_INSI_INSX_ILm128EiEEEEEELSL_0EEENSG_INSH_INSI_INSX_ILm256EiEEEEEELSL_0EEENSG_INSH_INSI_IfEEEELSL_0EEENSG_INSH_INSI_IdEEEELSL_0EEENSG_INSH_INS8_13ColumnDecimalINS8_7DecimalIiEEEEEELSL_0EEENSG_INSH_INS1X_INS1Y_IlEEEEEELSL_0EEENSG_INSH_INS1X_INS1Y_IS1J_EEEEEELSL_0EEENSG_INSH_INS1X_INS1Y_IS1N_EEEEEELSL_0EEENSG_INSH_INS1X_INS8_10DateTime64EEEEELSL_0EEENSG_INSH_INSI_I13StrongTypedefISY_NS8_7UUIDTagEEEEEELSL_0EEENSG_INSH_INSI_INS8_4IPv4EEEEELSL_0EEENSG_INSH_INSI_INS8_4IPv6EEEEELSL_0EEENSG_INSH_INS8_12ColumnStringEEELSL_0EEENSG_INSH_INS8_17ColumnFixedStringEEELSL_0EEENSG_INS8_16SimpleSortCursorELSL_0EEENSG_INS8_10SortCursorELSL_0EEENSG_INS8_23SortCursorWithCollationELSL_0EEEEEEEEEDcT_DpT0_ (__f=..., __vs=...) at ./contrib/llvm-project/libcxx/include/variant:548
2024-05-22 21:15:59 No locals.
2024-05-22 21:15:59 #22 0x0000aad18a64a724 in DB::MergingSortedAlgorithm::merge (this=0xff1a47764fc1) at ./src/Processors/Merges/Algorithms/MergingSortedAlgorithm.cpp:109
2024-05-22 21:16:00         result = {chunk = {columns = {__begin_ = 0x65746972775f6465, __end_ = 0x203a73657479625f, __end_cap_ = {<std::__1::__compressed_pair_elem<COW<DB::IColumn>::immutable_ptr<DB::IColumn>*, 0, false>> = {__value_ = 0xa36373339303937}, <std::__1::__compressed_pair_elem<std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> >, 1, true>> = {<std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> >> = {<std::__1::__non_trivial_if<true, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}, num_rows = 3546645421036156209, chunk_info = {__ptr_ = 0x3337333431393736, __cntrl_ = 0x3138373831203231}}, is_finished = 55, required_source = 3977858488303891510}
2024-05-22 21:16:00         result = <optimized out>
2024-05-22 21:16:00 #23 DB::IMergingTransform<DB::MergingSortedAlgorithm>::work (this=0xff1a44f0f798) at ./src/Processors/Merges/IMergingTransform.h:130
2024-05-22 21:16:00         status = {chunk = {columns = {__begin_ = 0x65746972775f6465, __end_ = 0x203a73657479625f, __end_cap_ = {<std::__1::__compressed_pair_elem<COW<DB::IColumn>::immutable_ptr<DB::IColumn>*, 0, false>> = {__value_ = 0xa36373339303937}, <std::__1::__compressed_pair_elem<std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> >, 1, true>> = {<std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> >> = {<std::__1::__non_trivial_if<true, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}, num_rows = 3546645421036156209, chunk_info = {__ptr_ = 0x3337333431393736, __cntrl_ = 0x3138373831203231}}, is_finished = 55, required_source = 3977858488303891510}
2024-05-22 21:16:00 #24 0x0000aad18b671290 in DB::executeJob (node=0xff1a41103600, read_progress_callback=0xff1a84730120) at ./build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:47
2024-05-22 21:16:31         exception = {<Poco::Exception> = {<std::exception> = {_vptr$exception = 0x0, static capacity = 32, frames = {0x0, 0x20950, 0x111ce0, 0x0, 0x0, 0x0, 0xff193f016460, 0xaad1868c5e00 <DB::ThreadStatus::updatePerformanceCounters()+512>, 0x0, 0x0, 0xff193f0162e0, 0xff1ae474ce00, 0xff193f016460, 0xaad1868d2224 <DB::QueryProfilerBase<DB::QueryProfilerCPU>::QueryProfilerBase(unsigned long, int, unsigned int, int)+260>, 0x0, 0xaad1868d23e0 <DB::QueryProfilerCPU::signalHandler(int, siginfo_t*, void*)>, 0x10000004, 0x140000480, 0x800, 0x0 <repeats 13 times>}, size = 0}, _msg = {static __endian_factor = 1, __r_ = {<std::__1::__compressed_pair_elem<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__rep, 0, false>> = {__value_ = {{__l = {__data_ = 0x0, __size_ = 280483896320936, __cap_ = 1, __is_long_ = 0}, __s = {__data_ = "\000\000\000\000\000\000\000\000\250c\001?\031\377\000\000\001\000\000\000\000\000", __padding_ = 0xff193f01630f "", __size_ = 0 '\000', __is_long_ = 0 '\000'}, __r = {__words = {0, 280483896320936, 1}}}}}, <std::__1::__compressed_pair_elem<std::__1::allocator<char>, 1, true>> = {<std::__1::allocator<char>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<char> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, static npos = 18446744073709551615}, _pNested = 0x0, _code = 0}, static enable_job_stack_trace = false, static thread_frame_pointers = {__begin_ = 0x1200000e00, __end_ = 0x0, __end_cap_ = {<std::__1::__compressed_pair_elem<std::__1::array<void*, 45ul>*, 0, false>> = {__value_ = 0x0}, <std::__1::__compressed_pair_elem<std::__1::allocator<std::__1::array<void*, 45ul> >, 1, true>> = {<std::__1::allocator<std::__1::array<void*, 45ul> >> = {<std::__1::__non_trivial_if<true, std::__1::allocator<std::__1::array<void*, 45ul> > >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}, static callback = {<std::__1::__function::__maybe_derive_from_unary_function<void (const std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > &, int, bool, const std::__1::vector<void *, std::__1::allocator<void *> > &)>> = {<No data fields>}, <std::__1::__function::__maybe_derive_from_binary_function<void (const std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > &, int, bool, const std::__1::vector<void *, std::__1::allocator<void *> > &)>> = {<No data fields>}, __f_ = {__buf_ = {__small = '\000' <repeats 15 times>, __large = 0x0}, __invoker_ = {__call_ = 0xaad186898160 <std::__1::__function::__policy_invoker<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool, std::__1::vector<void*, std::__1::allocator<void*> > const&)>::__call_empty(std::__1::__function::__policy_storage const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool, std::__1::vector<void*, std::__1::allocator<void*> > const&)>}, __policy_ = 0xaad18ffb8e78 <std::__1::__function::__policy::__create_empty[abi:v15000]()::__policy_>}}, remote = false, message_format_string = {static npos = 18446744073709551615, __data = 0xff193f016370 "\030\203\025\220Ѫ", __size = 187817001086852}, message_format_string_args = {__begin_ = 0xff1a482aa800, __end_ = 0x0, __end_cap_ = {<std::__1::__compressed_pair_elem<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, 0, false>> = {__value_ = 0x1}, <std::__1::__compressed_pair_elem<std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, 1, true>> = {<std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >> = {<std::__1::__non_trivial_if<true, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}, capture_thread_frame_pointers = {__begin_ = 0x0, __end_ = 0x0, __end_cap_ = {<std::__1::__compressed_pair_elem<std::__1::array<void*, 45ul>*, 0, false>> = {__value_ = 0x67fb9cd}, <std::__1::__compressed_pair_elem<std::__1::allocator<std::__1::array<void*, 45ul> >, 1, true>> = {<std::__1::allocator<std::__1::array<void*, 45ul> >> = {<std::__1::__non_trivial_if<true, std::__1::allocator<std::__1::array<void*, 45ul> > >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}}
2024-05-22 21:16:31         is_source = <optimized out>
2024-05-22 21:16:31         read_progress = <optimized out>
```

The server crashes when generating a StackTrace

**Comment by azat** [comment]
This is actually a different problem, and it is more similar to https://github.com/ClickHouse/ClickHouse/issues/60460

**Comment by Algunenano** [comment]
Let's continue in https://github.com/ClickHouse/ClickHouse/issues/64915 then. It keeps happening in CI almost daily
