### ISSUE TITLE
ubsan: Unsafe integer cast in `replaceNodesWithPositionalArguments`

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#63866]
https://s3.amazonaws.com/clickhouse-test-reports/63695/bc98cc212c5285d9739de78e251175b7afdf8a3e/ast_fuzzer__ubsan_.html

```
/build/contrib/llvm-project/libcxx/include/stdlib.h:112:25: runtime error: negation of -9223372036854775808 cannot be represented in type 'long'; cast to an unsigned type to negate this value to itself
    #0 0x55d0d5e515e5 in abs[abi:v15000](long) build_docker/./contrib/llvm-project/libcxx/include/stdlib.h:112:10
    #1 0x55d0d5e515e5 in DB::(anonymous namespace)::QueryAnalyzer::replaceNodesWithPositionalArguments(std::__1::shared_ptr<DB::IQueryTreeNode>&, std::__1::vector<std::__1::shared_ptr<DB::IQueryTreeNode>, std::__1::allocator<std::__1::shared_ptr<DB::IQueryTreeNode>>> const&, DB::(anonymous namespace)::IdentifierResolveScope&) build_docker/./src/Analyzer/Passes/QueryAnalysisPass.cpp:2332:41
    #2 0x55d0d5e2e788 in DB::(anonymous namespace)::QueryAnalyzer::resolveGroupByNode(DB::QueryNode&, DB::(anonymous namespace)::IdentifierResolveScope&) build_docker/./src/Analyzer/Passes/QueryAnalysisPass.cpp:6796:9
    #3 0x55d0d5e2e788 in DB::(anonymous namespace)::QueryAnalyzer::resolveQuery(std::__1::shared_ptr<DB::IQueryTreeNode> const&, DB::(anonymous namespace)::IdentifierResolveScope&) build_docker/./src/Analyzer/Passes/QueryAnalysisPass.cpp:8128:9
    #4 0x55d0d5e27d29 in DB::(anonymous namespace)::QueryAnalyzer::resolve(std::__1::shared_ptr<DB::IQueryTreeNode>&, std::__1::shared_ptr<DB::IQueryTreeNode> const&, std::__1::shared_ptr<DB::Context const>) build_docker/./src/Analyzer/Passes/QueryAnalysisPass.cpp:1149:17
    #5 0x55d0d5e27d29 in DB::QueryAnalysisPass::run(std::__1::shared_ptr<DB::IQueryTreeNode>&, std::__1::shared_ptr<DB::Context const>) build_docker/./src/Analyzer/Passes/QueryAnalysisPass.cpp:8392:14
    #6 0x55d0d5e20450 in DB::QueryTreePassManager::run(std::__1::shared_ptr<DB::IQueryTreeNode>) build_docker/./src/Analyzer/QueryTreePassManager.cpp:185:20
    #7 0x55d0d65ab686 in DB::(anonymous namespace)::buildQueryTreeAndRunPasses(std::__1::shared_ptr<DB::IAST> const&, DB::SelectQueryOptions const&, std::__1::shared_ptr<DB::Context const> const&, std::__1::shared_ptr<DB::IStorage> const&) build_docker/./src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:142:33
    #8 0x55d0d65a835b in DB::InterpreterSelectQueryAnalyzer::InterpreterSelectQueryAnalyzer(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) build_docker/./src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:160:18
    #9 0x55d0d65adbb3 in std::__1::__unique_if<DB::InterpreterSelectQueryAnalyzer>::__unique_single std::__1::make_unique[abi:v15000]<DB::InterpreterSelectQueryAnalyzer, std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context> const&, DB::SelectQueryOptions const&>(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context> const&, DB::SelectQueryOptions const&) build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:714:32
    #10 0x55d0d65ad204 in DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0::operator()(DB::InterpreterFactory::Arguments const&) const build_docker/./src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:270:16
    #11 0x55d0d65ad204 in decltype(std::declval<DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0&>()(std::declval<DB::InterpreterFactory::Arguments const&>())) std::__1::__invoke[abi:v15000]<DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0&, DB::InterpreterFactory::Arguments const&>(DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0&, DB::InterpreterFactory::Arguments const&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #12 0x55d0d65ad204 in std::__1::unique_ptr<DB::IInterpreter, std::__1::default_delete<DB::IInterpreter>> std::__1::__invoke_void_return_wrapper<std::__1::unique_ptr<DB::IInterpreter, std::__1::default_delete<DB::IInterpreter>>, false>::__call<DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0&, DB::InterpreterFactory::Arguments const&>(DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0&, DB::InterpreterFactory::Arguments const&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:470:16
    #13 0x55d0d65ad204 in std::__1::__function::__default_alloc_func<DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0, std::__1::unique_ptr<DB::IInterpreter, std::__1::default_delete<DB::IInterpreter>> (DB::InterpreterFactory::Arguments const&)>::operator()[abi:v15000](DB::InterpreterFactory::Arguments const&) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:235:12
    #14 0x55d0d65ad204 in std::__1::unique_ptr<DB::IInterpreter, std::__1::default_delete<DB::IInterpreter>> std::__1::__function::__policy_invoker<std::__1::unique_ptr<DB::IInterpreter, std::__1::default_delete<DB::IInterpreter>> (DB::InterpreterFactory::Arguments const&)>::__call_impl<std::__1::__function::__default_alloc_func<DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0, std::__1::unique_ptr<DB::IInterpreter, std::__1::default_delete<DB::IInterpreter>> (DB::InterpreterFactory::Arguments const&)>>(std::__1::__function::__policy_storage const*, DB::InterpreterFactory::Arguments const&) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716:16
    #15 0x55d0d64d0c72 in std::__1::__function::__policy_func<std::__1::unique_ptr<DB::IInterpreter, std::__1::default_delete<DB::IInterpreter>> (DB::InterpreterFactory::Arguments const&)>::operator()[abi:v15000](DB::InterpreterFactory::Arguments const&) const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:848:16
    #16 0x55d0d64d0c72 in std::__1::function<std::__1::unique_ptr<DB::IInterpreter, std::__1::default_delete<DB::IInterpreter>> (DB::InterpreterFactory::Arguments const&)>::operator()(DB::InterpreterFactory::Arguments const&) const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:1187:12
    #17 0x55d0d64d0c72 in DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) build_docker/./src/Interpreters/InterpreterFactory.cpp:355:12
    #18 0x55d0d6c65e5d in DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) build_docker/./src/Interpreters/executeQuery.cpp:1136:62
    #19 0x55d0d6c5f792 in DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) build_docker/./src/Interpreters/executeQuery.cpp:1393:26
    #20 0x55d0d89bea85 in DB::TCPHandler::runImpl() build_docker/./src/Server/TCPHandler.cpp:522:54
    #21 0x55d0d89f19d5 in DB::TCPHandler::run() build_docker/./src/Server/TCPHandler.cpp:2341:9
    #22 0x55d0dbcd64b7 in Poco::Net::TCPServerConnection::start() build_docker/./base/poco/Net/src/TCPServerConnection.cpp:43:3
    #23 0x55d0dbcd75f1 in Poco::Net::TCPServerDispatcher::run() build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:115:20
    #24 0x55d0dbf386b4 in Poco::PooledThread::run() build_docker/./base/poco/Foundation/src/ThreadPool.cpp:188:14
    #25 0x55d0dbf3386e in Poco::ThreadImpl::runnableEntry(void*) build_docker/./base/poco/Foundation/src/Thread_POSIX.cpp:335:27
    #26 0x7ff52b73cac2 in start_thread nptl/pthread_create.c:442:8
    #27 0x7ff52b7ce84f  misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /build/contrib/llvm-project/libcxx/include/stdlib.h:112:25 
```

```
4146311:2024.05.14 21:54:32.210457 [ 1185 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
4146312:2024.05.14 21:54:32.210490 [ 1185 ] {} <Fatal> BaseDaemon: (version 24.5.1.1060, build id: 0D8CE99BC57B94388BD541A625479B366F13656B, git hash: 111bde878d9b99bc5b6d5041cf080d263b3b5058) (from thread 161) Received signal -3
4146313:2024.05.14 21:54:32.210495 [ 1185 ] {} <Fatal> BaseDaemon: Signal description: sanitizer trap
4146314:2024.05.14 21:54:32.210498 [ 1185 ] {} <Fatal> BaseDaemon: Sanitizer trap.
4146315:2024.05.14 21:54:32.210507 [ 1185 ] {} <Fatal> BaseDaemon: Stack trace: 0x000055d0c9b35cf7 0x000055d0c9f30ec5 0x000055d0bd81a446 0x000055d0bd82478f 0x000055d0d5e515e6 0x000055d0d5e2e789 0x000055d0d5e27d2a 0x000055d0d5e20451 0x000055d0d65ab687 0x000055d0d65a835c 0x000055d0d65adbb4 0x000055d0d65ad205 0x000055d0d64d0c73 0x000055d0d6c65e5e 0x000055d0d6c5f793 0x000055d0d89bea86 0x000055d0d89f19d6 0x000055d0dbcd64b8 0x000055d0dbcd75f2 0x000055d0dbf386b5 0x000055d0dbf3386f 0x00007ff52b73cac3 0x00007ff52b7ce850
4146316:2024.05.14 21:54:32.210515 [ 1185 ] {} <Fatal> BaseDaemon: ########################################
4146317:2024.05.14 21:54:32.210578 [ 1185 ] {} <Fatal> BaseDaemon: (version 24.5.1.1060, build id: 0D8CE99BC57B94388BD541A625479B366F13656B, git hash: 111bde878d9b99bc5b6d5041cf080d263b3b5058) (from thread 161) (query_id: bba74432-775c-4f3b-ab83-aa169a033d3f) (query: SELECT DISTINCT toDateTime(1234567890) + toIntervalDay(toNullable(2)), toDateTime(concat(3, 3, toNullable(3), 3, 3, 3)), y FROM mt_with_pk GROUP BY concat(materialize(3), toNullable(3), 3, 3, toNullable(3), 3, 3), -9223372036854775808, toDateTime(toUInt128(1234567890))) Received signal sanitizer trap (-3)
4146318:2024.05.14 21:54:32.210593 [ 1185 ] {} <Fatal> BaseDaemon: Sanitizer trap.
4146319:2024.05.14 21:54:32.210604 [ 1185 ] {} <Fatal> BaseDaemon: Stack trace: 0x000055d0c9b35cf7 0x000055d0c9f30ec5 0x000055d0bd81a446 0x000055d0bd82478f 0x000055d0d5e515e6 0x000055d0d5e2e789 0x000055d0d5e27d2a 0x000055d0d5e20451 0x000055d0d65ab687 0x000055d0d65a835c 0x000055d0d65adbb4 0x000055d0d65ad205 0x000055d0d64d0c73 0x000055d0d6c65e5e 0x000055d0d6c5f793 0x000055d0d89bea86 0x000055d0d89f19d6 0x000055d0dbcd64b8 0x000055d0dbcd75f2 0x000055d0dbf386b5 0x000055d0dbf3386f 0x00007ff52b73cac3 0x00007ff52b7ce850
4146320:2024.05.14 21:54:32.220296 [ 1185 ] {} <Fatal> BaseDaemon: 0. ./build_docker/./src/Common/StackTrace.cpp:347: StackTrace::tryCapture() @ 0x0000000023feccf7
4146321:2024.05.14 21:54:32.243342 [ 1185 ] {} <Fatal> BaseDaemon: 1. ./src/Common/StackTrace.h:0: sanitizerDeathCallback() @ 0x00000000243e7ec5
4146330:2024.05.14 21:54:33.010763 [ 1185 ] {} <Fatal> BaseDaemon: 2. __sanitizer::Die() @ 0x0000000017cd1446
4146331:2024.05.14 21:54:33.755329 [ 1185 ] {} <Fatal> BaseDaemon: 3. ? @ 0x0000000017cdb78f
4146332:2024.05.14 21:54:33.835855 [ 1185 ] {} <Fatal> BaseDaemon: 4. ./build_docker/./src/Analyzer/Passes/QueryAnalysisPass.cpp:2304: DB::(anonymous namespace)::QueryAnalyzer::replaceNodesWithPositionalArguments(std::shared_ptr<DB::IQueryTreeNode>&, std::vector<std::shared_ptr<DB::IQueryTreeNode>, std::allocator<std::shared_ptr<DB::IQueryTreeNode>>> const&, DB::(anonymous namespace)::IdentifierResolveScope&) @ 0x00000000303085e6
4146333:2024.05.14 21:54:33.910136 [ 1185 ] {} <Fatal> BaseDaemon: 5.0. inlined from ./build_docker/./src/Analyzer/Passes/QueryAnalysisPass.cpp:0: DB::(anonymous namespace)::QueryAnalyzer::resolveGroupByNode(DB::QueryNode&, DB::(anonymous namespace)::IdentifierResolveScope&)
4146334:2024.05.14 21:54:33.910197 [ 1185 ] {} <Fatal> BaseDaemon: 5. ./build_docker/./src/Analyzer/Passes/QueryAnalysisPass.cpp:8128: DB::(anonymous namespace)::QueryAnalyzer::resolveQuery(std::shared_ptr<DB::IQueryTreeNode> const&, DB::(anonymous namespace)::IdentifierResolveScope&) @ 0x00000000302e5789
4146335:2024.05.14 21:54:33.981527 [ 1185 ] {} <Fatal> BaseDaemon: 6.0. inlined from ./build_docker/./src/Analyzer/Passes/QueryAnalysisPass.cpp:0: DB::(anonymous namespace)::QueryAnalyzer::resolve(std::shared_ptr<DB::IQueryTreeNode>&, std::shared_ptr<DB::IQueryTreeNode> const&, std::shared_ptr<DB::Context const>)
4146336:2024.05.14 21:54:33.981590 [ 1185 ] {} <Fatal> BaseDaemon: 6. ./build_docker/./src/Analyzer/Passes/QueryAnalysisPass.cpp:8392: DB::QueryAnalysisPass::run(std::shared_ptr<DB::IQueryTreeNode>&, std::shared_ptr<DB::Context const>) @ 0x00000000302ded2a
4146337:2024.05.14 21:54:33.994559 [ 1185 ] {} <Fatal> BaseDaemon: 7. ./build_docker/./src/Analyzer/QueryTreePassManager.cpp:0: DB::QueryTreePassManager::run(std::shared_ptr<DB::IQueryTreeNode>) @ 0x00000000302d7451
4146339:2024.05.14 21:54:34.013828 [ 1185 ] {} <Fatal> BaseDaemon: 8. ./build_docker/./src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:0: DB::(anonymous namespace)::buildQueryTreeAndRunPasses(std::shared_ptr<DB::IAST> const&, DB::SelectQueryOptions const&, std::shared_ptr<DB::Context const> const&, std::shared_ptr<DB::IStorage> const&) @ 0x0000000030a62687
4146340:2024.05.14 21:54:34.031023 [ 1185 ] {} <Fatal> BaseDaemon: 9. ./build_docker/./src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:160: DB::InterpreterSelectQueryAnalyzer::InterpreterSelectQueryAnalyzer(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&) @ 0x0000000030a5f35c
4146341:2024.05.14 21:54:34.050246 [ 1185 ] {} <Fatal> BaseDaemon: 10. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:0: std::__unique_if<DB::InterpreterSelectQueryAnalyzer>::__unique_single std::make_unique[abi:v15000]<DB::InterpreterSelectQueryAnalyzer, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::Context> const&, DB::SelectQueryOptions const&>(std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::Context> const&, DB::SelectQueryOptions const&) @ 0x0000000030a64bb4
4146342:2024.05.14 21:54:34.069034 [ 1185 ] {} <Fatal> BaseDaemon: 11.0. inlined from ./contrib/llvm-project/libcxx/include/__memory/compressed_pair.h:40: __compressed_pair_elem<DB::InterpreterSelectQueryAnalyzer *, void>
4146343:2024.05.14 21:54:34.069080 [ 1185 ] {} <Fatal> BaseDaemon: 11.1. inlined from ./contrib/llvm-project/libcxx/include/__memory/compressed_pair.h:108: __compressed_pair<DB::InterpreterSelectQueryAnalyzer *, std::default_delete<DB::InterpreterSelectQueryAnalyzer> >
4146344:2024.05.14 21:54:34.069097 [ 1185 ] {} <Fatal> BaseDaemon: 11.2. inlined from ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:211: unique_ptr<DB::InterpreterSelectQueryAnalyzer, std::default_delete<DB::InterpreterSelectQueryAnalyzer>, void, void>
4146345:2024.05.14 21:54:34.069109 [ 1185 ] {} <Fatal> BaseDaemon: 11.3. inlined from ./contrib/llvm-project/libcxx/include/__functional/invoke.h:470: ?
4146346:2024.05.14 21:54:34.069119 [ 1185 ] {} <Fatal> BaseDaemon: 11.4. inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:235: ?
4146347:2024.05.14 21:54:34.069130 [ 1185 ] {} <Fatal> BaseDaemon: 11. ./contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x0000000030a64205
4146348:2024.05.14 21:54:34.077185 [ 1185 ] {} <Fatal> BaseDaemon: 12.0. inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:818: ?
4146349:2024.05.14 21:54:34.077218 [ 1185 ] {} <Fatal> BaseDaemon: 12.1. inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:1174: ?
4146350:2024.05.14 21:54:34.077234 [ 1185 ] {} <Fatal> BaseDaemon: 12. ./build_docker/./src/Interpreters/InterpreterFactory.cpp:356: DB::InterpreterFactory::get(std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) @ 0x0000000030987c73
4146351:2024.05.14 21:54:34.121442 [ 1185 ] {} <Fatal> BaseDaemon: 13. ./build_docker/./src/Interpreters/executeQuery.cpp:0: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x000000003111ce5e
4146352:2024.05.14 21:54:34.168180 [ 1185 ] {} <Fatal> BaseDaemon: 14. ./build_docker/./src/Interpreters/executeQuery.cpp:1393: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x0000000031116793
4146353:2024.05.14 21:54:34.203974 [ 1185 ] {} <Fatal> BaseDaemon: 15. ./build_docker/./src/Server/TCPHandler.cpp:522: DB::TCPHandler::runImpl() @ 0x0000000032e75a86
4146354:2024.05.14 21:54:34.264124 [ 1185 ] {} <Fatal> BaseDaemon: 16. ./build_docker/./src/Server/TCPHandler.cpp:2343: DB::TCPHandler::run() @ 0x0000000032ea89d6
4146355:2024.05.14 21:54:34.266182 [ 1185 ] {} <Fatal> BaseDaemon: 17. ./build_docker/./base/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x000000003618d4b8
4146356:2024.05.14 21:54:34.269186 [ 1185 ] {} <Fatal> BaseDaemon: 18.0. inlined from ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:302: std::unique_ptr<Poco::Net::TCPServerConnection, std::default_delete<Poco::Net::TCPServerConnection>>::reset[abi:v15000](Poco::Net::TCPServerConnection*)
4146357:2024.05.14 21:54:34.269207 [ 1185 ] {} <Fatal> BaseDaemon: 18.1. inlined from ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
4146358:2024.05.14 21:54:34.269216 [ 1185 ] {} <Fatal> BaseDaemon: 18. ./build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:116: Poco::Net::TCPServerDispatcher::run() @ 0x000000003618e5f2
4146359:2024.05.14 21:54:34.271995 [ 1185 ] {} <Fatal> BaseDaemon: 19. ./build_docker/./base/poco/Foundation/src/ThreadPool.cpp:202: Poco::PooledThread::run() @ 0x00000000363ef6b5
4146360:2024.05.14 21:54:34.274687 [ 1185 ] {} <Fatal> BaseDaemon: 20.0. inlined from ./base/poco/Foundation/include/Poco/AutoPtr.h:205: Poco::AutoPtr<Poco::ThreadImpl::ThreadData>::operator->()
4146361:2024.05.14 21:54:34.274706 [ 1185 ] {} <Fatal> BaseDaemon: 20. ./base/poco/Foundation/src/Thread_POSIX.cpp:350: Poco::ThreadImpl::runnableEntry(void*) @ 0x00000000363ea86f
4146362:2024.05.14 21:54:34.274718 [ 1185 ] {} <Fatal> BaseDaemon: 21. ? @ 0x00007ff52b73cac3
4146363:2024.05.14 21:54:34.274728 [ 1185 ] {} <Fatal> BaseDaemon: 22. ? @ 0x00007ff52b7ce850
4146364:2024.05.14 21:54:34.274742 [ 1185 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
4146442:2024.05.14 21:54:36.327257 [ 1185 ] {} <Fatal> BaseDaemon: Changed settings: max_block_size = 1048576, max_threads = 10, receive_timeout = 10., receive_data_timeout_ms = 10000, optimize_move_to_prewhere = true, allow_suspicious_low_cardinality_types = true, compile_expressions = true, min_count_to_compile_expression = 0, force_index_by_date = false, force_primary_key = false, log_queries = true, table_function_remote_max_addresses = 200, joined_subquery_requires_alias = false, allow_experimental_analyzer = true, max_rows_to_read = 100, max_bytes_before_external_sort = 33554432, max_execution_time = 2., join_algorithm = 'partial_merge', max_memory_usage = 300000000, log_comment = '/workspace/ch/tests/queries/0_stateless/00955_test_final_mark.sql', send_logs_level = 'fatal', prefer_localhost_replica = false, allow_introspection_functions = true, database_atomic_wait_for_drop_and_detach_synchronously = false, mutations_sync = 2, insert_null_as_default = true, insert_keeper_fault_injection_probability = 0.

```

**Comment by Avogar** [comment]
Already fixed in https://github.com/ClickHouse/ClickHouse/pull/63734
