### ISSUE TITLE
Integration tests are broken in backports

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#64301]
Many failures

Example: https://s3.amazonaws.com/clickhouse-test-reports/64265/93699954a4db0934e1fb1e56f1dd50f13fd37c09/integration_tests__release__[1_4].html

```
Traceback (most recent call last):
  File "/ClickHouse/tests/integration/helpers/cluster.py", line 2654, in start
    self.docker_client = docker.DockerClient(
  File "/usr/local/lib/python3.10/dist-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/local/lib/python3.10/dist-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: Not supported URL scheme http+docker
```

**Comment by Algunenano** [comment]
It seems we no longer run them
