### ISSUE TITLE
AddressSanitizer: global-buffer-overflow (multiif + short_circuit_function_evaluation)

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#64946]
https://s3.amazonaws.com/clickhouse-test-reports/0/d6db78955f7bcb040a45236bf1d77f40720c6513/ast_fuzzer__asan_.html

```
SELECT multiIf((16 % 2) = 0, '', ''), multiIf(11 = (number % 2), toInt8(1), (number % 3) = 0, toInt8(2), toInt64(3)), multiIf((number % toLowCardinality(toNullable(toUInt128(2)))) = (number % toNullable(2)), toInt8(1), (number % materialize(toLowCardinality(3))) = toUInt128(toNullable(0)), toInt8(materialize(materialize(2))), toInt64(toUInt128(3))) FROM system.numbers LIMIT 1048576;
```

```
=================================================================
==913036==ERROR: AddressSanitizer: global-buffer-overflow on address 0x5555598305e0 at pc 0x555584213fc4 bp 0x7ffefdbf8120 sp 0x7ffefdbf8118
READ of size 16 at 0x5555598305e0 thread T3 (QueryPullPipeEx)
→ Progress: 65.41 thousand rows, 523.27 KB (79.65 thousand rows/s., 637.21 KB/s.) ████████████                                                                                                                                                                                       6%    #0 0x555584213fc3 in void DB::(anonymous namespace)::FunctionMultiIf::calculateInserts<char8_t>(std::__1::vector<DB::(anonymous namespace)::FunctionMultiIf::Instruction, std::__1::allocator<DB::(anonymous namespace)::FunctionMultiIf::Instruction>> const&, unsigned long, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>&) multiIf.cpp
    #1 0x5555841f23db in void DB::(anonymous namespace)::FunctionMultiIf::executeInstructionsColumnar<long, char8_t, false>(std::__1::vector<DB::(anonymous namespace)::FunctionMultiIf::Instruction, std::__1::allocator<DB::(anonymous namespace)::FunctionMultiIf::Instruction>> const&, unsigned long, DB::PODArray<long, 4096ul, Allocator<false, false>, 63ul, 64ul>&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>*) multiIf.cpp
    #2 0x5555841d98ab in DB::(anonymous namespace)::FunctionMultiIf::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const multiIf.cpp
    #3 0x5555620adc14 in DB::FunctionToExecutableFunctionAdaptor::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/mnt/ch/ClickHouse/build_asan/programs/clickhouse+0xcb59c14) (BuildId: e2becb604b3f1fe2872bea54f46f062d61506260)
    #4 0x55557eb207c9 in DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const (/mnt/ch/ClickHouse/build_asan/programs/clickhouse+0x295cc7c9) (BuildId: e2becb604b3f1fe2872bea54f46f062d61506260)
    #5 0x55557eb226a9 in DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const (/mnt/ch/ClickHouse/build_asan/programs/clickhouse+0x295ce6a9) (BuildId: e2becb604b3f1fe2872bea54f46f062d61506260)
    #6 0x55557eb26e5e in DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const (/mnt/ch/ClickHouse/build_asan/programs/clickhouse+0x295d2e5e) (BuildId: e2becb604b3f1fe2872bea54f46f062d61506260)
    #7 0x55558217fca4 in DB::executeAction(DB::ExpressionActions::Action const&, DB::(anonymous namespace)::ExecutionContext&, bool, bool) /mnt/ch/ClickHouse/src/Interpreters/ExpressionActions.cpp:616:60
    #8 0x55558217fca4 in DB::ExpressionActions::execute(DB::Block&, unsigned long&, bool, bool) const /mnt/ch/ClickHouse/src/Interpreters/ExpressionActions.cpp:750:13
    #9 0x5555890fb86d in DB::ExpressionTransform::transform(DB::Chunk&) /mnt/ch/ClickHouse/src/Processors/Transforms/ExpressionTransform.cpp:23:17
    #10 0x555576ceffdd in DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) /mnt/ch/ClickHouse/src/Processors/ISimpleTransform.h:32:9
    #11 0x555588873ada in DB::ISimpleTransform::work() /mnt/ch/ClickHouse/src/Processors/ISimpleTransform.cpp:89:9
    #12 0x5555888cc26d in DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*) /mnt/ch/ClickHouse/src/Processors/Executors/ExecutionThreadContext.cpp:47:26
    #13 0x5555888cc26d in DB::ExecutionThreadContext::executeTask() /mnt/ch/ClickHouse/src/Processors/Executors/ExecutionThreadContext.cpp:96:9
    #14 0x5555888abce6 in DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) /mnt/ch/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:272:26
    #15 0x5555888abce6 in DB::PipelineExecutor::executeSingleThread(unsigned long) /mnt/ch/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:238:5
    #16 0x5555888a81d3 in DB::PipelineExecutor::executeImpl(unsigned long, bool) /mnt/ch/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:410:9
    #17 0x5555888a7a65 in DB::PipelineExecutor::execute(unsigned long, bool) /mnt/ch/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:110:9
    #18 0x5555888d7ccd in DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::__1::shared_ptr<DB::ThreadGroup>, unsigned long, bool) /mnt/ch/ClickHouse/src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:83:24
    #19 0x5555888d7ccd in DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0::operator()() const /mnt/ch/ClickHouse/src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:109:13
    #20 0x5555888d7ccd in decltype(std::declval<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>()()) std::__1::__invoke[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&) /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #21 0x5555888d7ccd in decltype(auto) std::__1::__apply_tuple_impl[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>) /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/tuple:1789:1
    #22 0x5555888d7ccd in decltype(auto) std::__1::apply[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&) /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/tuple:1798:1
    #23 0x5555888d7ccd in ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()::operator()() /mnt/ch/ClickHouse/src/Common/ThreadPool.h:251:13
    #24 0x5555888d7ccd in decltype(std::declval<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>()()) std::__1::__invoke[abi:v15000]<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&) /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #25 0x5555888d7ccd in void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&) /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/invoke.h:479:9
    #26 0x5555888d7ccd in std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>::operator()[abi:v15000]() /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:235:12
    #27 0x5555888d7ccd in void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:716:16
    #28 0x555571a5a48c in std::__1::__function::__policy_func<void ()>::operator()[abi:v15000]() const /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:848:16
    #29 0x555571a5a48c in std::__1::function<void ()>::operator()() const /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:1187:12
    #30 0x555571a5a48c in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) /mnt/ch/ClickHouse/src/Common/ThreadPool.cpp:462:13
    #31 0x555571a68414 in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const /mnt/ch/ClickHouse/src/Common/ThreadPool.cpp:219:73
    #32 0x555571a68414 in decltype(std::declval<void>()()) std::__1::__invoke[abi:v15000]<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&) /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #33 0x555571a68414 in void std::__1::__thread_execute[abi:v15000]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>&, std::__1::__tuple_indices<>) /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/thread:284:5
    #34 0x555571a68414 in void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/thread:295:5
    #35 0x55555ff856a6 in asan_thread_start(void*) crtstuff.c
    #36 0x7ffff7e2adec in start_thread /usr/src/debug/glibc/glibc/nptl/pthread_create.c:447:8
    #37 0x7ffff7eae0db in clone3 /usr/src/debug/glibc/glibc/misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

0x5555598305e0 is located 0 bytes after global variable 'DB::empty_pod_array' defined in '/mnt/ch/ClickHouse/src/Common/PODArray.cpp:45' (0x5555598301e0) of size 1024
SUMMARY: AddressSanitizer: global-buffer-overflow multiIf.cpp in void DB::(anonymous namespace)::FunctionMultiIf::calculateInserts<char8_t>(std::__1::vector<DB::(anonymous namespace)::FunctionMultiIf::Instruction, std::__1::allocator<DB::(anonymous namespace)::FunctionMultiIf::Instruction>> const&, unsigned long, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>&)
Shadow bytes around the buggy address:
  0x555559830300: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x555559830380: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x555559830400: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x555559830480: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x555559830500: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x555559830580: 00 00 00 00 00 00 00 00 00 00 00 00[f9]f9 f9 f9
  0x555559830600: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x555559830680: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 00 00 00 00
  0x555559830700: 00 00 00 00 00 00 00 00 00 00 00 00 00 f9 f9 f9
  0x555559830780: 00 f9 f9 f9 00 f9 f9 f9 00 f9 f9 f9 00 f9 f9 f9
  0x555559830800: 00 f9 f9 f9 00 f9 f9 f9 00 f9 f9 f9 00 f9 f9 f9
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
```

Not present in 24.5. Most likely introduced in https://github.com/ClickHouse/ClickHouse/pull/63723 where I rewrote short circuit optimization internals

**Comment by Algunenano** [comment]
Confirmed I introduced it in https://github.com/ClickHouse/ClickHouse/pull/63723
