### ISSUE TITLE
LOGICAL_ERROR: Expected the argument №5 ('materialize(_CAST(5_LowCardinality(UInt8), 'LowCardinality(UInt8)'_String))' of type UInt8) to have 0 rows, but it has 2

### ISSUE THREAD

**Issue by devcrafter** [ClickHouse/ClickHouse#65867]
**Describe the bug**
https://s3.amazonaws.com/clickhouse-test-reports/65769/9a9c36cc5fd04c3b5df42be07bb32a295163f89f/ast_fuzzer__ubsan_.html

**How to reproduce**
```sql
SELECT
    concat('Int64', 5, 5, 5, 5, 5, 5, 5, 5, 5, materialize(materialize(5))),
    concat('Int64', 5, 5, toUInt256(5), materialize(5), 5, 5, 5, toNullable(5), toNullable(5)),
    concat(5, concat(concat('Int64', 5, toLowCardinality(5), 5, materialize(toLowCardinality(5)), 5, 5, 5), toNullable(5), toLowCardinality('Int64'), 5, 5, 5, 5, 5, 5, 5))
FROM remote('127.0.0.{2,2}')
GROUP BY 'Int64'
    WITH ROLLUP
```
```
[ip-10-2-2-126] 2024.06.30 18:02:50.576815 [ 1130631 ] {87f874cd-b8b6-4cdc-a667-19ec3b24b21c} <Error> executeQuery: Code: 49. DB::Exception: Expected the argument №5 ('materialize(_CAST(5_LowCardinality(UInt8), 'LowCardinality(UInt8)'_String))' of type UInt8) to have 0 rows, but it has 2. (LOGICAL_ERROR) (version 24.7.1.1) (from 127.0.0.1:64966) (in query: SELECT concat('Int64', 5, 5, 5, 5, 5, 5, 5, 5, 5, materialize(materialize(5))), concat('Int64', 5, 5, toUInt256(5), materialize(5), 5, 5, 5, toNullable(5), toNullable(5)), concat(5, concat(concat('Int64', 5, toLowCardinality(5), 5, materialize(toLowCardinality(5)), 5, 5, 5), toNullable(5), toLowCardinality('Int64'), 5, 5, 5, 5, 5, 5, 5)) FROM remote('127.0.0.{2,2}') GROUP BY 'Int64' WITH ROLLUP), Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(String const&, int) @ 0x0000000013b1d839
1. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000ad0d199
2. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x0000000005d0738c
3. DB::Exception::Exception<unsigned long, String const&, String, unsigned long&, unsigned long&>(int, FormatStringHelperImpl<std::type_identity<unsigned long>::type, std::type_identity<String const&>::type, std::type_identity<String>::type, std::type_identity<unsigned long&>::type, std::type_identity<unsigned long&>::type>, unsigned long&&, String const&, String&&, unsigned long&, unsigned long&) @ 0x000000000e6f8cb9
4. DB::checkFunctionArgumentSizes(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, unsigned long) @ 0x000000000e6f8a35
5. DB::IExecutableFunction::executeWithoutSparseColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000000e6ed95c
6. DB::IExecutableFunction::execute(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000000e6ee79b
7. DB::ActionsDAG::evaluatePartialResult(std::unordered_map<DB::ActionsDAG::Node const*, DB::ColumnWithTypeAndName, std::hash<DB::ActionsDAG::Node const*>, std::equal_to<DB::ActionsDAG::Node const*>, std::allocator<std::pair<DB::ActionsDAG::Node const* const, DB::ColumnWithTypeAndName>>>&, std::vector<DB::ActionsDAG::Node const*, std::allocator<DB::ActionsDAG::Node const*>> const&, unsigned long, bool) @ 0x000000000f53d78e
8. DB::ActionsDAG::updateHeader(DB::Block const&) const @ 0x000000000f53c608
9. DB::ExpressionTransform::transformHeader(DB::Block const&, DB::ActionsDAG const&) @ 0x00000000115df112
10. DB::ExpressionStep::ExpressionStep(DB::DataStream const&, std::shared_ptr<DB::ActionsDAG> const&) @ 0x000000001174d234
11. DB::(anonymous namespace)::addExpressionStep(DB::QueryPlan&, std::shared_ptr<DB::ActionsAndProjectInputsFlag> const&, String const&, std::vector<std::shared_ptr<DB::ActionsDAG>, std::allocator<std::shared_ptr<DB::ActionsDAG>>>&) @ 0x000000000ff268ed
12. DB::Planner::buildPlanForQueryNode() @ 0x000000000ff21b88
13. DB::Planner::buildQueryPlanIfNeeded() @ 0x000000000ff1bde7
14. DB::InterpreterSelectQueryAnalyzer::getQueryPlan() @ 0x000000000ff19fcd
15. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x00000000102d6782
16. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x00000000102d355a
17. DB::TCPHandler::runImpl() @ 0x00000000113147ab
18. DB::TCPHandler::run() @ 0x000000001132c6d9
19. Poco::Net::TCPServerConnection::start() @ 0x0000000013bc41e7
20. Poco::Net::TCPServerDispatcher::run() @ 0x0000000013bc46de
21. Poco::PooledThread::run() @ 0x0000000013b6eef2
22. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000013b6c9c3
23. ? @ 0x000078aa57694ac3
24. ? @ 0x000078aa57726850


Elapsed: 0.008 sec.

Received exception from server (version 24.7.1):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: Expected the argument №5 ('materialize(_CAST(5_LowCardinality(UInt8), 'LowCardinality(UInt8)'_String))' of type UInt8) to have 0 rows, but it has 2. (LOGICAL_ERROR)

```

**Comment by Algunenano** [comment]
Same issue as https://github.com/ClickHouse/ClickHouse/issues/64945 or https://github.com/ClickHouse/ClickHouse/issues/63006.

I'll close it since https://github.com/ClickHouse/ClickHouse/issues/63006 reproducer is almost the same.

**Comment by kssenii** [comment]
The same issue still happens
```
Logical error: \'\''Expected the argument №2 (\'\''_CAST(NULL_Nullable(String), \'\''Nullable(String)\'\''_String)\'\'' of type Nullable(String)) to have 2 rows, but it has 0\'\''.\\n [ 9488 ] {5a43977e-db9c-4538-b731-bb089b17387c} <Fatal> : Stack trace (when copying this message, always include the lines below):\\n [ 3793 ] {} <Fatal> Application: Child process was terminated by signal 6.\\n [ 9488 ] {5a43977e-db9c-4538-b731-bb089b17387c} <Fatal> : Logical error: \'\''Expected the argument №2 (\'\''_CAST(NULL_Nullable(String), \'\''Nullable(String)\'\''_String)\'\'' of type Nullable(String)) to have 2 rows, but it has 0\'\''.\\n
```
```
2024-07-31 00:26:38 Thread 797 "TCPHandler" received signal SIGABRT, Aborted.
2024-07-31 00:26:38 [Switching to Thread 0x7f4d101f0640 (LWP 9488)]
2024-07-31 00:26:38 0x00007f50a89bf9fc in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
2024-07-31 00:26:38 #0  0x00007f50a89bf9fc in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
2024-07-31 00:26:38 No symbol table info available.
2024-07-31 00:26:38 #1  0x00007f50a896b476 in raise () from /lib/x86_64-linux-gnu/libc.so.6
2024-07-31 00:26:38 No symbol table info available.
2024-07-31 00:26:38 #2  0x00007f50a89517f3 in abort () from /lib/x86_64-linux-gnu/libc.so.6
2024-07-31 00:26:38 No symbol table info available.
2024-07-31 00:26:38 #3  0x000000000c518e13 in DB::abortOnFailedAssertion (description=..., trace=<optimized out>, trace_offset=trace_offset@entry=0, trace_size=<optimized out>) at /build/src/Common/Exception.cpp:48
2024-07-31 00:26:38         logger = <optimized out>
2024-07-31 00:26:38 #4  0x000000000c5198d4 in DB::handle_error_code (msg=..., code=49, trace=..., remote=<optimized out>) at /build/src/Common/Exception.cpp:71
2024-07-31 00:26:38 No locals.
2024-07-31 00:26:38 #5  DB::Exception::Exception (this=0x7f4e11d40880, msg_masked=..., code=49, remote_=<optimized out>) at /build/src/Common/Exception.cpp:115
2024-07-31 00:26:38 No locals.
2024-07-31 00:26:38 #6  0x0000000006f3b16c in DB::Exception::Exception (this=0x7f4e11d40880, msg=..., code=49, remote_=false) at /build/src/Common/Exception.h:110
2024-07-31 00:26:38 No locals.
2024-07-31 00:26:38 #7  DB::Exception::Exception (this=0x7f4e11d40880, msg=..., code=49) at /build/src/Common/Exception.h:63
2024-07-31 00:26:39 No locals.
2024-07-31 00:26:39 #8  0x0000000006f5d059 in DB::Exception::Exception<unsigned long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long&, unsigned long&> (this=this@entry=0x7f4e11d40880, code=49, fmt=..., args=@0x7f4d101dcad0: 0, args=@0x7f4d101dcad0: 0, args=@0x7f4d101dcad0: 0, args=@0x7f4d101dcad0: 0, args=@0x7f4d101dcad0: 0) at /build/src/Common/Exception.h:128
2024-07-31 00:26:39 No locals.
2024-07-31 00:26:39 #9  0x0000000006f5c1a9 in DB::checkFunctionArgumentSizes (arguments=..., input_rows_count=2) at /build/src/Functions/FunctionHelpers.cpp:302
2024-07-31 00:26:40         current_size = 0
2024-07-31 00:26:40         i = <optimized out>
2024-07-31 00:26:40 #10 0x0000000007a92ad6 in DB::IExecutableFunction::executeWithoutSparseColumns (this=this@entry=0x7f4f401411c0, arguments=..., result_type=..., input_rows_count=input_rows_count@entry=0, dry_run=true) at /build/src/Functions/IFunction.cpp:279
2024-07-31 00:26:41         res = {<boost::intrusive_ptr<DB::IColumn const>> = {px = 0x0}, <No data fields>}
2024-07-31 00:26:41         res_indexes = {<boost::intrusive_ptr<DB::IColumn const>> = {px = 0x7f4e67ed8640}, <No data fields>}
2024-07-31 00:26:41         res_is_constant = <optimized out>
2024-07-31 00:26:41         can_be_executed_on_default_arguments = <optimized out>
2024-07-31 00:26:41         dictionary_type = <optimized out>
2024-07-31 00:26:41         new_input_rows_count = 2
2024-07-31 00:26:41         keys = {<boost::intrusive_ptr<DB::IColumn const>> = {px = 0x11cbcf76 <DB::recursiveRemoveSparse(COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&)+374>}, <No data fields>}
2024-07-31 00:26:41         res_mut_dictionary = {<boost::intrusive_ptr<DB::IColumnUnique>> = {px = 0x7f4d101dcdd0}, <No data fields>}
2024-07-31 00:26:41         indexes = {<boost::intrusive_ptr<DB::IColumn const>> = {px = 0x7f4f6de35320}, <No data fields>}
2024-07-31 00:26:41         res_dictionary = <optimized out>
2024-07-31 00:26:41         res_low_cardinality_type = 0x7f4e67fcfe18
2024-07-31 00:26:41         columns_without_low_cardinality = {__begin_ = 0x7f4e67eeb5e0, __end_ = 0x7f4e67eeb640, __end_cap_ = {<std::__1::__compressed_pair_elem<DB::ColumnWithTypeAndName*, 0, false>> = {__value_ = 0x7f4e67eeb640}, <std::__1::__compressed_pair_elem<std::__1::allocator<DB::ColumnWithTypeAndName>, 1, true>> = {<std::__1::allocator<DB::ColumnWithTypeAndName>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<DB::ColumnWithTypeAndName> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}
2024-07-31 00:26:41         result = {<boost::intrusive_ptr<DB::IColumn const>> = {px = 0x0}, <No data fields>}
2024-07-31 00:26:41 #11 0x0000000007a93825 in DB::IExecutableFunction::execute (this=0x7f4f401411c0, arguments=..., result_type=..., input_rows_count=0, dry_run=true) at /build/src/Functions/IFunction.cpp:380
2024-07-31 00:26:41         columns_without_sparse = {__begin_ = 0x7f4e67eeb640, __end_ = 0x7f4e67eeb6a0, __end_cap_ = {<std::__1::__compressed_pair_elem<DB::ColumnWithTypeAndName*, 0, false>> = {__value_ = 0x7f4e67eeb6a0}, <std::__1::__compressed_pair_elem<std::__1::allocator<DB::ColumnWithTypeAndName>, 1, true>> = {<std::__1::allocator<DB::ColumnWithTypeAndName>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<DB::ColumnWithTypeAndName> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}
2024-07-31 00:26:41         num_sparse_columns = <optimized out>
2024-07-31 00:26:41         num_full_columns = <optimized out>
2024-07-31 00:26:41         sparse_column_position = <optimized out>
2024-07-31 00:26:41         use_default_implementation_for_sparse_columns = <optimized out>
2024-07-31 00:26:41 #12 0x0000000010dd9101 in DB::executeActionForPartialResult (node=0x7f4e332c3770, arguments=..., input_rows_count=0) at /build/src/Interpreters/ActionsDAG.cpp:693
2024-07-31 00:26:42         res_column = {column = {<boost::intrusive_ptr<DB::IColumn const>> = {px = 0x0}, <No data fields>}, type = {__ptr_ = 0x7f4e67fcfe18, __cntrl_ = 0x7f4e67fcfe00}, name = {static __endian_factor = 1, __r_ = {<std::__1::__compressed_pair_elem<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__rep, 0, false>> = {__value_ = {{__l = {__data_ = 0x7f4e0271fec0 "concat(position(concat(_CAST('03'_String, 'String'_String), nullIf(1_UInt8, materialize(_CAST(1_LowCardinality(UInt8), 'LowCardinality(UInt8)'_String)))), _CAST('ca'_LowCardinality(Nullable(String)), "..., __size_ = 301, __cap_ = 304, __is_long_ = 1}, __s = {__data_ = "\300\376q\002N\177\000\000-\001\000\000\000\000\000\000\060\001\000\000\000\000", __padding_ = 0x7f4d101dcdcf "\200\340\205\355gN\177", __size_ = 0 '\000', __is_long_ = 1 '\001'}, __r = {__words = {139973025201856, 301, 9223372036854776112}}}}}, <std::__1::__compressed_pair_elem<std::__1::allocator<char>, 1, true>> = {<std::__1::allocator<char>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<char> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, static npos = 18446744073709551615}}
2024-07-31 00:26:42         column = <optimized out>
2024-07-31 00:26:42         key = <optimized out>
2024-07-31 00:26:42         array = <optimized out>
2024-07-31 00:26:42         data = <optimized out>
2024-07-31 00:26:42 #13 DB::ActionsDAG::evaluatePartialResult (node_to_column=..., outputs=..., input_rows_count=input_rows_count@entry=0, throw_on_error=true) at /build/src/Interpreters/ActionsDAG.cpp:863
2024-07-31 00:26:44         node = 0x7f4e332c3770
```

**Comment by kssenii** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/67459/d69f6cccde7633214eba48c08d7647e4ea9a40da/stress_test__debug_.html
https://s3.amazonaws.com/clickhouse-test-reports/67459/d69f6cccde7633214eba48c08d7647e4ea9a40da/stress_test__tsan_.html

**Comment by kssenii** [comment]
> Same issue as https://github.com/ClickHouse/ClickHouse/issues/64945 or https://github.com/ClickHouse/ClickHouse/issues/63006.

Not sure if I reopened correct issue...
