### ISSUE TITLE
assert(false) in `DB::DDLLoadingDependencyVisitor::extractTableNameFromArgument`

### ISSUE THREAD

**Issue by kssenii** [ClickHouse/ClickHouse#66390]
https://github.com/ClickHouse/ClickHouse/blob/1ebe1da7b9c03912245cb577d6370d6454078272/src/Databases/DDLLoadingDependencyVisitor.cpp#L216

https://s3.amazonaws.com/clickhouse-test-reports/66290/e5020690bed630e92253b632ce1b6aa8b21414b7/stateless_tests__debug__[1_2]/gdb.log

```
2024-07-11 12:10:08 Thread 1500 "TCPHandler" received signal SIGABRT, Aborted.
2024-07-11 12:10:08 [Switching to Thread 0x7fb7fef51640 (LWP 31176)]
2024-07-11 12:10:08 0x00007fc1166089fc in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
2024-07-11 12:10:08 #0  0x00007fc1166089fc in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
2024-07-11 12:10:08 No symbol table info available.
2024-07-11 12:10:08 #1  0x00007fc1165b4476 in raise () from /lib/x86_64-linux-gnu/libc.so.6
2024-07-11 12:10:08 No symbol table info available.
2024-07-11 12:10:08 #2  0x00007fc11659a7f3 in abort () from /lib/x86_64-linux-gnu/libc.so.6
2024-07-11 12:10:08 No symbol table info available.
2024-07-11 12:10:08 #3  0x00007fc11659a71b in ?? () from /lib/x86_64-linux-gnu/libc.so.6
2024-07-11 12:10:08 No symbol table info available.
2024-07-11 12:10:08 #4  0x00007fc1165abe96 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
2024-07-11 12:10:08 No symbol table info available.
2024-07-11 12:10:08 #5  0x0000000010a632d7 in DB::DDLLoadingDependencyVisitor::extractTableNameFromArgument (function=..., data=..., arg_idx=<optimized out>) at /build/src/Databases/DDLLoadingDependencyVisitor.cpp:216
2024-07-11 12:10:09         identifier = 0x0
2024-07-11 12:10:09         literal = <optimized out>
2024-07-11 12:10:09         function_arg = 0x0
2024-07-11 12:10:09         qualified_name = {database = {static __endian_factor = 1, __r_ = {<std::__1::__compressed_pair_elem<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__rep, 0, false>> = {__value_ = {{__l = {__data_ = 0x0, __size_ = 0, __cap_ = 0, __is_long_ = 0}, __s = {__data_ = '\000' <repeats 22 times>, __padding_ = 0x7fb7fef3dd87 "", __size_ = 0 '\000', __is_long_ = 0 '\000'}, __r = {__words = {0, 0, 0}}}}}, <std::__1::__compressed_pair_elem<std::__1::allocator<char>, 1, true>> = {<std::__1::allocator<char>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<char> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, static npos = 18446744073709551615}, table = {static __endian_factor = 1, __r_ = {<std::__1::__compressed_pair_elem<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__rep, 0, false>> = {__value_ = {{__l = {__data_ = 0x0, __size_ = 0, __cap_ = 0, __is_long_ = 0}, __s = {__data_ = '\000' <repeats 22 times>, __padding_ = 0x7fb7fef3dd9f "", __size_ = 0 '\000', __is_long_ = 0 '\000'}, __r = {__words = {0, 0, 0}}}}}, <std::__1::__compressed_pair_elem<std::__1::allocator<char>, 1, true>> = {<std::__1::allocator<char>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<char> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, static npos = 18446744073709551615}}
2024-07-11 12:10:09         arg = <optimized out>
2024-07-11 12:10:09 #6  0x0000000010a63575 in DB::InDepthNodeVisitor<DB::DDLLoadingDependencyVisitor, true, false, std::__1::shared_ptr<DB::IAST> const>::doVisit (this=this@entry=0x7fb7fef3df78, ast=...) at /build/src/Interpreters/InDepthNodeVisitor.h:71
2024-07-11 12:10:09         e = <optimized out>
2024-07-11 12:10:09 #7  0x0000000010a63721 in DB::InDepthNodeVisitor<DB::DDLLoadingDependencyVisitor, true, false, std::__1::shared_ptr<DB::IAST> const>::visitImplMain<false> (this=0x7fb7fef3df78, ast=...) at /build/src/Interpreters/InDepthNodeVisitor.h:61
2024-07-11 12:10:09 No locals.
2024-07-11 12:10:09 #8  DB::InDepthNodeVisitor<DB::DDLLoadingDependencyVisitor, true, false, std::__1::shared_ptr<DB::IAST> const>::visitImpl<false> (this=0x7fb7fef3df78, ast=...) at /build/src/Interpreters/InDepthNodeVisitor.h:51
2024-07-11 12:10:09 No locals.
2024-07-11 12:10:09 #9  DB::InDepthNodeVisitor<DB::DDLLoadingDependencyVisitor, true, false, std::__1::shared_ptr<DB::IAST> const>::visitChildren<false> (this=this@entry=0x7fb7fef3df78, ast=...) at /build/src/Interpreters/InDepthNodeVisitor.h:92
2024-07-11 12:10:09         need_visit_child = true
2024-07-11 12:10:09         child = @0x7fbf7f6aa838: {__ptr_ = 0x7fbe71365698, __cntrl_ = 0x7fbe71365680}
2024-07-11 12:10:09         __range3 = <optimized out>
2024-07-11 12:10:09         __begin0 = 0x7fbf7f6aa838
2024-07-11 12:10:09         __end0 = <optimized out>
2024-07-11 12:10:09 #10 0x0000000010a6372c in DB::InDepthNodeVisitor<DB::DDLLoadingDependencyVisitor, true, false, std::__1::shared_ptr<DB::IAST> const>::visitImplMain<false> (this=0x7fb7fef3df78, ast=...) at /build/src/Interpreters/InDepthNodeVisitor.h:64
2024-07-11 12:10:09 No locals.
2024-07-11 12:10:09 #11 DB::InDepthNodeVisitor<DB::DDLLoadingDependencyVisitor, true, false, std::__1::shared_ptr<DB::IAST> const>::visitImpl<false> (this=0x7fb7fef3df78, ast=...) at /build/src/Interpreters/InDepthNodeVisitor.h:51
2024-07-11 12:10:09 No locals.
2024-07-11 12:10:09 #12 DB::InDepthNodeVisitor<DB::DDLLoadingDependencyVisitor, true, false, std::__1::shared_ptr<DB::IAST> const>::visitChildren<false> (this=this@entry=0x7fb7fef3df78, ast=...) at /build/src/Interpreters/InDepthNodeVisitor.h:92
2024-07-11 12:10:09         need_visit_child = true
2024-07-11 12:10:09         child = @0x7fbe7ec069b8: {__ptr_ = 0x7fbf7f6aa818, __cntrl_ = 0x7fbf7f6aa800}
2024-07-11 12:10:09         __range3 = <optimized out>
2024-07-11 12:10:09         __begin0 = 0x7fbe7ec069b8
2024-07-11 12:10:09         __end0 = <optimized out>
2024-07-11 12:10:09 #13 0x0000000010a6372c in DB::InDepthNodeVisitor<DB::DDLLoadingDependencyVisitor, true, false, std::__1::shared_ptr<DB::IAST> const>::visitImplMain<false> (this=0x7fb7fef3df78, ast=...) at /build/src/Interpreters/InDepthNodeVisitor.h:64
2024-07-11 12:10:09 No locals.
2024-07-11 12:10:09 #14 DB::InDepthNodeVisitor<DB::DDLLoadingDependencyVisitor, true, false, std::__1::shared_ptr<DB::IAST> const>::visitImpl<false> (this=0x7fb7fef3df78, ast=...) at /build/src/Interpreters/InDepthNodeVisitor.h:51
2024-07-11 12:10:09 No locals.
2024-07-11 12:10:09 #15 DB::InDepthNodeVisitor<DB::DDLLoadingDependencyVisitor, true, false, std::__1::shared_ptr<DB::IAST> const>::visitChildren<false> (this=this@entry=0x7fb7fef3df78, ast=...) at /build/src/Interpreters/InDepthNodeVisitor.h:92
2024-07-11 12:10:10         need_visit_child = true
2024-07-11 12:10:10         child = @0x7fbf7f622948: {__ptr_ = 0x7fbe7ec06998, __cntrl_ = 0x7fbe7ec06980}
2024-07-11 12:10:10         __range3 = <optimized out>
2024-07-11 12:10:10         __begin0 = 0x7fbf7f622948
2024-07-11 12:10:10         __end0 = <optimized out>
2024-07-11 12:10:10 #16 0x0000000010a6372c in DB::InDepthNodeVisitor<DB::DDLLoadingDependencyVisitor, true, false, std::__1::shared_ptr<DB::IAST> const>::visitImplMain<false> (this=0x7fb7fef3df78, ast=...) at /build/src/Interpreters/InDepthNodeVisitor.h:64
2024-07-11 12:10:10 No locals.
2024-07-11 12:10:10 #17 DB::InDepthNodeVisitor<DB::DDLLoadingDependencyVisitor, true, false, std::__1::shared_ptr<DB::IAST> const>::visitImpl<false> (this=0x7fb7fef3df78, ast=...) at /build/src/Interpreters/InDepthNodeVisitor.h:51
2024-07-11 12:10:10 No locals.
2024-07-11 12:10:10 #18 DB::InDepthNodeVisitor<DB::DDLLoadingDependencyVisitor, true, false, std::__1::shared_ptr<DB::IAST> const>::visitChildren<false> (this=this@entry=0x7fb7fef3df78, ast=...) at /build/src/Interpreters/InDepthNodeVisitor.h:92
2024-07-11 12:10:10         need_visit_child = true
2024-07-11 12:10:10         child = @0x7fbe5e238d48: {__ptr_ = 0x7fbf7f622918, __cntrl_ = 0x7fbf7f622900}
2024-07-11 12:10:10         __range3 = <optimized out>
2024-07-11 12:10:10         __begin0 = 0x7fbe5e238d48
2024-07-11 12:10:10         __end0 = <optimized out>
2024-07-11 12:10:10 #19 0x0000000010a623dc in DB::InDepthNodeVisitor<DB::DDLLoadingDependencyVisitor, true, false, std::__1::shared_ptr<DB::IAST> const>::visitImplMain<false> (this=0x7fb7fef3df78, ast=...) at /build/src/Interpreters/InDepthNodeVisitor.h:64
2024-07-11 12:10:10 No locals.
2024-07-11 12:10:10 #20 DB::InDepthNodeVisitor<DB::DDLLoadingDependencyVisitor, true, false, std::__1::shared_ptr<DB::IAST> const>::visitImpl<false> (this=0x7fb7fef3df78, ast=...) at /build/src/Interpreters/InDepthNodeVisitor.h:51
2024-07-11 12:10:10 No locals.
2024-07-11 12:10:10 #21 DB::InDepthNodeVisitor<DB::DDLLoadingDependencyVisitor, true, false, std::__1::shared_ptr<DB::IAST> const>::visit (this=0x7fb7fef3df78, ast=...) at /build/src/Interpreters/InDepthNodeVisitor.h:32
2024-07-11 12:10:10 No locals.
```

**Comment by KochetovNicolai** [comment]
https://github.com/ClickHouse/ClickHouse/pull/66395
