### ISSUE TITLE
NullPointerException in C++

### ISSUE THREAD

**Issue by nikitamikhaylov** [ClickHouse/ClickHouse#66589]
**Describe the bug**
```
libc++abi: terminating due to uncaught exception of type Poco::NullPointerException: Null pointer
```

https://s3.amazonaws.com/clickhouse-test-reports/66549/5eaf10b4280818feaf957b4f1fd999a14724b122/stateless_tests__coverage__[3_5].html

**How to reproduce**

The core file is not debuggable and there is nothing in logs. Maybe this PR will help in the future https://github.com/ClickHouse/ClickHouse/pull/61109

**Comment by Algunenano** [comment]
The fact that the PR is changing the client code, and the crash is in the client is suspicious.

```
$ wget https://s3.amazonaws.com/clickhouse-builds/PRs/66549/5eaf10b4280818feaf957b4f1fd999a14724b122/package_release_coverage/clickhouse
$ chmod +x clickhouse
$ clickhouse local # To decompress
$ wget https://s3.amazonaws.com/clickhouse-test-reports/66549/5eaf10b4280818feaf957b4f1fd999a14724b122/stateless_tests__coverage__[3_5]/core.clickhouse-clie.37152-308408.zst
$ zstd -d core.clickhouse-clie.37152-308408.zstd
$ gdb clickhouse -c core.clickhouse-clie.37152-308408
```

```
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140054830083520) at ./nptl/pthread_kill.c:44
44      ./nptl/pthread_kill.c: No such file or directory.
[Current thread is 1 (Thread 0x7f610e656dc0 (LWP 37152))]
(gdb)  bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140054830083520) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140054830083520) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140054830083520, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007f610e789476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007f610e76f7f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x0000000024b1e346 in abort_message (format=0x14968ca "terminating due to %s exception of type %s: %s") at ./build_docker/./contrib/llvm-project/libcxxabi/src/abort_message.cpp:78
#6  0x0000000024b1e16d in demangling_terminate_handler () at ./build_docker/./contrib/llvm-project/libcxxabi/src/cxa_default_handlers.cpp:72
#7  0x0000000024b35583 in std::__terminate (func=0x9120) at ./build_docker/./contrib/llvm-project/libcxxabi/src/cxa_handlers.cpp:59
#8  0x0000000024b35cfd in __cxxabiv1::scan_eh_tab (results=..., actions=_UA_SEARCH_PHASE, native_exception=true, unwind_exception=unwind_exception@entry=0x7f60ff554b20, context=<optimized out>) at ./build_docker/./contrib/llvm-project/libcxxabi/src/cxa_personality.cpp:858
#9  0x0000000024b356ab in __gxx_personality_v0 (version=<optimized out>, actions=_UA_SEARCH_PHASE, exceptionClass=<optimized out>, unwind_exception=0x7f60ff554b20, context=0x7ffdafb50270) at ./build_docker/./contrib/llvm-project/libcxxabi/src/cxa_personality.cpp:958
#10 0x0000000024b3bb5e in unwind_phase1 (uc=0x7ffdafb50638, cursor=0x7ffdafb506e0, exception_object=0x7f60ff554b20) at ./build_docker/./contrib/libunwind/src/UnwindLevel1.c:137
#11 _Unwind_RaiseException (exception_object=0x7f60ff554b20) at ./build_docker/./contrib/libunwind/src/UnwindLevel1.c:413
#12 0x0000000024b34cc7 in __cxa_throw (thrown_object=0x7f60ff554b40, tinfo=0x45cd878 <typeinfo for Poco::NullPointerException>, dest=0x22c1f620 <Poco::Exception::~Exception()>) at ./build_docker/./contrib/llvm-project/libcxxabi/src/cxa_exception.cpp:279
#13 0x0000000022c1353b in Poco::Bugcheck::nullPointer (ptr=0x1566bda "_pInstance", file=0x144c3ee "base/poco/Util/include/Poco/Util/Application.h", line=<optimized out>) at ./build_docker/./base/poco/Foundation/src/Bugcheck.cpp:42
#14 0x000000001f9cfd86 in Poco::Util::Application::instance () at ./base/poco/Util/include/Poco/Util/Application.h:446
#15 DB::ClientApplicationBase::getInstance () at ./build_docker/./src/Client/ClientApplicationBase.cpp:59
#16 DB::interruptSignalHandler (signum=2) at ./build_docker/./src/Client/ClientApplicationBase.cpp:50
#17 <signal handler called>
#18 0x0000000016612689 in dumpCoverage()::$_0::operator()<std::__1::span<unsigned long const, 18446744073709551615ul> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::span<unsigned long const, 18446744073709551615ul>) const
    (name=..., span=..., this=<optimized out>) at ./build_docker/./src/Common/Coverage.cpp:43
#19 dumpCoverage () at ./build_docker/./src/Common/Coverage.cpp:61
#20 0x000000000ddd46bc in main (argc_=14, argv_=<optimized out>) at ./build_docker/./programs/main.cpp:251
```
