### ISSUE TITLE
MSAN: use-of-uninitialized-value in DB::ColumnConst::ColumnConst

### ISSUE THREAD

**Issue by nikitamikhaylov** [ClickHouse/ClickHouse#66964]
**Describe the bug**
Found here https://s3.amazonaws.com/clickhouse-test-reports/0/5611ef0d387e7c18a76dbcb1d1619d19ac60b501/ast_fuzzer__msan_.html

```
Uninitialized bytes in __msan_check_mem_is_initialized at offset 0 inside [0x709000b43a30, 8)
==174==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x55fb62372fdd in DB::ColumnConst::ColumnConst(COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&, unsigned long) build_docker/./src/Columns/ColumnConst.cpp:42:9
    #1 0x55fb37098bee in DB::IExecutableFunction::defaultImplementationForConstantArguments(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const (/workspace/clickhouse+0xb443bee) (BuildId: 504e16b938ef00bc65c0242343cc0490065bdf46)
    #2 0x55fb37099a4e in DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const (/workspace/clickhouse+0xb444a4e) (BuildId: 504e16b938ef00bc65c0242343cc0490065bdf46)
    #3 0x55fb3709bb2d in DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const (/workspace/clickhouse+0xb446b2d) (BuildId: 504e16b938ef00bc65c0242343cc0490065bdf46)
    #4 0x55fb370a205d in DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const (/workspace/clickhouse+0xb44d05d) (BuildId: 504e16b938ef00bc65c0242343cc0490065bdf46)
    #5 0x55fb5fe5ee51 in DB::QueryAnalyzer::resolveFunction(std::__1::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&) build_docker/./src/Analyzer/Resolve/QueryAnalyzer.cpp:3447:47
    #6 0x55fb5fdffb45 in DB::QueryAnalyzer::resolveExpressionNode(std::__1::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool, bool) build_docker/./src/Analyzer/Resolve/QueryAnalyzer.cpp:3747:46
    #7 0x55fb5fdfcdd0 in DB::QueryAnalyzer::resolveExpressionNodeList(std::__1::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool) build_docker/./src/Analyzer/Resolve/QueryAnalyzer.cpp:3905:49
    #8 0x55fb5fe9525f in DB::QueryAnalyzer::resolveProjectionExpressionNodeList(std::__1::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&) build_docker/./src/Analyzer/Resolve/QueryAnalyzer.cpp:4162:40
    #9 0x55fb5fde78a1 in DB::QueryAnalyzer::resolveQuery(std::__1::shared_ptr<DB::IQueryTreeNode> const&, DB::IdentifierResolveScope&) build_docker/./src/Analyzer/Resolve/QueryAnalyzer.cpp:5415:30
    #10 0x55fb5fde4305 in DB::QueryAnalyzer::resolve(std::__1::shared_ptr<DB::IQueryTreeNode>&, std::__1::shared_ptr<DB::IQueryTreeNode> const&, std::__1::shared_ptr<DB::Context const>) build_docker/./src/Analyzer/Resolve/QueryAnalyzer.cpp:137:13
    #11 0x55fb5fde270e in DB::QueryAnalysisPass::run(std::__1::shared_ptr<DB::IQueryTreeNode>&, std::__1::shared_ptr<DB::Context const>) build_docker/./src/Analyzer/Resolve/QueryAnalysisPass.cpp:18:14
    #12 0x55fb5fdd06f8 in DB::QueryTreePassManager::run(std::__1::shared_ptr<DB::IQueryTreeNode>) build_docker/./src/Analyzer/QueryTreePassManager.cpp:185:20
    #13 0x55fb60334a43 in DB::(anonymous namespace)::buildQueryTreeAndRunPasses(std::__1::shared_ptr<DB::IAST> const&, DB::SelectQueryOptions const&, std::__1::shared_ptr<DB::Context const> const&, std::__1::shared_ptr<DB::IStorage> const&) build_docker/./src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:142:33
    #14 0x55fb6032c08d in DB::InterpreterSelectQueryAnalyzer::InterpreterSelectQueryAnalyzer(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) build_docker/./src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:160:18
    #15 0x55fb60337894 in std::__1::__unique_if<DB::InterpreterSelectQueryAnalyzer>::__unique_single std::__1::make_unique[abi:v15007]<DB::InterpreterSelectQueryAnalyzer, std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context> const&, DB::SelectQueryOptions const&>(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context> const&, DB::SelectQueryOptions const&) build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:714:32
    #16 0x55fb60337012 in DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0::operator()(DB::InterpreterFactory::Arguments const&) const build_docker/./src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:270:16
    #17 0x55fb60337012 in decltype(std::declval<DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0&>()(std::declval<DB::InterpreterFactory::Arguments const&>())) std::__1::__invoke[abi:v15007]<DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0&, DB::InterpreterFactory::Arguments const&>(DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0&, DB::InterpreterFactory::Arguments const&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #18 0x55fb60337012 in std::__1::unique_ptr<DB::IInterpreter, std::__1::default_delete<DB::IInterpreter>> std::__1::__invoke_void_return_wrapper<std::__1::unique_ptr<DB::IInterpreter, std::__1::default_delete<DB::IInterpreter>>, false>::__call<DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0&, DB::InterpreterFactory::Arguments const&>(DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0&, DB::InterpreterFactory::Arguments const&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:470:16
    #19 0x55fb60337012 in std::__1::__function::__default_alloc_func<DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0, std::__1::unique_ptr<DB::IInterpreter, std::__1::default_delete<DB::IInterpreter>> (DB::InterpreterFactory::Arguments const&)>::operator()[abi:v15007](DB::InterpreterFactory::Arguments const&) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:235:12
    #20 0x55fb60337012 in std::__1::unique_ptr<DB::IInterpreter, std::__1::default_delete<DB::IInterpreter>> std::__1::__function::__policy_invoker<std::__1::unique_ptr<DB::IInterpreter, std::__1::default_delete<DB::IInterpreter>> (DB::InterpreterFactory::Arguments const&)>::__call_impl<std::__1::__function::__default_alloc_func<DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0, std::__1::unique_ptr<DB::IInterpreter, std::__1::default_delete<DB::IInterpreter>> (DB::InterpreterFactory::Arguments const&)>>(std::__1::__function::__policy_storage const*, DB::InterpreterFactory::Arguments const&) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716:16
    #21 0x55fb6019fc0b in std::__1::__function::__policy_func<std::__1::unique_ptr<DB::IInterpreter, std::__1::default_delete<DB::IInterpreter>> (DB::InterpreterFactory::Arguments const&)>::operator()[abi:v15007](DB::InterpreterFactory::Arguments const&) const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:848:16
    #22 0x55fb6019fc0b in std::__1::function<std::__1::unique_ptr<DB::IInterpreter, std::__1::default_delete<DB::IInterpreter>> (DB::InterpreterFactory::Arguments const&)>::operator()(DB::InterpreterFactory::Arguments const&) const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:1197:12
    #23 0x55fb6019fc0b in DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) build_docker/./src/Interpreters/InterpreterFactory.cpp:356:12
    #24 0x55fb60f2df76 in DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) build_docker/./src/Interpreters/executeQuery.cpp:1160:62
    #25 0x55fb60f22f5c in DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) build_docker/./src/Interpreters/executeQuery.cpp:1390:26
    #26 0x55fb65c3b737 in DB::TCPHandler::runImpl() build_docker/./src/Server/TCPHandler.cpp:521:54
    #27 0x55fb65c8bff0 in DB::TCPHandler::run() build_docker/./src/Server/TCPHandler.cpp:2366:9
    #28 0x55fb6b54033f in Poco::Net::TCPServerConnection::start() build_docker/./base/poco/Net/src/TCPServerConnection.cpp:43:3
    #29 0x55fb6b54127f in Poco::Net::TCPServerDispatcher::run() build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:115:20
    #30 0x55fb6b423314 in Poco::PooledThread::run() build_docker/./base/poco/Foundation/src/ThreadPool.cpp:205:14
    #31 0x55fb6b41fced in Poco::(anonymous namespace)::RunnableHolder::run() build_docker/./base/poco/Foundation/src/Thread.cpp:45:11
    #32 0x55fb6b41cbb0 in Poco::ThreadImpl::runnableEntry(void*) build_docker/./base/poco/Foundation/src/Thread_POSIX.cpp:335:27
    #33 0x7f18025c1ac2 in start_thread nptl/pthread_create.c:442:8
    #34 0x7f180265384f  misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

  Uninitialized value was stored to memory at
    #0 0x55fb361df41e in DB::FunctionJSONHelpers::Executor<DB::NameJSONExtractFloat, DB::JSONExtractFloat64Impl, DB::SimdJSONParser>::run(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, DB::FormatSettings const&) (/workspace/clickhouse+0xa58a41e) (BuildId: 504e16b938ef00bc65c0242343cc0490065bdf46)
    #1 0x55fb361ddaa5 in DB::ExecutableFunctionJSON<DB::NameJSONExtractFloat, DB::JSONExtractFloat64Impl>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/workspace/clickhouse+0xa588aa5) (BuildId: 504e16b938ef00bc65c0242343cc0490065bdf46)
    #2 0x55fb33dd2661 in DB::IExecutableFunction::executeDryRunImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/workspace/clickhouse+0x817d661) (BuildId: 504e16b938ef00bc65c0242343cc0490065bdf46)
    #3 0x55fb37099b70 in DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const (/workspace/clickhouse+0xb444b70) (BuildId: 504e16b938ef00bc65c0242343cc0490065bdf46)
    #4 0x55fb370988af in DB::IExecutableFunction::defaultImplementationForConstantArguments(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const (/workspace/clickhouse+0xb4438af) (BuildId: 504e16b938ef00bc65c0242343cc0490065bdf46)
    #5 0x55fb37099a4e in DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const (/workspace/clickhouse+0xb444a4e) (BuildId: 504e16b938ef00bc65c0242343cc0490065bdf46)
    #6 0x55fb3709bb2d in DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const (/workspace/clickhouse+0xb446b2d) (BuildId: 504e16b938ef00bc65c0242343cc0490065bdf46)
    #7 0x55fb370a205d in DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const (/workspace/clickhouse+0xb44d05d) (BuildId: 504e16b938ef00bc65c0242343cc0490065bdf46)
    #8 0x55fb5fe5ee51 in DB::QueryAnalyzer::resolveFunction(std::__1::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&) build_docker/./src/Analyzer/Resolve/QueryAnalyzer.cpp:3447:47
    #9 0x55fb5fdffb45 in DB::QueryAnalyzer::resolveExpressionNode(std::__1::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool, bool) build_docker/./src/Analyzer/Resolve/QueryAnalyzer.cpp:3747:46
    #10 0x55fb5fdfcdd0 in DB::QueryAnalyzer::resolveExpressionNodeList(std::__1::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool) build_docker/./src/Analyzer/Resolve/QueryAnalyzer.cpp:3905:49
    #11 0x55fb5fe9525f in DB::QueryAnalyzer::resolveProjectionExpressionNodeList(std::__1::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&) build_docker/./src/Analyzer/Resolve/QueryAnalyzer.cpp:4162:40
    #12 0x55fb5fde78a1 in DB::QueryAnalyzer::resolveQuery(std::__1::shared_ptr<DB::IQueryTreeNode> const&, DB::IdentifierResolveScope&) build_docker/./src/Analyzer/Resolve/QueryAnalyzer.cpp:5415:30
    #13 0x55fb5fde4305 in DB::QueryAnalyzer::resolve(std::__1::shared_ptr<DB::IQueryTreeNode>&, std::__1::shared_ptr<DB::IQueryTreeNode> const&, std::__1::shared_ptr<DB::Context const>) build_docker/./src/Analyzer/Resolve/QueryAnalyzer.cpp:137:13
    #14 0x55fb5fde270e in DB::QueryAnalysisPass::run(std::__1::shared_ptr<DB::IQueryTreeNode>&, std::__1::shared_ptr<DB::Context const>) build_docker/./src/Analyzer/Resolve/QueryAnalysisPass.cpp:18:14
    #15 0x55fb5fdd06f8 in DB::QueryTreePassManager::run(std::__1::shared_ptr<DB::IQueryTreeNode>) build_docker/./src/Analyzer/QueryTreePassManager.cpp:185:20
    #16 0x55fb60334a43 in DB::(anonymous namespace)::buildQueryTreeAndRunPasses(std::__1::shared_ptr<DB::IAST> const&, DB::SelectQueryOptions const&, std::__1::shared_ptr<DB::Context const> const&, std::__1::shared_ptr<DB::IStorage> const&) build_docker/./src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:142:33
    #17 0x55fb6032c08d in DB::InterpreterSelectQueryAnalyzer::InterpreterSelectQueryAnalyzer(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) build_docker/./src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:160:18
    #18 0x55fb60337894 in std::__1::__unique_if<DB::InterpreterSelectQueryAnalyzer>::__unique_single std::__1::make_unique[abi:v15007]<DB::InterpreterSelectQueryAnalyzer, std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context> const&, DB::SelectQueryOptions const&>(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context> const&, DB::SelectQueryOptions const&) build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:714:32
    #19 0x55fb60337012 in DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0::operator()(DB::InterpreterFactory::Arguments const&) const build_docker/./src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:270:16
    #20 0x55fb60337012 in decltype(std::declval<DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0&>()(std::declval<DB::InterpreterFactory::Arguments const&>())) std::__1::__invoke[abi:v15007]<DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0&, DB::InterpreterFactory::Arguments const&>(DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0&, DB::InterpreterFactory::Arguments const&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #21 0x55fb60337012 in std::__1::unique_ptr<DB::IInterpreter, std::__1::default_delete<DB::IInterpreter>> std::__1::__invoke_void_return_wrapper<std::__1::unique_ptr<DB::IInterpreter, std::__1::default_delete<DB::IInterpreter>>, false>::__call<DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0&, DB::InterpreterFactory::Arguments const&>(DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0&, DB::InterpreterFactory::Arguments const&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:470:16
    #22 0x55fb60337012 in std::__1::__function::__default_alloc_func<DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0, std::__1::unique_ptr<DB::IInterpreter, std::__1::default_delete<DB::IInterpreter>> (DB::InterpreterFactory::Arguments const&)>::operator()[abi:v15007](DB::InterpreterFactory::Arguments const&) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:235:12
    #23 0x55fb60337012 in std::__1::unique_ptr<DB::IInterpreter, std::__1::default_delete<DB::IInterpreter>> std::__1::__function::__policy_invoker<std::__1::unique_ptr<DB::IInterpreter, std::__1::default_delete<DB::IInterpreter>> (DB::InterpreterFactory::Arguments const&)>::__call_impl<std::__1::__function::__default_alloc_func<DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0, std::__1::unique_ptr<DB::IInterpreter, std::__1::default_delete<DB::IInterpreter>> (DB::InterpreterFactory::Arguments const&)>>(std::__1::__function::__policy_storage const*, DB::InterpreterFactory::Arguments const&) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716:16

  Uninitialized value was created by an allocation of 'value.i' in the stack frame
    #0 0x55fb361df35c in DB::FunctionJSONHelpers::Executor<DB::NameJSONExtractFloat, DB::JSONExtractFloat64Impl, DB::SimdJSONParser>::run(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, DB::FormatSettings const&) (/workspace/clickhouse+0xa58a35c) (BuildId: 504e16b938ef00bc65c0242343cc0490065bdf46)

SUMMARY: MemorySanitizer: use-of-uninitialized-value build_docker/./src/Columns/ColumnConst.cpp:42:9 in DB::ColumnConst::ColumnConst(COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&, unsigned long)
Exiting
```
**How to reproduce**
```
WITH '{ "v":1.1}' AS raw SELECT JSONExtract(raw, 'float') AS float32_1, JSONExtract(concat(tuple('1970-01-05', 10, materialize(10), 10, 10, 10, toUInt256(10), 10, toNullable(10), 10, 10), materialize(toUInt256(0)), ', ', 2, 2, toLowCardinality(toLowCardinality(2))), raw, toLowCardinality('v'), 'Float32') AS float32_2, JSONExtractFloat(raw) AS float64_1, JSONExtract(raw, 'v', 'double') AS float64_2
```

**Comment by nikitamikhaylov** [comment]
Looks like it failed after this PR was merged: https://github.com/ClickHouse/ClickHouse/pull/65298

**Comment by Algunenano** [comment]
I've reverted d3a269c locally and run the query and it still fails for me. I'll check older official builds to make sure

**Comment by Algunenano** [comment]
`v24.6.2.17-stable` looks fine, while master does not. Marking as blocker for 24.7

**Comment by Avogar** [comment]
Found the problem, will create a fix
