### ISSUE TITLE
LeakSanitizer: detected memory leaks in SchedulerThrottlerConstraint unit test

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#67678]
https://s3.amazonaws.com/clickhouse-test-reports/67610/582bcfdc03e1124500325c3104497719473657cc/stateless_tests__tsan__[1_4]/run.log

``` 
Direct leak of 316736 byte(s) in 4949 object(s) allocated from:
    #0 0x55c9c4a6cdbd in operator new(unsigned long) (/unit_tests_dbms+0x9c75dbd) (BuildId: ab10b1d291bd5e2eede9b86d354ff9896ff260bb)
    #1 0x55c9c4cacafb in DB::ResourceTestClass::enqueue(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::vector<long, std::__1::allocator<long>> const&) build_docker/./src/Common/Scheduler/Nodes/tests/ResourceTest.h:154:35
    #2 0x55c9c4ce1ed9 in SchedulerThrottlerConstraint_PeekAndAvgLimits_Test::TestBody() build_docker/./src/Common/Scheduler/Nodes/tests/gtest_throttler_constraint.cpp:130:11
    #3 0x55c9d607aa2b in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) build_docker/./contrib/googletest/googletest/src/gtest.cc:2635:10
    #4 0x55c9d607aa2b in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) build_docker/./contrib/googletest/googletest/src/gtest.cc:2671:14
    #5 0x55c9d607a740 in testing::Test::Run() build_docker/./contrib/googletest/googletest/src/gtest.cc:2710:5
    #6 0x55c9d607cf58 in testing::TestInfo::Run() build_docker/./contrib/googletest/googletest/src/gtest.cc:2856:11
    #7 0x55c9d607f9a4 in testing::TestSuite::Run() build_docker/./contrib/googletest/googletest/src/gtest.cc:3034:30
    #8 0x55c9d60aa12d in testing::internal::UnitTestImpl::RunAllTests() build_docker/./contrib/googletest/googletest/src/gtest.cc:5964:44
    #9 0x55c9d60a912b in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) build_docker/./contrib/googletest/googletest/src/gtest.cc:2635:10
    #10 0x55c9d60a912b in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) build_docker/./contrib/googletest/googletest/src/gtest.cc:2671:14
    #11 0x55c9d60a8c58 in testing::UnitTest::Run() build_docker/./contrib/googletest/googletest/src/gtest.cc:5543:10
    #12 0x55c9c4f186ff in RUN_ALL_TESTS() build_docker/./contrib/googletest/googletest/include/gtest/gtest.h:2334:73
    #13 0x55c9c4f186ff in main build_docker/./src/Common/tests/gtest_main.cpp:17:12
    #14 0x7fb22b565d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: 490fef8403240c91833978d494d39e537409b92e)

Direct leak of 121024 byte(s) in 1891 object(s) allocated from:
    #0 0x55c9c4a6cdbd in operator new(unsigned long) (/unit_tests_dbms+0x9c75dbd) (BuildId: ab10b1d291bd5e2eede9b86d354ff9896ff260bb)
    #1 0x55c9c4cacafb in DB::ResourceTestClass::enqueue(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::vector<long, std::__1::allocator<long>> const&) build_docker/./src/Common/Scheduler/Nodes/tests/ResourceTest.h:154:35
    #2 0x55c9c4ce2cc6 in SchedulerThrottlerConstraint_ThrottlerAndFairness_Test::TestBody() build_docker/./src/Common/Scheduler/Nodes/tests/gtest_throttler_constraint.cpp:157:11
    #3 0x55c9d607aa2b in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) build_docker/./contrib/googletest/googletest/src/gtest.cc:2635:10
    #4 0x55c9d607aa2b in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) build_docker/./contrib/googletest/googletest/src/gtest.cc:2671:14
    #5 0x55c9d607a740 in testing::Test::Run() build_docker/./contrib/googletest/googletest/src/gtest.cc:2710:5
    #6 0x55c9d607cf58 in testing::TestInfo::Run() build_docker/./contrib/googletest/googletest/src/gtest.cc:2856:11
    #7 0x55c9d607f9a4 in testing::TestSuite::Run() build_docker/./contrib/googletest/googletest/src/gtest.cc:3034:30
    #8 0x55c9d60aa12d in testing::internal::UnitTestImpl::RunAllTests() build_docker/./contrib/googletest/googletest/src/gtest.cc:5964:44
    #9 0x55c9d60a912b in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) build_docker/./contrib/googletest/googletest/src/gtest.cc:2635:10
    #10 0x55c9d60a912b in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) build_docker/./contrib/googletest/googletest/src/gtest.cc:2671:14
    #11 0x55c9d60a8c58 in testing::UnitTest::Run() build_docker/./contrib/googletest/googletest/src/gtest.cc:5543:10
    #12 0x55c9c4f186ff in RUN_ALL_TESTS() build_docker/./contrib/googletest/googletest/include/gtest/gtest.h:2334:73
    #13 0x55c9c4f186ff in main build_docker/./src/Common/tests/gtest_main.cpp:17:12
    #14 0x7fb22b565d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: 490fef8403240c91833978d494d39e537409b92e)

Direct leak of 65152 byte(s) in 1018 object(s) allocated from:
    #0 0x55c9c4a6cdbd in operator new(unsigned long) (/unit_tests_dbms+0x9c75dbd) (BuildId: ab10b1d291bd5e2eede9b86d354ff9896ff260bb)
    #1 0x55c9c4cacafb in DB::ResourceTestClass::enqueue(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::vector<long, std::__1::allocator<long>> const&) build_docker/./src/Common/Scheduler/Nodes/tests/ResourceTest.h:154:35
    #2 0x55c9c4ce2e0b in SchedulerThrottlerConstraint_ThrottlerAndFairness_Test::TestBody() build_docker/./src/Common/Scheduler/Nodes/tests/gtest_throttler_constraint.cpp:158:11
    #3 0x55c9d607aa2b in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) build_docker/./contrib/googletest/googletest/src/gtest.cc:2635:10
    #4 0x55c9d607aa2b in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) build_docker/./contrib/googletest/googletest/src/gtest.cc:2671:14
    #5 0x55c9d607a740 in testing::Test::Run() build_docker/./contrib/googletest/googletest/src/gtest.cc:2710:5
    #6 0x55c9d607cf58 in testing::TestInfo::Run() build_docker/./contrib/googletest/googletest/src/gtest.cc:2856:11
    #7 0x55c9d607f9a4 in testing::TestSuite::Run() build_docker/./contrib/googletest/googletest/src/gtest.cc:3034:30
    #8 0x55c9d60aa12d in testing::internal::UnitTestImpl::RunAllTests() build_docker/./contrib/googletest/googletest/src/gtest.cc:5964:44
    #9 0x55c9d60a912b in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) build_docker/./contrib/googletest/googletest/src/gtest.cc:2635:10
    #10 0x55c9d60a912b in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) build_docker/./contrib/googletest/googletest/src/gtest.cc:2671:14
    #11 0x55c9d60a8c58 in testing::UnitTest::Run() build_docker/./contrib/googletest/googletest/src/gtest.cc:5543:10
    #12 0x55c9c4f186ff in RUN_ALL_TESTS() build_docker/./contrib/googletest/googletest/include/gtest/gtest.h:2334:73
    #13 0x55c9c4f186ff in main build_docker/./src/Common/tests/gtest_main.cpp:17:12
    #14 0x7fb22b565d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: 490fef8403240c91833978d494d39e537409b92e)
...
```

**Comment by Algunenano** [comment]
I'm disabling the tests in the meantime: https://github.com/ClickHouse/ClickHouse/pull/67622/commits/146b8afce61ca2db2cdfd0621b0378746e90de59

**Comment by nikitamikhaylov** [comment]
As per this comment https://github.com/ClickHouse/ClickHouse/pull/69645#issuecomment-2429257187 I believe the issue is fixed.
