### ISSUE TITLE
24.8 S3Queue + Zookeeper 3.8 => Marshalling error

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#70376]
```
SELECT * FROM s3_files_queue SETTINGS stream_like_engine_allow_direct_select = 1
Query id: fb9598bc-0b03-45b5-b8e2-bea98cb9468b
Elapsed: 0.040 sec. 

Received exception from server (version 24.8.4):
Code: 999. DB::Exception: Received from localhost:9011. DB::Exception: Coordination error: Marshalling error: While executing ObjectStorageQueue. Stack trace:

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c2cb4e4
1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000763a89c
2. DB::Exception::Exception<char const*>(int, FormatStringHelperImpl<std::type_identity<char const*>::type>, char const*&&) @ 0x00000000099ac278
3. Coordination::Exception::Exception<char const*>(Coordination::Error, FormatStringHelperImpl<std::type_identity<char const*>::type>, char const*&&) @ 0x00000000113410b0
4. Coordination::Exception::Exception(Coordination::Error) @ 0x000000001134106c
5. zkutil::ZooKeeper::tryMulti(std::vector<std::shared_ptr<Coordination::Request>, std::allocator<std::shared_ptr<Coordination::Request>>> const&, std::vector<std::shared_ptr<Coordination::Response>, std::allocator<std::shared_ptr<Coordination::Response>>>&, bool) @ 0x000000001134fa7c
6. DB::ObjectStorageQueueUnorderedFileMetadata::setProcessingImpl() @ 0x0000000010b5e570
7. DB::ObjectStorageQueueIFileMetadata::setProcessing() @ 0x0000000010ae9220
8. DB::ObjectStorageQueueSource::FileIterator::nextImpl(unsigned long) @ 0x0000000010b6daac
9. DB::StorageObjectStorageSource::IIterator::next(unsigned long) @ 0x000000000eb8a9e8
10. DB::StorageObjectStorageSource::createReader(unsigned long, std::shared_ptr<DB::StorageObjectStorageSource::IIterator> const&, std::shared_ptr<DB::StorageObjectStorage::Configuration> const&, std::shared_ptr<DB::IObjectStorage> const&, DB::ReadFromFormatInfo&, std::optional<DB::FormatSettings> const&, std::shared_ptr<DB::KeyCondition const> const&, std::shared_ptr<DB::Context const> const&, DB::SchemaCache*, std::shared_ptr<Poco::Logger> const&, unsigned long, unsigned long, bool) @ 0x000000000eb88d54
11. DB::ObjectStorageQueueSource::generateImpl() @ 0x0000000010b75c34
12. DB::ObjectStorageQueueSource::generate() @ 0x0000000010b75900
13. DB::ISource::tryGenerate() @ 0x0000000010d1a76c
14. DB::ISource::work() @ 0x0000000010d1a454
15. DB::ExecutionThreadContext::executeTask() @ 0x0000000010d2ec90
16. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x0000000010d254d0
17. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreads()::$_0, void ()>>(std::__function::__policy_storage const*) @ 0x0000000010d269a4
18. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false, true>, void*>) @ 0x000000000c38953c
19. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000c38cf90
20. void* std::__thread_proxy[abi:v15007]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000c38bdac
21. start_thread @ 0x0000000000007624
22. ? @ 0x00000000000d162c
. (KEEPER_EXCEPTION)
```

In Zookeeper logs: 

```
2024-10-04 10:31:03,124 [myid:] - ERROR [ProcessThread(sid:0 cport:2181)::o.a.z.s.PrepRequestProcessor@951] - Failed to process sessionid:0x1000c356a16093d type:multi cxid:0x90 zxid:0xde12 txntype:14 reqpath:
java.io.IOException: Invalid type of op
	at org.apache.zookeeper.MultiOperationRecord.deserialize(MultiOperationRecord.java:162)
	at org.apache.zookeeper.server.ByteBufferInputStream.byteBuffer2Record(ByteBufferInputStream.java:78)
	at org.apache.zookeeper.server.PrepRequestProcessor.pRequestHelper(PrepRequestProcessor.java:832)
	at org.apache.zookeeper.server.PrepRequestProcessor.pRequest(PrepRequestProcessor.java:779)
	at org.apache.zookeeper.server.PrepRequestProcessor.run(PrepRequestProcessor.java:157)
```

See also https://github.com/ClickHouse/ClickHouse/issues/67895

**Comment by antonio2368** [comment]
Yeah, the problem is Keeper specific operation was used.
This should be caught by our CI, I will push a fix and hopefully with a fix for CI so we notice those issues instantly.

**Comment by filimonov** [comment]
Yep, i thought the same, but the mutlitransanction in the code looks quite simple (contains a sequence of Create / Remove / Set) 

https://github.com/ClickHouse/ClickHouse/blob/1d689518ff3a7d8b6fb14769d8633e081c066dad/src/Storages/ObjectStorageQueue/ObjectStorageQueueUnorderedFileMetadata.cpp#L57-L67

**Comment by antonio2368** [comment]
the devil is in the details :smile: 
last create request has `/* ignore_if_exists */true` which will produce `CreateIfNotExists` request, a Keeper-specific request

**Comment by jkilpatrick-twilio** [comment]
My team and I just ran into this very problem as well.  I assume there is currently no work-around other than "Switch to Keeper" which currently isn't an option for us?  Thank you!

**Comment by PedroTadim** [comment]
Hello! I just hit this error too with:

```sql
CREATE DATABASE d1 ENGINE = Replicated('<set replicated params>');
CREATE MATERIALIZED VIEW d1.v0 REFRESH AFTER 1 SECOND RANDOMIZE FOR 2 SECOND APPEND ENGINE = MergeTree() ORDER BY tuple() AS (SELECT 1, 2);
```
Stack trace
```
Error on processing query 'CREATE MATERIALIZED VIEW d1.v0 REFRESH AFTER 1 SECOND RANDOMIZE FOR 2 SECOND APPEND ENGINE = MergeTree ORDER BY tuple() AS SELECT 1, 2': Received from localhost:9000. Coordination::Exception. Coordination::Exception: Coordination error: Marshalling error. Stack trace:

0. std::exception::exception[abi:v15007]() @ 0x0000000019546af4
1. base/poco/Foundation/src/Exception.cpp:27: Poco::Exception::Exception(String const&, int) @ 0x00000000393467a0
2. src/Common/Exception.cpp:105: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000002630746b
3. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x00000000193e47b6
4. src/Common/Exception.h:123: Coordination::Exception::Exception<char const*>(Coordination::Error, FormatStringHelperImpl<std::type_identity<char const*>::type>, char const*&&) @ 0x0000000036b7a2dc
5. src/Common/ZooKeeper/IKeeper.cpp:52: Coordination::Exception::Exception(Coordination::Error) @ 0x0000000036b78999
6. src/Common/ZooKeeper/ZooKeeper.cpp:1617: zkutil::KeeperMultiException::check(Coordination::Error, std::vector<std::shared_ptr<Coordination::Request>, std::allocator<std::shared_ptr<Coordination::Request>>> const&, std::vector<std::shared_ptr<Coordination::Response>, std::allocator<std::shared_ptr<Coordination::Response>>> const&) @ 0x0000000036b8bc77
7. src/Common/ZooKeeper/ZooKeeper.cpp:807: zkutil::ZooKeeper::multi(std::vector<std::shared_ptr<Coordination::Request>, std::allocator<std::shared_ptr<Coordination::Request>>> const&, bool) @ 0x0000000036b8bb1c
8. src/Storages/MaterializedView/RefreshTask.cpp:101: DB::RefreshTask::RefreshTask(DB::StorageMaterializedView*, std::shared_ptr<DB::Context const>, DB::ASTRefreshStrategy const&, bool, bool, bool) @ 0x000000003590aeb9
9. contrib/llvm-project/libcxx/include/__memory/construct_at.h:35: DB::RefreshTask* std::construct_at[abi:v15007]<DB::RefreshTask, DB::StorageMaterializedView*&, std::shared_ptr<DB::Context>&, DB::ASTRefreshStrategy const&, bool&, bool&, bool&, DB::RefreshTask*>(DB::RefreshTask*, DB::StorageMaterializedView*&, std::shared_ptr<DB::Context>&, DB::ASTRefreshStrategy const&, bool&, bool&, bool&) @ 0x000000003591c678
10. contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:298: std::__shared_ptr_emplace<DB::RefreshTask, std::allocator<DB::RefreshTask>>::__shared_ptr_emplace[abi:v15007]<DB::StorageMaterializedView*&, std::shared_ptr<DB::Context>&, DB::ASTRefreshStrategy const&, bool&, bool&, bool&>(std::allocator<DB::RefreshTask>, DB::StorageMaterializedView*&, std::shared_ptr<DB::Context>&, DB::ASTRefreshStrategy const&, bool&, bool&, bool&) @ 0x000000003591c1f3
11. contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:953: std::shared_ptr<DB::RefreshTask> std::allocate_shared[abi:v15007]<DB::RefreshTask, std::allocator<DB::RefreshTask>, DB::StorageMaterializedView*&, std::shared_ptr<DB::Context>&, DB::ASTRefreshStrategy const&, bool&, bool&, bool&, void>(std::allocator<DB::RefreshTask> const&, DB::StorageMaterializedView*&, std::shared_ptr<DB::Context>&, DB::ASTRefreshStrategy const&, bool&, bool&, bool&) @ 0x000000003591c02b
12. contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:962: DB::RefreshTask::create(DB::StorageMaterializedView*, std::shared_ptr<DB::Context>, DB::ASTRefreshStrategy const&, bool, bool, bool) @ 0x000000003590c78e
13. src/Storages/StorageMaterializedView.cpp:226: DB::StorageMaterializedView::StorageMaterializedView(DB::StorageID const&, std::shared_ptr<DB::Context const>, DB::ASTCreateQuery const&, DB::ColumnsDescription const&, DB::LoadingStrictnessLevel, String const&) @ 0x0000000034a70ffc
14. contrib/llvm-project/libcxx/include/__memory/construct_at.h:35: std::__shared_ptr_emplace<DB::StorageMaterializedView, std::allocator<DB::StorageMaterializedView>>::__shared_ptr_emplace[abi:v15007]<DB::StorageID const&, std::shared_ptr<DB::Context>, DB::ASTCreateQuery const&, DB::ColumnsDescription const&, DB::LoadingStrictnessLevel const&, String const&>(std::allocator<DB::StorageMaterializedView>, DB::StorageID const&, std::shared_ptr<DB::Context>&&, DB::ASTCreateQuery const&, DB::ColumnsDescription const&, DB::LoadingStrictnessLevel const&, String const&) @ 0x0000000034a86d5c
15. contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:953: std::shared_ptr<DB::StorageMaterializedView> std::allocate_shared[abi:v15007]<DB::StorageMaterializedView, std::allocator<DB::StorageMaterializedView>, DB::StorageID const&, std::shared_ptr<DB::Context>, DB::ASTCreateQuery const&, DB::ColumnsDescription const&, DB::LoadingStrictnessLevel const&, String const&, void>(std::allocator<DB::StorageMaterializedView> const&, DB::StorageID const&, std::shared_ptr<DB::Context>&&, DB::ASTCreateQuery const&, DB::ColumnsDescription const&, DB::LoadingStrictnessLevel const&, String const&) @ 0x0000000034a86b4a
16. contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:962: std::shared_ptr<DB::IStorage> std::__function::__policy_invoker<std::shared_ptr<DB::IStorage> (DB::StorageFactory::Arguments const&)>::__call_impl<std::__function::__default_alloc_func<DB::registerStorageMaterializedView(DB::StorageFactory&)::$_0, std::shared_ptr<DB::IStorage> (DB::StorageFactory::Arguments const&)>>(std::__function::__policy_storage const*, DB::StorageFactory::Arguments const&) @ 0x0000000034a8380f
17. contrib/llvm-project/libcxx/include/__functional/function.h:848: ? @ 0x000000003496937f
18. src/Interpreters/InterpreterCreateQuery.cpp:1878: DB::InterpreterCreateQuery::doCreateTable(DB::ASTCreateQuery&, DB::InterpreterCreateQuery::TableProperties const&, std::unique_ptr<DB::DDLGuard, std::default_delete<DB::DDLGuard>>&, DB::LoadingStrictnessLevel) @ 0x0000000032615cda
19. src/Interpreters/InterpreterCreateQuery.cpp:1694: DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0x000000003260b30f
20. src/Interpreters/InterpreterCreateQuery.cpp:2265: DB::InterpreterCreateQuery::execute() @ 0x0000000032620d65
21. src/Interpreters/executeQuery.cpp:1368: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x00000000330ff243
22. src/Interpreters/executeQuery.cpp:1667: DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::shared_ptr<DB::Context>, std::function<void (DB::QueryResultDetails const&)>, DB::QueryFlags, std::optional<DB::FormatSettings> const&, std::function<void (DB::IOutputFormat&, String const&, std::shared_ptr<DB::Context const> const&, std::optional<DB::FormatSettings> const&)>) @ 0x000000003310477c
23. src/Interpreters/DDLWorker.cpp:508: DB::DDLWorker::tryExecuteQuery(DB::DDLTaskBase&, std::shared_ptr<zkutil::ZooKeeper> const&) @ 0x0000000031f8432e
24. src/Interpreters/DDLWorker.cpp:672: DB::DDLWorker::processTask(DB::DDLTaskBase&, std::shared_ptr<zkutil::ZooKeeper> const&) @ 0x0000000031f8133c
25. src/Databases/DatabaseReplicatedWorker.cpp:364: DB::DatabaseReplicatedDDLWorker::tryEnqueueAndExecuteEntry(DB::DDLLogEntry&, std::shared_ptr<DB::Context const>) @ 0x000000003160c30c
26. src/Databases/DatabaseReplicated.cpp:1086: DB::DatabaseReplicated::tryEnqueueReplicatedDDL(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const>, DB::QueryFlags) @ 0x00000000315d189e
27. src/Interpreters/InterpreterCreateQuery.cpp:1674: DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0x000000003260aae1
28. src/Interpreters/InterpreterCreateQuery.cpp:2265: DB::InterpreterCreateQuery::execute() @ 0x0000000032620d65
29. src/Interpreters/executeQuery.cpp:1368: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x00000000330ff243
30. src/Interpreters/executeQuery.cpp:1535: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x00000000330f914e
31. src/Server/TCPHandler.cpp:656: DB::TCPHandler::runImpl() @ 0x0000000035b8ee5c
```
Am I doing something wrong?
