### ISSUE TITLE
Failure in SASL_SSL Connection from Clickhouse to Kafka on v24.4 and above

### ISSUE THREAD

**Issue by ilugid** [ClickHouse/ClickHouse#70400]
Up until v24.3 a kafka table with sasl_ssl configurations described in kafka.xml file was able to initiate a connection to a broker with SASL_SSL listener.

It can be reproduced on any version over 24.3
  - 24.8.4.13
  - ...
  - ...
  - 24.4.1.2088

**How to reproduce**

```
CREATE TABLE default.kafka_check
(
    `payload` String
)
ENGINE = MergeTree
ORDER BY tuple()
```

```
CREATE TABLE default.kafka_check_kafka
(
    `payload` String
)
ENGINE = Kafka
SETTINGS kafka_broker_list = 'broker:9092',
         kafka_topic_list = 'test-topic',
         kafka_group_name = 'server_test-topic',
         kafka_format = 'RawBLOB'
```

```
CREATE MATERIALIZED VIEW default.kafka_check_mv TO default.kafka_check
(
    `payload` String
)
AS SELECT payload
FROM default.kafka_check_kafka
```
/etc/clickhouse-server/config.d/kafka.xml

```
<clickhouse>
    <kafka>
        <enable_ssl_certificate_verification>false</enable_ssl_certificate_verification>
        <ssl_endpoint_identification_algorithm>none</ssl_endpoint_identification_algorithm>
        <debug>all</debug>
    </kafka>
    <kafka_test-topic>
        <sasl_username>username</sasl_username>
        <sasl_password>password</sasl_password>
        <security_protocol>sasl_ssl</security_protocol>
        <sasl_mechanisms>PLAIN</sasl_mechanisms>
    </kafka_test-topic>
</clickhouse>
```

Now we can publish to the kafka topic on the broker:

```
cat << EOF > /tmp/client.properties
ssl.endpoint.identification.algorithm=
security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
  username="username" \
  password="password";
EOF
```

```
kafka-topics.sh --bootstrap-server broker:9092 --create --topic test-topic --command-config /tmp/client.properties
kafka-console-producer.sh --bootstrap-server broker:9092 --topic test-topic --producer.config /tmp/client.properties
>entry_1
>entry_2
```

**Expected behavior**
Upto v24.3*, we see the entries being populated in Clickhouse table. However, once the version is updated to 24.4* and above, we start to see errors in both Clickhouse and Kafka.

**Error message and/or stacktrace**

 - Clickhouse

```
2024.10.04 03:46:23.720681 [ 865943 ] {} <Error> StorageKafka (kafka_check_kafka): [client.id:ClickHouse-broker-default-kafka_check_kafka] [rdk:ERROR] [thrd:broker:9092/bootstrap]: 1/1 brokers are down
2024.10.04 03:46:23.720800 [ 865738 ] {} <Error> StorageKafka (kafka_check_kafka): [client.id:ClickHouse-broker-default-kafka_check_kafka] [rdk:ERROR] [thrd:app]: ClickHouse-broker-default-kafka_check_kafka#consumer-2: broker:9092/bootstrap: Disconnected while requesting ApiVersion: might be caused by incorrect security.protocol configuration (connecting to a SSL listener?) or broker version is < 0.10 (see api.version.request) (after 2ms in state APIVERSION_QUERY)
2024.10.04 03:46:23.902096 [ 865943 ] {} <Information> StorageKafka (kafka_check_kafka): [client.id:ClickHouse-broker-default-kafka_check_kafka] [rdk:FAIL] [thrd:broker:9092/bootstrap]: broker:9092/bootstrap: Disconnected while requesting ApiVersion: might be caused by incorrect security.protocol configuration (connecting to a SSL listener?) or broker version is < 0.10 (see api.version.request) (after 2ms in state APIVERSION_QUERY, 1 identical error(s) suppressed)
```

 - Kafka
 
```
[2024-10-05 05:00:53,286] INFO [SocketServer listenerType=BROKER, nodeId=1] Failed authentication with /10.10.10.11 (channelId=10.10.10.11:9092-10.10.10.11:44428-298) (SSL handshake failed) (org.apache.kafka.common.network.Selector)
javax.net.ssl|WARNING|36|data-plane-kafka-network-thread-1-ListenerName(BROKER)-SASL_SSL-1|2024-10-05 05:00:53.286 UTC|SSLEngineOutputRecord.java:182|outbound has closed, ignore outbound application data
javax.net.ssl|ERROR|37|data-plane-kafka-network-thread-1-ListenerName(BROKER)-SASL_SSL-2|2024-10-05 05:01:03.289 UTC|TransportContext.java:352|Fatal (INTERNAL_ERROR): problem unwrapping net record (
"throwable" : {
  javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
        at java.base/sun.security.ssl.SSLEngineInputRecord.bytesInCompletePacket(SSLEngineInputRecord.java:146)
        at java.base/sun.security.ssl.SSLEngineInputRecord.bytesInCompletePacket(SSLEngineInputRecord.java:64)
        at java.base/sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:557)
        at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:454)
        at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:433)
        at java.base/javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:637)
        at org.apache.kafka.common.network.SslTransportLayer.handshakeUnwrap(SslTransportLayer.java:527)
        at org.apache.kafka.common.network.SslTransportLayer.doHandshake(SslTransportLayer.java:381)
        at org.apache.kafka.common.network.SslTransportLayer.handshake(SslTransportLayer.java:301)
        at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:178)
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:547)
        at org.apache.kafka.common.network.Selector.poll(Selector.java:485)
        at kafka.network.Processor.poll(SocketServer.scala:1111)
        at kafka.network.Processor.run(SocketServer.scala:1015)
        at java.base/java.lang.Thread.run(Thread.java:829)}
)
```

**Additional context**

When we run **tcpdump** on connections from a v24.3 vs v24.4 and above including 24.9, we see a difference in the interaction.
24.3 and below we see the information from the certificate being exchanged, however in 24.4 and above, there is no such exchange. It seems like a **PLAIN Text connection is being initiated to a SASL_SSL listener**.

**Comment by antaljanosbenjamin** [comment]
The config is probably broken by https://github.com/ClickHouse/ClickHouse/pull/58956. I don't see yet how though, will check it out as soon as I can finish more urgent fixes. In the meantime you can try to use the new config, that should work.

**Comment by ilugid** [comment]
Moving individual topic definitions into parent <kafka> ... </kafka> block helped. Until prior versions they were separate blocks.
