### ISSUE TITLE
MSAN: MemorySanitizer: use-of-uninitialized-value in unit test SchedulerRoot_Cancel_Test

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#70504]
https://s3.amazonaws.com/clickhouse-test-reports/70464/d57f0a9d37ea98067a6f77bd07ce1b391440c154/unit_tests__msan_/run.log

```
==19==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x55555d7218b1 in bool std::__1::__libcpp_thread_poll_with_backoff[abi:v15007]<std::__1::__barrier_base<std::__1::__empty_completion>::wait[abi:v15007](unsigned char&&) const::'lambda'() const&, std::__1::__libcpp_timed_backoff_policy>(std::__1::__barrier_base<std::__1::__empty_completion>::wait[abi:v15007](unsigned char&&) const::'lambda'() const&, std::__1::__libcpp_timed_backoff_policy&&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l>>) build_docker/./contrib/llvm-project/libcxx/include/__thread/poll_with_backoff.h:44:11
    #1 0x55555d77fee6 in std::__1::__barrier_base<std::__1::__empty_completion>::wait[abi:v15007](unsigned char&&) const build_docker/./contrib/llvm-project/libcxx/include/barrier:152:9
    #2 0x55555d77fee6 in std::__1::barrier<std::__1::__empty_completion>::wait[abi:v15007](unsigned char&&) const build_docker/./contrib/llvm-project/libcxx/include/barrier:310:13
    #3 0x55555d77fee6 in std::__1::barrier<std::__1::__empty_completion>::arrive_and_wait[abi:v15007]() build_docker/./contrib/llvm-project/libcxx/include/barrier:315:9
    #4 0x55555d77fee6 in SchedulerRoot_Cancel_Test::TestBody()::$_0::operator()() const::'lambda'()::operator()() const build_docker/./src/Common/Scheduler/Nodes/tests/gtest_resource_scheduler.cpp:195:27
    #5 0x55555d77fee6 in decltype(std::declval<SchedulerRoot_Cancel_Test::TestBody()::$_0::operator()() const::'lambda'()&>()()) std::__1::__invoke[abi:v15007]<SchedulerRoot_Cancel_Test::TestBody()::$_0::operator()() const::'lambda'()&>(SchedulerRoot_Cancel_Test::TestBody()::$_0::operator()() const::'lambda'()&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #6 0x55555d77fee6 in void std::__1::__invoke_void_return_wrapper<void, true>::__call<SchedulerRoot_Cancel_Test::TestBody()::$_0::operator()() const::'lambda'()&>(SchedulerRoot_Cancel_Test::TestBody()::$_0::operator()() const::'lambda'()&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:479:9
    #7 0x55555d77fee6 in std::__1::__function::__default_alloc_func<SchedulerRoot_Cancel_Test::TestBody()::$_0::operator()() const::'lambda'(), void ()>::operator()[abi:v15007]() build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:235:12
    #8 0x55555d77fee6 in void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<SchedulerRoot_Cancel_Test::TestBody()::$_0::operator()() const::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716:16
    #9 0x55555d793bcb in std::__1::__function::__policy_func<void ()>::operator()[abi:v15007]() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:848:16
    #10 0x55555d793bcb in std::__1::function<void ()>::operator()() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:1197:12
    #11 0x55555d793bcb in MyRequest::execute() build_docker/./src/Common/Scheduler/Nodes/tests/gtest_resource_scheduler.cpp:102:13
    #12 0x55555d7874ae in DB::SchedulerRoot::execute(DB::ResourceRequest*) build_docker/./src/Common/Scheduler/SchedulerRoot.h:251:18
    #13 0x55555d7874ae in DB::SchedulerRoot::schedulerThread() build_docker/./src/Common/Scheduler/SchedulerRoot.h:240:17
    #14 0x55555d7870ae in DB::SchedulerRoot::start()::'lambda'()::operator()() const build_docker/./src/Common/Scheduler/SchedulerRoot.h:69:55
    #15 0x55555d7870ae in decltype(std::declval<DB::SchedulerRoot::start()::'lambda'()&>()()) std::__1::__invoke[abi:v15007]<DB::SchedulerRoot::start()::'lambda'()&>(DB::SchedulerRoot::start()::'lambda'()&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #16 0x55555d7870ae in decltype(auto) std::__1::__apply_tuple_impl[abi:v15007]<DB::SchedulerRoot::start()::'lambda'()&, std::__1::tuple<>&>(DB::SchedulerRoot::start()::'lambda'()&, std::__1::tuple<>&, std::__1::__tuple_indices<...>) build_docker/./contrib/llvm-project/libcxx/include/tuple:1789:1
    #17 0x55555d7870ae in decltype(auto) std::__1::apply[abi:v15007]<DB::SchedulerRoot::start()::'lambda'()&, std::__1::tuple<>&>(DB::SchedulerRoot::start()::'lambda'()&, std::__1::tuple<>&) build_docker/./contrib/llvm-project/libcxx/include/tuple:1798:1
    #18 0x55555d7870ae in ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::SchedulerRoot::start()::'lambda'()>(DB::SchedulerRoot::start()::'lambda'()&&)::'lambda'()::operator()() build_docker/./src/Common/ThreadPool.h:311:13
    #19 0x55555d786efe in decltype(std::declval<DB::SchedulerRoot::start()::'lambda'()>()()) std::__1::__invoke[abi:v15007]<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::SchedulerRoot::start()::'lambda'()>(DB::SchedulerRoot::start()::'lambda'()&&)::'lambda'()&>(DB::SchedulerRoot::start()::'lambda'()&&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #20 0x55555d786efe in void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::SchedulerRoot::start()::'lambda'()>(DB::SchedulerRoot::start()::'lambda'()&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::SchedulerRoot::start()::'lambda'()>(DB::SchedulerRoot::start()::'lambda'()&&)::'lambda'()&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:479:9
    #21 0x55555d786efe in std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::SchedulerRoot::start()::'lambda'()>(DB::SchedulerRoot::start()::'lambda'()&&)::'lambda'(), void ()>::operator()[abi:v15007]() build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:235:12
    #22 0x55555d786efe in void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::SchedulerRoot::start()::'lambda'()>(DB::SchedulerRoot::start()::'lambda'()&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716:16
    #23 0x555596a0319c in std::__1::__function::__policy_func<void ()>::operator()[abi:v15007]() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:848:16
    #24 0x555596a0319c in std::__1::function<void ()>::operator()() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:1197:12
    #25 0x555596a0319c in ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::worker() build_docker/./src/Common/ThreadPool.cpp:785:17
    #26 0x555596a15e23 in decltype(*std::declval<ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*>().*std::declval<void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)()>()()) std::__1::__invoke[abi:v15007]<void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*, void>(void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*&&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:359:23
    #27 0x555596a15e23 in void std::__1::__thread_execute[abi:v15007]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*, 2ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*>&, std::__1::__tuple_indices<2ul>) build_docker/./contrib/llvm-project/libcxx/include/thread:284:5
    #28 0x555596a15e23 in void* std::__1::__thread_proxy[abi:v15007]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*>>(void*) build_docker/./contrib/llvm-project/libcxx/include/thread:295:5
    #29 0x7ffff7e18ac2  (/lib/x86_64-linux-gnu/libc.so.6+0x94ac2) (BuildId: 490fef8403240c91833978d494d39e537409b92e)
    #30 0x7ffff7eaa84f  (/lib/x86_64-linux-gnu/libc.so.6+0x12684f) (BuildId: 490fef8403240c91833978d494d39e537409b92e)

  Uninitialized value was stored to memory at
    #0 0x55555d7218aa in std::__1::__barrier_base<std::__1::__empty_completion>::wait[abi:v15007](unsigned char&&) const::'lambda'()::operator()() const build_docker/./contrib/llvm-project/libcxx/include/barrier:150:56
    #1 0x55555d7218aa in bool std::__1::__libcpp_thread_poll_with_backoff[abi:v15007]<std::__1::__barrier_base<std::__1::__empty_completion>::wait[abi:v15007](unsigned char&&) const::'lambda'() const&, std::__1::__libcpp_timed_backoff_policy>(std::__1::__barrier_base<std::__1::__empty_completion>::wait[abi:v15007](unsigned char&&) const::'lambda'() const&, std::__1::__libcpp_timed_backoff_policy&&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l>>) build_docker/./contrib/llvm-project/libcxx/include/__thread/poll_with_backoff.h:44:11
    #2 0x55555d77fee6 in std::__1::__barrier_base<std::__1::__empty_completion>::wait[abi:v15007](unsigned char&&) const build_docker/./contrib/llvm-project/libcxx/include/barrier:152:9
    #3 0x55555d77fee6 in std::__1::barrier<std::__1::__empty_completion>::wait[abi:v15007](unsigned char&&) const build_docker/./contrib/llvm-project/libcxx/include/barrier:310:13
    #4 0x55555d77fee6 in std::__1::barrier<std::__1::__empty_completion>::arrive_and_wait[abi:v15007]() build_docker/./contrib/llvm-project/libcxx/include/barrier:315:9
    #5 0x55555d77fee6 in SchedulerRoot_Cancel_Test::TestBody()::$_0::operator()() const::'lambda'()::operator()() const build_docker/./src/Common/Scheduler/Nodes/tests/gtest_resource_scheduler.cpp:195:27
    #6 0x55555d77fee6 in decltype(std::declval<SchedulerRoot_Cancel_Test::TestBody()::$_0::operator()() const::'lambda'()&>()()) std::__1::__invoke[abi:v15007]<SchedulerRoot_Cancel_Test::TestBody()::$_0::operator()() const::'lambda'()&>(SchedulerRoot_Cancel_Test::TestBody()::$_0::operator()() const::'lambda'()&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #7 0x55555d77fee6 in void std::__1::__invoke_void_return_wrapper<void, true>::__call<SchedulerRoot_Cancel_Test::TestBody()::$_0::operator()() const::'lambda'()&>(SchedulerRoot_Cancel_Test::TestBody()::$_0::operator()() const::'lambda'()&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:479:9
    #8 0x55555d77fee6 in std::__1::__function::__default_alloc_func<SchedulerRoot_Cancel_Test::TestBody()::$_0::operator()() const::'lambda'(), void ()>::operator()[abi:v15007]() build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:235:12
    #9 0x55555d77fee6 in void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<SchedulerRoot_Cancel_Test::TestBody()::$_0::operator()() const::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716:16
    #10 0x55555d793bcb in std::__1::__function::__policy_func<void ()>::operator()[abi:v15007]() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:848:16
    #11 0x55555d793bcb in std::__1::function<void ()>::operator()() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:1197:12
    #12 0x55555d793bcb in MyRequest::execute() build_docker/./src/Common/Scheduler/Nodes/tests/gtest_resource_scheduler.cpp:102:13
    #13 0x55555d7874ae in DB::SchedulerRoot::execute(DB::ResourceRequest*) build_docker/./src/Common/Scheduler/SchedulerRoot.h:251:18
    #14 0x55555d7874ae in DB::SchedulerRoot::schedulerThread() build_docker/./src/Common/Scheduler/SchedulerRoot.h:240:17
    #15 0x55555d7870ae in DB::SchedulerRoot::start()::'lambda'()::operator()() const build_docker/./src/Common/Scheduler/SchedulerRoot.h:69:55
    #16 0x55555d7870ae in decltype(std::declval<DB::SchedulerRoot::start()::'lambda'()&>()()) std::__1::__invoke[abi:v15007]<DB::SchedulerRoot::start()::'lambda'()&>(DB::SchedulerRoot::start()::'lambda'()&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #17 0x55555d7870ae in decltype(auto) std::__1::__apply_tuple_impl[abi:v15007]<DB::SchedulerRoot::start()::'lambda'()&, std::__1::tuple<>&>(DB::SchedulerRoot::start()::'lambda'()&, std::__1::tuple<>&, std::__1::__tuple_indices<...>) build_docker/./contrib/llvm-project/libcxx/include/tuple:1789:1
    #18 0x55555d7870ae in decltype(auto) std::__1::apply[abi:v15007]<DB::SchedulerRoot::start()::'lambda'()&, std::__1::tuple<>&>(DB::SchedulerRoot::start()::'lambda'()&, std::__1::tuple<>&) build_docker/./contrib/llvm-project/libcxx/include/tuple:1798:1
    #19 0x55555d7870ae in ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::SchedulerRoot::start()::'lambda'()>(DB::SchedulerRoot::start()::'lambda'()&&)::'lambda'()::operator()() build_docker/./src/Common/ThreadPool.h:311:13
    #20 0x55555d786efe in decltype(std::declval<DB::SchedulerRoot::start()::'lambda'()>()()) std::__1::__invoke[abi:v15007]<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::SchedulerRoot::start()::'lambda'()>(DB::SchedulerRoot::start()::'lambda'()&&)::'lambda'()&>(DB::SchedulerRoot::start()::'lambda'()&&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #21 0x55555d786efe in void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::SchedulerRoot::start()::'lambda'()>(DB::SchedulerRoot::start()::'lambda'()&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::SchedulerRoot::start()::'lambda'()>(DB::SchedulerRoot::start()::'lambda'()&&)::'lambda'()&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:479:9
    #22 0x55555d786efe in std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::SchedulerRoot::start()::'lambda'()>(DB::SchedulerRoot::start()::'lambda'()&&)::'lambda'(), void ()>::operator()[abi:v15007]() build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:235:12
    #23 0x55555d786efe in void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::SchedulerRoot::start()::'lambda'()>(DB::SchedulerRoot::start()::'lambda'()&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716:16
    #24 0x555596a0319c in std::__1::__function::__policy_func<void ()>::operator()[abi:v15007]() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:848:16
    #25 0x555596a0319c in std::__1::function<void ()>::operator()() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:1197:12
    #26 0x555596a0319c in ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::worker() build_docker/./src/Common/ThreadPool.cpp:785:17
    #27 0x555596a15e23 in decltype(*std::declval<ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*>().*std::declval<void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)()>()()) std::__1::__invoke[abi:v15007]<void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*, void>(void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*&&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:359:23
    #28 0x555596a15e23 in void std::__1::__thread_execute[abi:v15007]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*, 2ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*>&, std::__1::__tuple_indices<2ul>) build_docker/./contrib/llvm-project/libcxx/include/thread:284:5
    #29 0x555596a15e23 in void* std::__1::__thread_proxy[abi:v15007]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*>>(void*) build_docker/./contrib/llvm-project/libcxx/include/thread:295:5
    #30 0x7ffff7e18ac2  (/lib/x86_64-linux-gnu/libc.so.6+0x94ac2) (BuildId: 490fef8403240c91833978d494d39e537409b92e)

  Member fields were destroyed
    #0 0x55555d25c62d in __sanitizer_dtor_callback_fields (/unit_tests_dbms+0x7d0862d) (BuildId: 6354779692b1007f7dbcd003197be47ef2a84c87)
    #1 0x55555d77e37f in std::__1::__barrier_base<std::__1::__empty_completion>::~__barrier_base() build_docker/./contrib/llvm-project/libcxx/include/barrier:114:61
    #2 0x55555d77e37f in std::__1::__barrier_base<std::__1::__empty_completion>::~__barrier_base() build_docker/./contrib/llvm-project/libcxx/include/barrier:110:7
    #3 0x55555d77e37f in std::__1::barrier<std::__1::__empty_completion>::~barrier() build_docker/./contrib/llvm-project/libcxx/include/barrier:284:7
    #4 0x55555d77e37f in SchedulerRoot_Cancel_Test::TestBody() build_docker/./src/Common/Scheduler/Nodes/tests/gtest_resource_scheduler.cpp:218:1
    #5 0x5555759cd160 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) build_docker/./contrib/googletest/googletest/src/gtest.cc:2635:10
    #6 0x5555759cd160 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) build_docker/./contrib/googletest/googletest/src/gtest.cc:2671:14
    #7 0x5555759ccdba in testing::Test::Run() build_docker/./contrib/googletest/googletest/src/gtest.cc:2710:5
    #8 0x5555759d0061 in testing::TestInfo::Run() build_docker/./contrib/googletest/googletest/src/gtest.cc:2856:11
    #9 0x5555759d364d in testing::TestSuite::Run() build_docker/./contrib/googletest/googletest/src/gtest.cc:3034:30
    #10 0x555575a11322 in testing::internal::UnitTestImpl::RunAllTests() build_docker/./contrib/googletest/googletest/src/gtest.cc:5964:44
    #11 0x555575a101a0 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) build_docker/./contrib/googletest/googletest/src/gtest.cc:2635:10
    #12 0x555575a101a0 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) build_docker/./contrib/googletest/googletest/src/gtest.cc:2671:14
    #13 0x555575a0fde9 in testing::UnitTest::Run() build_docker/./contrib/googletest/googletest/src/gtest.cc:5543:10
    #14 0x55555db25b60 in RUN_ALL_TESTS() build_docker/./contrib/googletest/googletest/include/gtest/gtest.h:2334:73
    #15 0x55555db25b60 in main build_docker/./src/Common/tests/gtest_main.cpp:17:12
    #16 0x7ffff7dadd8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: 490fef8403240c91833978d494d39e537409b92e)

SUMMARY: MemorySanitizer: use-of-uninitialized-value build_docker/./contrib/llvm-project/libcxx/include/__thread/poll_with_backoff.h:44:11 in bool std::__1::__libcpp_thread_poll_with_backoff[abi:v15007]<std::__1::__barrier_base<std::__1::__empty_completion>::wait[abi:v15007](unsigned char&&) const::'lambda'() const&, std::__1::__libcpp_timed_backoff_policy>(std::__1::__barrier_base<std::__1::__empty_completion>::wait[abi:v15007](unsigned char&&) const::'lambda'() const&, std::__1::__libcpp_timed_backoff_policy&&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l>>)
Exiting
```

**Comment by serxa** [comment]
Fixed by https://github.com/ClickHouse/ClickHouse/pull/74973
