### ISSUE TITLE
Unit test `CoordinationTest/3.ChangelogTestSimple` failure in release build

### ISSUE THREAD

**Issue by serxa** [ClickHouse/ClickHouse#71278]
(you don't have to strictly follow this form)

**Describe the bug**
[A link to the report
](https://s3.amazonaws.com/clickhouse-test-reports/71266/2760f283a1c54351c3103e4a9ce6556b06009149/unit_tests__release_/run.log)

**Error message and/or stacktrace**
```
[ RUN      ] CoordinationTest/3.ChangelogTestSimple

Thread 4245 "ThreadPool" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffd675fe640 (LWP 4270)]
0x00007ffff7e1a9fc in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
#0  0x00007ffff7e1a9fc in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff7dc6476 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff7dac7f3 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x000000001023e9de in ThreadFromGlobalPoolImpl<true, true>::join (
    this=<optimized out>) at ./src/Common/ThreadPool.h:345
#4  0x000000001023e9de in DB::Changelog::shutdown (
    this=this@entry=0x7ffd356d8758)
#5  0x000000001023ebfb in DB::Changelog::~Changelog (this=0x7ffd356d8758)
    at ./build_docker/./src/Coordination/Changelog.cpp:2387
#6  0x0000000006918f14 in DB::KeeperLogStore::~KeeperLogStore (
    this=0x7ffd356d8718) at ./src/Coordination/KeeperLogStore.h:14
#7  0x0000000006afa20e in std::__1::__shared_count::__release_shared[abi:v15007]() (this=0x7ffd356d8700)
    at ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:174
#8  std::__1::__shared_weak_count::__release_shared[abi:v15007]() (
    this=0x7ffd356d8700)
    at ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:215
#9  std::__1::shared_ptr<DB::KeeperLogStore>::~shared_ptr[abi:v15007]() (
    this=0x7fffeb4270c0)
    at ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:702
#10 DB::KeeperStateManager::~KeeperStateManager (this=0x7fffeb427018)
    at ./src/Coordination/KeeperStateManager.h:17
#11 0x000000001463c788 in std::__1::__shared_count::__release_shared[abi:v15007]() (this=<optimized out>)
    at ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:174
#12 std::__1::__shared_weak_count::__release_shared[abi:v15007]() (
    this=<optimized out>)
    at ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:215
#13 std::__1::shared_ptr<nuraft::state_mgr>::~shared_ptr[abi:v15007]() (
    this=<optimized out>)
    at ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:702
#14 nuraft::context::~context (this=this@entry=0x7fffefc6a000)
    at ./contrib/NuRaft/include/libnuraft/context.hxx:42
#15 0x0000000014635087 in std::__1::default_delete<nuraft::context>::operator()[abi:v15007](nuraft::context*) const (this=<optimized out>, 
    __ptr=0x7fffefc6a000)
    at ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48
#16 std::__1::unique_ptr<nuraft::context, std::__1::default_delete<nuraft::context> >::reset[abi:v15007](nuraft::context*) (this=0x7fffefc58698, __p=0x0)
    at ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:305
#17 std::__1::unique_ptr<nuraft::context, std::__1::default_delete<nuraft::context> >::~unique_ptr[abi:v15007]() (this=0x7fffefc58698)
    at ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259
#18 nuraft::raft_server::~raft_server (this=0x7fffefc58518)
    at ./build_docker/./contrib/NuRaft/src/raft_server.cxx:337
#19 0x00000000102392bb in std::__1::__shared_count::__release_shared[abi:v15007]() (this=0x7fffefc58500)
    at ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:174
#20 std::__1::__shared_weak_count::__release_shared[abi:v15007]() (
    this=0x7fffefc58500)
    at ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:215
#21 std::__1::shared_ptr<nuraft::raft_server>::~shared_ptr[abi:v15007]() (
    this=<optimized out>)
    at ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:702
#22 DB::Changelog::appendCompletionThread (this=this@entry=0x7ffd356d8758)
    at ./build_docker/./src/Coordination/Changelog.cpp:1971
#23 0x0000000010240d27 in DB::Changelog::Changelog(std::__1::shared_ptr<Poco::Logger>, DB::LogFileSettings, DB::FlushSettings, std::__1::shared_ptr<DB::KeeperContext>)::$_3::operator()() const (this=<optimized out>)
    at ./build_docker/./src/Coordination/Changelog.cpp:1631
#24 std::__1::__invoke[abi:v15007]<DB::Changelog::Changelog(std::__1::shared_ptr<Poco::Logger>, DB::LogFileSettings, DB::FlushSettings, std::__1::shared_ptr<DB::KeeperContext>)::$_3&>(DB::Changelog::Changelog(std::__1::shared_ptr<Poco::Logger>, DB::LogFileSettings, DB::FlushSettings, std::__1::shared_ptr<DB::KeeperContext>)::$_3&) (__f=...)
    at ./contrib/llvm-project/libcxx/include/__functional/invoke.h:394
#25 _ZNSt3__118__apply_tuple_implB6v15007IRZN2DB9ChangelogC1ENS_10shared_ptrIN4Poco6LoggerEEENS1_15LogFileSettingsENS1_13FlushSettingsENS3_INS1_13KeeperContextEEEE3$_3RNS_5tupleIJEEETpTnmJEEEDcOT_OT0_NS_15__tuple_indicesIJXspT1_EEEE (
    __f=..., __t=...) at ./contrib/llvm-project/libcxx/include/tuple:1789
#26 std::__1::apply[abi:v15007]<DB::Changelog::Changelog(std::__1::shared_ptr<Poco::Logger>, DB::LogFileSettings, DB::FlushSettings, std::__1::shared_ptr<DB::KeeperContext>)::$_3&, std::__1::tuple<>&>(DB::Changelog::Changelog(std::__1::shared_ptr<Poco::Logger>, DB::LogFileSettings, DB::FlushSettings, std::__1::shared_ptr<DB::KeeperContext>)::$_3&, std::__1::tuple<>&) (__f=..., __t=...)
    at ./contrib/llvm-project/libcxx/include/tuple:1798
#27 ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::Changelog::Changelog(std::__1::shared_ptr<Poco::Logger>, DB::LogFileSettings, DB::FlushSettings, std::__1::shared_ptr<DB::KeeperContext>)::$_3>(DB::Changelog::Changelog(std::__1::shared_ptr<Poco::Logger>, DB::LogFileSettings, DB::FlushSettings, std::__1::shared_ptr<DB::KeeperContext>)::$_3&&)::{lambda()#1}::operator()() (
    this=0x7fffeb4f30a0) at ./src/Common/ThreadPool.h:311
#28 std::__1::__invoke[abi:v15007]<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::Changelog::Changelog(std::__1::shared_ptr<Poco::Logger>, DB::LogFileSettings, DB::FlushSettings, std::__1::shared_ptr<DB::KeeperContext>)::$_3>(DB::Changelog::Changelog(std::__1::shared_ptr<Poco::Logger>, DB::LogFileSettings, DB::FlushSettings, std::__1::shared_ptr<DB::KeeperContext>)::$_3&&)::{lambda()#1}&>(DB::Changelog::Changelog(std::__1::shared_ptr<Poco::Logger>, DB::LogFileSettings, DB::FlushSettings, std::__1::shared_ptr<DB::KeeperContext>)::$_3&&) (__f=...) at ./contrib/llvm-project/libcxx/include/__functional/invoke.h:394
#29 std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::Changelog::Changelog(std::__1::shared_ptr<Poco::Logger>, DB::LogFileSettings, DB::FlushSettings, std::__1::shared_ptr<DB::KeeperContext>)::$_3>(DB::Changelog::Changelog(std::__1::shared_ptr<Poco::Logger>, DB::LogFileSettings, DB::FlushSettings, std::__1::shared_ptr<DB::KeeperContext>)::$_3&&)::{lambda()#1}&>(ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::Changelog::Changelog(std::__1::shared_ptr<Poco::Logger>, DB::LogFileSettings, DB::FlushSettings, std::__1::shared_ptr<DB::KeeperContext>)::$_3>(DB::Changelog::Changelog(std::__1::shared_ptr<Poco::Logger>, DB::LogFileSettings, DB::FlushSettings, std::__1::shared_ptr<DB::KeeperContext>)::$_3&&)::{lambda()#1}&) (__args=...)
    at ./contrib/llvm-project/libcxx/include/__functional/invoke.h:479
#30 std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::Changelog::Changelog(std::__1::shared_ptr<Poco::Logger>, DB::LogFileSettings, DB::FlushSettings, std::__1::shared_ptr<DB::KeeperContext>)::$_3>(DB::Changelog::Changelog(std::__1::shared_ptr<Poco::Logger>, DB::LogFileSettings, DB::FlushSettings, std::__1::shared_ptr<DB::KeeperContext>)::$_3&&)::{lambda()#1}, void ()>::operator()[abi:v15007]() (this=0x7fffeb4f30a0)
    at ./contrib/llvm-project/libcxx/include/__functional/function.h:235
#31 std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::Changelog::Changelog(std::__1::shared_ptr<Poco::Logger>, DB::LogFileSettings, DB::FlushSettings, std::__1::shared_ptr<DB::KeeperContext>)::$_3>(DB::Changelog::Changelog(std::__1::shared_ptr<Poco::Logger>, DB::LogFileSettings, DB::FlushSettings, std::__1::shared_ptr<DB::KeeperContext>)::$_3&&)::{lambda()#1}, void ()> >(std::__1::__function::__policy_storage const*) (
    __buf=<optimized out>)
    at ./contrib/llvm-project/libcxx/include/__functional/function.h:716
#32 0x000000001482fce3 in std::__1::__function::__policy_func<void ()>::operator()[abi:v15007]() const (this=0x7ffd675fb000)
    at ./contrib/llvm-project/libcxx/include/__functional/function.h:848
#33 std::__1::function<void()>::operator() (this=0x7ffd675fb000)
    at ./contrib/llvm-project/libcxx/include/__functional/function.h:1197
#34 ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::worker (
    this=0x7fffefc00200) at ./build_docker/./src/Common/ThreadPool.cpp:785
#35 0x00000000148353bb in std::__1::__invoke[abi:v15007]<void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*, , void>(void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*&&)
    (
    __f=@0x7fffefc00228: (void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool * const)) 0x1482f8e0 <ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::worker()>, 
    __a0=@0x7fffefc00238: 0x7fffefc00200)
    at ./contrib/llvm-project/libcxx/include/__functional/invoke.h:359
#36 std::__1::__thread_execute[abi:v15007]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*, 2ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*>&, std::__1::__tuple_indices<2ul>) (
    __t=...) at ./contrib/llvm-project/libcxx/include/thread:284
#37 std::__1::__thread_proxy[abi:v15007]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*> >(void*) (__vp=0x7fffefc00220)
    at ./contrib/llvm-project/libcxx/include/thread:295
#38 0x00007ffff7e18ac3 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#39 0x00007ffff7eaa850 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
```

**Comment by alexey-milovidov** [comment]
Not anymore:

https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSBjaGVja19zdGFydF90aW1lID49IG5vdygpIC0gSU5URVJWQUwgMSBZRUFyCiAgICBBTkQgKGhlYWRfcmVmID0gJ21hc3RlcicgQU5EIHN0YXJ0c1dpdGgoaGVhZF9yZXBvLCAnQ2xpY2tIb3VzZS8nKSkKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnU0tJUFBFRCcKICAgIEFORCAodGVzdF9zdGF0dXMgTElLRSAnRiUnIE9SIHRlc3Rfc3RhdHVzIExJS0UgJ0UlJykgCiAgICBBTkQgY2hlY2tfc3RhdHVzICE9ICdzdWNjZXNzJwogICAgQU5EIHBvc2l0aW9uKHRlc3RfbmFtZSwgJ0Nvb3JkaW5hdGlvblRlc3QnKSA+IDAKT1JERVIgQlkgY2hlY2tfc3RhcnRfdGltZQ==

https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSBjaGVja19zdGFydF90aW1lID49IG5vdygpIC0gSU5URVJWQUwgMSBZRUFyCiAgICBBTkQgKGhlYWRfcmVmID0gJ21hc3RlcicgQU5EIHN0YXJ0c1dpdGgoaGVhZF9yZXBvLCAnQ2xpY2tIb3VzZS8nKSkKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnU0tJUFBFRCcKICAgIEFORCAodGVzdF9zdGF0dXMgTElLRSAnRiUnIE9SIHRlc3Rfc3RhdHVzIExJS0UgJ0UlJykgCiAgICBBTkQgY2hlY2tfc3RhdHVzICE9ICdzdWNjZXNzJwogICAgQU5EIHBvc2l0aW9uKGNoZWNrX25hbWUsICdVbml0JykgPiAwCk9SREVSIEJZIGNoZWNrX3N0YXJ0X3RpbWU=
