### ISSUE TITLE
DROP DATABASE throws UNKNOWN_TABLE exception 

### ISSUE THREAD

**Issue by acoj1993** [ClickHouse/ClickHouse#71475]
**Describe what's wrong**

We have been trying to upgrade ClickHouse from 24.3.3.102 to 24.8.5.115 and have been getting "Table does not exist. (UNKNOWN_TABLE)" errors when running DROP DATABASE statements, which we weren't getting with 24.3 version. See the details below.

At the time of writing, I noticed that 24.8.6.70 was released. I have tried with that version as well, but the issue still occurs. 

**How to reproduce**

I don't have an easy test case to send to you, but will try to explain how we reproduce it. 

We have a java application built on top of ClickHouse. We have a test class with unit tests testing a particular service. This service interacts with ClickHouse by executing all sorts of different SQL statements. 

Among those SQL statements are also CREATE TABLE statements, which we use to create auxiliary tables. After the service is done, as the last step, it asynchronously executes DROP TABLE statements to cleanup previously created auxiliary tables.

But then, after the last test is executed, the test class runs a DROP DATABASE statement, to remove the created test database. However, approximately every 5-8th time, the DROP DATABASE fails with the following exception:
`Caused by: java.io.IOException: Code: 60. DB::Exception: Table test.TEST_TABLE_1 (5f261660-cd69-4d88-a8cd-8d82a14a1795) does not exist. (UNKNOWN_TABLE) (version 24.8.6.70 (official build))`

Perhaps it is worth mentioning that these tables use the table engine "Memory". Also, we are currently using the official ClickHouse JDBC driver version 0.6.0-patch3.

This never failed with previous versions. We have been using ClickHouse for a long time (24.3, 23.3, 22.3) and have had this test class for a long time as well. This seems to be some sort of a race condition, but I don't see a reason why a DROP DATABASE should fail with table does not exist. Have there been changes to DROP TABLE and DROP DATABASE behaviors since 24.3?

**Comment by jsajlovic** [comment]
+1, also interested in this

**Comment by acoj1993** [comment]
Would this be enough for you?
```
Code: 60. DB::Exception: Table test.TEST_TABLE_1 (7e83fd93-0514-441e-aa73-bb8c58a99c92) does not exist. (UNKNOWN_TABLE) (version 24.8.5.115 (official build))
, server ClickHouseNode [uri=http://10.98.128.47:34543/default, options={socket_timeout=1000000,connect_timeout=1000000,typeMappings=UInt64=java.math.BigInteger,UInt32=java.lang.Long,socket_keepalive=true,socket_reuseaddr=true,http_connection_provider=APACHE_HTTP_CLIENT}]@775031714
	at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:85)
	at com.clickhouse.jdbc.SqlExceptionUtils.create(SqlExceptionUtils.java:31)
	at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:90)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.getLastResponse(ClickHouseStatementImpl.java:122)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:474)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.execute(ClickHouseStatementImpl.java:462)
	at <our_package>.dropClickHouseDatabase(AbstractClickhouseAdapter.java:78)
```

**Comment by Algunenano** [comment]
I meant the stacktrace from ClickHouse, that's the one from your Java app. Depending on the app, it might be easier to get it from CH text logs or system.query_log and they'd look something like:

```
2024.11.05 17:16:03.432227 [ 509016 ] {cc1b9fba-0000-4b59-bd2d-12c0fefcd2a2} <Error> executeQuery: Code: 60. DB::Exception: Table default.t0 does not exist. (UNKNOWN_TABLE) (version 24.11.1.1) (from 0.0.0.0:0) (in query: drop table t0;), Stack trace (when copying this message, always include the lines below):

0. /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/exception:141: Poco::Exception::Exception(String const&, int) @ 0x0000000015a23392
1. /mnt/ch/ClickHouse/src/Common/Exception.cpp:109: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000bcba227
2. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x0000000006b0971a
3. DB::Exception::Exception<String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type>, String&&, String&&) @ 0x0000000006b0acbb
4. /mnt/ch/ClickHouse/src/Databases/IDatabase.cpp:37: DB::IDatabase::getTable(String const&, std::shared_ptr<DB::Context const>) const @ 0x000000001063e3cb
5. /mnt/ch/ClickHouse/src/Interpreters/DatabaseCatalog.cpp:441: DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, std::shared_ptr<DB::Context const>, std::optional<DB::Exception>*) const @ 0x0000000010b7ff3c
6. /mnt/ch/ClickHouse/src/Interpreters/DatabaseCatalog.cpp:984: DB::DatabaseCatalog::getDatabaseAndTable(DB::StorageID const&, std::shared_ptr<DB::Context const>) const @ 0x0000000010b86794
7. /mnt/ch/ClickHouse/src/Interpreters/InterpreterDropQuery.cpp:150: DB::InterpreterDropQuery::executeToTableImpl(std::shared_ptr<DB::Context const> const&, DB::ASTDropQuery&, std::shared_ptr<DB::IDatabase>&, StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>&) @ 0x0000000010f4c022
8. /mnt/ch/ClickHouse/src/Interpreters/InterpreterDropQuery.cpp:122: DB::InterpreterDropQuery::executeToTable(DB::ASTDropQuery&) @ 0x0000000010f4b7c9
9. /mnt/ch/ClickHouse/src/Interpreters/InterpreterDropQuery.cpp:95: DB::InterpreterDropQuery::executeSingleDropQuery(std::shared_ptr<DB::IAST> const&) @ 0x0000000010f4ad67
10. /mnt/ch/ClickHouse/src/Interpreters/InterpreterDropQuery.cpp:76: DB::InterpreterDropQuery::execute() @ 0x0000000010f4ab65
11. /mnt/ch/ClickHouse/src/Interpreters/executeQuery.cpp:1397: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x00000000114fe9a2
12. /mnt/ch/ClickHouse/src/Interpreters/executeQuery.cpp:1564: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x00000000114fac29
13. /mnt/ch/ClickHouse/src/Client/LocalConnection.cpp:240: DB::LocalConnection::sendQuery(DB::ConnectionTimeouts const&, String const&, std::unordered_map<String, String, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, String>>> const&, String const&, unsigned long, DB::Settings const*, DB::ClientInfo const*, bool, std::function<void (DB::Progress const&)>) @ 0x0000000012a0750c
14. /mnt/ch/ClickHouse/src/Client/ClientBase.cpp:1095: DB::ClientBase::processOrdinaryQuery(String const&, std::shared_ptr<DB::IAST>) @ 0x00000000129a90f6
15. /mnt/ch/ClickHouse/src/Client/ClientBase.cpp:2069: DB::ClientBase::processParsedSingleQuery(String const&, String const&, std::shared_ptr<DB::IAST>, std::optional<bool>, bool) @ 0x00000000129a76a0
16. /mnt/ch/ClickHouse/src/Client/ClientBase.cpp:2402: DB::ClientBase::executeMultiQuery(String const&) @ 0x00000000129b1835
17. /mnt/ch/ClickHouse/src/Client/ClientBase.cpp:2547: DB::ClientBase::processQueryText(String const&) @ 0x00000000129b2641
18. /mnt/ch/ClickHouse/src/Client/ClientBase.cpp:2777: DB::ClientBase::runInteractive() @ 0x00000000129b4aa0
19. /mnt/ch/ClickHouse/programs/local/LocalServer.cpp:0: DB::LocalServer::main(std::vector<String, std::allocator<String>> const&) @ 0x000000000bf2ac8e
20. /mnt/ch/ClickHouse/base/poco/Util/src/Application.cpp:315: Poco::Util::Application::run() @ 0x0000000015b01ad4
21. /mnt/ch/ClickHouse/programs/local/LocalServer.cpp:1026: mainEntryClickHouseLocal(int, char**) @ 0x000000000bf35501
22. /mnt/ch/ClickHouse/programs/main.cpp:248: main @ 0x0000000006b02f98
23. ? @ 0x000072d89e839e08
24. ? @ 0x000072d89e839ecc
25. _start @ 0x0000000006b0202e
```

It will make it easier to identify where the error was triggered inside CH codebase, and probably identify the problem

**Comment by acoj1993** [comment]
Ah, of course. Here it is:
```
2024.11.05 18:42:02.469949 [ 1663 ] {33b80f1f-f02d-4f50-b0fe-5cdd1cecbfae} <Error> executeQuery: Code: 60. DB::Exception: Table test.TEST_TABLE_1 (d8b3e664-e8d2-4eef-b79c-4360dbb859e4) does not exist. (UNKNOWN_TABLE) (version 24.8.5.115 (official build)) (from 172.17.0.1:56682) (in query: DROP DATABASE test), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000db0867b
1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x0000000007e5e2ac
2. DB::Exception::Exception<String>(int, FormatStringHelperImpl<std::type_identity<String>::type>, String&&) @ 0x0000000007e5ddeb
3. DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, std::shared_ptr<DB::Context const>, std::optional<DB::Exception>*) const @ 0x0000000011688c3c
4. DB::DatabaseCatalog::getTable(DB::StorageID const&, std::shared_ptr<DB::Context const>) const @ 0x00000000116901aa
5. DB::InterpreterDropQuery::execute() @ 0x0000000011a0523f
6. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x0000000011e346d9
7. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::shared_ptr<DB::Context>, std::function<void (DB::QueryResultDetails const&)>, DB::QueryFlags, std::optional<DB::FormatSettings> const&, std::function<void (DB::IOutputFormat&, String const&, std::shared_ptr<DB::Context const> const&, std::optional<DB::FormatSettings> const&)>) @ 0x0000000011e394de
8. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional<DB::CurrentThread::QueryScope>&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x0000000012f484d6
9. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x0000000012f4c439
10. DB::HTTPServerConnection::run() @ 0x0000000012feb38a
11. Poco::Net::TCPServerConnection::start() @ 0x0000000015dcadc7
12. Poco::Net::TCPServerDispatcher::run() @ 0x0000000015dcb259
13. Poco::PooledThread::run() @ 0x0000000015d98201
14. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000015d967bd
15. ? @ 0x00007fffff7a6609
16. ? @ 0x00007fffff6cb353

2024.11.05 18:42:02.471135 [ 1663 ] {33b80f1f-f02d-4f50-b0fe-5cdd1cecbfae} <Error> DynamicQueryHandler: Code: 60. DB::Exception: Table test.TEST_TABLE_1 (d8b3e664-e8d2-4eef-b79c-4360dbb859e4) does not exist. (UNKNOWN_TABLE), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000db0867b
1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x0000000007e5e2ac
2. DB::Exception::Exception<String>(int, FormatStringHelperImpl<std::type_identity<String>::type>, String&&) @ 0x0000000007e5ddeb
3. DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, std::shared_ptr<DB::Context const>, std::optional<DB::Exception>*) const @ 0x0000000011688c3c
4. DB::DatabaseCatalog::getTable(DB::StorageID const&, std::shared_ptr<DB::Context const>) const @ 0x00000000116901aa
5. DB::InterpreterDropQuery::execute() @ 0x0000000011a0523f
6. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x0000000011e346d9
7. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::shared_ptr<DB::Context>, std::function<void (DB::QueryResultDetails const&)>, DB::QueryFlags, std::optional<DB::FormatSettings> const&, std::function<void (DB::IOutputFormat&, String const&, std::shared_ptr<DB::Context const> const&, std::optional<DB::FormatSettings> const&)>) @ 0x0000000011e394de
8. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional<DB::CurrentThread::QueryScope>&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x0000000012f484d6
9. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x0000000012f4c439
10. DB::HTTPServerConnection::run() @ 0x0000000012feb38a
11. Poco::Net::TCPServerConnection::start() @ 0x0000000015dcadc7
12. Poco::Net::TCPServerDispatcher::run() @ 0x0000000015dcb259
13. Poco::PooledThread::run() @ 0x0000000015d98201
14. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000015d967bd
15. ? @ 0x00007fffff7a6609
16. ? @ 0x00007fffff6cb353
 (version 24.8.5.115 (official build))
```

**Comment by acoj1993** [comment]
Any update on this one? Have there been any changes that could have affected this behavior recently since 24.3? 
I have been testing extensively and can once again confirm, with 24.3 this test class never fails, and with 24.8 every 5-10 times. 

To re-iterate, it's two threads initiated, the first one dropping a table and the second dropping the entire database. Dropping the database fails with the above mentioned exception.

Since we rely on creating auxiliary tables and we dynamically create and remove databases, this is actually a blocker for us, as dropping the database could suddenly fail.

**Comment by jsajlovic** [comment]
Any updates here?
