### ISSUE TITLE
Insert into Hudi table SEGV

### ISSUE THREAD

**Issue by PedroTadim** [ClickHouse/ClickHouse#71506]
**Describe the bug**
According to the docs, the Hudi engine is read-only, but an INSERT shouldn't SEGV.

**How to reproduce**
Run:
```sql
CREATE TABLE tx(t0 Int) ENGINE=Hudi('<any file on a MinIO bucket>', '<user>', '<password>');
INSERT INTO tx VALUES (1); --SEGV
```
Stack trace:
```
#0  0x000055557bd29694 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__is_long[abi:v15007]() const (this=0x0) at ./contrib/llvm-project/libcxx/include/string:1499
#1  std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string (this=0x7fff0383c420, __str=...) at ./contrib/llvm-project/libcxx/include/string:2012
#2  DB::StoredObject::StoredObject (this=0x7fff0383c420, remote_path_=..., local_path_=..., bytes_size_=0) at ./src/Disks/ObjectStorages/StoredObject.h:26
#3  0x000055557bdbc545 in DB::checkAndGetNewFileOnInsertIfNeeded (object_storage=..., configuration=..., settings=..., key=..., sequence_number=<optimized out>) at src/Storages/ObjectStorage/Utils.cpp:21
#4  0x000055557bd1fd43 in DB::StorageObjectStorage::write (this=0x51d000967898, query=..., metadata_snapshot=..., local_context=...) at src/Storages/ObjectStorage/StorageObjectStorage.cpp:364
#5  0x0000555583cd64ef in DB::buildPushingToViewsChain (storage=..., metadata_snapshot=..., context=..., query_ptr=..., no_destination=<optimized out>, thread_status_holder=..., running_group=..., elapsed_counter_ms=<optimized out>, 
    async_insert=<optimized out>, live_view_header=...) at src/Processors/Transforms/buildPushingToViewsChain.cpp:594
#6  0x000055557f38623f in DB::InterpreterInsertQuery::buildSink (this=<optimized out>, table=..., metadata_snapshot=..., thread_status_holder=..., running_group=..., elapsed_counter_ms=<optimized out>)
    at src/Interpreters/InterpreterInsertQuery.cpp:364
#7  0x000055557f387f21 in DB::InterpreterInsertQuery::buildPreAndSinkChains (this=<optimized out>, presink_streams=1, sink_streams=<optimized out>, table=..., metadata_snapshot=..., query_sample_block=...)
    at src/Interpreters/InterpreterInsertQuery.cpp:443
#8  0x000055557f38d60f in DB::InterpreterInsertQuery::buildInsertPipeline (this=0x507000150480, query=..., table=...) at src/Interpreters/InterpreterInsertQuery.cpp:695
#9  0x000055557f390e39 in DB::InterpreterInsertQuery::execute (this=0x507000150480) at src/Interpreters/InterpreterInsertQuery.cpp:815
#10 0x000055557fbc7299 in DB::executeQueryImpl (begin=<optimized out>, end=<optimized out>, context=..., flags=..., stage=<optimized out>, istr=<optimized out>) at src/Interpreters/executeQuery.cpp:1397
#11 0x000055557fbbfc85 in DB::executeQuery (query=..., context=..., flags=..., stage=<optimized out>) at src/Interpreters/executeQuery.cpp:1564
#12 0x00005555832daa73 in DB::TCPHandler::runImpl (this=0x51b0005a6d80) at src/Server/TCPHandler.cpp:595
#13 0x000055558330cf00 in DB::TCPHandler::run (this=<optimized out>) at src/Server/TCPHandler.cpp:2528
#14 0x000055558a84178f in Poco::Net::TCPServerConnection::start (this=0x17) at base/poco/Net/src/TCPServerConnection.cpp:43
#15 0x000055558a842377 in Poco::Net::TCPServerDispatcher::run (this=0x511001141c00) at base/poco/Net/src/TCPServerDispatcher.cpp:115
#16 0x000055558a74407c in Poco::PooledThread::run (this=<optimized out>) at base/poco/Foundation/src/ThreadPool.cpp:205
#17 0x000055558a73e1c8 in Poco::ThreadImpl::runnableEntry (pThread=<optimized out>) at ./base/poco/Foundation/src/Thread_POSIX.cpp:335
#18 0x0000555560309059 in asan_thread_start(void*) ()
#19 0x00007ffff7ca1e2e in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
#20 0x00007ffff7d33a4c in __GI___clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```

**Comment by Algunenano** [comment]
When it works correctly:
```
Received exception from server (version 24.8.2):
Code: 36. DB::Exception: Received from clickhouse-01:49000. DB::Exception: Object in bucket backups with key  already exists. If you want to overwrite it, enable setting s3_truncate_on_insert, if you want to create a new file on each insert, enable setting s3_create_new_file_on_insert. (BAD_ARGUMENTS)
```

Seems like something that's only triggered under some situations, so testing with msan makes sense:

MSAN from master right now:
```
INSERT INTO tx FORMAT Values

Query id: e2f6ce10-7dbf-41da-acfc-4d94c33ce218

[Mordor] 2024.11.06 16:58:04.824260 [ 343988 ] <Fatal> BaseDaemon: ########################################
[Mordor] 2024.11.06 16:58:04.824618 [ 343988 ] <Fatal> BaseDaemon: (version 24.11.1.1, build id: 3ED320FC11CAE03ECCAC23E81205BA620D15FB33, git hash: 1756fe28eee7a90524e6254aeb74f5769d1a8465) (from thread 343240) (query_id: e2f6ce10-7dbf-41da-acfc-4d94c33ce218) (query: INSERT INTO tx VALUES ) Received signal Segmentation fault (11)
[Mordor] 2024.11.06 16:58:04.824772 [ 343988 ] <Fatal> BaseDaemon: Address: 0x17. Access: read. Address not mapped to object.
[Mordor] 2024.11.06 16:58:04.824898 [ 343988 ] <Fatal> BaseDaemon: Stack trace: 0x0000555574f811be 0x00005555758ca140 0x000055555daadfad 0x00007ffff7dce1d0 0x0000555586fdbc98 0x00005555870c529f 0x0000555586fcc106 0x00005555939c270e 0x000055558c4904be 0x000055558c4934f2 0x000055558c49d53f 0x000055558c4a3a79 0x000055558d2b18a6 0x000055558d2a1fdd 0x0000555592a38658 0x0000555592a8d681 0x0000555598986500 0x00005555989874a8 0x000055559885d5b5 0x0000555598859c2e 0x00005555988568cc 0x00007ffff7e2539d 0x00007ffff7eaa49c
[Mordor] 2024.11.06 16:58:05.075148 [ 343988 ] <Fatal> BaseDaemon: 0.0. inlined from /mnt/ch/ClickHouse/src/Common/StackTrace.cpp:380: StackTrace::tryCapture()
[Mordor] 2024.11.06 16:58:05.075326 [ 343988 ] <Fatal> BaseDaemon: 0. /mnt/ch/ClickHouse/src/Common/StackTrace.cpp:349: StackTrace::StackTrace(ucontext_t const&) @ 0x000000001fa2d1be
[Mordor] 2024.11.06 16:58:05.407218 [ 343988 ] <Fatal> BaseDaemon: 1. /mnt/ch/ClickHouse/src/Common/SignalHandlers.cpp:85: signalHandler(int, siginfo_t*, void*) @ 0x0000000020376140
[Mordor] 2024.11.06 16:58:05.677937 [ 343988 ] <Fatal> BaseDaemon: 2. SignalAction(int, void*, void*) @ 0x0000000008559fad
[Mordor] 2024.11.06 16:58:05.678078 [ 343988 ] <Fatal> BaseDaemon: 3. ? @ 0x00007ffff7dce1d0
[Mordor] 2024.11.06 16:58:06.761546 [ 343988 ] <Fatal> BaseDaemon: 4.0. inlined from /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/string:1499: String::__is_long[abi:v15007]() const
[Mordor] 2024.11.06 16:58:06.761745 [ 343988 ] <Fatal> BaseDaemon: 4.1. inlined from /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/string:2012: basic_string
[Mordor] 2024.11.06 16:58:06.761868 [ 343988 ] <Fatal> BaseDaemon: 4. /mnt/ch/ClickHouse/src/Disks/ObjectStorages/StoredObject.h:26: DB::StoredObject::StoredObject(String const&, String const&, unsigned long) @ 0x0000000031a87c98
[Mordor] 2024.11.06 16:58:06.950269 [ 343988 ] <Fatal> BaseDaemon: 5. /mnt/ch/ClickHouse/src/Storages/ObjectStorage/Utils.cpp:21: DB::checkAndGetNewFileOnInsertIfNeeded(DB::IObjectStorage const&, DB::StorageObjectStorage::Configuration const&, DB::StorageObjectStorage::QuerySettings const&, String const&, unsigned long) @ 0x0000000031b7129f
[Mordor] 2024.11.06 16:58:07.857980 [ 343988 ] <Fatal> BaseDaemon: 6. /mnt/ch/ClickHouse/src/Storages/ObjectStorage/StorageObjectStorage.cpp:364: DB::StorageObjectStorage::write(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::Context const>, bool) @ 0x0000000031a78106
[Mordor] 2024.11.06 16:58:09.197043 [ 343988 ] <Fatal> BaseDaemon: 7. /mnt/ch/ClickHouse/src/Processors/Transforms/buildPushingToViewsChain.cpp:594: DB::buildPushingToViewsChain(std::shared_ptr<DB::IStorage> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::Context const>, std::shared_ptr<DB::IAST> const&, bool, std::shared_ptr<DB::ThreadStatusesHolder>, std::shared_ptr<DB::ThreadGroup>, std::atomic<unsigned long>*, bool, DB::Block const&) @ 0x000000003e46e70e
[Mordor] 2024.11.06 16:58:09.883946 [ 343988 ] <Fatal> BaseDaemon: 8. /mnt/ch/ClickHouse/src/Interpreters/InterpreterInsertQuery.cpp:364: DB::InterpreterInsertQuery::buildSink(std::shared_ptr<DB::IStorage> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::ThreadStatusesHolder>, std::shared_ptr<DB::ThreadGroup>, std::atomic<unsigned long>*) @ 0x0000000036f3c4be
[Mordor] 2024.11.06 16:58:10.593363 [ 343988 ] <Fatal> BaseDaemon: 9. /mnt/ch/ClickHouse/src/Interpreters/InterpreterInsertQuery.cpp:443: DB::InterpreterInsertQuery::buildPreAndSinkChains(unsigned long, unsigned long, std::shared_ptr<DB::IStorage>, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::Block const&) @ 0x0000000036f3f4f2
[Mordor] 2024.11.06 16:58:11.341015 [ 343988 ] <Fatal> BaseDaemon: 10. /mnt/ch/ClickHouse/src/Interpreters/InterpreterInsertQuery.cpp:695: DB::InterpreterInsertQuery::buildInsertPipeline(DB::ASTInsertQuery&, std::shared_ptr<DB::IStorage>) @ 0x0000000036f4953f
[Mordor] 2024.11.06 16:58:12.105205 [ 343988 ] <Fatal> BaseDaemon: 11. /mnt/ch/ClickHouse/src/Interpreters/InterpreterInsertQuery.cpp:815: DB::InterpreterInsertQuery::execute() @ 0x0000000036f4fa79
[Mordor] 2024.11.06 16:58:13.163614 [ 343988 ] <Fatal> BaseDaemon: 12. /mnt/ch/ClickHouse/src/Interpreters/executeQuery.cpp:1397: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x0000000037d5d8a6
[Mordor] 2024.11.06 16:58:14.375024 [ 343988 ] <Fatal> BaseDaemon: 13. /mnt/ch/ClickHouse/src/Interpreters/executeQuery.cpp:1564: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x0000000037d4dfdd
[Mordor] 2024.11.06 16:58:15.011518 [ 343988 ] <Fatal> BaseDaemon: 14. /mnt/ch/ClickHouse/src/Server/TCPHandler.cpp:595: DB::TCPHandler::runImpl() @ 0x000000003d4e4658
[Mordor] 2024.11.06 16:58:16.145795 [ 343988 ] <Fatal> BaseDaemon: 15. /mnt/ch/ClickHouse/src/Server/TCPHandler.cpp:2528: DB::TCPHandler::run() @ 0x000000003d539681
[Mordor] 2024.11.06 16:58:16.177947 [ 343988 ] <Fatal> BaseDaemon: 16. /mnt/ch/ClickHouse/base/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x0000000043432500
[Mordor] 2024.11.06 16:58:16.236848 [ 343988 ] <Fatal> BaseDaemon: 17. /mnt/ch/ClickHouse/base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x00000000434334a8
[Mordor] 2024.11.06 16:58:16.306550 [ 343988 ] <Fatal> BaseDaemon: 18. /mnt/ch/ClickHouse/base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x00000000433095b5
[Mordor] 2024.11.06 16:58:16.379198 [ 343988 ] <Fatal> BaseDaemon: 19. /mnt/ch/ClickHouse/base/poco/Foundation/src/Thread.cpp:45: Poco::(anonymous namespace)::RunnableHolder::run() @ 0x0000000043305c2e
[Mordor] 2024.11.06 16:58:16.441232 [ 343988 ] <Fatal> BaseDaemon: 20. /mnt/ch/ClickHouse/base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x00000000433028cc
[Mordor] 2024.11.06 16:58:16.441397 [ 343988 ] <Fatal> BaseDaemon: 21. ? @ 0x00007ffff7e2539d
[Mordor] 2024.11.06 16:58:16.441501 [ 343988 ] <Fatal> BaseDaemon: 22. ? @ 0x00007ffff7eaa49c
```

**Comment by Algunenano** [comment]
I'm not sure what paths is or what this code is doing, so before investigating more, maybe @kssenii can help here.

**Comment by kssenii** [comment]
Resolved via https://github.com/ClickHouse/ClickHouse/pull/78960
