### ISSUE TITLE
Parallel table shutdown

### ISSUE THREAD

**Issue by azat** [ClickHouse/ClickHouse#72557]
While looking into some CI failures, like [this one](https://s3.amazonaws.com/clickhouse-test-reports/71406/9534a35696d8a82182d59ed24e4a604d7d11adcd/stress_test__asan_.html), I found out that the problem was slow table shutdown that are used to proxy system tables to cloud.

And even `flush_on_detach=0` does not help for `Distributed` tables since for some tables the sending can be already in progress.

I think that parallel table shutdown should help, **this will also improve performance of table shutdown in general**.

<details>

<summary>CI failure details</summary>

```
2024.11.25 22:25:09.343396 [ 35138 ] {} <Trace> BaseDaemon: Received signal 15
2024.11.25 22:25:09.343477 [ 35138 ] {} <Information> Application: Received termination signal (Terminated)
2024.11.25 22:25:09.343544 [ 35137 ] {} <Debug> Application: Received termination signal.
...
2024.11.25 22:26:56.877500 [ 35137 ] {} <Debug> StorageDistributed (zookeeper_log_sender): Joining background threads for async INSERT
2024.11.25 22:26:56.877530 [ 35137 ] {} <Debug> StorageDistributed (zookeeper_log_sender): Background threads for async INSERT joined
2024.11.25 22:26:57.284909 [ 35133 ] {} <Fatal> Application: Child process was terminated by signal 9 (KILL). If it is not done by 'forcestop' command or manually, the possible cause is OOM Killer (see 'dmesg' and look at the '/var/log/kern.log' for the details).
```

```
2024-11-25 22:26:56 Thread 1 (Thread 0x7f0d9c23f500 (LWP 35137) "clickhouse-serv"):
2024-11-25 22:26:56 #0  0x00007f0d9c3c02c0 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
2024-11-25 22:26:56 #1  0x00007f0d9c3c7002 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libc.so.6
2024-11-25 22:26:56 #2  0x00005618e962896b in pthread_mutex_lock (arg=0x511000ba64e8) at ./build_docker/./src/Common/ThreadFuzzer.cpp:427
2024-11-25 22:26:56 #3  0x000056190a964eeb in std::__1::__libcpp_mutex_lock[abi:v15007](pthread_mutex_t*) (__m=0x511000ba64e8) at ./contrib/llvm-project/libcxx/include/__threading_support:304
2024-11-25 22:26:56 #4  std::__1::mutex::lock (this=0x511000ba64e8) at ./build_docker/./contrib/llvm-project/libcxx/src/mutex.cpp:38
2024-11-25 22:26:56 #5  0x00005618f657245e in std::__1::lock_guard<std::__1::mutex>::lock_guard[abi:v15007](std::__1::mutex&) (__m=..., this=<optimized out>) at ./contrib/llvm-project/libcxx/include/__mutex_base:94
2024-11-25 22:26:56 #6  DB::BackgroundSchedulePoolTaskInfo::deactivate (this=0x511000ba6498) at ./build_docker/./src/Core/BackgroundSchedulePool.cpp:51
2024-11-25 22:26:56 #7  0x00005618fc95eeb3 in DB::DistributedAsyncInsertDirectoryQueue::shutdownWithoutFlush (this=<optimized out>) at ./build_docker/./src/Storages/Distributed/DistributedAsyncInsertDirectoryQueue.cpp:193
2024-11-25 22:26:56 #8  0x00005618fbeba433 in DB::StorageDistributed::flushClusterNodesAllDataImpl (this=<optimized out>, local_context=..., settings_changes=..., flush=<optimized out>) at ./build_docker/./src/Storages/StorageDistributed.cpp:1764
2024-11-25 22:26:56 #9  0x00005618fbeb9120 in DB::StorageDistributed::flushAndPrepareForShutdown (this=0x519000270ba0) at ./build_docker/./src/Storages/StorageDistributed.cpp:1711
2024-11-25 22:26:56 #10 0x00005618f7147799 in DB::DatabaseWithOwnTablesBase::shutdown (this=<optimized out>) at ./build_docker/./src/Databases/DatabasesCommon.cpp:452
2024-11-25 22:26:56 #11 0x00005618f7ea4308 in DB::DatabaseCatalog::shutdownImpl (this=0x51d00005a080) at ./build_docker/./src/Interpreters/DatabaseCatalog.cpp:281
2024-11-25 22:26:56 #12 0x00005618f7ced0f8 in DB::ContextSharedPart::shutdown (this=0x5210002a8100) at ./build_docker/./src/Interpreters/Context.cpp:744
2024-11-25 22:26:56 #13 0x00005618e9960f55 in DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)::$_2::operator()() const (this=0x7ffdd888d770) at ./build_docker/./programs/server/Server.cpp:1085

2024-11-25 22:26:51 Thread 291 (Thread 0x7f0a06f0a640 (LWP 35698) "BgDistSchPool"):
2024-11-25 22:26:51 #0  0x00007f0d9c44381c in read () from /lib/x86_64-linux-gnu/libc.so.6
2024-11-25 22:26:51 #1  0x00005618d8cd0066 in __interceptor_read ()
2024-11-25 22:26:51 #2  0x0000561909deba9e in sock_read (b=0x50d0005adae0, out=0x52900028f203 "\027\003\003\005\323\001", outl=5) at ./build_docker/./contrib/openssl/crypto/bio/bss_sock.c:127
2024-11-25 22:26:51 #3  0x0000561909dd7109 in bread_conv (bio=0x4b, data=0x52900028f203 "\027\003\003\005\323\001", datal=5, readbytes=0x7f0a04935960) at ./build_docker/./contrib/openssl/crypto/bio/bio_meth.c:121
2024-11-25 22:26:51 #4  0x0000561909dd352f in bio_read_intern (b=0x4b, b@entry=0x50d0005adae0, data=0x52900028f203, dlen=0, readbytes=0x7f0d9c44381c <read+76>, readbytes@entry=0x7f0a04935960) at ./build_docker/./contrib/openssl/crypto/bio/bio_lib.c:285
2024-11-25 22:26:51 #5  0x0000561909dd3292 in BIO_read (b=<optimized out>, data=<optimized out>, dlen=<optimized out>) at ./build_docker/./contrib/openssl/crypto/bio/bio_lib.c:311
2024-11-25 22:26:51 #6  0x0000561909d4dff3 in tls_default_read_n (rl=0x52100005f100, n=5, max=5, extend=<optimized out>, clearold=<optimized out>, readbytes=0x7f0a04aff220) at ./build_docker/./contrib/openssl/ssl/record/methods/tls_common.c:406
2024-11-25 22:26:51 #7  0x0000561909d4e7cc in tls_get_more_records (rl=0x52100005f100) at ./build_docker/./contrib/openssl/ssl/record/methods/tls_common.c:583
2024-11-25 22:26:51 #8  0x0000561909d50dac in tls_read_record (rl=0x52100005f100, rechandle=0x522001a64d80, rversion=0x522001a64d88, type=0x522001a64d8c "\027", data=0x522001a64d90, datalen=0x522001a64da0, epoch=0x0, seq_num=0x0) at ./build_docker/./contrib/openssl/ssl/record/methods/tls_common.c:1130
2024-11-25 22:26:51 #9  0x0000561909d4443e in ssl3_read_bytes (ssl=0x522001a64100, type=23 '\027', recvd_type=0x0, buf=0x7f0908913800 "\001", len=1048576, peek=0, readbytes=0x7f0a04935920) at ./build_docker/./contrib/openssl/ssl/record/rec_layer_s3.c:689
2024-11-25 22:26:51 #10 0x0000561909c949b8 in ssl3_read_internal (s=0x522001a64100, buf=0x7f0908913800, len=1048576, peek=0, readbytes=<optimized out>) at ./build_docker/./contrib/openssl/ssl/s3_lib.c:4528
2024-11-25 22:26:51 #11 0x0000561909cb027c in ssl_read_internal (s=0x522001a64100, buf=<optimized out>, num=<optimized out>, readbytes=<optimized out>) at ./build_docker/./contrib/openssl/ssl/ssl_lib.c:2314
2024-11-25 22:26:51 #12 0x0000561909cb0b52 in SSL_read (s=<optimized out>, buf=<optimized out>, num=<optimized out>) at ./build_docker/./contrib/openssl/ssl/ssl_lib.c:2328
2024-11-25 22:26:51 #13 0x0000561904e7355b in Poco::Net::SecureSocketImpl::receiveBytes (this=0x50f000947c58, buffer=<optimized out>, length=<optimized out>, flags=<optimized out>) at ./build_docker/./base/poco/NetSSL_OpenSSL/src/SecureSocketImpl.cpp:356
2024-11-25 22:26:51 #14 0x00005618e98860f4 in DB::ReadBufferFromPocoSocketBase::socketReceiveBytesImpl (this=<optimized out>, ptr=<optimized out>, size=<optimized out>) at ./build_docker/./src/IO/ReadBufferFromPocoSocket.cpp:78
2024-11-25 22:26:51 #15 0x00005618e9887884 in DB::ReadBufferFromPocoSocketBase::nextImpl (this=0x5110009ff158) at ./build_docker/./src/IO/ReadBufferFromPocoSocket.cpp:107
2024-11-25 22:26:51 #16 0x00005618fd739b36 in DB::ReadBufferFromPocoSocketChunked::nextImpl (this=0x5110009ff158) at ./build_docker/./src/IO/ReadBufferFromPocoSocketChunked.cpp:103
2024-11-25 22:26:51 #17 0x00005618d9027a6b in DB::ReadBuffer::next() ()
2024-11-25 22:26:51 #18 0x00005618e967608a in DB::ReadBuffer::eof (this=0x5110009ff158) at ./src/IO/ReadBuffer.h:106
2024-11-25 22:26:51 #19 DB::varint_impl::readVarUInt<true> (x=@0x7f0a04caccd0: 0, istr=...) at ./src/IO/VarInt.h:95
2024-11-25 22:26:51 #20 0x00005618fd72c41a in DB::readVarUInt (x=@0x7f0a04caccd0: 0, istr=...) at ./src/IO/VarInt.h:114
2024-11-25 22:26:51 #21 DB::Connection::receivePacket (this=<optimized out>) at ./build_docker/./src/Client/Connection.cpp:1210
2024-11-25 22:26:51 #22 0x00005618fc97f57d in DB::RemoteInserter::onFinish (this=0x7f0a04f38960) at ./build_docker/./src/QueryPipeline/RemoteInserter.cpp:133
2024-11-25 22:26:51 #23 0x00005618fc967cd8 in DB::DistributedAsyncInsertDirectoryQueue::processFile (this=<optimized out>, file_path=..., settings_changes=...) at ./build_docker/./src/Storages/Distributed/DistributedAsyncInsertDirectoryQueue.cpp:449
2024-11-25 22:26:51 #24 0x00005618fc95e676 in DB::DistributedAsyncInsertDirectoryQueue::processFiles (this=0x5170003a1100, settings_changes=...) at ./build_docker/./src/Storages/Distributed/DistributedAsyncInsertDirectoryQueue.cpp:395
2024-11-25 22:26:51 #25 0x00005618fc95f2f2 in DB::DistributedAsyncInsertDirectoryQueue::run (this=0x5170003a1100) at ./build_docker/./src/Storages/Distributed/DistributedAsyncInsertDirectoryQueue.cpp:215
2024-11-25 22:26:51 #26 0x00005618f6572c8f in std::__1::__function::__policy_func<void ()>::operator()[abi:v15007]() const (this=0x4b) at ./contrib/llvm-project/libcxx/include/__functional/function.h:848
2024-11-25 22:26:51 #27 std::__1::function<void()>::operator() (this=0x4b) at ./contrib/llvm-project/libcxx/include/__functional/function.h:1197
2024-11-25 22:26:51 #28 DB::BackgroundSchedulePoolTaskInfo::execute (this=0x511000ba6498) at ./build_docker/./src/Core/BackgroundSchedulePool.cpp:106
```

</details>

**Comment by azat** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/71406/9534a35696d8a82182d59ed24e4a604d7d11adcd/stress_test__tsan_.html

**Comment by cangyin** [comment]
> proxy system tables to cloud.

Sounds advanced ! Is that a cloud-only feature ?

**Comment by azat** [comment]
>Sounds advanced ! Is that a cloud-only feature ?

No, it is just MV + Distributed tables that send data to another ClickHouse

**Comment by Algunenano** [comment]
This is still happening: https://s3.amazonaws.com/clickhouse-test-reports/75543/6294bb2c41b65d9da58a24aecb4e3bf6f064aa29/stress_test__ubsan_.html

<details>

<summary>The stress tests do no finish shutting down because of distributed async insert</summary>

Main thread:

```
2025-02-05 02:03:13 Thread 1 (Thread 0x7f7645107480 (LWP 61292) "clickhouse-serv"):
2025-02-05 02:03:13 #0  0x00007f76452882c0 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
2025-02-05 02:03:13 #1  0x00007f764528f002 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libc.so.6
2025-02-05 02:03:13 #2  0x000055e759c1107f in pthread_mutex_lock (arg=0x7f74cc01faa8) at ./build_docker/./src/Common/ThreadFuzzer.cpp:446
2025-02-05 02:03:13 #3  0x000055e770231869 in std::__1::__libcpp_mutex_lock[abi:ne180100](pthread_mutex_t*) (__m=0x7f74cc01faa8) at ./contrib/llvm-project/libcxx/include/__threading_support:280
2025-02-05 02:03:13 #4  std::__1::mutex::lock (this=0x7f74cc01faa8) at ./build_docker/./contrib/llvm-project/libcxx/src/mutex.cpp:29
2025-02-05 02:03:13 #5  0x000055e76484afa2 in std::__1::lock_guard<std::__1::mutex>::lock_guard[abi:ne180100](std::__1::mutex&) (this=0x7ffdb5214280, __m=...) at ./contrib/llvm-project/libcxx/include/__mutex/lock_guard.h:35
2025-02-05 02:03:13 #6  DB::BackgroundSchedulePoolTaskInfo::deactivate (this=0x7f74cc01fa58) at ./build_docker/./src/Core/BackgroundSchedulePool.cpp:51
2025-02-05 02:03:13 #7  0x000055e768b830b1 in DB::StorageDistributed::flushClusterNodesAllDataImpl (this=this@entry=0x7f749c122780, local_context=..., settings_changes=..., flush=<optimized out>) at ./build_docker/./src/Storages/StorageDistributed.cpp:1772
2025-02-05 02:03:13 #8  0x000055e768b82207 in DB::StorageDistributed::flushAndPrepareForShutdown (this=0x7f749c122780) at ./build_docker/./src/Storages/StorageDistributed.cpp:1719
2025-02-05 02:03:13 #9  0x000055e764f4f2b1 in DB::DatabaseWithOwnTablesBase::shutdown (this=0x55e77ef825c8) at ./build_docker/./src/Databases/DatabasesCommon.cpp:459
2025-02-05 02:03:13 #10 0x000055e76586938e in DB::DatabaseCatalog::shutdownImpl (this=0x55e77c8315c0) at ./build_docker/./src/Interpreters/DatabaseCatalog.cpp:277
2025-02-05 02:03:13 #11 0x000055e765737fa8 in DB::ContextSharedPart::shutdown (this=0x55e77c82a500) at ./build_docker/./src/Interpreters/Context.cpp:758
2025-02-05 02:03:13 #12 0x000055e759fb8f61 in DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)::$_3::operator()() const (this=this@entry=0x7ffdb5215f00) at ./build_docker/./programs/server/Server.cpp:1131
2025-02-05 02:03:13 #13 0x000055e759f9b913 in BasicScopeGuard<DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)::$_3>::invoke (this=0x7ffdb5215f00) at ./base/base/../base/scope_guard.h:101
2025-02-05 02:03:13 #14 BasicScopeGuard<DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)::$_3>::~BasicScopeGuard (this=0x7ffdb5215f00) at ./base/base/../base/scope_guard.h:50
2025-02-05 02:03:13 #15 DB::Server::main (this=0x7ffdb52175f8) at ./build_docker/./programs/server/Server.cpp:2619
2025-02-05 02:03:13 #16 0x000055e76e11b53b in Poco::Util::Application::run (this=0x7ffdb52175f8) at ./build_docker/./base/poco/Util/src/Application.cpp:315
2025-02-05 02:03:13 #17 0x000055e759f76533 in DB::Server::run (this=0x7ffdb52175f8) at ./build_docker/./programs/server/Server.cpp:563
2025-02-05 02:03:13 #18 0x000055e759f72f1d in mainEntryClickHouseServer (argc=6, argv=0x55e77bf267a0) at ./build_docker/./programs/server/Server.cpp:361
2025-02-05 02:03:13 #19 0x000055e74cd57a48 in main (argc_=<optimized out>, argv_=<optimized out>) at ./build_docker/./programs/main.cpp:294
2025-02-05 02:03:13 [Inferior 1 (process 61292) detached]
```

Looking for `0x7f74cc01fa58`:
```
2025-02-05 02:03:07 Thread 310 (Thread 0x7f7248e51640 (LWP 61854) "BgDistSchPool"):
2025-02-05 02:03:07 #0  0x00007f764530fbcf in poll () from /lib/x86_64-linux-gnu/libc.so.6
2025-02-05 02:03:07 #1  0x000055e76e0c7095 in Poco::Net::SocketImpl::pollImpl (this=<optimized out>, remainingTime=..., mode=<optimized out>) at ./build_docker/./base/poco/Net/src/SocketImpl.cpp:437
2025-02-05 02:03:07 #2  0x000055e76e0f915e in Poco::Net::SecureSocketImpl::mustRetry (this=this@entry=0x7f73e400ba88, rc=rc@entry=-1, remaining_time=...) at ./build_docker/./base/poco/NetSSL_OpenSSL/src/SecureSocketImpl.cpp:497
2025-02-05 02:03:07 #3  0x000055e76e0fb794 in Poco::Net::SecureSocketImpl::receiveBytes (this=0x7f73e400ba88, buffer=0x7f73e4120910, length=1048576, flags=0) at ./build_docker/./base/poco/NetSSL_OpenSSL/src/SecureSocketImpl.cpp:358
2025-02-05 02:03:07 #4  0x000055e759dab362 in DB::ReadBufferFromPocoSocketBase::socketReceiveBytesImpl (this=this@entry=0x7f73e4012ed8, ptr=0x7f73e4120910 "\316\b\003\305\033\001\220I\004\252\004\v\201\004\001S", size=1048576) at ./build_docker/./src/IO/ReadBufferFromPocoSocket.cpp:78
2025-02-05 02:03:07 #5  0x000055e759dad3b5 in DB::ReadBufferFromPocoSocketBase::nextImpl (this=0x7f73e4012ed8) at ./build_docker/./src/IO/ReadBufferFromPocoSocket.cpp:107
2025-02-05 02:03:07 #6  0x000055e74cf30992 in DB::ReadBuffer::next() ()
2025-02-05 02:03:07 #7  0x000055e769c248d2 in DB::ReadBuffer::eof (this=0x7f73e4012ed8) at ./src/IO/ReadBuffer.h:103
2025-02-05 02:03:07 #8  DB::varint_impl::readVarUInt<true> (x=@0x7f7248e48df0: 0, istr=...) at ./src/IO/VarInt.h:77
2025-02-05 02:03:07 #9  DB::readVarUInt (x=@0x7f7248e48df0: 0, istr=...) at ./src/IO/VarInt.h:96
2025-02-05 02:03:07 #10 DB::Connection::receivePacket (this=0x7f73e4017758) at ./build_docker/./src/Client/Connection.cpp:1256
2025-02-05 02:03:07 #11 0x000055e769244b74 in DB::RemoteInserter::onFinish (this=0x7f7248e495b0) at ./build_docker/./src/QueryPipeline/RemoteInserter.cpp:133
2025-02-05 02:03:07 #12 0x000055e7692355ec in DB::DistributedAsyncInsertDirectoryQueue::processFile (this=this@entry=0x7f74cc01e050, file_path=..., settings_changes=...) at ./build_docker/./src/Storages/Distributed/DistributedAsyncInsertDirectoryQueue.cpp:450
2025-02-05 02:03:07 #13 0x000055e76922e8ac in DB::DistributedAsyncInsertDirectoryQueue::processFiles (this=this@entry=0x7f74cc01e050, force=<optimized out>, settings_changes=...) at ./build_docker/./src/Storages/Distributed/DistributedAsyncInsertDirectoryQueue.cpp:396
2025-02-05 02:03:07 #14 0x000055e76922ef59 in DB::DistributedAsyncInsertDirectoryQueue::run (this=0x7f74cc01e050) at ./build_docker/./src/Storages/Distributed/DistributedAsyncInsertDirectoryQueue.cpp:216
2025-02-05 02:03:07 #15 0x000055e76484b44c in std::__1::__function::__policy_func<void ()>::operator()[abi:ne180100]() const (this=0x7f7248e488e8) at ./contrib/llvm-project/libcxx/include/__functional/function.h:714
2025-02-05 02:03:07 #16 std::__1::function<void()>::operator() (this=0x7f7248e488e8) at ./contrib/llvm-project/libcxx/include/__functional/function.h:981
2025-02-05 02:03:07 #17 DB::BackgroundSchedulePoolTaskInfo::execute (this=0x7f74cc01fa58) at ./build_docker/./src/Core/BackgroundSchedulePool.cpp:106
2025-02-05 02:03:07 #18 0x000055e76484f4d7 in DB::BackgroundSchedulePool::threadFunction (this=this@entry=0x55e77cb9e990) at ./build_docker/./src/Core/BackgroundSchedulePool.cpp:304
2025-02-05 02:03:07 #19 0x000055e764850506 in DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1::operator()() const (this=<optimized out>) at ./build_docker/./src/Core/BackgroundSchedulePool.cpp:170
2025-02-05 02:03:07 #20 std::__1::__invoke[abi:ne180100]<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&) (__f=...) at ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:344
2025-02-05 02:03:07 #21 _ZNSt3__118__apply_tuple_implB8ne180100IRZN2DB22BackgroundSchedulePoolC1Em13StrongTypedefImN14CurrentMetrics9MetricTagEES6_PKcE3$_1RNS_5tupleIJEEETpTnmJEEEDcOT_OT0_NS_15__tuple_indicesIJXspT1_EEEE (__f=..., __t=...) at ./contrib/llvm-project/libcxx/include/tuple:1424
2025-02-05 02:03:07 #22 std::__1::apply[abi:ne180100]<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&, std::__1::tuple<>&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&, std::__1::tuple<>&) (__f=..., __t=...) at ./contrib/llvm-project/libcxx/include/tuple:1428
2025-02-05 02:03:07 #23 ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&&)::{lambda()#1}::operator()() (this=0x55e77ca6b530) at ./src/Common/ThreadPool.h:311
2025-02-05 02:03:07 #24 std::__1::__invoke[abi:ne180100]<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&&)::{lambda()#1}&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&&) (__f=...) at ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:344
2025-02-05 02:03:07 #25 std::__1::__invoke_void_return_wrapper<void, true>::__call[abi:ne180100]<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&&)::{lambda()#1}&>(ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&&)::{lambda()#1}&) (__args=...) at ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:419
2025-02-05 02:03:07 #26 std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&&)::{lambda()#1}, void ()>::operator()[abi:ne180100]() (this=0x55e77ca6b530) at ./contrib/llvm-project/libcxx/include/__functional/function.h:208
2025-02-05 02:03:07 #27 std::__1::__function::__policy_invoker<void ()>::__call_impl[abi:ne180100]<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&&)::{lambda()#1}, void ()> >(std::__1::__function::__policy_storage const*) (__buf=<optimized out>) at ./contrib/llvm-project/libcxx/include/__functional/function.h:608
2025-02-05 02:03:07 #28 0x000055e759ccbe38 in std::__1::__function::__policy_func<void ()>::operator()[abi:ne180100]() const (this=0x7f7248e49f20) at ./contrib/llvm-project/libcxx/include/__functional/function.h:714
2025-02-05 02:03:07 #29 std::__1::function<void()>::operator() (this=0x7f7248e49f20) at ./contrib/llvm-project/libcxx/include/__functional/function.h:981
2025-02-05 02:03:07 #30 ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::worker (this=0x55e77ca60330) at ./build_docker/./src/Common/ThreadPool.cpp:785
2025-02-05 02:03:07 #31 0x000055e759cd2f4a in std::__1::__invoke[abi:ne180100]<void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*, , void>(void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*&&) (__f=@0x55e77cb96418: (void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool * const)) 0x55e759ccb820 <ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::worker()>, __a0=@0x55e77cb96428: 0x55e77ca60330) at ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:312
2025-02-05 02:03:07 #32 std::__1::__thread_execute[abi:ne180100]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*, 2ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*>&, std::__1::__tuple_indices<2ul>) (__t=...) at ./contrib/llvm-project/libcxx/include/__thread/thread.h:193
2025-02-05 02:03:07 #33 std::__1::__thread_proxy[abi:ne180100]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*> >(void*) (__vp=0x55e77cb96410) at ./contrib/llvm-project/libcxx/include/__thread/thread.h:202
2025-02-05 02:03:07 #34 0x00007f764528bac3 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
2025-02-05 02:03:07 #35 0x00007f764531d850 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
```

And we can see related log messages before the server was killed:

```
2025.02.05 10:46:40.662333 [ 794 ] {0cc20da5-ada4-437f-ac9b-42599fdc089a::202502_1_26_5} <Information> system.asynchronous_metric_log (0cc20da5-ada4-437f-ac9b-42599fdc089a) (MergerMutator): Merged 6 parts: [202502_1_21_4, 202502_26_26_0] -> 202502_1_26_5
2025.02.05 10:46:40.662920 [ 794 ] {} <Debug> MemoryTracker: Background process (mutate/merge) peak memory usage: 6.25 MiB.
2025.02.05 10:46:40.689502 [ 731 ] {} <Debug> system.asynchronous_metric_log_sender.DistributedInsertQueue.default: Sending `/workspace/db/store/e9a/e9ad8afe-fcc0-4e00-b1a1-333452ae4038/shard1_replica1/25.bin` to kng4alm55c.us-east-2.aws.clickhouse-staging.com:9440 (1.35 thousand rows, 141.69 KiB bytes)
2025.02.05 10:46:41.039249 [ 739 ] {} <Trace> system.text_log_sender.DistributedInsertQueue.default: Finished processing `/workspace/db/store/0f6/0f610919-0153-42db-8579-848314a97f8c/shard1_replica1/37.bin` (took 1449 ms)
2025.02.05 10:46:41.039337 [ 739 ] {} <Trace> system.text_log_sender.DistributedInsertQueue.default/Bg: Execution took 1449 ms.
2025.02.05 10:47:03.079881 [ 169 ] {} <Fatal> Application: Child process was terminated by signal 6.
```

</details>

**Comment by azat** [comment]
@Algunenano nice catch, and the reason is...

```
2025.02.05 02:01:24.085990 [ 61296 ] {15689821-be89-4be4-b914-f371a77883e2} <Test> CancellationChecker: Added to set. query: SYSTEM STOP DISTRIBUTED SENDS, timeout: 60000 milliseconds
2025.02.05 02:01:24.105464 [ 61296 ] {15689821-be89-4be4-b914-f371a77883e2} <Error> executeQuery: Code: 722. DB::Exception: Waited job failed: Code: 696. DB::Exception: ... (CANNOT_SCHEDULE_TASK), Stack trace (when copying this message, always include the lines below):
```

I will fix it

_P.S. issues is not about CI issues, but just about implementing parallel table shutdown, so I would say it is a new feature request._
