### ISSUE TITLE
clickhouse-test script causes error on macos - NameError: name 'args' is not defined

### ISSUE THREAD

**Issue by ollidraese** [ClickHouse/ClickHouse#73310]
**Company or project name**
cribl.io

**Describe what's wrong**
Trying to contribute a bug fix PR to Clickhouse master, I want to run the `clickhouse-test` script to verify functionality locally. I am developing natively under macos . The `clickhouse-test` script, executed as explained in examples, throws an error that "args" is not defined. This seems to be caused by macos' process model.

`❯ tests/clickhouse-test 01428_hash_set_nan_key
Using queries from '/Users/olli/dev/ClickHouse/tests/queries' directory
Connecting to ClickHouse server... OK
Connected to server 25.1.1.1 @ a83402172bea2f9bc7d56bf24f38458bc3135325 issue-72877-formatDateTime
Found 1 parallel tests and 0 sequential tests
Process Process-3:
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/olli/dev/ClickHouse/tests/clickhouse-test", line 2626, in run_tests_process
    return run_tests_array(*args, **kwargs)
  File "/Users/olli/dev/ClickHouse/tests/clickhouse-test", line 2289, in run_tests_array
    OP_SQUARE_BRACKET = colored("[", args, attrs=["bold"])
NameError: name 'args' is not defined
Won't run stateful tests because test data wasn't loaded.
All tests have finished.`

**Does it reproduce on the most recent release?**
yes

**How to reproduce**

1. Current macos (15.x)
2. Any 3.x (tried with 3.9, 3.11) python runtime env
3. go into Clickhouse repo directory while `clickhouse-server` is running
4. Run test script like `tests/clickhouse-test 01428_hash_set_nan_key`

**Expected behavior**

Expected the `clickhouse-test` script also to work under macos.

**Error message and/or stacktrace**

Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/olli/dev/ClickHouse/tests/clickhouse-test", line 2626, in run_tests_process
    return run_tests_array(*args, **kwargs)
  File "/Users/olli/dev/ClickHouse/tests/clickhouse-test", line 2289, in run_tests_array
    OP_SQUARE_BRACKET = colored("[", args, attrs=["bold"])
NameError: name 'args' is not defined

**Comment by wxybear** [comment]
It seems that the clickhouse-test code has been modified recently. You can try to specify the `--no-parallel` to see if it works.

**Comment by ollidraese** [comment]
Yes, adding --no-parallel indeed is a workaround. Thx.

**Comment by nikitamikhaylov** [comment]
Have the same issue, haven't fixed yet.

**Comment by Algunenano** [comment]
I'm surprise this works on Linux. It's using a global variable that's not defined yet

**Comment by ollidraese** [comment]
macos process mode differs from linux (or windows) affecting vars like args:
https://github.com/pyinstaller/pyinstaller/issues/2322

**Comment by Algunenano** [comment]
We should justt pass parameters properly instead of relying on random Python behaviour.

**Comment by Algunenano** [comment]
It seems there are more issues with our code apart from `args`, like `server_died`

**Comment by fm4v** [comment]
Should be fixed by https://github.com/ClickHouse/ClickHouse/pull/73440
I've tested it on macos and linux with the 'spawn' start method, which reproduces the problem. Could someone validate it?

**Comment by ollidraese** [comment]
Verified that it is running fine on my macos (15.2) now without needing the `--no-parallel` option. Thx!
