### ISSUE TITLE
deadlock leading to unresponsive server

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#7383]
Server with 19.14.6 stopped accepting connections (both http & tcp).
The process is active and ports are opened.

The server has quite a lot of MV / Distributed errors and exceptions in logs (rather looks unrelated) 

gdb shows that there are 4081 threads working (so most probable server stopped to accepting connections due to reaching max_connection). 

3027 of threads are waiting for lock here
```
#6  unique_lock (__m=..., this=<synthetic pointer>) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/std_mutex.h:197
#7  DB::ProcessList::insert(std::string const&, DB::IAST const*, DB::Context&) () at /usr/src/debug/ClickHouse-19.14.6.12-stable/dbms/src/Interpreters/ProcessList.cpp:88
```

About ~500 more of threads are waiting for lock here:
```
#2  0x00000000076a4ec6 in lock_shared (this=0x924fc40 <libunwind::DwarfFDECache<libunwind::LocalAddressSpace>::_lock>) at /usr/src/debug/ClickHouse-19.14.6.12-stable/contrib/libunwind/src/RWMutex.hpp:63
#3  findFDE (pc=<optimized out>, mh=0) at /usr/src/debug/ClickHouse-19.14.6.12-stable/contrib/libunwind/src/UnwindCursor.hpp:139
#4  libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::setInfoBasedOnIPRegister (this=0x7f66331f2570, isReturnAddress=<optimized out>) at /usr/src/debug/ClickHouse-19.14.6.12-stable/contrib/libunwind/src/UnwindCursor.hpp:1897
#5  0x000000000769ed46 in step (this=0x7f66331f2570) at /usr/src/debug/ClickHouse-19.14.6.12-stable/contrib/libunwind/src/Registers.hpp:343
#6  step (this=0x7f66331f2570) at /usr/src/debug/ClickHouse-19.14.6.12-stable/contrib/libunwind/src/UnwindCursor.hpp:1960
#7  __unw_step (cursor=0x7f66331f2570) at /usr/src/debug/ClickHouse-19.14.6.12-stable/contrib/libunwind/src/libunwind.cpp:161
#8  0x000000000769ef0f in unw_backtrace (buffer=buffer@entry=0x7f66331f2700, size=size@entry=32) at /usr/src/debug/ClickHouse-19.14.6.12-stable/contrib/libunwind/src/libunwind.cpp:291
#9  0x0000000003353de0 in tryCapture (this=0x7f66331f26f0) at /usr/src/debug/ClickHouse-19.14.6.12-stable/dbms/src/Common/StackTrace.cpp:227
#10 StackTrace::StackTrace (this=0x7f66331f26f0) at /usr/src/debug/ClickHouse-19.14.6.12-stable/dbms/src/Common/StackTrace.cpp:190
```

I've followed thread 2037, it waits for lock here:
```
#7  DB::ProcessList::insert(std::string const&, DB::IAST const*, DB::Context&) () at /usr/src/debug/ClickHouse-19.14.6.12-stable/dbms/src/Interpreters/ProcessList.cpp:88
88	        std::unique_lock lock(mutex);
```

The mutex is owned by thread 3010 (LWP 56525), which has the following stacktrace
```
(gdb) backtrace
#0  0x00007f71cf6714ed in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007f71cf66e0e2 in pthread_rwlock_rdlock () from /lib64/libpthread.so.0
#2  0x00000000076a4ec6 in lock_shared (this=0x924fc40 <libunwind::DwarfFDECache<libunwind::LocalAddressSpace>::_lock>) at /usr/src/debug/ClickHouse-19.14.6.12-stable/contrib/libunwind/src/RWMutex.hpp:63
#3  findFDE (pc=<optimized out>, mh=0) at /usr/src/debug/ClickHouse-19.14.6.12-stable/contrib/libunwind/src/UnwindCursor.hpp:139
#4  libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::setInfoBasedOnIPRegister (this=0x7f385a94eb60, isReturnAddress=<optimized out>)
    at /usr/src/debug/ClickHouse-19.14.6.12-stable/contrib/libunwind/src/UnwindCursor.hpp:1897
#5  0x000000000769ed46 in step (this=0x7f385a94eb60) at /usr/src/debug/ClickHouse-19.14.6.12-stable/contrib/libunwind/src/Registers.hpp:343
#6  step (this=0x7f385a94eb60) at /usr/src/debug/ClickHouse-19.14.6.12-stable/contrib/libunwind/src/UnwindCursor.hpp:1960
#7  __unw_step (cursor=0x7f385a94eb60) at /usr/src/debug/ClickHouse-19.14.6.12-stable/contrib/libunwind/src/libunwind.cpp:161
#8  0x000000000769ef0f in unw_backtrace (buffer=buffer@entry=0x7f716801f370, size=size@entry=32) at /usr/src/debug/ClickHouse-19.14.6.12-stable/contrib/libunwind/src/libunwind.cpp:291
#9  0x0000000003353de0 in tryCapture (this=0x7f716801f360) at /usr/src/debug/ClickHouse-19.14.6.12-stable/dbms/src/Common/StackTrace.cpp:227
#10 StackTrace::StackTrace (this=0x7f716801f360) at /usr/src/debug/ClickHouse-19.14.6.12-stable/dbms/src/Common/StackTrace.cpp:190
#11 0x000000000335e0ff in DB::Exception::Exception (this=0x7f716801f340, msg=..., code=<optimized out>) at /usr/src/debug/ClickHouse-19.14.6.12-stable/dbms/src/Common/Exception.h:27
...

(gdb) frame 3
#3  findFDE (pc=<optimized out>, mh=0) at /usr/src/debug/ClickHouse-19.14.6.12-stable/contrib/libunwind/src/UnwindCursor.hpp:139
139	  _LIBUNWIND_LOG_IF_FALSE(_lock.lock_shared());
(gdb) p _lock
$6 = {_lock = {__data = {__lock = 2, __nr_readers = 1, __readers_wakeup = 0, __writer_wakeup = 0, __nr_readers_queued = 0, __nr_writers_queued = 0, __writer = 0, __shared = 0, __pad1 = 0, __pad2 = 0, 
      __flags = 0}, __size = "\002\000\000\000\001", '\000' <repeats 50 times>, __align = 4294967298}}
```
While looking what can keep a rw lock I've found those threads with suspicious backtraces: 
```

Thread 3603 (Thread 0x7f675934b700 (LWP 97404)):
#0  0x00007f71cf6714ed in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007f71cf66e0e2 in pthread_rwlock_rdlock () from /lib64/libpthread.so.0
#2  0x00000000076a4ec6 in lock_shared (this=0x924fc40 <libunwind::DwarfFDECache<libunwind::LocalAddressSpace>::_lock>) at /usr/src/debug/ClickHouse-19.14.6.12-stable/contrib/libunwind/src/RWMutex.hpp:63
#3  findFDE (pc=<optimized out>, mh=0) at /usr/src/debug/ClickHouse-19.14.6.12-stable/contrib/libunwind/src/UnwindCursor.hpp:139
#4  libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::setInfoBasedOnIPRegister (this=0x7f6759344f40, isReturnAddress=<optimized out>) at /usr/src/debug/ClickHouse-19.14.6.12-stable/contrib/libunwind/src/UnwindCursor.hpp:1897
#5  0x000000000769ed46 in step (this=0x7f6759344f40) at /usr/src/debug/ClickHouse-19.14.6.12-stable/contrib/libunwind/src/Registers.hpp:343
#6  step (this=0x7f6759344f40) at /usr/src/debug/ClickHouse-19.14.6.12-stable/contrib/libunwind/src/UnwindCursor.hpp:1960
#7  __unw_step (cursor=0x7f6759344f40) at /usr/src/debug/ClickHouse-19.14.6.12-stable/contrib/libunwind/src/libunwind.cpp:161
#8  0x000000000769ef0f in unw_backtrace (buffer=buffer@entry=0x7f6759345140, size=size@entry=32) at /usr/src/debug/ClickHouse-19.14.6.12-stable/contrib/libunwind/src/libunwind.cpp:291
#9  0x0000000003353e21 in tryCapture (this=0x7f6759345130) at /usr/src/debug/ClickHouse-19.14.6.12-stable/dbms/src/Common/StackTrace.cpp:227
#10 StackTrace::StackTrace (this=0x7f6759345130, signal_context=...) at /usr/src/debug/ClickHouse-19.14.6.12-stable/dbms/src/Common/StackTrace.cpp:195
#11 0x000000000336cea9 in DB::(anonymous namespace)::writeTraceInfo(DB::TimerType, int, siginfo_t*, void*) [clone .isra.16] () at /usr/src/debug/ClickHouse-19.14.6.12-stable/dbms/src/Common/QueryProfiler.cpp:70
#12 <signal handler called>
#13 0x00007f71cf6714eb in __lll_lock_wait () from /lib64/libpthread.so.0
#14 0x00007f71cf66cdcb in _L_lock_883 () from /lib64/libpthread.so.0
#15 0x00007f71cf66cc98 in pthread_mutex_lock () from /lib64/libpthread.so.0
#16 0x000000000649e2da in __gthread_mutex_lock (__mutex=0x7f70a4710ee8) at /opt/rh/devtoolset-8/root/usr/include/c++/8/x86_64-redhat-linux/bits/gthr-default.h:748
#17 lock (this=0x7f70a4710ee8) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/std_mutex.h:103
#18 lock_guard (__m=..., this=<synthetic pointer>) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/std_mutex.h:162
#19 DB::MergingAggregatedMemoryEfficientBlockInputStream::mergeThread(std::shared_ptr<DB::ThreadGroupStatus>) () at /usr/src/debug/ClickHouse-19.14.6.12-stable/dbms/src/DataStreams/MergingAggregatedMemoryEfficientBlockInputStream.cpp:322
#20 0x000000000649eeae in operator() (__closure=<optimized out>) at /opt/rh/devtoolset-8/root/usr/include/c++/8/ext/atomicity.h:96
#21 std::_Function_handler<void (), DB::MergingAggregatedMemoryEfficientBlockInputStream::start()::{lambda()#2}>::_M_invoke(std::_Any_data const&) () at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/std_function.h:297
#22 0x000000000338daa3 in operator() (this=0x7f67593462f0) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/std_function.h:260
#23 ThreadPoolImpl<ThreadFromGlobalPool>::worker (this=<optimized out>, thread_it=...) at /usr/src/debug/ClickHouse-19.14.6.12-stable/dbms/src/Common/ThreadPool.cpp:221
#24 0x000000000338f878 in _ZZN20ThreadFromGlobalPoolC4IZN14ThreadPoolImplIS_E12scheduleImplIvEET_St8functionIFvvEEiSt8optionalImEEUlvE1_JEEEOS4_DpOT0_ENKUlvE_clEv () at /usr/src/debug/ClickHouse-19.14.6.12-stable/dbms/src/Common/ThreadPool.h:147
#25 0x000000000338cb43 in operator() (this=0x7f67593465f0) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/std_function.h:260
#26 ThreadPoolImpl<std::thread>::worker (this=<optimized out>, thread_it=...) at /usr/src/debug/ClickHouse-19.14.6.12-stable/dbms/src/Common/ThreadPool.cpp:221
#27 0x000000000766d06f in execute_native_thread_routine ()
#28 0x00007f71cf66add5 in start_thread () from /lib64/libpthread.so.0
#29 0x00007f71cef8802d in clone () from /lib64/libc.so.6

....

Thread 3493 (Thread 0x7f392baf8700 (LWP 108896)):
#0  0x00007f71cf6714ed in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007f71cf66e0e2 in pthread_rwlock_rdlock () from /lib64/libpthread.so.0
#2  0x00000000076a4ec6 in lock_shared (this=0x924fc40 <libunwind::DwarfFDECache<libunwind::LocalAddressSpace>::_lock>) at /usr/src/debug/ClickHouse-19.14.6.12-stable/contrib/libunwind/src/RWMutex.hpp:63
#3  findFDE (pc=<optimized out>, mh=0) at /usr/src/debug/ClickHouse-19.14.6.12-stable/contrib/libunwind/src/UnwindCursor.hpp:139
#4  libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::setInfoBasedOnIPRegister (this=0x7f392baf0980, isReturnAddress=<optimized out>) at /usr/src/debug/ClickHouse-19.14.6.12-stable/contrib/libunwind/src/UnwindCursor.hpp:1897
#5  0x000000000769ed46 in step (this=0x7f392baf0980) at /usr/src/debug/ClickHouse-19.14.6.12-stable/contrib/libunwind/src/Registers.hpp:343
#6  step (this=0x7f392baf0980) at /usr/src/debug/ClickHouse-19.14.6.12-stable/contrib/libunwind/src/UnwindCursor.hpp:1960
#7  __unw_step (cursor=0x7f392baf0980) at /usr/src/debug/ClickHouse-19.14.6.12-stable/contrib/libunwind/src/libunwind.cpp:161
#8  0x000000000769ef0f in unw_backtrace (buffer=buffer@entry=0x7f392baf0b80, size=size@entry=32) at /usr/src/debug/ClickHouse-19.14.6.12-stable/contrib/libunwind/src/libunwind.cpp:291
#9  0x0000000003353e21 in tryCapture (this=0x7f392baf0b70) at /usr/src/debug/ClickHouse-19.14.6.12-stable/dbms/src/Common/StackTrace.cpp:227
#10 StackTrace::StackTrace (this=0x7f392baf0b70, signal_context=...) at /usr/src/debug/ClickHouse-19.14.6.12-stable/dbms/src/Common/StackTrace.cpp:195
#11 0x000000000336cea9 in DB::(anonymous namespace)::writeTraceInfo(DB::TimerType, int, siginfo_t*, void*) [clone .isra.16] () at /usr/src/debug/ClickHouse-19.14.6.12-stable/dbms/src/Common/QueryProfiler.cpp:70
#12 <signal handler called>
#13 0x00007f71cf66e0d1 in pthread_rwlock_rdlock () from /lib64/libpthread.so.0
#14 0x00000000076a4ec6 in lock_shared (this=0x924fc40 <libunwind::DwarfFDECache<libunwind::LocalAddressSpace>::_lock>) at /usr/src/debug/ClickHouse-19.14.6.12-stable/contrib/libunwind/src/RWMutex.hpp:63
#15 findFDE (pc=<optimized out>, mh=0) at /usr/src/debug/ClickHouse-19.14.6.12-stable/contrib/libunwind/src/UnwindCursor.hpp:139
#16 libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::setInfoBasedOnIPRegister (this=0x7f392baf1f40, isReturnAddress=<optimized out>) at /usr/src/debug/ClickHouse-19.14.6.12-stable/contrib/libunwind/src/UnwindCursor.hpp:1897
#17 0x000000000769ed46 in step (this=0x7f392baf1f40) at /usr/src/debug/ClickHouse-19.14.6.12-stable/contrib/libunwind/src/Registers.hpp:343
#18 step (this=0x7f392baf1f40) at /usr/src/debug/ClickHouse-19.14.6.12-stable/contrib/libunwind/src/UnwindCursor.hpp:1960
#19 __unw_step (cursor=0x7f392baf1f40) at /usr/src/debug/ClickHouse-19.14.6.12-stable/contrib/libunwind/src/libunwind.cpp:161
#20 0x000000000769ef0f in unw_backtrace (buffer=buffer@entry=0x7f392baf2140, size=size@entry=32) at /usr/src/debug/ClickHouse-19.14.6.12-stable/contrib/libunwind/src/libunwind.cpp:291
#21 0x0000000003353e21 in tryCapture (this=0x7f392baf2130) at /usr/src/debug/ClickHouse-19.14.6.12-stable/dbms/src/Common/StackTrace.cpp:227
#22 StackTrace::StackTrace (this=0x7f392baf2130, signal_context=...) at /usr/src/debug/ClickHouse-19.14.6.12-stable/dbms/src/Common/StackTrace.cpp:195
#23 0x000000000336cea9 in DB::(anonymous namespace)::writeTraceInfo(DB::TimerType, int, siginfo_t*, void*) [clone .isra.16] () at /usr/src/debug/ClickHouse-19.14.6.12-stable/dbms/src/Common/QueryProfiler.cpp:70
#24 <signal handler called>
#25 0x00007f71cf6714eb in __lll_lock_wait () from /lib64/libpthread.so.0
#26 0x00007f71cf66cdcb in _L_lock_883 () from /lib64/libpthread.so.0
#27 0x00007f71cf66cc98 in pthread_mutex_lock () from /lib64/libpthread.so.0
#28 0x000000000649e2da in __gthread_mutex_lock (__mutex=0x7f70e63eb4e8) at /opt/rh/devtoolset-8/root/usr/include/c++/8/x86_64-redhat-linux/bits/gthr-default.h:748
#29 lock (this=0x7f70e63eb4e8) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/std_mutex.h:103
#30 lock_guard (__m=..., this=<synthetic pointer>) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/std_mutex.h:162
#31 DB::MergingAggregatedMemoryEfficientBlockInputStream::mergeThread(std::shared_ptr<DB::ThreadGroupStatus>) () at /usr/src/debug/ClickHouse-19.14.6.12-stable/dbms/src/DataStreams/MergingAggregatedMemoryEfficientBlockInputStream.cpp:322
#32 0x000000000649eeae in operator() (__closure=<optimized out>) at /opt/rh/devtoolset-8/root/usr/include/c++/8/ext/atomicity.h:96
#33 std::_Function_handler<void (), DB::MergingAggregatedMemoryEfficientBlockInputStream::start()::{lambda()#2}>::_M_invoke(std::_Any_data const&) () at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/std_function.h:297
#34 0x000000000338daa3 in operator() (this=0x7f392baf32f0) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/std_function.h:260
#35 ThreadPoolImpl<ThreadFromGlobalPool>::worker (this=<optimized out>, thread_it=...) at /usr/src/debug/ClickHouse-19.14.6.12-stable/dbms/src/Common/ThreadPool.cpp:221
#36 0x000000000338f878 in _ZZN20ThreadFromGlobalPoolC4IZN14ThreadPoolImplIS_E12scheduleImplIvEET_St8functionIFvvEEiSt8optionalImEEUlvE1_JEEEOS4_DpOT0_ENKUlvE_clEv () at /usr/src/debug/ClickHouse-19.14.6.12-stable/dbms/src/Common/ThreadPool.h:147
#37 0x000000000338cb43 in operator() (this=0x7f392baf35f0) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/std_function.h:260
#38 ThreadPoolImpl<std::thread>::worker (this=<optimized out>, thread_it=...) at /usr/src/debug/ClickHouse-19.14.6.12-stable/dbms/src/Common/ThreadPool.cpp:221
#39 0x000000000766d06f in execute_native_thread_routine ()
#40 0x00007f71cf66add5 in start_thread () from /lib64/libpthread.so.0
#41 0x00007f71cef8802d in clone () from /lib64/libc.so.6
```
Both doing signal processing while keeping lock, which may be the potential reason for deadlock.
Some signal processing changes were introduced recently ( https://github.com/ClickHouse/ClickHouse/commit/f36d20915b6667f9089e066170225e52b270dd10#diff-1f307cce4cc43b590c8b9c2023ab213f ), so maybe somehow related. 

Full backtraces are attached:
[trace_log.tar.gz](https://github.com/ClickHouse/ClickHouse/files/3743881/trace_log.tar.gz)

**Comment by alexey-milovidov** [comment]
This task is assigned to @laplab
