### ISSUE TITLE
unexpected query result

### ISSUE THREAD

**Issue by Goodman1990** [ClickHouse/ClickHouse#8412]
[clickhouse.zip](https://github.com/ClickHouse/ClickHouse/files/4002536/clickhouse.zip)
(you don't have to strictly follow this form)

**Describe the bug or unexpected behaviour**
ZIP have Query. same query it works. Same not and have error.
And you cannot track the execution logic.

org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [43]: ClickHouse exception, code: 43, host: clickhouse.smapps.net, port: 8123; Code: 43, e.displayText() = DB::Exception: Argument 3 of function arrayFilter must be array. Found String instead. (version 19.15.3.6 (official build))

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:467)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:407)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:405)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:849)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2778)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:98)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:96)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 43, host: clickhouse.smapps.net, port: 8123; Code: 43, e.displayText() = DB::Exception: Argument 3 of function arrayFilter must be array. Found String instead. (version 19.15.3.6 (official build))

	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:58)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:28)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.checkForErrorAndThrow(ClickHouseStatementImpl.java:820)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.getInputStream(ClickHouseStatementImpl.java:616)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:127)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:110)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:105)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:100)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.execute(ClickHouseStatementImpl.java:236)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 11 more
Caused by: java.lang.Throwable: Code: 43, e.displayText() = DB::Exception: Argument 3 of function arrayFilter must be array. Found String instead. (version 19.15.3.6 (official build))

	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:53)
	... 21 more

**Comment by den-crane** [comment]
lamda arguments should not be named as columns, use i,j,x,y something
```

SELECT
	sum(payment_count_delta_1_1_1_2) as payment_delta_1_1_1_2_count1,
	sum(payment_amount_delta_1_1_1_2) as payment_delta_1_1_1_2_amount1
FROM(
	WITH groupArray(idx) as index,
	groupArray(timestamp) as event_time,
	groupArray(payments_cm_total_count) as payment_count,
	groupArray(payments_cm_total_amount) as payment_amount
	SELECT
		uniq(user_id) as count_users,
		arrayFilter(x, y -> (y = '1_1'), event_time, index)[1] as step_1,
		arrayFilter(x, y -> (y = '1_1'), payment_count,	index)[1] as payment_count_1,
		arrayFilter(x, y -> (y = '1_1'),payment_amount,	index)[1] as payment_amount_1,
		arrayFilter(x, y -> (y = '1_2')	AND (x >= step_1), event_time, index)[1] as step_2, minus(step_2,step_1) as delta_1_1_1_2, minus(payment_count_2,
		payment_count_1) as payment_count_delta_1_1_1_2,
		minus(payment_amount_2,
		payment_amount_1) as payment_amount_delta_1_1_1_2,
		arrayFilter(x,
		y -> (y = '1_2')
		AND (x >= payment_count_1),
		payment_count,
		index)[1] as payment_count_2,
		arrayFilter(x,
		y -> (y = '1_2')
		AND (x >= payment_amount_1),
		payment_amount,
		index)[1] as payment_amount_2
	FROM
		(
			SELECT user_id,	timestamp,
			payments_cm_total_count,
			payments_cm_total_amount,
			tracker_level_update_test_general_test_14_params_level_id_new as level_id_new,
			tracker_level_update_test_general_test_14_params_episode_id_new as episode_id_new,
			concat(toString(episode_id_new), '_', toString(level_id_new)) as idx
	   	FROM
			bottle_stage.tracker_new
			where
		(name ='level_update_test_general_test_14')
		AND (net_id ='cm')
		AND (date BETWEEN '2019-07-01' AND '2019-07-01')
		AND (level_id_new > 0)
		AND (episode_id_new > 0)
		AND (episode_id_new BETWEEN 0 AND 12))
	GROUP BY
		user_id)

┌─payment_delta_1_1_1_2_count1─┬─payment_delta_1_1_1_2_amount1─┐
│                            2 │                            20 │
└──────────────────────────────┴───────────────────────────────┘
```

**Comment by den-crane** [comment]
duplicate for https://github.com/ClickHouse/ClickHouse/issues/5046
