### ISSUE TITLE
not expected request behavior 

### ISSUE THREAD

**Issue by Goodman1990** [ClickHouse/ClickHouse#8937]
[clickhouse_error_pack.zip](https://github.com/ClickHouse/ClickHouse/files/4140246/clickhouse_erro_pack.zip)

**Describe the bug or unexpected behaviour**
I don’t understand why the subquery works. But the main query gives a strange error. All data is in the archive above.
**How to reproduce**
* execute all query in the archive.

**Error message**
SQL Error [42]: ClickHouse exception, code: 42, host: clickhouse.smapps.net, port: 8123; Code: 42, e.displayText() = DB::Exception: Aggregate function count requires zero or one argument (version 19.17.7.52 (official build))

**Stacktrace**
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [42]: ClickHouse exception, code: 42, host: clickhouse.smapps.net, port: 8123; Code: 42, e.displayText() = DB::Exception: Aggregate function count requires zero or one argument (version 19.17.7.52 (official build))

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:480)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:419)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:152)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:411)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:781)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2859)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:99)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:152)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:97)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3431)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 42, host: clickhouse.smapps.net, port: 8123; Code: 42, e.displayText() = DB::Exception: Aggregate function count requires zero or one argument (version 19.17.7.52 (official build))

	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:58)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:28)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.checkForErrorAndThrow(ClickHouseStatementImpl.java:875)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.getInputStream(ClickHouseStatementImpl.java:616)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:117)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:100)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:95)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:90)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.execute(ClickHouseStatementImpl.java:226)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 12 more
Caused by: java.lang.Throwable: Code: 42, e.displayText() = DB::Exception: Aggregate function count requires zero or one argument (version 19.17.7.52 (official build))

	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:53)
	... 22 more

**Comment by den-crane** [comment]
duplicate for https://github.com/ClickHouse/ClickHouse/issues/8412

lamda arguments should not be named as columns, use i,j,x,y something

```
SELECT
    countIf(delta_1_1_1_2 > 604800) AS count_delta_1_1_1_2,
    countIf(delta_1_2_1_3 > 604800) AS count_delta_1_2_1_3,
    countIf(delta_1_3_1_4 > 604800) AS count_delta_1_3_1_4,
    countIf(delta_1_4_1_5 > 604800) AS count_delta_1_4_1_5,
    countIf(delta_1_5_2_1 > 604800) AS count_delta_1_5_2_1,
    countIf(delta_2_1_2_2 > 604800) AS count_delta_2_1_2_2,
    countIf(delta_2_2_2_3 > 604800) AS count_delta_2_2_2_3,
    countIf(delta_2_3_2_4 > 604800) AS count_delta_2_3_2_4,
    countIf(delta_2_4_2_5 > 604800) AS count_delta_2_4_2_5
FROM
(
    WITH
        groupArray(idx) AS index,
        groupArray(timestamp) AS event_time
    SELECT
        uniq(user_id) AS count_users,
        arrayFilter((t, i) -> (i = '1_1'), event_time, index)[1] AS step_1,
        arrayFilter((t, i) -> ((i = '1_2') AND (t >= step_1)), event_time, index)[1] AS step_2,
        step_2 - step_1 AS delta_1_1_1_2,
        arrayFilter((t, i) -> ((i = '1_3') AND (t >= step_2)), event_time, index)[1] AS step_3,
        step_3 - step_2 AS delta_1_2_1_3,
        arrayFilter((t, i) -> ((i = '1_4') AND (t >= step_3)), event_time, index)[1] AS step_4,
        step_4 - step_3 AS delta_1_3_1_4,
        arrayFilter((t, i) -> ((i = '1_5') AND (t >= step_4)), event_time, index)[1] AS step_5,
        step_5 - step_4 AS delta_1_4_1_5,
        arrayFilter((t, i) -> ((i = '2_1') AND (t >= step_5)), event_time, index)[1] AS step_6,
        step_6 - step_5 AS delta_1_5_2_1,
        arrayFilter((t, i) -> ((i = '2_2') AND (t >= step_6)), event_time, index)[1] AS step_7,
        step_7 - step_6 AS delta_2_1_2_2,
        arrayFilter((t, i) -> ((i = '2_3') AND (t >= step_7)), event_time, index)[1] AS step_8,
        step_8 - step_7 AS delta_2_2_2_3,
        arrayFilter((t, i) -> ((i = '2_4') AND (t >= step_8)), event_time, index)[1] AS step_9,
        step_9 - step_8 AS delta_2_3_2_4,
        arrayFilter((t, i) -> ((i = '2_5') AND (t >= step_9)), event_time, index)[1] AS step_10,
        step_10 - step_9 AS delta_2_4_2_5
    FROM
    (
        SELECT
            user_id,
            timestamp,
            payments_cm_total_count,
            payments_cm_total_amount,
            tracker_level_update_test_general_params_level_id_new AS level_id_new,
            tracker_level_update_test_general_params_episode_id_new AS episode_id_new,
            concat(toString(episode_id_new), '_', toString(level_id_new)) AS idx
        FROM tracker_test
        WHERE (name = 'level_update_test_general') AND (net_id = 'cm') AND ((date >= '2020-01-01') AND (date <= '2020-01-20')) AND (level_id_new > 0) AND (episode_id_new > 0) AND ((episode_id_new >= 1) AND (episode_id_new <= 6))
    )
    GROUP BY user_id
)

┌─count_delta_1_1_1_2─┬─count_delta_1_2_1_3─┬─count_delta_1_3_1_4─┬─count_delta_1_4_1_5─┬─count_delta_1_5_2_1─┬─count_delta_2_1_2_2─┬─count_delta_2_2_2_3─┬─count_delta_2_3_2_4─┬─count_delta_2_4_2_5─┐
│                   0 │                   0 │                   0 │                   0 │                   0 │                   0 │                   0 │                   0 │                   0 │
└─────────────────────┴─────────────────────┴─────────────────────┴─────────────────────┴─────────────────────┴─────────────────────┴─────────────────────┴─────────────────────┴─────────────────────┘
```
