### ISSUE TITLE
Broken documentation link

### ISSUE THREAD

**Issue by FedericoCeratto** [ClickHouse/ClickHouse#9911]
https://clickhouse.tech/docs/v19.8/en/single/ is currently returning the following error:

```Traceback (most recent call last):
  File "/place/sandbox-data/tasks/1/4/636723341/ClickHouse/docs/tools/venv/lib/python3.7/site-packages/macros/plugin.py", line 261, in render
    md_template = self.env.from_string(markdown)
  File "/place/sandbox-data/tasks/1/4/636723341/ClickHouse/docs/tools/venv/lib/python3.7/site-packages/jinja2/environment.py", line 941, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/place/sandbox-data/tasks/1/4/636723341/ClickHouse/docs/tools/venv/lib/python3.7/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/place/sandbox-data/tasks/1/4/636723341/ClickHouse/docs/tools/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/place/sandbox-data/tasks/1/4/636723341/ClickHouse/docs/tools/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 11022, in template
jinja2.exceptions.TemplateSyntaxError: unexpected char '`' at 530061```

**Comment by blinkov** [comment]
@FedericoCeratto thx for reporting, it'll be fixed soon with #9874
